* 第XXI章 神在祂永恆的揀選中預定一些人蒙救恩，也預定其他人受滅亡！

** 明白预定論的人不會任意妄為，也不會不敢教導這教義(1-4)
*** 1神揀選的必要性和它所帶來的益處；對此教義好奇的危險？
　　實際上，生命的約並不是傳給所有的人，且聽到這信息的人也不都會有同樣的反應，而這不同的反應彰顯神深奧的智慧，這差別就證明神永恆的揀選。然而，若神只將救恩提供給一些人，而其他的人沒有得救的機會，是完全根據祂的美意，我們立刻就必須面對既大又難回答的問題。然而，只有當我們(敬虔的人)堅定相信神的揀選和預定，我們才能回答這些問題。對許多人而言，這是令人感到迷惑的問題，因他們認為在全人類當中，神預定一些人得救，卻預定其他人滅亡，這是互相矛盾的，然而我們下面就能看清他們在這教義上錯誤的辯論。此外，雖然這教義使他們感到迷惑，但我們卻能看見這教義的大功用，也能看見它所結的美妙果子。除非我們先了解神永恆的揀選，否則我們無法確信，就像我們應當確信那般。我們的救恩是出於神白白的憐憫，神的揀選以這對比光照祂的恩典：神並沒有將救恩的盼望賜給所有的人，而是只賜給一些人並拒絕其他的人。

　　對這教義無知並竊取神的榮耀和攔阻人自卑是眾所周知的。但保羅告訴我們，雖然人很需要知道這教義，但除非神完全在人的行為之外揀選人，否則人無法明白。保羅說：「如今也是這樣，照著揀選的恩典，還有所留的餘數。既是出於恩典，就不在乎行為；不然，恩典就不是恩典了。」(羅一一5-6)既然為了證明救恩完全出於神的憐憫，我們必須重新思考神的揀選，所以，那些拒絶相信這教義的人，是在竭力、惡劣地抹去人應當引以為榮和大聲宣告地教義，也同時在拔除謙卑。保羅清楚的教導當聖經說神所留的餘數，是照著揀選的恩典時，我們才明白神出於祂自己的美意，拯救祂所喜悅的人，而且這不是祂所欠人的債，因神不可能欠人什麼。

　　那些故意不給別人機會聽到這教義的人，不但得罪神，也是得罪人。因除此教義外，沒有任何事物能使我們謙卑，或讓我們深深地感受到我們有多虧欠神。並且就如基督所教導的那般，這也是確據的唯一根基。基督應許父神所交託祂看管的一切必定安全(約一O28-29)，是要我們在許多的危險、陷阱和威脅我們性命的爭戰中不致於懼怕，反而至終得勝。我們以此推論，一切不曉得自己是否屬神的人，不但在懼怕中也是悲慘的。因此，那些因對我們以上所列舉的三種福分，盲目而企圖拆毀我們救恩根基的人，不但害眾信徒，也害自己。難道揀選這教義不就是教會的源頭嗎？伯爾拿正確地教導：「教會的源頭不可能來自任何受造物，因神將這源頭隱藏在祂預定得永生和預定受滅亡的人中。」
但在我開始討論這教義之前，我要先描述兩種人 也對我們有幫助。
人的好奇使預定論這難明白的教義變得很模糊，甚至危險。沒有人能約束這好奇心，探究神所禁止的範圍，或有關神，但人卻不該問的事。若被許可，人的好奇也將設法探究神最大的奧祕。當我們看到許多在其他方面敬虔的人，卻到處迫不及待忙著這大膽、邪惡的事，我們必須提醒他們，神在這事上所要人盡的本分。
首先，他們應當牢記當他們出於好奇詢問關於預定論的事，就是在擅闖神智慧的至聖所。若任何人擅自闖入，他的好奇心絕得不到滿足，反而就如誤入找不到出口的迷宮。因神不許人毫不節制地詢問祂喜悅隱藏在自己裡面的事物，也不許我們擅自描述祂永恆至高的智慧。神要我們敬畏這智慧，卻不喜悅我們詳細探究祂不算向我們啟示的，因祂也要我們在這事上相信祂是奧妙的。神已在祂的話語上啟示祂喜悅我們明白關於祂美意的奧祕。祂決定向我們啟示這些奧祕，因祂知道這些奧祕與我們有關，也對我們有幫助。

*** 2唯有聖經教導預定論
　　奧古斯丁說：「我們既然已經上了信心的道路，就當在這道路上堅忍到底。這道路引領我們到君王的寶庫，在那裡藏著一切智慧和知識。當主基督告訴祂揀選的偉大門徒：『我還有好些事要告訴你們，但你們現在擔當不了』(約一六12)時，祂並不是輕看他們。我們必須行走、必須前進、必須成長，好讓自己的心之後能明白我們現在無法測透的事。在最後之日前夕，我們若仍有不明白的，到了最後之日我們將明白。」只要我們確信唯有神的道才能引領我們明白一切神許可我們知道關於基督的事，以及這道是唯一光照我們認識基督的亮光，這就會保守我們避免一切的輕率。如此我們就會知道自己一旦離開神話語的範圍，就行走在黑暗中，也必在這黑暗中摸索、滑倒。我們應當牢記這真理：我們若尋求任何在神真道之外關於預定論的知識是荒謬的，就如人決定在荒廢、無路之地飄流(cf.伯一二24)，或確信自己在黑暗中能看見一樣荒謬。我們也無須因對這事無知為恥，因這也算是我們的智慧。我們反而要自願約束自己想獲得這種知識，因為這樣的私慾既愚昧又危險，甚至是致命的。但我們若被某種放蕩的好奇心所攪擾，就當用這思想約束自己：就如吃蜜過多是不好的，同樣地，考究神的榮耀不是我們的榮耀(箴二五27，cf.Vg.)。我們有極好的理由遠離這樣的任意妄為，因為至終它只會使我們滅亡。

*** 3第二種人：因過分謹慎而閉口不談揀選的教義
　　又有一些人為了避免過分好奇的罪，幾乎連提都不提到預定論；事實上，他們教導人避免討論這教義就如航行的船盡量避免觸礁一般雖然他們在這事上的節制應得稱讚，因深信人當謹慎討論這些奧祕、但因他們幾乎都不談，就無法有效地影響好奇之人的思想，而這種好奇是不容易被約束的。所以，為了在這教義上有正確的平衡，我們必須査考神的道，因它是思想的正確原則。聖經是聖靈的學校，沒有省略任何人需要知道並對人有益的事，同樣地，它一切的教導都是我們應該知道的。所以我們必須避免忽略教導信徒任何聖經已啟示關於預定論的事，免得我們邪惡地攔阻他們受神喜悅賜給他們的祝福，或指控和嘲笑聖靈啟示一些對人不利的事。

　　我們應當允許信徒接受神向我們啟示的一切，只要是神所沒有啟示的，他也不再探究。最理智的自制就是在學習中總是跟隨神的帶領，但當神停止教導時，我們也應當停止學習。我們不應該因人認為神的一些啟示是對人不利，就不看重神的聖言。所羅門的這句話是眾所周知的：「將事隱祕乃神的榮耀。」(箴二五2，Vg.)然而敬虔和常識都告訴我們這句話不是絕對的。我們必須做區分，免得在含蓄和謹守的偽裝下，滿足於獸類的無知。摩西清楚簡要地教導這一點：「隱祕的事是屬耶和華——我們神的；唯有明顯的事是永遠屬我們和我們子孫的。」(申二九29，cf. Vg.)由此可見，摩西在此唯一勸戒百姓學律法的根據是：這是天上的預旨，是神喜悅向我們啟示的話語；他也以這話語約束百姓，因為人不被允許探究神隱密的事。

*** 4反駁這教義對人不利的說法
　　我承認不敬虔的人特別喜歡批評、咒罵、吼叫，或嘲笑預定論。但若我們因他們的無恥就猶豫傳講這教義，那就得對其他基督教基要的教義閉口不談了，因為這些教義，大部分也是他們和他們的同黨所褻瀆的。悖逆的人聽到在神的本質裡有三個位格，與聽到當神創造人時，祂預先知道一切將發生在人身上的事時，也有一樣傲慢、咒罵的反應。且當他們聽到自從神創造宇宙至今只有五千年的歷史，他們同樣會嘲笑，因他們想知道神為何拖延那麼久才開始發揮自己的大能。總之，聖經所教導的每一個教義都被他們嘲笑。難道為了塞住他們所說的一切褻瀆的話，我們就要停止教導聖子和聖靈的神性，或停止教導神對宇宙的創造嗎？我們絕不！神的道在這教義和所有的教義上都是全能的，也因此無須懼怕惡人的毀謗。

　　這與奧古斯丁在他的作品《堅忍的恩賜》 (The Gift of Perseverance)中所堅持的教導一樣。在新約時代中，假使徒也無法因侮辱和控告保羅正統的教義使保羅感到羞恥。我們的仇敵說這整個教義對敬虔之人有害，因這教義攔阻我們勸勉人、動搖人的信心，也攪擾人的心，使人感到恐懼，然而這是胡說八道！奧古斯丁說，人經常因同樣的緣故指控他太開放地教導預定論，但他卻輕而易舉地反駁他們的指控110既然許多人對此教義有各式各樣荒謬的指控，我們將在恰當的時候一一反駁。我在此只要承認我們不應當好奇地探究神的隱密事，並同時不忽略祂已向我們啟示的事，好避免過分的好奇心或忘恩負義。奧古斯丁也巧妙地表達同樣的含義：我們能毫不膽怯地學習聖經，因聖經對我們的教導就如母親按照小孩的理解力教導他一般。至於那些謹慎或懼怕到避免傷害的軟弱信徒且對預定論絕口不提的人，他們要用什麼掩飾自己的驕傲，其實這樣就間接指控神是愚昧、無深慮的，就如神沒有預測到他們自以為有智慧所看見的這危險？如此看來，咒罵預定論的人就是公開侮辱神，就如神不謹慎地教導了對教會有害的教義。

** 預定論的定義以及它與以色列國和各人的關聯(5-7)
*** 5預定論和神的預知；神對以色列的揀選
　　沒有任何希望被看待成敬虔的人敢直接否定預定論，即神賞賜一些人永生的盼望，而判其他的人永死。然而我們的仇敵(特別是那些主張神的預旨是預定論起因的人)對這教義有許多吹毛求疵的異議。我們承認這兩個教義都是神所教導的，但若說預定論是根據預知，這是荒謬的！

　　當我們提到神的預知時，我們的意思是，萬物從永遠到永遠都在神眼前，所以對祂的知識而言，沒有未來也沒有過去，反而萬事都是現在進行式。且這意思是神不但用意念思考萬事，就如我們思考我們所記住的事一般，祂也看萬事就如這一切正在祂眼前，且這預知包括全宇宙的每一個受造物。我們稱預定論為神自己決定各人一生將如何的永恆預旨，因神不是以同樣的目的創造萬人，祂預定一些人得永生，且預定其他的人永遠滅亡。因此，既然每一個人都是為了這兩種目的其中之一被創造，所以我們說他被預定得生命或受死。

　　神啟示祂的預定包括所有的人，也以亞伯拉罕的整個後裔作比方，證明各國的未來都是祂決定的：「至高者將地業賜給列邦，將世人分開......耶和華的分本是祂的百姓；祂的產業本是雅各。」(申三二8-9 p.，cf. Vg.)這分開是顯而易見的，在亞伯拉罕身上，就如神選擇了已枯萎的樹幹，祂特別揀選了一個種族，而拒絕了其他種族。祂沒有啟示其理由，只是摩西教導以色列之所以與眾不同，完全是出於神白白的慈愛，免得亞伯拉罕的後裔自誇。他宣告神拯救他們的原因是：神愛族長，「所以揀選他們的後裔」(申四37 )。 

　　他在另一章中更詳細地教導：「耶和華專愛你們，揀選你們，並非因你們的人數多於別族……只因耶和華愛你們。」(申七7-8 p.，cf. Vg.)摩西經常重複同樣的教導：「看哪，天和天上的天，地和地上所有的，都屬耶和華——你的神。耶和華但喜悅你的列祖，愛他們，從萬民中揀選他們的後裔，就是你們。」(申一O14-15，cf. Vg.)。同樣，摩西在另一處勸他們成聖，因神揀選他們做祂的子民(申七6)。在另一處經文中，他又宣告神保護他們是出於祂的愛(申二三 5)。信
徒也都一生宣告這真理：「祂為我們選擇產業，就是祂所愛之雅各的榮耀。」(詩四七4，cf. Comm.)一切神賞賜屬靈恩賜的人，都承認這些恩賜是出於神白白的愛，因他們知道這一切不是他們應得的，也知道連雅各這聖潔的族長自己的美德，仍不配神賞賜他和他的後裔這崇高的尊榮。神自己也說他們完全不應得這福分，因他們是頑梗、硬著頸項的百姓(出三二9；cf.申九6)，祂這樣說是為了更有效地根除他們的驕傲。此外，先知經常提醒猶太人他們是神的選民，為了提醒他們：他們已從這揀選上墮落了(cf. 摩三2)，雖然這激怒猶太人。

　　無論如何，我要請一切主張神的揀選是人的善行所應得的人留意，既然聖經記載神愛一國勝過其他國，也記載神所揀選的是卑賤，甚至是邪惡、頑梗的人，難道他們要因神喜悅彰顯自己的憐憫而指控祂嗎？但他們的咆哮必不能攔阻神的事工，他們對天怒罵也無法使神的公正受玷污。這些辱罵反而將落在他們身上！此外，當神要以色列人感謝祂，或盼望來世的永生時，祂就提醒他們這白白恩約的原則。先知說：「我們是祂造的，並不是自己造的；我們是祂的民，也是祂草場的羊。」(詩一OO3；cf. Comm. ；詩九九3，Vg.)他加上「不是自己造的」並不是多餘的，因這教導我們的神，不但是他們一切豐盛福分的來源，也告訴我們，祂善待他們的理由在於祂自己，因他們完全不應得這大尊榮。
　　先知也以這句話勸他們以神白白的恩賜為足：「祂僕人亞伯拉罕的後裔，祂所揀選雅各的子孫。」(詩一○五6：詩一○四6，Vg.)並且當先知記載神不斷的祝福是祂揀選的果實後，他的結論是神如此慷慨，「都因祂記念祂的聖言」(詩一○五42)。教會所唱的詩也與這教義完全一致：「因為他們不是靠自己的刀劍得地土；也不是靠自己的膀臂得勝，乃是靠你的右手，你的膀臂，和你臉上的亮光，因為你喜悅他們。」(詩四四3，1)我們應當留意「地土」是某種象徵，代表神將他們分別為聖、收養他們。大衛在另
處也一樣勸百姓感謝神：「以耶和華為神的，那國是有福的！祂所揀選為自己産業的，那民是有福的！」(詩三三12)撒母耳也以此教義勸他們盼望神：「耶和華既喜悅選你們作祂的子民，就必因祂的大名不撇棄你們。」(撒上一二 22 p.)當大衛的信心受攻擊時，他也以這教義與魔鬼作戰：「祢所揀選的人......必住在祢的院中。」(詩六五 4；cf. Comm. ；六四 5，Vg.)此外，因神的揀選(這奧秘是以色列人從埃及和巴比倫被釋放，以及神對他們一切的祝福所證實的)，以賽亞這樣運用「揀選」這一詞：「耶和華要憐恤雅各，必再揀選以色列。」(赛一四1 p.，cf. Vg.)在描述以色列的未來時，以賽亞宣告：雖然神似乎撇棄以色列人，但祂卻要將剩下的餘數聚集歸一，且這將證明祂的揀選必不落空，雖然當時這揀選看起來是落空了。當神在另一處說：「我揀選你，並不棄絕你」(賽四一 9)，神在強調祂一直以父親般的愛不斷慷慨地恩待以色列人。《撒迦利亞書》中的天使更清楚地表明這真理：「耶和華……也必再揀選耶路撒冷。」(撒二12)這好像在說神更嚴厲的管教證明祂棄絶了以色列，或以色列被擄掠斷絕了神對他們的揀選。但神的選召是沒有後悔的，雖然我們有時看不見祂揀選的證據。

*** 6神對個別以色列人的揀選和遺棄
　　我們現在要解釋第二種更為狹窄的神的揀選，或那更顯示出神特殊恩典的揀選，即神從亞伯拉罕的同一個種族中棄絕了一些人，卻叫其他人作祂的兒女，聚集他們到祂的教會裡。以實瑪利在一開始與他的兄弟以撒有同等的地位，因神一樣以割禮印記祂的恩約。以實瑪利之後被棄絕，再來是以掃，最後是無數的群眾，甚至幾乎整個以色列都被棄絕了。從以撒生的才被稱為神的後裔，這呼召也同樣繼續在雅各身上。神也在掃羅的身上彰顯祂的棄絕。詩篇奇妙地宣告這真理：「祂棄掉約瑟的帳棚，不揀選以法蓮支派，卻揀選猶大支派。」(詩七八67-68；cf. LXX；詩七七67-68，Vg.和Comm.)聖經多次記載這真理，好讓我們在這區分中更清楚明白神的恩典——這奇妙的奧祕。我承認以實瑪利、以掃，和其他被遺棄的人，是因自己的過錯和罪惡無法得兒子的名分。因神所設立的條件是要忠心謹守神的約，但他們卻不信地違背了。但這並不影響神祝福祂從萬國中特選的以色列國，就如詩篇所記載的：「別國祂都沒有這樣待過；至於祂的典章，他們向來沒有知道。」(詩一四七20，cf. LXX)

　　我們有極好的理由在此留意兩種揀選。神揀選全以色列國時，就證明祂的慷慨是自由的，不受任何轄制，好讓我們毫無根據要求神同樣恩待每一個人。神之所以不同等恩待每一個人，就證明神的恩典是自由的。因這緣故，瑪拉基強調以色列人的忘恩負義，因神不但從萬國中揀選他們，也從亞伯拉罕聖潔的家族中特選他們作自己的百姓，但他們卻不忠實，甚至褻瀆地藐視神——他們慈愛的父。「以掃不是雅各的哥哥嗎？我卻愛雅各，惡以掃。」(瑪一2-3；羅九13)神在此認為他們既都是同一位敬虔之父所生，都是祂恩約的後嗣，簡言之是同一棵聖潔之樹的兩根樹枝，所以雅各之子受這樣大的祝福，也就負更大的責任，是理所當然的，但當神拒絕了長子以掃，而揀選了他們的父雅各作後嗣(雖然他生來的位分是較卑微的)之後，神指控他們是加倍地忘恩負義，因他們棄絕了神雙重的揀選。

*** 7個人的揀選才是真實的揀選
　　雖然我們迄今已確實明白，神以祂隱密的計畫，照自己所喜悅的，白白揀選某些人，而棄絕其他的人，但在我們解釋個人的揀選之前，我們對神揀選的解釋仍不完整。神不但提供他們救恩，也預定之，甚至他們無疑必將蒙恩，這些人是保羅所說神應許的後裔(cf.羅九7-8；加三16 ff.)。神賜亞伯拉罕兒子的名分，雖然他許多的後裔被棄絕就如腐爛的枝子，然而為了證明神的揀選是有效和永久的，我們必須留意神所揀選的元首——主耶穌基督，因為父神在基督裡將祂的選民聚集歸一，並以無法被破壞的聯合，使他們與自己和好。所以，雖然神慷慨地恩待亞伯拉罕的後裔，而拒絕恩待其他人，但在基督的肢體上，我們卻看見神全能的恩典，因為基督的肢體一旦被稼接在元首身上，就永遠不會失去救恩。因此，保羅用以上《瑪拉基書》中的經文極為巧妙地推論：神雖然建立永生之約、並呼召以色列人歸向自己，但祂用了特別揀選的方式，特選他們其中的一些人，就證明祂不是以同等的恩典有效地揀選全部的以色列人(羅九13)。雖然祂說「我愛雅各」(瑪一2)是指這族長所有的後裔，因為先知在此將他們與以掃的後裔區分開來。但這與神在雅各身上預表祂有效的揀選並無衝突。保羅稱這些人為「剩下的餘數」(羅九27；一一5；cf，赛一○ 22-23)不是沒有理由的，因為我們的經驗也告訴我們，在神所呼召的眾多人當中，有許多人至終墮落，而剩下的餘數才是神真正的選民。

　　要解釋為何神對以色列人一般的揀選，不一定是堅定和有效的，並不困難。神與以色列人立約，卻沒有賜給每一個以色列人重生的聖靈，使他們在這恩約中堅忍到底。有三種人，一種是神公開棄絕的，一種是神真正的選民，另一種是表面看起來屬神，卻沒有內在保守人的恩典。雖然聖經稱整個以色列國為「神的產業」(申三二9；王上八51；詩二八9：三三12；等等)，然而當中有許多是外邦人。神應許以色列作他們的父和救贖者，雖然許多以色列人離棄了祂。但神與他們立的約卻不是徒然的，因為在他們當中，神保守了一些人作祂真正的選民，這證明祂的選召「是沒有後悔的」(羅一一29)。

　　神之所以不斷地從亞伯拉罕的後裔中，而不是從外邦國家中有效地將自己的教會呼召出來，是根據祂的恩約。雖然大多數的以色列人違背了這約，但祂卻保守了剩下的餘數，免得這恩約至終落空。簡言之，神對亞伯拉罕整個後裔的收養，從某一點來說是具體預表神對他們當中少數人更大的祝福。也就是為何保羅很仔細地將亞伯拉罕肉身所生的兒女與他屬靈的兒女，用以撒為代表的選民區分開來(加四28)。這並不是說作亞伯拉罕的後裔是徒然、無益的，若這樣說就是侮辱神的恩約！但神不改變的計畫就是祂照自己的美意預定人歸向祂的計畫，唯獨在乎這些屬靈的後裔。但在我引用許多經文充分證明這觀點之前，請讀者們不要先匆促做決定。

** 揀選教義的總結
　　聖經明確地教導，神根據祂永恆不改變的計畫，揀選了祂預定賞賜救恩的人，以及遺棄祂預定滅亡的人。我們深信對神的選民而言，這計畫是根據祂白白的憐憫，而不是人的價值。但神以祂的公正、無可指責卻測不透的審判，向祂所預定滅亡的人關了永生的門。就神的選民而論，神的呼召證明他們被揀選。我們也深信他們的稱義是另一個證據，直到他們得榮耀，就是這揀選的完成。然而，就如神藉著祂的呼召和稱義，見證祂的選民，同樣地，祂拒絕使祂所遺棄的人認識自己，或被聖靈成聖，也據此彰顯他們將受怎樣的審判。我在此略而不談許多愚昧者為了推翻預定論的教義所捏造的幻想。我們無須反駁這些幻想，因為它們本身就充分證明它們的錯誤。我只要稍微討論知識份子攻擊預定論的謬論，或可能絆倒單純之人的謬論，或不敬虔之人用來攻擊神公義的謬論。
