#+TITLE:書摘《活在聖靈中 Keep in Step with the Spirit》巴刻(J．I．Packer)著/霍玉蓮譯
#+AUTHOR:巴刻J．I．Packer著/霍玉蓮譯

* 目錄
 - [[#1_看清楚聖靈][1_看清楚聖靈]]
   - [[#認識並經歷神][認識並經歷神]]
   - [[#聖靈的能力][聖靈的能力]]
     - [[#基督徒的能力][基督徒的能力]]
     - [[#能力的限制][能力的限制]]
   - [[#表現_屬靈恩賜的運用][表現_屬靈恩賜的運用]]
     - [[#總動員事奉][總動員事奉]]
     - [[#正確地看表現][正確地看表現]]
   - [[#保守我們純潔][保守我們純潔]]
     - [[#道德掙紮教義的陷阱][道德掙紮教義的陷阱]]
   - [[#叫我們醒覺][叫我們醒覺]]
     - [[#泰萊觀點的毛病][泰萊觀點的毛病]]
   - [[#追溯我們的思路][追溯我們的思路]]
   - [[#基督的臨在][基督的臨在]]
     - [[#對神的覺醒][對神的覺醒]]
   - [[#綱要][綱要]]
 - [[#2_聖經裏的聖靈][2_聖經裏的聖靈]]
   - [[#屬靈恩賜][屬靈恩賜]]
     - [[#什麼是屬靈恩賜][什麼是屬靈恩賜]]
     - [[#屬靈恩賜的運用][屬靈恩賜的運用]]
     - [[#恩賜帶來的祝福][恩賜帶來的祝福]]
 - [[#6_聖靈的路徑_解釋聖靈生活][6_聖靈的路徑：解釋聖靈生活]]
   - [[#翻方言][翻方言]]
   - [[#醫治的恩賜][醫治的恩賜]]
   - [[#預言的恩賜][預言的恩賜]]
   - [[#對複還論神學思想的裁決][對複還論神學思想的裁決]]
   - [[#另一套神學理論][另一套神學理論]]
     - [[#說方言][說方言]]
   - [[#結論][結論]]
     - [[#4_說方言][4_說方言]]


* 1 看清楚聖靈
** 認識並經歷神
　　耶穌在世上的時候，門徒追隨他，但他們對屬靈事物的理解常有錯漏，而且經常對耶穌有許多誤解；可是，耶穌能夠超越他們思想上的限制，感動他們、改變他們的生命，純粹是由於他們愛他、信靠他，希望從他身上學習，誠心願意追隨他們心中的亮光去服從他。因此，十二個門徒中有十一個「已經乾淨了」，並且得與其他人一起進入耶穌平安的恩典中，而那時他們尚未能掌握耶穌釘十架的贖罪意義。神首先賜下救恩的禮物，改變他們的生命，其後他們才明白這是什麼一回事。

　　神是滿有恩慈的，只要我們以真誠的態度，全心全意尋求他的臉，希望與他親近，即使我們對何謂屬靈生命沒有認識，或只有錯誤的觀念，他都可以使我們靈裏的生命進深。但並不是說神賜福於那些無知和錯謬的人，是由於他們的無知和錯謬；也不是說神不在意我們是否認識和掌握他所啟示的旨意；更不是說一個人只要對神有誠懇的心和真摯的情感，就不怕無知和錯謬會損害他靈命的健康。

　　無數罪人在他們對耶穌和聖靈尚未有正確的認識時，就已經真實地經歷耶穌基督的救恩和聖靈使生命更新的能力。儘管如此，我們若對聖靈有較清晰的觀念，就更能欣賞聖靈的工作，以及避免墮入一些錯謬的陷阱。

[[Keep_in_Step_With_the_Spirit__orig.org#認識並經歷神][本文連結]]　　　
[[Keep_in_Step_With_the_Spirit__notes.org#目錄][目錄連結]]

** 聖靈的能力
　　許多人認為聖靈的教義基本上與能力有關，意思是神賜予能力，讓你可以做你應該做卻感有心無力的事情。容忍那考驗你耐性的人、愛那不可愛的人、控制脾氣、在壓力中站立得穩、為基督勇敢發言、在遭逢患難中仍信靠神。聖靈賦予人能力達致上述的種種表現，無論在思想上、言語上、講章及禱告裏，這主題都為人所津津樂道。

　　能力（power）一詞是一個重要的新約辭彙，而基督藉聖靈賦予信徒能力，確是新約中重大的事實，是福音裏的榮耀，也是世界各地忠實追隨基督的人的標記。我們受教導知道靠著超自然的能力去過超自然的生活，是整個新約基督教信仰的核心，故此，那些自稱信奉基督教的人，若不曾經歷能力的澆灌，也表現不出他們擁有這種能力，那麼照新約聖經的標準看來，他們的信仰是值得懷疑的。

　　儘管人以基督為信徒得力的唯一源頭，能力的澆奠往往是聖靈的工作，而人只提基督，是因為基督賜下聖靈。因此，能力是透過聖靈從基督而來；無論何時何地，誰人傳授基督教道理，都應該特別重視這個真理。過去三百多年來，福音派信徒一直仰賴神的應許，不斷向神支取能力來生活。我們應該為此感到高興，因為這種能力的賜予不單是聖經裏的一個重要主題，他還針對人類一個明顯而普遍的需要。凡肯誠實面對自己的人，都不時會因自己內心一份強烈的不足感而不知所措。所有基督徒都會一次又一次窘迫地呼喊：「主啊，幫助我，堅固我，扶持我，賜我能力，好讓我所言所行都能取悅你，令我剛強壯膽，有充足的力量面對種種壓力和要求。」

　　我們是被召去戰勝那惡者，他常以種種形態出現在我們心裏，或圍繞我們。我們需要知道在這一場爭戰裏，只有靠著聖靈的能力，才能獲取勝利；反之，若完全靠賴自己，最後只會發現自己的無能和經驗挫敗，引致痛苦。所以，福音信仰強調藉著聖靈而達致成聖是一件真實而又必需的事，這個教導永遠都切合時宜。

[[Keep_in_Step_With_the_Spirit__orig.org#聖靈的能力][本文連結]]　　　
[[Keep_in_Step_With_the_Spirit__notes.org#目錄][目錄連結]]

** 基督徒的能力
　　十七世紀時期，清教徒首先強調聖靈如何在人的生命中彰顯能力；到了十八世紀，衛斯理（John Wesley）開始提出一種教義，說聖靈會把人的罪從人心靈中連根拔起。這就是衛斯理所指的「合乎聖經的聖潔」。非衛理公會信徒對這種教訓退避踟躕，覺得他很虛妄，而且不合乎聖經，所以他們不斷警告自己教會的會友要防備這種思想。然而到了十九世紀中葉；許多人感到這股反完全主義的熱潮令基督徒完全遺忘了神有能力拯救人脫離罪，他能使人過一個平靜、得勝而公義的生活，他亦能夠使講員的資訊直透人心靈深處。忽然之間，人得勝的能力頓成為講章、書籍和非正式小組討論的話題。一個嶄新的福音信仰運動已經展開了。

　　這個得力的「秘訣」，有時也稱為「高超生命」或「得勝生活」的秘訣，已經在英倫一年一度為期一周的凱錫克培靈會（Keswick Convention）中，全面制度化地推展了，星期一的主題是罪惡，星期二的主題是那拯救我們脫離罪惡的基督，星期三是奉獻，星期四是在聖靈裏的生命，星期五是成聖者滿有能力的事奉（尤其是在宣教事工上）。仍依據凱錫克培靈會的教導，以信心就是得力之途為主題。「凱錫克型」的講員，專門在大會上宣講能力的資訊，凱錫克培靈會中有關成聖和事奉能力的資訊自然縈繞人心。

　　這種講論能力的主題也不是近年唯一的發展。基督的能力不單能夠赦免我們的罪，而且藉著聖靈，可拯救我們脫離罪惡的奴役。有如第一世紀一樣，這個資訊已再次成為教會福音資訊的主要部分。較古老的福音資訊，由於他強調律法、罪惡、審判和基督代贖受死的榮耀，誠然可以補充今天福音資訊的缺欠。可是整體來說，古老的福音資訊很少論及能力；既然神應允和賜予能力是千真萬確的事，那麼能力的主題如此受到重視，誠然是一件值得欣喜的事。事實上，強調能力的資訊不管透過什麼形式表達出來，今天已成為基督教福音信仰主流的標記，與世界性的靈恩運動並駕齊驅；

[[Keep_in_Step_With_the_Spirit__orig.org#基督徒的能力][本文連結]]　　　
[[Keep_in_Step_With_the_Spirit__notes.org#目錄][目錄連結]]

** 能力的限制
　　經驗告訴我們，當我們思想聖靈時，若只集中注意能力這個主題，而沒有一個更具深度的觀點，沒有從另一個中心主題去看聖靈的職事，那麼，扭曲的觀念很快就悄悄潛入我們的思想裏。

　　當人論及聖靈的工作時，往往傾向於以人為中心，就好像神的能力是一些隨時儲備妥當的東西，只要運用思想和意志——通常美其名為奉獻和信心--就可以開關「使用」。同時，這種態度形成一種觀念，認為只要我們肯釋放自己內在的能力，神的能力就會在我們心裏自動地運行，因此，我們可以隨時按著自己奉獻和信心的程度來調節這種能力。另一個隨之浮現的觀念，就是以為必須處於內在的被動狀態中，完全等候神的能力帶領我們，就是為心靈空虛的人提供一種「生活的力量」。表面上，就好像只要人肯委身基督，他立刻可以獲得發動和操縱能源的權利。

　　這些觀念混淆了憑己意去擺佈神的能力和因著順服神的旨意而經歷神的能力。佈道家們的講章經常暗示一件事實，就是我們一旦成為基督徒，神在我們裏面的能力就可以立時除去我們性格上的任何弱點，令我們生活一帆風順；可是，這種說法是違背聖經，甚至是不誠實的。當然，神有時候可以施行奇跡，令悔改的人忽然改變過來，從這些或那些弱點中得釋放，即如其他時候，他亦會偶然施行神跡奇事一樣；然而，每個基督徒的生命都是一場持久戰，要不斷對抗來自世界、肉體和魔鬼的種種試誘和壓力；同時，那追求活像基督的爭戰是嚴苛的，是永不停息的。凱錫克培靈會中的講論，經常鼓勵我們一時間對自己有過高及過低的期望——每時每刻完全脫離罪的纏累，是期望過高；另一方面，沒有機去期望能夠逐步擺脫罪對我們心靈的轄制，就是期望過低。這是一種拙劣的神學，而且在心理和精神上都不符現實。

　　所以只談聖靈能力，根本不能針對問題的核心。

[[Keep_in_Step_With_the_Spirit__orig.org#能力的限制][本文連結]]　　　
[[Keep_in_Step_With_the_Spirit__notes.org#目錄][目錄連結]]

** 表現_屬靈恩賜的運用

[[Keep_in_Step_With_the_Spirit__orig.org#表現_屬靈恩賜的運用][本文連結]]　　　
[[Keep_in_Step_With_the_Spirit__notes.org#目錄][目錄連結]]

*** 總動員事奉
　　許多人認為聖靈的教義基本上與表現有關，意思是運用屬靈恩賜。對這些人來說，聖靈的職事似乎由始至終只是關乎如何運用恩賜——講道、教導、說預言、說方言、醫治等等。他們認為根據新約聖經的教導，恩賜（charismata）是神所賜予的某些能力，尤其是藉著言語、行為和態度，把關乎耶穌基督的真理傳遞開去，彼此激勵，互相服事。他們又認為恩賜是藉著行為以辨認的，基督徒所表現出來的行為，正顯明神賜予他們什麼能力。因此，他們認為屬靈生命的實質在乎表現，同時假設人愈能表現恩賜，就表示他愈被聖靈充滿。

　　對於這種觀點，我首先要說明一點，就是他所強調的教導本身同樣是絕對正確的；這次是強調恩賜的實在，以及運用恩賜的重要。強調屬靈恩賜的普遍性，以及神對教會總動員事奉的期望，新約聖經對這兩方面的教導是相當清楚和明顯的。並非只有聖品人員及有職分的才具有恩賜，所有基督徒都具有恩賜，牧者必須認識這個事實，並運用自己的恩賜去裝備平信徒運用他們的恩賜。

　　近年來普世教聯運動和靈恩運動都抓緊這方面的聖經真理，使之漸漸成為基督教的老生常談，因而產生了一些可喜的效果。讓信徒有機會完全發揮他們的恩賜，令會眾整體受益；隨之興起的，是以一種認真的態度，去檢討傳統的崇拜程式和形式，以保障沒有任何恩賜受到窒礙，甚至銷滅聖靈的感動。這一切都是好現象。

[[Keep_in_Step_With_the_Spirit__orig.org#總動員事奉][本文連結]]　　　
[[Keep_in_Step_With_the_Spirit__notes.org#目錄][目錄連結]]

*** 正確地看表現
　　很不幸，這可喜情況也有其負面。過分強調平信徒的職事，令一些平信徒忘記要尊重牧者的職分和領導。也看不見另一個事實，就是教會生活中最重要的恩賜（如講道、教導、領導、輔導、支持）通常是一些被聖化了的天然才能。這些毛病不過是一些不受歡迎的副產品。原則本身是正確的，若不能切實遵守這些原則，就不可能有高質素的教會生活。

　　若我們單單專注恩賜的彰顯，因而認為這就是我們應該集中關注的聖靈工作，那就大錯特錯了。哥林多教會的信徒因擁有知識而自高自大（八 1、2）；每當他們在教會裏聚會，彼此之間就喜歡競爭和炫耀自己的恩賜。他們重視恩賜和自由過於公義、愛心和事奉；保羅說這樣的價值觀是錯誤的。

　　哥林多信徒因著自己的知識和恩賜，以為自己是「屬靈的」；可是，真正屬靈的質素是屬乎道德的。那遠勝哥林多信徒一切最可誇表現的「更妙之道」，就是愛。一個人可以有很好的表現，使他人靈性得益，但他本人卻沒有因著真正認識神，經歷聖靈在他心內動工所帶來的內在更新。彰顯聖靈的恩賜表現，與聖靈所結的果子，完全是兩回事；屬靈恩賜只屬於頭腦上或理解上的，不管是普通恩賜或特殊恩賜，都不能在心靈裏占一席位。
意志、情感和良心都與這些恩賜無關，因此，這些恩賜無法改變心靈。

　　在整本新約聖經裏，每逢提及神在人生命中的工作，著眼點往往是倫理道德，而不是靈恩方面的。那真正要緊的是活像基督（不是在恩賜上像基督，而是在愛心、謙卑、順服神的旨意、對別人的需要敏感等各方面像他）。任何把屬靈恩賜（奔走和辦事的能力和意願）看為比屬靈果子（在個人生命中像基督的品格）更重要的心態，在屬靈上都是方向錯誤的，需要矯正。最佳的矯正良藥就是重新調校我們對聖靈工作的觀點。

[[Keep_in_Step_With_the_Spirit__orig.org#正確地看表現][本文連結]]　　　
[[Keep_in_Step_With_the_Spirit__notes.org#目錄][目錄連結]]

** 保守我們純潔
　　有些人將聖靈的教義集中在「潔淨」（purifying）和「淨化」（purgation）之上。對他們來說，問題的核心並非經歷聖靈的能力，也非在乎基督徒對外的表現，反而是我們內心的爭戰，在追求聖潔的過程中如何對抗罪惡，尋求聖靈的幫助，保守我們純潔，不受玷污。

　　聖靈使基督徒醒覺到自己的罪汙，並為此感到羞慚，又激勵我們去「……潔淨自己除去身體、靈魂一切的汙穢，敬畏神，得以成聖。」（林後七 1）。基督徒在現世對純潔生命的追求，意味著他們長遠下去一種自覺的矛盾和掙紮，並常會感到成績未達理想；「因為情欲和聖靈相爭，聖靈和情欲相爭，這兩個是彼此相敵，使你們不能作所願意作的。」（加五 17）他在生活中認識到他所作的一切其實可以並且應該做得更好：在每一次嘗試之後，在每一個行動之後，他往往看見他在動機上、在表現上，都有許多可以改善之處。

　　當然，這不是說他永不會達到任何程度的義，保羅並非預料基督徒生命是經常完全失敗的，反而，他期望這是不斷的道德成長。「……當順著聖靈而行，就不放縱肉體的情欲了。」期望信徒努力向前，養成聖潔的習慣，積極操練自己，學像基督。意思是說，一些他從前愛做的事，如今放棄不作。現在，他要追隨自己心靈裏所感受到屬於聖靈的意願，而不陷溺在肉體的情欲中。基督徒生命必須是公義的生命，這正是他悔改和重生的自然流露，也是基本的要求。

　　活在聖靈中的基督徒，會不斷發現他的生命尚未達致本來應有的美善；他經常要面對重重障礙和限制，以及自己扭曲的天性背道而馳的拉扯，他正在打一場前所未有的硬仗；同時，即使是他最好的行為，也不免犯上動機上的罪；他亦發現他每日的生活充滿汙點，他必須每時每刻仰賴神在基督裏的赦罪恩典，否則他就會在罪中失喪；同時，他也認識到自己心靈的軟弱和善變，需要經常求告聖靈賜給他力量，使他在這場內在的鬥爭中能堅持到底。

[[Keep_in_Step_With_the_Spirit__orig.org#保守我們純潔][本文連結]]　　　
[[Keep_in_Step_With_the_Spirit__notes.org#目錄][目錄連結]]

*** 道德掙紮教義的陷阱
　　經驗告訴我們，當信徒以道德掙紮作為他們思想聖靈的重點時，常會被許多陷阱圍繞。他們會漸漸變成律法主義者，常常為自己和別人定下嚴格的規例，好讓自己對不相干的事情毫不染指，又給自己和別人強加一些呆板並約束性的行為模式，作為抵抗屬世潮流的堡壘，並且大大強調遵守這些人為禁忌的重要。他們注重提防那能污染人的事情，以及毫不妥協地堅守原則，多於注重實踐基督的愛；他們變得小題大造，沒有喜樂，終日內省，陷溺於懊悔自己心靈的腐朽，滋長出灰暗冷漠的人生觀。這種種態度可說是屬靈的神經衰弱症，他們歪曲、損害並削弱聖靈使人成聖的工作，因此實際上使聖靈在我們生命中的工作蒙上汙點。

　　這些心態通常是累積了種種因素構成的，諸如天生的性情、早年的教育和訓練，以及因害羞或缺乏安全感而形成的吹毛求疵習慣、低下的自我形象，甚至或者真正的自我憎厭，一些內向的教會文化和社群，都可以導致上述的情況。聖靈認識不足，也經常是一個原因。

[[Keep_in_Step_With_the_Spirit__orig.org#道德掙紮教義的陷阱][本文連結]]　　　
[[Keep_in_Step_With_the_Spirit__notes.org#目錄][目錄連結]]

** 叫我們醒覺
　　第四種看法，認為聖靈的職事基本上就是呈示，就是促使我們醒覺到一些事情。

　　泰萊視聖靈為聖經中一個代表神聖「交流」的名字，他喚起人對物、對己、對他人，以及對神的醒覺，催促我們作出種種抉擇，這些抉擇有時更要求我們作出自我犧牲。自五旬節以來，聖靈持續不斷的工作，就是使個別人覺醒到耶穌的神性，以致他們的生命能活出耶穌在加略山上為罪受死的自我犧牲精神。聖靈要召喚人對這個覺醒作出回應，他在心志相同的人群中所進行的工作最為有效。

　　泰萊從沒有忘記我們是人——罪惡、愚昧、多變、混亂的人——，而聖靈是我們神聖的主，他在我們心裏的工作是超過我們心思所能理解的。他的觀點由始至終都以神為中心。泰萊認識到聖靈不是神賜給我們的一種興奮劑，他不是任由我們操縱和支配的。聖靈是我們神聖的主，他在我們心裏的工作是超過我們心思所能理解的。泰萊不容許我們專注浸裏在我們內裏與罪惡的爭戰中，因為他看見聖靈經常把我們的注意力往上往外導引，叫我們以神、耶穌基督及其他人的事為念。

　　因此，泰萊一方面強調每個人在神面前的獨特性（醒覺是屬於個人的事情），另一方面，他的整體取向始終以小組、教會和社區作主導。對於「自發和出於超理性反應」的靈息表現——表現在醫治、方言，尤其是預言的恩賜上——，泰萊用全人的觀念去解釋這些表現：人不是只懂得作理性分析；整個人的各方面都是聖靈工作的範疇。

[[Keep_in_Step_With_the_Spirit__orig.org#叫我們醒覺][本文連結]]　　　
[[Keep_in_Step_With_the_Spirit__notes.org#目錄][目錄連結]]

*** 泰萊觀點的毛病

[[Keep_in_Step_With_the_Spirit__orig.org#泰萊觀點的毛病][本文連結]]　　　
[[Keep_in_Step_With_the_Spirit__notes.org#目錄][目錄連結]]

** 追溯我們的思路

　　許多人對聖靈的觀點雖然未至完全虛假，但肯定是含糊不清和不夠真實的，有時構成威脅、窒礙聖靈，使我們無力叫聖靈得著榮耀。故此，當務之急，就是更清楚地認識聖靈。

　　我們探討了目前四個關於聖靈職事並極具影響力的主要觀念：生活的力量（power）、事奉上的表現（performance）、行為和動機的純潔（purity）和驅使我們作決定的呈示（presentation）。這幾點事實上是未夠徹底的，可以再加多幾項：辨識力（perception）、催迫（push or pull) 和個性（personhood）。有些人實在以為聖靈主要和獨特的工作只是幫助人提高知覺（辨識力），另一些人，他們忘記了在我們墮落的人性裏那些不受約束的本能、被壓抑的理智及種種複雜病態的妄想如何會被自然界和撒但隨便利用，竟然把聖靈的感動等同於人內心的渴求（一些拉力或催迫），尤其當這些渴求與一些突然、強烈而又重複地出現的視覺和聽覺意象（如幻影、聲音、異夢）相連時，他們就更加確信是聖靈的感動。另一些人聲稱聖靈主要工作是幫助人領會自己獨特個性的奧秘、別人的價值，及對真誠關係的需要。

　　縈繞心間、擺脫不掉的思想、意念不一定源自神；撒但同樣精於製造使人擺脫不了的衝動，正如他能操縱並加強那些發自我們扭曲了的天性的衝動一樣。故此，對於一些突如其來佔據心神的思想，我們必須仔細檢討（最好是請教別人）然後才下結論，斷定他們是否從神的靈而來。其實，這些思想纏擾心神，叫人擺脫不了，已顯示出他們多半不是源於神的靈了。其實，自基督來了，聖靈的中心職事是幫助人與基督建立更密切的團契。無疑，因著普通恩典（common grace），聖靈會在世俗和異教的場合中提高人的辨識力和敏感度，但這從來不是聖靈工作的中心。

[[Keep_in_Step_With_the_Spirit__orig.org#追溯我們的思路][本文連結]]　　　
[[Keep_in_Step_With_the_Spirit__notes.org#目錄][目錄連結]]

** 基督的臨在
　　自從使徒行傳第二章五旬節事件以來，聖靈就一直賦予人能力、扶助人、潔淨人，並且引領世世代代的罪人去面對神。聖靈這樣做是要叫人認識基督、愛他、信靠他、尊崇他和讚美他；這是聖靈一貫的目標和目的，也是父神的目標和目的。至終來說，這就是聖靈新約職事的全部內容。

　　聖經中提到，神「與他們同在」，往往是指他賜下祝福的，當然有些時候是指追討罪債，使人們醒悟到他們的行為令他不悅。在新約底下，聖靈那獨特、恒常而又基要的職事，就是在信徒中間體現基督——意思是說，讓他們領會基督與他們同在，作為他們的救主、生命之主和神，也讓他們知道有三件持續的事。

　　首先，聖靈向我們呈示活著的主耶穌，讓我們認識這位元創造主以及這位朋友，好叫我們可以選擇那犧牲的道路，以回應他的愛和呼召。

　　第二，離開人性的自私，踏上像基督的人生道路，去過一種公義、忠心事奉、戰勝罪惡的生活，愈來愈像耶穌。

　　第三，聖靈使我們肯定自己被神所愛、已蒙救贖，使信徒心中綻放出感恩、喜悅、盼望、信心——這就是確據。

[[Keep_in_Step_With_the_Spirit__orig.org#基督的臨在][本文連結]]　　　
[[Keep_in_Step_With_the_Spirit__notes.org#目錄][目錄連結]]

*** 對神的覺醒
　　從整本聖經來看，認識神的同在意味著兩重的覺醒。首先，我們醒覺神在那裏：那位客觀地真實存在的創造主；每個人的前途，不論是禍是福，都全在他手裏。第二，我們醒覺到神在這裏，他已經就近我們，對我們說話，鑒察我們，顯露我們的弱點、罪惡和罪咎，使我們降卑，同時又用他的赦免和應許提升我們。

[[Keep_in_Step_With_the_Spirit__orig.org#對神的覺醒][本文連結]]　　　
[[Keep_in_Step_With_the_Spirit__notes.org#目錄][目錄連結]]

** 綱要
　　單單思想聖靈在我們生命中的工作，容易變得以人為中心，以經驗作根據，又毫無準則。我們需要進一步探討這些記述如何配合他們對神、他的工作和他的真理的整套觀念。今天能幫助我們活在聖靈中的，並不是一些叫我們向聖靈敞開心懷的勸勉——這方面的勸勉我們已足夠有餘了；反之，我們所缺乏的，是對聖靈工作有一套整全的觀念，能充分瞭解聖靈在教會、小組及個人生命中那自由、不受羈絆及多種形式的運行。

　　聖靈所作的，就是藉著宣告，叫子得榮耀，引導我們作出回應，存崇敬的心去榮耀子，使父的喜樂增加。「聖靈論」（pneumatology）一方面闡釋，父的旨意是要子被認識、被愛、受尊崇、受讚美，並在萬物中居首位；同時另一方面，透過賜下聖靈，子應許與他的子民同在，從今直到永遠。

[[Keep_in_Step_With_the_Spirit__orig.org#綱要][本文連結]]　　　
[[Keep_in_Step_With_the_Spirit__notes.org#目錄][目錄連結]]

* 2_聖經裏的聖靈

** 屬靈恩賜

[[Keep_in_Step_With_the_Spirit__notes.org#目錄][目錄連結]]

*** 什麼是屬靈恩賜
　　我們說恩賜從聖靈而來，然而我們仍舊認為恩賜是「才幹」，或者是超自然的新穎技倆。我們尚未習慣以教會的元首基督及他目前從天上在我們當中進行的工作來給恩賜下定義。保羅或其他新約聖經作者，都沒有為我們界定何謂屬靈恩賜，但保羅聲稱運用恩賜能使人得著造就，這正好反映出他對恩賜的看法。在保羅看來，造就是對基督並與他有關的各方面有愈來愈深入和豐富的認識，而個人與他的關係更漸趨完美。因此，我們給屬靈恩賜下的定義，必須以基督為根據。

[[Keep_in_Step_With_the_Spirit__orig.org#什麼是屬靈恩賜][本文連結]]　　　
[[Keep_in_Step_With_the_Spirit__notes.org#目錄][目錄連結]]

*** 屬靈恩賜的運用
　　我們運用屬靈恩賜，無非是基督藉著他的身體去事奉他的身體，事奉天父，事奉全人類。基督從天上使用基督徒作為他的嘴、他的手、他的腳，甚至他的笑容；他藉著我們——他的子民——此時在世上說話、行動、與人相會、去愛和拯救若其他基督徒給我們諒解和鼓勵，在我們有需要的時候幫助我們，無論採用什麼形式，其實都是基督親自工作，透過他們帶給我們這些益處。

[[Keep_in_Step_With_the_Spirit__orig.org#屬靈恩賜的運用][本文連結]]　　　
[[Keep_in_Step_With_the_Spirit__notes.org#目錄][目錄連結]]

*** 恩賜帶來的祝福
　　恩賜（chartsmata）的定義，是表彰基督的能力表現。惟有那些被神使用去造就信徒的能力，才稱得上是恩賜。當我們說基督徒有恩賜時，意思並不是說他們在什麼方面顯赫出眾或很有效率，而是神已經很明顯地使用他們某方面的能力來造就人。這使我們確信他將來也會繼續這樣使用他們。我們需要把人辦事的能力和神賜福的特權清楚劃分，因為構成恩賜的，是我們的才能被神使用，而不是才能本身。若然我們所作的不能經常為他人或自己帶來可辨認的屬靈益處，我們便不要將自己處事的能力誤以為屬靈恩賜。

　　不可以單單憑表現來界定恩賜（charisma），恩賜的定義必需包括神與人的關係，神在基督裏透過恩賜建立信徒；否則，即使所謂「恩賜」在形式上與真正屬靈能力的彰顯一模一樣，也只能算是屬肉體而不是屬靈能力的彰顯。

[[Keep_in_Step_With_the_Spirit__orig.org#恩賜帶來的祝福][本文連結]]　　　
[[Keep_in_Step_With_the_Spirit__notes.org#目錄][目錄連結]]

* 6_聖靈的路徑_解釋聖靈生活

　　對於獨特的靈恩經驗，我們怎樣以神的概念來解釋他呢？一方面可從其中心的信念及倫理上的果子而得出結論，認定神在他們中間，另方面，又發現「靈恩派」和「非靈恩派」的屬靈氣質比我們有時候所在意到的更加相近。倘若靈恩社群中的典型屬靈經驗是沒有基督在其中、沒有愛心和驕傲自負的，那麼，我們的疑問就不會出現。然而我們必需面對一個事實，靈息運動用以解釋其自稱擁有的特色的一個最普遍宣告的神學觀念，是十分不合乎聖經的。

　　沒有任何經驗單憑這經驗的發生本身就可證實是從神而來，一個經驗若是出於神恩典的賜予，他在聖經真理的試驗下，必能證明在其中心有一種加強了的醒覺——對於關乎神的一些啟示的真理的醒覺，以及對於我們作為受造物、罪人、受益人、信徒、養子、被買贖的僕人，及在其他各種身分下與神的關係，有強烈的醒覺。以這個標準去量度靈恩派經驗，發現他們在這一點上沒有缺失。可是，當這些經驗被用來印證某些誤解聖經的信念時，我們就只剩下兩個選擇：一是排斥這些經驗，否則，就重新給他們神學上的闡釋，表明這些經驗實際證實和確定的真理，與靈恩信徒所以為的有所不同。無論如何，我從靈恩經驗裏看見神在其中工作，因此，我大膽作出第二個選擇——就是嘗試重新建構其神學觀念。

　　傳統五旬節派對靈恩經驗的說明，是我曾經稱之為復還論的觀點，他們將使徒行傳第二章所形容門徒在五旬節的經驗，以及哥林多前書十二至十四章所形容哥林多教會的經驗，看為今日基督徒應該追求的標準規範、理想和目標。這經驗一旦臨到，他就被提升，而且通常會說方言，作為內在已發生了的經驗的外在印記。若我們接受上述的觀點，這觀點會迫使我們評價非靈恩派基督教——即是，那些不認識或不尋求悔改後聖靈施洗的基督教信仰——為低下門徑、次等，並欠缺了一些重要的東西；可是，其次，這觀點不能從聖經中成立，因為這觀點不能前後貫徹地解答一些從聖經引伸出來的反問，例如以下三條問題。

[[Keep_in_Step_With_the_Spirit__orig.org#6_聖靈的路徑_解釋聖靈生活][本文連結]]　　　
[[Keep_in_Step_With_the_Spirit__notes.org#目錄][目錄連結]]

** 翻方言
　　在我來看，有關翻方言這問題，似乎是最莫衷一是的。從保羅的話看來，他顯然認為哥林多信徒的方言是帶有可翻出來的意義的（林前一四9-13），而今天的翻方言者對今天的方言亦有相同的假設，把他們對方言的解釋視為方言的實際翻譯。

　　那些流暢、肯定而又自然流露出來的解釋，後來卻被證實是千篇一律、含糊不清和無所傳達的。我不會妄自憑幾句翻譯錯誤的例子作為基礎，去全盤否定所有方言的解釋，看他們為虛妄的，同時，我同意撒瑪連（Samarin）的意見，他認為說方言加上翻方言的宗教儀式所產生的團結友愛本身可以是有價值的。但我想，因此就假設我們已重獲保羅所說的翻方言恩賜，卻是十分危險的。無他，事實的證據委實太不肯定了。

　　賀其馬提出當說方言帶來祝福的時候，祝福的源頭「並不是方言本身，而是說方言時候的心境，或者說……在方言說出之先，一顆尋求更多被聖靈充滿的心。」 同樣，翻方言也可以帶來祝福，是由於他傳達了聖經的激勵。

[[Keep_in_Step_With_the_Spirit__orig.org#翻方言][本文連結]]　　　
[[Keep_in_Step_With_the_Spirit__notes.org#目錄][目錄連結]]

** 醫治的恩賜
　　靈恩派的醫治職事能否令人信服地與哥林多前書第十二章二十八及三十節描述的醫治恩賜等同呢？當然不可以。

　　耶穌和門徒是直接用他們的話或者他們的撫摸來醫治的。然後，病者立即得醫治。身體上的殘缺，以及功能性、徵候的和心理引致身心上的疾病，一概獲得醫治。有時候，他們叫死了多天的人復活。他們醫治一大群人，並且沒有任何記載說他們嘗試醫治而結果失敗的。再者，他們醫治的結果是持久的；沒有任何跡象顯示得醫治者後來舊病復發。對於現今那些為病者禱告的人的職事，他們當中沒有一人有上述如此驕人的成績。

　　在使徒時代，醫治的恩賜比起現今靈恩派信徒看來擁有的醫治恩賜，在本質上是更超越的，這並不等如說在這些人的職事裏，新約時期的醫治恩賜又重新出現。

[[Keep_in_Step_With_the_Spirit__orig.org#醫治的恩賜][本文連結]]　　　
[[Keep_in_Step_With_the_Spirit__notes.org#目錄][目錄連結]]

** 預言的恩賜
　　「靈恩派的預言能否確實被視為新約表記恩賜的復興？」當然不可以。

　　首先，彼得在五旬節曾經引述約珥的預言，說預言原則上是一項普世性的基督徙活動。

　　第二，先知職事的精髓意味著將啟示的真理應用出來，而不是增加神的啟示。一如舊約先知傳講律法，呼籲以色列人面對神與他們所立的約的順服要求，不然，就要受咒詛，同樣，新約先知傳講福音和信心的生命，看來是為了叫人悔改，造就人和鼓勵人。同理，任何藉言語加強聖經教導，以應用於聽者身上的方式，在今日大概可以正確地稱之為預言。

　　第三，保羅指導信眾在聚會中聽基督徒先知說話時，該「……慎思明辨」（林前一四 29），可見新約裏潛在的普世性預言，並非絕無謬誤，至少也有斟酌的餘地。意思是，我們要用辨識力來聆聽。

　　最後，預言應對人的行為產生的唯一影響，就是驅使人作好心理準備，以迎接預言的應驗，同時也準備好面對預言的不應驗。可是，行動的準則，必須是神啟示的話語和靠這話語管理生命的智慧。

　　我們應該明白到其實自有教會以來，預言一直不斷展現在每一篇發人深省，並切合聽眾需要的講章或非正式的「訊息」內。不論何時何地，只要聖經真理被真誠地傳講出來——意思是，真理被講解、詮釋和應用，不論是在講壇上或是非正式的分享——，就已經是預言了。然而，為此以為這種表現本質上與基督徒一貫為人所熟悉的（正式與非正式的）鼓勵和勸誡截然不同，從而把他認定為新約表記恩賜在今天的復甦，這樣的想法是不正確的。

[[Keep_in_Step_With_the_Spirit__orig.org#預言的恩賜][本文連結]]　　　
[[Keep_in_Step_With_the_Spirit__notes.org#目錄][目錄連結]]

** 對複還論神學思想的裁決
　　我們不能憑以上任何證據，而叫人信服地總結說，新約原初的靈恩經驗，消失了一段長時間之後，已經原原本本的再次賜給教會了。亦無需對以下可能根本沒有答案的問題表達意見，就是到底神在使徒職事完結之後，撤回所謂表記恩賜，是否代表他在任何情況底下都不會把這恩賜恢復呢？

　　如果團體相信，標準的信徒經驗應該以使徒行傳第二章使徒的經驗為典範，對神自己、他在基督裏的愛和他賜予的能力（聖靈的膏抹）有一種更深的體會，並得著說方言的能力，那麼，團體的成員肯定會追尋且「尋獲」這種經驗。

[[Keep_in_Step_With_the_Spirit__orig.org#對複還論神學思想的裁決][本文連結]]　　　
[[Keep_in_Step_With_the_Spirit__notes.org#目錄][目錄連結]]

** 另一套神學理論

[[Keep_in_Step_With_the_Spirit__notes.org#目錄][目錄連結]]

*** 說方言
　　成聖過程的整體楷模，必然包括平穩地恢復人在完全自覺、理性的控制能力下，達致人格完全的統合。當我們更深地表現出聖經所說的誠懇、純一、專心一志等質素時，我們就更能控制自己。

　　聖靈可能要透過這種表面上理性控制的鬆懈，去強化信徒更深層面的自製能力；心煩意亂的人，浸在浴缸裏，大聲哼無字句內容的歌，有助恢復健全的理性。若然說方言的效果真的為要加劇讚美及禱告的情緒，並使這些情緒持續，那麼，說方言可以幫助培養正面的性格，引領人進入密契禱告（mystical prayer）宣導者所稱的默觀（contemplation）裏。（可是，對其他擁有不同問題的人來說，神已經幫助他們自心裏向神發出通達的禱告，說方言對他們來說，遂變為不屬靈、瑣碎和不著邊際了）

[[Keep_in_Step_With_the_Spirit__orig.org#說方言][本文連結]]　　　
[[Keep_in_Step_With_the_Spirit__notes.org#目錄][目錄連結]]

** 結論
*** 4_說方言
　　有些人嘗試說方言這樣操練， 之後見證說發現自己所做的毫無屬靈實質，然而另有些人開始了這種操練後，結果卻經歷與神更深的相交；我們無理由懷疑他們任何一方面的見證。不應該將自己的方式強加於別人身上，也不應該因為別人與自己不同而貶抑他人遜於自己，同時若然在自己的陣營中有人因著相信是神的帶領而轉移到對方的陣營之中，亦無需為此信心動搖。用方言禱告及不用方言禱告的人都同是向主禱告；即使今日的說方言者不同于昔日哥林多信徒所說的方言，我們也不應該禁止他們說方言，而說方言者亦不應該認定好的基督徒必需說方言。

[[Keep_in_Step_With_the_Spirit__orig.org#4_說方言][本文連結]]　　　
[[Keep_in_Step_With_the_Spirit__notes.org#目錄][目錄連結]]

