#+TITLE:《活在聖靈中 Keep in Step with the Spirit》 巴刻J．I．Packer著 /霍玉蓮譯
#+TITLE: 巴刻J．I．Packer著 /霍玉蓮譯

* 目錄
 - [[#1_看清楚聖靈][1_看清楚聖靈]]
   - [[#蒙眼症][蒙眼症]]
   - [[#認識並經歷神][認識並經歷神]]
   - [[#聖靈的能力][聖靈的能力]]
     - [[#基督徒的能力][基督徒的能力]]
     - [[#能力的限制][能力的限制]]
   - [[#表現_屬靈恩賜的運用][表現_屬靈恩賜的運用]]
     - [[#總動員事奉][總動員事奉]]

* 1_看清楚聖靈
** 蒙眼症
　　市面上不是已經有許多關於聖靈的著作嗎？為什麼還要多添一本？這個問題問得正好，現在我要回答這個問題，就先從我的近視說起吧！

　　如果我除下眼鏡來看你，你在我眼中便蒙朧不清，我應該仍然知道你的存在，我大約仍可分辨你是男是女，我也許不至糊塗得把你撞個滿懷。但在我眼中，你的線條不是清晰可辨，你的容貌變得模糊不清（除了靠記憶外），我絕對無法清楚形容你。假使在我除下眼鏡時，一個陌生人走進我的房間，無疑我可以指出他來，但他的臉孔將會是模糊的一團，我無法知道他臉上的表情。我若不戴回眼鏡，你和他都會輪廓不明。
　
　　加爾文有一個很特別的比喻，他說像我這類眼濛濛的人，需要配戴眼鏡，去將物象對焦，同樣，我們所有人都需要聖經的裝備，幫助我們體會神的實在。雖然加爾文是一般性地運用這個比喻，但我相信在他腦海中，他必會想到以一些特殊真理作為鏡片，來獲致清晰的焦點。加爾文認為每個人都會對真實的神有概略的認識，但這些認識多半是含混模糊的。看清楚神是指對他的性格、他的主權、他的救贖、他的慈愛、他的兒子、他的聖靈和他的作為有正確的認識，亦即是對我們與他的關係有正確的瞭解——我們些受造物，究竟是活在罪中或恩典裏？在信、望、愛的生命中與他相交，或在枯竭、幽暗的心靈中與他隔絕？我們怎樣才能夠對這些事情有正確的認識呢？加爾文的答案是（我的也是一樣）：從聖經中學習。惟有從聖經中學習，我們才能夠清楚認識神，而他在我們腦海中的形象，也就不再模糊不清；我們可以聲稱他是三位一體的創造主，是聖父、聖子和聖靈。
　
　　好了，我現在要清楚指出我寫這些篇章的目的。正如我已經說過，今天聖靈大受注目，眾人所關注的，是他的身分，以及他在個人、教會及社群中做些什麼工作。團契、肢體生活。總動員事奉、聖靈的洗、恩賜、神的引導、預言、神跡，以及聖靈的啟示、更新和復興工作等題目，都常常掛在許多人的嘴邊，也在許多書本中討論過。這誠然是好的，我們應該為此感到快樂；反之，若然我們沒有討論這些題目，可能反映出我們在屬靈方面出了問題。然而正如近視漢看不清眼前的景物一樣，又好比任何人都會在一些事情上捉錯用神，對事物的真相只知其一，不知其二，因此，我們雖然經常頌揚聖靈的工作，但往往未能按聖經認識聖靈。對屬靈的事物，我們真個是濛濛眼，大受自己的偏見左右，以致我們沒法看得清楚。
　
** 認識並經歷神
　　我們很容易作出如此的假定：既然我們認識聖靈在我們生命中的一些作為，我們就已經完全認識聖靈。很抱歉，結論並不是這樣。事實上，正如一個人的概念知識可以遠超過他的屬靈經驗，同樣，屬靈經驗也可以走在概念知識的前頭。相信聖經的人經常強調需要有正確的概念知識，以致他們忽略了上述的情形。但事實確是如此，耶穌門徒的經驗就是很好的例子。耶穌在世上的時候，門徒追隨他，但他們對屬靈事物的理解常有錯漏，而且經常對耶穌有許多誤解；可是，耶穌能夠超越他們思想上的限制，感動他們、改變他們的生命，純粹是由於他們愛他、信靠他，希望從他身上學習，誠心願意追隨他們心中的亮光去服從他。因此，十二個門徒中有十一個「已經乾淨了」（意思是他們的罪得赦免，心靈獲得更新「約一五 3」），並且得與其他人一起進入耶穌恕宥和平安的恩典中（參路五 20 一 24，七 47—50，一九 5 一 10），而那時他們尚未能掌握耶穌釘十架的贖罪意義。神首先賜下救恩的禮物，改變他們的生命，其後他們才明白這是什麼一回事。
　　
　　同時，當這些人對神充滿信心，並願意敞開心靈去明自神的旨意時，他們便追求更完全活在聖靈裏的生命。（這是極其自然的！難道我們不曉得追求從聖靈而來的生命和追求從耶穌而來的生命，事實上是同一回事，只是名目不同而已？）我在這裏提出的，就是要著意尋求聖經教導我們去尋求的東西。既然神是言而有信的，我們便有把握期望我們所求的必然得著——我們更會發現臨到我們身上的美好恩賜，常是超過我們所想求的。主耶穌說：「你們祈求，就給你們；……你們……尚且知道拿好東西給兒女況天父，豈不更將聖靈給求他的人嗎？」（路—— 9、13）許多曾這樣祈求的人，都被神豐足的回應嚇了一跳。
　　
　　神是滿有恩慈的，只要我們以真誠的態度，全心全意尋求他的臉，希望與他親近，即使我們對何謂屬靈生命沒有認識，或只有錯誤的觀念，他都可以使我們靈裏的生命進深。在這要應用得著的公式是耶利米書二十九章十三、十四節的應許：「你們尋求我，若專心尋求我，就必尋見。……。然後，我們的責任就是要透過聖經的亮光，瞭解主實際上為我們做了什麼，並且瞭解他在我們個人經歷中的特別工作如何與聖經所說他透過聖靈為屬他的人作事的宣稱相關。因著主的慈愛，他在我們經歷中的作為都是匠心獨運地符合各人性格和環境上的需要。在我看來，這項工作是許多神的子民的當前急務。
　　
　　請勿誤會我！我並不是說神賜福於那些無知和錯謬的人，是由於他們的無知和錯謬；我也不是說神不在意我們是否認識和掌握他所啟示的旨意；更不是說一個人只要對神有誠懇的心和真摯的情感，就不怕無知和錯謬會損害他靈命的健康。我們可以肯定地說，神賜給信徒的福氣，是絕對而不變地按著他的真理賜下的；錯誤的信仰意味著屬靈的貧乏，對靈性更會造成嚴重損害。可是，任何接觸人心靈的人，總是一次又一次地因神奇妙的作為而大感驚訝，因為神豐豐富富地賜福給靈性貧乏的人，使這些有大堆錯謬思想，只認識一點點真理的人，大大改變過來。正如我曾經說過，無數罪人在他們對耶穌和聖靈尚未有正確的認識時，就已經真實地經歷耶穌基督的救恩和聖靈使生命更新的能力。（說句實話，若然神要等待我們有完全正確的屬靈觀念，才賜下福氣，那麼，我們現在真不知處於何等光景了！幾乎每個基督徒都曾經歷神豐厚的恩惠和幫助，而神的賜予，總遠遠超過他們的思想所配得的。）儘管如此，我們若對聖靈有較清晰的觀念，就更能欣賞聖靈的工作，以及避免墮入一些錯謬的陷阱。這正是本書嘗試提供的幫助。
　　
　　我的思潮又回到二十年前一個潮濕的下午，那時我正趕著去一間渾名為「蚤子窩」的橫街電影院，以先睹為快的心情去觀看一出剛到埠的著名默片「大將軍」（“TheGeneral”）。這出電影於一九二七年攝製，今日的影評人盛讚他是基頓（BusterKeaton）的代表作。當時我剛剛發現這樣一個憂鬱、品格高尚、容易遇上不幸、優柔寡斷、足智多謀的諧角基頓，因此「大將軍」深深地吸引著我。該故事發生於美國內戰時期，於是我順理成章地猜想這出電影必然像基頓其他一些電影一樣，片名已說明他的角色了。我並不是戰爭片迷，記得在步向電影院途中，我還在揣測這出電影會如何吸引我。
　　
　　沒錯，在「大將軍」一片中，基頓最後真正穿上了制服——準確一點說，是穿上陸軍中尉的制服——可是，若因此稱基頓為一位肩負領導責任的將軍，那真是極之誤導，而且有點不盡不實，因為基頓只是在最後的幾分鐘才得到他的制服，而在這片段之前的整整七十分鐘裏，展現眼前的不是模仿軍中生活的諷刺劇，而是一個古老蒸氣火車頭的故事。那是一部名貴、笨重、設有排障器的 4—4—0 型火車頭。故事安排火車頭被人取了，促使那不怕死活的司機驟然成為機智的英雄人物，展開一夫當關的神勇拯救行動，從而引發出不少瘋狂笑料。後來他拯救成功，所得的報酬就是獲得他渴慕已久的軍官身分；在此之前，他因為不能當上軍官，女朋友不願理睬他。原來「大將軍」就是那部火車頭的名稱。故事改編自一八六三年的大火車頭追逐事件，當時，真正的「大將軍」（火車頭）在喬治亞州瑪利安達被北方破壞者搶奪，在火車快要駛進北方疆域之際，剛好燃料用盡，終於成功地被追蹤奪回。對於我這個鬧劇迷兼火車在來說，當時是完完全全被迷住了。
　　
　　我想指出的，就是今天很多人殷殷暢論聖靈的工作及活在聖靈中的真實經歷，但其中一些觀念比對於事實真相，就差不多像我對「大將軍」一名先入為主的臆測一樣。請跟我察看一些有關觀念，讓我表明我說的到底是什麼意思吧！
　　
** 聖靈的能力
　　首先，許多人認為聖靈的教義基本上與能力有關，意思是神賜予能力，讓你可以做你應該做卻感有心無力的事情，例如：拒絕物欲的追求（諸如美色、煙、酒、毒品、金錢、刺激、奢華的生活、晉升機會、權力、名望、諂媚奉承等等）。容忍那考驗你耐性的人、愛那不可愛的人、控制脾氣、在壓力中站立得穩、為基督勇敢發言、在遭逢患難中仍信靠神。聖靈賦予人能力達致上述的種種表現，無論在思想上、言語上、講章及禱告裏，這主題都為人所津津樂道。
　　
　　然則我們對這些人所強調的有什麼異議嗎？他們的觀點是否錯誤？不是，絕對不是；情形剛好相反，這觀念本身是堂而皇之的正確。因為能力（power）一詞（通常相當於希臘文的 dunamis，由此引伸為英文的 dynamite，有時相當於 kratos 和 ischus）是一個重要的新約辭彙，而基督藉聖靈賦予信徒能力，確是新約中重大的事實，是福音裏的榮耀，也是世界各地忠實追隨基督的人的標記。如果你對我這番話產生疑問，你大可細讀以下
經文：
　　
　　耶穌曾把大使命託付門徒，叫他們將福音傳遍天下，並對他們說：「你們要在城裏等候，直到你們領受從上頭來的能力。」「但聖靈降臨在你們身上，你們就必得著能力 ……」（路二四 49；徒一 8）在五旬節，聖靈被澆灌下來時，「使徒大有能力，見證耶穌復活……」（徒四 33）同時，「司提反滿得恩惠、能力，在民間行了大奇事和神跡。」（徒六 8；另參閱彼得形容耶穌的相類似經文：「神怎樣以聖靈和能力膏拿撒勒人耶穌……」「徒一○38」）路加在這些經文裏告訴我們，從起初，福音就是靠著聖靈的能力傳揚開去。
　　
　　保羅為羅馬教會的人祈禱說：「……使你們藉著聖靈的能力，大有盼望。」（羅五 13）然後，他繼續談及基督透過他作的事情：「基督藉我作的那些事，……他藉語作為，用神跡奇事的能力，並聖靈的能力……」（羅一五 18、19）；他又提醒哥林教會的信徒，他傳講基督釘十字架，「……乃是用聖靈和大能的明證；叫你們的信……只在乎神的大能。」（林前二 4、5；另參閱林後六 6—10，一○4— 6；帖前一 5，13）當保羅感到有一根剌加在他肉體上時，他寫道：基督「對我說：『我的恩典夠你用的，因為我的能力是在人的軟弱上顯得完全。』所以，我更喜歡誇自己的軟弱，好叫基督的能力覆庇我。」（林後一二 9，另參閱四 7）他又對提摩太說，神賜給基督徒的「是剛強（power）、仁愛、謹守的心」，並指責那些「愛宴樂，不愛神，有敬虔的外貌，卻背了敬虔的實意（ power）」的人（提後一 7，三 4、5）。他說基督給予信徒能力（endunamoo，dunamoo，krataioo），使信徒能達成本來單憑己力是永遠無法辦到的事情（弗三 16，六 10，另參一 19 一 23；西一 11；提前一 12；提後四 17；另參林後一二10；彼前五 10）。並且，當他處身獄中，性命危在旦夕之時，卻發出勝利的呼喊：「我靠著那加給我力量的，凡事（意指神呼召他去做的一切事）都能作。」（腓四 13）無庸置疑，這一切都說明瞭聖靈是帶來能力的。我們受教導知道靠著超自然的能力去過超自然的生活，是整個新約基督教信仰的核心，故此，那些自稱信奉基督教的人，若不曾經歷能力的澆灌，也表現不出他們擁有這種能力，那麼照新約聖經的標準看來，他們的信仰是值得懷疑的。儘管人以基督為信徒得力的唯一源頭，能力的澆奠往往是聖靈的工作，而人只提基督，是因為基督賜下聖靈（約一 33，二 O22；徒二 33）。因此，能力是透過聖靈從基督而來；無論何時何地，誰人傳授基督教道理，都應該特別重視這個真理。
　　
　　過去三百多年來，福音派信徒一直仰賴神的應許，不斷向神支取能力來生活。我們應該為此感到高興，因為這種能力的賜予不單是聖經裏的一個重要主題，他還針對人類一個明顯而普遍的需要。凡肯誠實面對自己的人，都不時會因自己內心一份強烈的不足感而不知所措。所有基督徒都會一次又一次窘迫地呼喊：「主啊，幫助我，堅固我，扶持我，賜我能力，好讓我所言所行都能取悅你，令我剛強壯膽，有充足的力量面對種種壓力和要求。」

　　我們是被召去戰勝那惡者，他常以種種形態出現在我們心裏，或圍繞我們。我們需要知道在這一場爭戰裏，只有靠著聖靈的能力，才能獲取勝利；反之，若完全靠賴自己，最後只會發現自己的無能和經驗挫敗，引致痛苦。所以，福音信仰強調藉著聖靈而達致成聖是一件真實而又必需的事，這個教導永遠都切合時宜。
　　
*** 基督徒的能力
　　十七世紀時期，清教徒首先強調聖靈如何在人的生命中彰顯能力；可是，到了十八世紀，這種教導竟變成了福音派信徒間爭辯的主題，當時衛斯理（ John Wesley）開始提出一種教義，說聖靈會把人的罪從人心靈中連根拔起。這就是衛斯理所指的「合乎聖經的聖潔」，他相信神興起循道主義（Methodism）去宣揚這個教導。非衛理公會信徒對這種教訓退避踟躕，覺得他很虛妄，而且不合乎聖經，所以他們不斷警告自己教會的會友要防備這種思想。然而到了十九世紀中葉，反對的鐘擺搖晃到了另一個極端；許多人感到（不論他們的想法是否正確）這股反完全主義的熱潮令基督徒完全遺忘了神有能力拯救人脫離罪，他能使人過一個平靜、得勝而公義的生活，他亦能夠使講員的資訊直透人心靈深處。忽然之間，人得勝的能力頓成為講章、書籍和非正式小組討論的話題（他們稱這些小組討論為「閒談聚會」），遍及大西洋兩岸。龐馬（Phoebe Palmer）、馬漢（Asa Mahan）、史密夫（ RobertPearsall Smith）、漢娜·韋杜（ Hannah Whitall Smith）、賀堅斯（ Evan Hopkins）、慕安德列（ Andrew Murray）。叨雷（R．A．Torrey）、特榮布林（ Charles G．Trumbull）。麥奇堅（ Robert C．McQuilkin）、梅亞（F．B．Meyer）、慕耳（H．C.G．Moule）等人所致力宣告的信徒得力「秘訣」（“secret”，這是他們採用的字眼），被高舉為新的啟示。事實上，宣告這些道理的前們也如此相信。一個嶄新的福音信仰運動已經展開了。

　　這個得力的「秘訣」，有時也稱為「高超生命」或「得勝生活」的秘訣，已經在英倫一年一度為期一周的凱錫克培靈會（Keswick Convention）中，全面制度化地推展了，一如爵士樂隊的主要節目安排一樣，一直以來這個培靈會的各個聚會都有固定編排，星期一的主題是罪惡，星期二的主題是那拯救我們脫離罪惡的基督，星期三是奉獻，星期四是在聖靈裏的生命，星期五是成聖者滿有能力的事奉（尤其是在宣教事工上）。及後，一份凱錫克期刊在一八七四年創刊，名為《基督徒得力之途》（The Christian Pathway of Power）。五年後，刊物名稱改為《信心的生命》（The Life of Faith)，但名稱的改換並不代表期刊的性質有任何更改，仍依據凱錫克培靈會的教導，以信心就是得力之途為主題。凱錫克塔靈會的影響是世界性的，「凱錫克信徒。勃興於全世界所有以英語為地方語言的角落。「凱錫克培靈會的教導已經被視為近期教會歷史中一股最有潛力的屬靈力量。」1「凱錫克型」的講員，專門在大會上宣講能力的資訊，他們已成為一群獨特的福音信仰牧者，與福音信仰學者、聖經教師和講論預言性主題的講員並駕齊驅。凱錫克資訊經過制度化，又獲得欣賞凱錫克精神（平穩、愉快、節制、吹毛求疵等特性都非常迎合中產階級人士的喜好）的人支持；所以，凱錫克培靈會中有關成聖和事奉能力的資訊自然縈繞人心。

　　這種講論能力的主題也不是近年唯一的發展。基督的能力不單能夠赦免我們的罪，而且藉著聖靈，可拯救我們脫離罪惡的奴役。有如第一世紀一樣，這個資訊已再次成為教會福音資訊的主要部分。對於城市化的西方人來說，他們面對的邪惡，是具破壞性的惡習；對於較落後的部落社群來說，他們面對的邪惡就是邪靈的勢力。至於較古老的福音資訊，由於他強調律法、罪惡、審判和基督代贖受死的榮耀，誠然可以補充今天福音資訊的缺欠。可是整體來說，古老的福音資訊很少論及能力；從這方面看來，他的確是有些遜色了。

　　既然神應允和賜予能力是千真萬確的事，那麼能力的主題如此受到重視，誠然是一件值得欣喜的事。事實上，強調能力的資訊不管透過什麼形式表達出來，今天已成為基督教福音信仰主流的標記，與世界性的靈恩運動並駕齊驅；這無疑是一個對未來充滿希望的徵兆。
　　
*** 能力的限制
　　然而，在慶倖今天有許多關乎能力的講論之餘，我們也不無憂慮；因為經驗告訴我們，當我們思想聖靈時，若只集中注意能力這個主題，而沒有一個更具深度的觀點，沒有從另一個中心主題去看聖靈的職事，那麼，扭曲的觀念很快就悄悄潛入我們的思想裏。什麼是扭曲了的觀念呢？好，讓我拿以下的例子來開始吧！當一個人經常尋求力量去駕馭生活上的大小事情時，他會虔誠地專注自己心靈的起伏，因而產生一種自我中心和內向的心態，以致對社群的福利和社會的需要漠不關心。當人論及聖靈的工作時，往往傾向於以人為中心，就好像神的能力是一些隨時儲備妥當的東西，只要運用思想和意志——通常美其名為奉獻和信心——就可以開關「使用」（這是凱錫克培靈會的常用語）同時，這種態度形成一種觀念，認為只要我們肯釋放自己內在的能力，神的能力就會在我們心裏自動地運行，因此，我們可以隨時按著自己奉獻和信心的程度來調節這種能力。另一個隨之浮現的觀念，就是以為必須處於內在的被動狀態中，完全等候神的能力帶領我們（「放下自己，讓神工作」是流行得太響的口號）。同樣，在某些圈子的佈道工作裏，差不多形成了一種慣例，就是為心靈空虛的人提供一種「生活的力量」。表面上，就好像只要人肯委身基督，他立刻可以獲得發動和操縱能源的權利。

　　可是，這一切聽起來似乎較像瑜珈，甚於以聖經真理為基礎的基督教信仰。首先，這些觀念混淆了憑己意去擺佈神的能力（這是法術，西門的表現就是一個例子「徒八 18-24）和因著順服神的旨意而經歷神的能力（這是宗教，保羅的表現就是很好的例子「林後一二 9、10」）。再者，這些觀念是不切實際的。佈道家們的講章經常暗示一件事實，就是我們一旦成為基督徒，神在我們裏面的能力就可以立時除去我們性格上的任何弱點，令我們生活一帆風順；可是，這種說法是違背聖經，甚至是不誠實的。當然，神有時候可以施行奇跡，令悔改的人忽然改變過來，從這些或那些弱點中得釋放，即如其他時候，他亦會偶然施行神跡奇事一樣；然而，每個基督徒的生命都是一場持久戰，要不斷對抗來自世界、肉體和魔鬼的種種試誘和壓力；同時，那追求活像基督（即是智慧、忠心、愛心和公義的生活）的爭戰是嚴苛的，是永不停息的。在佈道中宣揚相反的現實，就無寧是一種騙取信心的技倆。同樣，凱錫克培靈會中的講論，經常鼓勵我們一時間對自己有過高及過低的期望——每時每刻完全脫離罪的纏累，是期望過高；另一方面，沒有動機去期望能夠逐步擺脫罪對我們心靈的轄制，就是期望過低。這是一種拙劣的神學，而且在心理和精神上都不符現實。我這些意見若早在一九五五年發表，一定會犯眾怒了，但在今天，我相信這些見解會較普遍受到接納。

　　討論下去，你就會漸漸明白我們真正的問題是需要對聖靈的教義有深刻而真確的洞見——這洞見的亮光能促使我們糾正對內在能力的謬說。不過，我打算暫且擱下這部分的論據，待我完成對聖靈問題的初步探討後才再談他。在目前的探討裏，我們只要記著一點，就是只談聖靈能力，根本不能針對問題的核心。

** 表現_屬靈恩賜的運用
　　其次，許多人認為聖靈的教義基本上與表現有關，意思是運用屬靈恩賜。對這些人來說，聖靈的職事似乎由始至終只是關乎如何運用恩賜——講道、教導、說預言、說方言、醫治等等。他們認為根據新約聖經的教導，恩賜（charismata）是神所賜予的某些能力，尤其是藉著言語、行為和態度，把關乎耶穌基督的真理傳遞開去，彼此激勵，互相服事。他們又認為「……聖靈顯在各人身上……」（林前一二 7），恩賜是藉著行以辨認的，基督徒所表現出來的行為，正顯明瞭神賜予他們什麼能力。因此，他們認為屬靈生命的實質在乎表現，同時假設人愈能表現恩賜，就表示他愈被聖靈充滿。
*** 總動員事奉
　　對於這種觀點——或更貼切地稱為心態，我首先要說明一點，就是他所強調的教本身同樣是絕對正確的；這次是強調恩賜的實在，以及運用恩賜的重要。曆世以來，教會以為事奉的恩賜只屬於一小部分基督徒專有（例如好的牧師和其他少數人），因此，他們並不十分注意恩賜這個題目。二十世紀以前，有關屬靈恩賜的全面研究，只有一本英文著作，由清教徒歐文（John Owen）於一六七九至一六八 O 年寫成。近期所強調屬靈恩賜的普遍性，以及神對教會總動員事奉的期望，其實早就應該提出，因為新約聖經對這兩方面的教導是相當清楚和明顯的。這裏引述一些主要經文。
　　
　　「恩賜『charisznata』原有分別，聖靈卻是一位。職事『diakonia』也有分別，主卻是一位。功用『energemata』也有分別，神卻是一位，在眾人裏面運行一切的事。」（林前一二 4 一 6）「我們各人蒙恩，都是照基督所量給各人的恩賜……凡事長進，于元首基督；全身……照著各體的功用彼此相助，便叫身體漸漸增長，在愛中建立自己。」（弗四 7、15、16）「各人要照所得的恩賜彼此服事，作神百般恩賜的好管家。」（彼前四 10）「正如我們一個身子上有好些肢體，肢體也不都是一樣的用處。我們這許多人，在基督裏成為一身，互相聯絡作肢體，也是如此。按我們所得的恩賜，各有不同。……」（羅一二 4—6）並非只有聖品人員及有職分的才具有恩賜，所有基督徒 都具有恩賜，牧者必須認識這個事實，並運用自己的恩賜去裝備平信徒運用他們的恩賜。「他所賜的，有使徒，有先知，有傳福音的，有牧師和教師；為要成全聖徒，各盡其識，建立基督的身體」（弗四 11、12）。

　　英文聖經的敘定譯本（ King James Version）掩蓋了保羅在此處的含義，把他翻譯為基督所賜的有使徒、先知、傳福音的、牧師和教師，「為了成全聖徒，為要各盡其職，為要建立基督的身體」（“for　the　perfecting　of　the　saints，for thework of ministry， for the edifying of the Body of Christ”［King James Version］）。乍看來，這三句平衡的句語好像都是聖品人員蒙召的職責。第六世紀的聖經版本遺漏了第七條誡命中的不字（出二○14），在歷史中流傳下來，被稱為邪惡的聖經版本；這裏英文聖經欽定譯本在「聖徒」（“saints”）之後加上了一個逗點，也同樣產生不良的效果。因為這個逗號將「職事」的範圍局限了，成為只有在位的領袖才可擔當，這不但隱藏了保羅的意思，簡直將保羅的意思顛倒過來，使本來是肢體各盡其職的成為教權主義（clericalism）。（這裏的「教權主義。是一種陰謀和專橫的結合，在其中，牧者宣稱所有屬靈職事都是他個人的責任，不是會眾的責任，而會眾亦同意這種想法。這個觀念在原則上很有問題，實踐起來更會導致聖靈的感動被銷滅。）
　　
　　其實，自上個世紀中葉開始，普利茅斯弟兄會（ Plymouth Brethren）已宣告恩賜的普及性和肢體應各盡其職，但由於他們的宣告摻雜在一種反動性的爭論裏——當時的論，是針對一些在被指為背離真道的教會裏事奉、受薪並曾受訓練的聖品人員——，們的宣告沒有受到多大注意。可是，近年來普世教聯運動和靈恩運動都抓緊這方面的聖經真理，使之漸漸成為基督教的老生常談，因而產生了一些可喜的效果。其中一個效果，就是許多地區的教會紛紛願意在教會生活中實驗新的制度及新的禮儀形式，讓信徒有機會完全發揮他們的恩賜，令會眾整體受益；隨之興起的，是以一種認真的態度，去檢討傳統的崇拜程式和形式，以保障沒有任何恩賜受到窒礙，甚至銷滅聖靈的感動。這一切都是好現象。
　　
