#+TITLE:《活在聖靈中 Keep in Step with the Spirit》巴刻(J．I．Packer)著/霍玉蓮譯
#+AUTHOR:巴刻J．I．Packer著/霍玉蓮譯

* 目錄
 - [[#1_看清楚聖靈][1_看清楚聖靈]]
   - [[#蒙眼症][蒙眼症]]
   - [[#認識並經歷神][認識並經歷神]]
   - [[#聖靈的能力][聖靈的能力]]
     - [[#基督徒的能力][基督徒的能力]]
     - [[#能力的限制][能力的限制]]
   - [[#表現_屬靈恩賜的運用][表現_屬靈恩賜的運用]]
     - [[#總動員事奉][總動員事奉]]
     - [[#正確地看表現][正確地看表現]]
   - [[#保守我們純潔][保守我們純潔]]
     - [[#道德掙紮教義的陷阱][道德掙紮教義的陷阱]]

* 1_看清楚聖靈
** 蒙眼症
　　市面上不是已經有許多關於聖靈的著作嗎？為什麼還要多添一本？這個問題問得正好，現在我要回答這個問題，就先從我的近視說起吧！

　　如果我除下眼鏡來看你，你在我眼中便蒙朧不清，我應該仍然知道你的存在，我大約仍可分辨你是男是女，我也許不至糊塗得把你撞個滿懷。但在我眼中，你的線條不是清晰可辨，你的容貌變得模糊不清（除了靠記憶外），我絕對無法清楚形容你。假使在我除下眼鏡時，一個陌生人走進我的房間，無疑我可以指出他來，但他的臉孔將會是模糊的一團，我無法知道他臉上的表情。我若不戴回眼鏡，你和他都會輪廓不明。

　　加爾文有一個很特別的比喻，他說像我這類眼濛濛的人，需要配戴眼鏡，去將物象對焦，同樣，我們所有人都需要聖經的裝備，幫助我們體會神的實在。雖然加爾文是一般性地運用這個比喻，但我相信在他腦海中，他必會想到以一些特殊真理作為鏡片，來獲致清晰的焦點。加爾文認為每個人都會對真實的神有概略的認識，但這些認識多半是含混模糊的。看清楚神是指對他的性格、他的主權、他的救贖、他的慈愛、他的兒子、他的聖靈和他的作為有正確的認識，亦即是對我們與他的關係有正確的瞭解——我們些受造物，究竟是活在罪中或恩典裏？在信、望、愛的生命中與他相交，或在枯竭、幽暗的心靈中與他隔絕？我們怎樣才能夠對這些事情有正確的認識呢？加爾文的答案是（我的也是一樣）：從聖經中學習。惟有從聖經中學習，我們才能夠清楚認識神，而他在我們腦海中的形象，也就不再模糊不清；我們可以聲稱他是三位一體的創造主，是聖父、聖子和聖靈。

　　好了，我現在要清楚指出我寫這些篇章的目的。正如我已經說過，今天聖靈大受注目，眾人所關注的，是他的身分，以及他在個人、教會及社群中做些什麼工作。團契、肢體生活。總動員事奉、聖靈的洗、恩賜、神的引導、預言、神跡，以及聖靈的啟示、更新和復興工作等題目，都常常掛在許多人的嘴邊，也在許多書本中討論過。這誠然是好的，我們應該為此感到快樂；反之，若然我們沒有討論這些題目，可能反映出我們在屬靈方面出了問題。然而正如近視漢看不清眼前的景物一樣，又好比任何人都會在一些事情上捉錯用神，對事物的真相只知其一，不知其二，因此，我們雖然經常頌揚聖靈的工作，但往往未能按聖經認識聖靈。對屬靈的事物，我們真個是濛濛眼，大受自己的偏見左右，以致我們沒法看得清楚。

** 認識並經歷神
　　我們很容易作出如此的假定：既然我們認識聖靈在我們生命中的一些作為，我們就已經完全認識聖靈。很抱歉，結論並不是這樣。事實上，正如一個人的概念知識可以遠超過他的屬靈經驗，同樣，屬靈經驗也可以走在概念知識的前頭。相信聖經的人經常強調需要有正確的概念知識，以致他們忽略了上述的情形。但事實確是如此，耶穌門徒的經驗就是很好的例子。耶穌在世上的時候，門徒追隨他，但他們對屬靈事物的理解常有錯漏，而且經常對耶穌有許多誤解；可是，耶穌能夠超越他們思想上的限制，感動他們、改變他們的生命，純粹是由於他們愛他、信靠他，希望從他身上學習，誠心願意追隨他們心中的亮光去服從他。因此，十二個門徒中有十一個「已經乾淨了」（意思是他們的罪得赦免，心靈獲得更新「約一五 3」），並且得與其他人一起進入耶穌恕宥和平安的恩典中（參路五 20 一 24，七 47—50，一九 5 一 10），而那時他們尚未能掌握耶穌釘十架的贖罪意義。神首先賜下救恩的禮物，改變他們的生命，其後他們才明白這是什麼一回事。

　　同時，當這些人對神充滿信心，並願意敞開心靈去明自神的旨意時，他們便追求更完全活在聖靈裏的生命。（這是極其自然的！難道我們不曉得追求從聖靈而來的生命和追求從耶穌而來的生命，事實上是同一回事，只是名目不同而已？）我在這裏提出的，就是要著意尋求聖經教導我們去尋求的東西。既然神是言而有信的，我們便有把握期望我們所求的必然得著——我們更會發現臨到我們身上的美好恩賜，常是超過我們所想求的。主耶穌說：「你們祈求，就給你們；……你們……尚且知道拿好東西給兒女況天父，豈不更將聖靈給求他的人嗎？」（路—— 9、13）許多曾這樣祈求的人，都被神豐足的回應嚇了一跳。

　　神是滿有恩慈的，只要我們以真誠的態度，全心全意尋求他的臉，希望與他親近，即使我們對何謂屬靈生命沒有認識，或只有錯誤的觀念，他都可以使我們靈裏的生命進深。在這要應用得著的公式是耶利米書二十九章十三、十四節的應許：「你們尋求我，若專心尋求我，就必尋見。……。然後，我們的責任就是要透過聖經的亮光，瞭解主實際上為我們做了什麼，並且瞭解他在我們個人經歷中的特別工作如何與聖經所說他透過聖靈為屬他的人作事的宣稱相關。因著主的慈愛，他在我們經歷中的作為都是匠心獨運地符合各人性格和環境上的需要。在我看來，這項工作是許多神的子民的當前急務。

　　請勿誤會我！我並不是說神賜福於那些無知和錯謬的人，是由於他們的無知和錯謬；我也不是說神不在意我們是否認識和掌握他所啟示的旨意；更不是說一個人只要對神有誠懇的心和真摯的情感，就不怕無知和錯謬會損害他靈命的健康。我們可以肯定地說，神賜給信徒的福氣，是絕對而不變地按著他的真理賜下的；錯誤的信仰意味著屬靈的貧乏，對靈性更會造成嚴重損害。可是，任何接觸人心靈的人，總是一次又一次地因神奇妙的作為而大感驚訝，因為神豐豐富富地賜福給靈性貧乏的人，使這些有大堆錯謬思想，只認識一點點真理的人，大大改變過來。正如我曾經說過，無數罪人在他們對耶穌和聖靈尚未有正確的認識時，就已經真實地經歷耶穌基督的救恩和聖靈使生命更新的能力。（說句實話，若然神要等待我們有完全正確的屬靈觀念，才賜下福氣，那麼，我們現在真不知處於何等光景了！幾乎每個基督徒都曾經歷神豐厚的恩惠和幫助，而神的賜予，總遠遠超過他們的思想所配得的。）儘管如此，我們若對聖靈有較清晰的觀念，就更能欣賞聖靈的工作，以及避免墮入一些錯謬的陷阱。這正是本書嘗試提供的幫助。

　　我的思潮又回到二十年前一個潮濕的下午，那時我正趕著去一間渾名為「蚤子窩」的橫街電影院，以先睹為快的心情去觀看一出剛到埠的著名默片「大將軍」（“TheGeneral”）。這出電影於一九二七年攝製，今日的影評人盛讚他是基頓（BusterKeaton）的代表作。當時我剛剛發現這樣一個憂鬱、品格高尚、容易遇上不幸、優柔寡斷、足智多謀的諧角基頓，因此「大將軍」深深地吸引著我。該故事發生於美國內戰時期，於是我順理成章地猜想這出電影必然像基頓其他一些電影一樣，片名已說明他的角色了。我並不是戰爭片迷，記得在步向電影院途中，我還在揣測這出電影會如何吸引我。

　　沒錯，在「大將軍」一片中，基頓最後真正穿上了制服——準確一點說，是穿上陸軍中尉的制服——可是，若因此稱基頓為一位肩負領導責任的將軍，那真是極之誤導，而且有點不盡不實，因為基頓只是在最後的幾分鐘才得到他的制服，而在這片段之前的整整七十分鐘裏，展現眼前的不是模仿軍中生活的諷刺劇，而是一個古老蒸氣火車頭的故事。那是一部名貴、笨重、設有排障器的 4—4—0 型火車頭。故事安排火車頭被人取了，促使那不怕死活的司機驟然成為機智的英雄人物，展開一夫當關的神勇拯救行動，從而引發出不少瘋狂笑料。後來他拯救成功，所得的報酬就是獲得他渴慕已久的軍官身分；在此之前，他因為不能當上軍官，女朋友不願理睬他。原來「大將軍」就是那部火車頭的名稱。故事改編自一八六三年的大火車頭追逐事件，當時，真正的「大將軍」（火車頭）在喬治亞州瑪利安達被北方破壞者搶奪，在火車快要駛進北方疆域之際，剛好燃料用盡，終於成功地被追蹤奪回。對於我這個鬧劇迷兼火車在來說，當時是完完全全被迷住了。

　　我想指出的，就是今天很多人殷殷暢論聖靈的工作及活在聖靈中的真實經歷，但其中一些觀念比對於事實真相，就差不多像我對「大將軍」一名先入為主的臆測一樣。請跟我察看一些有關觀念，讓我表明我說的到底是什麼意思吧！

** 聖靈的能力
　　首先，許多人認為聖靈的教義基本上與能力有關，意思是神賜予能力，讓你可以做你應該做卻感有心無力的事情，例如：拒絕物欲的追求（諸如美色、煙、酒、毒品、金錢、刺激、奢華的生活、晉升機會、權力、名望、諂媚奉承等等）。容忍那考驗你耐性的人、愛那不可愛的人、控制脾氣、在壓力中站立得穩、為基督勇敢發言、在遭逢患難中仍信靠神。聖靈賦予人能力達致上述的種種表現，無論在思想上、言語上、講章及禱告裏，這主題都為人所津津樂道。

　　然則我們對這些人所強調的有什麼異議嗎？他們的觀點是否錯誤？不是，絕對不是；情形剛好相反，這觀念本身是堂而皇之的正確。因為能力（power）一詞（通常相當於希臘文的 dunamis，由此引伸為英文的 dynamite，有時相當於 kratos 和 ischus）是一個重要的新約辭彙，而基督藉聖靈賦予信徒能力，確是新約中重大的事實，是福音裏的榮耀，也是世界各地忠實追隨基督的人的標記。如果你對我這番話產生疑問，你大可細讀以下
經文：

　　耶穌曾把大使命託付門徒，叫他們將福音傳遍天下，並對他們說：「你們要在城裏等候，直到你們領受從上頭來的能力。」「但聖靈降臨在你們身上，你們就必得著能力 ……」（路二四 49；徒一 8）在五旬節，聖靈被澆灌下來時，「使徒大有能力，見證耶穌復活……」（徒四 33）同時，「司提反滿得恩惠、能力，在民間行了大奇事和神跡。」（徒六 8；另參閱彼得形容耶穌的相類似經文：「神怎樣以聖靈和能力膏拿撒勒人耶穌……」「徒一○38」）路加在這些經文裏告訴我們，從起初，福音就是靠著聖靈的能力傳揚開去。

　　保羅為羅馬教會的人祈禱說：「……使你們藉著聖靈的能力，大有盼望。」（羅五 13）然後，他繼續談及基督透過他作的事情：「基督藉我作的那些事，……他藉語作為，用神跡奇事的能力，並聖靈的能力……」（羅一五 18、19）；他又提醒哥林教會的信徒，他傳講基督釘十字架，「……乃是用聖靈和大能的明證；叫你們的信……只在乎神的大能。」（林前二 4、5；另參閱林後六 6—10，一○4— 6；帖前一 5，13）當保羅感到有一根剌加在他肉體上時，他寫道：基督「對我說：『我的恩典夠你用的，因為我的能力是在人的軟弱上顯得完全。』所以，我更喜歡誇自己的軟弱，好叫基督的能力覆庇我。」（林後一二 9，另參閱四 7）他又對提摩太說，神賜給基督徒的「是剛強（power）、仁愛、謹守的心」，並指責那些「愛宴樂，不愛神，有敬虔的外貌，卻背了敬虔的實意（ power）」的人（提後一 7，三 4、5）。他說基督給予信徒能力（endunamoo，dunamoo，krataioo），使信徒能達成本來單憑己力是永遠無法辦到的事情（弗三 16，六 10，另參一 19 一 23；西一 11；提前一 12；提後四 17；另參林後一二10；彼前五 10）。並且，當他處身獄中，性命危在旦夕之時，卻發出勝利的呼喊：「我靠著那加給我力量的，凡事（意指神呼召他去做的一切事）都能作。」（腓四 13）無庸置疑，這一切都說明瞭聖靈是帶來能力的。我們受教導知道靠著超自然的能力去過超自然的生活，是整個新約基督教信仰的核心，故此，那些自稱信奉基督教的人，若不曾經歷能力的澆灌，也表現不出他們擁有這種能力，那麼照新約聖經的標準看來，他們的信仰是值得懷疑的。儘管人以基督為信徒得力的唯一源頭，能力的澆奠往往是聖靈的工作，而人只提基督，是因為基督賜下聖靈（約一 33，二 O22；徒二 33）。因此，能力是透過聖靈從基督而來；無論何時何地，誰人傳授基督教道理，都應該特別重視這個真理。

　　過去三百多年來，福音派信徒一直仰賴神的應許，不斷向神支取能力來生活。我們應該為此感到高興，因為這種能力的賜予不單是聖經裏的一個重要主題，他還針對人類一個明顯而普遍的需要。凡肯誠實面對自己的人，都不時會因自己內心一份強烈的不足感而不知所措。所有基督徒都會一次又一次窘迫地呼喊：「主啊，幫助我，堅固我，扶持我，賜我能力，好讓我所言所行都能取悅你，令我剛強壯膽，有充足的力量面對種種壓力和要求。」

　　我們是被召去戰勝那惡者，他常以種種形態出現在我們心裏，或圍繞我們。我們需要知道在這一場爭戰裏，只有靠著聖靈的能力，才能獲取勝利；反之，若完全靠賴自己，最後只會發現自己的無能和經驗挫敗，引致痛苦。所以，福音信仰強調藉著聖靈而達致成聖是一件真實而又必需的事，這個教導永遠都切合時宜。

*** 基督徒的能力
　　十七世紀時期，清教徒首先強調聖靈如何在人的生命中彰顯能力；可是，到了十八世紀，這種教導竟變成了福音派信徒間爭辯的主題，當時衛斯理（ John Wesley）開始提出一種教義，說聖靈會把人的罪從人心靈中連根拔起。這就是衛斯理所指的「合乎聖經的聖潔」，他相信神興起循道主義（Methodism）去宣揚這個教導。非衛理公會信徒對這種教訓退避踟躕，覺得他很虛妄，而且不合乎聖經，所以他們不斷警告自己教會的會友要防備這種思想。然而到了十九世紀中葉，反對的鐘擺搖晃到了另一個極端；許多人感到（不論他們的想法是否正確）這股反完全主義的熱潮令基督徒完全遺忘了神有能力拯救人脫離罪，他能使人過一個平靜、得勝而公義的生活，他亦能夠使講員的資訊直透人心靈深處。忽然之間，人得勝的能力頓成為講章、書籍和非正式小組討論的話題（他們稱這些小組討論為「閒談聚會」），遍及大西洋兩岸。龐馬（Phoebe Palmer）、馬漢（Asa Mahan）、史密夫（ RobertPearsall Smith）、漢娜·韋杜（ Hannah Whitall Smith）、賀堅斯（ Evan Hopkins）、慕安德列（ Andrew Murray）。叨雷（R．A．Torrey）、特榮布林（ Charles G．Trumbull）。麥奇堅（ Robert C．McQuilkin）、梅亞（F．B．Meyer）、慕耳（H．C.G．Moule）等人所致力宣告的信徒得力「秘訣」（“secret”，這是他們採用的字眼），被高舉為新的啟示。事實上，宣告這些道理的前們也如此相信。一個嶄新的福音信仰運動已經展開了。

　　這個得力的「秘訣」，有時也稱為「高超生命」或「得勝生活」的秘訣，已經在英倫一年一度為期一周的凱錫克培靈會（Keswick Convention）中，全面制度化地推展了，一如爵士樂隊的主要節目安排一樣，一直以來這個培靈會的各個聚會都有固定編排，星期一的主題是罪惡，星期二的主題是那拯救我們脫離罪惡的基督，星期三是奉獻，星期四是在聖靈裏的生命，星期五是成聖者滿有能力的事奉（尤其是在宣教事工上）。及後，一份凱錫克期刊在一八七四年創刊，名為《基督徒得力之途》（The Christian Pathway of Power）。五年後，刊物名稱改為《信心的生命》（The Life of Faith)，但名稱的改換並不代表期刊的性質有任何更改，仍依據凱錫克培靈會的教導，以信心就是得力之途為主題。凱錫克塔靈會的影響是世界性的，「凱錫克信徒。勃興於全世界所有以英語為地方語言的角落。「凱錫克培靈會的教導已經被視為近期教會歷史中一股最有潛力的屬靈力量。」1「凱錫克型」的講員，專門在大會上宣講能力的資訊，他們已成為一群獨特的福音信仰牧者，與福音信仰學者、聖經教師和講論預言性主題的講員並駕齊驅。凱錫克資訊經過制度化，又獲得欣賞凱錫克精神（平穩、愉快、節制、吹毛求疵等特性都非常迎合中產階級人士的喜好）的人支持；所以，凱錫克培靈會中有關成聖和事奉能力的資訊自然縈繞人心。

　　這種講論能力的主題也不是近年唯一的發展。基督的能力不單能夠赦免我們的罪，而且藉著聖靈，可拯救我們脫離罪惡的奴役。有如第一世紀一樣，這個資訊已再次成為教會福音資訊的主要部分。對於城市化的西方人來說，他們面對的邪惡，是具破壞性的惡習；對於較落後的部落社群來說，他們面對的邪惡就是邪靈的勢力。至於較古老的福音資訊，由於他強調律法、罪惡、審判和基督代贖受死的榮耀，誠然可以補充今天福音資訊的缺欠。可是整體來說，古老的福音資訊很少論及能力；從這方面看來，他的確是有些遜色了。

　　既然神應允和賜予能力是千真萬確的事，那麼能力的主題如此受到重視，誠然是一件值得欣喜的事。事實上，強調能力的資訊不管透過什麼形式表達出來，今天已成為基督教福音信仰主流的標記，與世界性的靈恩運動並駕齊驅；這無疑是一個對未來充滿希望的徵兆。

*** 能力的限制
　　然而，在慶倖今天有許多關乎能力的講論之餘，我們也不無憂慮；因為經驗告訴我們，當我們思想聖靈時，若只集中注意能力這個主題，而沒有一個更具深度的觀點，沒有從另一個中心主題去看聖靈的職事，那麼，扭曲的觀念很快就悄悄潛入我們的思想裏。什麼是扭曲了的觀念呢？好，讓我拿以下的例子來開始吧！當一個人經常尋求力量去駕馭生活上的大小事情時，他會虔誠地專注自己心靈的起伏，因而產生一種自我中心和內向的心態，以致對社群的福利和社會的需要漠不關心。當人論及聖靈的工作時，往往傾向於以人為中心，就好像神的能力是一些隨時儲備妥當的東西，只要運用思想和意志——通常美其名為奉獻和信心——就可以開關「使用」（這是凱錫克培靈會的常用語）同時，這種態度形成一種觀念，認為只要我們肯釋放自己內在的能力，神的能力就會在我們心裏自動地運行，因此，我們可以隨時按著自己奉獻和信心的程度來調節這種能力。另一個隨之浮現的觀念，就是以為必須處於內在的被動狀態中，完全等候神的能力帶領我們（「放下自己，讓神工作」是流行得太響的口號）。同樣，在某些圈子的佈道工作裏，差不多形成了一種慣例，就是為心靈空虛的人提供一種「生活的力量」。表面上，就好像只要人肯委身基督，他立刻可以獲得發動和操縱能源的權利。

　　可是，這一切聽起來似乎較像瑜珈，甚於以聖經真理為基礎的基督教信仰。首先，這些觀念混淆了憑己意去擺佈神的能力（這是法術，西門的表現就是一個例子「徒八 18-24）和因著順服神的旨意而經歷神的能力（這是宗教，保羅的表現就是很好的例子「林後一二 9、10」）。再者，這些觀念是不切實際的。佈道家們的講章經常暗示一件事實，就是我們一旦成為基督徒，神在我們裏面的能力就可以立時除去我們性格上的任何弱點，令我們生活一帆風順；可是，這種說法是違背聖經，甚至是不誠實的。當然，神有時候可以施行奇跡，令悔改的人忽然改變過來，從這些或那些弱點中得釋放，即如其他時候，他亦會偶然施行神跡奇事一樣；然而，每個基督徒的生命都是一場持久戰，要不斷對抗來自世界、肉體和魔鬼的種種試誘和壓力；同時，那追求活像基督（即是智慧、忠心、愛心和公義的生活）的爭戰是嚴苛的，是永不停息的。在佈道中宣揚相反的現實，就無寧是一種騙取信心的技倆。同樣，凱錫克培靈會中的講論，經常鼓勵我們一時間對自己有過高及過低的期望——每時每刻完全脫離罪的纏累，是期望過高；另一方面，沒有動機去期望能夠逐步擺脫罪對我們心靈的轄制，就是期望過低。這是一種拙劣的神學，而且在心理和精神上都不符現實。我這些意見若早在一九五五年發表，一定會犯眾怒了，但在今天，我相信這些見解會較普遍受到接納。

　　討論下去，你就會漸漸明白我們真正的問題是需要對聖靈的教義有深刻而真確的洞見——這洞見的亮光能促使我們糾正對內在能力的謬說。不過，我打算暫且擱下這部分的論據，待我完成對聖靈問題的初步探討後才再談他。在目前的探討裏，我們只要記著一點，就是只談聖靈能力，根本不能針對問題的核心。

** 表現_屬靈恩賜的運用
　　其次，許多人認為聖靈的教義基本上與表現有關，意思是運用屬靈恩賜。對這些人來說，聖靈的職事似乎由始至終只是關乎如何運用恩賜——講道、教導、說預言、說方言、醫治等等。他們認為根據新約聖經的教導，恩賜（charismata）是神所賜予的某些能力，尤其是藉著言語、行為和態度，把關乎耶穌基督的真理傳遞開去，彼此激勵，互相服事。他們又認為「……聖靈顯在各人身上……」（林前一二 7），恩賜是藉著行以辨認的，基督徒所表現出來的行為，正顯明瞭神賜予他們什麼能力。因此，他們認為屬靈生命的實質在乎表現，同時假設人愈能表現恩賜，就表示他愈被聖靈充滿。

*** 總動員事奉
　　對於這種觀點——或更貼切地稱為心態，我首先要說明一點，就是他所強調的教本身同樣是絕對正確的；這次是強調恩賜的實在，以及運用恩賜的重要。曆世以來，教會以為事奉的恩賜只屬於一小部分基督徒專有（例如好的牧師和其他少數人），因此，他們並不十分注意恩賜這個題目。二十世紀以前，有關屬靈恩賜的全面研究，只有一本英文著作，由清教徒歐文（John Owen）於一六七九至一六八 O 年寫成。近期所強調屬靈恩賜的普遍性，以及神對教會總動員事奉的期望，其實早就應該提出，因為新約聖經對這兩方面的教導是相當清楚和明顯的。這裏引述一些主要經文。

　　「恩賜『charisznata』原有分別，聖靈卻是一位。職事『diakonia』也有分別，主卻是一位。功用『energemata』也有分別，神卻是一位，在眾人裏面運行一切的事。」（林前一二 4 一 6）「我們各人蒙恩，都是照基督所量給各人的恩賜……凡事長進，于元首基督；全身……照著各體的功用彼此相助，便叫身體漸漸增長，在愛中建立自己。」（弗四 7、15、16）「各人要照所得的恩賜彼此服事，作神百般恩賜的好管家。」（彼前四 10）「正如我們一個身子上有好些肢體，肢體也不都是一樣的用處。我們這許多人，在基督裏成為一身，互相聯絡作肢體，也是如此。按我們所得的恩賜，各有不同。……」（羅一二 4—6）並非只有聖品人員及有職分的才具有恩賜，所有基督徒 都具有恩賜，牧者必須認識這個事實，並運用自己的恩賜去裝備平信徒運用他們的恩賜。「他所賜的，有使徒，有先知，有傳福音的，有牧師和教師；為要成全聖徒，各盡其識，建立基督的身體」（弗四 11、12）。

　　英文聖經的敘定譯本（King James Version）掩蓋了保羅在此處的含義，把他翻譯為基督所賜的有使徒、先知、傳福音的、牧師和教師，「為了成全聖徒，為要各盡其職，為要建立基督的身體」（“for　the　perfecting　of　the　saints，for thework of ministry， for the edifying of the Body of Christ”［King James Version］）。乍看來，這三句平衡的句語好像都是聖品人員蒙召的職責。第六世紀的聖經版本遺漏了第七條誡命中的不字（出二○14），在歷史中流傳下來，被稱為邪惡的聖經版本；這裏英文聖經欽定譯本在「聖徒」（“saints”）之後加上了一個逗點，也同樣產生不良的效果。因為這個逗號將「職事」的範圍局限了，成為只有在位的領袖才可擔當，這不但隱藏了保羅的意思，簡直將保羅的意思顛倒過來，使本來是肢體各盡其職的成為教權主義（clericalism）。（這裏的「教權主義。是一種陰謀和專橫的結合，在其中，牧者宣稱所有屬靈職事都是他個人的責任，不是會眾的責任，而會眾亦同意這種想法。這個觀念在原則上很有問題，實踐起來更會導致聖靈的感動被銷滅。）

　　其實，自上個世紀中葉開始，普利茅斯弟兄會（ Plymouth Brethren）已宣告恩賜的普及性和肢體應各盡其職，但由於他們的宣告摻雜在一種反動性的爭論裏——當時的論，是針對一些在被指為背離真道的教會裏事奉、受薪並曾受訓練的聖品人員——，們的宣告沒有受到多大注意。可是，近年來普世教聯運動和靈恩運動都抓緊這方面的聖經真理，使之漸漸成為基督教的老生常談，因而產生了一些可喜的效果。其中一個效果，就是許多地區的教會紛紛願意在教會生活中實驗新的制度及新的禮儀形式，讓信徒有機會完全發揮他們的恩賜，令會眾整體受益；隨之興起的，是以一種認真的態度，去檢討傳統的崇拜程式和形式，以保障沒有任何恩賜受到窒礙，甚至銷滅聖靈的感動。這一切都是好現象。

*** 正確地看表現
　　很不幸，這可喜情況也有其負面：三大扭曲了的現象不時破壞我們認識聖靈的新取向。
　　第—，過分強調平信徒的職事，令一些平信徒低估和輕視牧師的特殊責任，忘記要尊重牧者的職分和領導。
　　第二，著重指出神慣於賜予聖徒一些與他們信主前的才能毫不相關的恩賜（這強調沒有錯，這的而且確是神的習慣）致使一些人受到蒙蔽，而看不見另一個事實，就是教會生活中最重要的恩賜（如講道、教導、領導、輔導、支持）通常是一些被聖化了的天然才能。
　　第三，有些人鼓勵基督徒在個人表現上有極度的自由，因此為了平衡這種極端，他們設立了各種極度專制的牧養監察形式，有時甚至比起中世紀教士運用權術控制基督徒良心的種種惡劣方式，有過之而無不及。

　　明顯地，上述發展都有毛病，但糾正這些毛病不等於要貶低他們背後的原則；這些毛病不過是一些不受歡迎的副產品。原則本身是正確的，若不能切實遵守這些原則，就不可能有高質素的教會生活。

　　話說回來，若我們單單專注恩賜的彰顯（例如以說方言為個人的五旬節經驗），以為這就是聖靈對個別信徒的主要職事，因而認為這就是我們應該集中關注的聖靈工作，那就大錯特錯了。只要讀讀哥林多前書，這個錯誤就顯而易見。哥林多教會的信徒因擁有知識而自高自大（八 1、2），他們為自己的恩賜自鳴得意，或者有些人會說，是雄心勃勃。他們藐視一些會友及外來講員，認為這些人的恩賜不及他們；每當他們在教會裏聚會，彼此之間就喜歡競爭和炫耀自己的恩賜。保羅為哥林多教會的信徒知識全備、滿有恩賜而感到十分高興（一 4—7）；但另一方面，保羅指出他們像嬰孩一樣不成熟，又屬乎肉體，行事為人自相矛盾，自招羞愧（三 l—4，五 1 一 13，六 1 一 8，—一 17  22）。他們重視恩賜和自由過於公義、愛心和事奉；保羅說這樣的價值觀是錯誤的。再沒有別的教會像哥林多教會一樣受到使徒這麼多的指責了。

　　哥林多信徒因著自己的知識和恩賜，以為自己是「屬靈的」（Pneumatikoi，一四37）；可是，保羅苦苦的向他們指出，真正屬靈的質素（假定聖靈已賜予我們悟性去瞭解福音，因為這是最基本的屬靈條件）是屬乎道德的。「豈不知你們的身子就是聖靈的殿嗎？這聖靈是從神而來，住在你們裏頭的；並且你們不是自己的人，因為你們是重價買來的。所以要在你們的身子上榮耀神。」（六 19、 20）那遠勝哥林多信徒一切最可誇表現的「更妙之道」，就是愛：「……恒久忍耐，又有恩慈……不嫉妒……不，不 張狂，不作害羞的事，不求自己的益處，不輕易發怒，不計算人的惡，不喜歡不義，只喜歡真理；凡事包容，凡事相信，凡事盼望，凡事忍耐。」（一三 4 一 7）保羅說，儘管你擁有世界上各樣最偉大的恩賜，然而沒有愛，你就算不得什麼（一三 1—3）——靈性上是死的。保羅懷疑哥林多教會的一些人事實上「算不得什麼」，因此，他寫信給他們說：「你們要醒悟為善，不要犯罪，因為有人不認識神。我說這話是要叫你們羞愧。」（一五 34；另參林後一三 5）

　　有一件事情是哥林多信徒需要瞭解的，也是今天我們一些信徒需要重新學習的，這就是清教徒歐文（ John Owen）所說的，有些人可以滿有恩賜卻完全沒有領受恩典，意思是一個人可以有很好的表現，使他人靈性得益，但他本人卻沒有因著真正認識神，經歷聖靈在他心內動工所帶來的內在更新。彰顯聖靈的恩賜表現，與聖靈所結的果子，即活像基督的品德（見加五 22、23）完全是兩回事；一個人可以在恩賜的表現上有驕人成績，卻欠缺像基督的美德。你可以有許多恩賜，但只有少許恩典；你甚至可以有真實的恩賜，但完全沒有真實的恩典；就如巴蘭、掃羅和猶大一樣。歐文寫道，這是由於：

　　屬靈恩賜只屬於頭腦上或理解上的，不管是普通恩賜或特殊恩賜，都不能在心靈裏占一席位。屬靈恩賜是頭腦上的，因為他們是觀念性和理論性，多於實際的。他們只是智慧而已。縱使有些恩賜，諸如行神跡和說方言，能夠在我們裏面找到住處，卻不過是一種特殊力量的「短暫運作」，曇花一現。神的亮光是所有其他恩賜的基礎，屬靈光照是恩賜的實質；所以使徒在希伯來書六章四節中表達出恩賜的次序［歐文將「來世權能」等同於屬靈恩賜」。意志、情感和良心都與這些恩賜無關，因此，這些恩賜無法改變心靈；固然，若憑著光照的功效，也許可以改革生命。雖然一般來說，神不會將恩賜賜予大奸大惡的罪犯，至於那些接受了恩賜的人，若果後來變得惡行昭彰，神多半不會繼續給他們賜下恩賜；然而，一些擁有恩賜的人可能生命從未真正更新，那就無法確保他們不會陷入嚴重的罪中。3

　　故此，沒有人可以用恩賜作為取悅神或得救的明證，屬靈恩賜並不等於這些。

　　在整本新約聖經裏，每逢提及神在人生命中的工作，著眼點往往是倫理道德，而不是靈恩方面的。那真正要緊的是活像基督（不是在恩賜上像基督，而是在愛心、謙卑、順服神的旨意、對別人的需要敏感等各方面像他）。這在保羅為信徒的禱告中表達得尤其清楚。他為哥羅西的信徒祈求，求神「照他榮耀的權能，［使信徒］得以在各樣的力上加力，好叫……。什麼？是透過豐盛有餘的恩賜，好叫他們在事奉上有輝煌的成就嗎？不是，而是好叫他們「凡事歡歡喜喜的忍耐寬容」（西一 11）。同時，他祈求腓立比信徒的愛心滿溢，「……在知識和各樣見識上，多而又多；使你們……。什麼？使你們在講道和爭辯中充滿說服力，或者有醫治的權柄，或者能說流利的方言嗎？不是，而是「作誠實無過的人，直到基督的日子；並靠著耶穌基督結滿了仁義的果子……」（腓 9—11；另參看弗三 14 一 19）。

　　以上這點不單切合那些終日埋首於發掘和使用屬靈恩賜的人，也適用於所有持以下態度的人：這些人也許受自己剛烈的性情所矇騙，總以他們參與基督教活動的多寡，以及推行活動的技巧和成敗來量度聖靈在他們身上的工作。

　　我的論點就是任何把屬靈恩賜（奔走和辦事的能力和意願）看為比屬靈果子（在個人生命中像基督的品格）更重要的心態，在屬靈上都是方向錯誤的，需要矯正。最佳的矯正良藥就是重新調校我們對聖靈工作的觀點，把基督徒的活動和表現看為服事神和榮耀神的途徑，並按這種價值去衡量他們，而不是憑我們的觀感，單單因為某些活動或表現充滿戲劇性、夠搶眼、足以吸引人、能讓人在教會中擔當重要職位，或者使我們對某人的期望提升，就看為寶貴。有關這方面的觀點，我將會在下文討論；目前，讓我們先弄清楚，強調恩賜和活動，跟強調經驗聖靈的能力一樣，都不能領我們進到聖靈真理的核心。讓我們繼續我們的檢討。

** 保守我們純潔

　　第三方面，有些人將聖靈的教義集中在「潔淨」（purifying）和「淨化」（purgation）之上，換句話說，就是神潔淨他的兒女，使他們脫離罪的污染和敗壞，幫助他們抵擋試探，行正義的事。對於這些人來說，聖靈在我們逐漸成聖的過程中，使我們趨向完全，幫助治死我們裏面的罪（羅八 14；另參看西三 5），並改變我們，叫我們「榮上加榮……」（林後三 18）。對他們來說，問題的核心並非經歷聖靈的能力，也在乎基督徒對外的表現，反而是我們內心的爭戰，在追求聖潔的過程中如何對抗罪惡，尋求聖靈的幫助，保守我們純潔，不受玷污。

　　這些人所強調的觀點，本身也是完全合乎聖經的。未曾重生的人，實際上如保羅所說，「……都在罪惡之下……」（羅三 9）；另一方面，罪仍然「住」在那些重生了的人裏面（羅七 20、23；另參看來一二 1；約壹一 8）。罪在本質上就是一種叛逆神的非理性能量——一種傲慢、任性的習慣，在道德及屬靈上形形色色的自我中心表現。無論罪以任何形式出現，都惹神憎厭（賽六一 8；耶四四 4；箴六 16 一 19），也使我們在神的眼裏成為不潔之民。所以，從聖經來看，罪不單需要被赦免，而且需要被潔淨。

　　同樣地，以賽亞盼望有一天「主以公義的靈和焚燒的靈，將錫安女子的汙穢洗去」（賽四 4；另參看要求人洗濯、自潔的經文：賽一 16；耶四 14）。以西結覆述神的話：「我必用清水灑在你們身上，你們就潔淨了。我要潔淨你們，使你們脫離一切的汙穢，棄掉一切的偶像。」（結三六 25）撒迦利亞預告：「那日，必給大衛家和耶路撒冷的居民，開一個泉源，洗除罪惡與汙穢。」（亞一三 1）瑪拉基發出警告說：神「如煉金之人的火，如漂布之人的鹺。他必坐下如煉淨銀子的，必潔淨利未人，熬煉他們像金銀一樣……」（瑪三 2、3；另參看賽一 25；亞一三 9）這些經文指出犯罪行為使我們在神面前成為汙穢；罪惡叫神討厭和反感，一如當我們發現本該是潔淨的地方變成汙穢時，我們自己也表示討厭和反感；但在神恩慈的聖潔裏，這一切都解決了，他不單赦免我們的罪，而且幫助我們不再犯罪。

　　在舊約聖經裏，所有潔淨的律例及潔淨的禮儀都指向這種神聖的潔淨工作。同樣，在新約聖經所有有關救贖的經文裏，都把救恩形容為被洗淨和被潔淨（約一三 10，一五3；徒二二 16；林前六 11；弗五 25—27；來九 13、14，一○22；約壹一 7—9），又指基督徒生命中最重要的事情，就是潔淨自己，除去一切使自己在神眼中看為汙穢的東西（林後七 1；弗五 3— 5；提後二 20—22；約壹三 3）。所以，基督徒的洗禮尤其反映些意義，洗禮事實上不折不扣地象徵了潔淨。

　　聖靈使基督徒醒覺到自己的罪汙，並為此感到羞慚，又激勵我們去「……潔淨自己除去身體、靈魂一切的汙穢，敬畏神，得以成聖。」（林後七 1）當我們突出聖靈這方面的工作時，正好顯明瞭聖經一個重點，而在我們這個頹廢的世代裏，一切道德標準不受重視，羞恥之心被視作等閒，這重點實在需要大大的強調。

　　同時，基督徒在現世對純潔生命的追求，意味著他們長遠下去一種自覺的矛盾和掙紮，並常會感到成績未達理想；這方面的著重也是相當正確的，「因為情欲和聖靈相爭，聖靈和情欲相爭，這兩個是彼此相敵，使你們不能作所願意作的。」（加五 17）

　　無論我們是否接受羅馬書七章十四至二十五節作為剖析基督徒經驗的一個橫切面，用以直接闡明上述要點（有些人贊成，有些人不贊成；我們稍後會再作討論），但毫無疑問，保羅在加拉太書正告訴我們基督徒生命裏的實際掙紮。他要我們知道，每個基督徒的生命裏，都存在著兩種敵對的欲望；這兩種力量在動機的層次上彼此為敵。有些欲望表現出人性墮落後一種悖逆神、自私自利的天性；有些欲望表現出由重生而來的超自然、榮耀神和愛神的動機。由於基督徒內心有這兩種敵對的催迫動力，當其中一股動力把他拉向前時，另一股動力便把他拉向後；因此，縱然他恒常的目標是完完全全地服事神，如一首聖詩所說，存著「忠誠專一的心」，他還是發覺他的心靈從未完全純潔無瑕，他所作的事，也並非絕對正確無誤。就這樣，他時時刻刻不能作他所願作的。他在生活中認識到他所作的一切其實可以並且應該做得更好：不單只在他被自己的驕傲、軟弱、愚昧出賣了時如此，他努力嘗試行善為義的時候也是如此。在每一次嘗試之後，在每一個行動之後，他往往看見他在動機上、在表現上，都有許多可以改善之處。他當其時感到已盡所能做到最好的事情，事後回顧都會發現並非做得最好。就這樣，他窮一生之力追求完美，卻又發現他所追求的永遠不能在他掌握之內。

　　當然，這不是說他永不會達到任何程度的義，保羅並非預料基督徒生命是經常完全失敗的，反而，他期望這是不斷的道德成長。「……當順著聖靈而行，就不放縱肉體的情欲了。」這是加拉太書五章十六節對信徒的直接要求，第十七節只不過是這要求的注腳而已。明顯地，保羅在這裏及其他經文教導有關基督徒品行時，他每每期望信徒努力向前，養成聖潔的習慣，積極操練自己，學像基督。

　　保羅說，基督徒既然從罪的奴役中釋放出來，他就可「按著心靈的新樣」（羅七6），實踐愛和公義；凡他現在能實踐的，他都必須去實踐，因為這聖潔的生活是神的旨意（加五 13、 14；羅六 17 至七 6；帖前四 1 一 8）。基督徒能夠且必須藉著聖靈治死他們的罪（羅八 13）；他也能夠且必須活在聖靈裏，走在屬神和善行的道路上（羅八 4；加五 16、25）。意思是說，一些他從前愛做的事，或一般未信主的人愛做的事，他如今放棄不作，而且，他開始選擇作另一些事情。現在，他要追隨自己心靈裏（即在他的意識裏）所感受到屬於聖靈的意願，而不陷溺在肉體的情欲中。基督徒生命必須是公義的生命，這正是他悔改和重生的自然流露，也是基本的要求。

　　談到保羅在第十七節所說的話，我只想發揮這唯一的重點：活在聖靈中的基督徒，會不斷發現他的生命尚未達致本來應有的美善；他經常要面對重重障礙和限制，以及自己扭曲的天性背道而馳的拉扯，他正在打一場前所未有的硬仗；同時，即使是他最好的行為，也不免犯上動機上的罪；他亦發現他每日的生活充滿汙點，他必須每時每刻仰賴神在基督裏的赦罪恩典，否則他就會在罪中失喪；同時，他也認識到自己心靈的軟弱和善變，需要經常求告聖靈賜給他力量，使他在這場內在的鬥爭中能堅持到底。「你確實不能實踐你心想望的那種聖潔生活。」對保羅來說，這句話明顯地道出了人追求聖潔的一些真相。誰可以說他是錯誤的呢？
　　
　　的確，自從革利免（Clement）和俄利根（Origen ）提出清除情欲、淨化靈魂的教導，早期教父記述他們如何頑抗醇酒美人、夜夜笙歌的幻想，以及奥古斯丁用自身的經歷去刻畫罪和恩典的本質以來，信徒不可避免地要與試探對抗的主題就成為基督教靈修教導中一個固定的著重累占。馬丁·路德和加爾文對這方面有很多闡釋，路德宗和加爾文派的信徒，尤其是加爾文派，都緊緊追隨他們的腳蹤。許多世紀以來，不少人曾一次又一次地對這個重點的真確性、現實性和健全性提出質疑與辯論，到如今，已經再沒有什麼見解能認真地挑戰上述重點了。藉著神的恩典，人的生命逐漸被洗滌和潔淨，因此，強調人生掙紮的真實性，是完全合乎聖經和十分恰當的。

*** 道德掙紮教義的陷阱
　　即使這樣，經驗告訴我們，當信徒以道德掙紮作為他們思想聖靈的重點時，常會被許多陷阱圍繞。他們會漸漸變成律法主義者，常常為自己和別人定下嚴格的規例，好讓自己對不相干的事情毫不染指，又給自己和別人強加一些呆板並約束性的行為模式，作為抵抗屬世潮流的堡壘，並且大大強調遵守這些人為禁忌的重要。他們的行事為人愈來愈像法利賽人，注重提防那能污染人的事情，以及毫不妥協地堅守原則，多於注重實踐基督的愛；他們變得小題大造，對於沒有真正構成威脅的事物，他們亦毫無理由地懼怕受到污染，又頑固地不肯安心；他們變得沒有喜樂，因為盤據他們腦海的，儘是這場屬靈戰爭如何冷酷無情的思想；他們變成病態的人，終日內省，陷溺於懊悔自己心靈的腐朽，久而久之，滋長出灰暗冷漠的人生觀；他們對於道德成長的可能性感到悲觀，不單看自己如此，看別人也是如此；他們對於脫離罪惡，不敢存什麼厚望，最大的希望只不過是不會比以前更糟。這種種態度可說是屬靈的神經衰弱症，他們歪曲、損害並削弱聖靈使人成聖的工作，因此實際上使聖靈在我們生命中的工作蒙上汙點。

　　我明白這些心態通常是累積了種種因素構成的，諸如天生的性情、早年的教育和訓練，以及因害羞或缺乏安全感而形成的吹毛求疵習慣、低下的自我形象，甚至或者真正的自我憎厭，都往往是一些成因；此外，一些內向的教會文化和社群，都可以導致上述的情況。只不過，現在我想指出的，就是對聖靈認識不足，也經常是一個原因。一如我們剛才討論到的其他兩類人一樣，這類人需要從另一個觀點認識聖靈，從上述我所描寫的那種灰暗、自我中心的屬靈狀況中擺脫出來。一會兒，我就會指出什麼是我所認為的正確觀點了。
　
