#+TITLE:書摘《活在聖靈中 Keep in Step with the Spirit》巴刻(J．I．Packer)著/霍玉蓮譯
#+AUTHOR:巴刻J．I．Packer著/霍玉蓮譯

* 目錄
 - [[#1_看清楚聖靈][1_看清楚聖靈]]
   - [[#蒙眼症][蒙眼症]]
   - [[#認識並經歷神][認識並經歷神]]
   - [[#聖靈的能力][聖靈的能力]]
     - [[#基督徒的能力][基督徒的能力]]
     - [[#能力的限制][能力的限制]]
   - [[#表現_屬靈恩賜的運用][表現_屬靈恩賜的運用]]
     - [[#總動員事奉][總動員事奉]]
     - [[#正確地看表現][正確地看表現]]

* 1 看清楚聖靈
** 認識並經歷神
　　耶穌在世上的時候，門徒追隨他，但他們對屬靈事物的理解常有錯漏，而且經常對耶穌有許多誤解；可是，耶穌能夠超越他們思想上的限制，感動他們、改變他們的生命，純粹是由於他們愛他、信靠他，希望從他身上學習，誠心願意追隨他們心中的亮光去服從他。因此，十二個門徒中有十一個「已經乾淨了」，並且得與其他人一起進入耶穌平安的恩典中，而那時他們尚未能掌握耶穌釘十架的贖罪意義。神首先賜下救恩的禮物，改變他們的生命，其後他們才明白這是什麼一回事。

　　神是滿有恩慈的，只要我們以真誠的態度，全心全意尋求他的臉，希望與他親近，即使我們對何謂屬靈生命沒有認識，或只有錯誤的觀念，他都可以使我們靈裏的生命進深。但並不是說神賜福於那些無知和錯謬的人，是由於他們的無知和錯謬；也不是說神不在意我們是否認識和掌握他所啟示的旨意；更不是說一個人只要對神有誠懇的心和真摯的情感，就不怕無知和錯謬會損害他靈命的健康。

　　無數罪人在他們對耶穌和聖靈尚未有正確的認識時，就已經真實地經歷耶穌基督的救恩和聖靈使生命更新的能力。儘管如此，我們若對聖靈有較清晰的觀念，就更能欣賞聖靈的工作，以及避免墮入一些錯謬的陷阱。

[[Keep_in_Step_With_the_Spirit__orig.org#認識並經歷神][本文]]

** 聖靈的能力
　　許多人認為聖靈的教義基本上與能力有關，意思是神賜予能力，讓你可以做你應該做卻感有心無力的事情。容忍那考驗你耐性的人、愛那不可愛的人、控制脾氣、在壓力中站立得穩、為基督勇敢發言、在遭逢患難中仍信靠神。聖靈賦予人能力達致上述的種種表現，無論在思想上、言語上、講章及禱告裏，這主題都為人所津津樂道。

　　能力（power）一詞是一個重要的新約辭彙，而基督藉聖靈賦予信徒能力，確是新約中重大的事實，是福音裏的榮耀，也是世界各地忠實追隨基督的人的標記。我們受教導知道靠著超自然的能力去過超自然的生活，是整個新約基督教信仰的核心，故此，那些自稱信奉基督教的人，若不曾經歷能力的澆灌，也表現不出他們擁有這種能力，那麼照新約聖經的標準看來，他們的信仰是值得懷疑的。

　　儘管人以基督為信徒得力的唯一源頭，能力的澆奠往往是聖靈的工作，而人只提基督，是因為基督賜下聖靈。因此，能力是透過聖靈從基督而來；無論何時何地，誰人傳授基督教道理，都應該特別重視這個真理。過去三百多年來，福音派信徒一直仰賴神的應許，不斷向神支取能力來生活。我們應該為此感到高興，因為這種能力的賜予不單是聖經裏的一個重要主題，他還針對人類一個明顯而普遍的需要。凡肯誠實面對自己的人，都不時會因自己內心一份強烈的不足感而不知所措。所有基督徒都會一次又一次窘迫地呼喊：「主啊，幫助我，堅固我，扶持我，賜我能力，好讓我所言所行都能取悅你，令我剛強壯膽，有充足的力量面對種種壓力和要求。」

　　我們是被召去戰勝那惡者，他常以種種形態出現在我們心裏，或圍繞我們。我們需要知道在這一場爭戰裏，只有靠著聖靈的能力，才能獲取勝利；反之，若完全靠賴自己，最後只會發現自己的無能和經驗挫敗，引致痛苦。所以，福音信仰強調藉著聖靈而達致成聖是一件真實而又必需的事，這個教導永遠都切合時宜。

[[Keep_in_Step_With_the_Spirit__orig.org#聖靈的能力][本文]]

** 基督徒的能力
　　十七世紀時期，清教徒首先強調聖靈如何在人的生命中彰顯能力；到了十八世紀，衛斯理（John Wesley）開始提出一種教義，說聖靈會把人的罪從人心靈中連根拔起。這就是衛斯理所指的「合乎聖經的聖潔」。非衛理公會信徒對這種教訓退避踟躕，覺得他很虛妄，而且不合乎聖經，所以他們不斷警告自己教會的會友要防備這種思想。然而到了十九世紀中葉；許多人感到這股反完全主義的熱潮令基督徒完全遺忘了神有能力拯救人脫離罪，他能使人過一個平靜、得勝而公義的生活，他亦能夠使講員的資訊直透人心靈深處。忽然之間，人得勝的能力頓成為講章、書籍和非正式小組討論的話題。一個嶄新的福音信仰運動已經展開了。

　　這個得力的「秘訣」，有時也稱為「高超生命」或「得勝生活」的秘訣，已經在英倫一年一度為期一周的凱錫克培靈會（Keswick Convention）中，全面制度化地推展了，星期一的主題是罪惡，星期二的主題是那拯救我們脫離罪惡的基督，星期三是奉獻，星期四是在聖靈裏的生命，星期五是成聖者滿有能力的事奉（尤其是在宣教事工上）。仍依據凱錫克培靈會的教導，以信心就是得力之途為主題。「凱錫克型」的講員，專門在大會上宣講能力的資訊，凱錫克培靈會中有關成聖和事奉能力的資訊自然縈繞人心。

　　這種講論能力的主題也不是近年唯一的發展。基督的能力不單能夠赦免我們的罪，而且藉著聖靈，可拯救我們脫離罪惡的奴役。有如第一世紀一樣，這個資訊已再次成為教會福音資訊的主要部分。較古老的福音資訊，由於他強調律法、罪惡、審判和基督代贖受死的榮耀，誠然可以補充今天福音資訊的缺欠。可是整體來說，古老的福音資訊很少論及能力；既然神應允和賜予能力是千真萬確的事，那麼能力的主題如此受到重視，誠然是一件值得欣喜的事。事實上，強調能力的資訊不管透過什麼形式表達出來，今天已成為基督教福音信仰主流的標記，與世界性的靈恩運動並駕齊驅；

[[Keep_in_Step_With_the_Spirit__orig.org#基督徒的能力][本文]]

** 能力的限制
　　經驗告訴我們，當我們思想聖靈時，若只集中注意能力這個主題，而沒有一個更具深度的觀點，沒有從另一個中心主題去看聖靈的職事，那麼，扭曲的觀念很快就悄悄潛入我們的思想裏。

　　當人論及聖靈的工作時，往往傾向於以人為中心，就好像神的能力是一些隨時儲備妥當的東西，只要運用思想和意志——通常美其名為奉獻和信心--就可以開關「使用」。同時，這種態度形成一種觀念，認為只要我們肯釋放自己內在的能力，神的能力就會在我們心裏自動地運行，因此，我們可以隨時按著自己奉獻和信心的程度來調節這種能力。另一個隨之浮現的觀念，就是以為必須處於內在的被動狀態中，完全等候神的能力帶領我們，就是為心靈空虛的人提供一種「生活的力量」。表面上，就好像只要人肯委身基督，他立刻可以獲得發動和操縱能源的權利。

　　這些觀念混淆了憑己意去擺佈神的能力和因著順服神的旨意而經歷神的能力。佈道家們的講章經常暗示一件事實，就是我們一旦成為基督徒，神在我們裏面的能力就可以立時除去我們性格上的任何弱點，令我們生活一帆風順；可是，這種說法是違背聖經，甚至是不誠實的。當然，神有時候可以施行奇跡，令悔改的人忽然改變過來，從這些或那些弱點中得釋放，即如其他時候，他亦會偶然施行神跡奇事一樣；然而，每個基督徒的生命都是一場持久戰，要不斷對抗來自世界、肉體和魔鬼的種種試誘和壓力；同時，那追求活像基督的爭戰是嚴苛的，是永不停息的。凱錫克培靈會中的講論，經常鼓勵我們一時間對自己有過高及過低的期望——每時每刻完全脫離罪的纏累，是期望過高；另一方面，沒有機去期望能夠逐步擺脫罪對我們心靈的轄制，就是期望過低。這是一種拙劣的神學，而且在心理和精神上都不符現實。

　　所以只談聖靈能力，根本不能針對問題的核心。

[[Keep_in_Step_With_the_Spirit__orig.org#能力的限制][本文]]

** 表現_屬靈恩賜的運用

[[Keep_in_Step_With_the_Spirit__orig.org#表現_屬靈恩賜的運用][本文]]

*** 總動員事奉
　　許多人認為聖靈的教義基本上與表現有關，意思是運用屬靈恩賜。對這些人來說，聖靈的職事似乎由始至終只是關乎如何運用恩賜——講道、教導、說預言、說方言、醫治等等。他們認為根據新約聖經的教導，恩賜（charismata）是神所賜予的某些能力，尤其是藉著言語、行為和態度，把關乎耶穌基督的真理傳遞開去，彼此激勵，互相服事。他們又認為恩賜是藉著行為以辨認的，基督徒所表現出來的行為，正顯明神賜予他們什麼能力。因此，他們認為屬靈生命的實質在乎表現，同時假設人愈能表現恩賜，就表示他愈被聖靈充滿。

　　對於這種觀點，我首先要說明一點，就是他所強調的教導本身同樣是絕對正確的；這次是強調恩賜的實在，以及運用恩賜的重要。強調屬靈恩賜的普遍性，以及神對教會總動員事奉的期望，新約聖經對這兩方面的教導是相當清楚和明顯的。並非只有聖品人員及有職分的才具有恩賜，所有基督徒都具有恩賜，牧者必須認識這個事實，並運用自己的恩賜去裝備平信徒運用他們的恩賜。

　　近年來普世教聯運動和靈恩運動都抓緊這方面的聖經真理，使之漸漸成為基督教的老生常談，因而產生了一些可喜的效果。讓信徒有機會完全發揮他們的恩賜，令會眾整體受益；隨之興起的，是以一種認真的態度，去檢討傳統的崇拜程式和形式，以保障沒有任何恩賜受到窒礙，甚至銷滅聖靈的感動。這一切都是好現象。

[[Keep_in_Step_With_the_Spirit__orig.org#總動員事奉][本文]]

*** 正確地看表現
　　很不幸，這可喜情況也有其負面。過分強調平信徒的職事，令一些平信徒忘記要尊重牧者的職分和領導。也看不見另一個事實，就是教會生活中最重要的恩賜（如講道、教導、領導、輔導、支持）通常是一些被聖化了的天然才能。這些毛病不過是一些不受歡迎的副產品。原則本身是正確的，若不能切實遵守這些原則，就不可能有高質素的教會生活。

　　若我們單單專注恩賜的彰顯，因而認為這就是我們應該集中關注的聖靈工作，那就大錯特錯了。哥林多教會的信徒因擁有知識而自高自大（八 1、2）；每當他們在教會裏聚會，彼此之間就喜歡競爭和炫耀自己的恩賜。他們重視恩賜和自由過於公義、愛心和事奉；保羅說這樣的價值觀是錯誤的。

　　哥林多信徒因著自己的知識和恩賜，以為自己是「屬靈的」；可是，真正屬靈的質素是屬乎道德的。那遠勝哥林多信徒一切最可誇表現的「更妙之道」，就是愛。一個人可以有很好的表現，使他人靈性得益，但他本人卻沒有因著真正認識神，經歷聖靈在他心內動工所帶來的內在更新。彰顯聖靈的恩賜表現，與聖靈所結的果子，完全是兩回事；屬靈恩賜只屬於頭腦上或理解上的，不管是普通恩賜或特殊恩賜，都不能在心靈裏占一席位。
意志、情感和良心都與這些恩賜無關，因此，這些恩賜無法改變心靈。

　　在整本新約聖經裏，每逢提及神在人生命中的工作，著眼點往往是倫理道德，而不是靈恩方面的。那真正要緊的是活像基督（不是在恩賜上像基督，而是在愛心、謙卑、順服神的旨意、對別人的需要敏感等各方面像他）。任何把屬靈恩賜（奔走和辦事的能力和意願）看為比屬靈果子（在個人生命中像基督的品格）更重要的心態，在屬靈上都是方向錯誤的，需要矯正。最佳的矯正良藥就是重新調校我們對聖靈工作的觀點。

[[Keep_in_Step_With_the_Spirit__orig.org#正確地看表現][本文]]
