#+TITLE:《活在聖靈中 Keep in Step with the Spirit》巴刻(J．I．Packer)著/霍玉蓮譯
#+AUTHOR:巴刻J．I．Packer著/霍玉蓮譯

* 目錄
 - [[#1_看清楚聖靈][1_看清楚聖靈]]
   - [[#蒙眼症][蒙眼症]]
   - [[#認識並經歷神][認識並經歷神]]
   - [[#聖靈的能力][聖靈的能力]]
     - [[#基督徒的能力][基督徒的能力]]
     - [[#能力的限制][能力的限制]]
   - [[#表現_屬靈恩賜的運用][表現_屬靈恩賜的運用]]
     - [[#總動員事奉][總動員事奉]]
     - [[#正確地看表現][正確地看表現]]
   - [[#保守我們純潔][保守我們純潔]]
     - [[#道德掙紮教義的陷阱][道德掙紮教義的陷阱]]
   - [[#叫我們醒覺][叫我們醒覺]]
     - [[#泰萊觀點的毛病][泰萊觀點的毛病]]
   - [[#追溯我們的思路][追溯我們的思路]]
   - [[#基督的臨在][基督的臨在]]
     - [[#對神的覺醒][對神的覺醒]]
   - [[#綱要][綱要]]
   - [[#注文][注文]]
 - [[#2_聖經裏的聖靈][2_聖經裏的聖靈]]
   - [[#屬靈恩賜][屬靈恩賜]]
     - [[#什麼是屬靈恩賜][什麼是屬靈恩賜]]
     - [[#屬靈恩賜的運用][屬靈恩賜的運用]]
     - [[#恩賜帶來的祝福][恩賜帶來的祝福]]
 - [[#6_聖靈的路徑_解釋聖靈生活][6_聖靈的路徑：解釋聖靈生活]]
   - [[#翻方言][翻方言]]
   - [[#醫治的恩賜][醫治的恩賜]]
   - [[#預言的恩賜][預言的恩賜]]
   - [[#對複還論神學思想的裁決][對複還論神學思想的裁決]]
   - [[#另一套神學理論][另一套神學理論]]
     - [[#說方言][說方言]]


* 1_看清楚聖靈
** 蒙眼症
　　市面上不是已經有許多關於聖靈的著作嗎？為什麼還要多添一本？這個問題問得正好，現在我要回答這個問題，就先從我的近視說起吧！

　　如果我除下眼鏡來看你，你在我眼中便蒙朧不清，我應該仍然知道你的存在，我大約仍可分辨你是男是女，我也許不至糊塗得把你撞個滿懷。但在我眼中，你的線條不是清晰可辨，你的容貌變得模糊不清（除了靠記憶外），我絕對無法清楚形容你。假使在我除下眼鏡時，一個陌生人走進我的房間，無疑我可以指出他來，但他的臉孔將會是模糊的一團，我無法知道他臉上的表情。我若不戴回眼鏡，你和他都會輪廓不明。

　　加爾文有一個很特別的比喻，他說像我這類眼濛濛的人，需要配戴眼鏡，去將物象對焦，同樣，我們所有人都需要聖經的裝備，幫助我們體會神的實在。雖然加爾文是一般性地運用這個比喻，但我相信在他腦海中，他必會想到以一些特殊真理作為鏡片，來獲致清晰的焦點。加爾文認為每個人都會對真實的神有概略的認識，但這些認識多半是含混模糊的。看清楚神是指對他的性格、他的主權、他的救贖、他的慈愛、他的兒子、他的聖靈和他的作為有正確的認識，亦即是對我們與他的關係有正確的瞭解——我們些受造物，究竟是活在罪中或恩典裏？在信、望、愛的生命中與他相交，或在枯竭、幽暗的心靈中與他隔絕？我們怎樣才能夠對這些事情有正確的認識呢？加爾文的答案是（我的也是一樣）：從聖經中學習。惟有從聖經中學習，我們才能夠清楚認識神，而他在我們腦海中的形象，也就不再模糊不清；我們可以聲稱他是三位一體的創造主，是聖父、聖子和聖靈。

　　好了，我現在要清楚指出我寫這些篇章的目的。正如我已經說過，今天聖靈大受注目，眾人所關注的，是他的身分，以及他在個人、教會及社群中做些什麼工作。團契、肢體生活。總動員事奉、聖靈的洗、恩賜、神的引導、預言、神跡，以及聖靈的啟示、更新和復興工作等題目，都常常掛在許多人的嘴邊，也在許多書本中討論過。這誠然是好的，我們應該為此感到快樂；反之，若然我們沒有討論這些題目，可能反映出我們在屬靈方面出了問題。然而正如近視漢看不清眼前的景物一樣，又好比任何人都會在一些事情上捉錯用神，對事物的真相只知其一，不知其二，因此，我們雖然經常頌揚聖靈的工作，但往往未能按聖經認識聖靈。對屬靈的事物，我們真個是濛濛眼，大受自己的偏見左右，以致我們沒法看得清楚。

[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 認識並經歷神
　　我們很容易作出如此的假定：既然我們認識聖靈在我們生命中的一些作為，我們就已經完全認識聖靈。很抱歉，結論並不是這樣。事實上，正如一個人的概念知識可以遠超過他的屬靈經驗，同樣，屬靈經驗也可以走在概念知識的前頭。相信聖經的人經常強調需要有正確的概念知識，以致他們忽略了上述的情形。但事實確是如此，耶穌門徒的經驗就是很好的例子。耶穌在世上的時候，門徒追隨他，但他們對屬靈事物的理解常有錯漏，而且經常對耶穌有許多誤解；可是，耶穌能夠超越他們思想上的限制，感動他們、改變他們的生命，純粹是由於他們愛他、信靠他，希望從他身上學習，誠心願意追隨他們心中的亮光去服從他。因此，十二個門徒中有十一個「已經乾淨了」（意思是他們的罪得赦免，心靈獲得更新「約一五 3」），並且得與其他人一起進入耶穌恕宥和平安的恩典中（參路五 20 一 24，七 47—50，一九 5 一 10），而那時他們尚未能掌握耶穌釘十架的贖罪意義。神首先賜下救恩的禮物，改變他們的生命，其後他們才明白這是什麼一回事。

　　同時，當這些人對神充滿信心，並願意敞開心靈去明自神的旨意時，他們便追求更完全活在聖靈裏的生命。（這是極其自然的！難道我們不曉得追求從聖靈而來的生命和追求從耶穌而來的生命，事實上是同一回事，只是名目不同而已？）我在這裏提出的，就是要著意尋求聖經教導我們去尋求的東西。既然神是言而有信的，我們便有把握期望我們所求的必然得著——我們更會發現臨到我們身上的美好恩賜，常是超過我們所想求的。主耶穌說：「你們祈求，就給你們；……你們……尚且知道拿好東西給兒女況天父，豈不更將聖靈給求他的人嗎？」（路—— 9、13）許多曾這樣祈求的人，都被神豐足的回應嚇了一跳。

　　神是滿有恩慈的，只要我們以真誠的態度，全心全意尋求他的臉，希望與他親近，即使我們對何謂屬靈生命沒有認識，或只有錯誤的觀念，他都可以使我們靈裏的生命進深。在這要應用得著的公式是耶利米書二十九章十三、十四節的應許：「你們尋求我，若專心尋求我，就必尋見。……。然後，我們的責任就是要透過聖經的亮光，瞭解主實際上為我們做了什麼，並且瞭解他在我們個人經歷中的特別工作如何與聖經所說他透過聖靈為屬他的人作事的宣稱相關。因著主的慈愛，他在我們經歷中的作為都是匠心獨運地符合各人性格和環境上的需要。在我看來，這項工作是許多神的子民的當前急務。

　　請勿誤會我！我並不是說神賜福於那些無知和錯謬的人，是由於他們的無知和錯謬；我也不是說神不在意我們是否認識和掌握他所啟示的旨意；更不是說一個人只要對神有誠懇的心和真摯的情感，就不怕無知和錯謬會損害他靈命的健康。我們可以肯定地說，神賜給信徒的福氣，是絕對而不變地按著他的真理賜下的；錯誤的信仰意味著屬靈的貧乏，對靈性更會造成嚴重損害。可是，任何接觸人心靈的人，總是一次又一次地因神奇妙的作為而大感驚訝，因為神豐豐富富地賜福給靈性貧乏的人，使這些有大堆錯謬思想，只認識一點點真理的人，大大改變過來。正如我曾經說過，無數罪人在他們對耶穌和聖靈尚未有正確的認識時，就已經真實地經歷耶穌基督的救恩和聖靈使生命更新的能力。（說句實話，若然神要等待我們有完全正確的屬靈觀念，才賜下福氣，那麼，我們現在真不知處於何等光景了！幾乎每個基督徒都曾經歷神豐厚的恩惠和幫助，而神的賜予，總遠遠超過他們的思想所配得的。）儘管如此，我們若對聖靈有較清晰的觀念，就更能欣賞聖靈的工作，以及避免墮入一些錯謬的陷阱。這正是本書嘗試提供的幫助。

　　我的思潮又回到二十年前一個潮濕的下午，那時我正趕著去一間渾名為「蚤子窩」的橫街電影院，以先睹為快的心情去觀看一出剛到埠的著名默片「大將軍」（“TheGeneral”）。這出電影於一九二七年攝製，今日的影評人盛讚他是基頓（BusterKeaton）的代表作。當時我剛剛發現這樣一個憂鬱、品格高尚、容易遇上不幸、優柔寡斷、足智多謀的諧角基頓，因此「大將軍」深深地吸引著我。該故事發生於美國內戰時期，於是我順理成章地猜想這出電影必然像基頓其他一些電影一樣，片名已說明他的角色了。我並不是戰爭片迷，記得在步向電影院途中，我還在揣測這出電影會如何吸引我。

　　沒錯，在「大將軍」一片中，基頓最後真正穿上了制服——準確一點說，是穿上陸軍中尉的制服——可是，若因此稱基頓為一位肩負領導責任的將軍，那真是極之誤導，而且有點不盡不實，因為基頓只是在最後的幾分鐘才得到他的制服，而在這片段之前的整整七十分鐘裏，展現眼前的不是模仿軍中生活的諷刺劇，而是一個古老蒸氣火車頭的故事。那是一部名貴、笨重、設有排障器的 4—4—0 型火車頭。故事安排火車頭被人取了，促使那不怕死活的司機驟然成為機智的英雄人物，展開一夫當關的神勇拯救行動，從而引發出不少瘋狂笑料。後來他拯救成功，所得的報酬就是獲得他渴慕已久的軍官身分；在此之前，他因為不能當上軍官，女朋友不願理睬他。原來「大將軍」就是那部火車頭的名稱。故事改編自一八六三年的大火車頭追逐事件，當時，真正的「大將軍」（火車頭）在喬治亞州瑪利安達被北方破壞者搶奪，在火車快要駛進北方疆域之際，剛好燃料用盡，終於成功地被追蹤奪回。對於我這個鬧劇迷兼火車在來說，當時是完完全全被迷住了。

　　我想指出的，就是今天很多人殷殷暢論聖靈的工作及活在聖靈中的真實經歷，但其中一些觀念比對於事實真相，就差不多像我對「大將軍」一名先入為主的臆測一樣。請跟我察看一些有關觀念，讓我表明我說的到底是什麼意思吧！

[[Keep_in_Step_With_the_Spirit__notes.org#認識並經歷神][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 聖靈的能力
　　首先，許多人認為聖靈的教義基本上與能力有關，意思是神賜予能力，讓你可以做你應該做卻感有心無力的事情，例如：拒絕物欲的追求（諸如美色、煙、酒、毒品、金錢、刺激、奢華的生活、晉升機會、權力、名望、諂媚奉承等等）。容忍那考驗你耐性的人、愛那不可愛的人、控制脾氣、在壓力中站立得穩、為基督勇敢發言、在遭逢患難中仍信靠神。聖靈賦予人能力達致上述的種種表現，無論在思想上、言語上、講章及禱告裏，這主題都為人所津津樂道。

　　然則我們對這些人所強調的有什麼異議嗎？他們的觀點是否錯誤？不是，絕對不是；情形剛好相反，這觀念本身是堂而皇之的正確。因為能力（power）一詞（通常相當於希臘文的 dunamis，由此引伸為英文的 dynamite，有時相當於 kratos 和 ischus）是一個重要的新約辭彙，而基督藉聖靈賦予信徒能力，確是新約中重大的事實，是福音裏的榮耀，也是世界各地忠實追隨基督的人的標記。如果你對我這番話產生疑問，你大可細讀以下
經文：

　　耶穌曾把大使命託付門徒，叫他們將福音傳遍天下，並對他們說：「你們要在城裏等候，直到你們領受從上頭來的能力。」「但聖靈降臨在你們身上，你們就必得著能力 ……」（路二四 49；徒一 8）在五旬節，聖靈被澆灌下來時，「使徒大有能力，見證耶穌復活……」（徒四 33）同時，「司提反滿得恩惠、能力，在民間行了大奇事和神跡。」（徒六 8；另參閱彼得形容耶穌的相類似經文：「神怎樣以聖靈和能力膏拿撒勒人耶穌……」「徒一○38」）路加在這些經文裏告訴我們，從起初，福音就是靠著聖靈的能力傳揚開去。

　　保羅為羅馬教會的人祈禱說：「……使你們藉著聖靈的能力，大有盼望。」（羅五 13）然後，他繼續談及基督透過他作的事情：「基督藉我作的那些事，……他藉語作為，用神跡奇事的能力，並聖靈的能力……」（羅一五 18、19）；他又提醒哥林教會的信徒，他傳講基督釘十字架，「……乃是用聖靈和大能的明證；叫你們的信……只在乎神的大能。」（林前二 4、5；另參閱林後六 6—10，一○4— 6；帖前一 5，13）當保羅感到有一根剌加在他肉體上時，他寫道：基督「對我說：『我的恩典夠你用的，因為我的能力是在人的軟弱上顯得完全。』所以，我更喜歡誇自己的軟弱，好叫基督的能力覆庇我。」（林後一二 9，另參閱四 7）他又對提摩太說，神賜給基督徒的「是剛強（power）、仁愛、謹守的心」，並指責那些「愛宴樂，不愛神，有敬虔的外貌，卻背了敬虔的實意（ power）」的人（提後一 7，三 4、5）。他說基督給予信徒能力（endunamoo，dunamoo，krataioo），使信徒能達成本來單憑己力是永遠無法辦到的事情（弗三 16，六 10，另參一 19 一 23；西一 11；提前一 12；提後四 17；另參林後一二10；彼前五 10）。並且，當他處身獄中，性命危在旦夕之時，卻發出勝利的呼喊：「我靠著那加給我力量的，凡事（意指神呼召他去做的一切事）都能作。」（腓四 13）無庸置疑，這一切都說明瞭聖靈是帶來能力的。我們受教導知道靠著超自然的能力去過超自然的生活，是整個新約基督教信仰的核心，故此，那些自稱信奉基督教的人，若不曾經歷能力的澆灌，也表現不出他們擁有這種能力，那麼照新約聖經的標準看來，他們的信仰是值得懷疑的。儘管人以基督為信徒得力的唯一源頭，能力的澆奠往往是聖靈的工作，而人只提基督，是因為基督賜下聖靈（約一 33，二 O22；徒二 33）。因此，能力是透過聖靈從基督而來；無論何時何地，誰人傳授基督教道理，都應該特別重視這個真理。

　　過去三百多年來，福音派信徒一直仰賴神的應許，不斷向神支取能力來生活。我們應該為此感到高興，因為這種能力的賜予不單是聖經裏的一個重要主題，他還針對人類一個明顯而普遍的需要。凡肯誠實面對自己的人，都不時會因自己內心一份強烈的不足感而不知所措。所有基督徒都會一次又一次窘迫地呼喊：「主啊，幫助我，堅固我，扶持我，賜我能力，好讓我所言所行都能取悅你，令我剛強壯膽，有充足的力量面對種種壓力和要求。」

　　我們是被召去戰勝那惡者，他常以種種形態出現在我們心裏，或圍繞我們。我們需要知道在這一場爭戰裏，只有靠著聖靈的能力，才能獲取勝利；反之，若完全靠賴自己，最後只會發現自己的無能和經驗挫敗，引致痛苦。所以，福音信仰強調藉著聖靈而達致成聖是一件真實而又必需的事，這個教導永遠都切合時宜。

[[Keep_in_Step_With_the_Spirit__notes.org#聖靈的能力][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

*** 基督徒的能力
　　十七世紀時期，清教徒首先強調聖靈如何在人的生命中彰顯能力；可是，到了十八世紀，這種教導竟變成了福音派信徒間爭辯的主題，當時衛斯理（ John Wesley）開始提出一種教義，說聖靈會把人的罪從人心靈中連根拔起。這就是衛斯理所指的「合乎聖經的聖潔」，他相信神興起循道主義（Methodism）去宣揚這個教導。非衛理公會信徒對這種教訓退避踟躕，覺得他很虛妄，而且不合乎聖經，所以他們不斷警告自己教會的會友要防備這種思想。然而到了十九世紀中葉，反對的鐘擺搖晃到了另一個極端；許多人感到（不論他們的想法是否正確）這股反完全主義的熱潮令基督徒完全遺忘了神有能力拯救人脫離罪，他能使人過一個平靜、得勝而公義的生活，他亦能夠使講員的資訊直透人心靈深處。忽然之間，人得勝的能力頓成為講章、書籍和非正式小組討論的話題（他們稱這些小組討論為「閒談聚會」），遍及大西洋兩岸。龐馬（Phoebe Palmer）、馬漢（Asa Mahan）、史密夫（ RobertPearsall Smith）、漢娜·韋杜（ Hannah Whitall Smith）、賀堅斯（ Evan Hopkins）、慕安德列（ Andrew Murray）。叨雷（R．A．Torrey）、特榮布林（ Charles G．Trumbull）。麥奇堅（ Robert C．McQuilkin）、梅亞（F．B．Meyer）、慕耳（H．C.G．Moule）等人所致力宣告的信徒得力「秘訣」（“secret”，這是他們採用的字眼），被高舉為新的啟示。事實上，宣告這些道理的前們也如此相信。一個嶄新的福音信仰運動已經展開了。

　　這個得力的「秘訣」，有時也稱為「高超生命」或「得勝生活」的秘訣，已經在英倫一年一度為期一周的凱錫克培靈會（Keswick Convention）中，全面制度化地推展了，一如爵士樂隊的主要節目安排一樣，一直以來這個培靈會的各個聚會都有固定編排，星期一的主題是罪惡，星期二的主題是那拯救我們脫離罪惡的基督，星期三是奉獻，星期四是在聖靈裏的生命，星期五是成聖者滿有能力的事奉（尤其是在宣教事工上）。及後，一份凱錫克期刊在一八七四年創刊，名為《基督徒得力之途》（The Christian Pathway of Power）。五年後，刊物名稱改為《信心的生命》（The Life of Faith)，但名稱的改換並不代表期刊的性質有任何更改，仍依據凱錫克培靈會的教導，以信心就是得力之途為主題。凱錫克塔靈會的影響是世界性的，「凱錫克信徒。勃興於全世界所有以英語為地方語言的角落。「凱錫克培靈會的教導已經被視為近期教會歷史中一股最有潛力的屬靈力量。」1「凱錫克型」的講員，專門在大會上宣講能力的資訊，他們已成為一群獨特的福音信仰牧者，與福音信仰學者、聖經教師和講論預言性主題的講員並駕齊驅。凱錫克資訊經過制度化，又獲得欣賞凱錫克精神（平穩、愉快、節制、吹毛求疵等特性都非常迎合中產階級人士的喜好）的人支持；所以，凱錫克培靈會中有關成聖和事奉能力的資訊自然縈繞人心。

　　這種講論能力的主題也不是近年唯一的發展。基督的能力不單能夠赦免我們的罪，而且藉著聖靈，可拯救我們脫離罪惡的奴役。有如第一世紀一樣，這個資訊已再次成為教會福音資訊的主要部分。對於城市化的西方人來說，他們面對的邪惡，是具破壞性的惡習；對於較落後的部落社群來說，他們面對的邪惡就是邪靈的勢力。至於較古老的福音資訊，由於他強調律法、罪惡、審判和基督代贖受死的榮耀，誠然可以補充今天福音資訊的缺欠。可是整體來說，古老的福音資訊很少論及能力；從這方面看來，他的確是有些遜色了。

　　既然神應允和賜予能力是千真萬確的事，那麼能力的主題如此受到重視，誠然是一件值得欣喜的事。事實上，強調能力的資訊不管透過什麼形式表達出來，今天已成為基督教福音信仰主流的標記，與世界性的靈恩運動並駕齊驅；這無疑是一個對未來充滿希望的徵兆。

[[Keep_in_Step_With_the_Spirit__notes.org#基督徒的能力][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

*** 能力的限制
　　然而，在慶倖今天有許多關乎能力的講論之餘，我們也不無憂慮；因為經驗告訴我們，當我們思想聖靈時，若只集中注意能力這個主題，而沒有一個更具深度的觀點，沒有從另一個中心主題去看聖靈的職事，那麼，扭曲的觀念很快就悄悄潛入我們的思想裏。什麼是扭曲了的觀念呢？好，讓我拿以下的例子來開始吧！當一個人經常尋求力量去駕馭生活上的大小事情時，他會虔誠地專注自己心靈的起伏，因而產生一種自我中心和內向的心態，以致對社群的福利和社會的需要漠不關心。當人論及聖靈的工作時，往往傾向於以人為中心，就好像神的能力是一些隨時儲備妥當的東西，只要運用思想和意志——通常美其名為奉獻和信心——就可以開關「使用」（這是凱錫克培靈會的常用語）同時，這種態度形成一種觀念，認為只要我們肯釋放自己內在的能力，神的能力就會在我們心裏自動地運行，因此，我們可以隨時按著自己奉獻和信心的程度來調節這種能力。另一個隨之浮現的觀念，就是以為必須處於內在的被動狀態中，完全等候神的能力帶領我們（「放下自己，讓神工作」是流行得太響的口號）。同樣，在某些圈子的佈道工作裏，差不多形成了一種慣例，就是為心靈空虛的人提供一種「生活的力量」。表面上，就好像只要人肯委身基督，他立刻可以獲得發動和操縱能源的權利。

　　可是，這一切聽起來似乎較像瑜珈，甚於以聖經真理為基礎的基督教信仰。首先，這些觀念混淆了憑己意去擺佈神的能力（這是法術，西門的表現就是一個例子「徒八 18-24）和因著順服神的旨意而經歷神的能力（這是宗教，保羅的表現就是很好的例子「林後一二 9、10」）。再者，這些觀念是不切實際的。佈道家們的講章經常暗示一件事實，就是我們一旦成為基督徒，神在我們裏面的能力就可以立時除去我們性格上的任何弱點，令我們生活一帆風順；可是，這種說法是違背聖經，甚至是不誠實的。當然，神有時候可以施行奇跡，令悔改的人忽然改變過來，從這些或那些弱點中得釋放，即如其他時候，他亦會偶然施行神跡奇事一樣；然而，每個基督徒的生命都是一場持久戰，要不斷對抗來自世界、肉體和魔鬼的種種試誘和壓力；同時，那追求活像基督（即是智慧、忠心、愛心和公義的生活）的爭戰是嚴苛的，是永不停息的。在佈道中宣揚相反的現實，就無寧是一種騙取信心的技倆。同樣，凱錫克培靈會中的講論，經常鼓勵我們一時間對自己有過高及過低的期望——每時每刻完全脫離罪的纏累，是期望過高；另一方面，沒有動機去期望能夠逐步擺脫罪對我們心靈的轄制，就是期望過低。這是一種拙劣的神學，而且在心理和精神上都不符現實。我這些意見若早在一九五五年發表，一定會犯眾怒了，但在今天，我相信這些見解會較普遍受到接納。

　　討論下去，你就會漸漸明白我們真正的問題是需要對聖靈的教義有深刻而真確的洞見——這洞見的亮光能促使我們糾正對內在能力的謬說。不過，我打算暫且擱下這部分的論據，待我完成對聖靈問題的初步探討後才再談他。在目前的探討裏，我們只要記著一點，就是只談聖靈能力，根本不能針對問題的核心。

[[Keep_in_Step_With_the_Spirit__notes.org#能力的限制][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 表現_屬靈恩賜的運用
　　其次，許多人認為聖靈的教義基本上與表現有關，意思是運用屬靈恩賜。對這些人來說，聖靈的職事似乎由始至終只是關乎如何運用恩賜——講道、教導、說預言、說方言、醫治等等。他們認為根據新約聖經的教導，恩賜（charismata）是神所賜予的某些能力，尤其是藉著言語、行為和態度，把關乎耶穌基督的真理傳遞開去，彼此激勵，互相服事。他們又認為「……聖靈顯在各人身上……」（林前一二 7），恩賜是藉著行以辨認的，基督徒所表現出來的行為，正顯明瞭神賜予他們什麼能力。因此，他們認為屬靈生命的實質在乎表現，同時假設人愈能表現恩賜，就表示他愈被聖靈充滿。

[[Keep_in_Step_With_the_Spirit__notes.org#表現_屬靈恩賜的運用][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

*** 總動員事奉
　　對於這種觀點——或更貼切地稱為心態，我首先要說明一點，就是他所強調的教本身同樣是絕對正確的；這次是強調恩賜的實在，以及運用恩賜的重要。曆世以來，教會以為事奉的恩賜只屬於一小部分基督徒專有（例如好的牧師和其他少數人），因此，他們並不十分注意恩賜這個題目。二十世紀以前，有關屬靈恩賜的全面研究，只有一本英文著作，由清教徒歐文（John Owen）於一六七九至一六八 O 年寫成。近期所強調屬靈恩賜的普遍性，以及神對教會總動員事奉的期望，其實早就應該提出，因為新約聖經對這兩方面的教導是相當清楚和明顯的。這裏引述一些主要經文。

　　「恩賜『charisznata』原有分別，聖靈卻是一位。職事『diakonia』也有分別，主卻是一位。功用『energemata』也有分別，神卻是一位，在眾人裏面運行一切的事。」（林前一二 4 一 6）「我們各人蒙恩，都是照基督所量給各人的恩賜……凡事長進，于元首基督；全身……照著各體的功用彼此相助，便叫身體漸漸增長，在愛中建立自己。」（弗四 7、15、16）「各人要照所得的恩賜彼此服事，作神百般恩賜的好管家。」（彼前四 10）「正如我們一個身子上有好些肢體，肢體也不都是一樣的用處。我們這許多人，在基督裏成為一身，互相聯絡作肢體，也是如此。按我們所得的恩賜，各有不同。……」（羅一二 4—6）並非只有聖品人員及有職分的才具有恩賜，所有基督徒 都具有恩賜，牧者必須認識這個事實，並運用自己的恩賜去裝備平信徒運用他們的恩賜。「他所賜的，有使徒，有先知，有傳福音的，有牧師和教師；為要成全聖徒，各盡其識，建立基督的身體」（弗四 11、12）。

　　英文聖經的敘定譯本（King James Version）掩蓋了保羅在此處的含義，把他翻譯為基督所賜的有使徒、先知、傳福音的、牧師和教師，「為了成全聖徒，為要各盡其職，為要建立基督的身體」（“for　the　perfecting　of　the　saints，for thework of ministry， for the edifying of the Body of Christ”［King James Version］）。乍看來，這三句平衡的句語好像都是聖品人員蒙召的職責。第六世紀的聖經版本遺漏了第七條誡命中的不字（出二○14），在歷史中流傳下來，被稱為邪惡的聖經版本；這裏英文聖經欽定譯本在「聖徒」（“saints”）之後加上了一個逗點，也同樣產生不良的效果。因為這個逗號將「職事」的範圍局限了，成為只有在位的領袖才可擔當，這不但隱藏了保羅的意思，簡直將保羅的意思顛倒過來，使本來是肢體各盡其職的成為教權主義（clericalism）。（這裏的「教權主義。是一種陰謀和專橫的結合，在其中，牧者宣稱所有屬靈職事都是他個人的責任，不是會眾的責任，而會眾亦同意這種想法。這個觀念在原則上很有問題，實踐起來更會導致聖靈的感動被銷滅。）

　　其實，自上個世紀中葉開始，普利茅斯弟兄會（ Plymouth Brethren）已宣告恩賜的普及性和肢體應各盡其職，但由於他們的宣告摻雜在一種反動性的爭論裏——當時的論，是針對一些在被指為背離真道的教會裏事奉、受薪並曾受訓練的聖品人員——，們的宣告沒有受到多大注意。可是，近年來普世教聯運動和靈恩運動都抓緊這方面的聖經真理，使之漸漸成為基督教的老生常談，因而產生了一些可喜的效果。其中一個效果，就是許多地區的教會紛紛願意在教會生活中實驗新的制度及新的禮儀形式，讓信徒有機會完全發揮他們的恩賜，令會眾整體受益；隨之興起的，是以一種認真的態度，去檢討傳統的崇拜程式和形式，以保障沒有任何恩賜受到窒礙，甚至銷滅聖靈的感動。這一切都是好現象。

[[Keep_in_Step_With_the_Spirit__notes.org#總動員事奉][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

*** 正確地看表現
　　很不幸，這可喜情況也有其負面：三大扭曲了的現象不時破壞我們認識聖靈的新取向。
　　第—，過分強調平信徒的職事，令一些平信徒低估和輕視牧師的特殊責任，忘記要尊重牧者的職分和領導。
　　第二，著重指出神慣於賜予聖徒一些與他們信主前的才能毫不相關的恩賜（這強調沒有錯，這的而且確是神的習慣）致使一些人受到蒙蔽，而看不見另一個事實，就是教會生活中最重要的恩賜（如講道、教導、領導、輔導、支持）通常是一些被聖化了的天然才能。
　　第三，有些人鼓勵基督徒在個人表現上有極度的自由，因此為了平衡這種極端，他們設立了各種極度專制的牧養監察形式，有時甚至比起中世紀教士運用權術控制基督徒良心的種種惡劣方式，有過之而無不及。

　　明顯地，上述發展都有毛病，但糾正這些毛病不等於要貶低他們背後的原則；這些毛病不過是一些不受歡迎的副產品。原則本身是正確的，若不能切實遵守這些原則，就不可能有高質素的教會生活。

　　話說回來，若我們單單專注恩賜的彰顯（例如以說方言為個人的五旬節經驗），以為這就是聖靈對個別信徒的主要職事，因而認為這就是我們應該集中關注的聖靈工作，那就大錯特錯了。只要讀讀哥林多前書，這個錯誤就顯而易見。哥林多教會的信徒因擁有知識而自高自大（八 1、2），他們為自己的恩賜自鳴得意，或者有些人會說，是雄心勃勃。他們藐視一些會友及外來講員，認為這些人的恩賜不及他們；每當他們在教會裏聚會，彼此之間就喜歡競爭和炫耀自己的恩賜。保羅為哥林多教會的信徒知識全備、滿有恩賜而感到十分高興（一 4—7）；但另一方面，保羅指出他們像嬰孩一樣不成熟，又屬乎肉體，行事為人自相矛盾，自招羞愧（三 l—4，五 1 一 13，六 1 一 8，—一 17  22）。他們重視恩賜和自由過於公義、愛心和事奉；保羅說這樣的價值觀是錯誤的。再沒有別的教會像哥林多教會一樣受到使徒這麼多的指責了。

　　哥林多信徒因著自己的知識和恩賜，以為自己是「屬靈的」（Pneumatikoi，一四37）；可是，保羅苦苦的向他們指出，真正屬靈的質素（假定聖靈已賜予我們悟性去瞭解福音，因為這是最基本的屬靈條件）是屬乎道德的。「豈不知你們的身子就是聖靈的殿嗎？這聖靈是從神而來，住在你們裏頭的；並且你們不是自己的人，因為你們是重價買來的。所以要在你們的身子上榮耀神。」（六 19、 20）那遠勝哥林多信徒一切最可誇表現的「更妙之道」，就是愛：「……恒久忍耐，又有恩慈……不嫉妒……不，不 張狂，不作害羞的事，不求自己的益處，不輕易發怒，不計算人的惡，不喜歡不義，只喜歡真理；凡事包容，凡事相信，凡事盼望，凡事忍耐。」（一三 4 一 7）保羅說，儘管你擁有世界上各樣最偉大的恩賜，然而沒有愛，你就算不得什麼（一三 1—3）——靈性上是死的。保羅懷疑哥林多教會的一些人事實上「算不得什麼」，因此，他寫信給他們說：「你們要醒悟為善，不要犯罪，因為有人不認識神。我說這話是要叫你們羞愧。」（一五 34；另參林後一三 5）

　　有一件事情是哥林多信徒需要瞭解的，也是今天我們一些信徒需要重新學習的，這就是清教徒歐文（ John Owen）所說的，有些人可以滿有恩賜卻完全沒有領受恩典，意思是一個人可以有很好的表現，使他人靈性得益，但他本人卻沒有因著真正認識神，經歷聖靈在他心內動工所帶來的內在更新。彰顯聖靈的恩賜表現，與聖靈所結的果子，即活像基督的品德（見加五 22、23）完全是兩回事；一個人可以在恩賜的表現上有驕人成績，卻欠缺像基督的美德。你可以有許多恩賜，但只有少許恩典；你甚至可以有真實的恩賜，但完全沒有真實的恩典；就如巴蘭、掃羅和猶大一樣。歐文寫道，這是由於：

　　屬靈恩賜只屬於頭腦上或理解上的，不管是普通恩賜或特殊恩賜，都不能在心靈裏占一席位。屬靈恩賜是頭腦上的，因為他們是觀念性和理論性，多於實際的。他們只是智慧而已。縱使有些恩賜，諸如行神跡和說方言，能夠在我們裏面找到住處，卻不過是一種特殊力量的「短暫運作」，曇花一現。神的亮光是所有其他恩賜的基礎，屬靈光照是恩賜的實質；所以使徒在希伯來書六章四節中表達出恩賜的次序［歐文將「來世權能」等同於屬靈恩賜」。意志、情感和良心都與這些恩賜無關，因此，這些恩賜無法改變心靈；固然，若憑著光照的功效，也許可以改革生命。雖然一般來說，神不會將恩賜賜予大奸大惡的罪犯，至於那些接受了恩賜的人，若果後來變得惡行昭彰，神多半不會繼續給他們賜下恩賜；然而，一些擁有恩賜的人可能生命從未真正更新，那就無法確保他們不會陷入嚴重的罪中。3

　　故此，沒有人可以用恩賜作為取悅神或得救的明證，屬靈恩賜並不等於這些。

　　在整本新約聖經裏，每逢提及神在人生命中的工作，著眼點往往是倫理道德，而不是靈恩方面的。那真正要緊的是活像基督（不是在恩賜上像基督，而是在愛心、謙卑、順服神的旨意、對別人的需要敏感等各方面像他）。這在保羅為信徒的禱告中表達得尤其清楚。他為哥羅西的信徒祈求，求神「照他榮耀的權能，［使信徒］得以在各樣的力上加力，好叫……。什麼？是透過豐盛有餘的恩賜，好叫他們在事奉上有輝煌的成就嗎？不是，而是好叫他們「凡事歡歡喜喜的忍耐寬容」（西一 11）。同時，他祈求腓立比信徒的愛心滿溢，「……在知識和各樣見識上，多而又多；使你們……。什麼？使你們在講道和爭辯中充滿說服力，或者有醫治的權柄，或者能說流利的方言嗎？不是，而是「作誠實無過的人，直到基督的日子；並靠著耶穌基督結滿了仁義的果子……」（腓 9—11；另參看弗三 14 一 19）。

　　以上這點不單切合那些終日埋首於發掘和使用屬靈恩賜的人，也適用於所有持以下態度的人：這些人也許受自己剛烈的性情所矇騙，總以他們參與基督教活動的多寡，以及推行活動的技巧和成敗來量度聖靈在他們身上的工作。

　　我的論點就是任何把屬靈恩賜（奔走和辦事的能力和意願）看為比屬靈果子（在個人生命中像基督的品格）更重要的心態，在屬靈上都是方向錯誤的，需要矯正。最佳的矯正良藥就是重新調校我們對聖靈工作的觀點，把基督徒的活動和表現看為服事神和榮耀神的途徑，並按這種價值去衡量他們，而不是憑我們的觀感，單單因為某些活動或表現充滿戲劇性、夠搶眼、足以吸引人、能讓人在教會中擔當重要職位，或者使我們對某人的期望提升，就看為寶貴。有關這方面的觀點，我將會在下文討論；目前，讓我們先弄清楚，強調恩賜和活動，跟強調經驗聖靈的能力一樣，都不能領我們進到聖靈真理的核心。讓我們繼續我們的檢討。

[[Keep_in_Step_With_the_Spirit__notes.org#正確地看表現][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 保守我們純潔

　　第三方面，有些人將聖靈的教義集中在「潔淨」（purifying）和「淨化」（purgation）之上，換句話說，就是神潔淨他的兒女，使他們脫離罪的污染和敗壞，幫助他們抵擋試探，行正義的事。對於這些人來說，聖靈在我們逐漸成聖的過程中，使我們趨向完全，幫助治死我們裏面的罪（羅八 14；另參看西三 5），並改變我們，叫我們「榮上加榮……」（林後三 18）。對他們來說，問題的核心並非經歷聖靈的能力，也在乎基督徒對外的表現，反而是我們內心的爭戰，在追求聖潔的過程中如何對抗罪惡，尋求聖靈的幫助，保守我們純潔，不受玷污。

　　這些人所強調的觀點，本身也是完全合乎聖經的。未曾重生的人，實際上如保羅所說，「……都在罪惡之下……」（羅三 9）；另一方面，罪仍然「住」在那些重生了的人裏面（羅七 20、23；另參看來一二 1；約壹一 8）。罪在本質上就是一種叛逆神的非理性能量——一種傲慢、任性的習慣，在道德及屬靈上形形色色的自我中心表現。無論罪以任何形式出現，都惹神憎厭（賽六一 8；耶四四 4；箴六 16 一 19），也使我們在神的眼裏成為不潔之民。所以，從聖經來看，罪不單需要被赦免，而且需要被潔淨。

　　同樣地，以賽亞盼望有一天「主以公義的靈和焚燒的靈，將錫安女子的汙穢洗去」（賽四 4；另參看要求人洗濯、自潔的經文：賽一 16；耶四 14）。以西結覆述神的話：「我必用清水灑在你們身上，你們就潔淨了。我要潔淨你們，使你們脫離一切的汙穢，棄掉一切的偶像。」（結三六 25）撒迦利亞預告：「那日，必給大衛家和耶路撒冷的居民，開一個泉源，洗除罪惡與汙穢。」（亞一三 1）瑪拉基發出警告說：神「如煉金之人的火，如漂布之人的鹺。他必坐下如煉淨銀子的，必潔淨利未人，熬煉他們像金銀一樣……」（瑪三 2、3；另參看賽一 25；亞一三 9）這些經文指出犯罪行為使我們在神面前成為汙穢；罪惡叫神討厭和反感，一如當我們發現本該是潔淨的地方變成汙穢時，我們自己也表示討厭和反感；但在神恩慈的聖潔裏，這一切都解決了，他不單赦免我們的罪，而且幫助我們不再犯罪。

　　在舊約聖經裏，所有潔淨的律例及潔淨的禮儀都指向這種神聖的潔淨工作。同樣，在新約聖經所有有關救贖的經文裏，都把救恩形容為被洗淨和被潔淨（約一三 10，一五3；徒二二 16；林前六 11；弗五 25—27；來九 13、14，一○22；約壹一 7—9），又指基督徒生命中最重要的事情，就是潔淨自己，除去一切使自己在神眼中看為汙穢的東西（林後七 1；弗五 3— 5；提後二 20—22；約壹三 3）。所以，基督徒的洗禮尤其反映些意義，洗禮事實上不折不扣地象徵了潔淨。

　　聖靈使基督徒醒覺到自己的罪汙，並為此感到羞慚，又激勵我們去「……潔淨自己除去身體、靈魂一切的汙穢，敬畏神，得以成聖。」（林後七 1）當我們突出聖靈這方面的工作時，正好顯明瞭聖經一個重點，而在我們這個頹廢的世代裏，一切道德標準不受重視，羞恥之心被視作等閒，這重點實在需要大大的強調。

　　同時，基督徒在現世對純潔生命的追求，意味著他們長遠下去一種自覺的矛盾和掙紮，並常會感到成績未達理想；這方面的著重也是相當正確的，「因為情欲和聖靈相爭，聖靈和情欲相爭，這兩個是彼此相敵，使你們不能作所願意作的。」（加五 17）

　　無論我們是否接受羅馬書七章十四至二十五節作為剖析基督徒經驗的一個橫切面，用以直接闡明上述要點（有些人贊成，有些人不贊成；我們稍後會再作討論），但毫無疑問，保羅在加拉太書正告訴我們基督徒生命裏的實際掙紮。他要我們知道，每個基督徒的生命裏，都存在著兩種敵對的欲望；這兩種力量在動機的層次上彼此為敵。有些欲望表現出人性墮落後一種悖逆神、自私自利的天性；有些欲望表現出由重生而來的超自然、榮耀神和愛神的動機。由於基督徒內心有這兩種敵對的催迫動力，當其中一股動力把他拉向前時，另一股動力便把他拉向後；因此，縱然他恒常的目標是完完全全地服事神，如一首聖詩所說，存著「忠誠專一的心」，他還是發覺他的心靈從未完全純潔無瑕，他所作的事，也並非絕對正確無誤。就這樣，他時時刻刻不能作他所願作的。他在生活中認識到他所作的一切其實可以並且應該做得更好：不單只在他被自己的驕傲、軟弱、愚昧出賣了時如此，他努力嘗試行善為義的時候也是如此。在每一次嘗試之後，在每一個行動之後，他往往看見他在動機上、在表現上，都有許多可以改善之處。他當其時感到已盡所能做到最好的事情，事後回顧都會發現並非做得最好。就這樣，他窮一生之力追求完美，卻又發現他所追求的永遠不能在他掌握之內。

　　當然，這不是說他永不會達到任何程度的義，保羅並非預料基督徒生命是經常完全失敗的，反而，他期望這是不斷的道德成長。「……當順著聖靈而行，就不放縱肉體的情欲了。」這是加拉太書五章十六節對信徒的直接要求，第十七節只不過是這要求的注腳而已。明顯地，保羅在這裏及其他經文教導有關基督徒品行時，他每每期望信徒努力向前，養成聖潔的習慣，積極操練自己，學像基督。

　　保羅說，基督徒既然從罪的奴役中釋放出來，他就可「按著心靈的新樣」（羅七6），實踐愛和公義；凡他現在能實踐的，他都必須去實踐，因為這聖潔的生活是神的旨意（加五 13、 14；羅六 17 至七 6；帖前四 1 一 8）。基督徒能夠且必須藉著聖靈治死他們的罪（羅八 13）；他也能夠且必須活在聖靈裏，走在屬神和善行的道路上（羅八 4；加五 16、25）。意思是說，一些他從前愛做的事，或一般未信主的人愛做的事，他如今放棄不作，而且，他開始選擇作另一些事情。現在，他要追隨自己心靈裏（即在他的意識裏）所感受到屬於聖靈的意願，而不陷溺在肉體的情欲中。基督徒生命必須是公義的生命，這正是他悔改和重生的自然流露，也是基本的要求。

　　談到保羅在第十七節所說的話，我只想發揮這唯一的重點：活在聖靈中的基督徒，會不斷發現他的生命尚未達致本來應有的美善；他經常要面對重重障礙和限制，以及自己扭曲的天性背道而馳的拉扯，他正在打一場前所未有的硬仗；同時，即使是他最好的行為，也不免犯上動機上的罪；他亦發現他每日的生活充滿汙點，他必須每時每刻仰賴神在基督裏的赦罪恩典，否則他就會在罪中失喪；同時，他也認識到自己心靈的軟弱和善變，需要經常求告聖靈賜給他力量，使他在這場內在的鬥爭中能堅持到底。「你確實不能實踐你心想望的那種聖潔生活。」對保羅來說，這句話明顯地道出了人追求聖潔的一些真相。誰可以說他是錯誤的呢？
　　
　　的確，自從革利免（Clement）和俄利根（Origen ）提出清除情欲、淨化靈魂的教導，早期教父記述他們如何頑抗醇酒美人、夜夜笙歌的幻想，以及奥古斯丁用自身的經歷去刻畫罪和恩典的本質以來，信徒不可避免地要與試探對抗的主題就成為基督教靈修教導中一個固定的著重累占。馬丁·路德和加爾文對這方面有很多闡釋，路德宗和加爾文派的信徒，尤其是加爾文派，都緊緊追隨他們的腳蹤。許多世紀以來，不少人曾一次又一次地對這個重點的真確性、現實性和健全性提出質疑與辯論，到如今，已經再沒有什麼見解能認真地挑戰上述重點了。藉著神的恩典，人的生命逐漸被洗滌和潔淨，因此，強調人生掙紮的真實性，是完全合乎聖經和十分恰當的。

[[Keep_in_Step_With_the_Spirit__notes.org#保守我們純潔][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

*** 道德掙紮教義的陷阱
　　即使這樣，經驗告訴我們，當信徒以道德掙紮作為他們思想聖靈的重點時，常會被許多陷阱圍繞。他們會漸漸變成律法主義者，常常為自己和別人定下嚴格的規例，好讓自己對不相干的事情毫不染指，又給自己和別人強加一些呆板並約束性的行為模式，作為抵抗屬世潮流的堡壘，並且大大強調遵守這些人為禁忌的重要。他們的行事為人愈來愈像法利賽人，注重提防那能污染人的事情，以及毫不妥協地堅守原則，多於注重實踐基督的愛；他們變得小題大造，對於沒有真正構成威脅的事物，他們亦毫無理由地懼怕受到污染，又頑固地不肯安心；他們變得沒有喜樂，因為盤據他們腦海的，儘是這場屬靈戰爭如何冷酷無情的思想；他們變成病態的人，終日內省，陷溺於懊悔自己心靈的腐朽，久而久之，滋長出灰暗冷漠的人生觀；他們對於道德成長的可能性感到悲觀，不單看自己如此，看別人也是如此；他們對於脫離罪惡，不敢存什麼厚望，最大的希望只不過是不會比以前更糟。這種種態度可說是屬靈的神經衰弱症，他們歪曲、損害並削弱聖靈使人成聖的工作，因此實際上使聖靈在我們生命中的工作蒙上汙點。

　　我明白這些心態通常是累積了種種因素構成的，諸如天生的性情、早年的教育和訓練，以及因害羞或缺乏安全感而形成的吹毛求疵習慣、低下的自我形象，甚至或者真正的自我憎厭，都往往是一些成因；此外，一些內向的教會文化和社群，都可以導致上述的情況。只不過，現在我想指出的，就是對聖靈認識不足，也經常是一個原因。一如我們剛才討論到的其他兩類人一樣，這類人需要從另一個觀點認識聖靈，從上述我所描寫的那種灰暗、自我中心的屬靈狀況中擺脫出來。一會兒，我就會指出什麼是我所認為的正確觀點了。

[[Keep_in_Step_With_the_Spirit__notes.org#道德掙紮教義的陷阱][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 叫我們醒覺
　　現在，我們必須探討第四種看法，他認為聖靈的職事基本上就是呈示；簡單來說，就是促使我們醒覺到一些事情。這是泰萊主教（BIShop J．V．Tpylor）的著作《仲介之神》（ The Go-between God）裏面所載的觀點。

　　泰萊視聖靈（希伯來文的 ruach，希臘文的 pneuma；兩個原文的意思是「吹動的風」或「呼出的氣息」）為聖經中一個代表神聖「交流」（“current of communication”）的名字，他喚起人對物、對己、對他人，以及對神的醒覺，使人覺察到這一切都是重要的現實，催促我們作出種種抉擇，這些抉擇有時更要求我們作出自我犧牲。聖靈的影響，就是藉著這種「覺醒——抉擇——犧牲」的行為模式顯出來；聖靈就是那位「人生命的仲介之靈」（“life－giving　Go－Between）4，他透過自然界、歷史、人類生命， 及世界宗教施行他的工作，並在其中運行。這種覺醒是對意義和要求的頓然領會，是理性而又感性的。每一次的覺醒和對覺醒的回應，都影響著事後的抉擇和犧牲。自五旬節以來，聖靈持續不斷的工作，就是使個別人覺醒到耶穌的神性，以致他們的生命能活出耶穌在加略山上為罪受死的自我犧牲精神。聖靈要召喚人對這個覺醒作出回應，他在心志相同的人群中所進行的工作最為有效，因為整個群體可以喚起個人的覺醒，而個人又可以提高群體的覺醒。這些論點是泰萊根據歷史悠久和歷史短淺的教會的實際經驗，經過連串反省後得出來的；他視這些教會群體為神聖使命的表徵和途徑，他所有思想都是圍繞著這個中心思想組織起來的。

　　我們以上所綜覽的幾種對聖靈的看法，受一般牧者大力提倡，卻往往被學者挑剔地評為「大眾化的敬虔」；泰萊是位有恩賜的神學家，故此，他的見解比其他人的看法較有深度是不足為奇的。他著作的大部分內容都使人印象深刻。首先，他的觀點由始至終都以神為中心。不僅他的「交流」關鍵思想是根據三一真理的啟示，源自聖靈那「在聖父與聖子之間的永恆職分，使兩者互相察覺」5，而且他比其他人對於聖靈自由主權的本質有更深遠的洞見——那些人認為聖靈是神賜給我們的力量，供我們使用，或讓我們有所表現；只要我們除去障礙，這股力量就會從我們心裏自動釋放出來。泰萊認識到聖靈不是神賜給我們的一種興奮劑，他不是任由我們操縱和支配的。所以，泰萊永不跟隨別人膚淺的言論；他們談論讓聖靈在我們裏面得釋放，其實只不過是靠賴自己的抉擇，憑著自己的意志，根本不是聖靈的作為。泰萊在講述聖靈是我們的溝通者和激勵者之餘，從沒有忘記我們是人——罪惡、愚昧、多變、混亂的人——，而聖靈是我們神聖的主，他在我們心裏的工作是超過我們心思所能理解的。泰萊不容許我們專注浸裏在我們內裏與罪惡的爭戰中，因為他看見聖靈經常把我們的注意力往上往外導引，叫我們以神、耶穌基督及其他人的事為念。

　　因此，泰萊一方面強調每個人在神面前的獨特性（醒覺是屬於個人的事情），另一方面，他的整體取向始終以小組、教會和社區作主導，毫不宣導個人主義。不過，對於文化習尚在聖靈帶領的社群中施加任何限制，他原則上不以為然。他指出，既然耶穌並不屬於他時代的既成文化模式，聖靈在今日也會拆毀一切我們試圖限制他的文化框框。

　　對於「自發和出於超理性反應」的靈息表現——表現在醫治、方言，尤其是預言的恩賜上——，泰萊亦很靈巧地建構了一套神學思想。他用全人的觀念去解釋這些表現：人不是只懂得作理性分析；整個人的各方面都是聖靈工作的範疇。不過他警誡我們防備自我主義。自我主義與不成熟的思想行為互為因果，往往危害靈恩的精神。泰萊再次表現他的智慧（雖然他所表現的智慧或許並非必需）。他探測那既險且真的道理：人愈趨成熟，聖靈的道德指引便愈有創意，帶領我們超越（當然不是偏離）有聖經根據的正規律例範疇。

　　這些都是真正的灼見。

[[Keep_in_Step_With_the_Spirit__notes.org#叫我們醒覺][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

*** 泰萊觀點的毛病

　　與上述長處並排的，是兩項缺點——這些缺點是基於泰萊未能完全按著聖經嚴格的要求去徹底發展他的聖經觀點。

　　首先，他對聖靈所呈示的道說得太少。他討論這個主題時，引用兩節論到神的話語（words）的經文（賽五九 21；民二三 5），然後立即說到約翰福音及教父們所講述的道（Word）——那有位格的神聖之道（personal divineLogos）——，好像話語和道是同一東西。6 然而無論是聖經上的用法或普通常識都告訴我們兩者並非一樣。那些見證有位格的道（the personal Word）的話語（ words），顯然與道（Word）有別。（在這裏，泰萊是追隨巴特「Karl Barth」的講法。巴特肯定地宣稱這些是表現神獨一的道三種形式的其中兩種，但這宣稱本身在神學上是一個謎：聖經裏沒有這種說法；巴特曾聲稱他憎惡那些脫離聖經的推測，但在半個世紀以後的今天看來，似乎他自己也在不知不覺間採納了那種方法。）

　　對於聖靈所激發的覺醒，泰萊的論說尚欠完善，他還需要做的，就是分析聖靈如何證實神所啟示的話語、教訓和資訊；這些教導和資訊，是先知和使徒們從神那要領受，然後重新安排，再以聖經的形式書寫出來的。此外，泰萊還需要分析聖靈如何擔當詮釋者的角色，帶領我們實在地掌握神此時此刻對我們說什麼話。可是，泰萊對這些問題沒有提供任何分析。

　　其次，泰萊對於聖靈所呈示的基督說得太少。出乎意料之外，他並沒有系統地綜覽保羅和約翰對聖靈的論說，沒有探討這兩位對聖靈瞭解極深的偉大新約神學家如何闡述聖靈在多方面體現基督，這大大削弱了他的觀點。他所述有關聖靈的引證使我們覺察到基督，他雖一方面專注講述歷史中的耶穌，另一方面卻對耶穌現今掌權、將要再來、他不斷為我們代求、現在與我們的關係、基督徒與他永恆同在的確實盼望等等，都沒有一視同仁地強調；這些欠缺徹底沖淡了對基督醒覺的意義。

　　泰萊寫道：「那充滿我們異象的基督，不管他是歷史中的耶穌、活著的救主，還是那為我們捨身流血的基督，或是那道和宇宙的主，又或是我的鄰舍和窮人的基督，都不打緊；這些只不過是他存在的某方面。無論我們覺得哪一方面最為真實，要緊的是我們崇敬他。」沒錯，這裏說得很好，但假若泰萊補充說，我們欲要心中的基督形象配得上基督自己，又符合聖經的真理，那我們就需要將基督各方面的真理連結起來，並且加上更多，這將成為更好的教義。

　　就最後的分析來說，我們習慣上怎樣去思想基督，實在是舉足輕重的事；我們屬靈的健康很在乎我們對他是否有足夠的認識，因為認識基督不單只是認識他宇宙性的地位和他在地上的歷史事蹟；反之，猶如墨蘭頓（Melanchthon）很早以前說過，是要認識他的好處——即是要知道耶穌在他所擔當的各種角色中，諸如使者、中保和神救恩的體現等，賜與我們什麼。不過，若然你對基督的認識很少，你對他的好處自然也所知有限。

　　我不是說信徒從耶穌領受的不會超乎他所知的。我先前談論過神的豐盛慈愛，他為愛他的人所作的，是「……超過（新國際譯本「NIV」譯作『無限量的超乎』）我們所求所想的」（弗三 20）；我們應在這裏回想一下這個要點。耶穌基督對於信徒是始終如一的（神人二性的救主、主、中保、牧人、倡議者、先知、祭司、君王、代贖的祭牲、生命、盼望等等），不在乎他們腦海中對這種與基督的多重關係有多深或多淺的瞭解。舉例來說，使徒兼神學家保羅對這些關係的瞭解，比路加福音二十三章三十九至四十三節中悔改的強盜認識更深，然而耶穌的拯救對任何人都同樣豐厚，我們可以肯定，使徒和強盜此時都同在寶座面前；他們在地上擁有神學知識的多寡，絕不影響他們在天家享受與基督同在的福樂。「……同有一位主……厚待一切求告他的人」（羅一○12）——主不單厚待猶太人和希利尼人，也同時厚待不擅長也沒有博覽神學的人，這一點是無可置疑的。

　　但是我所關注的，就是愈少人認識基督，愈早需要提出以下問題：既然他們對耶穌只有蒙朧而歪曲的觀念，他們對耶穌的回應究竟能否真正算為基督徒的信仰？人愈是偏離聖經所述有關耶穌的各種道理（前列的也許是基要道理），掌握基督真理就愈少，以至到一個地步，就是經常談論基督（回教徒、馬克思主義者、通神學者等都會這樣），但實際上並不認識他。

　　因為上述提及的聖經真理，都指出基督是我們問題的答案；這些問題源自神的聖潔和我們的罪，是聖經教導我們針對我們自己與神的關係而發出的。人與這些聖經啟示距離愈遠，便愈發感到那些問題與自己無關，結果他對真正的基督和真正的神的認識便會愈少。假如有人以為今日的英國是被一個前度搖擺舞蹈家依利莎伯所統治，他就住在波利尼西亞一間木屋裏，隨便按他自己的意思立法，這個人可以說是根本對真正的女皇完全無知。同樣道理，要對耶穌的救贖有真實正確的認識，單單知道他的名字是不足夠的。

　　或者，讓我用另一個講法去解釋：耶穌基督的真理與新約神學的真理結合（而我像主流基督教傳統一樣依從新約神學的宣稱），意思正是說聖父藉著聖靈給聖子作見證。固然，只有這神學中的耶穌，才是真正的耶穌。不管在保羅、約翰、路加、馬太、彼得、希伯來書的作者，或誰人的筆下，這新約神學實質上都是宣告耶穌基督的拯救，他拯救我們脫離那捆鎖我們的假神、假信念、假方法、假希望，以及在創造主面前的各種虛假態度等，內裏包藏著各樣外表吸引的宗教和哲學思想。新約的宣告就是為這整個虛謊和假像的萬花筒疹症，他各樣虛假根藏在種種具體的表現中，不知不覺地把普通啟示壓抑了，誤導人心靈中崇拜的天性，使人對神的福音無知或抗拒。羅馬書一章十八節至三章二十節的表達，是斬釘截鐵的；而蔔仁納（ Emil Brunner）也實在寫得正確：「所有宗教都嘗試重見那失落了的神的真理，所有宗教都渴求神的光和神的愛；但在所有宗教裏，亦同時出現一個無底深淵，真理被邪惡扭曲了，而人更用盡方法去逃避神。」8

　　若然如此，我們必須憑愛心堅定地指出神所教導的福音與其他解釋世界真象的說法存在對立，決不能稍有寬讓或基於禮貌而淡然處之。不然，新約聖經所講述「……基督那測不透的豐富……」（弗三 8），以及他拯救我們脫離罪的權勢，除去我們的罪，最終使我們完全擺脫罪和他的果子等闡述，都會因為我們俯就那不協調的思想模式而被沖淡。這實際上是極端而具破壞性地視福音為一種相對的道理。雖然在這些不協調的思想架構裏，也許會有某些新約思想特別受到重視，但新約神學的絕對正確性，他那肯定的地位、絕對的權威，就經常被否定——在這裏，否定的意思是不容許新約神學批判及修正各種思想架構：如印度教、佛教、猶太教、回教、馬克思主義或其他宗教。因為事實上並非所有宗教和所有思潮都提出關乎神和人的相同基本問題，亦不是朝相同的方向尋找答案。

　　有兩種對話正在進行，他們彼此有極大的分別。第一種企圖尋索基督教與其他信仰之間的對照，而這個對照至終是否定一方以肯定另一方的。第二種對話是嘗試在其他宗教信仰中尋找基督，或勉強把基督移植在其他宗教信仰中。有一點必須指出，雖然泰萊談到種族宗教與基督教後期種種信仰如何透過聖靈接觸基督，從而經歷轉變、更新、死亡與復活 9，但我們完全不能確定泰萊所追尋的是第一種而不是第二種對話。這種含糊的情況其實是他著作裏第三個弱點，是由前兩個弱點引發出來的。這兩個弱點前文已經指出——他沒有認真考慮到那「已記下來的神的話語」10 的實在，同時，對於關乎基督的知識，他忽略了在種種試驗以外，必須以新約中論到基督的教導作為量度的準繩。

　　在泰萊的聖靈觀裏，聖靈是一位居間的聖者，他的工作是呈露現實、驅使人作出抉擇，及喚起人以犧牲作回應。前面所述絕不是批評泰萊這個中心思想。要找出能令我們瞭解聖靈一直以來在信徒生命中職事的新約主要思想，並不需要遠超泰萊卻步之處。他帶領了我們，雖不中亦不遠。

[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 追溯我們的思路

　　先讓我們回顧一下所走過的思路。

　　開始的時候，我們注意到聖靈是現今熱門的話題，不同類型的基督徒經驗都確證聖靈的影響，不同基督徒對他的主要職事都有不同的瞭解，這樣表明了（正如我所力言的）並非所有信徒都能正確地看聖靈。許多人對聖靈的觀點雖然未至完全虛假，但肯定是含糊不清和不夠真實的，因此出現了種種缺欠和實際的不平衡現象，有時構成威脅、窒礙聖靈，使我們無力叫聖靈得著榮耀。故此，當務之急，就是更清楚地認識聖靈。

　　為了衡量近代思潮的狀況，我們探討了目前四個關於聖靈職事並極具影響力的主要觀念：生活的力量（power）、事奉上的表現（performance）、行為和動機的純潔（purity）和驅使我們作決定的呈示（presentation）。這幾點事實上是未夠徹底的，我立即可以再加多幾項：辨識力（perception）。催迫（ push or pull) 和個性（personhood）。因為我們一旦離開基督徒的生活圈子，我們會發現有些人實在以為聖靈主要和獨特的工作只是幫助人提高知覺（辨識力），故此，任何意識提升的狀態，不論是宗教的（基督教、印度教，或祭禮的、忘形的、神秘的思想）、美感的（被音樂、性行為、詩章、日落、毒品所引發），或者是理想層面的（熱情的愛國主義、愛情、為一群人或一個目標貢獻自己），都被視為聖靈的印記。我們也曾遇見另一些人，他們忘記了在我們墮落的人性裏那些不受約束的本能、被壓抑的理智及種種複雜病態的妄想如何會被自然界和撒但隨便利用，竟然把聖靈的感動等同於人內心的渴求（一些拉力或催迫），尤其當這些渴求與一些突然、強烈而又重複地出現的視覺和聽覺意象（如幻影、聲音、異夢）相連時，他們就更加確信是聖靈的感動。我們亦曾遇見另一些人，他們聲稱聖靈在有宗教及沒有宗教信仰的人當中一直運行，他的主要工作是幫助人領會自己獨特個性的奧秘、別人的價值，及對真誠關係的需要。

　　若說神的靈永不助人提高醒覺，亦不會透過內心催迫去叫人做某些事情，也不會令未信主的人更欣賞個人的價值，這些說法肯定是錯誤的，我也絕對無意否定聖靈這幾方面的工作，事實上，我甚至會為聖靈這些職事爭辯。可是，今日一般的想法，以為上述其中一項聖靈職事就等於聖靈的主要職事，似乎與事實相去甚遠。其實，自基督來了，聖靈的中心職事是幫助人與基督建立更密切的團契。無疑，因著普通恩典（common grace），聖靈會在世俗和異教的場合中提高人的辨識力和敏感度，但這從來不是聖靈工作的中心。

　　就拿內在的催迫來說，有些人感到內在的催迫強烈地一再出現，有時候還附以聲音、幻象、異夢等，使他們的感覺更形強烈，驅使他們去強姦、去報復、去傷害人、對兒童進行性侵擾，甚至結束自己的生命。難道這些催迫是出於聖靈的引導嗎？這問題根本不答自明。縈繞心間、擺脫不掉的思想、意念（我們上述所談的，正是這種心神的纏擾）不一定源自神；撒但同樣精於製造使人擺脫不了的衝動，正如他能操縱並加強那些發自我們扭曲了的天性的衝動一樣。故此，對於一些突如其來佔據心神的思想，我們必須仔細檢討（最好是請教別人）然後才下結論，斷定他們是否從神的靈而來。其實，這些思想纏擾心神，叫人擺脫不了，已顯示出他們多半不是源於神的靈了。

[[Keep_in_Step_With_the_Spirit__notes.org#追溯我們的思路][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 基督的臨在
　　現在，讓我們回到實際的基督徒生活圈子去看，在這裏，每個信徒至少朝正確的方向，把聖靈與他們在基督裏的新生命或多或少違絡起來。讓我們再一次發出這個問題：在今天，什麼是聖靈工作的本質、中心和重心？在他賦予人能力、扶助人、潔淨人、向人呈現等工作中，究竟有沒有一樣基本的活動把這些連接起來，讓人充分瞭解他的職事？到底有沒有一個神聖計畫，把聖靈賦予人生命的這幾方面工作聯繫起來，指向一個目標？

　　我認為這計畫是存在的。現在，我會嘗試提出我的見解——我這見解是以臨在的觀念為焦點的。我所指的，就是聖靈在教會及基督徒中間，具體彰顯那位已經復活、掌權的救主，即歷史中的耶穌；這位耶穌就是基督。聖經指出（正如我所堅持的）自從使徒行傳第二章五旬節事件以來，聖靈就一直這樣工作，他賦予人能力、扶助人、潔淨人，並且引領世世代代的罪人去面對神。聖靈這樣做是要叫人認識基督、愛他、信靠他、尊崇他和讚美他；這是聖靈一貫的目標和目的，也是父神的目標和目的。至終來說，這就是聖靈新約職事的全部內容。

　　我在這裏談及的臨在，並非傳統神學所指神的無所不在，這種無所不在的思想，在詩篇一百三十九篇、耶利米書二十三章二十三節、阿摩司書九章二至五節、使徒行傳十七章二十六至二十八節等經文內都有記載，是指神維繫著宇宙萬物的存在及其間的活動，同時覺察每一角落的每一件事。無所不在是一項重要的真理，我現在所要說的亦已假設隱含了這個真理，但在我用臨在一詞之際，我心目中所指的，是一些很不相同的東西。我用這個詞的意思，亦即是聖經作者常用的意思，他們說神與他的子民同在——換句話說，神在特殊的環境中工作，賜福給忠信的子民，使他們認識他的愛，得著他的幫助，從而引發他們對他的敬拜。沒錯，神有些時候會追討罪債，「臨近」人施行審判（如瑪拉基書三章五節的例子），意思是他會作出行動，使人們醒悟到他們的行為令他不悅，事實上他現在仍不斷作這些審判；不過，通常當聖經描述神就近他的子民、與他們同在的時候，往往是指他賜下祝福的。

　　聖經中的用語通常是神「與他們同在」。「耶和華與他［約瑟」同在，他就百事順利。」——正如丁道爾（Tyndale）所說，他是個「幸運的寵兒」（創三九 2）。摩西想到要回埃及去就驚恐，因為在那裏他是個通緝犯；他也恐懼要公然對抗法老。神說：「我必與你同在」——這個應許是要驅走摩西內心一切的恐懼（出三 12，另參看三三 14—16）。摩西離世後，約書亞繼承領導重任，神向他重複這相同的應許：「……我怎樣與摩西同在，也必照樣與你同在；……你當剛強壯膽！……因為你無論往哪里去，耶和華你的神必與你同在。」（書一 5、9；另參看申三一 6、8）堅固以色列民信心的，也是這相同的應許：「你從水中經過，我必與你同在；……不要害怕，因我與你同在……」（賽四三 2、5）。馬太在他的福音書裏，一開始就提到神與他的子民同在、賜福給他們：他宣稱耶穌的出生應驗了以賽亞先知以馬內利的預言（以馬內利翻出來的意思就是「神與我們同在」）。並且在馬大福音的結尾，他也記錄了耶穌為一切願意使人作他門徒的跟隨者所賜下的應許：「……我就常與你們同在……」（太一 23，二八 30）。因為耶穌——救恩的賜予者——就是道成肉身的神，基督的同在正是神的同在。

　　事實是這樣的。在新約底下，聖靈那獨特、恒常而又基要的職事，就是在信徒中間體現基督——意思是說，讓他們領會基督與他們同在，作為他們的救主、生命之主和神，也讓他們知道有三件持續的事。

　　首先，是與耶穌的契合：就是與耶穌密交的、敬虔的生活。縱然耶穌現在已不再以形體在地上顯現，而是坐在天上榮耀的寶座上，但昔日耶穌受難前與第一批門徒在巴勒斯坦的密交生活，今天也可以成為信徒的實在經歷。（這正是呈示的意念：聖靈向我們呈示活著的主耶穌，讓我們認識這位元創造主以及這位朋友，好叫我們可以選擇那犧牲的道路，以回應他的愛和呼召。）

　　第二，品格開始更新，愈來愈像耶穌。當信徒以耶穌為模範和力量、敬拜他、學習為他和其他人有所付出甚至舍己的時候，更新便開始。（這裏正好跟「能力」、「表現」、「潔淨」等主題吻合，他們全都顯出何謂離開人性的自私，踏上像基督的人生道路，去過一種公義、忠心事奉、戰勝罪惡的生活。）

　　第三，聖靈使我們肯定自己被神所愛、已蒙救贖，並藉著基督被接納進入天父家裏，因此我們能夠成為「神的後嗣，和基督同作後嗣」（羅八 17）；這種肯定，使信徒心中綻放出感恩、喜悅、盼望、信心——一言以蔽之，這就是確據。（這一點正好幫助我們瞭解許多基督徒信主後的顛峰經驗。耶穌在約翰福音十四章二十一至二十三節應許聖父和聖子要住在我們裏面，這應許藉著聖靈得以實現，為要給我們更大的確據。）這些經驗正好顯明聖靈讓我們認識到基督臨在——借用戴利仁（Samuel Terrien）的描述；這是：「虛幻、難以捉摸、不可預告、不受規限、不能用經驗來證實、外面看不見而內在卻無可抗拒的」11。

[[Keep_in_Step_With_the_Spirit__notes.org#基督的臨在][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

*** 對神的覺醒
　　從整本聖經來看，認識神的同在意味著兩重的覺醒。首先，我們醒覺神在那裏：那位客觀地真實存在的創造主、掌管宇宙之主、萬物的主宰和所有存於時空之物的原動力；每個人的前途，不論是禍是福，都全在他手裏。第二，我們醒覺到神在這裏，他已經就近我們，對我們說話，質詢我們，鑒察我們，顯露我們的弱點、罪惡和罪咎，使我們降卑，同時又用他的赦免和應許提升我們。在神啟示自己是「蘊含三位」（“three－personed”）（套用但思「John Donne」的說法）之前，人只知道有一位神臨在。可是，現在透過道成肉身的啟示和新約聖經裏的啟迪，有關神的知識已變成了有關聖父、聖子和聖靈的知識；認識神的同在變成了因著聖靈的工作與聖子相遇及相交，並藉著聖子與聖父相交。故此，認識基督的同在，就是在自己時面找到這份對神的雙重覺醒，覺察到他既真實又接近；同時，這種醒覺圍繞著那位來自加利利的人，也就是多馬親口呼喊為「我的主！我的神！」（約二 O28）的那一位。保羅寫道：「那吩咐光從黑暗裏照出來的神，已經照在我們心裏，叫我們得知神榮耀的光顯在耶穌基督的面上。」（林後四6）他所描述的，正是這種對神的認識。

　　自五旬節以來，聖靈特殊的職事是體現基督，這是新納聖經明顯的資訊。正如許多解經家常常指出，聖靈常被視為神的兒子耶穌基督的靈（徒一六 7；羅八 9；加四 6；腓一 19；彼前一 11）。那居於我們心裏的靈，正是那位降臨在耶穌身上，並住在他裏面的靈（路三 22，四 1、14、18，一 O21；約一 32，三 34；徒一 038）。耶穌擁有聖靈，也是賜下聖靈者（約一 33，一五 26，一六 7，二 O22，另參看七 37—39；徒二 33；約壹二20、27）。耶穌被提後，離開門徒，聖靈便臨到門徒身上；這實際上相當於耶穌回到他們當中（約一四 16、18 一 21）。聖經形容神的靈（也就是基督的靈）住在我們心裏為基督在我們心裏（參羅八 9 一 11），正如論到那被高舉的基督所親自宣告的資訊時，就說是「聖靈向眾教會所說的話」一樣（參啟二 1、7、8、11、12、17、18、29，三1、6、7、13、14、22）。

　　再者，保羅在哥林多後書三章十六節寫道：「但他們的心幾時歸向主，帕子「蒙蔽心靈的」就幾時除去了。」這句話是出埃及記三十四章三十四節的迴響，其中記述摩西如何在與神說話時揭去帕子。）然後保羅繼續寫道：

　　主（即上一節經文所述的主）就是那靈（故此，「歸向主」的意思就是「承當這新約的執事，不是憑著字句，乃是憑著聖靈「請參閱第六節 1）；主（耶穌）的靈在哪里，哪里就得以自由。我們眾人既然敞著臉得以看見（或作反照：兩種譯法都可以，而且同具真確的意義）主的（耶穌的）榮光，好像從鏡子裏返照，就變成主的形狀，榮上加榮，如同從主的靈變成的。（林後三 17、18）

　　這些經文所表達的，並不如一些人所想，以為新約聖經作者看不見聖子和聖靈有什麼清晰的區別，其實新約聖經作者看見聖靈在五旬節後的工作主要是讓我們體會那坐在寶座上的基督的同在、話語和作為；只有掌握這基本的新約角度，我們才能清楚認識聖靈。

[[Keep_in_Step_With_the_Spirit__notes.org#對神的覺醒][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 綱要
　　本書認定聖靈受託去體現基督，以這個真理作為瞭解聖靈多面職事的線索。在我看來，現時許多對聖靈工作的綜覽，都未能循這途徑把資料綜合起來，這是他們的缺點。一個表面化的記述，單指出聖靈在新約時期如何被彰顯，以及新約作者怎樣述說這些表彰是不足夠的，我們需要進一步探討這些記述如何配合他們對神、他的工作和他的真理的整套觀念——換句話說，就是他們的整套神學思想——，因為缺乏這方面的探討是一個致命傷，使我們思想聖靈在我們生命中的工作時，變得以人為中心，以經驗作根據，又毫無準則。難怪許多有關聖靈的著述，本來可以是十分精彩的，卻沒有如期望中叫讀者得著幫助，讀者亦不如他們想像中那般獲益。因為今天能幫助我們活在聖靈中的，並不是一些叫我們向聖靈敞開心懷的勸勉——這方面的勸勉我們已足夠有餘了；反之，我們所缺乏的，是對聖靈工作全面而通達的神學透視，好讓我們有一套整全的觀念，能充分瞭解聖靈在教會、小組及個人生命中那自由、不受羈絆及多種形式的運行（聖靈這方面的工作是今日基督教所強調的）。新納聖經所論述有關聖靈的主要真理，是聖靈體現基督的臨在和相交；我希望循這個概念去發展出通達的神學觀點，希望至少能勾畫出一個綱領。

　　在聖經的基礎上，我的目標和觀點可以這樣表達：耶穌在他被賣的那一夜，述說有關聖靈的事：「他要榮耀我……」（約一六 14），意思就是「他將要使我在人的眼中得榮耀，使他們覺察到那本屬於我的榮耀，並且在我通過十字架、復活和升天回到父那裏去，坐在我國度的寶座上時，這榮耀將更大。」這個關於聖靈從前是什麼，現今又奉差遣來做什麼的基本定義（正如我一直認為的），給我們一個完整透徹而具方向性的參照標準，我們必須透過他整體去看聖靈的新約職事，否則我們很難充分瞭解聖靈職事的任何一部分。

　　然後，耶穌繼續說這榮耀將要如何成就，「因為他要將受於我的，告訴你們。」耶穌說「受於我的」是什麼意思呢？他的話至少有這個含義：「一切關於我的事實和真理，就是道成肉身、是天父的同工——創造萬物、眷顧神的子民和賜下恩典，又是這世界正式的君主，即是那位掌管宇宙萬物的主人［參一七 2］。不管人們是否承認我這一切，事實卻是如此。」不過，當然他還有這樣的含義：「一切關於我的事實和真理：我是你神聖的愛人、你的中保、你的新約保證人、你的先知、祭司和君王，又是把你從罪咎和罪惡的權勢、世界的敗壞及魔鬼的掌握中拯救出來的救主，並且是你的牧人、良人、朋友、你的生命、你的盼望、你信仰的創始成終者、你個人生命歷史的主，將來要帶領你與我同在，分享我的榮耀。所以，我是你的道路和你的獎賞。」故此，因著我與你彼此的關係，「受於我的」也就是「受於你的」了。

　　我的童年屬於低唱抒情歌的年代，記得當時有一首民謠，名為「你的一切」（“All the Things You Are”），歌曲結尾是這樣的：「……有一天，我將會認識那神聖的一刻，那時候，你的一切也成了我的一切。」聖靈說服我們相信耶穌在他榮耀裏的一切都是為我們預備的，藉此讓我們看見耶穌的榮耀。套用保羅在哥林多前書二章七節的說法，是「使我們得榮耀」——認識這個真理比輕歌淺唱的浪漫時刻更神聖。

　　耶穌說：「他要……告訴你們。」這個「你們」是單指使徒還是所有與他們一起的基督徒呢？主要是指使徒而言：他們得著這些真理的直接啟示。但其次亦是指所有信徒：透過使徒口傳或筆錄的見證，聖靈會教導眾信徒認識同樣的真理。使徒必須與神的眾子民分享他們屬靈的領受，昔日如此，今天亦然。

　　第十五節有如一個注腳。為了不讓上一句話我的一詞所涉及的整個範疇和含義遭忽略，耶穌繼續說道：「凡父所有的，都是我的，所以我說，他要將受於我的告訴你們。」加上這句注腳，是為了防備一些可能產生的誤解，避免人以為父神和他的工作比耶穌本人及其工作更超越，又或者（反過來說）父的屬性、宣稱、能力、計畫、展望和榮耀都比耶穌的更偉大，更廣遠。「凡父所有的，都是我的」；子和父是平等的；父的旨意是「……叫人都尊敬子如同尊敬父一樣……」（約五 23）最終來說，一切基督徒真實信仰、敬拜和實踐，都建立在這神聖的目標上。

　　在以下的篇章裏，我會從上述的角度嘗試解釋聖靈的職事。我會指出聖靈如何使父的喜樂增加，他所作的，就是藉著宣告，叫子得榮耀，引導我們作出回應，存崇敬的心去榮耀子。我始終堅持所有對聖靈多方面工作的解說——或者套用一個專門術語：「聖靈論」（pneumatology）——都需要從以下立場去闡釋：一方面，父的旨意是要子被認識、被愛、受尊崇、受讚美，並在萬物中居首位；同時另一方面，透過賜下聖靈，子應許與他的子民同在，從今直到永遠。除此以外，沒有一種解說能完全合乎基督教精神。我計畫在本書裏，指出在一套純正基督教聖靈論裏的一些主要成分；因此我的闡述會一貫地建基於約翰福音十四章十六至二十三節及十六章十四、十五節中耶穌所親自表達的思想上，而不會在他們以外另找基礎。我希望這樣的綱要是可接受的，並且我相信這是今天所需要的。我現在就循此路線去探討。

[[Keep_in_Step_With_the_Spirit__notes.org#綱要][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 注文
　　1 Steven Barabas，So Great Salvation（London：Marshall， Morgan＆Scott，1952），p．v．這本書提供一個對凱錫克信念的詳盡分析。另參考
J．C．Pollock，The Keswick Story：The Authorized History of the KeswickConvention（London： Hodder＆ Stoughton，1964）。
　　2“‘Keswlck’ and the Reformed Doctrine of sanctification，” Evangelieal Quarterly，27，No．3（1955 年 7 月）：第 153 一 167 頁。請看當時編者 F．F．Bruce 的評論，“In Retrospect：　　Remembrance of Things Past，”（Grand Rapids：Eerdmans，1980），第 187、 188 頁。
　　3 John Owens， Wods， ed． W． Goold（London： Banner of 們 Truth，1967),4：437．我們可以爭辯說，新約聖經列出的屬靈恩賜包括了性情上的質素，是歐文著重理智的分析所沒有的，然而這亦不影響他所講述有關語言方面恩賜的真理。
　　4 John V，Taylor，The Go－Between God（New York：Oxford　University Press，1979），第 212 頁。
　　5 同上，第 102 頁。
　　6 同上，第 58—62 頁。
　　7 同上，第 241 頁。
　　8 Emil Brunner，Revelation and Reason（Philadelphia： West-minster，1946），第265 頁。
　　9 Taylor，第 191 一 197 頁。
　　10  Anglican Article 20．
　　11 Samuel，Terrlen， The Elusive Presence：Towards a New　Biblical Theo1ogy（San Francisco： Harper＆ Row， 1978），第 457 頁。

[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

* 2_聖經裏的聖靈

** 屬靈恩賜
　　在第一章裏，我討論過一些關於屬靈恩賜的問題，在這裏我們需要更詳盡地探討這問題。

　　保羅強調屬靈恩賜是惠及所有基督徒的，因此基督身體裏的總動員事奉應該成為各教會的法則；近年來，這種思想普遍被接受了，我們應該為此高興。千多年來，大多數教會陷入教權主義的掌握中（衛理公會團體、普利茅斯弟兄會和救世軍等受人尊敬的組織除外），總動員事奉的思想是向好的一大轉變。雖然今天很多教會的平信徒仍處於被動狀態，許多神職人員仍舊助長這種狀況，因為他們害怕受到其他思想的威脅，然而這主流見解已經轉移，從前平信徒的事奉只屬於那些特別熱心的信徒，現在，平信徒事奉成為實踐門徒生命一個必需的部分。從前向信徒發出挑戰，要他們認識自己的恩賜和尋找自己事奉的職事，似乎只是屬於虔誠的抗辯宗溫室裏栽培出來的奇花異卉；但這種觀念現已轉變了。羅馬書十二章三至十三節、哥林多前書十二章和以弗所書四章七至十五節等經文中的有力論點，現在已普遍被接受了；今時今日，天主教與抗辯宗、自由派與保守派、靈恩派、普世派和各宗派的福音派信徒，均一致贊成每個基督徒都擁有恩賜，在教會整體的事奉裏各有自己的責任。這真是好消息啊！

[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

*** 什麼是屬靈恩賜
　　可是，我們對恩賜的想法十分膚淺。不錯，我們說恩賜從聖靈而來（保羅稱之為「聖靈的彰顯」，見林前一二 4—11）然而我們仍舊認為恩賜是「才幹」（即能夠運用純熟技巧，將事情辦得圓滿妥當的能力），或者是超自然的新穎技倆（說方言、醫治、直接從神領受資訊以傳給別人等等能力）。我們尚未習慣以教會的元首基督及他目前從天上在我們當中進行的工作來給恩賜下定義；就這方面看來，我們還沒有按著聖經真理去思想恩賜的問題。保羅在哥林多前書的開始，為信徒感謝神：「……因神在基督耶穌裏所賜給你們的恩惠；又因你們在他裏面凡事富足，口才、知識都全備，……以致你們在恩賜上（charisma ）沒有一樣不及人的……」林前一 4、5、7）保羅的話明確指出恩賜是在基督裏所賜的，是從基督而來的富足。哥林多前書十二章所論述的，是假設讀者已肯定了第一章四至七節所確立以基督為本的觀點。我們先看清楚這一點是很重要的，否則，我們就會把天生才幹與屬靈恩賜混淆，始終分不清。

　　保羅或其他新約聖經作者，都沒有為我們界定何謂屬靈恩賜，但保羅聲稱運用恩賜能使人得著造就（即「建立」，林前一四 3—5、12、26，另參一七章；弗四 12、16），這正好反映出他對恩賜的看法。對保羅而言，只有藉著基督、在基督裏、效法基督及回應基督，人方可得著造就。「造就」一詞的意義傳到後世變得較為通俗，比保羅的原意寬鬆得多；在保羅看來，造就是對基督並與他有關的各方面有愈來愈深入和豐富的認識，而個人與他的關係更漸趨完美；除此以外再無別的含義了。因此，我們給屬靈恩賜下的定義，必須以基督為根據：是某些能力的具體表現，藉行動或言語去表達、頌贊、展現及傳揚基督；在此以外再沒有造就可言。

[[Keep_in_Step_With_the_Spirit__notes.org#什麼是屬靈恩賜][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

*** 屬靈恩賜的運用
　　我們應當留意，一般來說，我們時常將「尋常」與「不尋常」的恩賜，或「自然」與「超自然」的恩賜作含糊不清的劃分，但在這兩組恩賜之上，還有更進一步的劃分：語言的恩賜及樂善好施的恩賜（即對他人肉身和物質上的需要作出友愛的幫助）。在羅馬書十二章六至八節裏，保羅談論恩賜時，在這兩類恩賜之間跳來跳去。他列舉的恩賜中，第—、第三和第四項，是關於說預言、教導及勸慰，屬於言語的恩賜；而第二、第五、第六和第七項，是關於服事（diakonia）、將財物分贈、領導和行善，都屬於樂善好施的恩賜。縱使這兩類恩賜在形式上極不相同，但從保羅的表達方式看來，我們應該曉得，對保羅來說兩者並沒有終極的神學分歧。

　　在這裏，我們必須掌握一個真理，我們運用屬靈恩賜，無非是基督藉著他的身體去事奉他的身體，事奉天父，事奉全人類。基督從天上使用基督徒作為他的嘴、他的手、他的腳，甚至他的笑容；他藉著我們——他的子民——此時在世上說話、行動、與人相會、去愛和拯救人。這似乎是（雖然有人持不同意見）保羅對教會作為基督身體的描繪的部分意義。在這個身體裏，信徒是肢體，即四肢或器官：頭是全身的指揮中心，肢體隨從頭的指揮行動。

　　保羅對以弗所教會及其他地方的信徒這樣寫道：「（基督）來傳和平的福音給你們遠處的人……」（弗二 17；我認為以弗所書是一封傳閱的書信，以弗所教會是其中一個傳閱的目的地。）基督怎可以這樣做呢？他並非靠自己複後的身體去做，而是靠著像保羅這些信徒運用他賜予他們講道和教導的恩賜。同樣，保羅給腓立比信徒寫道：「我的神必照他榮耀的豐富，在基督耶穌裏，使你們一切所需用的都充足。」（腓四 19）神又怎可以這樣做呢？至少，有部分是藉著基督透過聖靈工作，賜予腓立比信徒樂善好施的恩賜。信徒奉基督的名彼此教導（參帖後三 6），也因著他們是基督徒而彼此關懷（參可九 41），這樣，基督便透過他們親自賜下祝福。對於關懷的實踐，基督曾經明確地指出：「……這些事你們既作在我這弟兄中一個最小的身上，就是作在我身上了。」（太二五 40）因此我們或可以同樣明確地表示，若其他基督徒給我們諒解和鼓勵，在我們有需要的時候幫助我們，無論採用什麼形式，其實都是基督親自工作，透過他們帶給我們這些益處（參林後一三 3；羅一五 18）。

[[Keep_in_Step_With_the_Spirit__notes.org#屬靈恩賜的運用][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

*** 恩賜帶來的祝福
　　我給恩賜（chartsmata）的定義，是表彰基督的能力表現。以某種獨特方式去講或做的能力——我們或許稱之為「表現」的能力——並不是恩賜，惟有那些被神使用去造就信徒的能力，才稱得上是恩賜。有時候，神永不會使用一些與生俱來的才幹去造就人，但有時神又偏會使用一些被人判斷為不及水準的表現去造就人。這是一貫的特色：神顯明他所拯救和使用的人的軟弱，不讓任何東西勝過或遮蓋他的榮耀（林前一 27 一 29；林後四 7，另參一二 9）。因此，當我們說基督徒有恩賜時（羅一二 6），意思並不是說他們在什麼方面顯赫出眾或很有效率（或許是，或許不是，各人表現都不同），而是神已經很明顯地使用他們某方面的能力來造就人。這使我們確信他將來也會繼續這樣使用他們。我們需要把人辦事的能力和神賜福的特權清楚劃分，因為構成恩賜的，是我們的才能被神使用，而不是才能本身。若然我們所作的不能經常為他人或自己帶來可辨認的屬靈益處，我們便不要將自己處事的能力誤以為屬靈恩賜。

　　最初司布真教牧學院（C．H．Spurgeons PastorsCollege）的入學手續就採納了這項原則，候取生需要提供資料，證明他們曾經擔任講道和教導的工作，並曾使人蒙福；若缺乏這些證據，儘管申請人有多大的才能，都會被視為缺乏牧者恩賜，而拒絕接受申請。

　　五旬節派及靈恩派信徒宣稱神在他們當中重新興起新約時代的所謂表記恩賜（sign gifts；如說方言、翻方言、說預言和醫治）。我稍後將會在本書討論到我為什麼不接受這樣的宣稱；但現在即使假設我的觀點錯誤，他們的說法真確，我的原則仍舊適用，一如適用於有教導和行政技巧的基督徒身上。說方言及按手治病的能力，很可能在教會內外都同樣找到——我想事實上確是如此；這些能力不一定是屬靈恩賜，因為你不可以單單憑表現來界定恩賜（charisma），恩賜的定義必需包括神與人的關係，神在基督裏透過恩賜建立信徒；否則，即使所謂「恩賜」在形式上與真正屬靈能力的彰顯一模一樣，也只能算是屬肉體而不是屬靈能力的彰顯。有些從前是五旬節派或靈恩派的信徒告訴我們，他們發現以往說方言的能力是屬肉體的，我們大可同意他們的體會，而無需下結論評定所有說方言的恩賜都是如此。那構成及界定什麼是「恩賜」（charisma）的，並非行動的形式，而是神的賜福。

[[Keep_in_Step_With_the_Spirit__notes.org#恩賜帶來的祝福][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

* 6_聖靈的路徑_解釋聖靈生活

　　現在，我們來到一個主要的問題，是我們一直為他開山辟路的。對於獨特的靈恩經驗，我們應該以怎樣的神學觀點去看他呢？即是說，我們怎樣以神的概念來解釋他呢？當他們自稱他們的屬靈經驗比其他人更加超越的時候，我們應該怎樣看聖靈在他們身上的作為呢？事實上，這是靈恩運動向我們提出的一個主要問題。可是，我一方面可從其中心的信念及倫理上的果子而得出結論，認定神在他們中間，另方面，又發現「靈恩派」和「非靈恩派」的屬靈氣質比我們有時候所在意到的更加相近；這樣，我令到這個問題更加難以解答。倘若靈恩社群中的典型屬靈經驗是沒有基督在其中、沒有愛心和驕傲自負的，那麼，我們的疑問就不會出現，因為我們根本沒有理由將這些經驗歸功於聖靈；可是靈恩運動的情況正好並非這樣，那麼，這個問題就來得更加尖銳，且無法逃避了。因為我們必需面對一個事實，靈息運動用以解釋其自稱擁有的特色的一個最普遍宣告的神學觀念，是十分不合乎聖經的。

　　對於一個看自己為復興真正基督徒經驗的力量的運動，這個事實引起的問題肯定是顯然易見的。經驗是一個含糊的字眼，而種種經驗（即是思想與感情的特殊狀況）落在不全然被聖化的罪人身上，必然如同雜貪混在黃金裏。沒有任何經驗單憑這經驗的發生本身就可證實是從神而來，為要推展他恩典的作為。基督徒擁有的經驗，不一定就是基督徒經驗。一個經驗若是出於神恩典的賜予，他在聖經真理的試驗下，必能證明在其中心有一種加強了的醒覺——對於關乎神的一些啟示的真理的醒覺，以及對於我們作為受造物、罪人、受益人、信徒、養子、被買贖的僕人，及在其他各種身分下與神的關係，有強烈的醒覺。我們曾經以這個標準去量度靈恩派經驗，也發現他們在這一點上沒有缺失。可是，當這些經驗被用來印證某些誤解聖經的信念時——時常有人這樣做——，我們就只剩下兩個選擇：一是排斥這些經驗，看這些經驗為虛妄的，甚至可能源於撒但，否則，就重新給他們神學上的闡釋，表明這些經驗實際證實和確定的真理，與靈恩信徒所以為的有所不同。至少對於靈恩見證的主流，這是我們現在要作的抉擇。

　　有些人注意到靈恩經驗宣稱要證實的東西是錯誤的，他們採取頭一個立場，迅速批評這運動是虛妄和危險的。可是，想起有時候（並非經常如此）靈恩派信徒提出他們那些錯誤的主張時那種自嗚得意的態度，又天真幼稚地誤用聖經，而最令人懊喪的是，許多靈恩派的發言人，似乎對於真理的問題漠不關心，凡此種種，我們又不能完全譴責那些對靈恩運動口誅筆伐的人。我承認我也是其中一個受到靈恩運動衍生上述種種現象所困擾的人，不過，無論如何，我從靈恩經驗裏看見神在其中工作，因此，我大膽作出第二個選擇——就是嘗試重新建構其神學觀念。我在這個選擇上所作的，請讀者評斷。

　　首先，讓我們流覽一下傳統五旬節派對靈恩經驗的說明，這是大部分在德國以外的抗辯宗靈恩派信徒所持守的看法。這就是我曾經稱之為復還論的觀點，他們將使徒行傳第二章所形容門徒在五旬節的經驗，以及哥林多前書十二至十四章所形容哥林多教會的經驗，看為今日基督徒應該追求的標準規範、理想和目標。這觀點的中心建立在一種靈洗的觀念上，他們認為靈洗是「一種特殊的經驗，有別於信主經驗，通常在信主後才有的。在這經驗裏，人領受了全部的聖靈進入他的生命中，因此滿有力量去事奉和見證。」1 他們認為除非信徒經歷聖靈的洗，否則欠缺神早已為他儲備的必需資源，所以，他們命令基督徒尋求這種經驗，直到得著為止。2 這經驗一旦臨到，他就被提升，而且通常會（有人說是一定會）說方言，作為內在已發生了的經驗的外在印記。既然他們相信一個人只有如此才能領受「全部的聖靈」不管他們為這怪異的用詞如何注解），他們給這種經驗神學上的闡述，就是認為這種經驗完成了整個信奉基督的入教過程，一如聖公會會友之間的安立甘大公派理論，水禮只是開始，在堅信禮中領受聖靈才圓滿完成整個入教程式。3

　　最近，鄧恩（James D G． Dunn）、蔔仁納（F．D．Bruner）、史陶德（J．R．W．Stott）和賀其馬（A．A．Hoekema）對這觀點都有全面透徹的剖析，我們在這裏亦無需多費筆墨。我在這裏單提出以下兩點就已經足夠了。首先，若我們接受上述的觀點，這觀點會迫使我們評價非靈恩派基督教——即是，那些不認識或不尋求悔改後聖靈施洗的基督教信仰——為低下門徑、次等，並欠缺了一些重要的東西；可是，其次，這觀點不能從聖經中成立，因為這觀點不能前後貫徹地解答一些從聖經引伸出來的反問，例如以下三條問題。

[[Keep_in_Step_With_the_Spirit__notes.org#6_聖靈的路徑_解釋聖靈生活][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 翻方言
　　在我來看，有關翻方言這問題，似乎是最莫衷一是的。翻方言就是將所說方言的訊息內容（一如他們自己所聲稱的）宣佈出來。復還論引導我們將說方言及翻方言與哥林多教會的方言（charismata）等同。保羅給「翻」方言的用字是 diermeneuo（林前一二30，一四 5、13、27），可以指到解釋任何不明白的事情（一如路二四 27 所載的）；這辭彙與語言連結起來很自然是指到把字句本身蘊含的意思翻譯出來（一如徒九 36 所載）。從保羅的話看來，他顯然認為哥林多信徒的方言是帶有可翻出來的意義的（—四 19-13），而今天的翻方言者對今天的方言亦有相同的假設，把他們對方言的解釋視為方言的實際翻譯。

　　然而，他們的表現是令人因惑的。那些流暢、肯定而又自然流露出來的解釋，後來卻被證實是千篇一律、含糊不清和無所傳達的。其中造成了許多荒誕的錯誤。喬達（Kildahl）告訴我們非洲土話主禱文如何被翻為主再來的訊息。27 一位我曾教導過的埃塞俄比亞牧師，參加一個說方言的聚會，他誤以為是一個非正式的多種語言讚美崇拜會，於是，他站起來用基茲話（ Ge’ez，譯者注：一種已廢的閃族語，今用於埃塞俄比亞基督徒的禱文中。）背誦詩篇第二十三篇，這是他出生的科普替族（Coptic）崇拜時用的古老語言；他的背誦立刻被當眾翻譯出來。翌日，他憂愁困惑地告訴我：「全都翻錯了。」喬達也報導過一件事，同一段方言錄音經兩個不同的人翻譯，其中一個翻為「為一份新工作尋求引導」的禱告，另一個則翻為「為一次嚴重大病最近康復而獻上的感恩」。當告訴翻方言的人兩種解釋有出入時，「那翻譯者毫不遲疑，亦不自辯地說神給予一個翻譯者一種翻譯，又給予另一個翻譯者另一種翻譯。」 28 那翻方言者的經驗是，「方言的解釋」是即時浮現腦海的，換句話說，聽見方言之後，那些即時深印腦海的思想就視為那段方言的解釋。他們宣稱神直接賜予翻譯的內容；就好像靈恩派的預言一樣，他們持相類似的宣稱，只要該預言是合乎聖經的話，他就可以成立，不能修改，因為他是無從驗證的。我們可以看出一個翻方言的人——尤其是一開始就滿腦袋儲存了許多聖經真理的人——如何能夠藉著與講者、或講者的聲線語調、或聚會的氣氛共嗚感應而產生恰當並造就人的「解釋」。可是，至於這些解釋如何能夠直接表達所剛剛聽到的聲音的意義，以致實際上將一種不明白的言語翻譯為一種能明白的言語，那就難以理解了。

　　我不會妄自憑幾句翻譯錯誤的例子作為基礎，去全盤否定所有方言的解釋，看他們為虛妄的，同時，我同意撒瑪連（Samarin）的意見，他認為說方言加上翻方言的宗教儀式所產生的團結友愛本身可以是有價值的。 29 但我想，因此就假設我們已重獲保羅所說的翻方言恩賜，卻是十分危險的。無他，事實的證據委實太不肯定了。

　　賀其馬提出當說方言帶來祝福的時候，祝福的源頭「並不是方言本身，而是說方言時候的心境，或者說……在方言說出之先，一顆尋求更多被聖靈充滿的心。」 30 這個意見似乎比任何認為現時人所說的方言，在思想暫時停止活動的情況下，這方言本身能造就人的說法來得實在。同樣，翻方言也可以帶來祝福，是由於他傳達了聖經的激勵，而不一定像一些人的想法，認為這些必然是神所賜方言的神授解釋，就如當日在哥林多教會裏被翻出來的方言可能是神授的一樣。

　　走筆至此，我們必需就醫治和說預言提出一些反問。

[[Keep_in_Step_With_the_Spirit__notes.org#翻方言][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 醫治的恩賜
　　靈恩派的醫治職事能否令人信服地與哥林多前書第十二章二十八及三十節描述的醫治恩賜等同呢？當然不可以。

　　使徒時期教會醫治恩賜的典範只能夠是屬乎使徒擁有的醫治恩賜，而耶穌自己的醫治職事就是他們的典範。可是，耶穌和門徒是直接用他們的話（太八 5 一 13，九 6、7；約四 46 一 53；徒九 34）或者他們的撫摸（可一 41，五 25—34；徒二八 8）來醫治的。然後，病者立即得醫治（太八 13；可五 29；路六 10，一七 14；約五 9；徒三 7；有一次分兩階段進行醫治，每階段的效果是即時的，可七 32—35）。身體上的殘缺（例如跛子、瘸子），以及功能性、徵候的和心理引致身心上的疾病（徒三 2 一 10；路六 8—10；約九），一概獲得醫治。有時候，他們叫死了多天的人復活（路七 11—15，八 49—55；約—一 1 一 44；徒九 36—41）。他們醫治一大群人（路四 40，七 21；太四 23、24；徒五12—16，二八 19），並且沒有任何記載說他們嘗試醫治而結果失敗的（除卻有一次門徒忽略了禱告，要由耶穌接替他們進行醫治「可九 17—29」）。再者，他們醫治的結果是持久的；沒有任何跡象顯示得醫治者後來舊病復發。對於現今五旬節派及靈恩派醫者的職事，以及那些為病者禱告的人的職事，無論人如何說他們有神特別的呼召，他們當中沒有一人有上述如此驕人的成績。

　　所以，我們不能像某些人有時候的想法一樣，假設現今靈恩派醫治的能源一定就是保羅在哥林多前書十二章二十八節所講述的。在使徒時代，醫治的恩賜比起現今靈恩派信徒看來擁有的醫治恩賜，在本質上是更超越的。我們頂多可以說，靈恩派醫者有時候並在某些方面可以表現得像新約時代有恩賜的醫者一樣，而每次這樣的場合都印證了神的觸摸仍然具有他自遠古以來的能力。可是，這並不等如說在這些人的職事裏，新約時期的醫治恩賜又重新出現。

[[Keep_in_Step_With_the_Spirit__notes.org#醫治的恩賜][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 預言的恩賜
　　「靈恩派的預言能否確實被視為新約表記恩賜的復興？」當然不可以。

　　我提到的預言是指領受和傳達那聲言是神的訊息的東西。預言是靈恩派團契一項固定的特徵。一般對於預言的信念是（1）直接從神而來有關神的心思的啟示，在別處是無法知曉的；（2）預言經常包括神對未來計畫的特殊指引；（3）預言的正確口述形式等同舊約時代神的曉諭，那說話者通常是神自己；和（4）預言是使徒教會的一個表記恩賜，與其他的表記恩賜一樣，自教父時代中期至二十世紀，在教會中是暫時失效的。可是這一切信念都很值得懷疑。

　　首先，彼得在五旬節曾經引述約珥的預言，指出普世性的預言為聖靈時代的一個記號（徒二 17—21）。因此，當時說預言是一項所有信徒都能夠參與，並且也許期望去分享的活動（參徒一九 6；林前一四 1、23—25）；固然，看來也並非所有信徒都可以恰當地稱為先知（林前二 29），大概因為他們在預言職事上的參與太過斷斷續續。可是，既然說預言原則上是一項普世性的基督徙活動，那麼，我們既不應以為說預言只限于使徒時代，更不應該以為說預言會在任何一個時代消失，所以，對於那些假設預言已大多數不存在於教會生活中的理論，我們理應存疑。

　　第二，雖然個別的先知在主前和主後間或被聖靈感動說出未來的事（參太二四 15：徒—一 28，二一 10、11；彼前一 10 一 12；啟一 3，二二 18），先知職事的精髓卻在乎宣告神此時此刻要向他子民說的話，通常這意味著將啟示的真理應用出來，而不是增加神的啟示。一如舊約先知傳講律法，呼籲以色列人面對神與他們所立的約的順服要求，他們若依約順服，就能得著所應許的祝福，不然，就要受咒詛，同樣，新約先知傳講福音和信心的生命，看來是為了叫人悔改，造就人和鼓勵人（參林前一四 3、24、25；徒一五 32）。保羅願望整個哥林多教會都能分享這個職事（林前一四 1、5）。因此，一個很自然的假定，就是在一般情況下，（縱非每時每刻，也肯定有些時候是如此，）先知的「啟示」（林前一四 26、30）是一種由神引發的真理應用，一般而言，這真理早已啟示出來，而不是揭露一些以前從末知道，亦無法從其他途徑知道的有關神的思想和意願。由此推論，同理，任何藉言語加強聖經教導，以應用於聽者身上的方式，在今日大概可以正確地稱之為預言，因為本質上這確實就是預言了。

　　第三，保羅指導信眾在聚會中聽基督徒先知說話時，該「……慎思明辨」（林前一四 29），可見新約裏潛在的普世性預言，並非絕無謬誤、不容修改的，即使未至於需要實在地予以更正，至少也有斟酌的餘地。新約先知藉語言形式傳達他們的訊息時，聖經上沒有任何指示說他們以天父或聖子的角色自居。愛基遜（ Dayid Atkinson）說：「今日在靈恩派聚會中說預言常以單數第一人稱來發言，……這看來不是說預言的要素，而是一種次文化發展出來的習性。……先知訊息的權威不在其形式，而在乎其內容，像靈恩派採用的那種形式，只會使人更難於慎思明辨。」。32 愛基遜的話實在很真確。對於不屬聖經正典的預言，正正由於我們無法保證其內容的充分表達和思想的完全正確，他們必需受到試驗，意思是，我們要用辨識力來聆聽。因此，某些人的觀念，那認為聖經正典裏神直接說話的預言形式，也必須重現于現今教會那衍生自昔日預言、非無誤又不屬正典的預言裏的看法，似乎是混洧和錯誤的。

　　最後，當靈恩派先知預言未來的事情，用單數第一人稱的措辭表達，一如這預告本身是神直接的宣稱時，單純從他們語言表達的形式，或者單從發出預言這個行動本身去推論預言內容的真確性，肯定是一種錯誤。舊約提供的一個可以恒久應用的聖經準則，就是一如所有假定的預言的教義內容必須受考驗（參申一三 l—3），預言的真確與否，就必須看他們是否應驗（申一八 22）。這些預言應對人的行為產生的唯一影響，就是驅使人作好心理準備，以迎接預言的應驗，同時也準備好面對預言的不應驗。可是，行動的準則，必須是神啟示的話語和靠這話語管理生命的智慧（參申二九 29；箴一至九章）；我們不要隨便相信自封為先知的人那些很可能誤導人的預言。（寫到這裏，不禁令我聯想起在我身上發生的一件事。一九七九年，當時有一位相當誠懇的靈恩派先知規勸我，他說神並不是像我心裏認定的要引導我到溫哥華寫作，而是要我在城市教會內帶領基督徒渡過一段大分裂的時期。嗨，似乎今天的教會一如一九七九年的模樣，而我呢？此刻正坐在這裏寫這本書。）

　　我們不應以為預言是久已作古的第一世紀恩賜，今天復蘇過來，因而在語言表達形式上以盛裝出場，使他與十八、十九世紀以還所有其他基督教溝通的形式分別出來；肯定說，恰當的結論反而是我們應該明白到其實自有教會以來，預言一直不斷展現在每一篇發人深省，並切合聽眾需要的講章或非正式的「訊息」內。不論何時何地，只要聖經真理被真誠地傳講出來——意思是，真理被講解、詮釋和應用，不論是在講壇上或是非正式的分享——，就已經是預言了。傳講訊息就是教導神的真理，並加以應用，這種具備應用實踐的教導就是預言，以前如此，將來也是如此。今天在靈恩派信徒中間宣講的預言，並不比任何時間其他任何團體所宣講的更加優勝，過去、現在、將來也是如此。有些人在宣講之前沒有默想，採用第一身單數表達，其文法猶如是神自己直接宣告，把聖經真理應用在各種處境和不同的人身上，又為發生了的事情歡喜慶賀，同時瞻望未來要發生的一切。無可置疑，神也曾在這個時代，藉著這一切祝福那講的和那聽的人。然而，為此以為這種表現本質上與基督徒一貫為人所熟悉的（正式與非正式的）鼓勵和勸誡截然不同，從而把他認定為新約表記恩賜在今天的復蘇，這樣的想法是不正確的。

[[Keep_in_Step_With_the_Spirit__notes.org#預言的恩賜][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 對複還論神學思想的裁決
　　上述提到的七條問題，其中最重要的字眼是令人信服。對於上述問題的種種肯定和否定論說，都曾經有人提出過，這不是現在我們要談論的。我想指出的是這種種論據到目前為止還未有足夠的說服力使他們貫串有力，而且似乎亦永不會變為可信服的了。誠然，靈恩派信徒（也包括其他非靈恩派的信徒）所經歷神的眷佑和神工作的彰顯，在某些方面來說，相當於使徒的神跡、醫治、說方言，以及（頗成疑問的）翻方言；在使徒時代，這些恩賜印證使徒能力的來源，表彰他們所傳揚的基督（參林後一二 12；羅一五15—19；來二 3、4；和使徒行傳的記述）。誠然，在整個靈恩派圈內圈外，在整個教會歷史以還，確有「第二次祝福」和聖靈的膏抹臨到信徒，而這些恩賜在某些方面來說，確與五旬節經驗相似。34 可是，我們不能憑以上任何證據，而叫人信服地總結說，新約原初的靈恩經驗，消失了一段長時間之後，已經原原本本的再次賜給教會了。

　　我們無需否認，自從第一世紀末期，在不同的教會傳統中，一些基督徒屬靈方面的進深經驗，可能在感覺上很像使徒們五旬節的經驗；我們所需要注意的，反而是新約神學禁止我們用五旬節的經驗去解釋信徒這些經驗，或者將任何悔改以外的經驗，解釋為領受那正充分發揮其新約職事的基督的靈。我們亦無需對以下可能根本沒有答案的問題表達意見，就是到底神在使徒職事完結之後，撤回所謂表記恩賜，是否代表他在任何情況底下都不會把這恩賜恢復呢？我們只需要觀察，儘管與一些靈恩派信徒所宣稱的相反，事實上到如今這些恩賜還未曾真正恢復過。一言以蔽之，很明顯以複還論作為解釋靈恩經驗的神學理論是行不通的，倘若我們想明辨神在這個運動之中有何作為，我們必需循其他方向去思想。

　　這裏，我還想加多一個短評。要評價靈恩派現象，我們需要記得的，就是團體信念塑造團體期望，團體期望塑造個人經驗。一個具備導師和著作文獻的團體，很容易模造其成員的思想和經驗，而且模造的程度可以是十分驚人的。具體來說，例如團體相信，標準的信徒經驗應該以使徒行傳第二章使徒的經驗為典範，對神自己、他在基督裏的愛和他賜予的能力（聖靈的膏抹）有一種更深的體會，並得著說方言的能力，那麼，團體的成員肯定會追尋且「尋獲」這種經驗。這經驗也不會單單由於某些錯誤的觀念黏附其上，而必然地成為一種誤導的、沒有聖靈在其中的、自我衍生的經驗。正如我們一直所體會的，神是滿有恩慈的，他祝福那尋求他的人，即使他們的觀念未必完全正確。可是，我們必須以這種經驗為一種受期望塑造的經驗來試驗他，而那塑造經驗的期望亦要分開來接受考驗，去看他們是否合乎神所啟示的真理。故此，同理，若然人們期望從神而來的訊息應以某個特定風格傳遞，那麼，不論正典式預言復蘇這個意念是否有聖經根據，這種傳遞方式肯定會應運而生；然後，在每一次個別的情況，我們都需要試驗訊息的內容，這種試驗與就塑造傳遞過程的期望而作的評斷是很不相同的，兩者不能混為一談。

　　讓我重申：我從沒有表示過這些受期望塑造的經驗是沒有屬靈實質的。我唯一希望指出的，是複還論者的宣稱（他們期望的基礎）是經不起考驗的，我們需要另一套神學理論去闡述聖靈的工作。我想，這一點我已經很清楚詳盡地證實了，因此，我會繼續寫下去。

[[Keep_in_Step_With_the_Spirit__notes.org#對複還論神學思想的裁決][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 另一套神學理論

[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

*** 說方言
　　那麼，我們對說方言有什麼看法呢？我們看見現今說方言的人，他們能夠保留那種情緒，思想卻休假去了，因此我們不能根據任何觀點，信心十足地認定他們的表現等同於新約時代的方言。在這種理解底下，人們經常極力主張的，就是既然神的目標是要人在完全自覺、理性的控制能力下，達致人格完全的統合，那麼，成聖過程的整體楷模，必然包括平穩地恢復這種控制能力。當我們更深地表現出聖經所說的誠懇、純一、專心一志等質素時，我們就更能控制自己，同時在我所行的一切事上，我心中「只有一件事……」（腓三 13；另參林後—一 3；雅一 7、8）既然是這樣（按照推論是如此），我們就再沒有說方言的必要，因為說方言的時候，人放棄了對聲帶理性的控制。然而，一個雙重的回答可能合適。

　　首先，既然靈恩派信徒故意選擇說方言作為一種傳達工具，去表達他們心中就某些主題要向神獻上的崇敬和祈求，藉此向神多說一些他無法用語言表達的心事，若然我們聲稱他們完全缺乏理性的控制，是不很真確的。

　　其次，聖靈可能要透過這種表面上理性控制的鬆懈，去強化信徒更深層面的自製能力；這種見解並非不可思議。心煩意亂的人，浸在浴缸裏，大聲哼無字句內容的歌，有助恢復健全的理性；說方言可能在屬靈方面就有著相同的意義。倘真如此的話，那麼說方言的確是神的奇妙恩賜。並且，若然說方言的效果真的為要加劇讚美及禱告的情緒，並使這些情緒持續，以免因思想的魂遊象外而無法維持，那麼，說方言可以幫助培養正面的性格，引領人進入密契禱告（ mystical prayer）宣導者所稱的默觀（contemplation）裏。這種操練對於某一類人可能尤其有益，由於現代生活匆忙、浮面、脆弱而不真實，許多人成為這種生活的受害者，無法在更深層面與他們的自我接觸，於是，他們的基督教變成形式化、概念性、隨俗、定型、抄襲和二手的信仰。（畢竟，靈恩運動主要是一種都市現象，而在城市裏面，這些壓力對人有最直接的影響。）

　　這樣看來，起碼對某些人來說，說方言可以是神的美善恩賜；這是基於一個觀念，就是任何能夠幫助人專注神、體驗他的同在，並使人敞開心靈讓神影響的東西，都是美善的恩賜。（可是，對其他擁有不同問題的人來說，神已經幫助他們自心裏向神發出通達的禱告，說方言對他們來說，遂變為不屬靈、瑣碎和不著邊際了；現時有些人對於不論何處出現的方言都持這種看法。這就是正所謂一人的佳餚可能是另一人的毒藥了。）

[[Keep_in_Step_With_the_Spirit__notes.org#說方言][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

