#+TITLE:《活在聖靈中 Keep in Step with the Spirit》巴刻(J．I．Packer)著/霍玉蓮譯
#+AUTHOR:巴刻J．I．Packer著/霍玉蓮譯

* 目錄
 - [[#1_看清楚聖靈][1_看清楚聖靈]]
   - [[#蒙眼症][蒙眼症]]
   - [[#認識並經歷神][認識並經歷神]]
   - [[#聖靈的能力][聖靈的能力]]
     - [[#基督徒的能力][基督徒的能力]]
     - [[#能力的限制][能力的限制]]
   - [[#表現_屬靈恩賜的運用][表現_屬靈恩賜的運用]]
     - [[#總動員事奉][總動員事奉]]
     - [[#正確地看表現][正確地看表現]]
   - [[#保守我們純潔][保守我們純潔]]
     - [[#道德掙紮教義的陷阱][道德掙紮教義的陷阱]]
   - [[#叫我們醒覺][叫我們醒覺]]
     - [[#泰萊觀點的毛病][泰萊觀點的毛病]]
   - [[#追溯我們的思路][追溯我們的思路]]
   - [[#基督的臨在][基督的臨在]]
     - [[#對神的覺醒][對神的覺醒]]
   - [[#綱要][綱要]]
   - [[#注文][注文]]
 - [[#2_聖經裏的聖靈][2_聖經裏的聖靈]]
   - [[#神的靈][神的靈]]
   - [[#聖靈的位格][聖靈的位格]]
     - [[#聖靈是保惠師][聖靈是保惠師]]
     - [[#聖靈是神][聖靈是神]]
   - [[#聖靈與基督][聖靈與基督]]
     - [[#應許賜下聖靈][應許賜下聖靈]]
     - [[#聖靈與基督的同在][聖靈與基督的同在]]
     - [[#聖靈的教導][聖靈的教導]]
     - [[#聖靈的見證][聖靈的見證]]
     - [[#聖靈照明基督][聖靈照明基督]]
   - [[#聖靈與基督徒][聖靈與基督徒]]
     - [[#新生][新生]]
     - [[#認識神及愛神][認識神及愛神]]
   - [[#恩膏_見證_憑據][恩膏、見證、憑據]]
   - [[#內心之旅][內心之旅]]
   - [[#屬靈恩賜][屬靈恩賜]]
     - [[#什麼是屬靈恩賜][什麼是屬靈恩賜]]
     - [[#屬靈恩賜的運用][屬靈恩賜的運用]]
     - [[#恩賜帶來的祝福][恩賜帶來的祝福]]
   - [[#五旬節的意義][五旬節的意義]]
     - [[#惹起爭論的經文_約翰福音二十章二十二節][惹起爭論的經文：約翰福音二十章二十二節]]
     - [[#五旬節的實質][五旬節的實質]]
     - [[#聖靈的洗和聖靈充滿][聖靈的洗和聖靈充滿]]
   - [[#聖靈與我們][聖靈與我們]]
 - [[#3_聖靈的路徑_聖潔之道][3_聖靈的路徑：聖潔之道]]
   - [[#基督徒的優先選擇][基督徒的優先選擇]]
   - [[#應優先考慮的事][應優先考慮的事]]
     - [[#自我中心的虔敬觀念][自我中心的虔敬觀念]]
     - [[#活躍的危機][活躍的危機]]
     - [[#忽略聖潔][忽略聖潔]]
     - [[#聖潔與世俗][聖潔與世俗]]
   - [[#基本聖經原則][基本聖經原則]]
     - [[#1_聖潔的本質就是透過分別為聖達到更新][1_聖潔的本質就是透過分別為聖達到更新]]
     - [[#2_聖潔是藉著耶穌基督稱義][2_聖潔是藉著耶穌基督稱義]]
     - [[#3_聖潔的根源是與耶穌基督同釘死同復活][3_聖潔的根源是與耶穌基督同釘死同復活]]
     - [[#4_聖潔藉聖靈而成][4_聖潔藉聖靈而成]]
     - [[#5_聖潔的經驗是矛盾的][5_聖潔的經驗是矛盾的]]
     - [[#6_聖潔的法則就是神所啟示的律法][6_聖潔的法則就是神所啟示的律法]]
     - [[#7_聖靈的中心是愛的精神][7_聖靈的中心是愛的精神]]
   - [[#重建工程][重建工程]]
   - [[#活在聖靈中][活在聖靈中]]
 - [[#6_聖靈的路徑_解釋聖靈生活][6_聖靈的路徑：解釋聖靈生活]]
   - [[#翻方言][翻方言]]
   - [[#醫治的恩賜][醫治的恩賜]]
   - [[#預言的恩賜][預言的恩賜]]
   - [[#對複還論神學思想的裁決][對複還論神學思想的裁決]]
   - [[#另一套神學理論][另一套神學理論]]
     - [[#說方言][說方言]]
   - [[#結論][結論]]
     - [[#4_說方言][4_說方言]]

* 1_看清楚聖靈
** 蒙眼症
　　市面上不是已經有許多關於聖靈的著作嗎？為什麼還要多添一本？這個問題問得正好，現在我要回答這個問題，就先從我的近視說起吧！

　　如果我除下眼鏡來看你，你在我眼中便蒙朧不清，我應該仍然知道你的存在，我大約仍可分辨你是男是女，我也許不至糊塗得把你撞個滿懷。但在我眼中，你的線條不是清晰可辨，你的容貌變得模糊不清（除了靠記憶外），我絕對無法清楚形容你。假使在我除下眼鏡時，一個陌生人走進我的房間，無疑我可以指出他來，但他的臉孔將會是模糊的一團，我無法知道他臉上的表情。我若不戴回眼鏡，你和他都會輪廓不明。

　　加爾文有一個很特別的比喻，他說像我這類眼濛濛的人，需要配戴眼鏡，去將物象對焦，同樣，我們所有人都需要聖經的裝備，幫助我們體會神的實在。雖然加爾文是一般性地運用這個比喻，但我相信在他腦海中，他必會想到以一些特殊真理作為鏡片，來獲致清晰的焦點。加爾文認為每個人都會對真實的神有概略的認識，但這些認識多半是含混模糊的。看清楚神是指對他的性格、他的主權、他的救贖、他的慈愛、他的兒子、他的聖靈和他的作為有正確的認識，亦即是對我們與他的關係有正確的瞭解——我們些受造物，究竟是活在罪中或恩典裏？在信、望、愛的生命中與他相交，或在枯竭、幽暗的心靈中與他隔絕？我們怎樣才能夠對這些事情有正確的認識呢？加爾文的答案是（我的也是一樣）：從聖經中學習。惟有從聖經中學習，我們才能夠清楚認識神，而他在我們腦海中的形象，也就不再模糊不清；我們可以聲稱他是三位一體的創造主，是聖父、聖子和聖靈。

　　好了，我現在要清楚指出我寫這些篇章的目的。正如我已經說過，今天聖靈大受注目，眾人所關注的，是他的身分，以及他在個人、教會及社群中做些什麼工作。團契、肢體生活。總動員事奉、聖靈的洗、恩賜、神的引導、預言、神跡，以及聖靈的啟示、更新和復興工作等題目，都常常掛在許多人的嘴邊，也在許多書本中討論過。這誠然是好的，我們應該為此感到快樂；反之，若然我們沒有討論這些題目，可能反映出我們在屬靈方面出了問題。然而正如近視漢看不清眼前的景物一樣，又好比任何人都會在一些事情上捉錯用神，對事物的真相只知其一，不知其二，因此，我們雖然經常頌揚聖靈的工作，但往往未能按聖經認識聖靈。對屬靈的事物，我們真個是濛濛眼，大受自己的偏見左右，以致我們沒法看得清楚。

[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 認識並經歷神
　　我們很容易作出如此的假定：既然我們認識聖靈在我們生命中的一些作為，我們就已經完全認識聖靈。很抱歉，結論並不是這樣。事實上，正如一個人的概念知識可以遠超過他的屬靈經驗，同樣，屬靈經驗也可以走在概念知識的前頭。相信聖經的人經常強調需要有正確的概念知識，以致他們忽略了上述的情形。但事實確是如此，耶穌門徒的經驗就是很好的例子。耶穌在世上的時候，門徒追隨他，但他們對屬靈事物的理解常有錯漏，而且經常對耶穌有許多誤解；可是，耶穌能夠超越他們思想上的限制，感動他們、改變他們的生命，純粹是由於他們愛他、信靠他，希望從他身上學習，誠心願意追隨他們心中的亮光去服從他。因此，十二個門徒中有十一個「已經乾淨了」（意思是他們的罪得赦免，心靈獲得更新「約一五 3」），並且得與其他人一起進入耶穌恕宥和平安的恩典中（參路五 20 一 24，七 47—50，一九 5 一 10），而那時他們尚未能掌握耶穌釘十架的贖罪意義。神首先賜下救恩的禮物，改變他們的生命，其後他們才明白這是什麼一回事。

　　同時，當這些人對神充滿信心，並願意敞開心靈去明自神的旨意時，他們便追求更完全活在聖靈裏的生命。（這是極其自然的！難道我們不曉得追求從聖靈而來的生命和追求從耶穌而來的生命，事實上是同一回事，只是名目不同而已？）我在這裏提出的，就是要著意尋求聖經教導我們去尋求的東西。既然神是言而有信的，我們便有把握期望我們所求的必然得著——我們更會發現臨到我們身上的美好恩賜，常是超過我們所想求的。主耶穌說：「你們祈求，就給你們；……你們……尚且知道拿好東西給兒女況天父，豈不更將聖靈給求他的人嗎？」（路—— 9、13）許多曾這樣祈求的人，都被神豐足的回應嚇了一跳。

　　神是滿有恩慈的，只要我們以真誠的態度，全心全意尋求他的臉，希望與他親近，即使我們對何謂屬靈生命沒有認識，或只有錯誤的觀念，他都可以使我們靈裏的生命進深。在這要應用得著的公式是耶利米書二十九章十三、十四節的應許：「你們尋求我，若專心尋求我，就必尋見。……。然後，我們的責任就是要透過聖經的亮光，瞭解主實際上為我們做了什麼，並且瞭解他在我們個人經歷中的特別工作如何與聖經所說他透過聖靈為屬他的人作事的宣稱相關。因著主的慈愛，他在我們經歷中的作為都是匠心獨運地符合各人性格和環境上的需要。在我看來，這項工作是許多神的子民的當前急務。

　　請勿誤會我！我並不是說神賜福於那些無知和錯謬的人，是由於他們的無知和錯謬；我也不是說神不在意我們是否認識和掌握他所啟示的旨意；更不是說一個人只要對神有誠懇的心和真摯的情感，就不怕無知和錯謬會損害他靈命的健康。我們可以肯定地說，神賜給信徒的福氣，是絕對而不變地按著他的真理賜下的；錯誤的信仰意味著屬靈的貧乏，對靈性更會造成嚴重損害。可是，任何接觸人心靈的人，總是一次又一次地因神奇妙的作為而大感驚訝，因為神豐豐富富地賜福給靈性貧乏的人，使這些有大堆錯謬思想，只認識一點點真理的人，大大改變過來。正如我曾經說過，無數罪人在他們對耶穌和聖靈尚未有正確的認識時，就已經真實地經歷耶穌基督的救恩和聖靈使生命更新的能力。（說句實話，若然神要等待我們有完全正確的屬靈觀念，才賜下福氣，那麼，我們現在真不知處於何等光景了！幾乎每個基督徒都曾經歷神豐厚的恩惠和幫助，而神的賜予，總遠遠超過他們的思想所配得的。）儘管如此，我們若對聖靈有較清晰的觀念，就更能欣賞聖靈的工作，以及避免墮入一些錯謬的陷阱。這正是本書嘗試提供的幫助。

　　我的思潮又回到二十年前一個潮濕的下午，那時我正趕著去一間渾名為「蚤子窩」的橫街電影院，以先睹為快的心情去觀看一出剛到埠的著名默片「大將軍」（“TheGeneral”）。這出電影於一九二七年攝製，今日的影評人盛讚他是基頓（BusterKeaton）的代表作。當時我剛剛發現這樣一個憂鬱、品格高尚、容易遇上不幸、優柔寡斷、足智多謀的諧角基頓，因此「大將軍」深深地吸引著我。該故事發生於美國內戰時期，於是我順理成章地猜想這出電影必然像基頓其他一些電影一樣，片名已說明他的角色了。我並不是戰爭片迷，記得在步向電影院途中，我還在揣測這出電影會如何吸引我。

　　沒錯，在「大將軍」一片中，基頓最後真正穿上了制服——準確一點說，是穿上陸軍中尉的制服——可是，若因此稱基頓為一位肩負領導責任的將軍，那真是極之誤導，而且有點不盡不實，因為基頓只是在最後的幾分鐘才得到他的制服，而在這片段之前的整整七十分鐘裏，展現眼前的不是模仿軍中生活的諷刺劇，而是一個古老蒸氣火車頭的故事。那是一部名貴、笨重、設有排障器的 4—4—0 型火車頭。故事安排火車頭被人取了，促使那不怕死活的司機驟然成為機智的英雄人物，展開一夫當關的神勇拯救行動，從而引發出不少瘋狂笑料。後來他拯救成功，所得的報酬就是獲得他渴慕已久的軍官身分；在此之前，他因為不能當上軍官，女朋友不願理睬他。原來「大將軍」就是那部火車頭的名稱。故事改編自一八六三年的大火車頭追逐事件，當時，真正的「大將軍」（火車頭）在喬治亞州瑪利安達被北方破壞者搶奪，在火車快要駛進北方疆域之際，剛好燃料用盡，終於成功地被追蹤奪回。對於我這個鬧劇迷兼火車在來說，當時是完完全全被迷住了。

　　我想指出的，就是今天很多人殷殷暢論聖靈的工作及活在聖靈中的真實經歷，但其中一些觀念比對於事實真相，就差不多像我對「大將軍」一名先入為主的臆測一樣。請跟我察看一些有關觀念，讓我表明我說的到底是什麼意思吧！

[[Keep_in_Step_With_the_Spirit__notes.org#認識並經歷神][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 聖靈的能力
　　首先，許多人認為聖靈的教義基本上與能力有關，意思是神賜予能力，讓你可以做你應該做卻感有心無力的事情，例如：拒絕物欲的追求（諸如美色、煙、酒、毒品、金錢、刺激、奢華的生活、晉升機會、權力、名望、諂媚奉承等等）。容忍那考驗你耐性的人、愛那不可愛的人、控制脾氣、在壓力中站立得穩、為基督勇敢發言、在遭逢患難中仍信靠神。聖靈賦予人能力達致上述的種種表現，無論在思想上、言語上、講章及禱告裏，這主題都為人所津津樂道。

　　然則我們對這些人所強調的有什麼異議嗎？他們的觀點是否錯誤？不是，絕對不是；情形剛好相反，這觀念本身是堂而皇之的正確。因為能力（power）一詞（通常相當於希臘文的 dunamis，由此引伸為英文的 dynamite，有時相當於 kratos 和 ischus）是一個重要的新約辭彙，而基督藉聖靈賦予信徒能力，確是新約中重大的事實，是福音裏的榮耀，也是世界各地忠實追隨基督的人的標記。如果你對我這番話產生疑問，你大可細讀以下
經文：

　　耶穌曾把大使命託付門徒，叫他們將福音傳遍天下，並對他們說：「你們要在城裏等候，直到你們領受從上頭來的能力。」「但聖靈降臨在你們身上，你們就必得著能力 ……」（路二四 49；徒一 8）在五旬節，聖靈被澆灌下來時，「使徒大有能力，見證耶穌復活……」（徒四 33）同時，「司提反滿得恩惠、能力，在民間行了大奇事和神跡。」（徒六 8；另參閱彼得形容耶穌的相類似經文：「神怎樣以聖靈和能力膏拿撒勒人耶穌……」「徒一○38」）路加在這些經文裏告訴我們，從起初，福音就是靠著聖靈的能力傳揚開去。

　　保羅為羅馬教會的人祈禱說：「……使你們藉著聖靈的能力，大有盼望。」（羅五 13）然後，他繼續談及基督透過他作的事情：「基督藉我作的那些事，……他藉語作為，用神跡奇事的能力，並聖靈的能力……」（羅一五 18、19）；他又提醒哥林教會的信徒，他傳講基督釘十字架，「……乃是用聖靈和大能的明證；叫你們的信……只在乎神的大能。」（林前二 4、5；另參閱林後六 6—10，一○4— 6；帖前一 5，13）當保羅感到有一根剌加在他肉體上時，他寫道：基督「對我說：『我的恩典夠你用的，因為我的能力是在人的軟弱上顯得完全。』所以，我更喜歡誇自己的軟弱，好叫基督的能力覆庇我。」（林後一二 9，另參閱四 7）他又對提摩太說，神賜給基督徒的「是剛強（power）、仁愛、謹守的心」，並指責那些「愛宴樂，不愛神，有敬虔的外貌，卻背了敬虔的實意（ power）」的人（提後一 7，三 4、5）。他說基督給予信徒能力（endunamoo，dunamoo，krataioo），使信徒能達成本來單憑己力是永遠無法辦到的事情（弗三 16，六 10，另參一 19 一 23；西一 11；提前一 12；提後四 17；另參林後一二10；彼前五 10）。並且，當他處身獄中，性命危在旦夕之時，卻發出勝利的呼喊：「我靠著那加給我力量的，凡事（意指神呼召他去做的一切事）都能作。」（腓四 13）無庸置疑，這一切都說明瞭聖靈是帶來能力的。我們受教導知道靠著超自然的能力去過超自然的生活，是整個新約基督教信仰的核心，故此，那些自稱信奉基督教的人，若不曾經歷能力的澆灌，也表現不出他們擁有這種能力，那麼照新約聖經的標準看來，他們的信仰是值得懷疑的。儘管人以基督為信徒得力的唯一源頭，能力的澆奠往往是聖靈的工作，而人只提基督，是因為基督賜下聖靈（約一 33，二 O22；徒二 33）。因此，能力是透過聖靈從基督而來；無論何時何地，誰人傳授基督教道理，都應該特別重視這個真理。

　　過去三百多年來，福音派信徒一直仰賴神的應許，不斷向神支取能力來生活。我們應該為此感到高興，因為這種能力的賜予不單是聖經裏的一個重要主題，他還針對人類一個明顯而普遍的需要。凡肯誠實面對自己的人，都不時會因自己內心一份強烈的不足感而不知所措。所有基督徒都會一次又一次窘迫地呼喊：「主啊，幫助我，堅固我，扶持我，賜我能力，好讓我所言所行都能取悅你，令我剛強壯膽，有充足的力量面對種種壓力和要求。」

　　我們是被召去戰勝那惡者，他常以種種形態出現在我們心裏，或圍繞我們。我們需要知道在這一場爭戰裏，只有靠著聖靈的能力，才能獲取勝利；反之，若完全靠賴自己，最後只會發現自己的無能和經驗挫敗，引致痛苦。所以，福音信仰強調藉著聖靈而達致成聖是一件真實而又必需的事，這個教導永遠都切合時宜。

[[Keep_in_Step_With_the_Spirit__notes.org#聖靈的能力][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

*** 基督徒的能力
　　十七世紀時期，清教徒首先強調聖靈如何在人的生命中彰顯能力；可是，到了十八世紀，這種教導竟變成了福音派信徒間爭辯的主題，當時衛斯理（ John Wesley）開始提出一種教義，說聖靈會把人的罪從人心靈中連根拔起。這就是衛斯理所指的「合乎聖經的聖潔」，他相信神興起循道主義（Methodism）去宣揚這個教導。非衛理公會信徒對這種教訓退避踟躕，覺得他很虛妄，而且不合乎聖經，所以他們不斷警告自己教會的會友要防備這種思想。然而到了十九世紀中葉，反對的鐘擺搖晃到了另一個極端；許多人感到（不論他們的想法是否正確）這股反完全主義的熱潮令基督徒完全遺忘了神有能力拯救人脫離罪，他能使人過一個平靜、得勝而公義的生活，他亦能夠使講員的資訊直透人心靈深處。忽然之間，人得勝的能力頓成為講章、書籍和非正式小組討論的話題（他們稱這些小組討論為「閒談聚會」），遍及大西洋兩岸。龐馬（Phoebe Palmer）、馬漢（Asa Mahan）、史密夫（ RobertPearsall Smith）、漢娜·韋杜（ Hannah Whitall Smith）、賀堅斯（ Evan Hopkins）、慕安德列（ Andrew Murray）。叨雷（R．A．Torrey）、特榮布林（ Charles G．Trumbull）。麥奇堅（ Robert C．McQuilkin）、梅亞（F．B．Meyer）、慕耳（H．C.G．Moule）等人所致力宣告的信徒得力「秘訣」（“secret”，這是他們採用的字眼），被高舉為新的啟示。事實上，宣告這些道理的前們也如此相信。一個嶄新的福音信仰運動已經展開了。

　　這個得力的「秘訣」，有時也稱為「高超生命」或「得勝生活」的秘訣，已經在英倫一年一度為期一周的凱錫克培靈會（Keswick Convention）中，全面制度化地推展了，一如爵士樂隊的主要節目安排一樣，一直以來這個培靈會的各個聚會都有固定編排，星期一的主題是罪惡，星期二的主題是那拯救我們脫離罪惡的基督，星期三是奉獻，星期四是在聖靈裏的生命，星期五是成聖者滿有能力的事奉（尤其是在宣教事工上）。及後，一份凱錫克期刊在一八七四年創刊，名為《基督徒得力之途》（The Christian Pathway of Power）。五年後，刊物名稱改為《信心的生命》（The Life of Faith)，但名稱的改換並不代表期刊的性質有任何更改，仍依據凱錫克培靈會的教導，以信心就是得力之途為主題。凱錫克塔靈會的影響是世界性的，「凱錫克信徒。勃興於全世界所有以英語為地方語言的角落。「凱錫克培靈會的教導已經被視為近期教會歷史中一股最有潛力的屬靈力量。」1「凱錫克型」的講員，專門在大會上宣講能力的資訊，他們已成為一群獨特的福音信仰牧者，與福音信仰學者、聖經教師和講論預言性主題的講員並駕齊驅。凱錫克資訊經過制度化，又獲得欣賞凱錫克精神（平穩、愉快、節制、吹毛求疵等特性都非常迎合中產階級人士的喜好）的人支持；所以，凱錫克培靈會中有關成聖和事奉能力的資訊自然縈繞人心。

　　這種講論能力的主題也不是近年唯一的發展。基督的能力不單能夠赦免我們的罪，而且藉著聖靈，可拯救我們脫離罪惡的奴役。有如第一世紀一樣，這個資訊已再次成為教會福音資訊的主要部分。對於城市化的西方人來說，他們面對的邪惡，是具破壞性的惡習；對於較落後的部落社群來說，他們面對的邪惡就是邪靈的勢力。至於較古老的福音資訊，由於他強調律法、罪惡、審判和基督代贖受死的榮耀，誠然可以補充今天福音資訊的缺欠。可是整體來說，古老的福音資訊很少論及能力；從這方面看來，他的確是有些遜色了。

　　既然神應允和賜予能力是千真萬確的事，那麼能力的主題如此受到重視，誠然是一件值得欣喜的事。事實上，強調能力的資訊不管透過什麼形式表達出來，今天已成為基督教福音信仰主流的標記，與世界性的靈恩運動並駕齊驅；這無疑是一個對未來充滿希望的徵兆。

[[Keep_in_Step_With_the_Spirit__notes.org#基督徒的能力][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

*** 能力的限制
　　然而，在慶倖今天有許多關乎能力的講論之餘，我們也不無憂慮；因為經驗告訴我們，當我們思想聖靈時，若只集中注意能力這個主題，而沒有一個更具深度的觀點，沒有從另一個中心主題去看聖靈的職事，那麼，扭曲的觀念很快就悄悄潛入我們的思想裏。什麼是扭曲了的觀念呢？好，讓我拿以下的例子來開始吧！當一個人經常尋求力量去駕馭生活上的大小事情時，他會虔誠地專注自己心靈的起伏，因而產生一種自我中心和內向的心態，以致對社群的福利和社會的需要漠不關心。當人論及聖靈的工作時，往往傾向於以人為中心，就好像神的能力是一些隨時儲備妥當的東西，只要運用思想和意志——通常美其名為奉獻和信心——就可以開關「使用」（這是凱錫克培靈會的常用語）同時，這種態度形成一種觀念，認為只要我們肯釋放自己內在的能力，神的能力就會在我們心裏自動地運行，因此，我們可以隨時按著自己奉獻和信心的程度來調節這種能力。另一個隨之浮現的觀念，就是以為必須處於內在的被動狀態中，完全等候神的能力帶領我們（「放下自己，讓神工作」是流行得太響的口號）。同樣，在某些圈子的佈道工作裏，差不多形成了一種慣例，就是為心靈空虛的人提供一種「生活的力量」。表面上，就好像只要人肯委身基督，他立刻可以獲得發動和操縱能源的權利。

　　可是，這一切聽起來似乎較像瑜珈，甚於以聖經真理為基礎的基督教信仰。首先，這些觀念混淆了憑己意去擺佈神的能力（這是法術，西門的表現就是一個例子「徒八 18-24）和因著順服神的旨意而經歷神的能力（這是宗教，保羅的表現就是很好的例子「林後一二 9、10」）。再者，這些觀念是不切實際的。佈道家們的講章經常暗示一件事實，就是我們一旦成為基督徒，神在我們裏面的能力就可以立時除去我們性格上的任何弱點，令我們生活一帆風順；可是，這種說法是違背聖經，甚至是不誠實的。當然，神有時候可以施行奇跡，令悔改的人忽然改變過來，從這些或那些弱點中得釋放，即如其他時候，他亦會偶然施行神跡奇事一樣；然而，每個基督徒的生命都是一場持久戰，要不斷對抗來自世界、肉體和魔鬼的種種試誘和壓力；同時，那追求活像基督（即是智慧、忠心、愛心和公義的生活）的爭戰是嚴苛的，是永不停息的。在佈道中宣揚相反的現實，就無寧是一種騙取信心的技倆。同樣，凱錫克培靈會中的講論，經常鼓勵我們一時間對自己有過高及過低的期望——每時每刻完全脫離罪的纏累，是期望過高；另一方面，沒有動機去期望能夠逐步擺脫罪對我們心靈的轄制，就是期望過低。這是一種拙劣的神學，而且在心理和精神上都不符現實。我這些意見若早在一九五五年發表，一定會犯眾怒了，但在今天，我相信這些見解會較普遍受到接納。

　　討論下去，你就會漸漸明白我們真正的問題是需要對聖靈的教義有深刻而真確的洞見——這洞見的亮光能促使我們糾正對內在能力的謬說。不過，我打算暫且擱下這部分的論據，待我完成對聖靈問題的初步探討後才再談他。在目前的探討裏，我們只要記著一點，就是只談聖靈能力，根本不能針對問題的核心。

[[Keep_in_Step_With_the_Spirit__notes.org#能力的限制][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 表現_屬靈恩賜的運用
　　其次，許多人認為聖靈的教義基本上與表現有關，意思是運用屬靈恩賜。對這些人來說，聖靈的職事似乎由始至終只是關乎如何運用恩賜——講道、教導、說預言、說方言、醫治等等。他們認為根據新約聖經的教導，恩賜（charismata）是神所賜予的某些能力，尤其是藉著言語、行為和態度，把關乎耶穌基督的真理傳遞開去，彼此激勵，互相服事。他們又認為「……聖靈顯在各人身上……」（林前一二 7），恩賜是藉著行以辨認的，基督徒所表現出來的行為，正顯明瞭神賜予他們什麼能力。因此，他們認為屬靈生命的實質在乎表現，同時假設人愈能表現恩賜，就表示他愈被聖靈充滿。

[[Keep_in_Step_With_the_Spirit__notes.org#表現_屬靈恩賜的運用][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

*** 總動員事奉
　　對於這種觀點——或更貼切地稱為心態，我首先要說明一點，就是他所強調的教本身同樣是絕對正確的；這次是強調恩賜的實在，以及運用恩賜的重要。曆世以來，教會以為事奉的恩賜只屬於一小部分基督徒專有（例如好的牧師和其他少數人），因此，他們並不十分注意恩賜這個題目。二十世紀以前，有關屬靈恩賜的全面研究，只有一本英文著作，由清教徒歐文（John Owen）於一六七九至一六八 O 年寫成。近期所強調屬靈恩賜的普遍性，以及神對教會總動員事奉的期望，其實早就應該提出，因為新約聖經對這兩方面的教導是相當清楚和明顯的。這裏引述一些主要經文。

　　「恩賜『charisznata』原有分別，聖靈卻是一位。職事『diakonia』也有分別，主卻是一位。功用『energemata』也有分別，神卻是一位，在眾人裏面運行一切的事。」（林前一二 4 一 6）「我們各人蒙恩，都是照基督所量給各人的恩賜……凡事長進，于元首基督；全身……照著各體的功用彼此相助，便叫身體漸漸增長，在愛中建立自己。」（弗四 7、15、16）「各人要照所得的恩賜彼此服事，作神百般恩賜的好管家。」（彼前四 10）「正如我們一個身子上有好些肢體，肢體也不都是一樣的用處。我們這許多人，在基督裏成為一身，互相聯絡作肢體，也是如此。按我們所得的恩賜，各有不同。……」（羅一二 4—6）並非只有聖品人員及有職分的才具有恩賜，所有基督徒 都具有恩賜，牧者必須認識這個事實，並運用自己的恩賜去裝備平信徒運用他們的恩賜。「他所賜的，有使徒，有先知，有傳福音的，有牧師和教師；為要成全聖徒，各盡其識，建立基督的身體」（弗四 11、12）。

　　英文聖經的敘定譯本（King James Version）掩蓋了保羅在此處的含義，把他翻譯為基督所賜的有使徒、先知、傳福音的、牧師和教師，「為了成全聖徒，為要各盡其職，為要建立基督的身體」（“for　the　perfecting　of　the　saints，for thework of ministry， for the edifying of the Body of Christ”［King James Version］）。乍看來，這三句平衡的句語好像都是聖品人員蒙召的職責。第六世紀的聖經版本遺漏了第七條誡命中的不字（出二○14），在歷史中流傳下來，被稱為邪惡的聖經版本；這裏英文聖經欽定譯本在「聖徒」（“saints”）之後加上了一個逗點，也同樣產生不良的效果。因為這個逗號將「職事」的範圍局限了，成為只有在位的領袖才可擔當，這不但隱藏了保羅的意思，簡直將保羅的意思顛倒過來，使本來是肢體各盡其職的成為教權主義（clericalism）。（這裏的「教權主義。是一種陰謀和專橫的結合，在其中，牧者宣稱所有屬靈職事都是他個人的責任，不是會眾的責任，而會眾亦同意這種想法。這個觀念在原則上很有問題，實踐起來更會導致聖靈的感動被銷滅。）

　　其實，自上個世紀中葉開始，普利茅斯弟兄會（ Plymouth Brethren）已宣告恩賜的普及性和肢體應各盡其職，但由於他們的宣告摻雜在一種反動性的爭論裏——當時的論，是針對一些在被指為背離真道的教會裏事奉、受薪並曾受訓練的聖品人員——，們的宣告沒有受到多大注意。可是，近年來普世教聯運動和靈恩運動都抓緊這方面的聖經真理，使之漸漸成為基督教的老生常談，因而產生了一些可喜的效果。其中一個效果，就是許多地區的教會紛紛願意在教會生活中實驗新的制度及新的禮儀形式，讓信徒有機會完全發揮他們的恩賜，令會眾整體受益；隨之興起的，是以一種認真的態度，去檢討傳統的崇拜程式和形式，以保障沒有任何恩賜受到窒礙，甚至銷滅聖靈的感動。這一切都是好現象。

[[Keep_in_Step_With_the_Spirit__notes.org#總動員事奉][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

*** 正確地看表現
　　很不幸，這可喜情況也有其負面：三大扭曲了的現象不時破壞我們認識聖靈的新取向。
　　第—，過分強調平信徒的職事，令一些平信徒低估和輕視牧師的特殊責任，忘記要尊重牧者的職分和領導。
　　第二，著重指出神慣於賜予聖徒一些與他們信主前的才能毫不相關的恩賜（這強調沒有錯，這的而且確是神的習慣）致使一些人受到蒙蔽，而看不見另一個事實，就是教會生活中最重要的恩賜（如講道、教導、領導、輔導、支持）通常是一些被聖化了的天然才能。
　　第三，有些人鼓勵基督徒在個人表現上有極度的自由，因此為了平衡這種極端，他們設立了各種極度專制的牧養監察形式，有時甚至比起中世紀教士運用權術控制基督徒良心的種種惡劣方式，有過之而無不及。

　　明顯地，上述發展都有毛病，但糾正這些毛病不等於要貶低他們背後的原則；這些毛病不過是一些不受歡迎的副產品。原則本身是正確的，若不能切實遵守這些原則，就不可能有高質素的教會生活。

　　話說回來，若我們單單專注恩賜的彰顯（例如以說方言為個人的五旬節經驗），以為這就是聖靈對個別信徒的主要職事，因而認為這就是我們應該集中關注的聖靈工作，那就大錯特錯了。只要讀讀哥林多前書，這個錯誤就顯而易見。哥林多教會的信徒因擁有知識而自高自大（八 1、2），他們為自己的恩賜自鳴得意，或者有些人會說，是雄心勃勃。他們藐視一些會友及外來講員，認為這些人的恩賜不及他們；每當他們在教會裏聚會，彼此之間就喜歡競爭和炫耀自己的恩賜。保羅為哥林多教會的信徒知識全備、滿有恩賜而感到十分高興（一 4—7）；但另一方面，保羅指出他們像嬰孩一樣不成熟，又屬乎肉體，行事為人自相矛盾，自招羞愧（三 l—4，五 1 一 13，六 1 一 8，—一 17  22）。他們重視恩賜和自由過於公義、愛心和事奉；保羅說這樣的價值觀是錯誤的。再沒有別的教會像哥林多教會一樣受到使徒這麼多的指責了。

　　哥林多信徒因著自己的知識和恩賜，以為自己是「屬靈的」（Pneumatikoi，一四37）；可是，保羅苦苦的向他們指出，真正屬靈的質素（假定聖靈已賜予我們悟性去瞭解福音，因為這是最基本的屬靈條件）是屬乎道德的。「豈不知你們的身子就是聖靈的殿嗎？這聖靈是從神而來，住在你們裏頭的；並且你們不是自己的人，因為你們是重價買來的。所以要在你們的身子上榮耀神。」（六 19、 20）那遠勝哥林多信徒一切最可誇表現的「更妙之道」，就是愛：「……恒久忍耐，又有恩慈……不嫉妒……不，不 張狂，不作害羞的事，不求自己的益處，不輕易發怒，不計算人的惡，不喜歡不義，只喜歡真理；凡事包容，凡事相信，凡事盼望，凡事忍耐。」（一三 4 一 7）保羅說，儘管你擁有世界上各樣最偉大的恩賜，然而沒有愛，你就算不得什麼（一三 1—3）——靈性上是死的。保羅懷疑哥林多教會的一些人事實上「算不得什麼」，因此，他寫信給他們說：「你們要醒悟為善，不要犯罪，因為有人不認識神。我說這話是要叫你們羞愧。」（一五 34；另參林後一三 5）

　　有一件事情是哥林多信徒需要瞭解的，也是今天我們一些信徒需要重新學習的，這就是清教徒歐文（ John Owen）所說的，有些人可以滿有恩賜卻完全沒有領受恩典，意思是一個人可以有很好的表現，使他人靈性得益，但他本人卻沒有因著真正認識神，經歷聖靈在他心內動工所帶來的內在更新。彰顯聖靈的恩賜表現，與聖靈所結的果子，即活像基督的品德（見加五 22、23）完全是兩回事；一個人可以在恩賜的表現上有驕人成績，卻欠缺像基督的美德。你可以有許多恩賜，但只有少許恩典；你甚至可以有真實的恩賜，但完全沒有真實的恩典；就如巴蘭、掃羅和猶大一樣。歐文寫道，這是由於：

　　屬靈恩賜只屬於頭腦上或理解上的，不管是普通恩賜或特殊恩賜，都不能在心靈裏占一席位。屬靈恩賜是頭腦上的，因為他們是觀念性和理論性，多於實際的。他們只是智慧而已。縱使有些恩賜，諸如行神跡和說方言，能夠在我們裏面找到住處，卻不過是一種特殊力量的「短暫運作」，曇花一現。神的亮光是所有其他恩賜的基礎，屬靈光照是恩賜的實質；所以使徒在希伯來書六章四節中表達出恩賜的次序［歐文將「來世權能」等同於屬靈恩賜」。意志、情感和良心都與這些恩賜無關，因此，這些恩賜無法改變心靈；固然，若憑著光照的功效，也許可以改革生命。雖然一般來說，神不會將恩賜賜予大奸大惡的罪犯，至於那些接受了恩賜的人，若果後來變得惡行昭彰，神多半不會繼續給他們賜下恩賜；然而，一些擁有恩賜的人可能生命從未真正更新，那就無法確保他們不會陷入嚴重的罪中。3

　　故此，沒有人可以用恩賜作為取悅神或得救的明證，屬靈恩賜並不等於這些。

　　在整本新約聖經裏，每逢提及神在人生命中的工作，著眼點往往是倫理道德，而不是靈恩方面的。那真正要緊的是活像基督（不是在恩賜上像基督，而是在愛心、謙卑、順服神的旨意、對別人的需要敏感等各方面像他）。這在保羅為信徒的禱告中表達得尤其清楚。他為哥羅西的信徒祈求，求神「照他榮耀的權能，［使信徒］得以在各樣的力上加力，好叫……。什麼？是透過豐盛有餘的恩賜，好叫他們在事奉上有輝煌的成就嗎？不是，而是好叫他們「凡事歡歡喜喜的忍耐寬容」（西一 11）。同時，他祈求腓立比信徒的愛心滿溢，「……在知識和各樣見識上，多而又多；使你們……。什麼？使你們在講道和爭辯中充滿說服力，或者有醫治的權柄，或者能說流利的方言嗎？不是，而是「作誠實無過的人，直到基督的日子；並靠著耶穌基督結滿了仁義的果子……」（腓 9—11；另參看弗三 14 一 19）。

　　以上這點不單切合那些終日埋首於發掘和使用屬靈恩賜的人，也適用於所有持以下態度的人：這些人也許受自己剛烈的性情所矇騙，總以他們參與基督教活動的多寡，以及推行活動的技巧和成敗來量度聖靈在他們身上的工作。

　　我的論點就是任何把屬靈恩賜（奔走和辦事的能力和意願）看為比屬靈果子（在個人生命中像基督的品格）更重要的心態，在屬靈上都是方向錯誤的，需要矯正。最佳的矯正良藥就是重新調校我們對聖靈工作的觀點，把基督徒的活動和表現看為服事神和榮耀神的途徑，並按這種價值去衡量他們，而不是憑我們的觀感，單單因為某些活動或表現充滿戲劇性、夠搶眼、足以吸引人、能讓人在教會中擔當重要職位，或者使我們對某人的期望提升，就看為寶貴。有關這方面的觀點，我將會在下文討論；目前，讓我們先弄清楚，強調恩賜和活動，跟強調經驗聖靈的能力一樣，都不能領我們進到聖靈真理的核心。讓我們繼續我們的檢討。

[[Keep_in_Step_With_the_Spirit__notes.org#正確地看表現][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 保守我們純潔

　　第三方面，有些人將聖靈的教義集中在「潔淨」（purifying）和「淨化」（purgation）之上，換句話說，就是神潔淨他的兒女，使他們脫離罪的污染和敗壞，幫助他們抵擋試探，行正義的事。對於這些人來說，聖靈在我們逐漸成聖的過程中，使我們趨向完全，幫助治死我們裏面的罪（羅八 14；另參看西三 5），並改變我們，叫我們「榮上加榮……」（林後三 18）。對他們來說，問題的核心並非經歷聖靈的能力，也在乎基督徒對外的表現，反而是我們內心的爭戰，在追求聖潔的過程中如何對抗罪惡，尋求聖靈的幫助，保守我們純潔，不受玷污。

　　這些人所強調的觀點，本身也是完全合乎聖經的。未曾重生的人，實際上如保羅所說，「……都在罪惡之下……」（羅三 9）；另一方面，罪仍然「住」在那些重生了的人裏面（羅七 20、23；另參看來一二 1；約壹一 8）。罪在本質上就是一種叛逆神的非理性能量——一種傲慢、任性的習慣，在道德及屬靈上形形色色的自我中心表現。無論罪以任何形式出現，都惹神憎厭（賽六一 8；耶四四 4；箴六 16 一 19），也使我們在神的眼裏成為不潔之民。所以，從聖經來看，罪不單需要被赦免，而且需要被潔淨。

　　同樣地，以賽亞盼望有一天「主以公義的靈和焚燒的靈，將錫安女子的汙穢洗去」（賽四 4；另參看要求人洗濯、自潔的經文：賽一 16；耶四 14）。以西結覆述神的話：「我必用清水灑在你們身上，你們就潔淨了。我要潔淨你們，使你們脫離一切的汙穢，棄掉一切的偶像。」（結三六 25）撒迦利亞預告：「那日，必給大衛家和耶路撒冷的居民，開一個泉源，洗除罪惡與汙穢。」（亞一三 1）瑪拉基發出警告說：神「如煉金之人的火，如漂布之人的鹺。他必坐下如煉淨銀子的，必潔淨利未人，熬煉他們像金銀一樣……」（瑪三 2、3；另參看賽一 25；亞一三 9）這些經文指出犯罪行為使我們在神面前成為汙穢；罪惡叫神討厭和反感，一如當我們發現本該是潔淨的地方變成汙穢時，我們自己也表示討厭和反感；但在神恩慈的聖潔裏，這一切都解決了，他不單赦免我們的罪，而且幫助我們不再犯罪。

　　在舊約聖經裏，所有潔淨的律例及潔淨的禮儀都指向這種神聖的潔淨工作。同樣，在新約聖經所有有關救贖的經文裏，都把救恩形容為被洗淨和被潔淨（約一三 10，一五3；徒二二 16；林前六 11；弗五 25—27；來九 13、14，一○22；約壹一 7—9），又指基督徒生命中最重要的事情，就是潔淨自己，除去一切使自己在神眼中看為汙穢的東西（林後七 1；弗五 3— 5；提後二 20—22；約壹三 3）。所以，基督徒的洗禮尤其反映些意義，洗禮事實上不折不扣地象徵了潔淨。

　　聖靈使基督徒醒覺到自己的罪汙，並為此感到羞慚，又激勵我們去「……潔淨自己除去身體、靈魂一切的汙穢，敬畏神，得以成聖。」（林後七 1）當我們突出聖靈這方面的工作時，正好顯明瞭聖經一個重點，而在我們這個頹廢的世代裏，一切道德標準不受重視，羞恥之心被視作等閒，這重點實在需要大大的強調。

　　同時，基督徒在現世對純潔生命的追求，意味著他們長遠下去一種自覺的矛盾和掙紮，並常會感到成績未達理想；這方面的著重也是相當正確的，「因為情欲和聖靈相爭，聖靈和情欲相爭，這兩個是彼此相敵，使你們不能作所願意作的。」（加五 17）

　　無論我們是否接受羅馬書七章十四至二十五節作為剖析基督徒經驗的一個橫切面，用以直接闡明上述要點（有些人贊成，有些人不贊成；我們稍後會再作討論），但毫無疑問，保羅在加拉太書正告訴我們基督徒生命裏的實際掙紮。他要我們知道，每個基督徒的生命裏，都存在著兩種敵對的欲望；這兩種力量在動機的層次上彼此為敵。有些欲望表現出人性墮落後一種悖逆神、自私自利的天性；有些欲望表現出由重生而來的超自然、榮耀神和愛神的動機。由於基督徒內心有這兩種敵對的催迫動力，當其中一股動力把他拉向前時，另一股動力便把他拉向後；因此，縱然他恒常的目標是完完全全地服事神，如一首聖詩所說，存著「忠誠專一的心」，他還是發覺他的心靈從未完全純潔無瑕，他所作的事，也並非絕對正確無誤。就這樣，他時時刻刻不能作他所願作的。他在生活中認識到他所作的一切其實可以並且應該做得更好：不單只在他被自己的驕傲、軟弱、愚昧出賣了時如此，他努力嘗試行善為義的時候也是如此。在每一次嘗試之後，在每一個行動之後，他往往看見他在動機上、在表現上，都有許多可以改善之處。他當其時感到已盡所能做到最好的事情，事後回顧都會發現並非做得最好。就這樣，他窮一生之力追求完美，卻又發現他所追求的永遠不能在他掌握之內。

　　當然，這不是說他永不會達到任何程度的義，保羅並非預料基督徒生命是經常完全失敗的，反而，他期望這是不斷的道德成長。「……當順著聖靈而行，就不放縱肉體的情欲了。」這是加拉太書五章十六節對信徒的直接要求，第十七節只不過是這要求的注腳而已。明顯地，保羅在這裏及其他經文教導有關基督徒品行時，他每每期望信徒努力向前，養成聖潔的習慣，積極操練自己，學像基督。

　　保羅說，基督徒既然從罪的奴役中釋放出來，他就可「按著心靈的新樣」（羅七6），實踐愛和公義；凡他現在能實踐的，他都必須去實踐，因為這聖潔的生活是神的旨意（加五 13、 14；羅六 17 至七 6；帖前四 1 一 8）。基督徒能夠且必須藉著聖靈治死他們的罪（羅八 13）；他也能夠且必須活在聖靈裏，走在屬神和善行的道路上（羅八 4；加五 16、25）。意思是說，一些他從前愛做的事，或一般未信主的人愛做的事，他如今放棄不作，而且，他開始選擇作另一些事情。現在，他要追隨自己心靈裏（即在他的意識裏）所感受到屬於聖靈的意願，而不陷溺在肉體的情欲中。基督徒生命必須是公義的生命，這正是他悔改和重生的自然流露，也是基本的要求。

　　談到保羅在第十七節所說的話，我只想發揮這唯一的重點：活在聖靈中的基督徒，會不斷發現他的生命尚未達致本來應有的美善；他經常要面對重重障礙和限制，以及自己扭曲的天性背道而馳的拉扯，他正在打一場前所未有的硬仗；同時，即使是他最好的行為，也不免犯上動機上的罪；他亦發現他每日的生活充滿汙點，他必須每時每刻仰賴神在基督裏的赦罪恩典，否則他就會在罪中失喪；同時，他也認識到自己心靈的軟弱和善變，需要經常求告聖靈賜給他力量，使他在這場內在的鬥爭中能堅持到底。「你確實不能實踐你心想望的那種聖潔生活。」對保羅來說，這句話明顯地道出了人追求聖潔的一些真相。誰可以說他是錯誤的呢？
　　
　　的確，自從革利免（Clement）和俄利根（Origen ）提出清除情欲、淨化靈魂的教導，早期教父記述他們如何頑抗醇酒美人、夜夜笙歌的幻想，以及奥古斯丁用自身的經歷去刻畫罪和恩典的本質以來，信徒不可避免地要與試探對抗的主題就成為基督教靈修教導中一個固定的著重累占。馬丁·路德和加爾文對這方面有很多闡釋，路德宗和加爾文派的信徒，尤其是加爾文派，都緊緊追隨他們的腳蹤。許多世紀以來，不少人曾一次又一次地對這個重點的真確性、現實性和健全性提出質疑與辯論，到如今，已經再沒有什麼見解能認真地挑戰上述重點了。藉著神的恩典，人的生命逐漸被洗滌和潔淨，因此，強調人生掙紮的真實性，是完全合乎聖經和十分恰當的。

[[Keep_in_Step_With_the_Spirit__notes.org#保守我們純潔][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

*** 道德掙紮教義的陷阱
　　即使這樣，經驗告訴我們，當信徒以道德掙紮作為他們思想聖靈的重點時，常會被許多陷阱圍繞。他們會漸漸變成律法主義者，常常為自己和別人定下嚴格的規例，好讓自己對不相干的事情毫不染指，又給自己和別人強加一些呆板並約束性的行為模式，作為抵抗屬世潮流的堡壘，並且大大強調遵守這些人為禁忌的重要。他們的行事為人愈來愈像法利賽人，注重提防那能污染人的事情，以及毫不妥協地堅守原則，多於注重實踐基督的愛；他們變得小題大造，對於沒有真正構成威脅的事物，他們亦毫無理由地懼怕受到污染，又頑固地不肯安心；他們變得沒有喜樂，因為盤據他們腦海的，儘是這場屬靈戰爭如何冷酷無情的思想；他們變成病態的人，終日內省，陷溺於懊悔自己心靈的腐朽，久而久之，滋長出灰暗冷漠的人生觀；他們對於道德成長的可能性感到悲觀，不單看自己如此，看別人也是如此；他們對於脫離罪惡，不敢存什麼厚望，最大的希望只不過是不會比以前更糟。這種種態度可說是屬靈的神經衰弱症，他們歪曲、損害並削弱聖靈使人成聖的工作，因此實際上使聖靈在我們生命中的工作蒙上汙點。

　　我明白這些心態通常是累積了種種因素構成的，諸如天生的性情、早年的教育和訓練，以及因害羞或缺乏安全感而形成的吹毛求疵習慣、低下的自我形象，甚至或者真正的自我憎厭，都往往是一些成因；此外，一些內向的教會文化和社群，都可以導致上述的情況。只不過，現在我想指出的，就是對聖靈認識不足，也經常是一個原因。一如我們剛才討論到的其他兩類人一樣，這類人需要從另一個觀點認識聖靈，從上述我所描寫的那種灰暗、自我中心的屬靈狀況中擺脫出來。一會兒，我就會指出什麼是我所認為的正確觀點了。

[[Keep_in_Step_With_the_Spirit__notes.org#道德掙紮教義的陷阱][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 叫我們醒覺
　　現在，我們必須探討第四種看法，他認為聖靈的職事基本上就是呈示；簡單來說，就是促使我們醒覺到一些事情。這是泰萊主教（BIShop J．V．Tpylor）的著作《仲介之神》（ The Go-between God）裏面所載的觀點。

　　泰萊視聖靈（希伯來文的 ruach，希臘文的 pneuma；兩個原文的意思是「吹動的風」或「呼出的氣息」）為聖經中一個代表神聖「交流」（“current of communication”）的名字，他喚起人對物、對己、對他人，以及對神的醒覺，使人覺察到這一切都是重要的現實，催促我們作出種種抉擇，這些抉擇有時更要求我們作出自我犧牲。聖靈的影響，就是藉著這種「覺醒——抉擇——犧牲」的行為模式顯出來；聖靈就是那位「人生命的仲介之靈」（“life－giving　Go－Between）4，他透過自然界、歷史、人類生命， 及世界宗教施行他的工作，並在其中運行。這種覺醒是對意義和要求的頓然領會，是理性而又感性的。每一次的覺醒和對覺醒的回應，都影響著事後的抉擇和犧牲。自五旬節以來，聖靈持續不斷的工作，就是使個別人覺醒到耶穌的神性，以致他們的生命能活出耶穌在加略山上為罪受死的自我犧牲精神。聖靈要召喚人對這個覺醒作出回應，他在心志相同的人群中所進行的工作最為有效，因為整個群體可以喚起個人的覺醒，而個人又可以提高群體的覺醒。這些論點是泰萊根據歷史悠久和歷史短淺的教會的實際經驗，經過連串反省後得出來的；他視這些教會群體為神聖使命的表徵和途徑，他所有思想都是圍繞著這個中心思想組織起來的。

　　我們以上所綜覽的幾種對聖靈的看法，受一般牧者大力提倡，卻往往被學者挑剔地評為「大眾化的敬虔」；泰萊是位有恩賜的神學家，故此，他的見解比其他人的看法較有深度是不足為奇的。他著作的大部分內容都使人印象深刻。首先，他的觀點由始至終都以神為中心。不僅他的「交流」關鍵思想是根據三一真理的啟示，源自聖靈那「在聖父與聖子之間的永恆職分，使兩者互相察覺」5，而且他比其他人對於聖靈自由主權的本質有更深遠的洞見——那些人認為聖靈是神賜給我們的力量，供我們使用，或讓我們有所表現；只要我們除去障礙，這股力量就會從我們心裏自動釋放出來。泰萊認識到聖靈不是神賜給我們的一種興奮劑，他不是任由我們操縱和支配的。所以，泰萊永不跟隨別人膚淺的言論；他們談論讓聖靈在我們裏面得釋放，其實只不過是靠賴自己的抉擇，憑著自己的意志，根本不是聖靈的作為。泰萊在講述聖靈是我們的溝通者和激勵者之餘，從沒有忘記我們是人——罪惡、愚昧、多變、混亂的人——，而聖靈是我們神聖的主，他在我們心裏的工作是超過我們心思所能理解的。泰萊不容許我們專注浸裏在我們內裏與罪惡的爭戰中，因為他看見聖靈經常把我們的注意力往上往外導引，叫我們以神、耶穌基督及其他人的事為念。

　　因此，泰萊一方面強調每個人在神面前的獨特性（醒覺是屬於個人的事情），另一方面，他的整體取向始終以小組、教會和社區作主導，毫不宣導個人主義。不過，對於文化習尚在聖靈帶領的社群中施加任何限制，他原則上不以為然。他指出，既然耶穌並不屬於他時代的既成文化模式，聖靈在今日也會拆毀一切我們試圖限制他的文化框框。

　　對於「自發和出於超理性反應」的靈息表現——表現在醫治、方言，尤其是預言的恩賜上——，泰萊亦很靈巧地建構了一套神學思想。他用全人的觀念去解釋這些表現：人不是只懂得作理性分析；整個人的各方面都是聖靈工作的範疇。不過他警誡我們防備自我主義。自我主義與不成熟的思想行為互為因果，往往危害靈恩的精神。泰萊再次表現他的智慧（雖然他所表現的智慧或許並非必需）。他探測那既險且真的道理：人愈趨成熟，聖靈的道德指引便愈有創意，帶領我們超越（當然不是偏離）有聖經根據的正規律例範疇。

　　這些都是真正的灼見。

[[Keep_in_Step_With_the_Spirit__notes.org#叫我們醒覺][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

*** 泰萊觀點的毛病

　　與上述長處並排的，是兩項缺點——這些缺點是基於泰萊未能完全按著聖經嚴格的要求去徹底發展他的聖經觀點。

　　首先，他對聖靈所呈示的道說得太少。他討論這個主題時，引用兩節論到神的話語（words）的經文（賽五九 21；民二三 5），然後立即說到約翰福音及教父們所講述的道（Word）——那有位格的神聖之道（personal divineLogos）——，好像話語和道是同一東西。6 然而無論是聖經上的用法或普通常識都告訴我們兩者並非一樣。那些見證有位格的道（the personal Word）的話語（ words），顯然與道（Word）有別。（在這裏，泰萊是追隨巴特「Karl Barth」的講法。巴特肯定地宣稱這些是表現神獨一的道三種形式的其中兩種，但這宣稱本身在神學上是一個謎：聖經裏沒有這種說法；巴特曾聲稱他憎惡那些脫離聖經的推測，但在半個世紀以後的今天看來，似乎他自己也在不知不覺間採納了那種方法。）

　　對於聖靈所激發的覺醒，泰萊的論說尚欠完善，他還需要做的，就是分析聖靈如何證實神所啟示的話語、教訓和資訊；這些教導和資訊，是先知和使徒們從神那要領受，然後重新安排，再以聖經的形式書寫出來的。此外，泰萊還需要分析聖靈如何擔當詮釋者的角色，帶領我們實在地掌握神此時此刻對我們說什麼話。可是，泰萊對這些問題沒有提供任何分析。

　　其次，泰萊對於聖靈所呈示的基督說得太少。出乎意料之外，他並沒有系統地綜覽保羅和約翰對聖靈的論說，沒有探討這兩位對聖靈瞭解極深的偉大新約神學家如何闡述聖靈在多方面體現基督，這大大削弱了他的觀點。他所述有關聖靈的引證使我們覺察到基督，他雖一方面專注講述歷史中的耶穌，另一方面卻對耶穌現今掌權、將要再來、他不斷為我們代求、現在與我們的關係、基督徒與他永恆同在的確實盼望等等，都沒有一視同仁地強調；這些欠缺徹底沖淡了對基督醒覺的意義。

　　泰萊寫道：「那充滿我們異象的基督，不管他是歷史中的耶穌、活著的救主，還是那為我們捨身流血的基督，或是那道和宇宙的主，又或是我的鄰舍和窮人的基督，都不打緊；這些只不過是他存在的某方面。無論我們覺得哪一方面最為真實，要緊的是我們崇敬他。」沒錯，這裏說得很好，但假若泰萊補充說，我們欲要心中的基督形象配得上基督自己，又符合聖經的真理，那我們就需要將基督各方面的真理連結起來，並且加上更多，這將成為更好的教義。

　　就最後的分析來說，我們習慣上怎樣去思想基督，實在是舉足輕重的事；我們屬靈的健康很在乎我們對他是否有足夠的認識，因為認識基督不單只是認識他宇宙性的地位和他在地上的歷史事蹟；反之，猶如墨蘭頓（Melanchthon）很早以前說過，是要認識他的好處——即是要知道耶穌在他所擔當的各種角色中，諸如使者、中保和神救恩的體現等，賜與我們什麼。不過，若然你對基督的認識很少，你對他的好處自然也所知有限。

　　我不是說信徒從耶穌領受的不會超乎他所知的。我先前談論過神的豐盛慈愛，他為愛他的人所作的，是「……超過（新國際譯本「NIV」譯作『無限量的超乎』）我們所求所想的」（弗三 20）；我們應在這裏回想一下這個要點。耶穌基督對於信徒是始終如一的（神人二性的救主、主、中保、牧人、倡議者、先知、祭司、君王、代贖的祭牲、生命、盼望等等），不在乎他們腦海中對這種與基督的多重關係有多深或多淺的瞭解。舉例來說，使徒兼神學家保羅對這些關係的瞭解，比路加福音二十三章三十九至四十三節中悔改的強盜認識更深，然而耶穌的拯救對任何人都同樣豐厚，我們可以肯定，使徒和強盜此時都同在寶座面前；他們在地上擁有神學知識的多寡，絕不影響他們在天家享受與基督同在的福樂。「……同有一位主……厚待一切求告他的人」（羅一○12）——主不單厚待猶太人和希利尼人，也同時厚待不擅長也沒有博覽神學的人，這一點是無可置疑的。

　　但是我所關注的，就是愈少人認識基督，愈早需要提出以下問題：既然他們對耶穌只有蒙朧而歪曲的觀念，他們對耶穌的回應究竟能否真正算為基督徒的信仰？人愈是偏離聖經所述有關耶穌的各種道理（前列的也許是基要道理），掌握基督真理就愈少，以至到一個地步，就是經常談論基督（回教徒、馬克思主義者、通神學者等都會這樣），但實際上並不認識他。

　　因為上述提及的聖經真理，都指出基督是我們問題的答案；這些問題源自神的聖潔和我們的罪，是聖經教導我們針對我們自己與神的關係而發出的。人與這些聖經啟示距離愈遠，便愈發感到那些問題與自己無關，結果他對真正的基督和真正的神的認識便會愈少。假如有人以為今日的英國是被一個前度搖擺舞蹈家依利莎伯所統治，他就住在波利尼西亞一間木屋裏，隨便按他自己的意思立法，這個人可以說是根本對真正的女皇完全無知。同樣道理，要對耶穌的救贖有真實正確的認識，單單知道他的名字是不足夠的。

　　或者，讓我用另一個講法去解釋：耶穌基督的真理與新約神學的真理結合（而我像主流基督教傳統一樣依從新約神學的宣稱），意思正是說聖父藉著聖靈給聖子作見證。固然，只有這神學中的耶穌，才是真正的耶穌。不管在保羅、約翰、路加、馬太、彼得、希伯來書的作者，或誰人的筆下，這新約神學實質上都是宣告耶穌基督的拯救，他拯救我們脫離那捆鎖我們的假神、假信念、假方法、假希望，以及在創造主面前的各種虛假態度等，內裏包藏著各樣外表吸引的宗教和哲學思想。新約的宣告就是為這整個虛謊和假像的萬花筒疹症，他各樣虛假根藏在種種具體的表現中，不知不覺地把普通啟示壓抑了，誤導人心靈中崇拜的天性，使人對神的福音無知或抗拒。羅馬書一章十八節至三章二十節的表達，是斬釘截鐵的；而蔔仁納（ Emil Brunner）也實在寫得正確：「所有宗教都嘗試重見那失落了的神的真理，所有宗教都渴求神的光和神的愛；但在所有宗教裏，亦同時出現一個無底深淵，真理被邪惡扭曲了，而人更用盡方法去逃避神。」8

　　若然如此，我們必須憑愛心堅定地指出神所教導的福音與其他解釋世界真象的說法存在對立，決不能稍有寬讓或基於禮貌而淡然處之。不然，新約聖經所講述「……基督那測不透的豐富……」（弗三 8），以及他拯救我們脫離罪的權勢，除去我們的罪，最終使我們完全擺脫罪和他的果子等闡述，都會因為我們俯就那不協調的思想模式而被沖淡。這實際上是極端而具破壞性地視福音為一種相對的道理。雖然在這些不協調的思想架構裏，也許會有某些新約思想特別受到重視，但新約神學的絕對正確性，他那肯定的地位、絕對的權威，就經常被否定——在這裏，否定的意思是不容許新約神學批判及修正各種思想架構：如印度教、佛教、猶太教、回教、馬克思主義或其他宗教。因為事實上並非所有宗教和所有思潮都提出關乎神和人的相同基本問題，亦不是朝相同的方向尋找答案。

　　有兩種對話正在進行，他們彼此有極大的分別。第一種企圖尋索基督教與其他信仰之間的對照，而這個對照至終是否定一方以肯定另一方的。第二種對話是嘗試在其他宗教信仰中尋找基督，或勉強把基督移植在其他宗教信仰中。有一點必須指出，雖然泰萊談到種族宗教與基督教後期種種信仰如何透過聖靈接觸基督，從而經歷轉變、更新、死亡與復活 9，但我們完全不能確定泰萊所追尋的是第一種而不是第二種對話。這種含糊的情況其實是他著作裏第三個弱點，是由前兩個弱點引發出來的。這兩個弱點前文已經指出——他沒有認真考慮到那「已記下來的神的話語」10 的實在，同時，對於關乎基督的知識，他忽略了在種種試驗以外，必須以新約中論到基督的教導作為量度的準繩。

　　在泰萊的聖靈觀裏，聖靈是一位居間的聖者，他的工作是呈露現實、驅使人作出抉擇，及喚起人以犧牲作回應。前面所述絕不是批評泰萊這個中心思想。要找出能令我們瞭解聖靈一直以來在信徒生命中職事的新約主要思想，並不需要遠超泰萊卻步之處。他帶領了我們，雖不中亦不遠。

[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 追溯我們的思路

　　先讓我們回顧一下所走過的思路。

　　開始的時候，我們注意到聖靈是現今熱門的話題，不同類型的基督徒經驗都確證聖靈的影響，不同基督徒對他的主要職事都有不同的瞭解，這樣表明了（正如我所力言的）並非所有信徒都能正確地看聖靈。許多人對聖靈的觀點雖然未至完全虛假，但肯定是含糊不清和不夠真實的，因此出現了種種缺欠和實際的不平衡現象，有時構成威脅、窒礙聖靈，使我們無力叫聖靈得著榮耀。故此，當務之急，就是更清楚地認識聖靈。

　　為了衡量近代思潮的狀況，我們探討了目前四個關於聖靈職事並極具影響力的主要觀念：生活的力量（power）、事奉上的表現（performance）、行為和動機的純潔（purity）和驅使我們作決定的呈示（presentation）。這幾點事實上是未夠徹底的，我立即可以再加多幾項：辨識力（perception）。催迫（ push or pull) 和個性（personhood）。因為我們一旦離開基督徒的生活圈子，我們會發現有些人實在以為聖靈主要和獨特的工作只是幫助人提高知覺（辨識力），故此，任何意識提升的狀態，不論是宗教的（基督教、印度教，或祭禮的、忘形的、神秘的思想）、美感的（被音樂、性行為、詩章、日落、毒品所引發），或者是理想層面的（熱情的愛國主義、愛情、為一群人或一個目標貢獻自己），都被視為聖靈的印記。我們也曾遇見另一些人，他們忘記了在我們墮落的人性裏那些不受約束的本能、被壓抑的理智及種種複雜病態的妄想如何會被自然界和撒但隨便利用，竟然把聖靈的感動等同於人內心的渴求（一些拉力或催迫），尤其當這些渴求與一些突然、強烈而又重複地出現的視覺和聽覺意象（如幻影、聲音、異夢）相連時，他們就更加確信是聖靈的感動。我們亦曾遇見另一些人，他們聲稱聖靈在有宗教及沒有宗教信仰的人當中一直運行，他的主要工作是幫助人領會自己獨特個性的奧秘、別人的價值，及對真誠關係的需要。

　　若說神的靈永不助人提高醒覺，亦不會透過內心催迫去叫人做某些事情，也不會令未信主的人更欣賞個人的價值，這些說法肯定是錯誤的，我也絕對無意否定聖靈這幾方面的工作，事實上，我甚至會為聖靈這些職事爭辯。可是，今日一般的想法，以為上述其中一項聖靈職事就等於聖靈的主要職事，似乎與事實相去甚遠。其實，自基督來了，聖靈的中心職事是幫助人與基督建立更密切的團契。無疑，因著普通恩典（common grace），聖靈會在世俗和異教的場合中提高人的辨識力和敏感度，但這從來不是聖靈工作的中心。

　　就拿內在的催迫來說，有些人感到內在的催迫強烈地一再出現，有時候還附以聲音、幻象、異夢等，使他們的感覺更形強烈，驅使他們去強姦、去報復、去傷害人、對兒童進行性侵擾，甚至結束自己的生命。難道這些催迫是出於聖靈的引導嗎？這問題根本不答自明。縈繞心間、擺脫不掉的思想、意念（我們上述所談的，正是這種心神的纏擾）不一定源自神；撒但同樣精於製造使人擺脫不了的衝動，正如他能操縱並加強那些發自我們扭曲了的天性的衝動一樣。故此，對於一些突如其來佔據心神的思想，我們必須仔細檢討（最好是請教別人）然後才下結論，斷定他們是否從神的靈而來。其實，這些思想纏擾心神，叫人擺脫不了，已顯示出他們多半不是源於神的靈了。

[[Keep_in_Step_With_the_Spirit__notes.org#追溯我們的思路][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 基督的臨在
　　現在，讓我們回到實際的基督徒生活圈子去看，在這裏，每個信徒至少朝正確的方向，把聖靈與他們在基督裏的新生命或多或少違絡起來。讓我們再一次發出這個問題：在今天，什麼是聖靈工作的本質、中心和重心？在他賦予人能力、扶助人、潔淨人、向人呈現等工作中，究竟有沒有一樣基本的活動把這些連接起來，讓人充分瞭解他的職事？到底有沒有一個神聖計畫，把聖靈賦予人生命的這幾方面工作聯繫起來，指向一個目標？

　　我認為這計畫是存在的。現在，我會嘗試提出我的見解——我這見解是以臨在的觀念為焦點的。我所指的，就是聖靈在教會及基督徒中間，具體彰顯那位已經復活、掌權的救主，即歷史中的耶穌；這位耶穌就是基督。聖經指出（正如我所堅持的）自從使徒行傳第二章五旬節事件以來，聖靈就一直這樣工作，他賦予人能力、扶助人、潔淨人，並且引領世世代代的罪人去面對神。聖靈這樣做是要叫人認識基督、愛他、信靠他、尊崇他和讚美他；這是聖靈一貫的目標和目的，也是父神的目標和目的。至終來說，這就是聖靈新約職事的全部內容。

　　我在這裏談及的臨在，並非傳統神學所指神的無所不在，這種無所不在的思想，在詩篇一百三十九篇、耶利米書二十三章二十三節、阿摩司書九章二至五節、使徒行傳十七章二十六至二十八節等經文內都有記載，是指神維繫著宇宙萬物的存在及其間的活動，同時覺察每一角落的每一件事。無所不在是一項重要的真理，我現在所要說的亦已假設隱含了這個真理，但在我用臨在一詞之際，我心目中所指的，是一些很不相同的東西。我用這個詞的意思，亦即是聖經作者常用的意思，他們說神與他的子民同在——換句話說，神在特殊的環境中工作，賜福給忠信的子民，使他們認識他的愛，得著他的幫助，從而引發他們對他的敬拜。沒錯，神有些時候會追討罪債，「臨近」人施行審判（如瑪拉基書三章五節的例子），意思是他會作出行動，使人們醒悟到他們的行為令他不悅，事實上他現在仍不斷作這些審判；不過，通常當聖經描述神就近他的子民、與他們同在的時候，往往是指他賜下祝福的。

　　聖經中的用語通常是神「與他們同在」。「耶和華與他［約瑟」同在，他就百事順利。」——正如丁道爾（Tyndale）所說，他是個「幸運的寵兒」（創三九 2）。摩西想到要回埃及去就驚恐，因為在那裏他是個通緝犯；他也恐懼要公然對抗法老。神說：「我必與你同在」——這個應許是要驅走摩西內心一切的恐懼（出三 12，另參看三三 14—16）。摩西離世後，約書亞繼承領導重任，神向他重複這相同的應許：「……我怎樣與摩西同在，也必照樣與你同在；……你當剛強壯膽！……因為你無論往哪里去，耶和華你的神必與你同在。」（書一 5、9；另參看申三一 6、8）堅固以色列民信心的，也是這相同的應許：「你從水中經過，我必與你同在；……不要害怕，因我與你同在……」（賽四三 2、5）。馬太在他的福音書裏，一開始就提到神與他的子民同在、賜福給他們：他宣稱耶穌的出生應驗了以賽亞先知以馬內利的預言（以馬內利翻出來的意思就是「神與我們同在」）。並且在馬大福音的結尾，他也記錄了耶穌為一切願意使人作他門徒的跟隨者所賜下的應許：「……我就常與你們同在……」（太一 23，二八 30）。因為耶穌——救恩的賜予者——就是道成肉身的神，基督的同在正是神的同在。

　　事實是這樣的。在新約底下，聖靈那獨特、恒常而又基要的職事，就是在信徒中間體現基督——意思是說，讓他們領會基督與他們同在，作為他們的救主、生命之主和神，也讓他們知道有三件持續的事。

　　首先，是與耶穌的契合：就是與耶穌密交的、敬虔的生活。縱然耶穌現在已不再以形體在地上顯現，而是坐在天上榮耀的寶座上，但昔日耶穌受難前與第一批門徒在巴勒斯坦的密交生活，今天也可以成為信徒的實在經歷。（這正是呈示的意念：聖靈向我們呈示活著的主耶穌，讓我們認識這位元創造主以及這位朋友，好叫我們可以選擇那犧牲的道路，以回應他的愛和呼召。）

　　第二，品格開始更新，愈來愈像耶穌。當信徒以耶穌為模範和力量、敬拜他、學習為他和其他人有所付出甚至舍己的時候，更新便開始。（這裏正好跟「能力」、「表現」、「潔淨」等主題吻合，他們全都顯出何謂離開人性的自私，踏上像基督的人生道路，去過一種公義、忠心事奉、戰勝罪惡的生活。）

　　第三，聖靈使我們肯定自己被神所愛、已蒙救贖，並藉著基督被接納進入天父家裏，因此我們能夠成為「神的後嗣，和基督同作後嗣」（羅八 17）；這種肯定，使信徒心中綻放出感恩、喜悅、盼望、信心——一言以蔽之，這就是確據。（這一點正好幫助我們瞭解許多基督徒信主後的顛峰經驗。耶穌在約翰福音十四章二十一至二十三節應許聖父和聖子要住在我們裏面，這應許藉著聖靈得以實現，為要給我們更大的確據。）這些經驗正好顯明聖靈讓我們認識到基督臨在——借用戴利仁（Samuel Terrien）的描述；這是：「虛幻、難以捉摸、不可預告、不受規限、不能用經驗來證實、外面看不見而內在卻無可抗拒的」11。

[[Keep_in_Step_With_the_Spirit__notes.org#基督的臨在][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

*** 對神的覺醒
　　從整本聖經來看，認識神的同在意味著兩重的覺醒。首先，我們醒覺神在那裏：那位客觀地真實存在的創造主、掌管宇宙之主、萬物的主宰和所有存於時空之物的原動力；每個人的前途，不論是禍是福，都全在他手裏。第二，我們醒覺到神在這裏，他已經就近我們，對我們說話，質詢我們，鑒察我們，顯露我們的弱點、罪惡和罪咎，使我們降卑，同時又用他的赦免和應許提升我們。在神啟示自己是「蘊含三位」（“three－personed”）（套用但思「John Donne」的說法）之前，人只知道有一位神臨在。可是，現在透過道成肉身的啟示和新約聖經裏的啟迪，有關神的知識已變成了有關聖父、聖子和聖靈的知識；認識神的同在變成了因著聖靈的工作與聖子相遇及相交，並藉著聖子與聖父相交。故此，認識基督的同在，就是在自己時面找到這份對神的雙重覺醒，覺察到他既真實又接近；同時，這種醒覺圍繞著那位來自加利利的人，也就是多馬親口呼喊為「我的主！我的神！」（約二 O28）的那一位。保羅寫道：「那吩咐光從黑暗裏照出來的神，已經照在我們心裏，叫我們得知神榮耀的光顯在耶穌基督的面上。」（林後四6）他所描述的，正是這種對神的認識。

　　自五旬節以來，聖靈特殊的職事是體現基督，這是新納聖經明顯的資訊。正如許多解經家常常指出，聖靈常被視為神的兒子耶穌基督的靈（徒一六 7；羅八 9；加四 6；腓一 19；彼前一 11）。那居於我們心裏的靈，正是那位降臨在耶穌身上，並住在他裏面的靈（路三 22，四 1、14、18，一 O21；約一 32，三 34；徒一 038）。耶穌擁有聖靈，也是賜下聖靈者（約一 33，一五 26，一六 7，二 O22，另參看七 37—39；徒二 33；約壹二20、27）。耶穌被提後，離開門徒，聖靈便臨到門徒身上；這實際上相當於耶穌回到他們當中（約一四 16、18 一 21）。聖經形容神的靈（也就是基督的靈）住在我們心裏為基督在我們心裏（參羅八 9 一 11），正如論到那被高舉的基督所親自宣告的資訊時，就說是「聖靈向眾教會所說的話」一樣（參啟二 1、7、8、11、12、17、18、29，三1、6、7、13、14、22）。

　　再者，保羅在哥林多後書三章十六節寫道：「但他們的心幾時歸向主，帕子「蒙蔽心靈的」就幾時除去了。」這句話是出埃及記三十四章三十四節的迴響，其中記述摩西如何在與神說話時揭去帕子。）然後保羅繼續寫道：

　　主（即上一節經文所述的主）就是那靈（故此，「歸向主」的意思就是「承當這新約的執事，不是憑著字句，乃是憑著聖靈「請參閱第六節 1）；主（耶穌）的靈在哪里，哪里就得以自由。我們眾人既然敞著臉得以看見（或作反照：兩種譯法都可以，而且同具真確的意義）主的（耶穌的）榮光，好像從鏡子裏返照，就變成主的形狀，榮上加榮，如同從主的靈變成的。（林後三 17、18）

　　這些經文所表達的，並不如一些人所想，以為新約聖經作者看不見聖子和聖靈有什麼清晰的區別，其實新約聖經作者看見聖靈在五旬節後的工作主要是讓我們體會那坐在寶座上的基督的同在、話語和作為；只有掌握這基本的新約角度，我們才能清楚認識聖靈。

[[Keep_in_Step_With_the_Spirit__notes.org#對神的覺醒][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 綱要
　　本書認定聖靈受託去體現基督，以這個真理作為瞭解聖靈多面職事的線索。在我看來，現時許多對聖靈工作的綜覽，都未能循這途徑把資料綜合起來，這是他們的缺點。一個表面化的記述，單指出聖靈在新約時期如何被彰顯，以及新約作者怎樣述說這些表彰是不足夠的，我們需要進一步探討這些記述如何配合他們對神、他的工作和他的真理的整套觀念——換句話說，就是他們的整套神學思想——，因為缺乏這方面的探討是一個致命傷，使我們思想聖靈在我們生命中的工作時，變得以人為中心，以經驗作根據，又毫無準則。難怪許多有關聖靈的著述，本來可以是十分精彩的，卻沒有如期望中叫讀者得著幫助，讀者亦不如他們想像中那般獲益。因為今天能幫助我們活在聖靈中的，並不是一些叫我們向聖靈敞開心懷的勸勉——這方面的勸勉我們已足夠有餘了；反之，我們所缺乏的，是對聖靈工作全面而通達的神學透視，好讓我們有一套整全的觀念，能充分瞭解聖靈在教會、小組及個人生命中那自由、不受羈絆及多種形式的運行（聖靈這方面的工作是今日基督教所強調的）。新納聖經所論述有關聖靈的主要真理，是聖靈體現基督的臨在和相交；我希望循這個概念去發展出通達的神學觀點，希望至少能勾畫出一個綱領。

　　在聖經的基礎上，我的目標和觀點可以這樣表達：耶穌在他被賣的那一夜，述說有關聖靈的事：「他要榮耀我……」（約一六 14），意思就是「他將要使我在人的眼中得榮耀，使他們覺察到那本屬於我的榮耀，並且在我通過十字架、復活和升天回到父那裏去，坐在我國度的寶座上時，這榮耀將更大。」這個關於聖靈從前是什麼，現今又奉差遣來做什麼的基本定義（正如我一直認為的），給我們一個完整透徹而具方向性的參照標準，我們必須透過他整體去看聖靈的新約職事，否則我們很難充分瞭解聖靈職事的任何一部分。

　　然後，耶穌繼續說這榮耀將要如何成就，「因為他要將受於我的，告訴你們。」耶穌說「受於我的」是什麼意思呢？他的話至少有這個含義：「一切關於我的事實和真理，就是道成肉身、是天父的同工——創造萬物、眷顧神的子民和賜下恩典，又是這世界正式的君主，即是那位掌管宇宙萬物的主人［參一七 2］。不管人們是否承認我這一切，事實卻是如此。」不過，當然他還有這樣的含義：「一切關於我的事實和真理：我是你神聖的愛人、你的中保、你的新約保證人、你的先知、祭司和君王，又是把你從罪咎和罪惡的權勢、世界的敗壞及魔鬼的掌握中拯救出來的救主，並且是你的牧人、良人、朋友、你的生命、你的盼望、你信仰的創始成終者、你個人生命歷史的主，將來要帶領你與我同在，分享我的榮耀。所以，我是你的道路和你的獎賞。」故此，因著我與你彼此的關係，「受於我的」也就是「受於你的」了。

　　我的童年屬於低唱抒情歌的年代，記得當時有一首民謠，名為「你的一切」（“All the Things You Are”），歌曲結尾是這樣的：「……有一天，我將會認識那神聖的一刻，那時候，你的一切也成了我的一切。」聖靈說服我們相信耶穌在他榮耀裏的一切都是為我們預備的，藉此讓我們看見耶穌的榮耀。套用保羅在哥林多前書二章七節的說法，是「使我們得榮耀」——認識這個真理比輕歌淺唱的浪漫時刻更神聖。

　　耶穌說：「他要……告訴你們。」這個「你們」是單指使徒還是所有與他們一起的基督徒呢？主要是指使徒而言：他們得著這些真理的直接啟示。但其次亦是指所有信徒：透過使徒口傳或筆錄的見證，聖靈會教導眾信徒認識同樣的真理。使徒必須與神的眾子民分享他們屬靈的領受，昔日如此，今天亦然。

　　第十五節有如一個注腳。為了不讓上一句話我的一詞所涉及的整個範疇和含義遭忽略，耶穌繼續說道：「凡父所有的，都是我的，所以我說，他要將受於我的告訴你們。」加上這句注腳，是為了防備一些可能產生的誤解，避免人以為父神和他的工作比耶穌本人及其工作更超越，又或者（反過來說）父的屬性、宣稱、能力、計畫、展望和榮耀都比耶穌的更偉大，更廣遠。「凡父所有的，都是我的」；子和父是平等的；父的旨意是「……叫人都尊敬子如同尊敬父一樣……」（約五 23）最終來說，一切基督徒真實信仰、敬拜和實踐，都建立在這神聖的目標上。

　　在以下的篇章裏，我會從上述的角度嘗試解釋聖靈的職事。我會指出聖靈如何使父的喜樂增加，他所作的，就是藉著宣告，叫子得榮耀，引導我們作出回應，存崇敬的心去榮耀子。我始終堅持所有對聖靈多方面工作的解說——或者套用一個專門術語：「聖靈論」（pneumatology）——都需要從以下立場去闡釋：一方面，父的旨意是要子被認識、被愛、受尊崇、受讚美，並在萬物中居首位；同時另一方面，透過賜下聖靈，子應許與他的子民同在，從今直到永遠。除此以外，沒有一種解說能完全合乎基督教精神。我計畫在本書裏，指出在一套純正基督教聖靈論裏的一些主要成分；因此我的闡述會一貫地建基於約翰福音十四章十六至二十三節及十六章十四、十五節中耶穌所親自表達的思想上，而不會在他們以外另找基礎。我希望這樣的綱要是可接受的，並且我相信這是今天所需要的。我現在就循此路線去探討。

[[Keep_in_Step_With_the_Spirit__notes.org#綱要][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 注文
　　1 Steven Barabas，So Great Salvation（London：Marshall， Morgan＆Scott，1952），p．v．這本書提供一個對凱錫克信念的詳盡分析。另參考
J．C．Pollock，The Keswick Story：The Authorized History of the KeswickConvention（London： Hodder＆ Stoughton，1964）。
　　2“‘Keswlck’ and the Reformed Doctrine of sanctification，” Evangelieal Quarterly，27，No．3（1955 年 7 月）：第 153 一 167 頁。請看當時編者 F．F．Bruce 的評論，“In Retrospect：　　Remembrance of Things Past，”（Grand Rapids：Eerdmans，1980），第 187、 188 頁。
　　3 John Owens， Wods， ed． W． Goold（London： Banner of 們 Truth，1967),4：437．我們可以爭辯說，新約聖經列出的屬靈恩賜包括了性情上的質素，是歐文著重理智的分析所沒有的，然而這亦不影響他所講述有關語言方面恩賜的真理。
　　4 John V，Taylor，The Go－Between God（New York：Oxford　University Press，1979），第 212 頁。
　　5 同上，第 102 頁。
　　6 同上，第 58—62 頁。
　　7 同上，第 241 頁。
　　8 Emil Brunner，Revelation and Reason（Philadelphia： West-minster，1946），第265 頁。
　　9 Taylor，第 191 一 197 頁。
　　10  Anglican Article 20．
　　11 Samuel，Terrlen， The Elusive Presence：Towards a New　Biblical Theo1ogy（San Francisco： Harper＆ Row， 1978），第 457 頁。

[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

* 2_聖經裏的聖靈
　　現在就讓我向你陳述本書的中心思想吧！這並非一個新思想，它古老得可與新約時代相比，要陳述這思想，無非是追溯基督徒的本源。他是如此簡單：在現在或任何一個基督教年代，聖靈職事的本質就是體現我們的主耶穌基督。縱然我們對這個真相的理解是落後而不足，但我作為基督徒作者，你作為基督徒讀者，其實已經活在聖靈這個職事以下。

　　在我的方程式裏，耶穌的同在不該以空間來思想，應該以關係來思想。我這樣說，是指著我對三件事情的覺醒而言的。第—，是拿撒勒人耶穌——聖經裏的基督——曾被釘死，現今得著榮耀，就在這裏親自俯近我，對我說話。第二，他正在積極工作，他催迫我們脫離惰性，加強我們的洞察力，安慰我們內疚的良心，使我們的脾氣轉好，在壓力中支持我們，堅固我們，使我們過公義的生活；就這樣，他大大地啟迪我和眾人，賦予我們生命朝氣，改變我們的生命。第三，就他自己和他的工作而言，他是榮耀的，配受我們所能獻上的一切崇拜、敬慕、愛和忠誠。因此，聖靈體現基督，盡他所能，在人的生命中創造、保持、加深和表達這種對耶穌同在的醒覺。在我們要清晰解說這一點時，耳熟能詳的主題就浮現我們腦海裏：在基督裏從神而來的溝通，和藉著基督人與神的密契；聖經的闡釋和人心靈的啟迪；罪人的重生和成聖；恩賜和善行；聖靈見證我們被神收納為後嗣，幫助我們勝過人性的軟弱；憑超自然的力量，產生信心、禱告、盼望、愛和所有像基督的性情……。這裏沒有什麼新鮮的事，只不過我指出聖靈這一切的工作時，特別強調他們都以基督為中心，而以前是很少人如此強調的。我在本章嘗試表明，這樣強調純粹是出於聖經的指引。

　　我想在開始的時候，我們最好看看聖靈的名稱及注意他蘊含的意義。

[[Keep_in_Step_With_the_Spirit__notes.org#2_聖經裏的聖靈][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 神的靈
　　今天，對於大多數人來說，靈（SPirit）是一個含糊褪色的字彙。英文 spirit 這個字最易令人聯想起人的情緒或態度（如 high or low spirits「情緒高漲或情緒低落」，animal spirits「輕快精神」，a cheerful or downcast spirit「高興或沮喪」，aspirit of mischief or kindness［惡作劇或和藹的態度」等等）。從前靈這個詞曾用來代表各類游魂和神靈（如天使、魔鬼、神仙、小精靈、妖怪、鬼、孤魂，以及住在山嶺、石頭和樹上的神靈）。因此，在一六九一年，年長的清教徒巴斯特（Richard Baxter）給他那本離奇趣怪、肯定靈界事物的書定名為《靈界的真實》（ The Certainty of the Worlds ofSPiritS）。但人們對這些靈體的信念已逐漸消失，至少在西方是如此。現在，許多人會認為相信各種靈體至少反映出人缺乏哲學性的冷靜。總之，在研究「神的靈」這個主題時，我們的西方文化根本不能給我們什麼幫助。

　　其實，一如聖經裏其他指向神的辭彙，靈是一個圖像化的名詞，具有生動逼真、明確、富色彩的意思。這個字的意象是呼出或喘著的氣，就如你吹熄生日蛋糕上的臘燭，或者吹脹一個汽球，或跑步時喘氣那樣。「靈」字在這裏的意義，可從以下的情景去瞭解：一頭狡猾的豺狼唬嚇一群小豬，大聲喝道：「我會發怒，我會噴氣，我會把你們的屋次塌！」整個意象就是強勁有力地，甚至猛烈地鼓動空氣，所表達的意念是釋放出來的能量、進取的力量、運用中的能力，以及藉活動來表彰的生命。

　　聖經中希伯來文及希臘文的「靈」字（ruach 和 Pneuma），都同時帶有這個基本意思，兩個字都同時使人產生相類似的聯想。他們的含義包括：（1）那位神聖的靈，是有位元元格和目的，看不見又無法抗拒的；（2)個人的意識（在這層意義上，靈就是魂的同義詞，例子見於路一 46、47）；（3）風：這種風一旦被激起，可使樹葉飛旋、大樹連根拔起、樓宇坍塌。（例子可參看（a）結三七 1 一 14；在枯骨的異象中，希伯來文ruach 的意思先後是氣息、風和神的靈。（b）約三 8；希臘文 Pneuma 意指風，同時也指神的靈。）但願在我們的語言裏也有一個字包含這種種聯想。英文字“puff”和“blow”（我想這兩個是唯一較貼切的字彙），既指從人的肺部呼出空氣，也表示風的吹動，但英文中完全沒有一個字既包含上述意義，又同時表達神並他所造具理性的受造物在智慧、意志和情感上的個性。相對地，英文字 spirit E 指在行動和反應上具有意識的人格，但這個字卻沒有風或氣息的含義。無可置疑，這是 spirit 不能給我們像 ruach 和 pneuma 這些字對昔日聖經時代人物同樣啟示的其中一個原因，因為他沒有運行的力量的含意。

　　其實，每當聖經提到神的靈，一個基本理念是能力的作為。在舊約聖經裏，「神的靈」常常指那位正在工作和改變事物的神。接近一百節經文（最低的數目是八十八節，最高的數目是九十七節；不同學者有不同的數算方法）對神的靈所進行的工作有如下記敍：

1．將整個創造模塑成形，賦予受造物生命氣息。（創一 2，二 7；詩三三 6；伯二六 13，三三 4）
2．控制大自然的秩序和歷史的進程。（詩一○四 29、30；賽三四 16，四○7）
3．藉著直接溝通和／或經過過濾的屬靈洞見，向神的使者啟示神的真理和旨意。（民二四 2；撒下二三 2；代下一二 18，一五 1；尼九 30；伯三二 8；賽六一 1 一 4；結二 2，——24，三七 1；彌三 8；亞七 12）
4．藉著這種種啟示，教導神的子民如何忠心愛主，多結果子（尼九 20；詩一四三10；賽四八 16，六三 10—14）
5．引發個人對神的回應（也就是聖經所說的認識神）——以信心、悔改、順服、公義、敞開心懷去接受神的訓令，以及透過讚美、禱告與神相交來回應神。（詩五一 10—12；賽——2，四四 3；結——19，三六 25—27，三七 14，三九 29；珥二 28、29；亞一二 10）
6．裝備個人成為領袖。（創四一 38，約瑟；民—一 17，摩西；民一 16—29，七十個長老；民二七 18 及申三四 9，約書亞；士三 10，古珊利薩田；士六 34，基甸；士—一29，耶弗他；士一三 25，一四 19 及一五 14，參孫；撒上一○10，—一 6，另參看一九 20—23，掃羅；撒上一六 13，大衛；王下二 9—15，以利亞和以利沙；賽—一 l 一 5 及四二1—4，彌賽亞）
7．賦予個人技巧和力量，去達致創造性的成就。（出三一 1—11 及三五 30—35，比撒列和亞何利亞伯；另參看王上七 14，戶蘭擅長手工藝；該二 5 及亞四 6，聖殿的建築）

　　簡言之，舊約的靈代表著神，擔當創造者、掌管者、啟示者、催迫者和輔助者等身分，積極作工；透過這些身分，神在一種充滿動力和要求嚴格的方式下向人顯現，正如主耶穌現在向眾信徒顯現一樣。詩人發問：「我往哪里去躲避你的靈？我往哪里逃躲避你的面？」（詩一三九 7）這兩個問題是互為解釋的，兩句話的意思都一樣。可是，靈的獨特位格並不是這啟示的一部分。舊約聖經中，神的靈（氣息！）在邏輯上與他的手和膀臂兩個形容神大能的擬人法字彙處於同等地位；同樣，說到他的熱心時，也是一種擬人法，是表明他目標堅定。你大可以說這些引述神的靈的經文表明堅定全能的神在工作，並且他的熱心和他的膀臂也一起作工；但若憑這些參考經文去推論在舊約聖經作者的思想裏，存在著合一的神本體裏蘊含多重位格的觀念，這是不正確的。三位一體的真理是新約的啟示。

　　可是，若然有人以為根據聖經來看，在舊約時期，神是一位的，直至耶穌降生，神才變為三位，那麼他亦是大錯特錯。這裏的問題不在於自永恆以來神存有的模式，而是他在歷史中啟示自己的形態。我並不是說神本體裏的第三位格在舊約時期不存在或不工作；新約聖經作者向我們確證只存在並作工。我只不過說舊約聖經作者並未將他的獨特位格表達出來。固然神的三一性是亙古以來的事實，但惟有透過基督，我們才可以認識這真理。

　　現在，讓我作一點補充：跟隨耶穌基督的人閱讀舊約聖經的正確方法，是藉著在基督裏並透過基督給我們啟示的真理，在新約的亮光下理解。耶穌表明他是舊約聖經的依據，並要成全經上的話（參太五 17，二六 54 一 56；路一八 31，二二 37，二四 25—27、44—47；約五 39、45—47），因而使徒都宣稱整本舊約是神賦予基督徒的教導（參羅一五 4；林前一○11；提後三 15—17；彼後一 19—21，三 16）；他們經常在舊約聖經中讀到神的真理和智慧，所以也經常發現經文所反映出來那關乎基督的知識和基督徒生命的真象。新約聖經引用舊約聖經的時候，情形正是這樣。因此，使徒閱讀舊約聖經有關神的靈在工作的經文時，必須根據新約中關於靈的獨特位格的啟示去瞭解；同樣，讀到舊約中關於那位獨一真神、主耶和華、創造主、救主和成聖之主、崇拜的唯一正確物件等經文時，也應該透過新約所揭示三一神的真理去瞭解。這不是隨便說的，這些理解聖經的步驟之所以正確，是因為他們承認兩約的神是同一位神。

　　肯定來說，這些解經步驟並非現代學者所說的歷史釋經法（historical exegesis）。歷史釋經法只尋求瞭解作者期望他心目中的讀者從他的文字得著些什麼，而不再深入探討。借助新約聖經的亮光去研讀舊約聖經的方法，最好形容為神學性釋經（用流行的詞句來說是「據典式釋經」）——就是問那位默示每位聖經作者的聖靈，他到底期望今天的基督徒讀聖經時，在他們有新約聖經的全部真理，並聖經其他經卷作為研讀背景的情形下，可以從聖經中領受些什麼。歷史釋經法使我們確信舊約作者在他們論及神大能氣息的時候，並無意暗示在神裏面有個別獨特的位格存在。可是，基督教神學的解釋，卻要求我們像主耶穌和他的門徒一樣，認識到神本體裏的第三位在舊約時期已經活躍，而舊約聖經有關神大能氣息的陳述，事實上是指到有位格的聖靈的作為。有關這個真理的教導，我們可從聖經裏找到線索，如馬可福音十二章三十六節、使徒行傳一章十六節和四章二十五節，都指出大衛靠著聖靈發言，與撒母耳記下二十三章二節遙相呼應；路加福音四章十八至二十一節也指出耶穌被聖靈的能力充滿（見三 22，四 1、14，另參一35、41、67），宣稱他的教訓應驗了以賽亞書六十一章一至四節的預言，見證聖靈膏立了耶穌；在約翰福音三章五至十節裏，關於藉「水和聖靈」重生的教導，明顯是回應以西結書三十六章二十五至二十七節及三十七章一至十四節的，而身為以色列人的先生的尼哥底母，就是因為不曉得這個教導的經文出處而受責備；在使徒行傳二十八章二十五節、希伯來書三章七節和十章十五至十七節裏，每當舊約教訓給應用在新約的教導上時，都以聖靈為根源；還有最具決定性的，就是使徒行傳二章十六至十八節，在這段經文裏，彼得指出五旬節聖靈的澆灌，是應驗約珥書二章二十八、二十九節的預言：「……我要將我的靈澆灌……」

　　因此，舊約聖經中那些論到神的靈的經文，其實是見證新約聖經裏聖靈的工作。在以下的討論中，我要以此作為基礎。

[[Keep_in_Step_With_the_Spirit__notes.org#神的靈][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 聖靈的位格
　　
*** 聖靈是保惠師
　　在新約聖經裏，聖靈被描述為第三位聖者，與父和子相連，卻又有別，即如父和子有別一樣。他是「保惠師」（paraclete）（約一四 16、25，一五 26，一六 7）——paraclete 是一個很豐富的辭彙，在英文裏還未找到一個圓滿的翻譯，他的意思包括安慰者（含有使人剛強的意思）、輔導員、幫忙者、支持者、顧問、辯護者、盟友、長者——惟有有位格的聖靈才能夠圓滿擔任這多重角色。簡言之，他是「另外……一位」保惠師（一四 16），緊隨主耶穌而來（我們可以這樣說），接續耶穌的職事——亦惟有像耶穌一樣有位格的聖靈，才能夠這樣做。在希臘文文法裏「聖靈」是個中性名詞（pneuma），必須配上一個中性代名詞（ekeino，「他」）；但約翰為了突出聖靈的位格，卻重複運用陽性代名詞（ekeinos，「他」）來敍述耶穌對聖靈的講論：約翰希望他的讀者肯定知道聖靈是「他」，不是「他」。約翰在約翰福音十四章十七節首次介紹聖靈時，運用了合乎文法的中性代名詞（ho 和 auto），這使他後來在一四 26，一五 26，一六 8、13—14 等章節裏轉用的陽性代名詞顯得尤為突出，因為由此可見他轉用陽性詞類並非他的希臘文力有不逮，相反，是源於一種具權威的神學思想。

　　同時，聖靈被描述為會聽、會講、能作見證、使人信服。榮耀基督、帶領、引導、命令、禁止、願望、感動人說話、給予人幫助，用說不出的歎息為信徒祈禱，並親自在信徒的禱告中向神呼求（參約一四 26，一五 26，一六 7—15；徒二 4，八 29，一三 2，一六 6、7；羅八 14、16、26、27；加四 6，五 17、18）；此外，他還會被欺哄，會擔憂（徒五 3、4；弗四 30）。只有具位格的，才能符合以上的描述。所以，聖靈並非單單一種影響力；他像父和子一樣，是有位格的。

[[Keep_in_Step_With_the_Spirit__notes.org#聖靈是保惠師][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

*** 聖靈是神
　　進一步來說，聖靈被描述為一位聖者。他的獨特性包含在合一的神的本體裏。聖靈的「聖」字意味他的神性，好幾段經文都很明確地道出這點。耶穌說他的門徒要受洗歸入神的名（注意：「名」「name」是用單數寫的，因為只有一位神）；他所宣稱的這個名字，是一個具有三重位格的名（tripersonalname）：「奉父子聖靈的名」（太二八19）。（巴特「KarlBarth」很美妙地稱這名為神的「教名」！譯者注：西方早期基督教會的傳統，人領洗歸信基督後，取一聖經人物或聖徒的名字作自己的教名「Christian name」。據舊約希伯來人的觀念，名字代表一個人的身分及他的個人特質。）同樣，約翰寫信給七個教會，開首就說：「但願從那昔在、今在、以後永在的神，和他寶座前的七靈，並那誠實作見證的，從死裏首先復活，為世上君王元首的耶穌基督，有恩惠、平安歸與你們。」（啟一 4—5）在啟示錄裏，「七」象徵神聖圓滿，而「七靈」肯定代表聖靈圓滿的能力和工作（見三 1，四 5，五 6）。且看天父列在首位，子排列第三，而聖靈列在二者之間；毫無疑問，聖靈與其他二者是同等的。確定此事之餘，我們同時發現一連串「三而一」的經文，在恩典的獨一計畫中不可分割的整體裏，聖父、聖子、聖靈連成一體（見林前一二 4— 6；林後一三 14；弗一 3—13，二 18，三 14—19，四 4— 6；提後二 13、14；彼前一 2）。所得的結論是，聖靈絕非單單一個有能力的受造物，像天使一樣；他與父和子同等，是那全能的神。

　　因此，我懇求各位：絕不可用非位格性的辭彙去思想或講論聖靈！有時候，我聽見基督徒用「他」而不是「他」來形容第三位聖者，我感到驚懼，我的心下沉。這在屬靈層次上相當於心理學上的佛洛伊德式口誤，即如有一次我在維真學院（Regent College）分享的資訊中，我本想對學生說：「請謹記，這是一所神學院（seminary）。」但我卻沖口而出說：「請謹記，這是一所墓地（ cemetary）。」當時雖然引來哄堂大笑，但其實我所講的並不是我的意思，我的意思也不是我沖口而出的話。我希望一些聖徒稱聖靈為「他」時，他們也不過是一時口快失言，他們所講的也不是他們心底的意思。因為除非你能夠掌握聖靈具有位格這個事實，否則你不能真正明白聖靈的職事。倘若聖靈的位格被否定了，我們根本沒法對聖靈的工作有一個牢固的觀念和清晰的瞭解。（若果你想找出這話的證據，且看自由派及激進派抗辯宗、猶太教、伊斯蘭教、獨神論和基督教科學的基本信仰。）我實在不願意看見堅守聖經信仰的基督徒當中，有誰在這一點上猶豫動搖。靈恩派對教會的一項重大貢獻，就是使人很難不以「他」來稱呼聖靈。然而，要叫信徒確信聖靈擁有位格，最穩當的方法莫如將新約聖經對聖靈工作所作的見證擺在信徒面前。現在就讓我們從這方面著手吧！

[[Keep_in_Step_With_the_Spirit__notes.org#聖靈是神][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 聖靈與基督
　　約翰福音是否有可靠的歷史根據這個問題，已掀起了整整一個世紀的學術辯論，故此在研究新約聖經主旨的時候，若還以約翰福音起始，就會顯得過時落伍了。一般慣常的做法，是透過馬太、馬可及路加福音，有時候也透過彼得和保羅的書信，去研究約翰的見證；就好像我們只能站在其他作者的肩膊上，才可清楚看見約翰一樣。可是，對於約翰的記載，既然我看不出有任何充分理由去懷疑他的真確性，也不見得內容含混不清，我提議以約翰福音作為闡釋聖靈新約職事的出發點，因為約翰福音記載了耶穌親口說的話，為我們提供了瞭解聖靈職事的重要線索。無論如何，若然我們想完全瞭解馬太、馬可、路加、彼得和保羅所告訴我們有關聖靈的真理，我們必須站在約翰的肩膊上去觀看。

[[Keep_in_Step_With_the_Spirit__notes.org#聖靈與基督][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

*** 應許賜下聖靈
　　約翰告訴我們，在耶穌被賣的那一夜，他向十一個門徒絮絮不休地說了一段很長的話，表示自己將要離開他們，進入榮耀中（約一三至一六章），而且談論到他們未來的門徒生命將會如何。他好幾次提到保惠師，即是他所說真理的靈（約一四 17，一五 26，一六 13）和聖靈（約一四 26）。他說在他離去以後（約一四 16、26），天父會因著他（聖子）的要求而差派保惠師來，因此，我們可以說聖靈是由聖子差派的一位天父的使者（約一五 26，一六 7）。耶穌說，他會「因我的名」受差遣（約一四 26），亦即是說他是耶穌的信差、發言人和代表；他將會永遠與耶穌的門徒同在（約一四 16）；藉著他的降臨，耶穌——他們榮耀的主——就會真實地住在他們中間（約一四 18—23）。在聖靈的新約職事中（這正是耶穌所講述的），聖靈會隱藏自己，而將人的注意力校正到耶穌身上，把人帶進信、望、愛、順服、敬拜和委身的生活中，以致與基督深深密契。讓我們說得清楚一點，這仍舊是量度所謂「屬靈」運動——諸如合一運動、靈恩運動、禮儀運動、小群運動、平信徒運動、普世宣教運動等——並所謂「屬靈」經歷的主要標準。

[[Keep_in_Step_With_the_Spirit__notes.org#應許賜下聖靈][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

*** 聖靈與基督的同在
　　凡願意遵行神話語的人，都表明他們是愛神的（約一四 21—23），聖靈會幫助他們真實地經歷基督的同在，並與基督和天父相交。「有了我的命令又遵守的，這人就是愛我的；愛我的必蒙我父愛他，我也要愛他，並且要向他顯現。」這是基督徒獲得獨特經歷的途徑，約翰已親自為這種經歷作見證，他寫道：「……我們乃是與父並他的兒子耶穌基督相交的。」（約壹一 3）這是基督給我們眾人的挑戰，叫我們尋求這種親身體驗的相交生活，而不單單滿足於次等的基督徒生活。

[[Keep_in_Step_With_the_Spirit__notes.org#聖靈與基督的同在][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

*** 聖靈的教導
　　耶穌在世上三年的事奉中，曾經不斷教導人，同樣，聖靈也負責教導的工作；聖靈教導的方式是使門徒回想並瞭解耶穌曾經說過的話。（約一四 26；另參一六 13，耶穌所說「一切的真理」，類似十四章二十六節的「一切的事」，意思並不是說「要知道所有任何事情」，而是指到「所有你需要知道有關我的事」，「將來的事」並非「將要發生在你身上的事」，而是「將要發生在我身上的事」——十字架、復活、作王、再來、復興萬事。）今天，林林總總的所謂基督教神學思想爭相吸引我們的注意力，我們大可用上述方法去試驗聖靈在這一切神學思想裏到底占了什麼地位。

[[Keep_in_Step_With_the_Spirit__notes.org#聖靈的教導][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

*** 聖靈的見證
　　最後，聖靈會為基督作見證，使眾人知道那像囚犯一樣受刑釘死的基督，實際上並非罪人；他復活後進入天父的榮耀中就證明他是正義無罪的；藉著十字架上的審判，他驅逐了世界的黑暗之主，並成為世界的審判者（參看約一二 31）；凡拒絕承認這些真理的都犯了不信的罪（約一五 27，一六 8 一 11）。那帶著見證的靈無形中成了世人的起訴者，讓世人醒悟到拒絕耶穌，或不以認真態度對他是何等嚴重的罪（約一六 8）。聖靈在一個又一個的心靈中工作，叫人知罪，承認：「我錯了；我有罪了；我需要神的赦免。」這是聖靈在福音工作中協助人信主的應許。他說服人及使人認罪的方式，是透過教會傳遞使徒的資訊，去說服人接受基督；而聖靈的見證，是藉著作見證的基督徒將真理展示在人們的心思意念中，然後聖靈就開啟眾人心靈的耳朵，使真理在每個人的良心裏運行（參約一五 27，一七 20）。

　　故此，聖靈是要榮耀那榮耀的救主（約一六 14）。一方面，他將關於基督的真理闡釋清楚，另方面，他開啟人愚昧的心竅去接受真理。由始至終，主基督耶穌都是聖靈職事的焦點。

[[Keep_in_Step_With_the_Spirit__notes.org#聖靈的見證][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

*** 聖靈照明基督
　　那麼，聖靈在新約中獨特的職事是要像泛光燈一樣，把主耶穌基督照明。關於聖靈這方面的職事，耶穌在地上的時候，聖靈「還沒有賜下」（約七 39）；直至天父榮耀了基督（見約一七 l、5），聖靈才開始他的工作，使人醒覺到耶穌的榮耀。

　　猶記得一個冬日黃昏，我正步往一間教會講道，講解「他將要榮耀我。這信息。我在街角看見一楝設有泛光照明的建築物，忽然發現這正是我的資訊中所需的例子。完善的泛光照明設備是將泛光燈設在人看不見的位置上，使人不能辨認燈光從何處來；他的作用只是照明建築物，讓人注目在建築物上。他要達到的效果是讓建築物在黑暗中仍清晰可見，輪廓鮮明，以增加其莊嚴氣勢。這正好說明瞭聖靈在新約的角色——他是照明救主的那盞隱蔽的泛光燈。

　　又或者我們可以這樣想：就好像聖靈站在我們背後，耶穌站在我們面前，聖靈在我們的肩膊上投射光芒到耶穌身上。聖靈的信息永不是：「看我，聽我，來就我，來認識我。」而是：「看他，看他的榮耀；聽他，留心他的話語；來就近神，並得著生命；認識他，並嘗嘗他所賜的喜樂和平安。」我們甚或可以說，聖靈是媒人，是屬天的婚姻介紹人，他的角色是帶領我們與基督在一起，並確保我們能夠維持這種關係。聖靈作為第二位保惠師，經常引領我們來到原本的保惠師面前。如上述所闡明的，這原本的保惠師常常藉著第二位保惠師的降臨就近我們（約一四 18）。聖靈協助我們辨出原本的保惠師，又在這位保惠師從他的寶座下來與我們相遇時，感動我們向他伸出雙手；就這樣，聖靈照著基督的話榮耀了基督。

[[Keep_in_Step_With_the_Spirit__notes.org#聖靈照明基督][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 聖靈與基督徒
　　正如前面說過的，耶穌的教訓給我們提供了主要線索，藉以闡明新約聖經一切有關聖靈職事的教導。太多時候，我們只是依據我們的需要和缺乏來理解聖靈的職事，而不是按著我們剛剛學習的真理——即是說，聖靈的工作是榮耀基督，他主要而恒常的職責是向我們體現基督，幫助我們醒覺耶穌是誰，好讓我們完全信靠他——來瞭解。結果，我們以基督徒為中心，而不是以基督為中心去理解聖靈的工作；換句話說，是以人為中心而不是以神為中心去看聖靈的職事。

　　無可置疑，其中一個導致這種以人為中心的觀點的原因，是雖然新約書信對聖靈在個人身上所擔任的職事有最詳盡的討論，卻甚少提及門徒與主耶穌之間的愛和相交（因為當時書信的讀者肯定已知道這方面的真理），然而在福音書中，雖對於關乎耶穌的一切有最詳細的描述和闡釋，但除了約翰福音十四章至十六章以外，就甚少論及聖靈。但是，我們必須謹記，福音書是為那些熟悉書信中教義的人寫的，同樣，新約書信也是為那些對福音書事蹟耳熟能詳的人寫的。因此，書信的讀者腦海中很自然會浮現有關信靠基督和愛基督的經文。誠然，我們讀新約書信時，也應考慮這一點，絕不可忘記聖靈在新約之下的主要工作仍舊是體現基督。我嘗試在以下的段落裏，指出牢記這個事實會如何影響我們慣常的思想。

[[Keep_in_Step_With_the_Spirit__notes.org#聖靈與基督徒][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

*** 新生
　　對於基督徒生命開始時的重大轉變，即耶穌所喻說的「新生」或「重生」（約三 3—8；另參彼前一 23；雅一 18），一種慣常又真實的說法，是「從靈生的」（6 節）。我前面已經暗示過，在我看來，第五節提及的「水」並非指任何可以補足聖靈內在工作的外在東西。他不是指約翰的施洗或基督徒的洗禮，或如一些人所假定的自然生產時的羊水，而是指到內在更新的潔淨，正如以西結書三十六章二十五至二十七節的意象一樣。（所以在第六節沒有提及水並不產生問題，因為水只不過說明聖靈更新工作的其中一方面而已。）在類似的基礎下，保羅稱這個過程為「重生」（regeneration）（多三 5）和「新造」（new creation）（林後五 17；加六 17），並把他解釋為與基督同死同復活的生命改變（羅六 3—11；西二 12 一 15）。保羅像耶穌一樣，確定基督徒藉著信心能逐漸達致完全。信心的意思是仰望基督，信靠他所流的寶血並寶血所印證赦罪的應許（參羅四16—25，一○8 一 13；西二 12；約三 15—21，五 24，六 47、53—58）。同時，保羅也告訴我們，聖靈吸引我們倚靠和追隨基督（林前一二 3），使我們與基督聯合，成為他教會的肢體，同屬一個身體（13 節）；因此我們藉著信心，可在他的大能之下活出超自然的生命。對相信聖經的人來說，這些都是正確的，都是老生常談。

　　可是，我們對於新生通常過於「主觀」，我說「主觀」的意思並不是個人化（這種情形可能性不大），而是說太內向，把注意力全集中到個別信徒身上，忽略了那位拯救人的基督。這是錯誤的想法，會產生兩個不良的後果。

　　首先，我們腦海中充塞著一種規格式的期望，認為悔改信主必定有某種情感經驗（為罪憂傷、在尋索真理過程中的痛苦掙紮、信主後的極度喜樂等等）。我們從別人的悔改經歷中推論出這種期望。這些經歷很可能自保羅開始，到後來的奥古斯丁（Augustine）、路德（Luther）、本仁（Bunyan）、衛斯理（Wesley），以至我們自己的悔改經驗；然後，我們用這些經歷作為判斷同儕和他人是否真正悔改的準繩。這真是愚昧又可悲！許多悔改經驗，甚至一些很突然而又可追溯日期的經驗（這些經驗可能只屬少數人），可以跟一般標準的期望有極大差異。我們硬要用這種尺度去量度別人，很容易把一些現時滿有悔改特徵的人指為未信者，同時，對於那些曾經一度見證自己有合乎標準悔改經驗的人，雖然現在已不再有那些經驗，我們還是把他們當作是已經悔改信主的。其實，正如清教徒和愛德華滋（Jonathan Edwards）所熟知的，根本沒有一種情感狀況或什麼必然後果，也沒有任何單獨的經驗，可以作為明確的新生指標；我們若憑任何一個指標去思想、判斷，必會產生無數錯誤。惟獨現時就表現出悔改的新生命，才足以讓人有信心去確定一個人以往曾在某一個時候悔改信主。

　　第二個不長後果，就是在我們的福音資訊中，基督不是我們所注意的中心，也不是開啟我們生命意義的鑰匙，他只不過是一個形象——有時只是一個模糊不清的形象，我們把他引進來，只不過為了解答我們一些先存以自我為中心的問題（如：我如何找到內心的平安？如何在壓力下找到心靈和思想上的平安？歡欣？喜樂？生活的力量？）。我們並不強調盡忠跟隨耶穌的必要及其中的要求（有些人甚至認為原則上是不應該強調的），因此跟隨耶穌的代價也就沒有人去計算了。結果，我們撒下的福音種子，只收割了一大批還未回轉的人，他們以為可以隨意呼喚耶穌，利用他作為救主和助手，但不承認他為生命的主。同時，亦吸引了一大堆人，他們被資訊中片面的光芒所誤導，以為基督可以保護屬他的人免遇上生命中一切煩惱。第一類人若然沒有完全流失，便成為教會中的枯木。第二類人大受打擊、極度困擾——這是因為他們所期望的，剛好與實際經驗相反。

　　我隨意抄下一份基督教刊物中的見證：「我的丈夫……和我以前是教會裏的青年導師；……我們兩歲半的兒子忽然在意外中溺斃了。我們一直為主而活，從沒有喪失任何親人；我們滿以為可以倖免這類事情。四年來，我過著麻木的生活，不明所以，不接納自己的憤怒，不斷努力表現自己的堅強。我從不向任何人傾訴我的痛苦，終於變得極度沮喪……」使信徒產生這種虛假期望的牧養方式是有問題的，甚至到達殘忍的地步；當困難臨到時，信徒除了咬緊牙關，頑強不屈，就再無其他應付方法了。這些期望到底從哪里來的呢？他們純粹是一廂情願的思想，抑或由外界因素導致？似乎很明顯，我們那種推銷員式以人為中心的福音資訊，一方面大力吹捧基督徒生命的好處，另一方面只避重就輕地談論基督徒的擔子，因而給信主的人固定了一條思想路線。這正是我們需要追溯的問題根源。

　　那麼，我們該怎樣清理現時福音資訊裏過多及有害的主觀成分？最簡潔的答案是：學習緊隨聖靈的引導，直接注目在耶穌基督身上——他是救世的神，是世人的典範、未來的審判者，也是軟弱、貧窮和不可愛者的愛侶；他曾親自背負了十字架，現在要帶領我們走十架的道路。然後，我們就可以打破那所謂標準悔改經驗的舊框框，強調悔改的內涵主要不是某種情感流露，而是個人對基督全然委身。同時，我們可以改變我們一貫的習慣，不再將悔改經驗抽離，作為判別信仰真偽的特徵，轉而以目前悔改生命的流露作為曾否悔改的唯一明證。再者，我們可以修正那不虔不敬的觀念，不再以耶穌為可供我們利用的一位救主，改為強調耶穌是道成肉身的神，我們必須以讚美和事奉來敬拜他。
　　
　　還有，我們可以矯正從前以為基督徒生命是一帆風順、鳥語花香的錯誤觀念。如巴斯特（Richard Baxter）所言：
　　基督領我經過的黑暗之地， 絕不比他自己曾走過的幽暗。

　　我們應該強調基督的道路是經過死亡再經歷復活的路。我們必須知道，他經常引領我們走上這一條相同的道路，即使他的形式或許千變萬化。

　　最後，我們可以矯正一般關於基督徒委身的含糊觀念。在我們的讀經生活裏，強調經常默想四福音書，甚於其他經文，因為研讀福音書可以幫助我們對主有清晰的觀念，並在思想裏掌握到作為他門徒的意義。其實，有關門徒實踐的教義，在書信裏寫得最清楚；但門徒實踐的性質，卻在福音書裏有最傳神的描繪。有些基督徒重視新約書信過於福音書，他們說從福音書的研習中畢業後，就可進入新約書信的研習，仿佛這就是屬靈成長的標誌；但事實上這種態度是十分惡劣的，他意味著我們著重神學觀念多於與主耶穌個人的相交。其實，我們應該把新約書信的神學思想視為一種裝備，好叫我們更瞭解福音書中基督與門徒的關係。讓我們不要忘記一般人慣常的說法，也是真確的說法：四福音書是世界上最奇妙的書。

　　有一件事是清楚肯定的，若我們能完成上述所有矯正和修改，那將是極大收穫。

[[Keep_in_Step_With_the_Spirit__notes.org#新生][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

*** 認識神及愛神
　　某些有關基督徒生命的真理，是眾多以聖經為信仰根據的基督徒所共知的。舉例來說，每個信主的人都領受聖靈（徒二 38；加三 2），這是大家熟知的真理。所以，那賜下給我們的聖靈，是一個「印記」——表示信徒屬於神（林後一 22；弗一 13）。從此以後，聖靈居住在他或他裏面（羅八 ll）：亦即是說，他好像一個長期住客，關往及投入我們生命和心靈中的大小事情。他擔當了「仁慈和甘心樂意的住客」角色，成為一股改變的力量，使我們更新，與耶穌的德性相似，「……榮上加榮……」（林後三 18）。這裏沒有什麼是新鮮的，全都是一般標準的教導。

　　成聖是一個形容改變過程的常用詞。從我們的觀點來看，成聖之道就是「順著聖靈而行」（加五 16），意思是拒絕隨從「肉體的情欲」（肉體和心思上罪性的欲望），讓聖靈在我們裏面結出他的「果子」，就是那九項與基督相似的特質（加五 22、23）。構成成聖生命的另一方法是效法基督的謙卑、愛心，遠避罪惡和實踐公義（約一三 12—15、34、35，一五 12、13；弗五 l、2；腓二 5—8；彼前二 21—25；來一二 l— 4）。耶穌重複地指出成聖就是遵行他的話語；他總結這種取悅神的生命，就是愛神和愛鄰舍（可一二 29—31；路一○25—37）。總言之，在福音信仰基督徒中間，這是早已清楚定下的真理基礎。

　　可是，當我們思想到屬靈生命經驗層次（有別於認罪、意志及管教層面）的問題時，這又完全是另一回事。關於這方面，我們好像走進了一個陌生的國土一樣，大部分福音信仰人土都感到不知所措。對於直接體會神的大能和良善、他的永恆和無窮盡、他的真理、慈愛、榮耀，並所有關乎基督又藉基督賜給我們的一切，我們從前的瞭解比今天豐富得多。這是我們需要重新學習的。這種種體會源於對聖經的瞭解，必須按聖經的標準去判斷，以聖經的神學思想去解釋。然而，這些體會本身是即時的，並獨立自主的，他們並不受制於我們，我們不可強求或預知這些經驗，他們純粹出於神的心意。這些體會通常透過聖靈賜下，賜給有愛心又肯順服的門徒，為要成就基督的應許，就是父和子要到這人那裏去，與他同住，並且向他顯現（約一四 18、20—23）。這些體會（這種說法比較說「這些經驗」為佳；固然，每一種體會確是「一次經驗」）帶來極大喜樂，因為信徒藉此經歷神的大愛。他們屬於內心世界，有別於我們認識人和事的外在知覺。雖然許多時候，我們對神的種種體會是從我們對人和事的知識而來，即使不一定在領受知識那一刻產生，也會在追憶回想的時候產生，但這些體會必須與一般人和事的知識區分出來。任何一種觀念，若認為認識神就是自我意識的下降或消失，都會混淆人的思想，應當加以排斥。

　　但這種混淆的思想俯拾皆是，結果，任何人嘗試重新強調基督教可經驗的一面，都遭受偏見的反對。我現在談論的與神相交，常被人誤解，以為與印度教聖人的所謂神秘主義沒有什麼分別；這些印度教聖人是泛神觀的，對他們來說，自我意識其實是幻覺，超越甚或消滅自我意識，就是修行的最高目標。很明顯，基督徒若追求印度教的目標，縱未算叛教，實際上已是異端。那麼，為什麼現在或過去一些熱心的密契主義信徒，會被懷疑是追隨印度教的目標呢？似乎引起這誤解的，是他們所用的字彙。在我的瞭解中，最吊詭的真相是由於他們運用一些言語，使他們遭受嫌疑；這些由衷自發，藉以表達他們對神的醒悟和回應的言語，往往是一些表達兩性之愛的言語，但其實這是最恰切的言語，因為男女的愛最能比喻神期望我們與他建立的親密關係。事實上，人間的愛無非幫助在愛中的人達致這更深遠的境界。在愛的經驗裏，不論是屬天或人間的愛情，當事人都有很強烈的自我意識；然而，在兩性之愛的關係裏，自我意識的最高境界就是看見自己成為對方的一部分，以致二人成為一個新的個體（可能就是創二 24 中「一體」的含意）。莎士比亞曾表達這種感覺：「在愛裏，數字已死！」2；又如華格納（Wagner）
所述：

　　崔斯坦：你是崔斯坦。我是易梭德——已不再是崔斯坦了。
　　易梭德：你是易梭德。我是崔斯坦——已不再是易梭德了。
　　雨人（齊）：去掉所有名字（Ohne Nennen）……誓盟我倆永永遠遠是一個……

　　這種愛的相交，就是在交感共鳴中，使個人的獨特性得以提升，而不是失去個性。

　　一些熱心愛主的基督徒，也採用相類似愛的言語——即是「二人成為一體」……等言詞——去表達愛神和被神所愛。有時候，他們這種言語就被指為跟隨印度教思想的證據。可是，這都是胡說八道。印度教裏，根本沒有一位有位格的神，神與「我」之間也沒有「彼此」之分，我們不能享有與神在愛裏的相交；至於獨立的自我（正如我上述所言），在印度教思想裏更是一種必須驅除的幻覺。雖然基督徒永遠有別于天父與聖子，而信徒只不過是區區一個受造物，卻在神救贖的愛中，永遠與他相連。這是自我意識的提升，意識到所領受的愛和對愛的回應，這正是與神合一的境界，可見基督教信仰跟印度教思想相去甚遠。任何小心研究基督教神秘屬靈經驗的人，都會很快發現這是真確的。 可是，今天的人對這種描述與神相交的言語還存有很大的偏見，一日這種偏見未能摒棄，一日我們也不易明白這屬靈的真相。

　　此外，還有另一個原因導致今天信徒甚少在經驗層面上真實認識神。現代那種都市化、機械化、集體化和世俗化生活的步伐，使人很難享有任何精神生活（除了存在主義所說那種不能適應社會環境的人的焦慮，和劇烈競爭中失敗者的創傷）。在這個奔跑飛馳、不容片刻喘息的世界裏，要把禱告放在生命的首位，像從前無數基督徒在修道院內外所做的一樣，實在難似登天。你若嘗試過這種生活，一定會被同輩視為反常。在今時今日，參與一連串程式化的活動才「合」潮流，昔日那種沉思安靜的生活理想，是「老套脫節」的。近期信徒對清教徒強調經驗的著作，和莫頓（Thomas Merton）等人所闡述禱告中潛心默想的傳統，再度燃起興趣，可見今天的人其實普遍渴求一種與神更親密、更溫暖和感情更深的相交。然而在大部分人的觀念裏，基督徒生活仍是一種在奔忙喧鬧中分別為聖的生活，結果，基督徒聖潔生活的經驗層面，就好像一本塵封的書，被束之高閣。

　　雖然二十世紀人物，如懷特（Alexander Whyte）和陶恕（A．W．Tozer），非常重視與神經驗上的相交，並旁徵博引有這方面著述的作者，而且一些偉大的清教徒，尤其是後期才勃起的清教徒愛德華滋（Jonathan Edwards），以及衛斯理的繼承人博勒徹爾（John Fletcher），對於這方面都有經典的著作；5 但是這個時代的福音派信徒卻對這些思想敬而遠之。引致這種態度有下列原因：一些闡述這方面主題的人（如霍士［George Fox］〃波艾微［Jacob Boehme］和佈雷克「William Blake」）看起來不合正統，或至少漠視教義；這些思想有時大開中門，引進盲信和反律法的態度；這些經驗被視為反知識的；他們被視為羅馬天主教獨有的觀念，所以很可能是不良的思想；福音信仰的靈修生活，著重透過聖經經文及在聖經經文中聽取神的話語，任何不同的方式都被認為值得懷疑。不管基於什麼原因，結果就是，對於從直接經驗意識到神使人成聖這方面，今天大多數人都沒有什麼可以分享。我們已很少聽見人說聖靈是「恩膏」，並且藉著他，信徒可以肯定使徒所宣講的耶穌基督是真實的（約壹二 27，也參看 20 節）；也很少聽見人說聖靈是作見證的，使信徒確信他們是藉著基督並與基督同為神的後嗣（羅八 15—17；加四 6）。我們似乎也不能解釋聖靈在何種意義上是信徒繼承屬天生命（林後一 22；弗一 14）的憑據——即是訂金，是保證可得其餘「初熟的果子」（羅八 23）的首期付款。我們似乎對於在聖靈裏禱告（弗六 18；猶 20）和聖靈的愛（西一 8；羅一五 30）並沒有更清晰的瞭解。事實上，這些都是目前所缺乏談論的事情，大家都在這些主題上極度沉默。事情顯而易見，今天以聖經為信仰根據的基督徒，無論他們在其他各方面怎樣剛強，內在的生命卻十分軟弱。

　　要在這裏圓滿地處理這些主題，即使我有這個能力，也是絕不可能的。現在，我僅能做的，是記下我心中所確信的，就是那能啟導我們領悟內在生命的鑰匙，亦即是約翰福音十六章十四節所詳述的聖靈的工作：使耶穌基督，我們那位被釘、復活、統治萬物的救主，時刻成為我們的榮耀，是我們真實經歷得到的。

[[Keep_in_Step_With_the_Spirit__notes.org#認識神及愛神][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 恩膏_見證_憑據
　　約翰駁斥諾斯底派對耶穌的不信時所指出的，正是聖靈這方面的職事。他宣告「從主所受的恩膏……在凡事上教訓你們」（「凡事」是指一切關於耶穌和他的榮耀的事），引導我們「住在他裏面」意思是我們不單只真心承認他，更作他門徒，與這位永活的主建立關係）。約翰稱聖靈為「見證」，文義直譯是「那見證者」（三位見證的首位；其實第二及第三位是「水和血」，即耶穌的受洗和死亡），是指聖靈的職事：幫助我們肯定使徒所傳揚的基督是真實和屬於我們的（約壹五 7、8）。奥古斯丁（Augustine）、伯爾納（Bernard）、路德、加爾文、歐文（Owen）、懷特菲（Whitefield）、司布真（Spurgeon）和其他許多人，包括無數聖詩作者，他們懷著驚人的確信、充滿信心的態度，洋溢著狂喜之情，不斷頌贊推崇主耶穌；我認為這些都是聖靈所結的果子。我相信所有讓聖靈在生命中完成他的職事的人，都會像他們那樣稱頌基督。若沒有神所賜這種對新約基督的確信，沒有按神的教導，以信心、愛、順服和敬拜的心恒常住在基督裏面，就活不出真正的基督徒生命來，也不能擁有真實的成聖生命——因為若缺乏了這一切，根本就沒有新生。

　　同時，聖靈見證信徒成為神的後嗣（羅八 15 一 17），是先讓我們認識基督曾降臨世上，愛我們，為我們死，現今他在榮耀裏愛我們，為我們活著，成為我們的中保；他永恆的生命保證我們與他一起住在永恆的榮耀裏。聖靈使我們看見基督在十架上為我們犧牲的愛，又讓我們領會天父為我們捨棄獨生兒子的大愛（羅八 32）。這條思路出於羅馬書五章五至八節，聖靈一次又一次引導我們循著這路線去思想，「……神的愛……澆灌在我們心裏……」

　　同時，聖靈也幫助我們看見我們藉著基督、在基督裏，並且與基督一起，現已成為神的兒女；他引導我們的思想，使我們自發地、本能地——因為我們內心有屬靈的本能及自然的本能——以神為我們的父，又這樣稱呼他（羅八 15；加四 6）。保羅兩次稱呼神為阿爸，都是為了強調這種親密的關係和對神的信任，因為阿爸是一個完全不拘禮節的稱呼，是耶穌慣常用來稱呼神的，在舊約時代從來沒有人在禱告中這樣稱呼神；這個稱呼相等于阿蘭文的「爹爹」。

　　知道神是你的父親，他對你這個義子的愛不下於對他獨生兒子的愛，又知道神應許讓你永享他的愛和榮耀，由這些認識所帶來內心的喜樂，有時候簡直洶湧澎湃；這也是聖靈的工作。保羅在羅馬書十四章十七節中用來界定神的國的「聖靈中的喜樂」，正是羅馬書五章十一節所說的「以神為樂」；這種喜樂是透過聖靈見證神的愛所帶給我們的。

　　我應該補充一句，聖靈的見證並非尋常的「一次經驗」，一如性高潮、震驚、迷惘、陶醉于大自然成音樂的美感中，或品嘗咖喱等經驗——這些經驗在我們的意識流裏是有時間性的、可銘記的，能從之前和之後發生的事情中分別出來，是比較短暫的。固然，在一些「經驗」中，聖靈的見證會忽然變得十分強烈。巴斯噶（ Blaise Pascal）著名的經驗就是一個例子。他在一六五四年十一月二十三日的記錄中，這樣開始：

　　晚上十時半至十二時半如火挑旺
　　是亞伯拉罕的神、以撒的神、雅各的神，
　　不是哲學家和學者的神。
　　確實無疑。確實無疑（確信）。
　　感覺（感情）。喜樂。平安。

　　約翰·衛斯理也有同樣著名的經驗。一七三八年五月二十四日，他「非常不願意地走向柯達士己街（AldersgateStreet）一個社團去，那裏有人在誦讀路德為羅馬書寫的序言。大約八時四十五分，誦讀的內容描述到神藉著人在基督裏的信心改變人的心靈，就在那一刻，我感到心裏異常溫暖。我感覺我確是信靠基督，並相信惟獨基督能給我拯救；接著我獲得一個確據，他已經除去我的罪，救我脫離罪惡和死亡的律法。」這些「經驗」只不過要加強每個信徒自起初信主時已有的真實經驗。保羅用現在式去講述聖靈的見證（「聖靈與我們的心同證（testifies）我們是神的兒女」「羅八 16」），意味著聖靈持續不斷地運行，賜我們對神恒久的信心。雖然這份信心不是時時刻刻都能強烈地感受得到，雖然他時不時會受到疑惑和失望所動搖，但這信心始終屹立不倒，至終不能被摧毀，因為有聖靈親自保守！

　　同時，那賜下的聖靈是我們得承產業的「憑據」。我的意思是：聖靈透過幫助我們看見基督的榮耀，和幫助我們活出與基督相交的生命，以他為我們的中保，又與父相交，領我們體驗屬天生命最深入的本質。把天堂看為一個地方和一個境界是不會錯的，因為聖經的作者也是這樣說；然而，什麼使天堂成為天堂呢？我們應該怎樣想像天堂呢？答案就是能與父和子在那裏建立真實完美的關係。聖靈今日對我們的職事，是指向這最終完美目標的首期付款。天堂的真正定義，就是看見神，永遠與基督在一起，以致愈來愈深入經驗與聖父及聖子愛的關係（參太五 8；林後五 6 一 8；提前四 7；啟二二 3—5）。藉著聖靈在我們裏面的工作，我們開始體驗天堂的滋味，一如藉著基督並在基督裏面，我們也承受他復活了的生命。保羅寫信給信徒說：「你們已經死了，你們的生命與基督一同藏在神裏面。」（西三 3，參二 11—14；羅六 3—11；弗二 1— 7）這「生命」是永恆的生命，是屬天的生命，不在其他地方，就在此時此地開始。

　　同時，我認為在聖靈裏禱告包含四個要素。首先，這禱告是尋求、宣告，和藉基督來到神面前（弗二 18）。然後，基督徒表達他對神的愛慕和感謝，因為他藉著基督得到神的接納，又因為深知道藉著基督他的禱告得蒙垂聽。第三，他祈求聖靈幫助他能看見並彰顯基督的榮耀，知道當他為自己的生命掙紮祈求要走在正路上時，聖靈和基督正為他代求（羅八 26、27、34）。最後，聖靈引導信徒以持續、專一單純的注意力和強烈的願望去專注神及他在基督裏的榮耀；這是從來沒有人知道的，都是出於一種超自然的力量。

　　在聖靈裏的禱告是從心靈發出的，源自對神、對自我、對他人、對周遭需要和對基督的醒覺。不管這禱告是用言語表達，如聖經記載的禱文和讚頌，或者是在愛中無言地沉思注視神，又或者透過聖靈賜下的方言，這些都不重要。凡藉著基督在心靈裏尋求神的，就是在聖靈裏禱告。

　　至於在聖靈裏的愛，無疑是因著認識聖父賜下獨生子，以及聖子獻上自己來拯救我們的愛，激發我們對神的感謝和對人的愛顧。在聖靈裏的愛，就是效法神的愛，是一種自我犧牲精神，經常願意為別人的緣故放下及捨棄自己生命裏的某些東西（參約一五12、13）。保羅在哥林多前書十三章四至七節勾畫出這個愛的輪廓。這愛的中心是對人友愛的利他主義，並且渴望看見別人變得偉大、善良、聖潔和快樂。在這個沉倫的世界中，這種感情是不可思議的，他本身完全是超自然的。愛（agape）是新約常用的字彙，在基督教出現之前，這個字還沒有上述的意思；這不足為奇，因為惟有透過基督，這愛才顯明出來。現在，在眾多自稱認識神的人當中，愛（agape）成為那些真實認識神的人的標記（約壹三 14—16，四 7—11）。

　　這愛不是天賦或自然發展，而是聖靈的超自然果子（參加五 22）：聖靈幫助人看見和認識神的愛，人心裏便生出這種愛來。

[[Keep_in_Step_With_the_Spirit__notes.org#恩膏_見證_憑據][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 內心之旅
　　我希望可以徹底討論這方面的事情（在以上的篇幅裏我當然未能做到），但我必須停下來，只能在這裏提供最後的評論。我們生命的旅程是雙線的旅程。一方面，這旅程是向外的，我們面對外來的衝擊，不斷有新發現，並建立各種關係；另一方面，這旅程是向內的，我們達致自我認識，尋求自我的表現、抱負的實現、自由和心靈的滿足。對基督徒而言，向外的旅程，是為創造主的緣故，學習如何積極及有意義地與世界和別人——亦即是神所創造的萬物——相處；而內心的旅程，是與神及聖子耶穌建立關係，並在這種關係上進深。

　　今天，在奔忙喧囂的西方社會，人的生活變得極度不平衡，教育、商業利益、傳播媒介、知識的爆炸，和我們社會所強調的積極進取精神，這些合起來都驅使人往向外的旅程進發，而且匆匆賓士，因而分散了人對內心旅程的關住。西方基督教的情況也一樣。今天我們大部分人都不知不覺地變成了不平衡的活躍分子，很不幸地追隨了世界的樣式。我們像法利賽人一樣，非常活躍（參太二三 15），像他們變得嚴厲、律法主義、墨守成規，過著忙碌、自滿的生活，關心活動程式尤甚於關心人。我們指責商人為他們的公司出賣靈魂，把他們的人格犧牲在機構的祭壇上；其實，我們不過是五十步笑百步。有關聖靈的真理，今天基督徒最急需學習的，也許再沒有比學習如何在內裏的生命與神相交更為迫切了。我稱這生命為內心旅程。（你亦可以稱之為向上的旅程——這個形容詞同樣適切。）

　　現在你明白我為什麼不可以繼續這個題目的討論了。不過，目前還有其他方面的事情是我必須指出的。

[[Keep_in_Step_With_the_Spirit__notes.org#內心之旅][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 屬靈恩賜
　　在第一章裏，我討論過一些關於屬靈恩賜的問題，在這裏我們需要更詳盡地探討這問題。

　　保羅強調屬靈恩賜是惠及所有基督徒的，因此基督身體裏的總動員事奉應該成為各教會的法則；近年來，這種思想普遍被接受了，我們應該為此高興。千多年來，大多數教會陷入教權主義的掌握中（衛理公會團體、普利茅斯弟兄會和救世軍等受人尊敬的組織除外），總動員事奉的思想是向好的一大轉變。雖然今天很多教會的平信徒仍處於被動狀態，許多神職人員仍舊助長這種狀況，因為他們害怕受到其他思想的威脅，然而這主流見解已經轉移，從前平信徒的事奉只屬於那些特別熱心的信徒，現在，平信徒事奉成為實踐門徒生命一個必需的部分。從前向信徒發出挑戰，要他們認識自己的恩賜和尋找自己事奉的職事，似乎只是屬於虔誠的抗辯宗溫室裏栽培出來的奇花異卉；但這種觀念現已轉變了。羅馬書十二章三至十三節、哥林多前書十二章和以弗所書四章七至十五節等經文中的有力論點，現在已普遍被接受了；今時今日，天主教與抗辯宗、自由派與保守派、靈恩派、普世派和各宗派的福音派信徒，均一致贊成每個基督徒都擁有恩賜，在教會整體的事奉裏各有自己的責任。這真是好消息啊！

[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

*** 什麼是屬靈恩賜
　　可是，我們對恩賜的想法十分膚淺。不錯，我們說恩賜從聖靈而來（保羅稱之為「聖靈的彰顯」，見林前一二 4—11）然而我們仍舊認為恩賜是「才幹」（即能夠運用純熟技巧，將事情辦得圓滿妥當的能力），或者是超自然的新穎技倆（說方言、醫治、直接從神領受資訊以傳給別人等等能力）。我們尚未習慣以教會的元首基督及他目前從天上在我們當中進行的工作來給恩賜下定義；就這方面看來，我們還沒有按著聖經真理去思想恩賜的問題。保羅在哥林多前書的開始，為信徒感謝神：「……因神在基督耶穌裏所賜給你們的恩惠；又因你們在他裏面凡事富足，口才、知識都全備，……以致你們在恩賜上（charisma ）沒有一樣不及人的……」林前一 4、5、7）保羅的話明確指出恩賜是在基督裏所賜的，是從基督而來的富足。哥林多前書十二章所論述的，是假設讀者已肯定了第一章四至七節所確立以基督為本的觀點。我們先看清楚這一點是很重要的，否則，我們就會把天生才幹與屬靈恩賜混淆，始終分不清。

　　保羅或其他新約聖經作者，都沒有為我們界定何謂屬靈恩賜，但保羅聲稱運用恩賜能使人得著造就（即「建立」，林前一四 3—5、12、26，另參一七章；弗四 12、16），這正好反映出他對恩賜的看法。對保羅而言，只有藉著基督、在基督裏、效法基督及回應基督，人方可得著造就。「造就」一詞的意義傳到後世變得較為通俗，比保羅的原意寬鬆得多；在保羅看來，造就是對基督並與他有關的各方面有愈來愈深入和豐富的認識，而個人與他的關係更漸趨完美；除此以外再無別的含義了。因此，我們給屬靈恩賜下的定義，必須以基督為根據：是某些能力的具體表現，藉行動或言語去表達、頌贊、展現及傳揚基督；在此以外再沒有造就可言。

[[Keep_in_Step_With_the_Spirit__notes.org#什麼是屬靈恩賜][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

*** 屬靈恩賜的運用
　　我們應當留意，一般來說，我們時常將「尋常」與「不尋常」的恩賜，或「自然」與「超自然」的恩賜作含糊不清的劃分，但在這兩組恩賜之上，還有更進一步的劃分：語言的恩賜及樂善好施的恩賜（即對他人肉身和物質上的需要作出友愛的幫助）。在羅馬書十二章六至八節裏，保羅談論恩賜時，在這兩類恩賜之間跳來跳去。他列舉的恩賜中，第—、第三和第四項，是關於說預言、教導及勸慰，屬於言語的恩賜；而第二、第五、第六和第七項，是關於服事（diakonia）、將財物分贈、領導和行善，都屬於樂善好施的恩賜。縱使這兩類恩賜在形式上極不相同，但從保羅的表達方式看來，我們應該曉得，對保羅來說兩者並沒有終極的神學分歧。

　　在這裏，我們必須掌握一個真理，我們運用屬靈恩賜，無非是基督藉著他的身體去事奉他的身體，事奉天父，事奉全人類。基督從天上使用基督徒作為他的嘴、他的手、他的腳，甚至他的笑容；他藉著我們——他的子民——此時在世上說話、行動、與人相會、去愛和拯救人。這似乎是（雖然有人持不同意見）保羅對教會作為基督身體的描繪的部分意義。在這個身體裏，信徒是肢體，即四肢或器官：頭是全身的指揮中心，肢體隨從頭的指揮行動。

　　保羅對以弗所教會及其他地方的信徒這樣寫道：「（基督）來傳和平的福音給你們遠處的人……」（弗二 17；我認為以弗所書是一封傳閱的書信，以弗所教會是其中一個傳閱的目的地。）基督怎可以這樣做呢？他並非靠自己複後的身體去做，而是靠著像保羅這些信徒運用他賜予他們講道和教導的恩賜。同樣，保羅給腓立比信徒寫道：「我的神必照他榮耀的豐富，在基督耶穌裏，使你們一切所需用的都充足。」（腓四 19）神又怎可以這樣做呢？至少，有部分是藉著基督透過聖靈工作，賜予腓立比信徒樂善好施的恩賜。信徒奉基督的名彼此教導（參帖後三 6），也因著他們是基督徒而彼此關懷（參可九 41），這樣，基督便透過他們親自賜下祝福。對於關懷的實踐，基督曾經明確地指出：「……這些事你們既作在我這弟兄中一個最小的身上，就是作在我身上了。」（太二五 40）因此我們或可以同樣明確地表示，若其他基督徒給我們諒解和鼓勵，在我們有需要的時候幫助我們，無論採用什麼形式，其實都是基督親自工作，透過他們帶給我們這些益處（參林後一三 3；羅一五 18）。

[[Keep_in_Step_With_the_Spirit__notes.org#屬靈恩賜的運用][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

*** 恩賜帶來的祝福
　　我給恩賜（chartsmata）的定義，是表彰基督的能力表現。以某種獨特方式去講或做的能力——我們或許稱之為「表現」的能力——並不是恩賜，惟有那些被神使用去造就信徒的能力，才稱得上是恩賜。有時候，神永不會使用一些與生俱來的才幹去造就人，但有時神又偏會使用一些被人判斷為不及水準的表現去造就人。這是一貫的特色：神顯明他所拯救和使用的人的軟弱，不讓任何東西勝過或遮蓋他的榮耀（林前一 27 一 29；林後四 7，另參一二 9）。因此，當我們說基督徒有恩賜時（羅一二 6），意思並不是說他們在什麼方面顯赫出眾或很有效率（或許是，或許不是，各人表現都不同），而是神已經很明顯地使用他們某方面的能力來造就人。這使我們確信他將來也會繼續這樣使用他們。我們需要把人辦事的能力和神賜福的特權清楚劃分，因為構成恩賜的，是我們的才能被神使用，而不是才能本身。若然我們所作的不能經常為他人或自己帶來可辨認的屬靈益處，我們便不要將自己處事的能力誤以為屬靈恩賜。

　　最初司布真教牧學院（C．H．Spurgeons PastorsCollege）的入學手續就採納了這項原則，候取生需要提供資料，證明他們曾經擔任講道和教導的工作，並曾使人蒙福；若缺乏這些證據，儘管申請人有多大的才能，都會被視為缺乏牧者恩賜，而拒絕接受申請。

　　五旬節派及靈恩派信徒宣稱神在他們當中重新興起新約時代的所謂表記恩賜（sign gifts；如說方言、翻方言、說預言和醫治）。我稍後將會在本書討論到我為什麼不接受這樣的宣稱；但現在即使假設我的觀點錯誤，他們的說法真確，我的原則仍舊適用，一如適用於有教導和行政技巧的基督徒身上。說方言及按手治病的能力，很可能在教會內外都同樣找到——我想事實上確是如此；這些能力不一定是屬靈恩賜，因為你不可以單單憑表現來界定恩賜（charisma），恩賜的定義必需包括神與人的關係，神在基督裏透過恩賜建立信徒；否則，即使所謂「恩賜」在形式上與真正屬靈能力的彰顯一模一樣，也只能算是屬肉體而不是屬靈能力的彰顯。有些從前是五旬節派或靈恩派的信徒告訴我們，他們發現以往說方言的能力是屬肉體的，我們大可同意他們的體會，而無需下結論評定所有說方言的恩賜都是如此。那構成及界定什麼是「恩賜」（charisma）的，並非行動的形式，而是神的賜福。

[[Keep_in_Step_With_the_Spirit__notes.org#恩賜帶來的祝福][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 五旬節的意義
　　現在，我們可以精確地回答一個引起眾說紛紜的問題，就是使徒行傳二章所記載的五旬節聖靈降臨究竟有什麼意義。

　　使徒行傳所載是不是聖靈第一次在這世上顯現呢？很明顯，答案是否定的。在舊約時代，我們已經見過聖靈的一些活動，及至耶穌在世上的生平和事奉，也有很多有關聖靈工作的記載。耶穌向門徒宣佈那位保惠師（或訓慰師）要來時，他說：「……真理的聖靈，乃世人不能接受的；」接著他補充道：「你們卻認識他，因他常與你們同在……」（約一四 17）。「你們……認識」（you know）和「他常與你們同在」（hedwells）兩句採用現在式，是符合語言習慣的，意思是所述的情況在不久將來即會發生（約翰在其他地方亦有採用現在式來表達即將發生的事）；但同時，耶穌的意思也可以是（事實這可能性更大）「你們已經認識聖靈（雖然你可能未必知道你已經認識他），因為他在此時此地已與你們同在，正如他與我同在一樣。」試看句中時式和介詞的強烈對比（「他常與你們同在「dwells with you」，也要在你們裏面「wi11 be in you」。」，除上述推想外，再難找到更滿意的解釋了；而且，在約翰的記載裏，他經常強調的，是耶穌在世的一生中有聖靈常在他裏面，並與他同在。耶穌是由聖靈感孕的（太一18、20；路一 35）。耶穌受洗時，聖靈彷佛鴿子降在他身上，表明他是神的受膏者，被聖靈充滿（太三 16；可一 10；路三 21、22，另參四 l、14；徒一○38；約一 32—34，另參六 27，這裏很有可能是指到洗禮中受膏的印記，及三 34「……神賜聖靈給他，是沒有限量的。」）。耶穌「被聖靈引到曠野中」受試探，經受嚴峻的考驗（參路四 1；太四1；可一 12）；他靠聖靈的能力傳道（路四 18），靠著聖靈趕鬼（太一二 28）；他「……被聖靈感動就歡樂……」（路一○21）；「基督藉著永遠的靈……」，將自己獻與神，在十字架上作無瑕無疵的祭（來九 14）；「……按著靈性說，他復活了」（彼前三18）；他在升天之前，「藉著聖靈」吩咐門徒往天下去（徒一 2）。所以，道成肉身的神子是「屬靈人」的理想典型——關於這一點我們是無可置疑的！因此，這裏表達的是五旬節前聖靈職事的其中一方面。

[[Keep_in_Step_With_the_Spirit__notes.org#五旬節的意義][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

*** 惹起爭論的經文_約翰福音二十章二十二節
　　約翰的一個中心思想是被聖靈充滿者也同是賜予聖靈者，即是「用聖靈施洗」又「差」聖靈到門徒那裏去的那一位（約一 32，一五 26，一六 7）。約翰記載了耶穌在復活當天首次在耶路撒冷向門徒顯現的時候，如何把使命託付門徒——「……父怎樣差遣了我，我也照樣差遣你們」——，然後立即「……向他們吹一口氣，說：『你們受聖靈』。」（約二○21、22）耶穌清脆俐落地由肺裏向他們吹一口氣，有人極力認為這就是賜下聖靈給門徒，叫他們開始新生的時刻；但這種論調不可能成立，原因有三：

　　首先，耶穌說過：「……你們是乾淨的……」（約一三 10，一五 3）意味著在耶穌受難之前，他們的新生命已經開始。耶穌與尼哥底母論重生時，說到重生的人是「從水和聖靈生的」　（約三 5），正如我們已經討論過，「乾淨」（純潔，因為罪咎和罪汙已經被洗淨、清除）可說是耶穌對重生的一半描寫。耶穌所說的，其實是間接地（也許並不這樣間接）邀請尼哥底母接受信仰（尼哥底母似乎有回應了「參約七 50，一九39」），而耶穌的整個教訓清楚告訴我們，沒有重生就沒有信仰，正如沒有信仰就不能重生一樣。故此，在耶穌三年的事奉中，所有信他的人，包括被揀選的十二個門徒中的十一個，全部都重生了。

　　第二，按上下文去理解，耶穌呼氣之舉並非與重生相關，而是相連於他剛授予他們的使命（「我差遣你們」），以及他隨即賜下的應許，就是賦予他們智慧和權能去應用福音（「你們赦免誰的罪，誰的罪就赦免了；你們留下誰的罪，誰的罪就留下了。」「約二○23」）。很明顯，耶穌向門徒吹氣，叫他們接受聖靈，是為了裝備他們作傳福音及牧養教會的事工。

　　第三，耶穌在他得著榮耀之後，才賜下聖靈；得榮耀的意思是「升天、被高舉、坐在寶座上」。他必須先「到父那裏去」（約一三 l，一四 28，一六 10，一七 11，二○17），回到與父同享榮耀的地方。這榮耀在未有世界以先，他已享有（約一七 5）。然後，他會從父那裏差遣聖靈來（參約一五 26），好讓門徒能看見他的榮耀，而聖靈的工作，就是把他們的救主及君王如今在寶座上享有的榮耀呈現在他們眼前。在約翰福音的較前部分裏，約翰曾強調以下的次序。耶穌說過：「人若渴了，可以到我這裏來喝。信我的人，就如經上所說：『從他腹中要流出活水的江河來。』」（耶穌引述的經文，很明顯是出自以西結書四十七章一至十二節裏有關重建聖殿的異象，耶穌視之為基督徒的預表。）敍述這些之後，約翰自己進一步解釋說：「耶穌這話是指著信他之人要受聖靈說的；那時還沒有賜下聖靈來，因為耶穌尚未得著榮耀。」（約七 37—39）這裏的希臘原文字面意義是「聖靈尚未為聖靈」（“the Spirit Was not yet”），意思是聖靈尚未扮演他即將要擔任的新角色。因此，我們也可以說英國的查理三世和戴安娜皇后尚未存在，雖然他們將來有一天會登位。我並不相信一些學者的講法，他們嘗試說服我們同意約翰的本意是耶穌在復活的黃昏已經得榮耀了；但我的結論是約翰期望我們記得七章三十七至三十九節，而在我們讀二十章二十一至二十三節的時候，我們會從七章推論當時不可能已真正賜下所應許的聖靈。

　　我這個論據不單否定了以約翰福音二十章二十二節為門徒新生開始之說，也否定了另一些人的看法，就是認為約翰的敍述是對路加在使徒行傳二章所描述的五旬節事件的另一寫法，與路加所記的比較，他把聖靈新約的職事推前了四十天。這看法似乎也是錯誤的。

　　因此，對於耶穌向門徒吹氣一事，最合理和最自然的解釋（一如大多數解經家的瞭解），就是以此為一種用行動表達的預言，而他的話（「你們受聖靈」）就是一個應許，表示門徒即將體驗聖靈的新職事，屆時聖靈會裝備他們，使他們能應付新的使命。

[[Keep_in_Step_With_the_Spirit__notes.org#惹起爭論的經文_約翰福音二十章二十二節][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

*** 五旬節的實質
　　那麼，我們該怎樣瞭解四十日後在五旬節早晨發生的事件？我們不應該看狂卷的風聲、降在各人頭上舌頭形狀的火焰、語言的恩賜等為這劃時代事件的實質（這些都是次要的東西，我們可稱之為點綴的飾物）。反之，整件事的實質就是聖靈的新約職事在當天早上九時就開始了，他讓每個門徒清楚瞭解耶穌在神整個計畫裏的位置，使他們強烈地意識到他們的身分和權柄，是在這世上代表耶穌，又賦予他們無限的勇氣，去宣告坐在寶座上的耶穌的權能——我們可從彼得的講章裏發現這些新生的特質。想到他從前是怎麼樣的人，這些改變不禁叫人驚訝。耶穌應許在聖靈降臨以後，門徒必得若能力去為他作見證（徒一 5、8）；路加在他的福音書中亦屢屢描述一個失敗的人物——彼得，顯然想讓我們看見耶穌的應許怎樣應驗在彼得身上，以他作為一個範例。路加也想我們瞭解這在新約裏「所賜的聖靈」——換句話說，是體驗聖靈的新職事，就是聖靈住在主的子民裏面，藉著他們榮耀耶穌——是應許賜給所有悔改、受洗的人的；從他們成為門徒的時候開始，便可得著聖靈（徒二 38，另參一六 31—33）。

　　在撒瑪利亞，神延遲給信徒賜下說方言及預言的恩賜，直等到彼得和約翰到來（徒八 12 一 17）；又在以弗所，十二個門徒受洗後，就得著上述恩賜（徒一九 1—6）。無論我們怎樣看這些事——路加在這些事上並沒有表明態度，更沒有清楚交代自己對這些事情的個人神學觀——貫穿整卷使徒行傳，都便開始了。暫且不說今天還應否繼續追尋五旬節後出現的「表記恩賜」（我們會在本書的另一章再作討論），我們卻可以充滿信心地說，自那歷史性的早晨開始，聖靈就一直積極工作，用各種方法在所有耶穌的跟隨者身上完成約翰福音十四章十四至十六節裏耶穌預言的聖靈職事，並且全卷新納聖經都為這件事歌頌禮贊；事實上，聖靈今天仍在積極工作。

　　一間神學院選院長的規例是這樣的，院長須從教員當中選出，而就任院長以後，要繼續教授他從前的課程。這樣，教員當上院長後，他的責任增加了，但不會失去舊有的職責。同樣，自五旬節開始，聖靈的職事擴大了，但他從前的職事卻絲毫未減。正如我們看到，在五旬節以前，聖靈扶養受造的萬物和眾生，使信徒心靈更新，賜予屬靈的悟性，賜下作領導或其他方面事奉的恩賜；今天聖靈仍舊執行這些職事。五旬節以後，聖靈職事的不同處，就是他作的不再是關乎那將要來臨的基督，這是聖靈對舊約聖徒所作的（這方面的提示見於約八 56—59；林前一○4；來—一 26；彼前一 10）；他的職事也不再系於在地上存活的基督，正如他感動西面和亞拿認出基督時所作的（路二 25—38），並且耶穌在世上公開事奉的三年中，聖靈都已經如此作；如今聖靈的職事是系於那已經來臨，已經受死、復活，在榮耀裏掌權的基督。對於那在神的新紀元中的新境界（就與聖靈有關的範圍來說），我們應該從上述方向去理解，正如我們應該以與基督的相交關係來理解自五旬節以來基督徒享有的新生命一樣。

[[Keep_in_Step_With_the_Spirit__notes.org#五旬節的實質][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

*** 聖靈的洗和聖靈充滿
　　我們經常聽聞一種見解，就是根據使徒行傳二章，認為神要每個基督徒的生命都分成兩個階段或兩個層次，悔改信主以後會有第二次經歷（按徒一 5，稱為聖靈的洗，按徒二 4，稱為被聖靈充滿），這經歷將一個人的屬靈生命提升到更高境界。對於這種見解，我們應該怎樣回應呢？我們應該如此說，雖然個別基督徒需要聖靈「第二次接觸」（還有第三次、第四次和許多次），並且一次又一次地得著這種經歷，但若以為這是神為所有基督徒安排的計畫，那就錯了。神定意所有基督徒從悔改信主那一刻開始，就享有五旬節所賜下的內在祝福（不一定是外在的修飾，而是心靈與基督的密契，並從這種關係湧流出來的一切）。

　　為什麼第一代門徒的屬靈生命可分成兩個階段或兩個層次？唯一的理由是他們在五旬節之前信主，但對於你和我——我們差不多在五旬節後二千年才成為基督徒，所啟示給我們的計畫，是我們一開始就可以完全享受到聖靈的新約職事。在新約裏面，這事已經十分清楚，保羅指出在悔改信主之時，聖靈的洗就發生在哥林多的信徒身上——同樣道理，這事也發生在五旬節之後所有信主的人身上（林前一二 13）。保羅以所有基督徒自悔改信主以後都應該一直實行的生活方式，來形容被聖靈充滿的表現（參弗五 18—21；見希臘原文）。我們若缺乏這種表現，並非因為神不定意如此，只不過（姑勿論我們是否察覺到）是我們消滅了聖靈的感動（參提前五 19）。

　　可以肯定說，基督徒是透過聖靈全面的新約職事而靈命逐漸成長（參弗四 15；提前三 12；提後一 3；彼後三 18），獲得新的屬靈經驗，並加深和豐富了舊的屬靈經驗。但我不打算在這裏詳述屬靈成長這回事。

[[Keep_in_Step_With_the_Spirit__notes.org#聖靈的洗和聖靈充滿][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 聖靈與我們
　　若然這章所述都是正確的話，今天我們提出以下有關聖靈的兩個問題便是錯了。

　　我們會問：你認識聖靈嗎？但我們不應該這樣問；反之，我們應該問：你認識耶穌基督嗎？你對他有足夠的認識嗎？你對他認識透徹嗎？這些問題是聖靈期望我們發問的，因為正如我們前面談過，聖靈總是隱藏自己。他的職事是作為耶穌的泛光燈，以強光將耶穌的榮耀照射在我們屬靈的眼前，又使我們與基督結合。聖靈並不引人注意自己，也不像父和子，直接與我們相交。他的工作和喜樂，在於增進我們與父和子的相交，一方面榮耀子，我們信心的物件，另一方面見證我們藉著子被收納進入父的家裏。

　　一旦我們的興趣從認識子轉移到認識聖靈，就會立刻產生兩種惡劣後果。一方面，我們會像歌羅西拜天使的人一樣，變得貧乏，因為我們「……與元首基督脫了節。（基督是頭，我們都是身體，全身的筋絡必須靠賴他才得連絡維繫，漸漸長大。）」（西二19，當代聖經）另一方面，我們會陷入一個充滿虛謊的「屬靈」感覺和幻想的世界，這個世界與基督完全無關，也與一切真實存在的事物無關，只有撒但欺詐的網羅，及其對真與善無限的歪曲；這條路我們連一步也不要踏上。任何有關聖靈的問題，若脫離了這個最基本的問題——我和所有基督徒（或說世人更為恰當）可以怎樣認識耶穌基督，並且認識他更多？——，都不應該提問。這是聖經加給我們一種思想上的基本自律，若以哥爾夫球作比喻，就是定睛在球上。

　　其次，我們問：你領受了聖靈沒有？我們不應拿這個問題來問基督徒，因為我們知道每一個基督徒自信主那一刻開始，就領受了聖靈。「……人若沒有基督的靈，就不是屬基督的。」（羅八 9）這樣說來，人需要做的不是繼續尋求聖靈，而是憑信心來到基督面前，並且悔改，聖靈就自然會賜下給他了。「你們各人要悔改，奉耶穌基督的名受洗，……就必領受所賜的聖靈；因為這應許［聖靈和赦罪的應許］是給你們，和你們的兒女，並一切在遠方的人，就是主我們神所召來的。」（徒二 38）人只可藉著接受基督去領受聖靈，此外沒有其他方法；假若有人說除了與復活主個人相遇外，還有其他方法可以得著聖靈，使人變得「屬靈」，這簡直是極具破壞性的錯謬觀念。

　　這些都不對，我們應向自己及彼此對問的問題應該是：聖靈有沒有得著你？他是否完全得著你，還是只得著部分的你？你有沒有使他擔憂（參弗四 30）？你是否接受他的引導（參羅八 12—14；加五 18—24）？你是否倚靠他催迫你，幫助你向基督作出回應？你有沒有認真處理這個事實，「……你們的身子就是聖靈的殿嗎？這聖靈是從神而來，住在你們裏頭的……」（林前六 19）你是否尊敬他在你心中的工作，並與他合作，抑或你老是不假思索、粗心大意、毫無自律、放縱自己，以致阻擋聖靈的工作？這裏的問題同樣必須以基督為中心來理解，他們實際上是以不同方式去問同一個問題：你的救主是不是你生命的主？當我們將問題聯繫到聖靈來發問時，問題就更有力、更具體，是其他提問方式所不能有的，因為聖靈住在我們裏面，改變我們，在我們的心靈和思想上不斷工作，領我們接近基督，保守我們與他保持親密的關係。聖靈本身與我們的關係非常密切，他明瞭我們隨時沉溺其中的汙穢思想和行為。用銀幕上影像的投射來作比喻，這就是所謂校正焦點。

　　在以下兩章，我們將以基督徒的聖潔作為我們探討的主題。

[[Keep_in_Step_With_the_Spirit__notes.org#聖靈與我們][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

* 3_聖靈的路徑_聖潔之道
　　不論是好是壞，我們大多數人一聽見「性」這詞都會產生觸電的感覺。我的意思是他迫使我們注意，使我們驚醒，抓住本來勿勿掠過的眼神和輕忽的耳朵；他帶有情感的電荷，給予我們一種情感的衝擊。為何會這樣？因為對於正常的成人來說，性是一個有無窮興味的主題。（你發現自己閱讀這段文章時特別加倍留心，是嗎？這就是我的意思。）

** 基督徒的優先選擇
　　對於健康的基督徒來說，聖潔一詞也同樣令人加倍留神。為什麼？因為神已經在每一個重生的心靈裏，深深種植一份對成聖趨之若渴的情感。成聖意指接近神、像神、委身給神和取悅神，是信徒在世上最希望達到的。他們對聖靈感興趣的一個原因，是因為知道聖靈的主要工作之一是使我們聖潔。基督徒想瞭解和證明聖靈使人成聖的能力，是十分正常和自然的；任何信徒若然對追求聖潔漠不關心，他的信仰很可能出了問題。本章是向一切有心追求聖潔的正常基督徒進言。

　　我們應該知道，「聖潔」是聖經中一個重要的辭彙。他的字根包含分離或隔開的意思；首先，這個詞意味著神跟人分別開來，其次，他標誌著基督徒為神分別出來。這裏，我們所關心的是第二個含義。試參閱以下經文：

　　那召你們的既是聖潔，你們在一切所行的事上也要聖潔；因為經上記著說：「你們要聖潔，因為我是聖潔的。」（彼前一 15、 16，引利一一44、45）

　　神的旨意就是要你們成為聖潔，……神召我們，本不是要我們沾染汙穢，乃是要我們成為聖潔。……願賜平安的神親自使你們全然成聖。又願你們的靈與魂與身子得蒙保守，在我主耶穌基督降臨的時候，完全無可指摘。（帖前四 3、7，五 23）

　　……神從創立世界以前，在基督裏揀選了我們，使我們在他面前成為聖潔，無有瑕疵；……基督愛教會，為教會舍己，要用水藉著道把教會洗淨，成為聖潔，可以獻給自己，作個榮耀的教會，毫無玷污、皺紋等類的病，乃是聖潔沒有瑕疵的。……我們原是他的工作，在基督耶穌裏造成的，為要叫我們行善，就是神所預備叫我們行的。（弗一4，五 25—27，二 10）

　　所以弟兄們，我以神的慈悲勸你們，將身體獻上，當作活祭，是聖潔的，是神所喜悅的；你們如此事奉乃是理所當然的。（羅一二 1）

　　……就當潔淨自己，除去身體、靈魂一切的汙穢，敬畏神，得以成聖。（林後七1）

　　這些經文立刻顯示出聖潔同時是神的禮物和命令；所以，我們應該祈求聖潔，並且每天竭力尋求實踐聖潔的生活。聖潔是我們蒙神揀選與救贖的目標，是神對我們的基本要求，也是神與我們一切交往的目標。

　　我們應該如何界定信徒的聖潔呢？我們也許可以說，一個聖人的聖潔，在於他的生活特質，這特質是他為神的緣故分別為聖，也是他仰賴神的恩典心靈得著更新的外在表現。清教徒歐文（John Owen）以其滔滔雄辯，聲壯氣沉地闡釋這方面的主題，他界定成聖是神改變人的工作，而聖潔就是被神改變了的人的生活方式。以下是一些對我們有幫助的定義，所以我將之全部引錄。歐文這樣寫道：

　　成聖是神的靈直接在信徒的靈裏動工，潔淨他們本來被罪污染的性情，使他們重新恢復神的形象，因而幫助他們能夠按照新約的要旨和條件，藉著耶穌基督的生和死，在神不變的屬靈恩典下，向神投靠順服。……故此，聖潔就是這項工作的果效；這工作本來就定意在我們內裏完成，要在我們內心鑄造出更新的原則或神的形象。所以，依據恩典的約，又因著那新的性情，這工作也包括倚靠耶穌基督，在聖潔生活中順服神。

　　由此觀之，聖潔是聖靈的果子，基督徒順著聖靈而行，就有聖潔表現（加五16、22、25）。聖潔就是與神神聖的親近。聖潔本質上是順服神，向神活著，為神而活，效法神，遵行他的誡命，與他一起對抗罪惡，實踐公義，行各樣善事，追隨耶穌的榜樣和教訓，在聖靈裏敬拜神，因著對基督的尊崇而愛神、愛人、事奉神和人。就與神的關係來說，聖潔是憑著愛、忠誠、摯情和讚美，以專一的熱誠來取悅神；就與罪的關係來說，聖潔是抵擋罪，過著自律的生活，不但不放縱肉體的情欲，更要治死身體的惡行（加五 16；羅八 13）。簡言之，聖潔是受神教導、被聖靈冶煉出酷似基督的氣質；是委身的門徒生命的內涵和總和；是由愛產生信心的表現；是重生者心靈裏的回應，湧流出超然生命的義。這樣的聖潔就是本章的主旨。

** 應優先考慮的事
　　很明顯，追求聖潔理應是基督徒優先考慮的事，但今天這個課題卻普遍被信徒所忽略。噢，這真是太顯而易見了。舉例說，試看看我們那種以人為中心的虔敬觀念。

*** 自我中心的虔敬觀念
　　現代基督徒趨向以尋求滿足感作為他們信仰的目標。我們關心自己理想的實現，尤甚於關心如何取悅神。這趨勢至少在今天以英語為主的西方國家是如此，他們紛紛為信徒大量出版各類教人「怎樣做」的書籍，諸如教我們怎樣達致成功的人際關係、怎樣在性生活中獲得更大樂趣、怎樣能夠成為一個更完全的人、怎樣發揮自我的潛質、怎樣在每天獲得更多興奮和刺激、怎樣減輕體重、怎樣改善我們的飲食習慣、怎樣理財、怎樣使家庭更快樂等等。對於那些一心渴想榮耀神的人來說，這一切關注自是合情合理，可是，這些教人「怎樣做」的書籍，經常以一種專顧自己的態度去探討問題，所關注的主要是我們生命中的享受，而不是神的榮耀。這些書籍只在他們所提供的大眾心理學和普通常識上，薄薄的鋪上一層聖經教訓；可是，他們整體的取向明顯反映出一種自戀心態——即「自我主義」（“selfism”），或有時稱為「唯我主義（“me－ism”）——，這是現代西方世界的一種趨勢。

　　不管這種自我陶醉在心態上如何虔誠，他始終與聖潔背道而馳。聖潔就是指屬神的氣質，而屬神的氣質是根源於以神為中心的生活；那些以為神存在是為了他們的益處，而並非他們的存在是為了讚美神的人，實不配稱為聖潔的人。他們的所謂聖潔，與真正的聖潔截然不同，是一種以自我為中心、不虔不敬的虛假聖潔。

*** 活躍的危機

　　或許，又讓我們看看我們在宗教活動上的活躍。現代基督徒傾向於以忙碌取代他們的宗教。我們羡慕和模仿那些工作狂的基督徒，漸漸自己也成為工作狂，誤以為忙碌的信徒就是最優秀的信徒。無可置疑，愛主的人確會為主忙碌，然而我們忙碌的心態卻往往是錯誤的。我們為神工作，奔跑勞碌，卻連禱告的時間也沒有；然而我們也不因此介懷，因為我們忘記了古諺所雲：若你忙碌得無暇禱告，那你實在是太忙碌了。可是，我們亦不覺得有需要禱告，因為我們在工作上已經變得十分自信和自足了，我們以為憑著我們的技巧、資源和優質的活動程式，一定會結出果子來。我們忘記我們若離開了基督——意指沒有信靠、順服、仰望、靠賴基督——，我們什麼都不能（參約一五 5）。我們一味活躍：我們的活動變得徒勞，因為沒有恆常意識到自己的不可靠，也沒有對神全然信靠。然而活躍不等於聖潔，也非聖潔的果子。活躍分子一心只牽掛著他的計畫、安排、策略和技巧，忽略了追求聖潔，或在成聖道路上長進。

　　可惜，似乎我們所有人都染上了活躍分子的精神。舉例說，當我們思想到牧者的角色和考慮揀選適合的人來牧養教會時，我們往往重視那人牧會的技巧過於他的聖潔，重視那人的活力過於他的熱誠，就好像我們並不知道事奉的能力來自事奉背後的那個人，而不是那人所能做的某些事情。或許我們對這真理的確懵然不知，只有我們的先祖才瞭解；那麼，這是我們要好好學習的時候了。一位元傳講復興資訊的蘇格蘭牧者馬欽芮（Robert Murray McCheyne）早在一個半世紀以前已糾正我們說：「我的會眾最大的需要是……」好了，你會期望這一位牧者怎樣說下去呢？是某項活動或某些特別的技巧？是對事物的一種新觀點？抑或是什麼呢？馬欽芮這樣說下去：「……我個人的聖潔」一首古老的聖詩說：「成聖需用時間工夫」，似乎我們都要重新學習這件事。因為倚靠自己能力的忙碌，不但非聖潔的表現，反而是聖潔的反面，令人遠離聖潔。這種心態必須重新描摹，他是一種不神聖的所謂聖潔，源於單憑己力。

　　但這仍未算最糟糕的事。環顧現代教會，一般都忽略了聖潔是教會最應關注的問題，因此在今日福音信仰的圈子裏，聖潔的榮光逐漸褪色。歷史上，一如聖潔是福音信仰的教師們所強調的重心，聖潔也是福音派信徒主要的標記。試回想路德如河強調信心產生善行，加爾文如何堅持律法的第三重用法，作為神兒女的法典和鞭策；又試想清教徒如何要求生命的改變作為重生的證據，苦苦鑽研怎樣在個人及社群生活中成為聖潔；試想荷蘭和德國的虔信派信徒（Pietists）強調純潔的心及純潔的生命，約翰·衛斯理宣稱「合乎聖經的聖潔」是循道主義的中心資訊；試想十九世紀中葉以後的所謂聖潔復興運動，以及萊耳（J．C．Ryle）的經典著作《聖潔》（Holiness，一百年後的今天，這書仍在發行出版），並且後期的師博，如卓巴斯（Oswald Chambers）、慕安德列（ Andrew Murray）、陶恕（ A． W． Toier）、倪柝聲和韋約翰（ John White）等帶來思想上的衝擊。過往，福音信仰人士熱切追求聖潔，毫不妥協；然而他們從前所看為最重要的，在我們今天掛著福音信仰名號的人看來，竟變成了次要的東西。為什麼？我想至少有四個原因。

*** 忽略聖潔
　　首先，今天福音派信徒忙於應付紛紜的爭論。我們為保衛合乎聖經的信仰而爭戰，惟恐他被減損或歪曲。我們致力於發展福音派學術，試圖堵截及扭轉自由、激進、主觀主義的潮流；我們奮力推動宣教及佈道工作；我們耗費精力去打擊人們執迷不悟的觀念——許多人以為聖潔的本質就是抽離一切活動，假定所有活動都是「屬世的」，但事實上有些活動卻是合法、有價值而又富教育性的，並且能真正娛樂身心；我們還要正面回答這個問題：「在基督裏，信徒有什麼自由？他們可以怎樣善用他？」雖然這些努力是正確的，但這些纏繞卻阻礙我們像教父們一樣熱切地追求聖潔。

　　其次，今日福音派信徒對於長久以來被灌輸有關「聖潔的教訓」（更高、更深刻而且得勝的生命、凱錫克［Keswick］。全然成聖，或任何「第二次祝福」論調的版本）感到失望。他們曾經耳熟能詳的道理，今天赫然驚覺都是貧瘠的、膚淺的，窒礙屬靈生命真正的成長，並且不適用於今天複雜矛盾的基督徒生活。我曾經詢問一位舊區的牧師，問他對「更高的生命」有什麼看法，他這樣回答：「只要你能抽出時間和金錢，追求這樣的生命是沒有問題的。」——這回答使人發笑，但從中可窺見人們信念的幻滅。

　　第三，今天福音派信徒的才華被用在其他地方，以致聖潔問題沒有受到應得的重視。在宗教改革及清教徒時期，才智出眾的神學家及教牧領袖——馬丁·路德（ Martin Luther）、加爾文（John Calvin）、歐文（John Owen）、巴斯特（Richard Baxter）、古得文（Thomas Goodwin）、賀維（John Howe）、史比士（Richard Sibbes）、居勞（William Gurnall）、屈臣（Thomas Watson）、布洛克（Thomas Brooks）……等，數之不盡——經常透徹思想和教導聖潔的課題。可是，到了二十世紀，大部分思想最傑出的福音信仰人士都致力鑽研其他範疇，結果，我們的現代神學對聖潔的瞭解十分膚淺（固然有例外的），對聖潔這個課題的研究，都缺乏合乎聖經的洞見、神學的深度，以及對
人性的瞭解。最顯赫的福音信仰神學家通常都不熱衷於闡釋聖潔的課題，而最熱衷於闡釋聖潔這題目的福音派人士，往往不一定是最可靠、最有見識的神學家。

　　第四個原因亦是最令人憂慮的，今天福音派信徒明顯地對神的聖潔毫不敏感。雖然我們慣常地肯定神對罪惡的憤怒，惟有基督傾流的寶血能塗抹我們的罪，但事實上我們甚少思想神如何恨惡他家裏的罪惡，亦不會像我們的祖先，因他的話戰兢，惟恐得罪了神（賽六六 2；拉一○3），我們亦不會像猶大，大大厭惡不潔的東西，「連那被情欲沾染的衣服也當厭惡」（猶 23）。我們習慣把天父、聖子、聖靈想為我們的密友，多於思想神的聖潔；若有人認為神最關注的，是訓練我們行在義中，以邁向未來的喜樂，而不是現在就把各樣快樂充滿我們，我們會駁斥這些想法為基督教信仰裏次等的觀念。在聖經裏，神視罪惡為汙穢，但我們卻不這樣看罪惡；當聖經告訴我們神對某些行為十分憎厭時（例如詩五 4—6，七 11 一 13；箴六 16；賽一 14，六一 8；摩五 21；路一六 15），我們卻認為這些只不過是誇大的說法。難怪我們今天漸漸不再追求聖潔了。

　　福音派對聖潔這課題相對地減低關注，實在有點可悲；尤其是今天福音派在數字、機構資源、宣教策略、學術成就、公眾地位，以及在許多方面上都突飛猛進，我只希望他在聖潔這課題上不再繼續失色下去。我們需要保持頭腦清醒，知道從長遠來看，除非我們在聖潔的追求上有更新的表現，否則這些增長都是徒然的。上一代以前，在大西洋兩岸，福音派的異象淩駕于自由派的學說之上，抓住基督徒的心思意念。多年來，這異象結出了許多果子，直至今天，他仍蓬勃，驅策著許多信徒；但願這異象長存下去，燃點不滅！但現在已經是時候，讓淩駕非福音派信仰的福音信仰異象同樣抓住我們的注意力，推動我們從深度的學術層面、牧養洞見和個人經驗上，重新探討聖潔的實質。

　　在本世紀，羅馬天主教徒、高派的聖公會信徒，以及各種中世紀信念崇信者，已對屬靈生命的各個題目——信心、禱告、平安、愛、自我認識、虛己、自律、背十字架、忘我並且投入為他人代求等等——有許多深入而透徹的探討；不論這些研究在福音的理解上是否全然正確，當中的屬靈觸覺及道德質素，是現代福音派在聖潔課題上的著作所望塵莫及的。這個事實使我憂傷，若然我現在所寫的能喚起一些福音派信徒看見這個需要，並在這方面致力改善，我便歡呼快樂。

*** 聖潔與世俗
　　今天，基督徒群體裏氾濫著「後基督教西方社會」的世俗潮流。那稱為「縱容主義」（“permissiveness”）的集體不道德思想，像一股巨浪洶湧而來，差點把我們淹沒。那些與過去傳統仍然保持密切關係的教會，比其他教會更有力地遏制這侵略性浪潮，然而沒有一間教會是完全成功的，尤其對年輕一輩的信徒來說，這影響極其嚴重。基督徒在性、家庭、社會、經濟、商業和個人方面的道德標準已經顯著地崩潰，現時流行的「新道德」，實際上是古老異教的不道德思想假借各種名號借屍還魂。「船隻在汪洋行走，」慕迪曾經如此說：「但若然海水滲入船中，那就麻煩了。」這真是一句逆耳的話，因為世俗的巨浪已經侵進現今的教會裏，水浸成災，造成很嚴重的禍害。

　　神呼召基督徒去抵擋世界，但在現時的情況下，怎樣可以實踐這個呼召呢？要對抗世俗的思潮，靠寫和講還可以，但若要對抗不聖潔的氾濫，只能靠聖潔的生活（見弗五3 一 14）。

　　今時今日，教會的普世性目標被界定為追求社會、種族和經濟上的公義，但若然我們首先追求每個基督徒個人生命及重體關係上的聖潔，這目標就更加健全了。現代西方社會需要基督教真理的影響，而且更需要基督教聖潔的影響，以表明敬虔才是人性的體現，以及防止社群生活腐朽消亡。因此，追求聖潔並非單單是私人的興趣，也非少數被揀選者的道路，而是今天基督徒宣教策略的一個重要原素。現今世界最大的需要，就是基督的子民追求和實踐個人的聖潔。

　　關於聖潔這個課題，一些適切這個時代，兼且具有權威的研究盡付厥如。在這個情況下，我嘗試把自己小小的捐獻投入這寶庫中，提供一些基本的，以聖經為原則的反省，作為我們以後討論的參考。

** 基本聖經原則　
　　這裏有七項關於聖潔的原則，我想沒有任何新約聖經讀者會對此存疑的，福音派學者在討論聖潔時，亦經常採用這些原則。

*** 1_聖潔的本質就是透過分別為聖達到更新
　　在新約聖經裏，有兩個字是用來形容聖潔的。第一個字是 hagiasmos(亦被譯為「成聖」「“sanctification”」，與形容詞 hagios 相關，翻譯為「聖者」【“saint”】，而動詞hagiazo，則翻譯為「使之成聖」「“sanctify”」）；這是關係上的字眼，意味著一種為神而分隔開來、有所分別的狀態——在人的方面來說，就是分別為聖事奉神；在神的方面來說，就是被神接納，被神使用。第二個字是 hosiotes，形容詞是 hodios，意味著一種內蘊的道德和屬靈質素，即在神面前，不論外在和內在都是公義而純潔的。將這些觀念合併起來，就能全面理解何謂聖潔。首先，這是關係上的聖潔，是透過持久不斷地分別為聖，並向拯救的神奉獻自己來達致聖潔；這是基督徒一生不斷悔改的另一面。然後，隨之而來是道德和屬靈上的潔淨，這一方面與我們作為神所收納的子嗣身分相配，另一方面是我們委身予神後不斷進到完美的過程。

　　我們需要瞭解，縱然神一開始就完全接納每個信徒，但只要我們仍然活在這個世界上，我們就需要不斷悔改。悔改就是從你自知的罪中轉回，又將你所認識自己的一切，獻給你所認識的神；當我們這三方面的知識不斷增長時，我們的悔改也隨之擴展。

　　所以，聖潔的生活就是我們積極地表達我們對神的認識，他透過基督我們的救主，將我們從罪人中分別出來歸向他，現仍不斷使我們更新變化，更有基督的形象。誠如保羅在腓立比書二章十二至十三節所說，我們順服神啟示的命令，「作成……得救的工夫」（即體現和表達救恩），這都是神在我們心裏運行的，所以我們作的時候，心存「恐懼戰兢」，但不是張惶失措，反而是對神在我們生命裏所成就的大工存尊崇的敬畏。他以他的靈在我們裏面運行，驅策我們立志遵行他的美意。這種生命質素所產生的結果，就是聖經所稱的「聖潔」。

　　那麼，讓我們弄清楚，我們分別為聖、被神接納的聖潔身分，正是我們談論成聖時通常心中所想到的個人的更新（韋敏斯德要理問答「Westminster Shorter Catechism」第三十五條這樣說：「靠著神白白的恩典，我們整個人都跟隨神的形象而更新，神的恩典幫助我們逐漸更多向罪死、向義活。」）基督徒在這世上的一切參與和擺上，一定要基於他自己所醒覺到的事實，也就是他已從所有受造物中分別出來，單屬於創造主。真正活出聖潔生命的信徒，都願意為了主的緣故，向配偶、兒女、父母、老闆、下屬和所有鄰舍有條理地、付極高代價而無限量地擺上；這是基於他們已徹底從這些人中間抽離出來，單單歸向神——父、子和聖靈。儘管一些人過著極度敬虔的生活，但若與以上的描繪不符合，在主看來，這些人的生命仍未算得上是聖潔的。

　　讓我們稍停一會，留意一下這個真理所蘊含似非而是的偉大道理——簡言之，一個藉著禱告和聖靈的力量，徹底從萬物中抽離，只專一愛主的生命，才最有可能徹底的投入人群，明白人們的需要，並甘心情願為幫助人群而付出自己。一般人以為聖人或多或少都與別人疏遠，這真是大錯特錯。詩人說：「親愛的主，我實在不懂得愛你；但你竟然這樣愛我。」基督徒之所以能夠對他人表現超乎常人的愛，完全是由於他學會了愛耶穌過於所有人（見約二一 25）。基於這個原因，信徒為神抽離自己，就得若能力去為其他人擺上自己——這是真正聖潔所不可缺少的表現。雖然這個論點很重要，但我們不能不討論下一點了。

*** 2_聖潔是藉著耶穌基督稱義
　　神白白稱我們為義，亦即是說，藉著基督完全順服，以至於為我們的罪死在十架上，使我們罪得赦免，蒙神接納，這就是整個成聖過程的基礎。這稱義是藉著聖靈、透過信心，叫我們與基督聯合而產生的；這基督就是為我們死，我們最初藉著信靠他而稱義（羅三至五章），並以後靠賴他活出聖潔生命的那一位（羅六至八章）。神聖子民的榮耀不在於他們的聖潔，而在於基督的十字架；因為最神聖的聖徒也只不過是一個被稱為義的罪人，他永不會脫離這個事實去看自己。百福特（John Bradford）——認識他的人都一致公認他是最聖潔的英國宗教改革家——在簽署信件時，經常自稱為硬心的罪人。有一個清教徒在他病重時兒證說：「我從未感到這麼需要基督的寶血——我亦從未可以這樣善用他的寶血。」約翰·衛斯理臨終時在病榻呢喃：「除了耶穌的寶血以外，再沒有方法可通去最聖潔的路。」而保羅自己，在年事已高、聖潔生命日長時，亦更清楚地認識自己的卑微，知道自己的不配，所以愈發謙卑；他在哥林多前書（約西元五十四年）自稱為使徒中最小的，在以弗所書（約西元六十一年）自稱為聖徒中最小的，在提摩太前書（約西元六十五年）更形容自己為罪人中的罪魁（見林前一五 9；弗三 8；提前一
15）。

　　固然，我們可能將太多含義讀進這三段獨立的經文裏；但不管如何，無論何時，基督徒看自己為罪人中的罪魁其實是世上最自然不過的事，使徒保羅的自稱實在不應該令我們驚訝。為何基督徒這樣判斷自己是最自然不過的？因為他認識到自己生命深處充滿了道德上的失敗、虛偽、苛刻、驕傲、不誠實、嫉妒、情欲、剝削別人的念頭、在動機上的怯懦，並私下一切羞恥；然而他未能認識任何人的內心世界像他認識自己那樣清楚。在聖潔上長進，就是對神更加敏感，從而更清楚估量自己的罪孽和缺點，因而更加深切地體會到自己恒常需要神恕宥和潔淨的恩慈。一切恩典中的長進都是建基於此。

　　故此，我們必需緊記，任何自我滿足或自義的聖潔，或者任何被認為是神所賜予的公義，若然減輕了我們藉基督稱義的需要，都是虛妄的，是不虔敬而又迷惑人的東西。這些所謂「聖潔」或「公義」，其實自相矛盾，其正確名稱應該是法利賽人的偽善，並非什麼基督徒的聖潔。

*** 3_聖潔的根源是與耶穌基督同釘死同復活
　　在羅馬書第六章，保羅解釋所有在基督裏有信心的，都是新造的人。他們已經與基督同釘十字架，意思是他們已將從前被罪惡佔據的生命置諸死地。同時，他們已與基督同復活，得著新生命，即那使基督復活的能力如今已在他們心裏運行，使他們可脫離以往被罪捆綁的生活。他們存有的中心，即保羅在羅馬書七章二十二節所稱的「我裏面的（人）」，亦即彼得在彼得前書三章四節所稱之「裏面隱藏的人」（譯自英譯本的“thehidden person of the heart”），已與從前不同了。他們已經改變了，那在他們裏面作王，驅使他們反抗神律法的罪的權勢已被推翻了。他們裏面重新生出了包樂（Luis Palau）一本著作的名稱所謂之「追求神的心」——深切而持久地渴望認識神、就近神、尋求神、尋找神、愛神、榮耀神、服事神、取悅神。這就是重建整體生命的主導動機。這也是約翰·衛斯理和他的門徒根據耶穌本人所說的「重生」的轉變（見約一 12，三 3、5、7—21）。

　　我們需要體會及牢記的，就是信徒的聖潔是學習在行動中活出那在我們裏面的生命。換句話說，這是活出新生命，表達我們在基督裏成為新造的人應具備的性情和本能（即是新的本性）。聖潔是靈裏復活的人「自然的狀態」，正如罪是靈裏死亡的人「自然的狀態」，基督徒順服神追求聖潔，其實不過是順應新造的人最深切的渴求而已。他向著神的（或說「向著天父的」更恰當）愛心、忠誠和奉獻，使向神活著，並已復活了的基督成為他心裏的動力和形象（參羅六 10、11）；我們大可稱這內在的生命為基督的性情或基督的本性。

　　對於一個從未在基督的死和復活上與他聯合的人，動機上的聖潔絕不會自然產生，甚至沒有可能，因為在動機層面上，罪惡仍不斷掌管他。「原來體貼肉體的，就是與神為仇；因為不服神的律法，也是不能服。」（羅八 7）要求沒有重生的人盡心、盡性、盡意、盡力愛神，他是力有不逮的。然而，一個從人方面藉著信心，從神方面靠著聖靈，得以與基督聯合的人，便能自發地產生實踐聖潔的動力；對他來說，向肉體的情欲降服是最不自然，又違反他重生本性的事（參加五 16 一 26）——這說明瞭為何靈命倒退的人內心往往那麼痛苦。任何一種觀念，若以為聖潔就是用人的意志去拒絕做一個人很想做的事，都必須加以排斥，視之為未重生者對聖潔的誤解。真正的聖潔源於神使人成聖的工作，亦即是清教徒所稱為「福音的奧秘」；這聖潔是基督徒真正的滿足，因為信徒按著在基督裏那嶄新而主導的本性，從心底深處渴望追求聖潔。縱然事實上很少基督徒能透徹地接觸自己心靈深處，以致能認同體會以上所說的，亦絲毫不能動搖這個真理。

*** 4_聖潔藉聖靈而成
　　在前章我已經講過，神居住在我們心裏的靈，在作為基督的靈時，能誘發聖潔。保羅說神在基督徒心裏工作，叫他們立志行事，為完成神的美意時，他心裏無疑是想著聖靈的能力活躍於奥古斯丁所稱之「先在恩典」中（編者按：「先在恩典」是神學名詞，指在人尚未回應神的大愛以致得救之前的恩寵），隨後活躍於「合作的恩典」裏。先在恩典使我們產生順服的決心，合作的恩典保守我們繼續順服。靠著聖靈的幫助，基督徒決意做一些正確的事情，而且實際行出來，於是養成做正確事情的習慣，從而培養出良善的品格。古諺說：「培養一種行動，就收割一種習慣；培養一種習慣，就收割一種品格。」這話在天然的生命中是正確的，在恩典的生命裏也同樣正確。保羅形容這種品格塑造的過程為變成主的形狀，榮上加榮（林後三 18），並稱這品格為聖靈的果子——細察之下，這證實如從前說過的，是耶穌基督自己活在門徒心裏（加五 22—24）。說到這裏，相信大家都熟悉整個問題的基礎。

　　然而，我們在此需要記著兩件不時被人遺忘的事情。第一，聖靈是透過「方法」來工作的——如透過恩典的客觀方法，即如聖經的真理、禱告、團契、崇拜和主餐，又同時透過恩典的主觀方法，使我們敞開自己，接受改變，即如思考、聆聽、自我發問、自省、告誡自己、與別人分享自己的心事，並衡量別人的回應。聖靈要在我們裏面彰顯他的能力，但他不會經常用異象、奇異的感覺或預言來幹擾上述的方法，給我們現成的屬靈洞見，有如已經放在碟上的即食面（這類特殊的溝通是罕有的，有些信徒根本從未經驗過）；反之，聖靈愛用慣常的方法來改變我們，使我們走在人生路上時，更有智慧、更加美善。有關聖潔的教導，若沒有指引人以堅忍態度去不斷行善，以培養出聖潔的習慣，這種教導是有缺欠的。習慣的培養，是聖靈引導我們進入聖潔的正常途徑。從某個角度看來，聖靈所結的果子就是一連串在行動和反應上的習慣：愛心、喜樂、和平、忍耐、恩慈、良善、信實、溫柔、節制等等，都是一些習性，意指一些慣有的思想模式、感受和行為。在聖潔生命中，習慣是十分重要的，尤其聖經指定的習慣；要培養這些習慣，有時不單只困難，甚而是痛苦的。

　　至於第二點，是平衡第一點的，並且同樣重要。我們要謹記的第二件事，就是雖然聖潔的習慣是靠自律和努力去自然培養出來，但這些習慣到底不是與生俱來的。種種操練和努力，必須受聖靈祝福，否則一切都是枉然。故此，我們整頓生命時付上的努力，都要浸浴在恒常的禱告中，承認我們靠己力無法改變自己，即如奧伯（ Harriet Auber）所獻上的。

　　我們所擁有的每一分德行、每一次勝利，以及每一個聖潔的思想，都全是他（聖靈）所有。

　　聖潔的生命是靠賴習慣培養而成的，這不是說我們可以憑自己的努力達致自我成聖，而是單單因著對聖靈的瞭解，並與他齊步同行才可獲致。

*** 5_聖潔的經驗是矛盾的
　　「因為情欲和聖靈相爭，聖靈和情欲相爭，這兩個是彼此相敵，使你們不能作所願意作的。」（加五 17）這些字句喚醒我們看見今世聖潔生活中一個劍拔弩張的現實，我們都需要付出努力，然而在今世是無法達致完全聖潔的。按照保羅的話，在我們更新的心靈裏，我們的愛好也就是聖靈的願望，而肉體的情欲便恰恰相反，他喜歡那「住在我裏頭的罪」（羅七 20）。住在我們裏頭的罪一而再地透過不同形式，如試探、虛謊和令人分心的事物，使我們叛逆神，以致無法達數十足的完美。所謂十足的完美，就是指衛斯理所說「天使般」的完美，一切都十分正確、充滿智慧、全心全意、完全榮耀神，達致不能再好的地步。一個重生的信徒，若在健康的屬靈狀況中，應每天都以完全的順服、完全的公義、完全地取悅他的天父為目標；正如我們討論過的，這才合乎他重生的本性。那麼，他能否達致這些目標？在這世上，他不可以！就這方面的事實來看，他就是不能作他所願意作的。

　　既然如此，他怎樣看他日常的生活？他深知道天使般的完美這應許是在天國才實現的，而在此時此地，他要竭力做到最接近完美。他也深知道誰會帶領及幫助他朝向目標邁進；他可以見證神已賜他力量抵抗罪惡、實踐公義，若單靠自己，他永遠無法做得到。（任何一個自稱基督徒的人，若沒有這樣的見證，他到底重生與否，尚屬疑問。）然而，信徒仍舊面對來自世界、肉體和魔鬼的種種攻擊，使他不能成為聖潔。所以他必須奮力頑抗，一次又一次地戰勝這三個魔頭；可是他卻往往不能達致天使般的完美，這一場又一場的戰役並未能把他帶到戰火的盡頭。

　　一如韋約翰（ John White）經典之作的題目：「打美好的仗」，聖潔的生命就是爭戰。保羅以意象豐富的詞句宣稱：「……我只有一件事，就是忘記背後，努力面前的，向著標竿直跑，要得神在基督耶穌裏從上面召我來得的獎賞。」（腓三 13、14）保羅所指的，就是那不斷的爭戰（保羅將這場爭戰描寫為長途賽跑，需要持續的決心和不斷使勁費力）。基督徒經常竭力抗拒從外而來的阻力，又要對付從內而發間歇性或情緒上的抗拒，這似乎不知從何而來，但在保羅的教導下，信徒就曉得這原來是肉體中叛逆聖靈的情欲。大概一百年前，懷特（ Alexander Whyte）針對一些以為提升的生命能使人免受試探的假像而提出意見，一針見血地指出：「呀，這是一場由始至終都激烈的戰爭。」

　　因此，我們必須牢記，在信徒今世追求聖潔的歷程中，任何以為可擺脫外在或內在矛盾的意念，都是癡人作夢，只能使我們感到幻滅、喪失鬥志，因為我們每天清醒時候的經驗已證其虛。反之，我們必須時刻認定，任何內裏真正的聖潔，都是在酷火中熬煉出來的，像我主一生的經歷一樣。希伯來書的作者這樣寫道：「那忍受罪人這樣頂撞的，你們要思想，免得疲倦灰心。你們與罪惡相爭，還沒有抵擋到流血的地步。」（來一二3、4）——但可能有一天你也會走到這個地步，一如耶穌在我們之前已作的榜樣，因為在這掙紮中，沒有障防或閘閂。因此，耶穌在客西馬尼園對打盹的門徒說的一番話，我們應該銘記於心：「總要警醒（要醒覺、機警、隨時戒備）禱告，免得入了迷惑（這試探必會臨到）；你們的心靈（已更新的你）固然願意，肉體（這裏不是指住在我們裏面的罪，而是指人性，內裏的罪就是藉此橫行）卻軟弱了。」（太二六 41）這是曆久不變的道理，缺乏了警醒的禱告及懷若禱告的警醒，我們一定無法站穩對抗世界、內裏的罪和惡魔，而只會陷墮於他們諂媚及誘惑的網羅裏。

*** 6_聖潔的法則就是神所啟示的律法
　　保羅說道，福音是要呼召我們「……將你們的心志改換一新，並且穿上新人；這新人是照著神的形像造的，有真理的仁義和聖潔。」（弗四 23、24）仁義和聖潔（這裏原文是 hosiotes，同時指到外在和內在的純潔）是彼此互屬的：兩者基本上是同一件事，只是從不同的角度看。當仁義被視為將自己分別為聖獻給神的表現時，那就是聖潔；當聖潔被視為遵行神的律法，那就是仁義，兩者二而為一。

　　在聖經裏，律法有多種不同的意思，但我在這裏用這個詞，是取其基本含意，就是神對人生命的要求。這些要求記載在十誡的律例和禁令上，被眾先知、使徒和基督自己闡釋與應用；又表現在聖經裏那些討神喜悅的人身上，而耶穌基督更列在眾位之首，從這個觀點看，他的生命就是律法的化身。誠如保羅告訴我們，在這個意義上，律法是聖潔、公義、良善和屬靈的（羅七 12、14）。律法的要求表達和反映了創造主的性情，而與律法符合的，就是神在人心裏的形象，亦即是酷似神的氣質；這形象在始祖墮落時失去了，現在才藉著恩典在我們裏面恢復。像神自己一樣，這律法的標準永不改變，而聖潔的高峰就是成就這早已賜給我們的仁義的法則。

　　我們應以神的律法作我們行事為人的準則，但切不可與律法主義混為一談。我們知道，律法主義是基督徒必須避免的錯誤。律法主義含有兩個意思：第一，他假設所有律法的要求都可用一套標準的守則去表達，且適用於一切情況，而這套守則卻不涉及行事者的動機、目的和心態；第二，他假設嚴守法規是救恩之道，我們可藉守律法進入榮耀裏，或至少獲得神一點寵佑，除此以外，別無他法。在這兩方面，律法主義不是正標誌著福音書所述的法利賽人，以及滋擾加拉太教會的猶太教基督徒嗎？然而，耶穌堅稱在人遵行律法或破壞律法之前，是先有意願和目的，然後才有行為和表現的，一針見血地點出第一個假設的錯誤。而保羅也粉碎了律法主義的第二個觀念；他闡釋福音是單單藉著基督，因信稱義，不是靠行為的。

　　今日福音信仰基督徒比較成功地防備了後者，對前者的防備卻沒有那麼著力。我們因信而罪得赦免、蒙神接納，這是最清楚不過的，但我們卻逾越了聖經的要求，為自己和他人訂立一些規則，視那遵守這些規則的人為屬靈上的精英。可是，這種藉著群眾壓力來削減基督徒個人自由的做法，並非聖潔之途；稍能引以為慰的，就是今天已有人起來反對他。

　　固然，為逃離熱窩而跳進爐火裏是不智的，若然我們為脫離律法主義而掉進無法無天的放肆裏，我們的終局可能比前者更加不堪。基督徒必須以遵行律法為他們一生的理想，誠如耶穌自己在登山寶訓中強調：「我實在告訴你們，就是到天地都廢去了，律法的一點一畫也不能廢去，都要成全。」（耶穌在這裏利用誇飾法講論，當時，他和許多聖經教師都經常採用這種技巧去突出要強調的重點；他實在的意思是，那體現在五經之中，以及貫穿並隱藏在整本舊約聖經裏的道德律例是永不消亡的。）「所以，無論何人廢掉這誡命中最小的一條，又教訓人這樣作，他在天國要稱為最小的；但無論何人遵行這誡命，又教訓人遵行，他在天國要稱為大的。」（太五 19）耶穌說，你若不是一個盡心盡責的律法遵從者，你不可能是一個好門徒。

　　肯定的說，基督徒並非律法主義式地遵行律法，不是為求取生命而遵行律法，而是自生命湧流律法的義，更不是為了獲取救恩，而是出於感激才遵行的（見羅一二 1）。他並非以罪人的身分，為求贏取救恩才順服神，而是作為神的兒子，在已享有的救恩中歡喜快樂地順服神。但他像保羅一樣，永不忘記他「不是沒有律法，……正在律法之下」（林前九 21）；故此他遵行主人的命令，力求取悅主人。這就是愛的明證（見約一四 15），也是真正的聖潔之路。這條路我們必須謹慎踏上，不能苟且貪圖捷徑，因為在道德上粗疏大意，就是屬肉體的（參林前三 1—3），不但沒有成全聖潔，反而把聖潔否定了。

*** 7_聖靈的中心是愛的精神
　　這一點對大家來說是那麼清楚、稔熟，實在無需太多解釋。耶穌說，律法的整個重心是愛神和愛人（太二二 35 一 40）。保羅說，愛是聖靈所結的第一個果子，那掛名的基督徒若沒有愛，便算不得什麼。愛超越（不是轉離）律例和原則，注目於人身上，並他們的福利及榮耀。愛實質上不單是一種感受，而是一種行為表現，即使愛以感覺開始，但若然是真愛，必定超乎感覺之外，有所表現，有所行動，有所給予；愛就如此建立他的身分。「主為我們捨命，我們從此就知道何為爰；我們也當為弟兄捨命。凡有世上財物的，看見弟兄窮乏，卻塞住憐恤的心，愛神的心怎能存在他裏面呢？小子們哪，我們相愛，不要只在言語和舌頭上，總要在行為和誠實上。」（約壹三 16 一 18）同時，「親愛的弟兄啊，我們應當彼此相愛，因為愛是從神來的。……不是我們愛神，乃是神愛我們，差他的兒子為我們的罪作了挽回祭，這就是愛了。親愛的弟兄啊，神既是這樣愛我們，我們也當彼此相愛。」（約壹四 7、10、11）

　　正如耶穌是律法的化身，他也是愛的化身，而最純全、最完美的聖潔表現，就是跟隨他的榜樣獻上自己。硬繃繃的、嚴苛的、冰冷的聖潔實際上是自相矛盾的。相反地，一如馬太福音二十二章三十七節引用申命記六章五節所指定的，和詩篇十八篇所表達的對神的愛，以及哥林多前書十三章四至七節所界定的，和耶穌透過好撒瑪利亞人的故事所闡釋（路一○29 一 37）有關對鄰舍的愛，才是聖潔的中心。至於實踐這種愛所要付上的高昂代價，我不會多花筆墨在此描述。我最主要帶出的，就是任何稱為聖潔的東西，若沒有愛，在神眼中都是徒然；換句話說，這只不過是空洞的偽裝。我們應當時常在這方面省察自己。

** 重建工程
　　那不能以彩色圖像說明的東西，不可輕信。

　　這是卓斯達頓（G．K．Chesterton）給一個聰明的孩子的最後忠告。話中的重點及蘊藏的智慧是最明顯不過的。那些空泛得難以用實例闡明的意念，大有可能是虛妄不實的抽象東西，甚至只是頭腦昏花的產品。真實的洞見是具體的，能用圖像表達，以解釋及證實其中的含義。更好的理念意象——用現代術語說，是「模型」（models）——動用了我們思維的另一半功能，也就是想像力；這些意象較諸純理性分析更能啟導我們對觀念的瞭解。很明顯，這是為何耶穌往往用比喻作教訓，又為何所有訊息傳遞者都必須培養一種分析與想像力並重的表達方式，才能產生長好溝通的原因之一。於是，作家們諸如魯益師（C.S．Lewis）、傳道人諸如司布真（ C．H．Spurgeon）都會如此，以至於巴刻，若他還有些少腦筋的話，尤其在討論聖潔教義的時候，更應如此。

　　為什麼？因為壞的圖像一樣會攫住想像力，而且錯誤的觀念會盤據腦海；近年來，聖潔教義更身受壞圖像的禍害。一直以來，有關聖靈的講論和闡釋在在隱含如下的意念：我們可以開動聖靈的能源，他就會自動在我們生命裏工作；聖潔的人長期處於一種被動的心理狀態，接受神的扶持；他們一旦將思想和情感交托予主，就可以不假思索地相信他們現在的思想和感情都是從神而來的；當基督那屬神的生命活在他們的肉身裏面時，他們的自我就自然消失，或說應該消失。一些並非出自聖經的語句被廣泛地濫用，例如「放心吧，一切交托給神」、「放棄自己的意願」、「將自我釘死」、「奉獻自己在祭壇上」、「讓基督掌管你的生命」等等，成為一些人思想及講述聖經所稱基督徒生命裏的「悔改」和「順服」唯一的屬靈術語（有關悔改，參林後七 9—11，一二 21；提後二25；啟二 5、16，三 3、19；有關順服，參羅一 5，六 16—19，一六 19；林後一○5、6；加五 7；腓二 12、13；彼前一 2、22；並參看約壹一 6）。壞的圖像和錯誤的觀念攪擾我們的腦袋，無怪乎我們的思想常常走入歧途。因此，我們把基本觀念整頓好之後，現在需要做的，就是找尋例證，以清楚闡釋聖潔生命。以下是我能找到的兩個最好例子，來自我多年來的經驗，第一個源於倫敦的希斯魯機場（Heathrow Airport），第二個來自溫哥華的維真學院（ Regent College）——兩者均是錯綜複雜的行政大樓，所以重建工程好像永不停止。

　　試想像一個地點，業務如常連作，同時又有各項工程正在進行。一座一座的建築物被拆卸，再利用拆卸下來的材料，重建一座又一座更新、更美的大廈。在工程進行期間，公司的業務運作如常，人們固然需要容忍好些臨時措施（例如在希斯魯機場，旅客需要穿越一連串的帳篷，然後由機場巴士接載至機場一哩以外的飛機旁邊；很英國式的做法，但卻不是最理想的機場設施）。經常更動使一些人感到厭煩，尤其是那些需要保持業務繼續進行，又事先沒有接到通告為何他們日常的工作程式必須一次又一次地那樣更改的人。但事實上，建築師老早為重建的每一階段擬好了總計畫，又有一位最能幹的監工指揮和統領每一個程式，每天都證明他們有辦法使一切如常運作（計畫中如此）。於是，那些在這工作上有分參與的人，每天都可以真正感到他們已經盡了服務大眾的責任，雖然未必能常常如期望般圓滿。

　　我的比喻是這樣的：重建地點和公司業務代表你的生命，神經常在其上工作，清拆我們的壞習慣，重建活像基督的習慣。天父為這漸進式的工作已擬好了總計畫，而基督就透過聖靈每一天逐步推行這個計畫。雖然你感到內裏日常的運作常受阻礙，又或者間歇地感到迷惘，不知神的工程今天已施行到什麼階段；然而，工程的整體結果，是要不斷增加你服事神和服事人的能力。（同時，你可能會，或者說應該會時刻都更醒覺到你所作的事的瑕疵，過於為著自己比從前做得更好而洋洋自得。）至於應用在基督徒群體身上的計畫，以弗所書五章二十五至二十七節有這樣描述：「……基督愛教會，為教會舍己，要用水藉著道把教會洗淨，成為聖潔，可以獻給自己，作個榮耀的教會，毫無玷污、皺紋等類的病，乃是聖潔沒有瑕疵的。」

　　我們在自我重建的過程中經歷種種困惑，在服事神時意識到自己的缺欠，屢屢遭受挫折，「……我們這有聖靈初結果子的，也是自己心裏歎息，等候得著兒子的名分，乃是我們的身體得贖。」（羅八 23）成聖往往不是一個舒服的過程，我們不要冀望在這過程中內心能波平如鏡。從另一個角度看，這重建的工程帶來苦楚，他是神對我們德性的管教和訓練，「凡管教的事，當時不覺得快樂，反覺得愁苦；後來卻為那經練過的人結出平安的果子，就是義。」所以神「……管教我們，是要我們得益處，使我們在他的聖潔上有分。」（來一二 ll、10）

　　彼得·威廉遜（ Peter Williamson ）曾經寫道：「我知道有些基督徒掛上英文縮寫P．B．P．G、I．F．W．M．Y．的記號，意思是『請容忍一下，神在我身上的工作還未完成呢！』（“Please be patient——God isn’t finished with me yet！”）這是萬分正確的。我們正處於被模造得更像神、更合乎他形象的過程中。保羅寫道：『我小子啊，我為你們再受生產之苦，直等到基督成形在你們心裏。』（加四 19）……保羅認為基督的生命必須在基督徒心裏逐漸成形，這生命並非一下子就完全臨到，是要時間和工夫去達成的。我們正處於這過程中。」2 這話說得正好。

** 活在聖靈中
　　保羅曾經兩次提到被聖靈「引導」（羅八 14；加五 18）。兩處經文都指到人實踐公義時，有他輕率的一面，那時正要靠著聖靈抵抗內心罪性的衝動（參羅八 12—14；加五16—18）。

　　「引導」（leads ）正好解為「指導」（guides），但這裏的意思並非神在人心裏啟示一些人本來不認識的指引；反之，聖靈催促我們去追求、實踐，並持守我們早已認識的聖潔。故此，據保羅所說，受引導和被指導是基督徒的標記。「凡被神的靈引導的，都是神的兒子」，他們就藉著他們生命的方向，叫人知道他們是神的兒子。「你們若被聖靈引導，就不在律法以下。」；你們的生命表明了你們是新造的人，現正活在恩典之下（加六 15；參羅六 14）。若果有人並不是這樣被聖靈引導，我們會懷疑他（或他）根本不是信徒。你若不追求公義，以致在聖潔的事上令聖靈擔憂（參弗四 30），那麼，你肯定在事奉上不能與聖靈同行。首要的事情終歸是首要的！

　　本章開始時，我強調聖潔應當是基督徒的優先選擇；現在我要重申這一點，作為本章的結尾。

　　要緊記聖潔是神計畫人類的救恩時對他子民的心意：「就如神從創立世界以前，在基督裏揀選了我們，使我們在他面前成為聖潔，無有瑕疵」（弗一 4）

　　要緊記聖潔是基督為全人類受死的目的：他「……愛教會，為教會舍己，要用水藉著道把教會洗淨，成為聖潔……」（弗五 25、26）

　　要緊記我們被提升至基督的生命裏，是為了叫我們成為聖潔：「我們原是他的工作，在基督耶穌裏造成的，為要叫我們行善，就是神所預備叫我們行的。」（弗二 10）

　　要緊記福音呼召我們歸向基督，也呼召我們成為聖潔：「因為神救眾人的恩典已經顯明出來，教訓我們除去不敬虔的心和世俗的情欲，在今世自守、公義、敬虔度日……」（多二 11、12）「如果你們聽過他的道，領了他的教，學了他的真理，就要脫去你們從前行為上的舊人，這舊人是因私欲的迷惑漸漸變壞的；又要將你們的心志改換一新，並且穿上新人；這新人是照著神的形像造的，有真理的仁義和聖潔。」（弗四 21—24）

　　要緊記聖潔——即脫離罪惡——是耶穌帶給我們的救恩的一部分：「……因他要將自己的百姓從罪惡裏救出來。」（太一 21）

　　要緊記「非聖潔沒有人能見主」（來一二 14）：這不是說基督徒要靠聖潔的生活去賺取神最終的接納，只不過正如人要有健康的眼睛才能清楚看見景物，所以，只有透過一顆純潔的心靈，人才能見神（在耶穌的權柄下，我們已擁有這福氣［參太五 8］）。

　　同時，要緊記只有聖潔的生命才能與神建立快樂的團契，不聖潔者只有錯失這福分。「耶和華啊，誰能寄居你的帳幕？誰能住在你的聖山？」答案是：「就是行為正直，作事公義……的人。」（詩一五 1、2）

　　同時，要緊記聖潔是被神使用的先決條件：「人若自潔，脫離卑賤的事，就必作貴重的器皿，成為聖潔，合乎主用，預備行各樣的善事。」（提後二 21）

　　最後，要緊記無論如何，對重生的人來說，聖潔是唯一最自然、最使人滿足的生活方式；神家裏不聖潔的兒女，由於違反了他們新生的本性，因此不但得不到內在的滿足，還要遭受慈愛的天父管教——並不是由於他們的罪惡熄滅了神的愛，而是愛之深、責之切，天父因愛他的兒女，不能容許他們無止境地走入歧途（參來一二 5—14）。

　　儘管我們對聖潔的本質及意義可能有不同的看法（下一章將會探討這方面的問題），我希望我們每一個人都贊成並緊記這一點：聖靈在我們當中的首要職事，是引領我們藉著信心，在基督我們的救主和主人裏，進入踏實的、個人的聖潔生命中；故此，我們身為基督徒，最關注的事情必須是以一百五十年前馬欽芮（ Robert Murray McCheyne）的禱文為我們自己的禱告，而那篇禱文正像是為我們而寫的：「主啊，使我成為聖潔，進到一個已得救的罪人扂能達致的最聖潔地步。」你會否說「阿們」呢？你若願意，那麼你閱讀本書所花上的精神和時間才不算白費，你的心靈狀態亦適合繼續閱讀本書。

* 4_聖靈的路徑_成聖面面觀

　　基督徒竟然在聖潔的問題上引起爭論，聽起來令人覺得丟臉， 又像自我譴責，一如要用拳頭來爭取和平一樣荒謬。溫柔和寬容豈不是聖潔的表現嗎？那麼，對聖潔教義的爭辯豈不傷害了聖潔的真諦嗎？而那爭辯者及其門派弟子，不管他們站在哪一方，豈不是自相矛盾嗎？爭辯本身豈不是不屬靈的，並且銷滅聖靈的感動嗎？答案是有兩重的。首先，若然為了眾靈魂的益處，爭辯並非不屬靈，一如關於基督和保羅，也引起不少爭論，只要我們尊重與我們意見相左的人就好了。其次，那些以避免爭論為美德的人，比起那些著意保護自己，其實臉皮薄而又自負的人高尚不了多少，而且，他們也許並沒有意識到真理的價值。有時候，爭辯是老師的責任，即使他教授的題目是聖潔，兼且沒有幾個人會為他的論點喝采。

　　在本章裏，我將為一些需要幫助的人而介入一些爭辯中。為了緩和緊張的爭論氣氛，我會盡可能少一點提名討論，也絕不會提起任何尚在人間而觀點不為我接納的人的名字。若然讀者發現我否定了他們本來持守的觀點，我盼望他們不要誤解我喜歡口舌之爭（其實我本人並不愛好爭鬧，只是迫於無奈而已）。我之所以這樣爭辯，完全是出於對人的愛。我從自己和別人的經驗中，深知道若對聖潔存錯謬的見解，不管這見解如何誠懇，他仍把人關鎖在虛妄和拉緊的狀態中，使人內在生命的真誠和喜樂盡毀；若我能力可及，我極願挽救我的讀者脫離這窘境。縱使你拒絕我以下的論點，仍請你記著我說這一番話的苦心。 

　　從牧養的角度看，第一場戰役就是要說服基督徒聖潔是必需的。我盼望在上一章我已極盡口舌之能說服人相信這一點。然而，基督徒願意委身追求聖潔後，第二場戰役又要開始了，這一回是如何在日常生活中實踐聖潔。在上一章，我們綜覽聖潔的七個合乎聖經的特點，希望這七個特點能為聖潔這題目圓滿地劃出一個範圍。固然，在認同這七個原則的大前提下，任何分歧都不過是次要的。然而，分歧是存在的，包括觀念和重點上的分歧都有，於是，我下一步就要把這些不同觀點勾畫出來，其中有三種主要觀點是需要分別清楚的。

** 奥古斯丁式的聖潔
　　第一個是「奥古斯丁式」取向的觀點，這是奥古斯丁用來對抗伯拉糾（Pelagius）的觀點，也是改革宗為對抗半伯拉糾主義而重申的觀點，至今還被保守的路德宗和改革宗的教師所堅持。他根本的原則是：神出於他的恩典（意指對罪人白白的、不計功勞代價的愛）和藉著他的恩典（意指聖靈在我們個人生命上的工作），必定在我們裏面動工，並且現在就如此動工，幫助我們達成他所要求的信、望、愛、敬拜和順服。套用奥古斯丁的話，神所賜下的，正是他所要求於我們的。事情必須如此，因為我們的本性都是與神為敵的，而且永遠不能完全擺脫罪惡的薰染。若非靠著恩典，我們實在不可能向神作出回應，縱使恩典的靈在我們生命裏工作，我們一切的回應和一切的義，都被罪惡所破損，故此，我們既然不能達致完美，就只配受到拒絕。

　　奥古斯丁主義只在改革宗教會裏貫徹始終地發展（在抗辯宗以外，幾乎所有號稱持守奥古斯丁觀點的人，除卻九世紀的哥特沙克［Gottschalk］、十四世紀的布拉特瓦丁［Bradwardine］和威克裏夫［Wycliffe］，以及十七世紀的詹森主義者 ［Jansenists］，都或多或少修改了其中有關主權和恩典的重點）。在抗辯宗主義裏，上述根本的原則得到兩項新的重點支持。第一，改革宗堅持有所謂現時完全被神接納（即稱義），以及基督的義歸予我們就是這稱義唯一及充分的基礎。（奥古斯丁持有一些觀念，認為我們藉著恩典應獲取救恩。這些觀念為日後羅馬天主教所追隨。）第二，清教徒和虔信派教徒堅持重生（新生）是關鍵；重生是無可改變的，藉著恩典，透遇與基督聯合，使人心改變，生出信心，這信心永不消逝。（奥古斯丁懷疑並非所有進入神所賜恩典的生命裏的人，都獲得堅忍的恩，這一點也成為日後羅馬天主教的觀點。）在這經過修正的架構內，一些人如歐文（Owen）、波士頓（Boston）、懷特菲（Whitefield）、愛德華滋（Edwards）、司布真（Spurgeon）、萊耳（Ryle ）和該柏爾（Kuyper）等，都已清楚貫徹地解說其中重要原則，就是在基督徒的生命裏，神所賜下的正是他所要求於基督徒的。

　　華菲德（B．B．Warfield）描繪奥古斯丁主義為一種「可憐罪人的基督教」——在今天這個喜歡自我讚賞，堅信精神健康的年代裏，這個形容乍聽起來非常可怕。然而我們極有可能誤解其中的含義。首先，當時用的是古老的語言。在一五四九年版道地奥古斯丁式的聖公會祈禱手冊（Anylican PrayerBook）裏，刊載蒙灰日（即大齋期首日）禱文，參加崇拜者要宣認自己是「無用的泥土、可憐的罪人」；今天，聖公會經常帶領會眾同誦：「在我們中間毫無健康，……求主憐憫我們這些得罪你的可憐罪人。」也同樣可回溯到相若的時期。這些字句並非意味著我們需要培養一種可憐兮兮的心態，我們亦不應該視這些句語為中世紀末葉病態的延續，抑或一種神經質的自我厭惡感和否定自我價值的表達（實際上，在我們這個年代，竟然上述每一種錯謬解釋都有人支持！）。在英文裏，「可憐」（miserable）一詞源自拉丁文 miserandi，意思是我們作為罪人，經常處於需要神的恩慈和憐恤的光景中；這不是神經質的虛幻主義病態，而是健康的基督徒所承認和接受的事實。較諸其他闡釋聖潔的見解，「可憐罪人的基督教」無疑較為強調我們的罪性，但這種描述反映出一種其清晰洞見的現實主義，絕不是貧瘠或枯竭的言論。

** 奥古斯丁主義的特色

　　奥古斯丁的觀點有三個重點：

*** 謙卑
　　首先，奧氏堅持在我們與神的相交中，需要極審慎的謙卑態度，不信任自己，懷疑自己。為什麼？因為神是完全聖潔、純全、良善的，他的信實永不改變，必定實現他的應許，而我們卻在這種種質素上沾不上邊兒。我們活在羅馬書七章下半部所描述的境況中：「……立志為善由得我，只是行出來由不得我。」（羅七 18）我們從前在亞當裏，是生來帶著罪性的，如今在基督裏，罪性的王權縱然被推翻，卻沒有完全消滅，仍舊存在我們裏面。我們經常受到罪的挑引、矇騙，被無法無天的驕傲和情欲所驅使，又被反抗神的自作主張和自我放縱（奥古斯丁採用的字眼是「自負」［superbia］和「欲望」「concuPiscentia」）重重圍困。因此，我們需要在救主神面前降卑，倒空自己，認識到自己的無能，完全倚靠神，也就是耶穌所說的虛心（太五 3）；否則，我們會在不知不覺間變得愈來愈驕傲自大，而驕傲往往使人陷墮（參林前一○12）。奥古斯丁主義的跟隨者肯定本仁（Bunyan）在唱出以下歌詞時，已得著這真理。

　　降卑的人無需害怕跌倒，
　　卑微的人沒有驕傲；
　　謙卑的人永遠擁有
　　神的引導。

　　他們看見聖靈部分的工作，就是不斷使我們愈來愈意識到神榮耀的聖潔和我們昏暗的罪孽形成強烈的對比。因此，在成聖的過程中，我們愈像神，與神愈加親近，也愈漸醒覺到神和我們之間有莫大的差距。

*** 行動
　　所堅持的第二個重點，就是神所有僕人在他們的行事為人上，都需要極進取的行動。為什麼？因為那住在我們裏面的罪，按其本性是不願遵行神旨意的，這罪性使我們對「善行」冷漠、疏懶、怠惰，並引致我們跟自己兒戲，跟神兒戲，好使我們合理地為自己的荒疏鬆懈解釋，但神拯救我們是要我們行善的（參弗二 10；多二 ll—14）。

　　奥古斯丁主義正是福音派寂靜主義者所推崇之「靜止狀態」（stillness）的極端相反，這「靜止」狀態也是約翰·衛斯理所極力爭辯頑抗的。這些寂靜主義者認為在聖經和普通常識的指引之上，並且在你認識到鄰舍的需要，因而要作出行動之前，你必須領受聖靈的特殊催迫，方可行動，否則，你所做的任何事都不能取悅神。他們說倘若沒有這特殊的催迫，你絕不應嘗試做任何有屬靈意義的事；不要讀聖經，不要祈禱，不可近教會，不要為神的緣故付上什麼，不要作任何事奉。在受聖靈感動之前，被動地不作任何行動就是最正確的途徑。約翰·衛斯理對此大力反對！「盡你所能行善」是約翰·衛斯理所教導有關聖潔的基本原則，他鼓勵人朝這個目標自動自發，可說是個十足的奥古斯丁主義者。

　　誠然，基督徒富進取的行動，不應該是隨便和糊塗的，也不應該單單相信自己和靠賴自己。基督徒的行動必須受智慧引導，即是要具備最清晰的洞見和聽取最佳的意見；採取行動時，必須以禱告的心仰賴神，並常存謙卑，願意改變和改進自己的計畫。

　　奥古斯丁主義有關聖潔的教訓，鼓勵人在行動上竭盡所能，一如很多極度忙碌的聖人，如奥古斯丁本人、加爾文、懷特菲、司布真和該柏爾等人的表現，但他們在心態上絕不倚恃自己的能力；反之，是按著四個階段而成的。第一，作為一個盡所能去行善的人，你要認清你所面對的工作、機會和責任。第二，你要為這些事情祈求神的幫助，承認離了基督，你什麼都不能作——意思是不能有任何成果（約一五 5）。第三，你要存著善意和高潔的心去開始工作，期待神會照你所求的幫助你。第四，你要感謝神在整件工作中的幫助，並求神赦免你的失敗，懇求他在下一件工作裏繼續幫助你。奥古斯丁式聖潔是勤勞的聖潔，建基在這重複又重複的程式上。

*** 改變
　　第三個重點是屬靈的改變——透過清教徒所謂逐漸清晰地彰顯恩典和不斷治死罪惡的過程，我們成長、前進，達致更完全像基督的地步。奥古斯丁主義者毫無保留地肯定神大愛的權能，因而對聖靈能更新信徒的生命十分樂觀，而對於未重生的人性則十分悲觀。對於基督徒在神完美標準的審判下，天天暴露他們的不足，他們又感到十分真實。奥古斯丁主義者認為神恩典的工作是首先更新人的心靈，然後逐漸由裏至外使人按著耶穌的形象完全改變過來，活在謙卑和愛中。因此，他們期望基督徒結出愈來愈多聖靈的果子，不管這些品德與他們的性情和傾向如何相違背。他們亦期望基督徒能勝過突如其來、陰險難測、捲土重來的試誘，並靠著聖靈的大能，「治死身體的惡行」（羅八 13；參看西三 4），即是說，使生命脫離罪惡的圍困，以致罪惡無所施其技。

　　奥古斯丁主義者（1）宣稱他們不遇是被恩典救贖的罪人，（2）認為這世上沒有任何事或任何人在道德和靈性上是完全的，（3）反對任何形式的完全主義教導，並且（4）公然數說他們自己的缺點；上述幾點容易令人產生兩重印象：第—，使他們以為不斷提醒基督徒罪經常纏繞他們是非常重要的。第二，他們對於今生能被拯救脫離罪的權勢期望過低，意味著根本不能實踐！但事實並非如此。舉例說，約翰·歐文在他那篇有關遏制情欲的論文裏，說到基督徒若發現自己「內心存著滿有權勢的罪，使他受這罪的律轄制，心靈困擾、心思迷惑、靈魂軟弱，不能與神交通，以致他五內不甯，沒有平安，甚至良心受污染，變得心裏剛硬」，他應該如何面對。歐文在文章結束時，提出以下的指引：

　　憑信心仰賴基督，治死你的罪。他的寶血對於被罪壓傷的靈魂，是偉大而靈效的良方。活在基督的寶血中，你就會至死仍是得勝者。是的，透過神的美意，你會看見你的情欲死在你的腳下。

　　有關奥古斯丁主義者對脫離罪惡沒有存多大期望的批評已談論得夠多了！固然，他們知道克制肉體的罪行並不等於完全脫離罪惡；悖逆神的精力仍存留在基督徒的屬靈系統中，經常按著不同的年齡和性格蠢蠢欲動，尋找新的發洩，故此，這一場對抗罪性的戰爭是畢生的。可是，藉著聖靈，我們不斷改變自己的性格，也能畢生勝過罪和試探。

　　羅馬書七章十四至二十五節在論述基督徒聖潔的篇章裏，羅馬書七章十四至二十五節可說是主要的經文；在奥古斯丁主義的教訓裏，一開始就強調這段經文，以下是這段經文典型的注釋。
　　
　　在羅馬書六章一節至七章六節，保羅宣告他那關乎自由釋放的神學——意思是藉著與基督聯合，信徒得以離罪就義，因為他們已不在律法的束縛之下，而在聖靈裏事奉神（參羅六 12—14、22，七 6）。然後，保羅為律法辯護，又承認律法的限制：律法雖然教育人的良心，顯露人的罪惡，卻不能帶給人生命（參羅三 19、20，五 13、20）。於是，保羅提出這個問題：律法和罪有什麼關係？他回答自己的問題，解釋律法（1）教導我們什麼要做，什麼不要做，（2）因而鼓動我們墮落了的天性去做不應做的事情，而不是達成律法的要求，再者，（3）律法一方面告訴我們向這衝動投降是有罪的，（4）另一方面卻無法給我們任何力量去抵抗這些衝動和試誘（羅七 7—25）。

　　為要將這四點精簡生動地表達出來，保羅數說自己的經驗，首先是他悔改以前的經驗（7—13 節），然後是他如今後在基督裏的經驗，以六章一節至七章六節的方式陳述出來。故此，第十四至二十五節看來似是保羅陳述自己在寫作時期如何經驗神的律法。既活在基督裏，他的心以律法為樂，渴想做那良善、正直的事情，而且完全地遵行律法（羅七 15—23，參看八 5 一 8）。但是他發覺自己不能達成完全順服的目標。每當他衡量自己做過的事情，他總發現自己不及標準（23 節）。由此，他察覺那敵擋神的衝動（即是罪），雖然已經不能再在他心中作王，卻仍舊在他敗壞的本性中（即「肉體」，參 18、 20、23、25 節）居住。因此，從基督徒的道德經驗可見（倘若保羅不以自己的經驗為典型的例子，他就不會引用自己的經驗去表達這個神學觀點），他要達到的目標，往往超乎他所能掌握的，而他追求完美的渴望，亦經常被內裏的罪迷擾心神、分散精力，而遭受挫折。

　　保羅寫到這個關於他自己的可悲事實時，他的苦惱就重新被挑起來，在二十四、二十五節的呼喊中，他為著自己不能多點榮耀神而感到痛苦：「我真是苦啊！誰能救我脫離這取死的身體呢？」然後，他自問自答：「感謝神，靠著我們的主耶穌基督就能脫離了。……」問題是用將來時式發問的（“Who Willdeliver me……？”），答案的動詞理應也用將來時式作答：「感謝神！靠著我們的主耶穌基督，他將會救我脫離……」保羅在這裏宣告他現在那無可奈何的缺陷（總括在二十五節後半截的詞句中）將有一天透過第八章二十三節所描述的身體得贖而成為過去（七章二十四節是這裏所形容的「歎息」的一部分）。因此我們必須盼望等候未來的救贖，經常持守那貫穿整部新約聖經的兩個世界、天路之旅和盼望將來榮耀等觀念。

　　羅馬書第七章直接引入有關基督徒確據的豐富敍述，擴展五章一至十一節的主題，使之充滿羅馬書第八章整整三十九節的經文。基督徒不被定罪，因為在基督裏，人不會與神的爰分離，也沒有戰慄，反而藉著基督從神得著盼望；這些主題是全章的脈搏。全章都是神學性和教牧性的講章；因為保羅試圖在律法（律法讓基督徒知道自己「失敗！軟弱！有罪！」）與福音（福音讓基督徒知道自己「蒙受！得救！安全！」）之間取得平衡，而他的目的，是叫讀者肯定，那在他們的良心裏下最後判語，並決定他們對神、對自己、對生命的最終態度，是福音，不是律法。試想像基督徒的生命有如一所有不同方向的房子。羅馬書第七章描寫那淒冷、陰暗，遠離陽光的一面；羅馬書第八章則表達那溫暖的一面，看得見也感覺得到陽光。我們只是離開羅馬書第七章，進入第八章，意思是我們聽了律法告訴我們關於自己的事情後，便讓福音對我們說話。然而，這兩方面的經驗——不完美的痛苦，以及得著確據、盼望、靈命長進的喜樂——都應該是我們經常有意識而相連地體驗得到的。在我們每一天的生活中，我們必然同時處於這兩章經文所描繪的境況裏。懷特（Alexander Whyte）搖動指頭指著他的會眾說：「我一日仍是你們的牧師，你們一日離不開羅馬書第七章！」他的意思是他會不斷提醒他們這個事實。

** 優點和缺點

*** 絕不妥協
　　我想，這聖潔教導的傳統有三項特別的優點。首先，他對神的道德律法是絕不妥協的。那律法命令我們內在動機和外在行為都要一致地愛神、愛人，凡違反這律法的態度和行事方式都被定罪，這律法也是耶穌在世時親口解說、親身活出來的，絕不容許有人絲毫削弱或減輕他的力量。奥古斯丁主義根據約翰（約壹三 4）對罪的定義，指罪就是違背律法——正如韋敏斯德要理問答（ Westminster Shorter Catechism ）第十四條所述：「不遵從神的律法，或違反神的律法」——，而且堅持從罪中得拯救的意思，是指獲得遵行律法的自由和能力。因此，奥古斯丁主義承認加爾文所謂律法的第三個作用，就是作為家庭法典，藉著建立一套理想標準，催迫神的兒女努力去取悅他們的天父。依上述所言，奧氏思想的主流就是要盡所能遠離反律主義（ antinomianism，即違背法則的生活）。

*** 現實主義
　　第二，奥古斯丁主義對我們的成就採取十分現實的態度。他堅持世上沒有什麼是完全的，並正視信徒在今世生活上的種種不完美。就以我來說，我所做的任何一件事，不論是構思一篇禱文、講一次道、寫一本書、對妻子表示我的愛、關心兒女或支持朋友，到事後檢討時我總發現自己能夠或應該做得更好。在我活過的日子中，我從未有一天是完全沒有遺漏半點我該做而未做完的事情的。我期望所有讀者都有同感，老實說，我對那些認為無需如此共嗚的人沒有多大敬意。有一個故事是這樣的，一天，有人走到司布真面前，說自己已有兩個月沒有犯罪了，司布真牧師很想試驗這個人，於是使勁重重地踩了他的腳趾一下；立時，這個人所自誇的記錄（「自誇」肯定是最恰切的字眼！）就黯淡無光，化為烏有。奥古斯丁主義者知道任何無罪的自稱都是虛妄的，因此，他們永不會裝作無罪；反之，他們經常為到神對這些不完美的基督徒如斯忍耐和慈愛，衷心讚美他。

*** 心存盼望
　　第三，奥古斯丁主義者是一天天地存有盼望的，他們除了盼望將來在天國的完美外，在每一天的患難裏，也盼望神的幫助，在每一天的工作中，亦盼望神賜他們力量去順服，因而藉著聖靈產生聖潔的習慣，達致性格上逐漸的更新。即使他們或有靈性低潮的時候，他們的生命容不下冷漠和怠情。他們從神那裏盼望偉大的事，為神作偉大的事，在聖潔的事情上，非常重視忍耐、自律、毅力（英國人稱為“stickability”，北美人稱為“stick－to－itiveness”，都是指到這種堅毅不拔的精神）。他們發現聖靈使用他們對受助的期望，藉以賜給他們力量，每天在單調的日常工作中堅持下去；而且他們知道真正聖潔（有別於那些有時令我們信以為真的裝腔作勢式虛假聖潔）的大部分內涵正是這種堅持的精神。

　　可是，除了長處外，這聖潔教導的傳統難道不也有弱點嗎？不錯，弱點是有的。奥古斯丁主義者的基本問題，在於他們一開始就面對憑己力產生功德的觀念——首先出現在伯拉糾主義（Pelagianism）中，然後表現在羅馬天主教教義（Roman Catholicism）上，再而表現在理性的亞米紐斯主義（Arminianism）上，結果使信心成為一種換取功勞的行為——以致他們提到世上沒有任何人的行為是完美的時候，表達出一種在倫理上乍聽起來是極度負面和悲觀的信念。故此，舉例來說，韋敏斯德要理問答巨冊第一四九條的答案十分令人氣餒：「沒有任何人靠自己或恩典，在這世上能夠完全遵行神的誡命，反而每一天都會在思想、言語、行為上破壞他。」人很容易從中得出一個結論，就是連嘗試遵行誠命都是沒有價值的。更近期，奥古斯丁主義者才剛剛重新肯定這一個負面的觀點，去抵抗杭辯宗完全主義的兩個主要形式：約翰·衛斯理和保守的循道主義所宣導心靈的完全，以及凱錫克運動和近期其他相關的運動所主張行為的完全。

　　這種負面的說法很自然惹人產生疑問。批評家經常提出的問題是：這種觀點豈不導致人對脫離罪惡和性格改變有過低期望嗎？這觀點豈不容易誤導我們，使我們仰望及祈求成聖恩典時要求過低，以致我們只滿足於少許恩典，而我們實際領受的也不會多？這觀點豈不壓抑聖靈及限制了神的工作？豈不錯失了查理·衛斯理那得勝的句子：「他粉碎那已被塗抹的罪的權勢」所包含的許多真理嗎？這豈不迫使那些認真尋求聖潔的人往別處去尋找脫離罪惡權勢的拯救？答案是：非也。就最好的詮釋者而言（例如加爾文「Calvin」、約翰·歐文「John Owen」和萊耳「J．C．Ryle」）是不會如此的；但某些二流的奥古斯丁主義者又確實如此，他們真的給人留下一個印象：只是死守正統和反完全主義，卻沒有任何積極途徑去伸張聖潔。可是我們評斷一些立場時，應該以他們當中最優秀的詮釋者為依歸。

** 衛斯理式完全主義
　　現在，我們應該轉而看看第二個立場，就是十八世紀中葉，約翰·衛斯理以「基督徒完全的生命」為題發展出來的思想觀念。這思想確定在一般新生（悔改信主）以外，有第二次憑恩典的更新。衛斯理宣稱神在這第二次工作中，除去基督徒內心一切犯罪動機，以致他全部心智和情感力量今後都為愛神及愛人而流動：這愛是像基督的、超自然的、剛強和穩定的、有目標和熱烈的，並超脫任何與此相反及相競的情感。

　　這是一條高貴的教義，歷史上與衛斯理氣度相當的衛斯理傳人——聖公會的傅勒徹爾（J．W．Fletcher）、救世軍的卜維廉（ William Booth）和白蘭高（ Samuel Logan Brengle），以及浸信會的卓巴斯（ Oswald Chambers）等，更將這教義發揚、修飾。這教義引發信徒追求聖潔的恩賜，因而吸引千千萬萬人進入被神的大愛更新的經驗裏。早期循道會信徒，即使未必完全受這種教義影響，也大大的受到薰陶，他們在讚美神時大唱大叫，在禱告中悲痛欲絕，為神的工作勇往直前，就好像他們的靈魂已大大增長，有無比容量。雖然在今日較大規模的循道教會裏，這種現象已幾乎完全湮沒了，衛斯理教義在其他圈子仍然活躍，這些屬神的人仍舊自稱生命進入了「第二次祝福」裏，獲得更新。毫無疑問，一些重大的事情已經在他們身上發生，但問題是衛斯理教義有否準確地描繪這些事情——簡言之，衛斯理教義是否神的真理。現在，讓我們在重新檢視這教義時，作出一些判決。

　　第一件事要說的，是衛斯理教義並沒有摒棄奥古斯丁主義，反而將之擴大。（我這裏所指的只限於傳統的奥古斯丁式關乎聖潔的教訓；至於而斯理的亞米紐斯主義摒棄了奥古斯丁恩典教義的精義，則不在我這裏所關注的範圍內。）約翰·衛斯理雙親的家庭都承襲清教徒傳統，難怪他那關乎聖潔的教導，保持了我們先前敍述的七項聖經原則，並有奥古斯丁所強調的幾項重點：就是神的律法對基督徒具有約束力；在絕對的標準下，每個基督徒的成就皆有不足；並且我們每天都需要神的幫助。事實上，他鄭重強調基督徒完全的生命為循道會教義的特徵；他認為這是聖經真理，是他首先將這真理清楚解說的。從那時候起，加爾文派的信徒一直抨擊衛斯理，指他堅持我們可以達到完全無罪的境界，而這正是奥古斯丁認為我們無法在今世達致的。不過，我們若仔細探討，就知道這純粹是誤解（這個誤解也起於衛斯理自己不反對採用「無罪的完全」這個辭彙，因此他也必須承受一點指責）。其實，衛斯理只是將奥古斯丁的傳統聖潔教義重新譜寫，並沒有摒棄其中要素；我以為這樣瞭解衛斯理教義較為正確。誠然，以自律及禱告的心懷積極進取，強調我們全然倚靠神至高無上的愛和能力，和對神在人生命中的工作有很高的期望，在這些方面，衛斯理與奥古斯丁的思想完全吻合。再者，誠實的自我評價令衛斯理不敢宣稱自己是完美的，並驅使他在一七六五年寫道：「我已告訴全世界我並不完全，……我沒有達致我自己構想的完美性格。」3 這真是奥古斯丁式的說法。那宣稱自己完全的絕不是奥古斯丁式思想！

　　然而，衛斯理透過他的教誨文章，以及他的兄弟查理所寫激勵人心的詩歌表達出來的完全教義，正好賦予他所描繪的基督徒生命一種熱情、豐盛及喜樂的特質——因認識神，讚美他的恩典，把自己交付在他手中而得著喜樂——；這特質遠遠超乎我們在加爾文、清教徒和早期虔信派教徒身上所找到的。在奥古斯丁的傳統裏，奥古斯丁本人、聖伯爾納（Bernard）和巴斯特（Richard Baxter）所表現的，與這完全主義所表彰的特質最為接近，但在筆者看來，衛斯理兄弟那些感情洋溢的詩文遠勝以上任何一個人。

　　衛斯理關乎完全成聖的教訓，內容豐富，反映出廣泛的資料來源。對於他所教導的完全，他經常稱之為「合乎聖經的聖潔」，但他所瞭解聖經對聖潔的教導，是由許多不同來源的資料綜合而成的。他是個十足的折衷主義者，他將從希臘早期教父的著作中學來的完全觀念（借用新約的字彙，完全是 teleiosis，是 teleios 的境界），加諸聖公會祈禱手冊所表現的奥古斯丁主義之上，又加在那培育他的、嚮往天堂的高派教會道德主義之上。（編者按：高派教會指較重視傳統與儀典的聖公宗或安立甘教會。）在這些希臘教父中，以「埃及人馬加利流」（Macarius the Egyptian”，此人其實是五世紀時期一個敘利亞修士）和以法蓮（ Ephraem Syrus）為主；他們認為完全的生命並不等於完全無罪，而是全面的道德改變，而且不斷深化的過程。在這意念之上，衛斯理又再加上他從那些他稱為「密契派作家」（這稱謂包括了聖公會的羅威廉［WilliamLaw］，羅馬天主教的穆利諾斯［Molinos］、芬尼倫 r6n6lon〕、蘭地『Gaston de Renty』、撒勒『Francis deSales』和蓋恩『Madame Guyon』，路德宗虔信派教徒富朗開［Francke］和前改革宗時期的《日爾曼聖道書》［Theo1ogiaGermanica］的作者）的著作上學到的功課：真正敬虔的心是一顆主動自發地愛神愛人的心；缺乏這顆心，所有宗教都是空洞和空虛的。

　　一七三八年，在愛打士基街頭（ Aldersgate Street），福音的確據始像破曉的黎明劃進衛斯理的生命中，然而在得著這確據之前，衛斯理對於完全的觀念已經十分清楚，正如他時常堅持說，他的完全觀念早在他進入所謂「兒子的信心」之前已建構好了。只是，一旦信心臨到，他就踏上最後一步，這對他來說是很獨特的一步，可使他進到完全。他開始宣稱，完全成聖——人們理解為全心全意愛神愛人的心靈境界（當信徒離開那取死的身體，聖靈就帶領他們進入這境界）——是可以今生在我們裏面即時陶煉出來的，透過操練堅毅、期待、一無所有、滿腔熱血，以及支取應許的信心而成，就與先前稱義的途徑一模一樣。衛斯理所教導有關第二次恩典的工作，一如先前新生的經驗一樣，是聖靈在人心中直接見證曾發生的事情，作為印記。然後，人在完全的生命裏靈命還會繼續長進，就如先前邁向完全一樣。

　　這樣看來，衛斯理的完全教義所講的似乎不是什麼無罪的境況，而是靈命的成長。衛斯理對完全的生命，或他經常稱之為「完全的愛」的理解，並不是律法式的，而是目的性的；換言之，不是「先前亞當式」或「天使式」的無瑕無疵境況，而是集中精神、結合精力、付上全副感情地決意進入敬虔裏，並保守自己常在其中。這本來就是神創造人及救贖人的本意。

　　於是，完全是一種境界，但這不是靜態的，而是全心全意地在順服的敬拜和事奉中與神恒常交往，而這團契是單單由內裏燃燒的愛所達致的。事實上，這是內在生命的質素多於外在的表現。對衛斯理來說，完全的人仍舊可以知識不足、判斷錯誤，甚至行事愚昧。他可能仍舊表現一些，甚或許多「內在及外在非道德性的不完全，……理解上的弱點和遲緩、領悟力低、對事物混淆、思想不連貫、想像力間歇地敏捷或遲鈍、……記憶力差……口齒不靈、言語不當、發音不准……」4 他仍會時時刻刻受試探所攻擊，他必須不斷頑抗去保持自己人格完整。可是，他的完全卻絲毫不受這些事實阻擾，因為這完全的生命純粹是一種對神和對人的愛成為他生命持久的推動力。

　　故此，根據衛斯理的想法，完全是一種主觀的狀況，是由神的靈創造和持守的。在這種狀況中，基督徒所有心智和心靈的力量都有意識地集中起來：首先，透過聖靈的見證，專注於實際理解神的愛；其次，為著神的緣故，積極地、順服地、懷著禱告的心、滿心歡喜地愛神及愛鄰舍。這愛首先表現在敬拜和讚美中，表現于欣然把自己交付在神手裏，預備接受神指派我們的任何使命。這是可切慕的福分，因為他把人的整個生命提升至能力和喜樂的新層次。我們應當追求這福分，因為聖經載有這樣的應許和見證，倘若新約信徒曾甘之若飴，今天的信徒也可以如此。神以他至高無上的智慧賜下這福分，然而在特殊情況（即如衛斯理的情況？），又或是他看來合適的時候，他可特意把這福分取回。不過，除非信徒尋求這福分，而且不斷尋求，否則沒有人能獲得。最後，這福分或會因為信徒一不小心而失去，不過，在悔悟中尋索，也許能失而復得。

** 對衛斯理式完全主義的評價
　　衛斯理關乎聖潔的教訓似乎堪稱醇酒，同時也是敗瓦。首先讓我先嘗一嘗芬芳的醇酒——他聖潔的觀點有許多優點。

　　衛斯理的思想以動機作為聖潔的試金石，一如耶穌自己在樹立標準及探察罪惡時所作的一樣（參太五 21—30，一五 18 一 20）。因此，這思想撇棄一切倫理上虛有其表和機械式的敬虔，以及所有法利賽形式主義和以數位量度的生活方式，並所有視宗教為常規活動的觀念。

　　同時，衛斯理的思想集中於愛神愛人，在動機的層次上完成基督的兩大誡命，以作為聖潔的根本，撇棄所有負面的成聖觀念，儘量回避一切汙穢人的東西。「『聖化』和『聖潔』等字……誠然帶有從不潔中潔淨之意，但卻沒有暗示任何主動行善的堅強力量。『完全的愛』恰好與這相反……」

　　最後，衛斯理的思想以信心為尋求及得著聖潔的途徑；信心就是對自己絕望，對神肯定的信靠。當然，我們必須付出努力和自律，但不能有絲毫靠賴自己之想；我們成聖的希望必須建在神之上，不是建在我們自己身上。這些思想可欽可敬，也十分符合奥古斯丁主義！南斯理視聖潔生命為一生不屈不撓的奮鬥目標，他反對反律主義、寂靜主義、感情主義，和以種種形式出現的道德上的被動，也拒絕給神的靈此時在我們裏頭的更新能力劃出界限；這些在在都是令人欽佩的觀點。

*** 達致完全所產生的問題
　　可是，根據衛斯理的完美生命、純潔心靈，或完全成聖教義——他的門生後來稱之為「第二次祝福」——，神的靈在一刻間把基督徒內心一切動機根除，只保留著愛；這教義著實引起許多問題。若果衛斯理單單宣稱聖父和聖子事實上時常以活潑的、溫暖的方式，使他忠心的門徒意識到他們的同在（參約一四 20—23），並藉著神這些眷佑，信徒對從前感到困擾的試探產生短期或較長期的免疫能力，而每個基督徒都應該恒常求主親近和賜福他們，這樣便毫無問題了，因為這意味著衛斯理道出了公認的活在聖靈裏的生命實況，所以不會引起爭議。可是，衛斯理斷言達致完全是一條教義——亦即是對神的工作一項標準的解說，一如重生般獨特和具特徵（衛斯理是這樣持信的）——；正由於他這樣斷言他所形容的完全生命是合乎聖經的教義，在過往和今天都不斷惹起爭論。

　　衛斯理認為這恩典與重生一樣，有主觀和客觀兩方面。客觀來說，重生就是推翻罪的王權，以及更新個人的態度，進入謙卑和有美德的新生命裏；主觀來說，人的罪得到赦免，藉著耶穌基督被收納入神的家裏後，他對神便有確實的信心。衛斯理視完全生命亦具有類似的結構。客觀來說，這是藉著真實而徹底地消滅那「生來的罪」，並將所有個人的力量，如智慧、意志、情感、動機等疏導，引進持久地愛神愛人的行動中，使心靈得著最後的滌淨。主觀來說，這完全的生命是靠賴聖靈直接的啟迪，讓信徒醒覺到自己在純全的愛中內心已完全被改變過來，以致愛成為他內心唯一的動機，而且他在每一個清醒的時刻，都從熱切的心靈裏發出禱告、歡欣和感謝。故此，達致完全是一條教義，這教義關乎聖靈在我們內心的具體工作；透過這工作所產生的，是一種有意識經驗的獨特模式。我們已經談過，衛斯理的思想是從兩個步驟而來的：第—，主要是他早期從希臘教父的完全生命觀念結晶出來；第二，他從在愛打士基街頭（ Aldersgate Street）的經驗推論出完全生命並非靠行為逐漸塑造而成的，反而像稱義一般，單單藉著信心和透過恩典，從神即時領受的。對於非衛斯理派的抗辯宗信徒，這達致完全的教義引起一些主要問題。

　　這是什麼問題？讓我首先聲明，我並沒有計算衛斯理表達他的觀點時的混亂和煽動之處——雖然這些弱點事實上在兩個世紀以來，已經引起許多誤解和誤導的批評。其實，衛斯理稱那從許多立場看來都不完美的境況為「完全」，的確引致混淆。再者，他主觀地把罪定義為「對某條律法明知故犯」，而不是客觀地下定義，把罪視為不管有意識或無意識、受意志控制或不由自主地達不到神啟示的標準；這也形成混亂。最後，他提到成聖的人就是無罪的人（因為他們不含蓄意干犯律法），但同時，他肯定這些基督徒每時每刻都需要基督的寶血去遮蓋他們的缺點；這真是混亂至極了。衛斯理堅稱按著神「完備律法」8 的客觀標準，每個成聖的罪人每天都需要求神赦免；這似乎與他所堅稱基督徒有更高尚完美的無罪生命自相矛盾。難怪由往昔至如今，那些認為基督徒應在神面前自覺一無可取的，都感到衛斯理頭腦糊塗、思想錯謬！誠然，他絕對可以避免採用「完全成聖」和「無罪」等字眼，仍能清楚解說他的教義；雖則在聖經和傳統裏我們都找到這些辭彙，這也不能成為他的藉口，去解釋他為何縱使看見這些辭彙所產生的混淆，仍然一意孤行或感覺遲鈍或好爭鬥地（真不知道該用什麼形容詞最恰當）堅持運用他們。

　　從這刻開始，我嘗試做衛斯理早應做的工作，把他的教義稱為「賦予完全的愛」，或簡單稱為「完全的愛」。於是，我可以減少那些單從字彙引起的問題，而自由地專注於觀念本身內蘊的困難，其中我看見四點。

　　第—，援引的聖經根據不能使人信服。衛斯理引用的經文（參注 5）是對聖潔的應許和呼召，其中表達出一種確信，就是神有一天會拯救他的子民脫離罪惡；或是援引新約聖經的宣告，表明基督徒已在某程度上真正脫離罪惡。衛斯理斷言一些應許可在今生完全及絕對地應驗，還援引有關的宣告，加上一些禱文和命令，去支持他的結論。這些宣告除了顯出罪人的重生帶來相對的罪中釋放，以致罪不再在他生命中作工外，不能再顯示些什麼。此外，從這些宣告看來，神要實現他拯救的應許時所要求於我們的，除了重生的重大改變，然後逐漸成聖（衛斯理看成聖是在賦予完全的愛之前和之後開始的），繼而得著心靈上最後的滌淨（衛斯理期望所有未曾進入完全的愛的聖人，在臨終前也經歷這最後的滌淨）外，我們再也看不出有更多的要求。再者，神呼召人成為聖潔，以及人祈求成為聖潔，除了證明完全的聖潔應當是我們的生命目標外，實在不能再證明些什麼。

　　他在一七六五年的講章「聖經中的救恩之道」（“The Scripture Way of Salvation” ）結束時，變得能言善道，呼籲基督徒尋求完全的愛，就是此時此地在基督裏，也藉著基督，蒙他白白的拯救，完全脫離罪惡。「那麼，每一日、每一時、每一刻都追求這完全的愛吧！何不就在此時此刻？……倘若你憑信心追求這完全的愛，你自會期望照著你的本相尋獲他。既若是照著你的本相，現在就期望得著他吧！……還等待什麼呢！基督已經準備好了，他就是你所渴求的。他正等待你的回應！他就在你的心門外！」 他的講法好像是這恩賜早就在那裏，只要信徒祈求就唾手可得。可是，根據聖經，要回答衛斯理的問題「何不就在此時？」答案是神應許這完全的愛要在天國裏才圓滿實現；我看不出有什麼聖經基礎能支持說基督徒可在今生先嘗這完全的愛，更遑論什麼確據呢！在這一點上，衛斯理對救恩的解釋錯了，他的觀點等同於現代有關天國的討論，稱為實現終末論：他未能正確劃分在神的拯救工作中，什麼是現在的，什麼是未曾發生的。

　　第二，他的神學理論是不符現實的。客觀來說，他解釋培養或誘發完全的愛，即是從心裏把惡欲完全消滅及根除。衛斯理認為這種道德本質的改變，也同時包含肉體本質上的神秘改變，這在他一七五九年所解答的一條問題中反映出來，問題是：「若然兩個完全的基督徒生育兒女，父母既然無罪，兒女又怎麼會生在罪中？」他接受這問題，然後作答如下，答案聽來有點兒奇特：

　　這個情形可能會發生，但機會極微。我倒很懷疑從前有沒有發生過，將來也恐怕不會出現。「為什麼呢？」撇開這點不提「！」，我的答案是：我之所以受罪污染，不是從父母繼承，而是承繼自第一個父母［亞當］。……我們可從園藝得到一個很好的說明。在野生酸蘋果的枝幹上接枝種植，我們可以培植出優良的果實；但假若將這果實的果核種在土裏，會有什麼事情發生呢？照樣種出慣常的酸蘋果。

　　正如素頓（E．H．Sugden）所觀察的，衛斯理視「罪惡為一件要從人身上取去的東西，就好像一個毒瘤或一隻壞牙。 」11 所以，衛斯理和他的弟弟查理說到要賦予完全的愛就得將罪惡根除時，他們所說的，正是字面的意思，同時也包括身心兩方面的意義。

　　但是照這樣來說，一個「完全」的人，或沿用衛斯理的用語，一個「成聖」的人應該沒有可能在試探中「被自己的私欲牽引誘惑的」（雅一 13 一 15），因為依照他的理論，罪已經在人心中徹底根除，又何來私欲——如放縱自己、沒有愛心、只顧自己利益、藐視神等——呢？現在，他應該置身試探之外，他性情裏的乖張、不守法和潛藏的不仁傾向，應絲毫不能誘惑他，就好像對未墮落前的亞當或主耶穌基督一樣，起不了作用。

　　可是，經驗告訴我們，就算最聖潔的人，在他一生的年日中，對人對事仍免不了流露出不仁愛、不道德的表現，有時甚至作出狂暴的反應；這些傾向仍舊僭藏在他們裏面。事實上，他們的聖潔本質上包括了不斷抵抗和壓制這些本能反應——這些反應隨時以一種連本人也察覺不到的形式被引發出來。這亦即是清教徒所謂「腐敗」（意思是在千變萬化的偽裝中，自我崇拜和自我服事：老年人、中年人和青年人的罪，過分投入或過於冷漠、過分敏感等等）；種種腐敗常被新的刺激誘發，因而亦不斷有使人降車、叫人羞愧的自我發現。那自稱已達致完全的人被司布真一語道破，他事前是否曉得有人忽然使勁地踩他的腳趾一下後，他會何等憤怒，我們並不知道，但我們卻知道梅亞（F．B．Meyer）——一位浸信會的聖徒——曾記載他在中年的晚期，看見群眾不再擁戴自己，轉聽摩根（G．CamP－bell Morgan）的講道時，他發現自己被嫉妒所侵蝕，他為此感到刻骨的震驚，因為他向來以為自己是對嫉妒免疫的。

　　因此，我們怎會以為可以找到一個基督徒，能倚仗過往特殊的福分，就永不會再遇上像梅亞那樣令他降卑的經驗？現實肯定迫使我們說，沒有任何一個基督徒——姑勿論他此時或將來如何全心全意地愛神、愛鄰舍——可免疫於更深一層暴露自己的罪惡本性時所引致的震驚。故此，衛斯理以為信徒可在今生裏根除自己的罪惡，實在與現實不符，該受摒棄；若有任何基督徒設想這已發生在自己身上，他一定是自欺。

　　這直接帶領我們去看衛斯理教義的另一個難題。

　　第三，他教義裏隱含的實際意思並不造就人。教義中有不少矛盾，卻又苦無滿意的解答。最主要的兩難境況已在剛才提過：基督徒若果相信罪惡已從他們內心根除，又該怎樣面對他們仍繼續犯罪這事實呢？衛斯理的教導使他們不能面對現實。然後，又出現另一個兩難境況：這樣的基督徒應否見證他們所承受的福分？倘若要，又怎樣作呢？不作見證無形中是強奪了神的榮耀和人得幫助的機會，甚至是為逃避麻煩的懦夫表現；可是，若照衛斯理所設想的作見證（「我已感覺不到罪，只有爰；我永不止息地禱告、喜樂、感恩。在我內裏清楚地見證我已經完全更新了，即如我已稱義一樣。」 13），又似乎會無可避免地把自己困鎖於一點也不可愛的沾沾自喜中。

　　衛斯理是一位出色的牧者，他優良的教牧意識透過他在這個問題上的掙紮顯露出來：「一個『完全更新』的基督徒，應否講述那曾發生在他身上的奇妙事情呢？」

　　「也許，起初的時候，」衛斯理寫道：「他會情不自禁，因他內裏的火焰燒得燙熱；他熱切渴望宣告主的恩慈，這熱望如一股急流把他卷去。但事後，對未認識神的人最好不要多說，……若沒有特殊原因和企望，他對其他人還是不要多說。之後，他應該尤其小心，儘量避免一切炫耀的空言，反而以最深的謙卑和崇敬，將所有榮耀歸與神。這其間，他寧可用生命而不用舌頭去說服人。」 

　　毫無疑問，這表現出良好的教牧修養，可惜仍未足夠！這裏，衛斯理自己成了他誤解罪惡可根除之說的受害者。事實上，他經常查案會眾所經驗的所謂完全，又鼓勵他們在循道會的聚會中作見證，以他們現已在完全的愛中被建立的一套語言來表達。這或許會產生令人沾占自喜以及與現實脫節的結果，而衛斯理對此有多少認識呢？這是個爭論不休的問題。牛頓·夫路（ R．Newton Flew）也很奇怪為何衛斯理常常鼓勵別人宣認完美，自己卻不這樣：「……這是不是基於一點吹毛求疵，抑或在不知不覺間懷疑到這公然的宣認會危害靈性健康呢？」15 我懷疑最主要的原因是衛斯理十分瞭解自己，即使他堅決地全然委身，在神的愛裏喜樂，對人滿懷好意，罪仍舊在他裏面活著，所以他深知這樣的宣稱是不誠實的。可是，我們不能一方面因為衛斯理沒有讓他深愛的教義淩駕他個人屬靈感性而喝采，另一方面又沒有因為他的完全主義無意地使別人的敏感性遲鈍了，並使人在這一點上存有基本上與現實不符的態度而感到遺憾。毫無疑問，像約翰·衛斯理這樣備受尊崇的領袖，他所強調和期望的，當然會在那些溫馴的、易受暗示的追隨者身上產生巨大的制約性影響。

　　第四，他的教義無可避免地與羅馬書七章十四至二十五節大相逕庭。保羅在第十四節從過去時式轉到現在時式的寫法，除了說明十四節以前是講述他成為基督徒之前所經歷到神的律法在他身上的影響，而十四節以後是講述他執筆時的經歷外，沒有更自然的解釋了；有人認為保羅的溝通技巧未到家，無緣無故、毫無意義地轉變文法句式，這些都是對他大大的誤解。他們更以為七至二十五節中的「我」並非保羅自己，只不過是虛構人物。一貫善於溝通的保羅，在這裏忽然變成如斯蠢笨，實在令人難以置信。可是，若然這些字句「我覺得肢體中另有個律和我心中的律交戰，把我擄去，叫我附從那肢體中犯罪的律」（羅七 23）所指的是現在，那麼，保羅的全部經驗顯然並非完全的愛；罪至少在功能上正在他裏面動工。以衛斯理的說法看來，他尚未達致完全。

　　衛斯理以及一些希臘教父和葡萄牙的亞米紐斯主義者，都把七至二十五節解作保羅未成為基督徒以前的經驗。但這觀點無法解釋時態上的轉變，亦解不通第十八和二十二節——保羅同來「立志行善」的能力？怎能夠有意識地喜悅神的律法？（試看八章七、八節怎樣描述「屬肉體」的人的心思意念！）而且，依據此看法，保羅是現在被拯救脫離罪的權勢，他感謝神之後，總結整個處境說：「這樣看來，我（不是修正標準譯本「RSV」的「靠我自己」「of myself」，而是「我這個人」「I the self same person」）以內心順服神的律；我肉體卻順服罪的律了。」（羅七 25）這又怎麼解釋呢？照衛斯理式假設來看，這節聖經唯一最自然的意思是所需的拯救尚未曾賜下，但這樣解法就使這節經文前後矛盾了。（衛斯理惟有迫於說經文的上半截「靠著我們的主耶穌基督」只是加插進去的，與下文並無邏輯上的關係，16 不過這種說法似乎有點牽強。）事實上，對於這幾節經文，唯一較連貫的闡釋是奥古斯丁主義者的解法；他們的觀點以前已經陳述過了。可是，仍有一個解法是可以使奥古斯丁主義者的闡釋與衛斯理的教義投合相融的，就是假設保羅也像衛斯理一樣，基於某些原因錯過了這大好福分，惟有講出自己的缺欠，但肯定沒有什麼人會認真願意維護這樣的觀點。

　　那麼，讓我總結，衛斯理的教義認為藉著聖靈，對信仰作出回應，就可以在此時此地立即達致完全；但在新約聖經裏，我們無法找到這思想。完全的愛——完全脫離任何摻有罪惡和追求私利的動機——就是天國應許的生命，然而不管信徒對神對人的愛心有多麼深厚，在世仍是無法達致這完全的愛的。我們若教導基督徒從任何現在的靈性提升境況，去推論所有罪惡的欲望從此永遠消除，就犯了具破壞性的錯誤；這推論是錯的，那些持定這推斷的人或多或少把自己宣判了道德和靈性上的不切實際。儘管如此，追隨衛斯理教義的聖徒仍能夠照耀出聖潔的光輝，但這並不是由於他們相信罪惡已根除所達致的。

　　然而，衛斯理對基督徒性情存著高貴的理想——全然喜樂、感恩和愛——，這理想對於任何受試誘去滿足於次等東西的人是一種譴責。若有人認為衛斯理對完全的愛的教義單單是見證湯姆·查麥士（ Thomas Chalmers）後來所稱為「帶有驅除力量的新感情」——即是說，這教義告訴我們，我們被神的愛呼召和救贖，以致我們愛父和耶穌，這愛為我們驅走尖刻、怨毒和驕傲——，那麼，這教義只有帶著蹂躪的力量，暴露我們的委身仍存有膚淺、自我沉醉和放縱自己的原素。

** 凱錫克信念：中途宿舍

　　所謂「凱錫克信念」，是指大約一個世紀以前一種修正版本的衛斯理觀點，這觀點回避了因宣稱神第二次決定性的恩典能根除基督徒心裏的罪而引致的批評。也曾有人稱他為「得勝生命之道」；這名稱今天仍沿用。正如我先前提過，建造這個架構的建築師，就是美國的長老會人士，諸如貴格會漢娜·韋杜 （Hannah Whitall Smith）的丈夫史密夫（Robert Pearsall Smith），和英國的聖公會人士，例如賀堅斯（Evan Hopkins）和慕勒（H． C． G Moule）主教；而所以稱為「凱錫克信念」，是因為這是自一八七五年開始，每年一度在英國湖區凱錫克舉行的「屬靈生命進深」大會上教導的信念。雖然到了今時今日，「凱錫克信念」已沒有多大的指導性地位；但事實上，凱錫克大會就是為這個目
的而設立的。

　　凱錫克信念縱然以多種模式和形式出現，他源自保羅在羅馬書六章一至十四節所說的話。使徒在經文裏宣告基督徒「……向罪也當看自己是死的；向神在基督耶穌裏，卻當看自己是活的」（11 節）；「我們的舊人和他同釘十字架，使罪身滅絕，叫我們不再作罪的奴僕」（6 節）；所以我們「將自己獻給神，並將肢體作義的器具獻給神」（13節）。由此，一些教師如史密夫推論出一種邁向「更高生命」或「至高生命」的方程式；在這樣的生命裏，儘管人心還是充滿罪惡，但人心中那些不應有的欲望和道德上的軟弱，已無法把人拖累下去。很明顯的，在十九世紀中葉，一般信徒對「向罪死和向神活」的理解，是形容基督徒悔改和決志的比喻（參加五 24），尤過於把他視為宣告，表明神已經在基督裏使信徒成為新造的人。對史密夫和其他人來說，這似乎是一種啟示，叫他們認識到保羅在這裏真正要說的，就是基督徒已經在他存有的本體上根本地被更新和改變，以致罪惡現在已不能像從前一樣支配他。我們應為他們已掌握保羅的資訊而高興！

　　但他們應用這真理的方法是怪異的。他們並不像保羅在第十三、十四節所言，將以上的資訊作為呼召我們去實踐公義的基礎；反之，他們視他為呼召我們去得著信心的基礎，而這信心又有特殊的意義，照他們的理解，信心是需要刻意地毫不費力（他們稱之為「歇息」），而被動是形容這種狀態唯一最自然的說法。照此理解，他們說信心是聖潔的大秘訣。他們對信心的詮釋是：第—，有意識地及持久地相信自己實在已向罪死了，向神活著；第二，每時每刻有意識地及持久地藉著聖靈倚靠基督戰勝罪惡，並喚醒自己生命裏的義；第三，在每一次罪惡的試探中，特別運用聖靈的能力，祈求基督提升自己，使自己超越試探。他們說，缺乏了這種信心，人永不能經歷脫離罪惡支配的自由。人可以嘗試單憑己力，靠賴自己的天賦去做正確的事，但他肯定會失敗，而且是活該的，因為事實上他的心態是驕傲、無知的，並且不相信在他心裏居衷的救主的能力。

　　故此，這些教師們高唱「靠著信心在耶穌裏成為聖潔，並非靠自己的力量」；他們抨擊教會教導信徒或至少容許信徒相信稱義是憑信心，而成聖卻是靠行為的；他們譴責所有刻意去順服的行為，認為這表現了人單憑己力；又指斥所有為了要有正直的行為而付上的努力都是「肉體的精力」（這句話很快就在他們的教導裏成為口令）；他們屢屢堅持信心的道路就是有意識地讓基督在你裏面工作，並藉著你作工，而不是嘗試靠自己
去工作。

　　他們這種教導使聖潔的表現成為智慧和屬靈的技巧。每當罪性發動，（他們說）你若直接抵擋他，你一定會被擊敗，但若然你把他們交托基督，他會為你得勝，而你亦能安然無恙地生活下去。因著內裏不拚命頑抗，凡事只仰望基督，就可達致完全。（當只有基督作工時，還可有其他結果嗎？）人如此行，雖然未能免除他內心洶湧翻騰的罪惡，他卻可得著拯救，不致真正犯罪。固然，人的罪性（這些教師所強調的）不會在這世上完全得以改變；然而人的罪欲不管怎樣頑強，只要人意識到自己的軟弱，學會每時每刻祈求基督掌管他一切心思意念，那麼，聖靈的能力會引導他外在的行為，全然消解他內裏的罪欲（「消解」「counteraction」是凱錫克信念中的一個術語）。

　　於是，凱錫克教師們一方面認為將完美等同於無罪的心是一種異端，而拒絕接受，另一方面，他們卻又宣稱無罪的行為（意思是意識到自己已從所有自知的過犯中釋放出來）就是完全的表現。衛斯理相信神會在今生賜下完全的愛，這點是凱錫克教師們所不接受的，然而他們卻同意衛斯理所持定關乎「罪（意指人故意觸犯已知的律法）」 的觀念，並根據這觀念去描述基督徒生命是潛藏了完全及永遠勝過任何試探和軟弱的能力的。他們教導人不要為達致聖潔而奮力掙紮，只要在神面前經常承認自己的無能，並信靠耶穌，就可進入始終「得勝、喜樂和榮耀」的「更高生命」裏；這生命的內涵，是國歌對元首的偉大歌頌所不能比擬的。這些教師說，勝過罪惡、在耶穌裏喜樂，以及完全讓神掌管的生命，都是人可想像得到最豐富的產業；這是福音的應許，透過聖靈，賜給所有屬基督，又懂得憑信心而活的人。

** 凱踢克信念的優點

　　在我們繼續討論之前，應該說幾句欣賞的話。

*** 凱錫克信念面對真實的困惑
　　你知道什麼是善，什麼是你要作的，你也知道什麼是惡的，什麼是你不要作的，可是你仍舊想去作。那麼，你該怎樣？蘇格拉底說過，德行就是知識，這知識使你自動自發去做你所認為對的事；但幾乎所有人都經歷過知而不行的矛盾，這就證明瞭蘇格拉底是錯誤的。奧維丟（OVid ）是異教的羅馬詩人，但當他說他雖然知道也贊同什麼是更好的，他實際卻追求那更壞的時，他明確地表達了人意志薄弱的問題，激起每個有點兒自覺能力的基督徒心裏苦惱的共嗚。至於保羅在成為基督徒之前之後，如何經歷這種困惑，我們亦已經討論遇了。每一位牧者都知道人大多有心持兩意的毛病，有如傷風感冒一樣普遍，無力去駕馭心裏的兩個拉力，在眾多願意向善的生命中，形成一塊巨大的絆腳石。凱錫克信念將這個問題顯明出來，並直接提出解決方法，是值得我們稱許的，即使我們未必同意他們提供的答案。

*** 凱錫克信念面對真實的陷阱
　　這信念正確地告誡人不要單憑自己而不去禱告。他剖析了憑自信去追求公義和發揮功用，都是血氣之勇，也堅持這種力量是貧乏空洞的；在這方面，凱錫克信念一矢中的，值得嘉許。

*** 凱錫克信念注重真正的權利
　　信徒與基督同死同復活，因而產生心靈的改變，這其實是人從罪中釋放並得稱為義的根源（羅六 14、17、18、20 一 22），也是激發基督徒因對神存有感激之愛而樂意順服神的原動力（羅一二 1）。為了對抗自然主義者的伯拉糾派觀念，認為聖潔是人類的一般道德，凱錫克信念正確地強調成聖是清教徒馬素（Walter Marshall）所謂「福音的奧秘」19（即是恩典的超自然作為），而聖潔的生命是無法在聖靈的內在工作以外達成的。這方面的強調也值得嘉許。

*** 凱錫克信念是對有血有肉的人說話
　　這是無可爭議的事實，一個世紀前如此，今天亦如是：無論是什麼原因，許多基督徒總不愛以悔改（從罪中轉向神）作為他們日常生活的基礎原則，因而靈性軟弱、枯乾和遲鈍；他們最需要的不外是自我反省，謙卑下來，接受挑戰，將自己完全分別為聖奉獻給神，亦即是完全表達出真正的悔改。凱錫克教師們經常強調，決定性的完全奉獻是憑信心經歷聖潔的先決條件，因為只有完全奉獻的信徒，才被聖靈充滿，亦只有在被聖靈充滿的聖徒心裏，聖靈的能力才湧溢自如，使信徒能夠勝過每個試探、成全所有的義。

　　誠然，凱錫克的語言——這種語言可以說是講壇上的語言，而不是神學反省的語言——總令人聽來感到像英國家居的食水供應一樣，採用地心吸力原理，如果樓上的水箱並未注滿，扭開水龍頭就不會有食水流出來。凱錫克教師們經常講及「聖靈充滿」（這句用語曾以講道形式在弗五 18 出現，亦以描述形式在路一 41、67；徒二 4，四 8、31，九 17，一三 9 等經文出現），說起來就好像在聖經神學裏表達稱義，或像與基督同死同復活等關係上的用語般精簡和具終極性，顯然令人產生不少疑問。但凱錫克教師們呼召人完全奉獻，誠然對於一些鬆散停滯的基督徒來說，是強而有力及探索心靈的呼召，兼且在這要求全然委身的呼召裏，他們有效地擊破許多三心兩意、不冷不熱、被世界纏累、沉溺罪惡的信徒（「屬肉體」的人，正如保羅在哥林多前書三章一節稱他們為「屬肉體，在基督裏為嬰孩的」）的屬靈屏障。這是凱錫克信念第四個值得嘉許的特色。

　　很可惜，凱錫克信念卻有他缺欠的一面。

** 凱錫克信念所引致的問題
　　正如以上所說，凱錫克信念實質上是衛斯理完全主義的修訂版，只不過他摒棄了衛斯理教訓中那與現實不符的宣告——罪惡已經完全從成聖的基督徒心中根除。因此，雖然凱錫克信念在某些方面脫離了衛斯理主義，但他骨子裏事實上仍多方標誌著衛斯理主義從前和現在所堅持的特色：亦即稱義和成聖。新生和聖潔，都是藉著相同的方法賜予我們的獨特福分。那方法就是運用信心，不再單憑自己的能力工作，才可以白白領受基督的禮物，亦即是我們一直奮力追求的東西——一方面被神接納，另一方面達致順服。

　　我相信連衛斯理本人也會大吃一驚的（雖然這不過是他一直堅稱追隨的亞米紐斯主義「Arminianism」的自然發展），就是在十九世紀，衛斯理信徒清楚明確地以人為中心的精神，將神的救恩包裝成兩份不同的禮物，各自蘊藏著一項恩典工作——第一項是基督使人稱義的工作，第二項是基督使人成聖的工作。在十九世紀中期和末葉，透過「聖潔復興」運動（凱錫克信念使這個運動更加如虎添翼），這個把救恩一分為二的觀念——一種救恩救人脫離罪咎，另一種救人脫離罪的勢力——成為了在路德宗信徒和加爾文派信徒以外所有福音派信徒的標準思想，甚至今天在一些信徒當中仍舊流傳。

　　我有時聽見他最後的殘喘（至少是最近期，但我希望這真是最後的了）：有些信徒說選擇做一個「屬肉體的基督徒」——即是接受基督作救主，但不接受他作聖化者——是一個任意的選擇，即使所選的並不是最好。如此拆散神在他獨生子身上結合的中保職分——即是祭司、先知（教師）和君王——正是把神的救恩分開包裝的結果（可以說是苦果）。

　　說句公道話，原本的凱錫克信念並非如此走歪的。雖然他把救恩分裝成兩個小包，但他沒有提出基督徒可自由選擇前者而捨棄後者（即是有信心而沒有侮改，得著救恩而沒有成聖）。反之，他認為神呼召信徒成聖的權威是自明之理，進而直接問道：「我們應如何回應這呼召？」不過，凱錫克信念帶著衛斯理觀念的框框，這就引起問題了。

*** 凱錫克信念如何闡釋羅馬書第六章？
　　凱錫克式閱讀和應用羅馬書第六章一至十四節（事實上，是六章一節至八章十三節，這段被視為一個獨立單元，指示怎樣在生活中不犯罪）的方法，是將上述觀念框框強自套進經文裏的結果。換句話說，是將稱義和成聖視為分別領受的不同福分，是藉著相應的信心行為而獲致的。保羅在羅馬書六章回答那具有雙重目的之問題——稱義的人是否應該實踐公義？他們為何要實踐公義？可是，套上衛斯理式框框去閱讀經文，整章聖經遂變成保羅對以下問題的回答：「怎可成功地尋求義？」再根據凱錫克信念，答案如下：要外在的生命達到聖潔，必須內在的生命先領受成聖的福氣——意思是你必須進入那得勝的生命中，即那經常藉著信心而持續勝過罪惡的生命。因著把自己完全奉獻予神，你便與這生命接連了（這假設了你從前沒有如此奉獻過）。自此，只要記若你已經與基督同死同復活，他也藉著聖靈住在你裏面，你就活出這生命來；而且每當你發現罪惡又蠢蠢欲動時，你可在這信心的基礎上祈求，並讓基督為你打敗罪惡。如此持續地奉獻自己和運用信心，是你要盡的本分，你只管付上，你信實的主自會動工。這樣，你就會嘗到從罪釋放的經歷；這是所有在恩典下重生的信徒所享有的權利。你活在這新經驗裏（至少對於你是新的），會嘗到前所未有的平安、喜樂、靈性成長，並對別人有所貢獻。這就是凱錫克信念所詳論之「危機後的過程」，亦即是他們認為保羅在羅馬書第六章所揭露的聖潔之謎（一至十四節，尤其是十一至十四節與十二章一至二節並行，表達那危機；而十五至二十三節則描述那過程）。根據凱錫克觀點，這就是「合乎聖經的聖潔」（注意這是從衛斯理借來的用詞！）。

　　究竟凱錫克信念應否為大西洋兩岸隨之興起的屬靈精英主義——自以為知道獨家的屬靈奧秘而產生的優越感；那內望的、反智的挑剔，並自嗚得意地使用「平安」、「喜樂」、「安息」和「祝福」作其嗡嗡之詞——而受責備，這是頗具爭論的。這教義可能吸引了一些在性情上有此傾向的人，若是如此，他們這份靈糧最差勁之處，就是他似乎未能改正這些不成熟的表現和屬靈的驕傲。但我想有一點是無可爭議的，就是在以上所述的事情上，凱錫克信念在一些立場上是公開接受聖經和神學上的批評的。

*** 對聖潔存有狹窄的觀點
　　凱錫克信念在闡明聖潔，從而建立基督徒的道德理想上，距離目標還很遠。他捉摸不到奥古斯丁對生命的異象——藉著讚美、順服、事奉和對價值的追求來榮耀神；也掌握不到衛斯理對神對人熱誠而無盡的愛。反之，他主要集中在生命的消極理想上，就是要脫離那可望而不可即的道德標準所帶來的張力，不用再因未達到應及的標準而受良心的譴責。他們的目標是無間斷的喜樂和平安，其實與達致公義沒有多大關係，反而與逃避道德上的挫敗感更有關連。但這理想肯定是以自我為中心，多於以神或鄰舍為中心的，而且他妨礙道德感和屬靈敏銳程度的培養，多於促進他們的增長。以現今的快樂為現在的目標，並非合乎聖經的敬虔之路。聖經沒有教導我們在與神同行、服事人群當中，追求一個平靜、快活、不紊的生命，全沒有痛苦；我們也不能從聖經中找到根據，去支援我們這樣的期望或追求。可是，這基督徒版本的中產階級世俗夢想，卻是傳統凱錫克信念的迷惑之歌。無疑，在歷史上，凱錫克運動是資產階級、富人紳士的事情，也是白領階層和社會上自嗚得意者的玩意。為何這許多現代福音派人士，對於鄰舍的需要，較諸其他基督徒反應遲緩？看見神的榮耀在現今世代裏受虧損仍無動於衷？部分原因可能是經過基督徒三代以來彼此投射凱錫克式的生活理想，以致我們在這些要點上變得麻木了。

*** 太多和太少
　　凱錫克信念在闡明聖靈使人成聖的工作上，也是失敗的，因他似乎同時肯定了太多和太少。我說「似乎」，是由於建構凱錫克工程的建築師，是一般平信徒和牧師，他們在議程中定意保留衛斯理式「第二次祝福」的架構，卻擺脫衛斯理式的完全主義；但他們為了達到這個目標而建立的觀念，正可能忽略了其中較寬闊的神學含意。可是，我們若按表面意義來理解他們的話，以上的評語是無可推諉的。他們事實上肯定了基督徒行為的完全，同時又否定了人悔改以後，神會進一步改變我們的心；這兩樣都是錯誤的。

　　首先，凱錫克信念應許基督徒能勝過任何已知的罪惡，是超乎新約聖經讓我們在今世所期望的（參約壹一 8 一 10；加五 17；羅七 14—25；其中部分我已提過，稍後會再詳論）。基督徒現今的義是相對的，他們作的一切，還未達到完美無瑕的地步。在他最優良的表現背後，往往是太少的熱情和太混雜的動機；正如耶穌判斷法利賽人的表現時所顯示的，不理會背後的目的和動機，單單評論人的行為，這評價在道德上是不真確的（參太六 l— 6、16—18，二三 25—28）。再者，正如上述已經指出，基督徒永不會做了一件大好的事，以致他再沒有可改良之處。一個人嘗試完成神的命令，就好比音樂家演繹一套樂譜，或演員演繹一個劇本；即使他已施展渾身解數，盡可能有最佳的表現，甚至連自己也欣賞這演出，但他依然尋找得到可改善之處，因為一個誠實的演繹者，永遠是自己最嚴格的批評者。只有那些非常麻木和心智不平衡的人，才會想像自己所作的是完美無瑕的。只要基督徒願意在神面前警醒，又對自己有點兒認識，他就會明白我所說的，並且時常思想，也自然會謙卑下來。誠然，新約聖經預期基督徒的生命不斷成長時，他會愈來愈脫離已知的罪，然而說神應許基督徒此時此刻完全勝過罪惡，不但缺乏聖經根據，在屬靈上也不符現實。

　　可是，凱錫克信念竟許下這樣的承諾，卻又同時肯定我們必須期望從重生的一刻至我們在世生命的盡頭，我們罪性的心靈會保留不變，實在叫人驚訝。但這是第二個錯謬，因為他忽略了一個事實，信徒是逐漸「……變成主的形狀，榮上加榮……」，又要「心意更新而變化」（林後三 18；羅一二 2）。這是一個漸進的過程，當聖靈在他們的生命中工作時，他們對屬靈事物的渴望和辨識能力就會漸次加強，罪惡的欲念和習慣亦明顯減弱。在一定程度上，他們會意識到自己持續不斷的改變，亦能夠見證這改變。正如我前面說過，基督徒若從沒有這樣的見證，他屬靈的健康便值得關注，而且確實使人懷疑他到底是否重生了。

　　以上就是傳統凱錫克信念與基督徒道德生活現實脫節的兩方面。正如上述所言，我很希望相信那些發展了這些信念的人，從未想過他們那反衛斯理主義的熱情所引發的言論有什麼含意，並且真的不是按著這個意思而言；但這樣判斷他們是否公平，我也不知道。

*** 受被動所限制
　　凱錫克信念在闡明基督徒與聖靈的關係上，又再次失敗。他內裏有強烈的寂靜主義（quietism）質素， 20 而寂靜主義預定了他的被動心態。（編者注：寂靜主義乃一種神秘主義，是十七世紀末穆利諾斯［Molinos］在羅馬，以及蓋恩夫人「Madame Guyon」和芬尼倫「Fenelon」在法國發起的一種宗教運動。主張消除意志，站於絕對被動的地位，完全被神充滿。）寂靜主義認為我們任何形式的自發性行動都是屬血氣的精力；若然神要感動我們，他會在我們心裏提醒和約束我們，我們可分辨得到這些感動並非源自我們自己的思想和衝動，而且我們應常常追求將自我滅絕，好讓神的生命可以在我們肉身的皮囊內自由流通。好了，我們已知道在內裏任神引領，使我們產生聖潔行為這個見解如何在凱錫克的方程式裏運作。然而，這流派的成員究竟在除滅自我的教導上，有多大的成效？又當我處於被動時，究竟是我開啟神的能力（「使用」神），抑或神開啟我的力量呢？這種種令人迷惑的疑問，我們暫時不宜追索下去；這裏亦不宜詳論另一個問題，就是你在被動狀態中或藉若被動狀態去「使用」聖靈，實在含有前後不一致的亞米紐斯主義（Arminianism），就即如你「使用」你所駕駛的汽車，或「使用」你校正程度後開動的洗衣機一樣。現在我們必須指出，依照聖經的標準，這種思想架構是全然錯誤的，因為聖靈通常是透過我們的心思和意志工作的。他感動我們工作的方法是：先催使我們看見一些原因，以致我們肯推動自己去工作。因此，我們那有意識的、理性的自我，不單只沒有被滅絕，反而更剛強了；在恭敬的、堅決的順服裏，我們得著救恩，深知道神在我們裏面作工，使我們「立志行事……為要成就他的美意」（腓二 13）。這就是聖潔了。說得確切一點，在成就聖潔的整個過程裏，我們完全不是被動的。

　　被動意指有意識地不動——在這裏，也就是內在的不動。有時候，我們把別的意思讀進某些經文裏，說聖經呼召我們進入被動的狀態中——謹慎的、分別為聖的被動——；但實際上從這些經文一點也讀不出這個意思來。舉例說，將自己「獻上」或「獻給神」（羅六 13，一二 1），或者，我們有時愛說向神「降服」，或「將自己完全交托」給神，這些都不是被動。保羅的意思並不是說我們一旦將自己交托給主，我們就應該落入不動之中，等候基督來感動我們；反而，我們應向神報到，讓他委派我們工作，一如保羅在大馬色路上所說：「主啊，我當作什麼？……」（徒二二 10）而且毫無保留地讓基督藉著他的靈透過他的話語指引我們工作。這是主動的！再者，「被神的靈引導」（羅八14；加五 18）也不表示被動。保羅的意思不是說我們應該什麼都不作，等候天上的指示靈機一閃地進入我們的腦中；反而，我們應該堅決地以禱告和努力去遵守基督的律法，並治死罪惡（參加五 13 至六 10；羅八 5 一 13）。這也是主動啊！

　　我們無需再多談了，重點是顯而易見的。寂靜主義者以為處於被動的地位便可以釋放聖靈，其實反而阻擋聖靈，銷滅他的感動。慣於被動的靈魂，不但沒法興旺，而且愈來愈衰弱。基督徒的座右銘不該是「隨遇而安，任神工作」，反該是「信靠神，不斷前進！」故此，舉例說，倘若你正要矯正一個壞習慣，你就得在神面前定下一個計畫，使自己不再陷入惡習的圈套中，並求神祝福你的計畫，讓你靠著他的力量向前邁進，隨時準備對試探說「不」！又或者你想養成一個好習慣，照樣可以在神面前定下一個計畫，求神幫助，然後盡力而為。可是被動的心態卻剛好背道而馳，凱錫克信念主張被動（「不用自己掙紮，凡事交托主。），其言下之意是不合乎聖經教導的，也阻礙基督徒邁向成熟。

*** 拙劣的教導
　　以凱錫克信念來牧養信徒，會帶來不堪設想的後果。這第四項失敗最令人傷痛，尤其是凱錫克信念的本意是幫助牧養的。他所教導的被動和所宣告的期望，都是不切實際的，再加上他堅稱人若不能過完全得勝的生活，是由於自己的過失，凡此種種，令凱錫克信念極具破壞性。我明白其中的問題，我也曾受這種信念薰陶。我想最簡捷的方法就是在這裏分享我的經驗，讓我節錄我於一九四五至四六年間在牛津所寫關於我初信主時的掙紮，我用了第三人稱的寫法來描述：

　　這是他的困惑：他聽過，也讀過他的教師們如何形容持續勝過罪惡的情形。所描述的一幅圖畫，是基督徒內心平靜，滿有能力，被聖靈充滿及引領，永不跌倒，又被聖靈感動和加力，為神成就超乎自己能力的工作。將自己交托、順服和奉獻予神，是唯一命定的道路。……可是這個學生嘗試跟循指引時，就感到自己猶如一個多年來嘗試全心全意拚命去穿越一堵磚牆的癮君子。他嘗試完全奉獻自己，結果落得這樣的光景——一個不成熟的、情感被激動翻湧的年青人，痛苦地認清自己，一如青春期的少男少女，每天在不滿與挫折中翻滾，不斷爭戰，尋找出路。……那些倒空和獻上自己的基督徒理當嘗過之得勝與充滿能力的生命，看來是那麼遙不可及。

　　但是他應該怎樣做呢？根據這教導，基督徒之所以無法享受快樂的生命，是因為他們不願繳交入場費——換句話說，他們未曾把自己完全交托神。因此，他所能做的，就是一次又一次地把自己獻上，不斷削刮自己的心靈，直至腫痛、創傷，以期根尋那些因未向神交付而阻礙神的祝福沛臨的東西。他不斷感到自己錯失良機，加上不知自己為何時常失誤而產生困惑，就好像腳底長了一個疣，又或是鞋子裏藏了一塊細石般難受，每走一步，都因痛楚而畏縮。

　　幸巧這個人是一條蛀書蟲，在適當時候讀到一些書籍，成為他的救生索，指引他怎樣對待自己，又使他看見他從前所不斷尋索的，只不過是如鬼人般難以捉摸的東西。……可是，正如曾被灼傷的小孩怕火一樣，那不切實際的聖潔教訓給他帶來的可怕和痛苦經驗，時至今日仍深印他心裏，令他痛恨。

　　我就是那名學生，我當時閱讀的書，就是清教徒約翰·歐文第六、七冊文集（Goold’s edition），以及萊耳的《聖潔》（ Holiness ）……

　　好了，問題來了：個多世紀以來，成千上萬的信徒都能見證他們的生命被凱錫克信念更新了，我們應怎樣解釋呢？我相信，答案系於兩個事實。第—，凱錫克信念稱頌耶穌基督，並在他裏面的信心，以及他在人生命裏的能力；許多人就只能從中聽到這麼多，再沒有其他。他們沒有察覺，也不著意理會凱錫克主要觀念的神學含意；即如英屬哥倫比亞人愛吃三文魚，英國人愛吃鹽醃或熏幹的鮭魚一樣，他們把魚肉吃後，留下魚骨。第二，誠如本書開始時說，不論人所持的神學觀念是好是劣，神是滿有恩慈的，凡真正尋求他的人，神就讓他們尋見（參耶二九 13；徒一○34、35）。現代抱官僚作風的人，除非看見人正確地填妥了申請表格，否則他們謹慎地不予人絲毫利益；但我們的神並非如此！我們應該為此高興。凱錫克信念感動了不少人更熱切地奉獻自己、更有生氣地渴求神幫助他們對抗罪惡；他們亦已尋獲所尋求的。哈利路亞！

　　然而，難道這些事實就可以為凱錫克信念中不盡不實之處辯護嗎？不。若你只能說：只要不大認真去接受這信念的細節，他會對你有幫助，那麼，這信念也並不真正值得推薦吧！反過來說，若你認真地接受這信念的每一細節，這信念不但不能幫助你，反會毀滅你，這樣說極之該死，但在這個情形下，我想我們還是必須這樣說。汽車製造廠會公開收回部分機件有毛病的汽車，因為他們會招致危險。我希望從前散播凱錫克信念的教師和團體能夠看見這信念的瑕疵可能對信徒有害，因而像汽車製造廠一樣公開收回他們的教導。

*** 羅馬書第六至八章的見證
　　第五（這一點在我看來是頂點的批評），若要以凱錫克信念來解釋和應用羅馬書第六至八章關乎已稱義之信徒的生命，那簡直是不可能的。我先前已指出，羅馬書第六章並非回答以下的問題：「已稱義的信徒怎樣可以過一個聖潔的生活？」而是解釋他為何必須這樣。這解釋由第六章開始，至七章六節。七章七節又提出另一個問題：誠如七章五節告訴我們，罪的欲念是由律法而生，那麼律法能否免被指控為有罪和邪惡呢？保羅從七章七節至該章的結尾，都解答這個新的問題。然後，保羅循著教牧書信的邏輯（八章一節的「如今」，似乎意指：「現在你們需要聽我說的第二件事是……」），展開神學性的熱烈討論，談及基督裏新生命的確據和實況：有「不定罪」的生命（1 節），不能與基督的愛隔絕（38、39 節），在現今沒有害怕（15、26—30 節，參看 32—36 節）。可是，在這些經文裏，保羅沒有嘗試解答以下問題：「信徒怎樣可以經歷完全脫離一切已知的罪？」同時，這些經文裏沒有任何可理解為保羅正在嘗試回答以上問題的證明。

　　再者，我們也不可把六章十三節「將自己獻給神」的命令理解為神召喚我們內心處於被動的狀況中。首先，「將你們的肢體獻給罪」（同一節，同一個動詞）根本不包含被動性，其次，在第十七、十八節裏，這種「獻」給神被清楚解釋為「從心裏順服了所傳給你們道理的模範……」，因而成為義的奴僕。這「獻」的命令（13 節）只是一個神學推論，是那啟示的真理——信徒在基督裏向罪死了，向神活著（11 節）——的必然結果。這不是一個召喚，要我們去經歷個人生命的轉捩點，以致我們的屬靈經驗質素完全改變過來；這只不過是一個淺白明確的聲明，說明基督徒應該做什麼。保羅在六章十一至十四節所費的筆墨，是直接回答第一節的問題：「……我們可以仍在罪中（意指仍舊做邪惡和不虔敬的事情，就好像未信主前的所作所為），叫恩典顯多嗎？」答案分為兩部分。十一至十三節實際上說「你不應該」；十四節（「罪必不能作你們的主，因你們不在律法之下，乃在恩典之下。）實際上說「無論如何，你不可能這樣」。你不應該這樣，因為你已經與基督一同復活，行在新的生命裏（13 節）；你也不可能這樣，因為你那愛罪、事奉罪的老我——亦即本性的你——已經與基督同釘十字架，已經死了（6節），換句話說，你的老我已屬過去（「在恩典之下」包含這個意思）。可是，在這裏或其他經文中，沒有提及內在的被動。

　　最後，若先決地抱著一種信念，認為已經奉獻、又被聖靈充滿的基督徒，可運用信心的技術，完全脫離一切已知的罪，我們便無法自然地理解羅馬書第七章十四至二十五節。我想最好視這段經文為一個活潑、健康的基督徒（保羅）一份典型而又坦白的自白書。他心裏的罪被律法鼓動，又同時被律法禁制和指控；這罪仍舊操縱他，使他默想時悲痛不已。這律法雖然是聖潔、公正、良善和屬靈的，卻沒有給他絲毫力量去對抗罪惡，原因是律法「因肉體軟弱了」（八 3）。凱錫克教師們對這段經文有新的解釋。他們認為這是一個基督徒的見證，這個基督徒試圖靠自己的力量戰勝罪惡，以致靈性上出現問題。他們又宣稱，只要人藉著奉獻和信心，掌握聖潔的秘訣，在他遇到試探的當兒，讓基督藉著聖靈工作，那麼，他就可以「由羅馬書第七章進入第八章。；他們亦特別把羅馬書第八章解釋為得勝生命的見證。慕勒（H．C.G．Moule）在《聖經評注》（Expositor ’s Bible，1894）有關羅馬書的部分裏，對以上的觀點提出最精深的論述——順帶一提，他改變了他的想法，因為早在《劍橋聖經》（Cambridge Bible）叢書（1879）裏，他採取了奥古斯丁的觀點來解釋羅馬書。可是，我們不能以凱錫克式釋經作為依歸。

　　首先，這是沒有根據的闡釋。保羅寫羅馬書七章七至二十五節的目的，不是教導有關基督徒的經歷，而是為律法洗脫有罪和邪惡的嫌疑；他舉引經驗，只不過想表明他的神學觀點，解明存在思想中的律法，與存在心靈和生命中的罪之間的關係。他何需在這裏毫無解釋或評注就描述那在凱錫克理論中基督徒不應有的屬靈狀況？在這部分裏，他指出一個要點：罪雖藉著律法發動，卻有別於聖潔的律法，且與律法為敵。若說十四至二十五節是要表明在基督徒的經驗裏，這種經驗非常真實，這較諸將十四至二十五節視為表達不及標準的基督徒經歷來得更加強而有力。反過來說，若然保羅在這裏只是指出某些不及標準的基督徒經歷，而不是按其普遍性而言，那麼，他只不過在提出一種不相關的界線，不但沒有使他的論點更加有力，反而把他削弱了。因此，這段經文的凱錫克式闡釋，是模糊地、扭曲地反映保羅的思想！

　　此外，保羅自第十四節開始，用第一人稱單數的現在時態去論述。固然，他希望這段描述是有代表性和普遍性的，也期望每一位收信的基督徒讀者或聽者在心裏共嗚：「是的，我正處於這種境況。」可是，這個事實卻正顯明以下的問題：「若然保羅寫羅馬書時，這一段不是他對自覺的真實狀態的描繪，他為何會如此分析呢？」難道我們應該假設保羅寫羅馬書第七章十四至二十五節時，屬靈狀況欠佳；但開始寫羅馬書第八章之前，他的靈性又提升至更高更健康的狀態中？否則，我們如何從凱錫克觀點去解釋保羅用第一人稱單數的現在時態寫法呢？

　　再者，在第七章十四至二十五節中，沒有任何經節符合凱錫克式的注釋， 22 那麼，既然無法從經文中讀出這種解釋，為何硬要將他讀進經文裏去？凱錫克解經家這樣做，無非是要挽救他們的理論，因他們認為由於罪在人的屬靈系統中仍舊活躍，使人煩擾、分心和麻木，以致人感到自己的敬拜和事奉未達致完全，而這種感覺是靈性健康的基督徒所不應有的。可是，我們已清楚瞭解不能接納這理論的原因，無論如何，加拉太書五章十七節已經與他相抵觸。事實上，我們完全沒有客觀的理由去引入凱錫克式注解。

　　還有，要是真的引入凱錫克式注解，會引致混亂。姑且將其他棘手的問題撇開，第二十五節已明顯與衛斯理式觀點不一致。凱錫克式闡釋是將保羅的「感謝神」解釋為慶賀此時此刻從第十四節所描述的境況中釋放出來。他又肯定這裏的動詞是現在時態或過去時態（「他救我脫離」或「他已經救我脫離」，“does deliver”or“has delivered”），而羅馬書第八章一至十三節告訴我們這拯救如何臨到——是透過聖靈的恩賜，聖靈就是那位為所有懷著信心的基督徒帶來勝利的使者。可是，第二十五節上下兩段又怎樣連接呢？保羅為現在的拯救獻上感謝後，怎可以隨即又說道：「這樣看來，我以內心順服神的律，我肉體卻順服罪的律了」？有些注釋書提出這個可能的答案：保羅受著內心感情的劇烈波動所影響，以致經文在邏輯上前後不一致，故此，他在二十五節尾才寫出二十三節未或二十四節前應該寫出的話。可是，這樣一位辭鋒淩厲、思想清晰的思想家小心翼翼地組織鋪陳這封致羅馬教會的書信時（這封信在外交上對保羅十分重要），竟然犯了這麼大的錯誤，實在令人難以置信。唯一恰當的處理，就是回到奥古斯丁式注解上去，那麼，問題就迎刃而解了。23

*** 總結
　　在前述的篇幅裏，已浮現了三方面的結論，一個是歷史性的，一個是神學性的，另一個是個人靈性方面的。
　　
　　歷史性的結論是，衛斯理式和凱錫克式關乎聖潔的教導之所以影響廣遠，主要是由於他們提供了所有基督徒都渴求的東西：前所未經歷過的更完全地脫離罪惡，並與基督更親密的相交。改革宗奥古斯丁主義強調基督徒持續的罪性，作為對抗憑行為稱義的部分論據，使人的罪性與成聖的盼望之間，形成了真空，因此這種教義就乘時竄進來了。人們聆聽這些教導，予以珍視，並緊緊追隨，並非因為他們使人在理智上信服，而是能夠迎合人心靈的需要。

　　神學性的結論是，聖經支持奥古斯丁主義，而反對那由奥古斯丁主義分支出來的衛斯理式和凱錫克思想，但聖經亦譴責奥古斯丁主義者過分渲染人持續的罪性，太少指出聖經中對人寄予的期望，就是藉著聖靈，人在道德上逐漸改變，更有基督的形象。

　　個人靈性方面的結論是，倘若基督徒藉著聖靈的能力，祈求神幫助他們更像耶穌，不管他們的神學觀念有多少缺點，他們都可達到。正如我們已經提過，因為他是滿有恩慈、最寬宏大量的神。

** 以基督為中心
　　本書以探索開始，為求建構一套比現時一些基督徒所持守有關聖靈的更佳神學。聖靈其中一個重要的職事，就是幫助信徒達致聖潔。在上一章，我們曾嘗試從聖經具體地建立一個思想架構，足以概括聖靈使人成聖的真正工作。在本章中，我們亦曾重溫三個有關聖靈賜予我們聖潔恩賜的主要福音信仰觀點，好讓我們欣賞他們的優點，又同時將一些能銷滅聖靈感動的意念清除。固然，上述的討論一定未臻圓滿。我沒有從社會層面看聖潔——如何聖化人際關係；我也沒有談到如何操練良心去明辨神的旨意；亦沒有嘗試處理禱告生活的問題；這些都是很大的罅隙，我現時只能暫且把他們擱在一旁。再者，我沒有將我的分析與我們的指導原則連上關係，這指導原則說明聖靈的主要新約職事，就是向我們、在我們裏面，並藉著我們榮耀基督，又催使我們活在基督裏，以他為我們的救主、我們的主、我們的神。或者，將這些線絡與上一章所述的連系起來的最佳方法是闡明聖經三項關乎聖靈的要點，這三點是從上述指導原則得出來的，而本章所重溫的各項事實，都有助闡明其中意義。以下就是這三個重點：

*** 1_聖潔是以基督為中心的生活
　　聖潔是作耶穌的門徒，聽從他的話，遵行他的命令，愛他，尊崇他為我們的救主，以他為我們的主來取悅他、榮耀他，並且現在作好準備，預備將來有一天要見他，與他永遠同在。奥古斯丁主義者深明此道，只是他們一向忙於與伯拉糾主義和亞米紐斯主義對抗，未有清楚把他表明出來。衛斯理主義也深明此理，查理·衛斯理尤其以無可比擬的神來之筆，撰寫聖詩來歌頌這個真理。凱錫克信眾亦通曉此道，他們經常強調「仰望為我們信心創始成終的耶穌……」（來一二 2），因而在凱錫克信念的實踐上，能夠避過他們其中一些神學理論可能帶來的壞影響。正直愛主的基督徒，即使可能被我這些複雜的論述弄得氣餒，也明白這個道理；他們就好像施洗約翰一樣，寧願自己衰微，卻高興看見他們的主興旺，他們會說出如懷特菲（ George Whitefield）講述自己的話：「讓懷特菲的名衰沒，但願基督得榮耀！」這種以耶穌為中心的表現，正是基督徒基本的聖潔樣式，也是聖靈在他所有使人成聖的工作中領人走向的目標。最聖潔的基督徒並非那些最關心何謂聖潔的人，而是那些把他們的思想、心靈、目標、目的、愛心和盼望，都最完全地集中在我們主耶穌基督身上的人。對於這一點，我們肯定可以贊同，也應該贊同。

*** 2_聖潔就是以遵行律法作為表達愛的方式
　　聖潔源自在基督裏認識那聖潔的神的愛。當聖潔的人注目加略山上的十字架時，他便深知道神以大能的愛愛他，於是他也盡力去愛神、愛鄰舍，來回應神的愛。在我們所檢討的三個傳統觀點裏，衛斯理主義者最熱烈提出這一點；而奥古斯丁主義者，如奥古斯丁、伯爾納和懷特菲，縱使他們在這一點上或許不如衛斯理主義者那麼思想清晰和熱情，然而透過他們的生命，這個精神已全然展露出來；至於凱錫克信念，由於他經常表現出一種宗教性的自我主義色彩，比其他兩個觀點更少著重這一點。可是，幾乎沒有任何一個福音信仰的基督徒會完全不會意聖潔的核心就是愛。

　　那麼，該如何表達對神和對人的愛呢？答案是藉著遵守神的命令，及持守他向我們啟示的人生理想——換句話說，就是遵行他在新約聖經裏為基督徒闡釋的律法。本著愛心去遵行律法，是達致聖潔的真正途徑。但這往往是一些忠於聖經的基督徒不能充分掌握的真理。一方面，總有些基督徒這樣宣稱：若聖靈居住在你心裏，你裏面自然有很強烈的愛的動力，你無需研讀聖經中神的律法，以求明白他的旨意，因為在任何環境中，你會自然而然知道聖靈想你做什麼。另一方面，亦常常有一些基督徒非常熱心遵行律法，以致他們的愛心枯乾，變成酷似法利賽人多於基督徒。在我們討論過的三個傳統觀點中，奥古斯丁主義者因著他們清晰地意識到地上國度的生活方式與在神國度裏的生活大有分別，加上很熱切地提倡全人基督化，最能夠把聖經中神的標準和旨意清楚闡明，同時堅持愛的精神——連同對神的頌贊——是基督徒真正的動力。衛斯理奉獻和博愛的倫理是高度個人主義的，但在其範疇內，他是合乎聖經和貫徹始終的。凱錫克信念往往傾向於假設你已經知道神的要求，而你唯一的問題是怎樣尋求力量去遵從，而且正由於凱錫克對美善生命的異像是（一般來說）敬虔和否定世界的（雖不能說是漠視世界），我們不
可能期望在這觀念影響下的人會細心研究神的律法。但在基本原則上仍沒有分別：這三個傳統觀點都認識到表達愛神和愛人的方法，就是遵行神的律法。

　　可是，這三個傳統觀點中，也許沒有一個充分強調耶穌基督就是道成肉身的律法，也賜給基督徒當守的律法——他的律法始自他在世上對門徒的教導，而以他從寶座上藉使徒記下的律法來結束。這是不爭的事實，而聖靈的基要工作，是引領基督徒遵行耶穌的教訓，並跟從他的榜樣，從而承認及尊崇他這兩方面的大能。一個世紀以前，福音派信徒由於自由派人士大談神的父性，故此對這主題避而不談；同樣，多個世紀以來，羅馬天主教一直強調仿效基督這個主題，似乎福音深信徒也因而避談這個題目。但是，這種「讓我們有所不同」的對抗原則，是絕少可以成就義的。事實上，聖靈呼召我們更努力去仿效基督，因為最真實的聖潔，是在品格和態度上與耶穌相似。對於這一點，我們也肯定可以贊同，且應該贊同。

*** 3_聖潔就是在信心生活中不斷經歷洗禮所象徵的與基督同死同復活
　　基督徒的洗禮，不論是浸禮、傾水禮或灑水禮，都要經過在水之下，象徵死亡，然後從「下麵出來」，象徵復活。而所象徵的死亡和復活是指到肉身（將來）和靈性（現在）兩方面的。靈性上的死亡和復活並不是在我們成為基督徒那一刻一次過成就的事情，而是不斷經歷「身上常帶著耶穌的死，使耶穌的生也顯明在我們身上」（林後四 10）。因為這就是我們一生的模式。為了耶穌，我們付上舍己的愛，願意順服，忍受痛苦和損失，因而每一日都進入千千萬萬的死亡中，又藉著聖靈的職事，我們從這些死亡中出來，恒常不斷重複經歷與基督同復活的生命。

　　耶穌，你是我一切：
　　是我勞苦中的安息，是我痛苦中的安慰，
　　是我破碎心靈的良藥，
　　是我爭戰中的平安，是我損失中的得著；
　　在暴君的橫眉下，你是我的微笑，
　　是我在羞辱中的榮耀和冠冕。
　　在匱乏中，你是我豐富的供應；
　　你是我軟弱中的大能，
　　是我在束縛中的完全釋放；
　　在撒但最幽暗的時刻裏，你是我的亮光；
　　你是我愁苦中不能言喻的喜樂，
　　是我死亡裏的生命，是我地獄裏的天堂。

　　查理·衛斯理如此描述他的經驗，我恐怕再沒有寫得更好的了。聖潔的生命是超然的，不單只因為聖靈在我們心內秘密動工，也藉著聖靈的工作，我們知道基督常常幫助我們。在這個意義上來說，聖潔的生命是在恒常、自覺和充滿期待的信心下生活。聖靈激勵我們仰望基督賜予我們所需的精神力量——溫柔、憐憫、樂意分享和饒恕；忍耐、堅毅、貫徹始終；勇敢、公正、包容，以及能夠保持和善親切等。同時，在我們祈求過後，而且仍不斷祈求的過程中，我們尋求活出這些美德，結果發現我們得若能力如此行。上述三個傳統觀點都宣告這個真理（縱然凱錫克信念所提倡的被動觀念使他的教導變得含糊不清）。今天教會最大的需要，就是重新認識基督使人成聖的超然能力；亦惟有倚靠這能力，我們才可在這個倫理相對、道德倫亡的世代達致聖潔。故此，所有基督徒都被呼召去證明和宣告這能力，並且盡可能支取！對於這一點，我們所有人都肯定能夠贊同。

　　我願意把本章結語，交給查理·衛斯理——那擅於描述基督徒經驗的偉大詩人。他在這裏完美無瑕地表達出那些正有聖靈在他們裏面為他們成就聖潔的人的禱告心懷；若然其中—、兩句意味著教義上的觀念錯誤，我們應當告訴自己，誠如有時候需要為這些事情爭論，有時候也需要讓他們過去。請聽聽他的話，並且學習去分辨。

　　耶穌，我的力量，我的盼望，
　　在你跟前，我放下憂慮，
　　存謙卑的信心仰望，
　　知道你垂聽我的禱告。
　　讓我在你面前等候，
　　直至我能成就萬事，
　　讓我盼望你創造的大能，
　　盼望你的更新。
　　求賜我敬畏的心，
　　敏銳明辨的眼睛，
　　罪惡臨近時，懂得仰望你，
　　好讓我看見那試探者落荒而逃；
　　求賜我裝備好的靈，
　　以謹慎作兵器，
　　永遠警醒，
　　在禱告中守望。
　　我渴求對你及你偉大的聖名，
　　一份真正的崇敬，
　　一個純—、堅定的目標，
　　利誘不能移、威武不能屈；
　　珍惜而合宜他，
　　看重你永恆的美德；
　　純然渴望人人都認識
　　並稱頌你的恩典。
　　我安躺在你的話語上，
　　深知你對我的應許；
　　主，我的幫助和拯救，
　　必定從你而來。
　　但求你仍舊與我同在，
　　也不容我信心失落，
　　直至你引導我忍耐的靈
　　進入你完全的愛中。

* 6_聖靈的路徑_解釋聖靈生活

　　現在，我們來到一個主要的問題，是我們一直為他開山辟路的。對於獨特的靈恩經驗，我們應該以怎樣的神學觀點去看他呢？即是說，我們怎樣以神的概念來解釋他呢？當他們自稱他們的屬靈經驗比其他人更加超越的時候，我們應該怎樣看聖靈在他們身上的作為呢？事實上，這是靈恩運動向我們提出的一個主要問題。可是，我一方面可從其中心的信念及倫理上的果子而得出結論，認定神在他們中間，另方面，又發現「靈恩派」和「非靈恩派」的屬靈氣質比我們有時候所在意到的更加相近；這樣，我令到這個問題更加難以解答。倘若靈恩社群中的典型屬靈經驗是沒有基督在其中、沒有愛心和驕傲自負的，那麼，我們的疑問就不會出現，因為我們根本沒有理由將這些經驗歸功於聖靈；可是靈恩運動的情況正好並非這樣，那麼，這個問題就來得更加尖銳，且無法逃避了。因為我們必需面對一個事實，靈息運動用以解釋其自稱擁有的特色的一個最普遍宣告的神學觀念，是十分不合乎聖經的。

　　對於一個看自己為復興真正基督徒經驗的力量的運動，這個事實引起的問題肯定是顯然易見的。經驗是一個含糊的字眼，而種種經驗（即是思想與感情的特殊狀況）落在不全然被聖化的罪人身上，必然如同雜貪混在黃金裏。沒有任何經驗單憑這經驗的發生本身就可證實是從神而來，為要推展他恩典的作為。基督徒擁有的經驗，不一定就是基督徒經驗。一個經驗若是出於神恩典的賜予，他在聖經真理的試驗下，必能證明在其中心有一種加強了的醒覺——對於關乎神的一些啟示的真理的醒覺，以及對於我們作為受造物、罪人、受益人、信徒、養子、被買贖的僕人，及在其他各種身分下與神的關係，有強烈的醒覺。我們曾經以這個標準去量度靈恩派經驗，也發現他們在這一點上沒有缺失。可是，當這些經驗被用來印證某些誤解聖經的信念時——時常有人這樣做——，我們就只剩下兩個選擇：一是排斥這些經驗，看這些經驗為虛妄的，甚至可能源於撒但，否則，就重新給他們神學上的闡釋，表明這些經驗實際證實和確定的真理，與靈恩信徒所以為的有所不同。至少對於靈恩見證的主流，這是我們現在要作的抉擇。

　　有些人注意到靈恩經驗宣稱要證實的東西是錯誤的，他們採取頭一個立場，迅速批評這運動是虛妄和危險的。可是，想起有時候（並非經常如此）靈恩派信徒提出他們那些錯誤的主張時那種自嗚得意的態度，又天真幼稚地誤用聖經，而最令人懊喪的是，許多靈恩派的發言人，似乎對於真理的問題漠不關心，凡此種種，我們又不能完全譴責那些對靈恩運動口誅筆伐的人。我承認我也是其中一個受到靈恩運動衍生上述種種現象所困擾的人，不過，無論如何，我從靈恩經驗裏看見神在其中工作，因此，我大膽作出第二個選擇——就是嘗試重新建構其神學觀念。我在這個選擇上所作的，請讀者評斷。

　　首先，讓我們流覽一下傳統五旬節派對靈恩經驗的說明，這是大部分在德國以外的抗辯宗靈恩派信徒所持守的看法。這就是我曾經稱之為復還論的觀點，他們將使徒行傳第二章所形容門徒在五旬節的經驗，以及哥林多前書十二至十四章所形容哥林多教會的經驗，看為今日基督徒應該追求的標準規範、理想和目標。這觀點的中心建立在一種靈洗的觀念上，他們認為靈洗是「一種特殊的經驗，有別於信主經驗，通常在信主後才有的。在這經驗裏，人領受了全部的聖靈進入他的生命中，因此滿有力量去事奉和見證。」1 他們認為除非信徒經歷聖靈的洗，否則欠缺神早已為他儲備的必需資源，所以，他們命令基督徒尋求這種經驗，直到得著為止。2 這經驗一旦臨到，他就被提升，而且通常會（有人說是一定會）說方言，作為內在已發生了的經驗的外在印記。既然他們相信一個人只有如此才能領受「全部的聖靈」不管他們為這怪異的用詞如何注解），他們給這種經驗神學上的闡述，就是認為這種經驗完成了整個信奉基督的入教過程，一如聖公會會友之間的安立甘大公派理論，水禮只是開始，在堅信禮中領受聖靈才圓滿完成整個入教程式。3

　　最近，鄧恩（James D G． Dunn）、蔔仁納（F．D．Bruner）、史陶德（J．R．W．Stott）和賀其馬（A．A．Hoekema）對這觀點都有全面透徹的剖析，我們在這裏亦無需多費筆墨。我在這裏單提出以下兩點就已經足夠了。首先，若我們接受上述的觀點，這觀點會迫使我們評價非靈恩派基督教——即是，那些不認識或不尋求悔改後聖靈施洗的基督教信仰——為低下門徑、次等，並欠缺了一些重要的東西；可是，其次，這觀點不能從聖經中成立，因為這觀點不能前後貫徹地解答一些從聖經引伸出來的反問，例如以下三條問題。

[[Keep_in_Step_With_the_Spirit__notes.org#6_聖靈的路徑_解釋聖靈生活][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 翻方言
　　在我來看，有關翻方言這問題，似乎是最莫衷一是的。翻方言就是將所說方言的訊息內容（一如他們自己所聲稱的）宣佈出來。復還論引導我們將說方言及翻方言與哥林多教會的方言（charismata）等同。保羅給「翻」方言的用字是 diermeneuo（林前一二30，一四 5、13、27），可以指到解釋任何不明白的事情（一如路二四 27 所載的）；這辭彙與語言連結起來很自然是指到把字句本身蘊含的意思翻譯出來（一如徒九 36 所載）。從保羅的話看來，他顯然認為哥林多信徒的方言是帶有可翻出來的意義的（—四 19-13），而今天的翻方言者對今天的方言亦有相同的假設，把他們對方言的解釋視為方言的實際翻譯。

　　然而，他們的表現是令人因惑的。那些流暢、肯定而又自然流露出來的解釋，後來卻被證實是千篇一律、含糊不清和無所傳達的。其中造成了許多荒誕的錯誤。喬達（Kildahl）告訴我們非洲土話主禱文如何被翻為主再來的訊息。27 一位我曾教導過的埃塞俄比亞牧師，參加一個說方言的聚會，他誤以為是一個非正式的多種語言讚美崇拜會，於是，他站起來用基茲話（ Ge’ez，譯者注：一種已廢的閃族語，今用於埃塞俄比亞基督徒的禱文中。）背誦詩篇第二十三篇，這是他出生的科普替族（Coptic）崇拜時用的古老語言；他的背誦立刻被當眾翻譯出來。翌日，他憂愁困惑地告訴我：「全都翻錯了。」喬達也報導過一件事，同一段方言錄音經兩個不同的人翻譯，其中一個翻為「為一份新工作尋求引導」的禱告，另一個則翻為「為一次嚴重大病最近康復而獻上的感恩」。當告訴翻方言的人兩種解釋有出入時，「那翻譯者毫不遲疑，亦不自辯地說神給予一個翻譯者一種翻譯，又給予另一個翻譯者另一種翻譯。」 28 那翻方言者的經驗是，「方言的解釋」是即時浮現腦海的，換句話說，聽見方言之後，那些即時深印腦海的思想就視為那段方言的解釋。他們宣稱神直接賜予翻譯的內容；就好像靈恩派的預言一樣，他們持相類似的宣稱，只要該預言是合乎聖經的話，他就可以成立，不能修改，因為他是無從驗證的。我們可以看出一個翻方言的人——尤其是一開始就滿腦袋儲存了許多聖經真理的人——如何能夠藉著與講者、或講者的聲線語調、或聚會的氣氛共嗚感應而產生恰當並造就人的「解釋」。可是，至於這些解釋如何能夠直接表達所剛剛聽到的聲音的意義，以致實際上將一種不明白的言語翻譯為一種能明白的言語，那就難以理解了。

　　我不會妄自憑幾句翻譯錯誤的例子作為基礎，去全盤否定所有方言的解釋，看他們為虛妄的，同時，我同意撒瑪連（Samarin）的意見，他認為說方言加上翻方言的宗教儀式所產生的團結友愛本身可以是有價值的。 29 但我想，因此就假設我們已重獲保羅所說的翻方言恩賜，卻是十分危險的。無他，事實的證據委實太不肯定了。

　　賀其馬提出當說方言帶來祝福的時候，祝福的源頭「並不是方言本身，而是說方言時候的心境，或者說……在方言說出之先，一顆尋求更多被聖靈充滿的心。」 30 這個意見似乎比任何認為現時人所說的方言，在思想暫時停止活動的情況下，這方言本身能造就人的說法來得實在。同樣，翻方言也可以帶來祝福，是由於他傳達了聖經的激勵，而不一定像一些人的想法，認為這些必然是神所賜方言的神授解釋，就如當日在哥林多教會裏被翻出來的方言可能是神授的一樣。

　　走筆至此，我們必需就醫治和說預言提出一些反問。

[[Keep_in_Step_With_the_Spirit__notes.org#翻方言][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 醫治的恩賜
　　靈恩派的醫治職事能否令人信服地與哥林多前書第十二章二十八及三十節描述的醫治恩賜等同呢？當然不可以。

　　使徒時期教會醫治恩賜的典範只能夠是屬乎使徒擁有的醫治恩賜，而耶穌自己的醫治職事就是他們的典範。可是，耶穌和門徒是直接用他們的話（太八 5 一 13，九 6、7；約四 46 一 53；徒九 34）或者他們的撫摸（可一 41，五 25—34；徒二八 8）來醫治的。然後，病者立即得醫治（太八 13；可五 29；路六 10，一七 14；約五 9；徒三 7；有一次分兩階段進行醫治，每階段的效果是即時的，可七 32—35）。身體上的殘缺（例如跛子、瘸子），以及功能性、徵候的和心理引致身心上的疾病（徒三 2 一 10；路六 8—10；約九），一概獲得醫治。有時候，他們叫死了多天的人復活（路七 11—15，八 49—55；約—一 1 一 44；徒九 36—41）。他們醫治一大群人（路四 40，七 21；太四 23、24；徒五12—16，二八 19），並且沒有任何記載說他們嘗試醫治而結果失敗的（除卻有一次門徒忽略了禱告，要由耶穌接替他們進行醫治「可九 17—29」）。再者，他們醫治的結果是持久的；沒有任何跡象顯示得醫治者後來舊病復發。對於現今五旬節派及靈恩派醫者的職事，以及那些為病者禱告的人的職事，無論人如何說他們有神特別的呼召，他們當中沒有一人有上述如此驕人的成績。

　　所以，我們不能像某些人有時候的想法一樣，假設現今靈恩派醫治的能源一定就是保羅在哥林多前書十二章二十八節所講述的。在使徒時代，醫治的恩賜比起現今靈恩派信徒看來擁有的醫治恩賜，在本質上是更超越的。我們頂多可以說，靈恩派醫者有時候並在某些方面可以表現得像新約時代有恩賜的醫者一樣，而每次這樣的場合都印證了神的觸摸仍然具有他自遠古以來的能力。可是，這並不等如說在這些人的職事裏，新約時期的醫治恩賜又重新出現。

[[Keep_in_Step_With_the_Spirit__notes.org#醫治的恩賜][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 預言的恩賜
　　「靈恩派的預言能否確實被視為新約表記恩賜的復興？」當然不可以。

　　我提到的預言是指領受和傳達那聲言是神的訊息的東西。預言是靈恩派團契一項固定的特徵。一般對於預言的信念是（1）直接從神而來有關神的心思的啟示，在別處是無法知曉的；（2）預言經常包括神對未來計畫的特殊指引；（3）預言的正確口述形式等同舊約時代神的曉諭，那說話者通常是神自己；和（4）預言是使徒教會的一個表記恩賜，與其他的表記恩賜一樣，自教父時代中期至二十世紀，在教會中是暫時失效的。可是這一切信念都很值得懷疑。

　　首先，彼得在五旬節曾經引述約珥的預言，指出普世性的預言為聖靈時代的一個記號（徒二 17—21）。因此，當時說預言是一項所有信徒都能夠參與，並且也許期望去分享的活動（參徒一九 6；林前一四 1、23—25）；固然，看來也並非所有信徒都可以恰當地稱為先知（林前二 29），大概因為他們在預言職事上的參與太過斷斷續續。可是，既然說預言原則上是一項普世性的基督徙活動，那麼，我們既不應以為說預言只限于使徒時代，更不應該以為說預言會在任何一個時代消失，所以，對於那些假設預言已大多數不存在於教會生活中的理論，我們理應存疑。

　　第二，雖然個別的先知在主前和主後間或被聖靈感動說出未來的事（參太二四 15：徒—一 28，二一 10、11；彼前一 10 一 12；啟一 3，二二 18），先知職事的精髓卻在乎宣告神此時此刻要向他子民說的話，通常這意味著將啟示的真理應用出來，而不是增加神的啟示。一如舊約先知傳講律法，呼籲以色列人面對神與他們所立的約的順服要求，他們若依約順服，就能得著所應許的祝福，不然，就要受咒詛，同樣，新約先知傳講福音和信心的生命，看來是為了叫人悔改，造就人和鼓勵人（參林前一四 3、24、25；徒一五 32）。保羅願望整個哥林多教會都能分享這個職事（林前一四 1、5）。因此，一個很自然的假定，就是在一般情況下，（縱非每時每刻，也肯定有些時候是如此，）先知的「啟示」（林前一四 26、30）是一種由神引發的真理應用，一般而言，這真理早已啟示出來，而不是揭露一些以前從末知道，亦無法從其他途徑知道的有關神的思想和意願。由此推論，同理，任何藉言語加強聖經教導，以應用於聽者身上的方式，在今日大概可以正確地稱之為預言，因為本質上這確實就是預言了。

　　第三，保羅指導信眾在聚會中聽基督徒先知說話時，該「……慎思明辨」（林前一四 29），可見新約裏潛在的普世性預言，並非絕無謬誤、不容修改的，即使未至於需要實在地予以更正，至少也有斟酌的餘地。新約先知藉語言形式傳達他們的訊息時，聖經上沒有任何指示說他們以天父或聖子的角色自居。愛基遜（ Dayid Atkinson）說：「今日在靈恩派聚會中說預言常以單數第一人稱來發言，……這看來不是說預言的要素，而是一種次文化發展出來的習性。……先知訊息的權威不在其形式，而在乎其內容，像靈恩派採用的那種形式，只會使人更難於慎思明辨。」。32 愛基遜的話實在很真確。對於不屬聖經正典的預言，正正由於我們無法保證其內容的充分表達和思想的完全正確，他們必需受到試驗，意思是，我們要用辨識力來聆聽。因此，某些人的觀念，那認為聖經正典裏神直接說話的預言形式，也必須重現于現今教會那衍生自昔日預言、非無誤又不屬正典的預言裏的看法，似乎是混洧和錯誤的。

　　最後，當靈恩派先知預言未來的事情，用單數第一人稱的措辭表達，一如這預告本身是神直接的宣稱時，單純從他們語言表達的形式，或者單從發出預言這個行動本身去推論預言內容的真確性，肯定是一種錯誤。舊約提供的一個可以恒久應用的聖經準則，就是一如所有假定的預言的教義內容必須受考驗（參申一三 l—3），預言的真確與否，就必須看他們是否應驗（申一八 22）。這些預言應對人的行為產生的唯一影響，就是驅使人作好心理準備，以迎接預言的應驗，同時也準備好面對預言的不應驗。可是，行動的準則，必須是神啟示的話語和靠這話語管理生命的智慧（參申二九 29；箴一至九章）；我們不要隨便相信自封為先知的人那些很可能誤導人的預言。（寫到這裏，不禁令我聯想起在我身上發生的一件事。一九七九年，當時有一位相當誠懇的靈恩派先知規勸我，他說神並不是像我心裏認定的要引導我到溫哥華寫作，而是要我在城市教會內帶領基督徒渡過一段大分裂的時期。嗨，似乎今天的教會一如一九七九年的模樣，而我呢？此刻正坐在這裏寫這本書。）

　　我們不應以為預言是久已作古的第一世紀恩賜，今天復甦過來，因而在語言表達形式上以盛裝出場，使他與十八、十九世紀以還所有其他基督教溝通的形式分別出來；肯定說，恰當的結論反而是我們應該明白到其實自有教會以來，預言一直不斷展現在每一篇發人深省，並切合聽眾需要的講章或非正式的「訊息」內。不論何時何地，只要聖經真理被真誠地傳講出來——意思是，真理被講解、詮釋和應用，不論是在講壇上或是非正式的分享——，就已經是預言了。傳講訊息就是教導神的真理，並加以應用，這種具備應用實踐的教導就是預言，以前如此，將來也是如此。今天在靈恩派信徒中間宣講的預言，並不比任何時間其他任何團體所宣講的更加優勝，過去、現在、將來也是如此。有些人在宣講之前沒有默想，採用第一身單數表達，其文法猶如是神自己直接宣告，把聖經真理應用在各種處境和不同的人身上，又為發生了的事情歡喜慶賀，同時瞻望未來要發生的一切。無可置疑，神也曾在這個時代，藉著這一切祝福那講的和那聽的人。然而，為此以為這種表現本質上與基督徒一貫為人所熟悉的（正式與非正式的）鼓勵和勸誡截然不同，從而把他認定為新約表記恩賜在今天的復蘇，這樣的想法是不正確的。

[[Keep_in_Step_With_the_Spirit__notes.org#預言的恩賜][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 對複還論神學思想的裁決
　　上述提到的七條問題，其中最重要的字眼是令人信服。對於上述問題的種種肯定和否定論說，都曾經有人提出過，這不是現在我們要談論的。我想指出的是這種種論據到目前為止還未有足夠的說服力使他們貫串有力，而且似乎亦永不會變為可信服的了。誠然，靈恩派信徒（也包括其他非靈恩派的信徒）所經歷神的眷佑和神工作的彰顯，在某些方面來說，相當於使徒的神跡、醫治、說方言，以及（頗成疑問的）翻方言；在使徒時代，這些恩賜印證使徒能力的來源，表彰他們所傳揚的基督（參林後一二 12；羅一五15—19；來二 3、4；和使徒行傳的記述）。誠然，在整個靈恩派圈內圈外，在整個教會歷史以還，確有「第二次祝福」和聖靈的膏抹臨到信徒，而這些恩賜在某些方面來說，確與五旬節經驗相似。34 可是，我們不能憑以上任何證據，而叫人信服地總結說，新約原初的靈恩經驗，消失了一段長時間之後，已經原原本本的再次賜給教會了。

　　我們無需否認，自從第一世紀末期，在不同的教會傳統中，一些基督徒屬靈方面的進深經驗，可能在感覺上很像使徒們五旬節的經驗；我們所需要注意的，反而是新約神學禁止我們用五旬節的經驗去解釋信徒這些經驗，或者將任何悔改以外的經驗，解釋為領受那正充分發揮其新約職事的基督的靈。我們亦無需對以下可能根本沒有答案的問題表達意見，就是到底神在使徒職事完結之後，撤回所謂表記恩賜，是否代表他在任何情況底下都不會把這恩賜恢復呢？我們只需要觀察，儘管與一些靈恩派信徒所宣稱的相反，事實上到如今這些恩賜還未曾真正恢復過。一言以蔽之，很明顯以複還論作為解釋靈恩經驗的神學理論是行不通的，倘若我們想明辨神在這個運動之中有何作為，我們必需循其他方向去思想。

　　這裏，我還想加多一個短評。要評價靈恩派現象，我們需要記得的，就是團體信念塑造團體期望，團體期望塑造個人經驗。一個具備導師和著作文獻的團體，很容易模造其成員的思想和經驗，而且模造的程度可以是十分驚人的。具體來說，例如團體相信，標準的信徒經驗應該以使徒行傳第二章使徒的經驗為典範，對神自己、他在基督裏的愛和他賜予的能力（聖靈的膏抹）有一種更深的體會，並得著說方言的能力，那麼，團體的成員肯定會追尋且「尋獲」這種經驗。這經驗也不會單單由於某些錯誤的觀念黏附其上，而必然地成為一種誤導的、沒有聖靈在其中的、自我衍生的經驗。正如我們一直所體會的，神是滿有恩慈的，他祝福那尋求他的人，即使他們的觀念未必完全正確。可是，我們必須以這種經驗為一種受期望塑造的經驗來試驗他，而那塑造經驗的期望亦要分開來接受考驗，去看他們是否合乎神所啟示的真理。故此，同理，若然人們期望從神而來的訊息應以某個特定風格傳遞，那麼，不論正典式預言復蘇這個意念是否有聖經根據，這種傳遞方式肯定會應運而生；然後，在每一次個別的情況，我們都需要試驗訊息的內容，這種試驗與就塑造傳遞過程的期望而作的評斷是很不相同的，兩者不能混為一談。

　　讓我重申：我從沒有表示過這些受期望塑造的經驗是沒有屬靈實質的。我唯一希望指出的，是複還論者的宣稱（他們期望的基礎）是經不起考驗的，我們需要另一套神學理論去闡述聖靈的工作。我想，這一點我已經很清楚詳盡地證實了，因此，我會繼續寫下去。

[[Keep_in_Step_With_the_Spirit__notes.org#對複還論神學思想的裁決][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 另一套神學理論

[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

*** 說方言
　　那麼，我們對說方言有什麼看法呢？我們看見現今說方言的人，他們能夠保留那種情緒，思想卻休假去了，因此我們不能根據任何觀點，信心十足地認定他們的表現等同於新約時代的方言。在這種理解底下，人們經常極力主張的，就是既然神的目標是要人在完全自覺、理性的控制能力下，達致人格完全的統合，那麼，成聖過程的整體楷模，必然包括平穩地恢復這種控制能力。當我們更深地表現出聖經所說的誠懇、純一、專心一志等質素時，我們就更能控制自己，同時在我所行的一切事上，我心中「只有一件事……」（腓三 13；另參林後—一 3；雅一 7、8）既然是這樣（按照推論是如此），我們就再沒有說方言的必要，因為說方言的時候，人放棄了對聲帶理性的控制。然而，一個雙重的回答可能合適。

　　首先，既然靈恩派信徒故意選擇說方言作為一種傳達工具，去表達他們心中就某些主題要向神獻上的崇敬和祈求，藉此向神多說一些他無法用語言表達的心事，若然我們聲稱他們完全缺乏理性的控制，是不很真確的。

　　其次，聖靈可能要透過這種表面上理性控制的鬆懈，去強化信徒更深層面的自製能力；這種見解並非不可思議。心煩意亂的人，浸在浴缸裏，大聲哼無字句內容的歌，有助恢復健全的理性；說方言可能在屬靈方面就有著相同的意義。倘真如此的話，那麼說方言的確是神的奇妙恩賜。並且，若然說方言的效果真的為要加劇讚美及禱告的情緒，並使這些情緒持續，以免因思想的魂遊象外而無法維持，那麼，說方言可以幫助培養正面的性格，引領人進入密契禱告（ mystical prayer）宣導者所稱的默觀（contemplation）裏。這種操練對於某一類人可能尤其有益，由於現代生活匆忙、浮面、脆弱而不真實，許多人成為這種生活的受害者，無法在更深層面與他們的自我接觸，於是，他們的基督教變成形式化、概念性、隨俗、定型、抄襲和二手的信仰。（畢竟，靈恩運動主要是一種都市現象，而在城市裏面，這些壓力對人有最直接的影響。）

　　這樣看來，起碼對某些人來說，說方言可以是神的美善恩賜；這是基於一個觀念，就是任何能夠幫助人專注神、體驗他的同在，並使人敞開心靈讓神影響的東西，都是美善的恩賜。（可是，對其他擁有不同問題的人來說，神已經幫助他們自心裏向神發出通達的禱告，說方言對他們來說，遂變為不屬靈、瑣碎和不著邊際了；現時有些人對於不論何處出現的方言都持這種看法。這就是正所謂一人的佳餚可能是另一人的毒藥了。）

[[Keep_in_Step_With_the_Spirit__notes.org#說方言][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

** 結論
*** 2_表記恩賜
　　關於表記恩賜的復還論，也是靈恩運動從古老五旬節派承受的，這理論並不適用；沒有人能夠肯定新約說方言、翻方言、醫治和行神跡的恩賜已經恢復，似乎亦不合乎事實，而來自聖靈的預言，實質不是新的啟示（雖然在聖經時代，新的啟示往往是預言的一部分），而是將已經啟示的真理應用在人身上的一種能力，這種能力不是單單規限在靈恩派圈子內；其實，這種能力一直以來都存在教會之中。然而，靈恩運動強調運用每個人都各自擁有一些的屬靈恩賜，積極推動教會總動員事奉，是完全正確的，也為軟弱和受創傷者特別帶來支持和扶助的豐富資源。
　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

*** 4_說方言
　　靈恩派方言，作為一種經選擇的、在神面前非語言的自我表達方式（所謂經選擇，在他們的信念裏，是神的旨意叫人這樣選擇的），在無可避免地多樣化的基督徒經驗裏自有他的地位；而在基督徒經驗中，種類繁多的靈修方式，正好反映了文化與個人的不同構造和特質。似乎看來很明顯的，就是說方言作為一種屬靈操練，的確豐富了一些人的屬靈生命，但對別的人來說，卻是毫無價值的不敬虔表現。有些人嘗試這樣操練，及後見證說發現自己所做的毫無屬靈實質，然而另有些人開始了這種操練後，結果卻經歷與神更深的相交；我們無理由懷疑他們任何一方面的見證。用方言禱告可以幫助一些過分理智的人釋放和解凍情感，正如結構分明、用言語清楚表達的禱文可以幫助一些過分感性的人穩定情緒、弄清思想。那些認識到說方言並非神為他們預備的道路的人，以及另外一些體驗過說方言豐富了他們的屬靈生命的人，都不應該將自己的方式強加於別人身上，也不應該因為別人與自己不同而貶抑他人遜於自己，同時若然在自己的陣營中有人因著相信是神的帶領而轉移到對方的陣營之中，亦無需為此信心動搖。用方言禱告及不用方言禱告的人都同是向主禱告；他們或站立或跌倒都是向他們的主人交代，並非做給其他僕人看。一如在基督裏面無分猶太人或希臘人、為奴的或自主的、男性或女性，同樣在基督裏亦無分說方言的或不說方言的。即使（正如我所懷疑的，雖然無法證明）今日的說方言者不同于昔日哥林多信徒所說的方言，我們也不應該禁止他們說方言，而說方言者亦不應該認定一級的基督徒必需說方言。

[[Keep_in_Step_With_the_Spirit__notes.org#4_說方言][摘要連結]]　　　
[[Keep_in_Step_With_the_Spirit__orig.org#目錄][目錄連結]]

