提摩太後書第四章：盡忠職守

* 1_背景
　　讀提摩太後書第四章，就好像看到使徒保羅在寫告別書一樣，根據教會的傳統說法，認為使徒保羅寫完提摩太後書之後不久，就被處以死刑。他因為具有羅馬公民的身份（參考使徒行傳廿二：27），因此，沒有釘死在十字架上，也沒有被丟進野獸競技場，而是被斬首示眾，在羅馬政府看來，這樣對待殖民區的人民已經是相當「人道」的了。

　　由於這是使徒保羅最後所說的話，因此也可以從這裏看出使徒保羅對提摩太的愛和鼓勵，就真的如同他在前書與後書的第一章開場白所說的，將提摩太看成是自己信仰上的「真兒子」。就是因為把提摩太當成是「真兒子」看待，因此，每當談到有關教會牧養工作時，使徒保羅幾乎就是說盡了一個傳道者應該有的傳道使命之態度。他沒有任何隱瞞或是存留甚麼秘方，可說是傾囊而出地將所有他想要說的話告訴提摩太，並且深深地對提摩太有一份很大的期盼，也因此，他幾乎就是毫無任何保留地將他自己獻身傳道的使命和對傳福音的看法讓提摩太知道，這對提摩太來說，是非常有幫助，也是學習的重要功課。

　　作為一個傳道者，應該就要像使徒保羅這樣，傾盡所有的力量，為福音打最美好的仗，也只有這樣，才能使福音成為生命的中心。如果一個傳道者，第一個想到的是自己利益的話，這樣就談不上所謂獻身的使命感，也說不上盡忠職守，獻身當傳道者，或是成為基督的教會，都應該有這樣的認識才對。

　　我曾提過使徒保羅書信中最喜歡用的資料，就是用羅馬軍隊出征去打仗時，那種雄赳赳、氣昂昂的精神，因為信仰所面對的敵人乃是屬於靈界的邪惡者。另一方面，他也喜歡用羅馬競技場上那種賽跑者認真的樣式，當作他勸勉信徒的教材，希望所有的信徒都會像正在競技場上的競賽者一樣，想要贏得那最終點的冠冕，因為那是極大的榮耀。

　　另一方面，我們也看到使徒保羅每當談到信仰的問題時，就會提到辨別真實信仰的重要性，信徒若是沒有注意信仰的內涵，就容易被那些經常借用耶穌基督的名進行欺騙行為的人所得逞，不但導致信徒誤入信仰的歧途，也會造成教會的紛亂，嚴重的話還會造成教會分裂。例如他寫給加拉太教會的書信中，就特別提到有人在「傳另一種福音」，他說根本就沒有「另一種福音」可言，那是錯誤的信息，和福音根本沒有關係（參考加拉太書一：6-9）。

　　不僅在加拉太教會有這樣的問題，在哥林多教會也出現有專門在欺騙教會的人，這些人能言善道，且很會標榜自己的能力，使徒保羅知道後非常生氣，諷刺地說這種人是「超等使徒」（參考哥林多後書十二：11），並不是真正的福音工作者，因為真正的使徒會揚傳耶穌基督受難於十字架，以及他復活的信息（參考哥林多前書二：2），而不是在述說自己的能力有多大，因為所有的能力，即使有醫病趕鬼的能力，也是為了要見證福音的緣故（參考羅馬書十五：18-19）。除了哥林多、加拉太等教會，其它的教會也都發生類似有人滲透到教會裏面，為的就是要欺騙信徒跟隨他們，而不是遵行聖經的教訓，也因為這樣，使徒保羅一再呼籲提摩太，在以弗所教會牧會工作中，就是要教導信徒認識聖經的教訓，並且要「正確地講解真理的信息」來幫助信徒辨明真正的信仰內容，他強調這是作為一個「問心無愧」的福音工人最基本該有的態度（參考提摩太後書二：15）。

　　也因此，使徒保羅很不喜歡那些在傳道事工上脫隊的同工，尤其是在教會中造成困擾與糾紛的人，他最不高興。可是他都有保留機會給這些人，希望能讓這些信徒再次回到教會團契，就像我們現在所讀的經文中提到約翰‧馬可，他原本脫離使徒保羅同工行列，後來再次回來，且成為使徒保羅的好同工。可是，對那些行徑很惡劣的同工，就不是這樣了，他會指名道姓，說出這些離經叛道的人的名字。使徒保羅寫給提摩太的書信中，我們已經看到他提到幾個離開教會信仰團契者的名字，他特別提到「舒米乃和亞歷山大」（提摩太前書一：20）、「腓吉路和黑摩其尼」（參考提摩太後書一：15）、「腓理徒」（參考提摩太後書二：17）、「雅尼和洋布雷」（參考提摩太後書三：8-9）、「底馬」（提摩太後書四：10）、「銅匠亞歷山大」（提摩太後書四：14）等，這通常不是使徒保羅的習慣做法，因為他喜歡將那些對福音有貢獻的人提出來，為的是希望大家能學習那些人，現在之所以會將這些成為信仰絆腳石的人寫出來，實在是讓他看不下去了，且是若不清楚將這些人的名字寫出來，可能會讓更多信徒離開了真確的信仰，因為在整個亞細亞省的人離棄信仰的人必定不少，才逼得使徒保羅必須採取這樣強烈的手段來防範（參考提摩太後書一：15）。

　　因此，辨別真確的信仰內涵，對一個信徒來說是很重要的信仰功課，而對一個傳道者來說，則是他在傳福音事工時，特別是在牧養工作上，需要經常注意的一件事。

* 2_經文內容
** 第一至五節：
　　在第一節一開始，使徒保羅就談到對人的生命有審判主權的，就是上帝和耶穌基督，我們不要小看這句話的重要性，因為這句話也是在否定羅馬政府對人生命的主宰權。使徒保羅當時是被關在監獄中，當他這樣寫的時候，等於在告訴羅馬政府，他不承認羅馬政府對他有生命的判決權，這種權柄只有創造生命的上帝，和為了救贖人的生命而犧牲在十字架上的耶穌基督才擁有而已，不是世上任何一個人所擁有的政治權柄和勢力。其實，我們如果從耶穌基督所說的話來認識，也會清楚使徒保羅所說的這句話是有原因的，耶穌基督說：「朋友們，我告訴你們，那只能殺害肉體，卻不能進一步傷害你們的，不用害怕。我要指示你們該怕的是誰：你們要怕那位奪走人的生命以後，又有權把他投入地獄的上帝。是的，我告訴你們，應該懼怕的就是他！」（路加福音十二：4-5）

　　耶穌基督這句話已經清楚在說明生命的主權是在上帝，人並沒有這樣的權柄。人所能做的，只能對人的身體進行迫害；但真正主宰著人的得救與否之權，那才是最重要的，而這權柄卻是在上帝和復活的耶穌基督身上。再者，這句「審判所有活人死人的基督耶穌」，可說是早期教會最重要的信仰告白內容。這句話也就是在回應當時羅馬政府對基督徒的迫害，基督徒要表明並不害怕這樣的迫害，因為真正的審判者就是復活的耶穌基督，他的審判是連活人、死人都包含在內。我相信這句話對我們是一點也不陌生，因為在使徒信經中就有提到復活的耶穌基督要來「審判活人與死人」這句話。

　　第二節對傳道者來說，或是對今天的基督教會都是具有非常大的意義，因為傳福音乃是教會存在的最重要使命，也是基督徒應該有的責任。而我們知道這裏所說的福音，指的就是耶穌基督拯救的信息。使徒保羅告訴提摩太不論在甚麼情況下，都要傳福音，因為福音是和生命的得救與否有密切關係。不是喜歡的時候才要傳福音，也不是遇到挫折或是困境時，就對福音事工採取懈怠或是放棄的態度。

　　使徒保羅在這裏提到幾個牧養工作的重點：
一是要耐心勸勉。這讓我們看出，牧養工作並不是一件易事，有些信徒並不是很甘願或是容易接受真理的教導，這就必須多用些時間，特別是在這裏提到要「耐心」，所謂的「耐心」，是指不妥協，但原則很清楚之意。並不是為了討好信徒，怕信徒離棄信仰就採取睜一隻眼、閉一隻眼的態度，不是這樣。而是要一而再、再而三的給予鼓勵之意。

二是督責，意思是指知道錯誤時，沒有將之當作沒有發生，而是會清楚地讓信徒知道，錯誤在甚麼地方。

三是教導。使徒保羅所使用的詞是積極式的，意思就是不放棄任何可以掌握的機會，要在信仰的事上用心，讓信徒明白甚麼才是正確的信仰。

第三至四節讓我們看到人性在信仰上的共同點，就是指想要滿足慾望的需要，並不是真在追求對真理的認識。這兩節也同時指出真假使徒的差異，就像舊約先知耶利米時代的假先知一樣，經常說出當時的人喜歡聽的話，但那些卻不是上帝要他們去說的，而是那些假先知自己所想的，不是來自上帝的啟示，要不然就是假冒上帝的名說虛假的信息（參考耶利米書十四：13-14）。真正的先知就像先知米該雅所下的定義說的：「我指著永生的上主發誓，上主對我說甚麼，我就說甚麼。」（參考列王紀上廿二：14）同樣的，身為一個福音的傳播者，他主要的使命就是見證上帝在耶穌基督身上的救恩，不是要彰顯自己的能力；他的主要責任就是在為福音作見證，而不是為了要討好信徒而講好聽的話。

第五節，這裏使徒保羅提到身為傳道者應該有的三點基本態度：

一是要謹慎。這是指要保持頭腦清醒之意。為甚麼傳道者需要頭腦清醒呢？很簡單，只有這樣才能避免受到誘惑。還有，當一個傳道者頭腦清醒的時候，他就會知道教會或是信徒的問題在哪裏。

二是忍受苦難。傳福音的工作一定不會很輕鬆，特別是在一個迫害的時代，傳福音甚至是會有生命的危險。因此，使徒保羅要提摩太有這樣的心理準備。雖然這個時代在咱台灣已經沒有類似使徒保羅時代這種政治迫害的問題，但這並不表示就沒有苦難，因為苦難不僅僅限在政治性的層面，比這更嚴酷的，恐怕就是來自教會內部信徒之間的爭鬥、分裂，以及不應該有的誤解。

三是忠心履行事奉的職務。這句話可以對照第二節所提到的「不管時機理想不理想都要傳」。但請注意，這並不是說非要在哪一間教會牧會多久才是在履行事奉的職務，我經常告訴那些因為與教會之間有發生糾紛的傳道者說，傳福音並不是被限制在教會，在教會是在牧會，真正可以讓一個傳道者放手去傳福音的地方，是在教會以外的地方，那是一個廣大的社會空間。傳道者就應該像耶穌基督告訴他的門徒所說的：「無論到甚麼地方，如果當地的人不接待你們，也不聽你們的話，你們就離開那地方，把腳上的塵土也跺掉，表示對他們的警告。」（馬可福音六：11）使徒保羅就曾用這種態度回應彼西底的安提阿人，以及哥林多城人對福音的冷漠（參考使徒行傳十三：50-51、十八：6）。沒錯，傳道者要盡責任在傳福音的事工，不論所遇到的境況是甚麼，都不要放棄傳福音的使命和責任。

** 第六至八節：
如果我們要說使徒保羅寫給提摩太的書信中，最精華的經文在哪裏？應該可以說是這一段才對。在這段經文中，使徒保羅提到幾點很值得我們注意的事：

一是他知道自己所剩下的日子不多（第六節）。所以他說他「離開人世的時刻」到了。在第六節他說自己「犧牲」的時候到了，為甚麼他是用「犧牲」這樣的句子呢？這是採用民數記第廿八章七節所提到以色列人用羔羊獻祭在祭壇上的方式，要把獻在祭壇上的羔羊澆滿一公升的酒，然後才點上火燒化獻給上帝。使徒保羅用這樣的詞句來形容自己就像要獻給上帝的時刻到了，意思就是他已經知道羅馬皇帝還是會將他判處死刑，但他看這樣的死刑乃是使他可以當作獻給上帝的牲祭一樣。

二是他做了自我評估，看到自己確實跑完「那值得競爭的賽跑」（第七節）。我曾在前面說過，使徒保羅將傳福音當作是在羅馬競技場上競爭一樣，是在賽跑，看誰能得到最後的勝利而獲得那榮耀的冠冕。請注意，他特別在這裏強調競爭的內容是「值得」的。甚麼是值得的競爭？且是值得用所有生命的力量去競爭呢？當然就是耶穌基督的福音。使徒保羅窮盡一生的時間為了傳福音而奮鬥，並沒有因為遇到挫折、失敗就放棄。如果我們看他寫給哥林多教會的書信，特別在後書第十一章廿三至廿七節這段經文中，他在描述自己傳福音的旅途中所經歷到的際遇，那簡直不是今天的傳道者所能想像得到的；他曾遇到牢獄之災，也曾被鞭打三十九下，又曾遇到多次生命的危險等等。因此，他說自己確實是跑盡全程，實在是一點也不為過。

三是他深信自己可以得到來自天上所賞賜的冠冕（第八節）。他曾寫信給腓立比教會，說自己是努力朝向所訂的目標前進，目的就是要贏得從天上來的獎賞（參考腓立比書三：12-14）。現在他說這項獎賞已經在等著他去領取，因為他確實跑盡了全程，且沒有改變信仰，因為他守住了該守的信仰。

再者，使徒保羅在第六節這裏用「離開人世」這個詞的希臘文是「analuseos」，這個詞後來演變成為英文的「analysis」（分析）。所謂「分析」，意思就是把原本糾纏在一起的東西，逐一的解開來，使之更清楚、明白。因此，這個字也有「鬆開」、「解放」的意思。這樣，我們可以從這裏了解使徒保羅在說他「離開人世」的時刻到了，意思就是指糾纏生命的一切枷鎖都將解開，不再負著重擔。這就像耶穌基督所說的：「來吧，所有勞苦、背負重擔的人都到我這裏來！我要使你們得安息。」（馬太福音十一：28）這也是為甚麼基督教信仰將生命的死亡看成是一種卸下重擔一樣，不是難過、痛苦，而是一種生命的解放（或是一般人所說的「解脫」之意）。因為辛勞一生，終於可以安然休息了，這是很值得安慰的事，特別是有耶穌基督成為復活生命的保證時，這樣的生命更是令人欣慰的事。

** 第九至十五節：
銅匠亞歷山大害我不淺；主會照他所做的報應他。你自己也得提防他，因為他極力反對我們所傳的信息。

這段經文讓我們看到許多珍貴的歷史資料：

一是我們看到醫生路加乃是使徒保羅最好的搭當，當許多其他同工因為各種原因必須離開使徒保羅時，他一直在使徒保羅身邊協助他、照顧他。這也是為甚麼路加這位作者所寫使徒行傳這本教會史書很有價值，就是因為他和使徒保羅在一起的時間很長。使徒保羅甚至稱呼路加是「親愛的路加醫生」（參考歌羅西書四：14），可見他和使徒保羅之間的關係甚為密切。

二是約翰‧馬可再次回到使徒保羅身邊，是好的同工。原本約翰‧馬可在使徒保羅第一次和巴拿巴去傳福音時，是同一個團隊（參考使徒行傳十三：4），但不知道為甚麼約翰‧馬可突然臨時脫隊，逕自回到耶路撒冷去（參考使徒行傳十三：13）。後來使徒保羅想要再第二次出去旅行傳道時，巴拿巴又要帶約翰‧馬可一起同行，被使徒保羅嚴詞拒絕，也為這件事兩個人從此分開各走各的路線（參考使徒行傳十五：37-39）。我們不知道是甚麼原因使他們再次和好成為同工，且在使徒保羅的語氣中，肯定約翰‧馬可是一位好的福音同伴，在這裏讓我們知道約翰‧馬可對使徒保羅在福音的事工上幫助非常大。

三是底馬貪愛現世。依照歌羅西書第四章十四節的記載，底馬曾和路加第一次陪同使徒保羅在羅馬監獄中。除了路加以外，也曾和約翰‧馬可、亞里達古等人與使徒保羅同為一個團隊在服事福音事工（腓利門書24節）。使徒保羅不會隨便批評這些曾與他同工過的人，但現在卻將底馬寫成「貪愛現世」，可見底馬確實有很嚴重信仰上態度的轉變，才會逼得使徒保羅必須說出這樣嚴重的話。

四是使徒保羅對提摩太有很深的感情，在他即將去世之前，希望能見到提摩太一面，或許就像這兩封書信所寫的一樣，他對提摩太有相當的期待，準備要將他的後事告訴他。但同時，使徒保羅並沒有要放棄以弗所教會的福音事工，因為以弗所是當時亞細亞省的省會，在福音事工上的位置佔有很重要的角色，因此，使徒保羅特地差派推基古去接替提摩太。這封書信很可能就是由推基古帶去給提摩太的。

五是銅匠亞歷山大對使徒保羅的傷害很大。這一位亞歷山大到底是誰？我們並不清楚，很可能就是和提摩太前書第一章二十節所提起的那位「亞歷山大」同一個人。到底是怎麼傷害使徒保羅的？也沒有明確資料可循，但使徒保羅在這裏所用的「害」這個字，在希臘文是用「endeiknumi」，這個字是「顯露」、「陳列」的意思，也含有「舉證」的意義。換句話說，很可能亞歷山大就是一個告密者，向羅馬政府告密有關基督徒聚會的事，這對早期教會來說，是很嚴重的一件傷害事件。因此，使徒保羅不僅在這裏提起，還特別要提摩太提防這個人。

** 第十六至十八節：
第十六節一直被聖經學界討論甚多，到底這裏所提起的「第一次為自己辯護」，這是指甚麼時候的第一次？是使徒行傳第廿八章記載的第一次抵達羅馬之時嗎？不太可能，因為那次並不是沒有人在他身邊，而是有些人一直在關心他、陪伴著他，甚至他還可以自由行動，且去拜訪他的人甚多。因此，有不少學者認為應該是在第二次他被關在監獄之時，那時因為看來情況並不樂觀，且迫害的情形越來越嚴重，頗有風聲鶴唳的氣氛，因而敢公開去探監的人沒有了，大家都有自身難保的危機意識。

第十七節，使徒保羅說上帝給他力量，使他能夠將耶穌基督復活的信息傳出來。其實，這也是使徒保羅堅持要上訴羅馬皇帝法庭的主要因素之一，他一直要讓羅馬統治當局知道，製造亂象的，並不是基督徒，而是一些想要迫害基督徒的猶太人，或是那些排斥基督教信仰的人。他一直努力要讓羅馬統治當局知道，基督徒是很守本份的，絕對不會與政府對抗（參考羅馬書十三：1-7）。除了這個因素之外，使徒保羅最希望做的一件事，就是將耶穌基督復活的信息傳揚出去，特別是希望能將復活的信息傳給羅馬統治階層的人。當他被羅馬總督、巡撫等人詢問時，他都會利用機會宣揚耶穌基督復活的信息（參考使徒行傳廿四：15、21、廿六：23），也因此使得羅馬總督制止他，認為使徒保羅是「瘋了」，是「神經失常了」（參考使徒行傳廿六：24）。這讓我們看出，使徒保羅就是要想盡辦法將耶穌基督復活的信息傳揚出去，那怕是被關、被殺，對他來說，那都是為了傳揚耶穌基督復活的信息的緣故。

第十八節，在這裏，使徒保羅並不是認為自己會從監獄中獲得釋放，因為他已經知道獲救的希望渺茫，才會要提摩太替他拿需要的衣服和書籍，並且要提摩太趕緊到羅馬去跟他相會，因此，這裏他說「主一定會救我脫離一切邪惡」，指的乃是讓他有堅定的信心，不受到任何外力的誘惑，甚至為了保存生命的安全而妥協傳福音的態度，或是對自己過去所傳揚的信息做任何傷害真理的承諾。他深信因為傳福音的緣故而受到迫害或喪失生命的，終必獲得上帝的賞賜，這就是在上帝國裏面得到永恆的生命。

** 第十九至廿二節
在這裏提到一份很齊全的名單，這也是後書與前書之間最大的差異。

亞居拉和百基拉，這是一對夫妻，他們夫妻兩人原本就是織帳棚的人，在哥林多城相遇，因為與使徒保羅同業（參考使徒行傳十八：2-3），且又有共同的信仰，因此，一直是使徒保羅在福音事工上最好的伙伴。他們也為了福音的緣故，特地將自己的家開放成為聚會的地方（參考哥林多前書十六：19）。

而阿尼色弗則是一位很疼惜使徒保羅的同工，為了尋找使徒保羅，他找遍了羅馬城，才知道使徒保羅被囚禁的地方（參考提摩太後書一：16-17）。

以拉都和提摩太兩人都是使徒保羅很深愛的門徒或是同工，曾被使徒保羅差派去馬其頓（參考使徒行傳十九：22）。這裏則說以拉都留在哥林多，在該城的教會見證福音的信息。後來可能就是一直居住在羅馬城，協助該城教會的事工（參考羅馬書十六：23）。

特羅非摩，他是使徒保羅的同工，卻也因為他的緣故，被猶太人逮到機會，認為使徒保羅就是故意帶領非猶太人的特羅非摩進入聖殿，等於藐視上帝聖殿的神聖一樣的尊嚴，因此將使徒保羅逮捕送官去審判（參考使徒行傳廿一：27-30）。

第廿一節提到要提摩太趕在冬天之前到羅馬來，主要原因就是：那是停止水陸交通時期。因為當地的冬天來襲的東北季風特強，不良於航行，若是再延誤一些時日，即使想要成行恐怕也有困難，而且使徒保羅自己也知道可能就會再過幾天日子就會被處死，他真希望看到提摩太最後一面。

友布羅、布田、利努、喀勞底雅等這四位是誰？我們也找不到更多的資料。不過這也是使徒保羅寫書信的一個特色，就是都會將和他同工且在身邊的人，在寄信時順便帶去請安的口信。

第廿二節很特別，前一句是用來對提摩太說的，因此，所用的是單數代名詞「你」，而下半句則是用複數代名詞的「你們」，指的就是對眾人所祝福的話，這裏的眾人很可能就是以弗所教會的兄弟姊妹們。

* 3_經文信息
** 3_1_讓我們在見證福音事工上成為盡忠職守的教會，以榮耀上帝的名。
　　當我們看到使徒保羅對自己在傳福音的事工上做最後一次反省時，他很清楚當時的局勢對他很不利，因此，他說「犧牲自己的時候到了」，這種「犧牲自己」所表明的意義，乃是要將自己獻給上帝，為的就是要讓福音的信息能夠見證出來，而不是說自己年老體衰，也不是說自己即將老而病死，都不是，而是要準備面對被判死刑的死亡。更重要的，他將自己的死看成是「獻祭」一樣，是神聖且有榮耀，這一點就很值得我們一起來學習的了。

　　當使徒保羅回頭一看自己所走過的這段傳福音的道路時，他看到自己就像寫給腓立比教會的書信中所說的，他確實是沒有改變所訂的目標，他是勇往直前朝向這個目標直奔，為的就是希望能贏取來自天上的獎賞（參考腓立比書三：12-14）。因為他一直懷著執著不變的傳福音態度。從他寫給哥林多教會的書信中，我們看到他為了完成達到傳福音的使命，他甚至是歷經了許多的苦難（參考哥林多後書十一：23-28），我深信這些苦難都不是今天的傳道者或是在台灣的基督教會曾有過的經歷。我們應該感謝上帝的，乃是沒有讓我們經歷到這些苦難，也因此，我們應該有這樣的認識：至少要學習使徒保羅對傳福音事工的熱情和執著不變的態度，想盡一切辦法要將耶穌基督復活與拯救的福音傳揚出去，使我們的教會成為一間真正可以成為有見證的教會，成為一間可以榮耀上帝聖名的教會，這樣，我們才能仰望耶穌基督再臨的時候，要賜給我們的榮耀冠冕。

** 3_2_不論在甚麼情況之下，都不要使傳福音的心冷淡下來，每間教會都要堅持這項使命感，持續到世界的末了。
　　使徒保羅寫這封書信給他最喜歡的門生提摩太，「不管時機理想不理想都要傳」，勸勉他不論在甚麼情況下，都要傳福音，並且在教導信徒的事工上，要用「耐心」、「督責」、「鼓勵」等態度，這在一個迫害的環境和時空下，確實是一個重大的功課。

　　想想看，甚麼時候叫做「時機不理想」？使徒保羅的時代，是面臨著羅馬帝國迫害的時代，隨時有可能被丟入野獸競技場餵食野獸；他的時代也是個容易就會被人誣告陷害而抓入監牢的時代，隨時都有可能因此被判死刑而釘死在十字架上。即使是這樣，使徒保羅還是勸勉提摩太不要停止傳福音，而且要用「最大的耐心」，努力傳福音，成為福音的見證者。不僅如此，他也要提摩太認真督責信徒，鼓勵他們，教導他們，讓他們在信仰生活和工作上有美好的見證。

　　如果時機不理想都需要這樣，那麼在時機理想的時候，豈不是更要加倍用心、認真傳福音？當然是這樣，因為那是最容易的時刻，且是最容易看到成果出現，在這樣的時機之下，傳福音最輕鬆，不會有重擔。我們應該說，今天的時代可說是時機最好的時代，也是最有空間的世代，因為今天也不再像使徒保羅的時代，傳福音會受到迫害，也不會有群眾鼓譟公然反對。再加上今天是一個多媒體的時代，可運用的傳播器材很多，這些都可以幫助教會和傳道者好好利用來作為傳福音的器具。另一方面，這個時代也是一個心靈很空虛的時代，科技過度發展的結果，不但沒有為我們帶來心靈的滿足，相對的，卻為我們帶來更多的不安和動亂。單單從社會現象的紛擾，以及越來越殘酷的犯罪手段，就可以看出這個時代實在是一個人心相當空虛的時代。

　　要保持高超的傳福音使命感，這是今天的傳道者和教會最重要的態度，但怎樣讓傳道者和教會保持這樣的使命感，則是所有的信徒需要學習的功課。


