* 提摩太後書這本書信
　　這也是一封使徒保羅在監獄寫的書信，雖然不是像以弗所書、腓立比書、歌羅西書、腓利門書等四本同列為「獄中書信」，我們從第二章九節他提到說：「我因為傳福音而遭受苦難，甚至被捆綁，像囚犯一樣。」就可看出他已經人在監獄中服刑了。但長久以來，提摩太前、後書，以及提多書等這三本都被歸類為所謂「教牧書信」，顧名思義是談到有關在教會牧養工作的問題，主要的目的是在告訴提摩太要怎樣固守著以弗所教會，別讓那些專門在破壞正確信仰的人，在教會中得勢。

** 為甚麼要寫這封書信
　　當他第一次在羅馬等待受審之時，那時他是備受禮遇，可以在外面租屋居住，隨時有人去請問有關信仰的問題（參考使徒行傳廿八：23）。但現在則不是這樣，他是「被捆綁，像囚犯一樣」（參考提摩太後書二：9）。他這次在監獄中，雖然還沒有被審判該受怎樣的刑期，但卻可看出使徒保羅內心似乎已經有了個譜——死刑（參考四：7）可能為了這個緣故，他急切地希望能見到提摩太，要他「盡快」到羅馬監獄去看他，且最好是趕在冬季之前（參考提摩太後書四：21），可見他與提摩太之間的關係多麼地密切，他曾說提摩太是「惟一」跟他同心的福音伙伴（參考腓立比書二：22）。

** 一、使徒保羅寫提摩太後書，心中是相當寂寞的。
　　在第一章十五節，他特別提到說：「在亞細亞省的人都離棄了我，包括腓吉路和黑摩其尼在內。」在第四章十六節說：「我第一次為自己辯護的時候，沒有人在我身邊，大家都離棄了我。願上帝不加罪於他們！」腓吉路和黑摩其尼必定是在亞細亞省教會很有名望的教會領袖，意思是大多數信徒都背棄了使徒保羅。另外一個重要的同工也離開了使徒保羅，那個人就是底馬。他原本與路加都是使徒保羅的同工（參考歌羅西書四：14），為甚麼會離開？使徒保羅說他是因為「貪愛現世」（參考提摩太後書四：10）。但我們知道此時的使徒保羅心中是孤獨的，需要有人在他身邊。

** 二、在羅馬皇帝尼祿殘酷手段逼害下，已經有不少信徒離棄了信仰。
　　希望提摩太看待因信仰受逼害的事件，要與其他的信徒有不同的態度。他說：「你不要把為我們的主作證當作一件羞恥的事，也不要因我為了主的緣故成為囚犯而覺得羞恥。你要按照上帝所賜的力量，為福音分擔苦難。」（提摩太後書一：8）可見當時在迫害之下，離棄信仰的人中有人開始對福音所帶來的生命際遇感到難以理解，更嚴重的是將為福音受苦的事當作是一件有羞恥感的事。這種「不以福音為恥」的信仰告白，一再出現在使徒保羅傳福音的態度中。

　　因此，寫這封書信也有一個主要用意，是多給一些鼓勵，即使人已經陷入囹圄中，還是盡他當福音僕人的使命。他從提摩太身上著手鼓勵做起，要他「堅守」從使徒保羅所領受得到的信息，以及和主耶穌之間連結所得到的「信心和愛心」（參考提摩太後書一：13）；要提摩太「持守」所接受的和確信的「真理」（提摩太後書三：14），並鼓勵他無論「時機理不理想都要傳，用最大的耐心勸勉，督責，鼓勵，教導」（提摩太後書四：2）。這讓我們看出，即使是像提摩太這樣值得他信任的同工，甚至可看成是「信仰上的真兒子」，也是要在迫害的時空下，多給一些鼓勵。

** 三、很人性化的一本書信
　　聖經中很少有一本經書是這麼清楚將自己的人性需要表露出來的，而提摩太後書卻在這方面充分地讓我們看到：作為一個傳道者在人性上的軟弱。我們看到的使徒保羅也有「孤獨感」的一面，因此，需要有人陪伴他，或是說需要「信仰上的真兒子——提摩太」專程去看他。不但這樣，他還特別交代提摩太去看他的時候，記得將他放在特羅亞的加布家裏之一件外衣帶去。我們不清楚這件外衣為甚麼對他在監獄中有那麼重要，或是說這件外衣在他生命中所代表的特別意義是甚麼，不過擁有一項自己看為最珍貴的物品在身邊，一般人陷入牢獄中也常會有這種想要將珍貴的物品留在身邊，這是很自然的，因為這樣或許對正在孤獨感甚深的受刑人來說，有很大慰藉。他同時要提摩太也為他帶去存放在那兒的一些「羊皮書卷」。所謂「羊皮書卷」，應該指的是舊約聖經。在監獄中閱讀聖經，這情形就像許多在監獄中的囚犯不忘記繼續研讀聖經一樣，我們看到人心靈裏共同的需要，這就是上帝的話語。

　　我們也從這本書信中看到他也在心中還記得一位名叫亞歷山大的銅匠，他說這位銅匠曾害過他很深，並且語帶詛咒的內涵說「主會照他所做的報應他」（提摩太後書四：14）。在這封書信中，他也提到了舒米乃、腓理徒、腓吉路、黑摩其尼，特別是舒米乃，不僅在前書提起，後書又再提起一次，可見這個人在當時的亞細亞省教會造成的影響有多大。使徒保羅將這些人對教會造成傷害的人的名字都一一寫下來，這樣的態度與他寫給羅馬教會書信指導的信仰態度顯然有差別（參考羅馬書十二：14、19-21）。但這種處理教會失序的方式，也成為後來教會引用作為借鏡的一種模式。



