
提摩太後書第二章：當問心無愧的工人
* 1_背景
　　使徒保羅的書信，喜歡引用兩種例子來描述傳福音的人。其一就是將傳福音當作像是在打仗的狀態，要有好的裝備、勇氣，以及軍人那種不懼怕，而且還要有權威的氣質。另外一個素材，就是用競技場上賽跑的情景來形容傳福音的人應該有的精神和態度。

** 1_1_軍人
　　他寫給以弗所教會的書信中這樣說：「所以，你們要準備好。要以真理作腰帶，以正義作護胸甲，以隨時宣揚和平的福音作鞋子穿上。要常常拿著信心的盾牌，好使你們能夠抵禦那邪惡者所射出的一切火箭。你們要以救恩作頭盔，以上帝的話作聖靈所賜的寶劍。」（以弗所書六：14-17）

　　他之所以會有這樣的描述，主要原因就是在於他的看法是：傳福音就是像在打仗，是跟邪惡的力量在打仗，必須要有齊全的裝備，這樣的軍人才不會打敗仗。他寫給腓立比教會的書信中，特別提起信耶穌基督的人，應該就像一個「天上公民」那樣（參考腓立比書三：20）。為甚麼他會這樣說？原因就是腓立比城乃是羅馬政府為退伍軍人建造的城市，羅馬軍人即使退伍了，還是喜歡穿著軍服上街，因為他們覺得當羅馬軍人是件很光榮的事。使徒保羅把羅馬軍人這種對自己角色的榮譽感，將之引用在基督徒的身上，也期盼所有的信徒會因為信耶穌基督，將自己看成是「天上公民」而有無上的光榮一樣。

　　他寫給帖撒羅尼迦教會的書信中出現，他說：「既然我們屬於白晝，就應該戒備。我們要以信和愛作護胸甲穿上，以得救的盼望作頭盔戴上。」（帖撒羅尼迦前書五：8）

　　在寫給歌羅西教會的書信中，使徒保羅提到耶穌基督就是打勝了「靈界執政者和掌權者的權勢，把他們當作凱旋行列中的俘虜，公開示眾」（參考歌羅西書二：15），這讓我們看到信耶穌基督者，就像跟隨耶穌基督去對「靈界執政者和掌權者」打一場屬靈的戰爭，一定要打贏，也確定會打贏，因為有耶穌基督作為後盾。

** 1_2_賽跑
　　在他寫給腓立比教會的書信中有這樣的一段精彩的話說：「這不是說我已經成功，或已經完全了。我繼續奔跑，只求贏得那獎賞；其實，為要使我達到這目標，基督耶穌已經先贏得了我。弟兄姊妹們，我並不認為我已經贏得了這獎賞；我只專心一件事：就是忘記背後，全力追求前面的事。我向著目標直奔，為要得到獎賞；這獎賞就是屬天的新生命，是上帝藉著基督耶穌呼召我去領受的。」（腓立比書三：12-14）這段經文讓我們看到使徒保羅就是將當時羅馬人最熱愛的競技場上賽跑方式，引用到信仰的層面上來。他認為一個信耶穌基督的人，就像一個在競技場上賽跑的選手一樣，要抓住明確目標，然後奮勇地向前努力奔跑。要把那些會纏絆自己得到天上獎賞的障礙都排除掉，因為只有這樣才能完成信仰的終極目標。

　　使徒保羅告訴哥林多教會的信徒，在信仰上要有奪取冠冕的信心，因為那才是生命最高的榮譽。他說：「你們一定知道，在運動場上賽跑的人很多，但是只有一個得獎。所以，你們要抱著奪標的心來跑。每一個運動員接受嚴格的訓練，為要爭取那會朽壞的華冠；但是我們所求的卻是那不朽的冠冕。所以，我只向著目標直奔；我又像鬥拳的人每一拳都不落空。我嚴格地對付自己的身體，為要完全控制它，免得我召喚別人參加競賽，自己反而被淘汰了。」（哥林多前書九：24-27）沒錯，如果信仰的事就像在競技場上賽跑一樣，則所有的信徒就必須接受嚴格的訓練才有可能得獎。信仰的事，不要馬虎。

　　因此，使徒保羅在寫給提摩太的書信中，就有多次引用競技場上的競爭場面來勉勵他，希望提摩太能盡一切心力奮勇向前，好使自己在傳福音的事工上有美好的見證，因為信仰關係到永恆生命的問題。在提摩太前書第六章十二節，他就這樣說：「在信仰的競賽上要盡力奔跑，為自己贏得永恆的生命。」在我們所讀的提摩太後書，他也將自己形容在競技場上盡力跑完全程的人，他說：「那值得競爭的賽跑，我已經跑過；該跑的全程，我已經跑完；該守的信仰，我已經守住。」（提摩太後書四：7）

* 2_經文內容
** 第一至七節：
　　面對亞細亞基督徒的背棄，以及阿尼色弗的忠心耿耿，保羅更加鼓勵提摩太必須在德行上及屬靈的能力上剛強起來。第二節保羅又回到關懷信仰傳承、福音信息內容的純正性。

　　在此保羅表達一個比較急迫的主題，期勉他能勝任基督教牧師的工作，並且憑著信心面對迫害的日子，並鼓勵提摩太與他一同分擔苦難。保羅並不是禁慾的苦行者，但他真心期盼一個基督教牧師應該隨時準備忍受困難。當時的人在信仰上受到迫害時，並不是以人的力量可以克服，因為這種迫害，並不是來自家庭或是個人，而是來自羅馬帝國的執政當局，力量之大可以想像得到。因此，使徒保羅提醒提摩太，不要以為可以倚靠自己的力量勝過這種來自羅馬帝國的迫害，而是要倚靠耶穌基督所賜的恩典。

　　保羅以三個例子來說明他的想法。(1)一個好的士兵不能被營外的私慾纏擾，基督的士兵更是不能被今世的俗務所纏擾。(2)運動員的訓練與紀律。想要勝任自己所有責任和工作的基督教牧師，就必須學著去約束自己。(3)了解勞力是豐收的必要因素，就像農夫辛勤工作一樣。這些都反應出一個牧師在心理上及精神上的訓練。有時牧師必須預備心面對不受歡迎的情形，甚至也必須面對因對上主的忠心而帶來的迫害。

** 第八至十三節：
　　「論到他兒子 - 我主耶穌基督。按肉體說，是從大衛後裔生的；按聖善的靈說，因從死裏復活，以大能顯明是上帝的兒子。」(羅馬書第一章3-4節)，是整篇羅馬書信息的濃縮，可幫助我們來了解提摩太後書第一章9節。保羅所宣講的福音就是爲了見證耶穌爲神人(God-man)。他寫道他就像一個囚犯遭受捆綁，但他知道上帝的話不會被捆綁。一個信仰也不會因爲它的領袖被下在監牢中便會毀滅。而且現在也有人繼續在傳揚，且透過這封從羅馬監獄所寄出的信，保羅自己仍繼續爲耶穌基督做見證。

　　保羅接受了這個困境，因將它視爲自己被耶穌基督差派之後，傳道經歷的一部分。所以，如果保羅一直持守他的信心直到生命的末了，那些跟隨他的人，就能因他的模範而得到支持與認可。保羅對於自己忍受苦難的了解及其重要意義，爲後來的人預備了一個方向、一首讚美詩(11-13節)來激勵自己、來擺上信心。

如果我們已經跟祂同死，我們就會跟祂同活。
如果我們忍耐到底，我們就會跟祂一同掌權。
如果我們不承認祂，祂也不會承認我們。
如果我們失信，祂依然信實可靠，因為祂不違背自己。

　　第一句表達了那些爲基督而死，也將與祂同活的人的信心。第二句則是對忍耐到底這項功課的呼召。事實上，有時爲基督而死，比活著卻不斷地面對迫害還來得容易呢！第三句的動詞用的卻是未來式，似乎暗示著基督不太可能被祂的信徒所棄絕。第三句也是一個嚴正的警告，但它並不會比耶穌在馬太福音十章13節的警告來得更嚴厲。第四句卻是一個充滿希望的信息，也可以是更嚴厲的警惕。它說明了基督必忠實遵守賞罰的標準及要求。然而並不是我們每一顆搖擺不定的信心，都會被我們的上主以嚴厲的審判加以否認和拒絕。「但是，主是信實的；也會使你們堅強，使你們不受那邪惡者的侵害。」(帖撒羅尼迦後書三章3節)假如我們對基督充滿信心的話，我們就能坦然無懼地面對那試驗的日子。

　　請注意，當聖經說上帝是「信實」的上帝時，這句話有三種意義：

(1)上帝永遠遵守祂與人所訂立的約。不論人是否繼續遵守這約，上帝永不改變這約（參考哥林多前書十：13，帖撒羅尼迦後書三：3，希伯來書十：16）。

(2)上帝的愛永不改變。這種觀念在詩篇中一再出現（參考詩篇三十六：5、八十九：1、2、14、28、九十二：2、九十八：3、一○○：5）。

(3)上帝的審判是公義的，而這公義是含有憐憫的意義在裏面（參考詩篇九十六：10、一四三：1，以賽亞書十一：5，約翰一書一：9）。

** 第十四至十九節：
　　從第十八節這句「竟說復活的事已成為過去」的話，可以明白他們受到當時「重智派」（Gnosticism）的影響甚深，認為耶穌基督並不是真正的人存活在世界上，只是個「幻影」而已。福音書告訴我們，耶穌基督復活顯現給門徒們看到的時候，並不是只有靈魂出現，而是實質的肉體顯現在門徒面前，他與門徒一起吃喝，並且要存著懷疑之心的多馬用手去觸摸他被釘十字架的傷痕（參考約翰福音二十：19-28），這些都說明了復活，乃是生命的復活，而生命是包括了肉體與靈魂。

　　第十五節使徒保羅特別勸勉三件事：
(1)要經得起考驗，不要受到誘惑，這不僅是在福音信息的內容上，也是在指生活上的誘惑甚多，必須要有堅定的信心、有堅強的毅力，才能經得起考驗。

(2)「無愧」就是沒有將自己的工作看成是一件羞恥的事。生命的安危。即使在那樣危險的環境中，使徒保羅也是要求提摩太要堅持公開表明自己就是一個福音的工作者。如果傳福音的人，因為懼怕生命的危險，就把自己所擁有的傳道者身份隱藏起來，甚至認為是很羞恥的身份，這就已經失去了當傳道者的意義了。

(3)要正確地講解真理的信息。請注意這裏「正確地講解」之詞所用的希臘文，是由「直的」（horthos）和「切割」（temno）這兩個希臘字合併起來的。意思是開拓一條道路，要將阻礙的地方給予切開，例如穿越山嶺、山洞等，使之成為一條直的道路。另一方面，古時候的石匠，為了要取石材作桌面，就必須正確地切開石頭的面，使之成為筆直且平滑的切割面。這在羅馬帝國時代，用這兩個字在一起，大家就會知道指的就是要有很好的技術，將一條道路開拓得很順暢，或將一塊石頭切割得很好，且因為切割正確，而使切割後的石頭看起來非常美麗。使徒保羅告訴提摩太在解釋聖經上也要如此恰到好處，主要目的就是讓信徒能明白聖經的教訓，並進而喜歡閱讀聖經。

** 第十六至十八節：
　　傳播錯誤信息，就是當時影響早期教會長達三個世紀之久的「重智派」觀念：耶穌基督沒有死，也沒有復活。人的復活只有靈魂，沒有肉體。這也就是為甚麼後來會有「使徒信經」這份影響後來基督教會發展甚大的信仰告白出現的主要原因。最後一句話是我信「肉體的復活，永遠的生命」。請注意，這裏指的是「肉體復活」，而不是說「靈魂復活」。

** 第二十至廿一節：
　　第廿一節說到在教會服事的工作中，不是在分「特別」或「普通」，而是在於潔淨的心為主所用。以色列人用甚麼方式來表明「聖潔」這個意義呢？就是用獻祭。所以，弟兄們，我以上帝的慈悲勸你們，將身體獻上，當作活祭，是聖潔的，是上帝所喜悅的；你們如此事奉乃是理所當然的。(羅馬書十二：1)

** 第廿三節：
　　重複對提摩太的提醒，要他避免陷入會引發爭吵、愚昧無知的辯論。保羅認爲在教義教導的健全之外，還要加上溫柔的心，並要有純正的生活，這些才是上主真正僕人的記號。

* 3_經文信息
** 3_1_作個無愧於福音事工的僕人
　　要成為一個無愧的工人，其最基本的要件，就是從「正確地講解真理的信息」開始。以弗所教會已經有人在傳不正確的信仰知識，說耶穌基督復活已是過去的事了。換句話說，有人在傳講沒有所謂復活這樣的信息，若是有，也只是靈魂復活，身體並不會復活。聖經告訴我們的，是生命的復活。上帝既然以祂的形像創造人類，並且賜給人類有生命之氣，這就是無法消失的「存在」。因此，在基督教信仰中，我們說復活乃是整體的生命，並沒有分開靈魂與肉體。

　　對聖經有正確的了解，就不會受到誘惑，否則很容易因為不正確的講解聖經方式，使信仰偏離了聖經的基礎。教會就是福音的僕人，就是要傳福音，見證福音的。因此，一間教會的信仰內涵好與否，主要就是看該教會是否有在帶領信徒研讀聖經，帶領人來認識聖經上帝的話語。

** 3_2_從我們自己潔淨心靈開始做起_各種不同的才能_才能讓我們成為福音的器皿
　　使徒保羅提醒提摩太，要知道信徒都是來自各種不同階層的人，大家都是身懷上帝所賞賜的不同恩典。這些恩典並不是用來炫耀自己的才華，或是只用來利益自己的需要。使徒保羅提到不同的材質；有的比較「特別」，有的比較「普通」。通常會讓人使用次數最多的，應該是最普通的器皿，也因為這樣，「普通」的器皿通常都不是最昂貴的材質做的。只有很少用到的東西，因為比較「特別」，所以一般來說都是材質比較好的。但越「普通」，與人的關係就越密切；相對的，越「特別」，和人之間互動也就越少。但不論是什麼材質，共同的目的就是為了要傳揚福音。如果我們沒有這樣的認識，要在同一間教會中共同推動福音事工，那是很困難的。

　　教會若要成為一間真正在傳福音的教會，就必須所有的會友都動起來，懷著心甘情願的心一起來參與這些服事的工作。使徒保羅說，這樣的人所奉獻的，才會被上帝所器重。
