
* 提摩太後書第一章：1-18　　中山成主講義　　2016/10/16 呂致中

** 標題：被揀選是因為上帝的愛
** 背景：
　　使徒保羅寫給提摩太的第一封書信時，也就是在羅馬租屋監獄兩年之後，這時候，他人是否在監獄中，或是可以在外面走走旅遊，我們並不能太確定，不過可以知道他是利用了這段空檔時間寫了第一本書信給提摩太，交代他留在以弗所教會協助牧養事工。後來，他又被關進監獄中，那時有些訪客到監所去看他，也跟他提起有關各地教會發生的問題，他覺得事態嚴重，因為許多異端邪說已經侵入教會中，導致教會發生紛爭，於是，他就在監獄中繼續寫另一封書信給提摩太，這就是此本後書的背景。而這封書信也是使徒保羅最後的一封書信，有點像是遺書一樣。

** 經文內容：
*** 第一至二節：
　　使徒保羅在信一開始隨即提到自己就是「奉上帝的旨意」作耶穌基督的「使徒」（參考羅馬書一：1，哥林多前書一：1，哥林多後書一：1，加拉太書一：1，以弗所書一：1，歌羅西書一：1，提摩太前書一：1），原因是許多人喜歡用耶穌基督的十二個門徒才是真正「使徒」當作權威，來否定使徒保羅傳福音的身份，和傳講信息內容的可信度有密切關係。

　　當他在說自己是「奉上帝的旨意」時，意思已經包含了自己被囚禁在監獄的苦難在內。不是事事順利才是「奉上帝的旨意」，而是當一個人遇到困境或是陷入苦難時，也有上帝的旨意在裏面。上帝旨意中的苦難，乃是為了要使人成長得更成熟（參考羅馬書五：3-5）。

　　當使徒保羅認為自己就是「使徒」時，這雖然是一種極大的榮譽，可是那時他已經被羅馬皇帝的法庭宣判為死刑犯，這樣，一個死刑犯有甚麼榮譽可言呢？我們的主耶穌基督，豈不是一再被羞辱嗎？事實上，會有榮譽出現，往往都是後代歷史重新翻案的結果。如果沒有翻案，想自認有榮譽，也不會得到親朋好友的認同。這也就是為甚麼在第十五節之處，使徒保羅很感慨地說：「在亞細亞省的人都離棄了我。」

　　「藉著耶穌基督所應許的新生命」，當一般人看死刑犯是一種羞辱時，使徒保羅卻說在耶穌基督的福音中，生命是嶄新的，不是沉淪的（參考哥林多後書五：17）。

*** 第三至七節：
　　第六至七節，使徒保羅再次提醒提摩太，在他身上的上帝恩賜：

一是有火熱的心。火熱的心用在傳福音的事工上時，就是隨時隨地都在為傳福音著想，不會被環境的困難所挫敗，也不會氣餒。並不是大場面的佈道會才是在傳福音，只要有聖靈充滿的人，隨時隨地都會想要傳福音。

二是不膽怯。對早期教會的信徒來說，要面對羅馬政府逮捕的危險，也要面對自己猶太同胞的威脅。有聖靈恩賜的人，不應該是害怕、膽怯的態度。很可能提摩太有這樣的問題，否則使徒保羅不會在寫給哥林多教會的書信中，特別這樣叮嚀該教會，不要因為他年輕就瞧不起他（參考哥林多前書十六：10-11）。

三是充滿力量。生命充滿聖靈力量的人，可以忍受困難，承擔苦難，勇敢地見證福音。

四是充滿愛心。傳道者必須忍受各式各樣的信徒在信仰上不同態度，忍受各種莫名其妙的毀謗。

五是充滿自制。也就是知道滿足，知道怎樣過嚴謹的生活。

*** 第八至十節：
　　不以福音為羞恥，這是使徒保羅寫給羅馬教會的書信中就已經很清楚告白過的（參考羅馬書一：1）。他現在告訴提摩太，傳福音一定會遇到許多挫折的事，甚至有性命的危險。此時的使徒保羅，已經被逮捕入監牢了，對攻擊使徒保羅的人來說，是他們羞辱使徒保羅最好的機會，可以說他以前傳講的都是虛假的，若是真的，上帝怎麼會讓他遇到苦難呢？類似這樣的問題其實也經常出現在今天的教會中，若是有一位比較活躍在教會事工的人遇到重病，或是家裏發生意外事故，會友或是親人就會這樣問：上帝怎麼會讓這樣熱心福音事工的人遇到這樣的災難？不要因為傳福音遇到迫害或苦難，就覺得羞恥，以為上帝沒有祝福和帶領，而是要將因為福音的緣故而受到的苦難，當作是在分擔耶穌基督的苦難一樣。

　　第九節，使徒保羅很清楚地指出一個人受呼召，並不是因為有甚麼好條件，這點對提摩太來說有特別的意義，因為他是當時以哥念、路司得這兩個地方的人人都稱讚的對象。也許他會認為自己就是有這樣的條件，才會被上帝透過使徒保羅所揀選。但使徒保羅提醒他不是這樣，任何人被上帝揀選，都是因為上帝的恩典。這救贖最根本的奧祕是上帝的心意，一種自由卻又負責任的心意。

　　摩西曾說上帝揀選以色列人，並不是因為以色列民族最強盛，而是因為上帝的愛的緣故（參考申命記七：7）。先知以西結則說以色列人就像一個棄嬰一樣，上帝將他撿起來照顧，養育長大，然後又和以色列民族訂立婚約（參考以西結書十六：4-13）。

　　第十節，當然耶穌並沒有廢除肉體的死亡。在耶穌來到世上之前和之後，所有人的生命都只有走向死亡一途。但耶穌戰勝了死亡。祂死了並且在第三天復活。耶穌告訴門徒，說祂離去是要爲他們預備地方，祂必再回來接他們到祂那裡去。耶穌消除了門徒對死亡的恐懼，並且提供一個確定的盼望，就是他們都將進入天國的家。

*** 第十一至十四節：
傳道者，這是要傳揚耶穌基督救贖的恩典，因為福音的中心就是耶穌基督。

使徒，這是指特殊的角色，在早期教會指的是那些跟隨耶穌基督的十二門徒。使徒保羅說他雖然沒有跟隨耶穌基督，但他成為使徒是上帝和耶穌基督親自揀選任命的。

教師，指幫助信徒明白真確的信仰認知。

　　使徒保羅在第十二節提到為了上述這些角色和任務，他受到許多苦難，在哥林多後書第十一章廿三至廿八節有很詳細描述。這些苦難其實對他不但沒有傷害，反而是增添了他的信心和勇氣（參考羅馬書五：3-5）。

　　「付託」這個字的意思是指將最貴重的東西交給一個可以信任的對象代為管理。因此，福音並不是某個人所擁有的專利品，也不是我們可以決定給誰就給誰。「付託」的另一面，就是要忠實、不欺騙，不能隨便更改被「付託」的內容。

　　在當時的環境，已經不是倚靠個人的力量可以抵擋那些邪說異論，因為這些會誘惑人心的。在第十四節，使徒保羅提醒提摩太，必須倚靠聖靈的力量才有辦法。而使徒保羅強調聖靈是住在每個人的內心，並不是某某人有、誰沒有。

*** 第十五至十八節：
　　亞細亞省，就是在今天的土耳其。以弗所就是亞細亞省的省都，而使徒保羅特別提起亞細亞省，其實就是在告訴提摩太必須小心注意自己過去的失敗。

　　在這兩段保羅個人的回想，第一段是一個很不愉快的回憶，第二段則是他對另一個陌生人深深地致敬。保羅提到兩個背棄他的人的名字，保羅在以弗所認識他們：腓吉路和黑摩其尼。

　　面對許多人的失敗與叛離，阿尼色弗所表現的忠誠顯得令人激賞。他和他的家人都住在以弗所。提摩太也熟知他在教會中服事的擺上。不知什麼原因，阿尼色弗也來到了羅馬，在那裡他遍尋所有監獄中的囚犯，直到他找到了保羅。他的探訪對保羅的幫助非常大，他爲這位孤寂的階下囚提振精神，同時也爲這位偉大使徒的心靈帶來力量。在這封信的最後，保羅還向阿尼色弗一家人問安(四章19節) 。有些聖經註釋者認爲，他的這些話暗示著阿尼色弗已然過世。或者阿尼色弗不在以弗所的家中而遠離在外。

** 經文信息：
*** 一、上帝以祂奇妙的愛揀選了我們，而不是因為有甚麼特別可愛的條件才使上帝揀選我們。
　　如果要說揀選條件，使徒保羅應該是最沒有資格的，因為他是曾大力迫害基督徒（參考腓立比書三：6），逮捕基督徒送入牢獄。但上帝揀選了他，讓他親眼看見復活的耶穌基督，使他因此而被揀選成為原先他在迫害的福音的見證者。上帝揀選一個人來見證福音，並「不是因為我們有甚麼好行為，而是出於他的旨意和恩典」。使徒保羅在寫給提多的信中也再次提起這樣的看法，說上帝「拯救了我們；這並不是因為我們自己有甚麼好行為，而是因為他憐憫我們。」（提多書三：4）

　　因此，被上帝揀選成為傳福音者，是上帝一項特別的恩典，不是讓我們用來驕傲的，而是用來分享、活出來並見證福音的。耶穌基督揀選十二個門徒之後，差派他們出去傳福音時給他們的交代，他說：「隨走隨傳，說『天國近了！』醫治病人，叫死人復活，叫長大痲瘋的潔淨，把鬼趕出去。你們白白地得來，也要白白地捨去。」（馬太福音十：7-8）

　　基督教會就是上帝揀選的福音僕人，應該學習毫無保留地與所有的人分享福音的信息，並活出見證福音的榮耀來。這就是所有的信徒都是「祭司」這個宗教改革運動重要的理念。

*** 二、因為傳福音而受苦難，這是很正常的經驗，也是教會歷史必然遇到的經歷。
　　如果我們翻開台灣教會歷史，就會發現早期宣教師來到台灣時，也是經常活在被羞辱中，甚至是被打死的狀況，像甘為霖牧師在台南白水溪地方差點被當地的民眾用火燒死，而台南神學院院長巴克禮牧師在西螺傳福音時，被當地人用糞便潑灑在身上的際遇，同樣的情況也發生在馬偕牧師的身上等等。今天我們就是「踏」在這些為福音而受難者的身上或血跡上，我們才能安然地分享福音所帶來的喜樂和福氣。

　　如果我們想要讓福音能繼續傳揚出去，就必須心存感恩和準備受難的心；感恩，是因為上帝的愛，透過許多信仰前輩的奉獻，讓我們得到福音的信息。準備受難的心，是我們知道，教會並不是在安逸的環境中生存下去的，而是在苦難中成長起來的。這苦難也可說是面對著社會環境變遷所帶來的各式各樣的挑戰，我們要有勇氣面對，而不是逃避。
