* 目錄
 - [[#1.提摩太前後書導論][1.提摩太前後書導論]]
   - [[#1.1_給牧者的信][1.1_給牧者的信]]
   - [[#1.2_寫作時間][1.2_寫作時間]]
   - [[#1.3_風格與內容][1.3_風格與內容]]
   - [[#1.4_爲何作者的問題這麼重要？對作者的認定會影響解釋][1.4_爲何作者的問題這麼重要？對作者的認定會影響解釋]]
 - [[#2.提摩太後書這本書信][2.提摩太後書這本書信]]
   - [[#2.1_為甚麼要寫這封書信][2.1_為甚麼要寫這封書信]]
   - [[#2.2_使徒保羅寫提摩太後書，心中是相當寂寞的。][2.2_使徒保羅寫提摩太後書，心中是相當寂寞的。]]
   - [[#2.3_在羅馬皇帝尼祿殘酷手段逼害下，已經有不少信徒離棄了信仰。][2.3_在羅馬皇帝尼祿殘酷手段逼害下，已經有不少信徒離棄了信仰。]]

* 1.提摩太前後書導論
** 1.1_給牧者的信
　　提摩太前後書和提多書素來被稱作「教牧書信」。帖撒羅尼迦前後書是寫給教會的；而提摩太前後書與提多書則是寫給個人的。然而，它們也並非純屬私人書信，而是保羅寫給提摩太和提多，教導他們如何做牧者的工作。同時，這些書信時常涉及神學，並且包括一些對教義的重要陳述。大致上來說，這些書信的觀點是極爲實際的，討論到在教會任職者的資格，辨別正確或錯誤教導的能力，以及保存福音信息的純正。其中還談到牧者工作在管理方面的細節，例如對待寡婦的方式、視群眾年齡層及階級的不同調整福音信息，以及帶領會眾禮拜。因此這些書信對於任何一個積極從事教會工作的人來說，都是有助益的。

** 1.2_寫作時間
　　在新約中，帖撒羅尼迦後書之後爲提摩太前書，但這並不意味著提摩太前書緊接著帖撒羅尼迦後書之後即被完成。帖撒羅尼迦前後書可能是保羅書信的第一部，並且我們可合理而準確地推算其於主後五十或五十一年完成。那些認爲提摩太前後書與提多書係由保羅寫成的人，都同意這三卷書是保羅書信的最後部份。承認保羅是上述書信的作者，並不能因此保證可以準確地推算出寫作的時間；要做到這一點需要對保羅的一生做整個的重新組織。但大致上仍有一共識，認爲寫作的時間約在主後六十五至六十七年間。那些認爲保羅不是這些書信之作者的人，寫作時間的認定上有更大的出入，但其中大多數的人認爲應介於第一世紀至第二世紀中葉間。無論哪一種看法，我們都在帖撒羅尼迦前後書及提摩太前後書與提多書中，發現保羅的第一部及最後一部書信之間的對比。

** 1.3_風格與內容
　　敏銳的讀者在研讀教牧書信時，也會察覺在寫作的風格上有不同之處。大致說來，與保羅早期的書信比較之下，教牧書信的筆調顯然較爲平和有序。即使是對假教師譴責的段落，也都相當冗長而且有點沉悶(如提摩太前書一章3-7節；提摩太後二章14-26節；三章1-9-1節；提多書一章10-14節)。在教牧書信中有些重要的段落，值得保羅以他最佳的文筆寫出，但整體看來，它們似乎缺少早期作品中那樣的衝擊與熱情。

　　比風格上差異更爲重要的，是內容上的差異。仔細研究帖撒羅尼迦前後書的學者，會立即察覺到，對基督再來盼望之強調，在比重上有了改變。在帖撒羅尼迦前後書裏，幾乎每一章都可看到這種期盼，並且在許多地方都是保羅進行論證時的主要思想。教牧書信的主要關懷似乎轉變到別的主題。作者非常留意教會組織與架構，教會的紀律，已成爲教牧書信的核心。

　　教牧書信的作者對於保存純正的信仰極爲關心，無論是對於假教師的抨擊、強調健全的教訓、或甚至發展「信仰的託付」的想法，都表現出這樣的關心。作者相信基督信仰的精神中，有一種「傳承」；此傳承被界定爲所接受的託付。它必須被善加守護，並且傳遞給那些努力忠心教導別人的人(提摩太前書四章6節，提摩太後書二章2節)。

** 1.4_爲何作者的問題這麼重要？對作者的認定會影響解釋
　　爲什麼帖撒羅尼迦前後書被公認爲保羅所寫，而提摩太前後書與提多書卻都引起爭論？雖然在此不可能對這問題提出答案，但處理一些所涉及的議題仍是必要的，因爲我們對於這些議題的態度，必會對我們現今如何理解這些書信的信息有所影響。

　　一般唸新約的讀者，將會由於在書信一開頭的身分介紹，以及許多自傳式的內容，而相信教牧書信是由保羅所寫的。但特別鑽研提摩太前後書及提多書的學者，知道這當中仍有一些問題尚未獲得解答。教牧書信與其他保羅書信所使用的語言，有顯而易見的差異。的確，在希臘原文中更容易看出這項差異，但是在英文翻譯版本中也同樣看得出。一個代表性的例子，是在教牧書信中有這樣的句子：「這話是可靠，值得完全接受的」(提摩太前書一章15節；三章1節；四章9節；提摩太後書二章11節；提多書三章9節)；但這種特別的表達方式在保羅的其他書信中並未出現。除此之外，我們若仔細地研究還可以發現，在教牧書信中大概有三分之一的用語，是在保羅早期的書信中找不到的。而且，即使是在這兩類書信中都能發現的用語，在教牧書信中也有著不同的意義。舉例而言，「正義」(righteousness)這個字在教牧書信中用以形容一種道德品質(提摩太前書六章11節；提摩太後書二章22節)；但在羅馬書中，則是用以形容一種信仰的關係。在教牧書信與保羅其他書信中諸如此類的差異，使得細心的學者懷疑，這兩類書信是否真有可能出自同一人之手。

　　在提摩太前書第二章5-6節中有一段著名的文字，闡述「基督是上帝和人之間的中間人」這項教義。它是這麼寫的：「只有一位上帝，在上帝和人之間有一位中間人，就是成爲人的基督耶穌；他犧牲自己爲要使人類得自由，證明了在時機成熟的時候，上帝要人人得救。」這段文字不論是保羅大約在主後六十八年所寫，或是他的門徒在後數十年所寫，均是真確的。然而我們在第7節讀到：「爲了這個目的，我奉差遣作外邦人的傳道者和使徒，作教師來使他們相信並認識真理。我沒有撒謊：我所說的都是真的！」在此作者是誰的問題就關係重大。我們或是看待這一節爲保羅真實無僞的見證，或是認爲它是由保羅門徒在保羅去世後幾年，以他的名義所寫的一段話，雖然這段話被認爲適用於保羅身上。這兩種看法的確會使我們對這一經節做出不同的解釋。並且，就某個意義而言，教義的表述所具有的權威，也受到我們對於第7節之作 者的認定所影響。在提摩太前書第一章12-17節中，有一段傳記，裡頭包含著一項重要的宣告：「『基督耶穌降世的目的是要拯救罪人』這話是可靠、值得完全接受的。」不管我們認爲作者是誰，我們均贊同這段話。但作者繼續說道：「我是罪人中最壞的一個。」(他在此想起他曾迫害教會，這在13節有提到。)他接著又說，因著他受到的憐憫，基督耶穌顯示了「他充分的忍耐，使我得以作那些以後要信他、接受永恆生命的人的榜樣。」在這種自傳式的段落中，作者是誰就成爲我們詮釋經文的關鍵。


* 2.提摩太後書這本書信
　　對於提摩太後書的背景資料，除了這封信所提供之外，其他任何地方無從得知。這是一封非常私人性卻又具啓示性的信。當保羅寫提摩太前書時，他還是自由之身，他差派提摩太往以弗所去，且希望能和他在那裡儘快會合。而寫給提多的信也是保羅能夠自由、積極從事宣教工作之時所完成的。但提摩太後書卻是保羅身處羅馬監獄時才著作的書信。此外，比較這封信與保羅所寫作第一封監獄書信(如歌羅西書) ，反映出截然不同的態度。當保羅第一次下監時，他正等候審判，如同一位尚未判刑的人，仍有機會期待被釋放。但是當他第二次下監時，整個羅馬地區對基督教的態度已經全然改變。寫這封信時，保羅已是一位被判有罪的人， 一位被迫害教派的領袖。經過初審，他已無法倖免於死刑的結局，所以對他的朋友而言，接近保羅是一件很危險的事。除了路加之外，不知什麼原因，保羅所有的朋友都離棄了他。阿尼色弗則找他找得很辛苦。在這種處境下，保羅這封信就成爲他留給提摩太最後的遺音；不僅如此，它更像是一個偉大的使徒留給他所服事過的教會一段最後的話語。在這封書信裡，保羅試著激勵提摩太面對迫害，因此，他不停地描繪著一個有信心的基督徒牧者的形象。在這封寫給他主內親愛兒子的親密信件中，保羅表達了他深切的關懷，如同他正站在人生道路的盡頭，回頭看他作使徒的生命，以及往前看那在墳墓背後與基督同在的生命問安的部分仍是依循著提摩太前書的格式。保羅再一次確認自己使徒的身分而且他是基督耶穌所差派來的人。他成爲使徒並不是因爲自己的選擇，乃是憑著上帝的旨意。至於他宣教的中心目標乃是爲了宣揚「藉著基督耶穌應許的新生命」。他寫信給提摩太就好像寫給一位他所愛的孩子。在前書裡，保羅強調提摩太是他在信仰中真正屬靈的兒子；在後書中，重心則轉移到他對提摩太深切的疼愛。

　　這也是一封使徒保羅在監獄寫的書信，雖然不是像以弗所書、腓立比書、歌羅西書、腓利門書等四本同列為「獄中書信」，我們從第二章九節他提到說：「我因為傳福音而遭受苦難，甚至被捆綁，像囚犯一樣。」就可看出他已經人在監獄中服刑了。但長久以來，提摩太前、後書，以及提多書等這三本都被歸類為所謂「教牧書信」，顧名思義是談到有關在教會牧養工作的問題，主要的目的是在告訴提摩太要怎樣固守著以弗所教會，別讓那些專門在破壞正確信仰的人，在教會中得勢。

** 2.1_為甚麼要寫這封書信
　　當他第一次在羅馬等待受審之時，那時他是備受禮遇，可以在外面租屋居住，隨時有人去請問有關信仰的問題（參考使徒行傳廿八：23）。但現在則不是這樣，他是「被捆綁，像囚犯一樣」（參考提摩太後書二：9）。他這次在監獄中，雖然還沒有被審判該受怎樣的刑期，但卻可看出使徒保羅內心似乎已經有了個譜——死刑（參考四：7）可能為了這個緣故，他急切地希望能見到提摩太，要他「盡快」到羅馬監獄去看他，且最好是趕在冬季之前（參考提摩太後書四：21），可見他與提摩太之間的關係多麼地密切，他曾說提摩太是「惟一」跟他同心的福音伙伴（參考腓立比書二：22）。

** 2.2_使徒保羅寫提摩太後書，心中是相當寂寞的。
　　在第一章十五節，他特別提到說：「在亞細亞省的人都離棄了我，包括腓吉路和黑摩其尼在內。」在第四章十六節說：「我第一次為自己辯護的時候，沒有人在我身邊，大家都離棄了我。願上帝不加罪於他們！」腓吉路和黑摩其尼必定是在亞細亞省教會很有名望的教會領袖，意思是大多數信徒都背棄了使徒保羅。另外一個重要的同工也離開了使徒保羅，那個人就是底馬。他原本與路加都是使徒保羅的同工（參考歌羅西書四：14），為甚麼會離開？使徒保羅說他是因為「貪愛現世」（參考提摩太後書四：10）。但我們知道此時的使徒保羅心中是孤獨的，需要有人在他身邊。

** 2.3_在羅馬皇帝尼祿殘酷手段逼害下，已經有不少信徒離棄了信仰。
　　希望提摩太看待因信仰受逼害的事件，要與其他的信徒有不同的態度。他說：「你不要把為我們的主作證當作一件羞恥的事，也不要因我為了主的緣故成為囚犯而覺得羞恥。你要按照上帝所賜的力量，為福音分擔苦難。」（提摩太後書一：8）可見當時在迫害之下，離棄信仰的人中有人開始對福音所帶來的生命際遇感到難以理解，更嚴重的是將為福音受苦的事當作是一件有羞恥感的事。這種「不以福音為恥」的信仰告白，一再出現在使徒保羅傳福音的態度中。

　　因此，寫這封書信也有一個主要用意，是多給一些鼓勵，即使人已經陷入囹圄中，還是盡他當福音僕人的使命。他從提摩太身上著手鼓勵做起，要他「堅守」從使徒保羅所領受得到的信息，以及和主耶穌之間連結所得到的「信心和愛心」（參考提摩太後書一：13）；要提摩太「持守」所接受的和確信的「真理」（提摩太後書三：14），並鼓勵他無論「時機理不理想都要傳，用最大的耐心勸勉，督責，鼓勵，教導」（提摩太後書四：2）。這讓我們看出，即使是像提摩太這樣值得他信任的同工，甚至可看成是「信仰上的真兒子」，也是要在迫害的時空下，多給一些鼓勵。

** 2.4 很人性化的一本書信
　　聖經中很少有一本經書是這麼清楚將自己的人性需要表露出來的，而提摩太後書卻在這方面充分地讓我們看到：作為一個傳道者在人性上的軟弱。我們看到的使徒保羅也有「孤獨感」的一面，因此，需要有人陪伴他，或是說需要「信仰上的真兒子——提摩太」專程去看他。不但這樣，他還特別交代提摩太去看他的時候，記得將他放在特羅亞的加布家裏之一件外衣帶去。我們不清楚這件外衣為甚麼對他在監獄中有那麼重要，或是說這件外衣在他生命中所代表的特別意義是甚麼，不過擁有一項自己看為最珍貴的物品在身邊，一般人陷入牢獄中也常會有這種想要將珍貴的物品留在身邊，這是很自然的，因為這樣或許對正在孤獨感甚深的受刑人來說，有很大慰藉。他同時要提摩太也為他帶去存放在那兒的一些「羊皮書卷」。所謂「羊皮書卷」，應該指的是舊約聖經。在監獄中閱讀聖經，這情形就像許多在監獄中的囚犯不忘記繼續研讀聖經一樣，我們看到人心靈裏共同的需要，這就是上帝的話語。

　　我們也從這本書信中看到他也在心中還記得一位名叫亞歷山大的銅匠，他說這位銅匠曾害過他很深，並且語帶詛咒的內涵說「主會照他所做的報應他」（提摩太後書四：14）。在這封書信中，他也提到了舒米乃、腓理徒、腓吉路、黑摩其尼，特別是舒米乃，不僅在前書提起，後書又再提起一次，可見這個人在當時的亞細亞省教會造成的影響有多大。使徒保羅將這些人對教會造成傷害的人的名字都一一寫下來，這樣的態度與他寫給羅馬教會書信指導的信仰態度顯然有差別（參考羅馬書十二：14、19-21）。但這種處理教會失序的方式，也成為後來教會引用作為借鏡的一種模式。




* 3.提摩太後書第一章：1-18

** 3.1 標題：被揀選是因為上帝的愛
** 3.2 背景：
　　使徒保羅寫給提摩太的第一封書信時，也就是在羅馬租屋監獄兩年之後，這時候，他人是否在監獄中，或是可以在外面走走旅遊，我們並不能太確定，不過可以知道他是利用了這段空檔時間寫了第一本書信給提摩太，交代他留在以弗所教會協助牧養事工。後來，他又被關進監獄中，那時有些訪客到監所去看他，也跟他提起有關各地教會發生的問題，他覺得事態嚴重，因為許多異端邪說已經侵入教會中，導致教會發生紛爭，於是，他就在監獄中繼續寫另一封書信給提摩太，這就是此本後書的背景。而這封書信也是使徒保羅最後的一封書信，有點像是遺書一樣。

** 3.3 經文內容：
*** 3.3.1 第一至二節：
　　使徒保羅在信一開始隨即提到自己就是「奉上帝的旨意」作耶穌基督的「使徒」（參考羅馬書一：1，哥林多前書一：1，哥林多後書一：1，加拉太書一：1，以弗所書一：1，歌羅西書一：1，提摩太前書一：1），原因是許多人喜歡用耶穌基督的十二個門徒才是真正「使徒」當作權威，來否定使徒保羅傳福音的身份，和傳講信息內容的可信度有密切關係。

　　當他在說自己是「奉上帝的旨意」時，意思已經包含了自己被囚禁在監獄的苦難在內。不是事事順利才是「奉上帝的旨意」，而是當一個人遇到困境或是陷入苦難時，也有上帝的旨意在裏面。上帝旨意中的苦難，乃是為了要使人成長得更成熟（參考羅馬書五：3-5）。

　　當使徒保羅認為自己就是「使徒」時，這雖然是一種極大的榮譽，可是那時他已經被羅馬皇帝的法庭宣判為死刑犯，這樣，一個死刑犯有甚麼榮譽可言呢？我們的主耶穌基督，豈不是一再被羞辱嗎？事實上，會有榮譽出現，往往都是後代歷史重新翻案的結果。如果沒有翻案，想自認有榮譽，也不會得到親朋好友的認同。這也就是為甚麼在第十五節之處，使徒保羅很感慨地說：「在亞細亞省的人都離棄了我。」

　　「藉著耶穌基督所應許的新生命」，當一般人看死刑犯是一種羞辱時，使徒保羅卻說在耶穌基督的福音中，生命是嶄新的，不是沉淪的（參考哥林多後書五：17）。

*** 3.3.2 第三至七節：
　　第六至七節，使徒保羅再次提醒提摩太，在他身上的上帝恩賜：

一是有火熱的心。火熱的心用在傳福音的事工上時，就是隨時隨地都在為傳福音著想，不會被環境的困難所挫敗，也不會氣餒。並不是大場面的佈道會才是在傳福音，只要有聖靈充滿的人，隨時隨地都會想要傳福音。

二是不膽怯。對早期教會的信徒來說，要面對羅馬政府逮捕的危險，也要面對自己猶太同胞的威脅。有聖靈恩賜的人，不應該是害怕、膽怯的態度。很可能提摩太有這樣的問題，否則使徒保羅不會在寫給哥林多教會的書信中，特別這樣叮嚀該教會，不要因為他年輕就瞧不起他（參考哥林多前書十六：10-11）。

三是充滿力量。生命充滿聖靈力量的人，可以忍受困難，承擔苦難，勇敢地見證福音。

四是充滿愛心。傳道者必須忍受各式各樣的信徒在信仰上不同態度，忍受各種莫名其妙的毀謗。

五是充滿自制。也就是知道滿足，知道怎樣過嚴謹的生活。

*** 3.3.3 第八至十節：
　　不以福音為羞恥，這是使徒保羅寫給羅馬教會的書信中就已經很清楚告白過的（參考羅馬書一：1）。他現在告訴提摩太，傳福音一定會遇到許多挫折的事，甚至有性命的危險。此時的使徒保羅，已經被逮捕入監牢了，對攻擊使徒保羅的人來說，是他們羞辱使徒保羅最好的機會，可以說他以前傳講的都是虛假的，若是真的，上帝怎麼會讓他遇到苦難呢？類似這樣的問題其實也經常出現在今天的教會中，若是有一位比較活躍在教會事工的人遇到重病，或是家裏發生意外事故，會友或是親人就會這樣問：上帝怎麼會讓這樣熱心福音事工的人遇到這樣的災難？不要因為傳福音遇到迫害或苦難，就覺得羞恥，以為上帝沒有祝福和帶領，而是要將因為福音的緣故而受到的苦難，當作是在分擔耶穌基督的苦難一樣。

　　第九節，使徒保羅很清楚地指出一個人受呼召，並不是因為有甚麼好條件，這點對提摩太來說有特別的意義，因為他是當時以哥念、路司得這兩個地方的人人都稱讚的對象。也許他會認為自己就是有這樣的條件，才會被上帝透過使徒保羅所揀選。但使徒保羅提醒他不是這樣，任何人被上帝揀選，都是因為上帝的恩典。這救贖最根本的奧祕是上帝的心意，一種自由卻又負責任的心意。

　　摩西曾說上帝揀選以色列人，並不是因為以色列民族最強盛，而是因為上帝的愛的緣故（參考申命記七：7）。先知以西結則說以色列人就像一個棄嬰一樣，上帝將他撿起來照顧，養育長大，然後又和以色列民族訂立婚約（參考以西結書十六：4-13）。

　　第十節，當然耶穌並沒有廢除肉體的死亡。在耶穌來到世上之前和之後，所有人的生命都只有走向死亡一途。但耶穌戰勝了死亡。祂死了並且在第三天復活。耶穌告訴門徒，說祂離去是要爲他們預備地方，祂必再回來接他們到祂那裡去。耶穌消除了門徒對死亡的恐懼，並且提供一個確定的盼望，就是他們都將進入天國的家。

*** 3.3.4 第十一至十四節：
傳道者，這是要傳揚耶穌基督救贖的恩典，因為福音的中心就是耶穌基督。

使徒，這是指特殊的角色，在早期教會指的是那些跟隨耶穌基督的十二門徒。使徒保羅說他雖然沒有跟隨耶穌基督，但他成為使徒是上帝和耶穌基督親自揀選任命的。

教師，指幫助信徒明白真確的信仰認知。

　　使徒保羅在第十二節提到為了上述這些角色和任務，他受到許多苦難，在哥林多後書第十一章廿三至廿八節有很詳細描述。這些苦難其實對他不但沒有傷害，反而是增添了他的信心和勇氣（參考羅馬書五：3-5）。

　　「付託」這個字的意思是指將最貴重的東西交給一個可以信任的對象代為管理。因此，福音並不是某個人所擁有的專利品，也不是我們可以決定給誰就給誰。「付託」的另一面，就是要忠實、不欺騙，不能隨便更改被「付託」的內容。

　　在當時的環境，已經不是倚靠個人的力量可以抵擋那些邪說異論，因為這些會誘惑人心的。在第十四節，使徒保羅提醒提摩太，必須倚靠聖靈的力量才有辦法。而使徒保羅強調聖靈是住在每個人的內心，並不是某某人有、誰沒有。

*** 3.3.5 第十五至十八節：
　　亞細亞省，就是在今天的土耳其。以弗所就是亞細亞省的省都，而使徒保羅特別提起亞細亞省，其實就是在告訴提摩太必須小心注意自己過去的失敗。

　　在這兩段保羅個人的回想，第一段是一個很不愉快的回憶，第二段則是他對另一個陌生人深深地致敬。保羅提到兩個背棄他的人的名字，保羅在以弗所認識他們：腓吉路和黑摩其尼。

　　面對許多人的失敗與叛離，阿尼色弗所表現的忠誠顯得令人激賞。他和他的家人都住在以弗所。提摩太也熟知他在教會中服事的擺上。不知什麼原因，阿尼色弗也來到了羅馬，在那裡他遍尋所有監獄中的囚犯，直到他找到了保羅。他的探訪對保羅的幫助非常大，他爲這位孤寂的階下囚提振精神，同時也爲這位偉大使徒的心靈帶來力量。在這封信的最後，保羅還向阿尼色弗一家人問安(四章19節) 。有些聖經註釋者認爲，他的這些話暗示著阿尼色弗已然過世。或者阿尼色弗不在以弗所的家中而遠離在外。

** 3.4 經文信息：
*** 3.4.1 上帝以祂奇妙的愛揀選了我們，而不是因為有甚麼特別可愛的條件才使上帝揀選我們。
　　如果要說揀選條件，使徒保羅應該是最沒有資格的，因為他是曾大力迫害基督徒（參考腓立比書三：6），逮捕基督徒送入牢獄。但上帝揀選了他，讓他親眼看見復活的耶穌基督，使他因此而被揀選成為原先他在迫害的福音的見證者。上帝揀選一個人來見證福音，並「不是因為我們有甚麼好行為，而是出於他的旨意和恩典」。使徒保羅在寫給提多的信中也再次提起這樣的看法，說上帝「拯救了我們；這並不是因為我們自己有甚麼好行為，而是因為他憐憫我們。」（提多書三：4）

　　因此，被上帝揀選成為傳福音者，是上帝一項特別的恩典，不是讓我們用來驕傲的，而是用來分享、活出來並見證福音的。耶穌基督揀選十二個門徒之後，差派他們出去傳福音時給他們的交代，他說：「隨走隨傳，說『天國近了！』醫治病人，叫死人復活，叫長大痲瘋的潔淨，把鬼趕出去。你們白白地得來，也要白白地捨去。」（馬太福音十：7-8）

　　基督教會就是上帝揀選的福音僕人，應該學習毫無保留地與所有的人分享福音的信息，並活出見證福音的榮耀來。這就是所有的信徒都是「祭司」這個宗教改革運動重要的理念。

*** 3.4.2 因為傳福音而受苦難，這是很正常的經驗，也是教會歷史必然遇到的經歷。
　　如果我們翻開台灣教會歷史，就會發現早期宣教師來到台灣時，也是經常活在被羞辱中，甚至是被打死的狀況，像甘為霖牧師在台南白水溪地方差點被當地的民眾用火燒死，而台南神學院院長巴克禮牧師在西螺傳福音時，被當地人用糞便潑灑在身上的際遇，同樣的情況也發生在馬偕牧師的身上等等。今天我們就是「踏」在這些為福音而受難者的身上或血跡上，我們才能安然地分享福音所帶來的喜樂和福氣。

　　如果我們想要讓福音能繼續傳揚出去，就必須心存感恩和準備受難的心；感恩，是因為上帝的愛，透過許多信仰前輩的奉獻，讓我們得到福音的信息。準備受難的心，是我們知道，教會並不是在安逸的環境中生存下去的，而是在苦難中成長起來的。這苦難也可說是面對著社會環境變遷所帶來的各式各樣的挑戰，我們要有勇氣面對，而不是逃避。
