* 讀_提摩太後書這本書信
作者: 盧俊義牧師  日期: 2011-03-03 17:13
這也是一封使徒保羅在監獄寫的書信，雖然不是像以弗所書、腓立比書、歌羅西書、腓利門書等四本同列為「獄中書信」，我們從第二章九節他提到說：「我因為傳福音而遭受苦難，甚至被捆綁，像囚犯一樣。」就可看出他已經人在監獄中服刑了。但長久以來，提摩太前書、提摩太後書，以及提多書等這三本都被歸類為所謂「教牧書信」。被歸類在「教牧書信」，其實可以顧名思義了解，這三本書信都是談到有關在教會牧養工作的問題，主要的目的是在告訴提摩太要怎樣固守著以弗所教會，別讓那些專門在破壞正確信仰的人，在教會中得勢。

** 為甚麼要寫這封書信

也是從這封書信中，我們知道使徒保羅的一些狀況；包括他曾去過「特羅亞、哥林多、米利多（參考四：、）。他這次在監獄中，雖然還沒有被審判該受怎樣的刑期，但卻可看出使徒保羅內心似乎已經有了個譜——死刑（參考四：）。我們不清楚是誰提供這個資訊給他，也可能為了這個緣故，他急切地希望能見到提摩太，要他「盡快」到羅馬監獄去看他，且最好是趕在冬季之前（參考提摩太後書四：、），可見他與提摩太之間的關係多麼地密切，他曾說提摩太是「惟一」跟他同心的福音伙伴（參考腓立比書二：）。當他第一次在羅馬等待受審之時，那時他是備受禮遇，可以在外面租屋居住，隨時有人去請問有關信仰的問題（參考使徒行傳廿八：—）。但現在則不是這樣，他是「被捆綁，像囚犯一樣」（參考提摩太後書二：）。是甚麼原因有這樣的差別？我們已經無法得到確切的資料。但從這封書信可看出幾點問題：


** 一、使徒保羅寫提摩太後書，心中是相當寂寞的。

在第一章十五節，他特別提到說：「在亞細亞省的人都離棄了我，包括腓吉路和黑摩其尼在內。」在第四章十六節說：「我第一次為自己辯護的時候，沒有人在我身邊，大家都離棄了我。願上帝不加罪於他們！」我們雖然不知道腓吉路和黑摩其尼這兩個人到底是誰，不過可以瞭解他們必定是在亞細亞省教會很有名望的教會領袖，否則使徒保羅不必刻意提起他們的名字讓提摩太知道。當然不會是亞細亞省全體教會都背棄了使徒保羅，這只是一種概略性的說法，意思是大多數信徒的反應。因為提摩太就在以弗所教會工作，而以弗所教會就在亞細亞省的首府。另外一個重要的同工也離開了使徒保羅，那個人就是底馬。他原本與路加都是使徒保羅的同工（參考歌羅西書四：），為甚麼會離開？使徒保羅說他是因為「貪愛現世」（參考提摩太後書四：）。但我們知道此時的使徒保羅心中是孤獨的，需要有人在他身邊。

** 二、在羅馬皇帝尼祿殘酷手段逼害下，已經有不少信徒離棄了信仰。

因此，使徒保羅希望提摩太看待因信仰受逼害的事件，要與其他的信徒有不同的態度。他說：「你不要把為我們的主作證當作一件羞恥的事，也不要因我為了主的緣故成為囚犯而覺得羞恥。你要按照上帝所賜的力量，為福音分擔苦難。」（提摩太後書一：）可見當時在迫害之下，離棄信仰的人中有人開始對福音所帶來的生命際遇感到難以理解，更嚴重的是將為福音受苦的事當作是一件有羞恥感的事。雖然沒有說明底馬「貪愛現世」的實際內情，但多少是與這種「羞恥感」有關係的。這種「不以福音為恥」的信仰告白，一再出現在使徒保羅傳福音的態度中（參考羅馬書一：）。

因此，寫這封書信也有一個主要用意，是多給一些鼓勵，即使人已經陷入囹圄中，還是盡他當福音僕人的使命。他從提摩太身上著手鼓勵做起，要他「堅守」從使徒保羅所領受得到的信息，以及和主耶穌之間連結所得到的「信心和愛心」（參考提摩太後書一：）；要提摩太「持守」所接受的和確信的「真理」（提摩太後書三：），並鼓勵他無論「時機理不理想都要傳，用最大的耐心勸勉，督責，鼓勵，教導」（提摩太後書四：）。這讓我們看出，即使是像提摩太這樣值得他信任的同工，甚至可看成是「信仰上的真兒子」，他也是要在迫害的時空下，多給一些鼓勵。如果連在監獄中的「囚犯」都會這樣用心鼓勵非囚犯的人，必定對受信人提摩太有相當大的意義。

很人性化的一本書信

聖經中很少有一本經書是這麼清楚將自己的人性需要表露出來的，而提摩太後書卻在這方面充分地讓我們看到：作為一個傳道者在人性上的軟弱。我們看到的使徒保羅也有「孤獨感」的一面，因此，需要有人陪伴他，或是說需要「信仰上的真兒子——提摩太」專程去看他。不但這樣，他還特別交代提摩太去看他的時候，記得將他放在特羅亞的加布家裏之一件外衣帶去。我們不清楚這件外衣為甚麼對他在監獄中有那麼重要，或是說這件外衣在他生命中所代表的特別意義是甚麼，不過擁有一項自己看為最珍貴的物品在身邊，一般人陷入牢獄中也常會有這種想要將珍貴的物品留在身邊，這是很自然的，因為這樣或許對正在孤獨感甚深的受刑人來說，有很大慰藉的公用，使徒保羅在這方面並不例外。

他同時要提摩太也為他帶去存放在那兒的一些「羊皮書卷」。所謂「羊皮書卷」，應該指的是舊約聖經。因為在使徒保羅的時代，聖經都半都是用刀子刻在羊皮，然後將之捲起來，因此，一般稱聖經都是「卷」。當然也有些聖經版本是寫在當時普遍流行用浦草製成的紙上。在監獄中閱讀聖經，這情形就像許多在監獄中的囚犯不忘記繼續研讀聖經一樣，我們看到人心靈裏共同的需要，這就是上帝的話語。

我們也從這本書信中看到他也在心中還記得一位名叫亞歷山大的銅匠，他說這位銅匠曾害過他很深，並且語帶詛咒的內涵說「主會照他所做的報應他」（提摩太後書四：）。在這封書信中，他也提到了舒米乃、腓理徒、腓吉路、黑摩其尼，特別是舒米乃，不僅在前書提起，後書又再提起一次，可見這個人在當時的亞細亞省教會造成的影響有多大。使徒保羅將這些人對教會造成傷害的人的名字都一一寫下來，這樣的態度與他寫給羅馬教會書信指導的信仰態度顯然有差別（參考羅馬書十二：、—）。但這種處理教會失序的方式，也成為後來教會引用作為借鏡的一種模式。


** 可分成下列幾個段落

一、 請安；一：—。
二、 感謝的話；一：—。
三、 勸勉提摩太；一：—二：。
四、 信仰上應該有的態度；二：—。
五、 注意末日來臨的現象；三：—四：。
六、 使徒保羅自己的評語；四：—。
七、 交代最後的話語；四：—。
八、 代問候語；四：—。


* 提摩太後書一：1-18
** 標題：被揀選是因為上帝的愛
** 背景：
使徒保羅寫寫給提摩太的第一封書信時，也就是在羅馬租屋監獄兩年之後，這時候，他人是否在監獄中，或是可以在外面走走旅遊，我們並不能太確定，不過可以知道他是利用了這段空檔時間寫了第一本書信給提摩太，交代他留在以弗所教會協助牧養事工。後來，他又被關進監獄中，那時有些訪客到監所去看他，也跟他提起有關各地教會發生的問題，他覺得事態嚴重，因為許多異端邪說已經侵入教會中，導致教會發生紛爭，於是，他就在監獄中繼續寫另一封書信給提摩太，這就是此本後書的背景。而這封書信也是使徒保羅最後的一封書信，有點像是遺書一樣。

** 經文內容：
*** 第一至二節：
**** 經文
我是保羅；我奉上帝的旨意作基督耶穌的使徒，來宣佈他藉著基督耶穌所應許的新生命。我寫信給你—我親愛的兒子提摩太：

願父上帝和我們的主基督耶穌賜恩典、憐憫、平安給你！
**** 解釋
使徒保羅在信一開始隨即提到自己就是「奉上帝的旨意」作耶穌基督的「使徒」（參考羅馬書一：，哥林多前書一：，哥林多後書一：，加拉太書一：，以弗所書一：，歌羅西書一：，提摩太前書一：），原因是許多人喜歡用耶穌基督的十二個門徒才是真正「使徒」當作權威，來否定使徒保羅傳福音的身份，和傳講信息內容的可信度有密切關係。

請注意，當他在說自己是「奉上帝的旨意」時，意思已經包含了自己被囚禁在監獄的苦難在內。不是事事順利才是「奉上帝的旨意」，而是當一個人遇到困境或是陷入苦難時，也有上帝的旨意在裏面。上帝旨意中的苦難，乃是為了要使人成長得更成熟（參考羅馬書五：—）。

當使徒保羅認為自己就是「使徒」時，這雖然是一種極大的榮譽，可是那時他已經被羅馬皇帝的法庭宣判為死刑犯，這樣，一個死刑犯有甚麼榮譽可言呢？我們的主耶穌基督，豈不是一再被羞辱嗎？事實上，會有榮譽出現，往往都是後代歷史重新翻案的結果。如果沒有翻案，想自認有榮譽，也不會得到親朋好友的認同。這也就是為甚麼在第十五節之處，使徒保羅很感慨地說：「在亞細亞省的人都離棄了我。」

「藉著耶穌基督所應許的新生命」，當一般人看死刑犯是一種羞辱時，使徒保羅卻說在耶穌基督的福音中，生命是嶄新的，不是沉淪的（參考哥林多後書五：）。

*** 第三至七節：
**** 經文
我感謝上帝，就是那位我跟祖宗一樣用清白的良心所敬拜的上帝。我日夜在禱告中懷念著你，一想起你惜別時所流的眼淚，我就急切地想要見你；見到你，我就會滿心快樂。我記得你那純真的信心，就是你外祖母羅綺和你母親友妮基所有的那種信心。她們的信心，我相信你也有了。所以，我提醒你：那在我為你按手時上帝所賜給你的恩賜，你要使它像火一樣燃燒不熄。因為，上帝所賜給我們的靈不使我們膽怯；相反地，他的靈會使我們充滿力量、愛心，和自制。

**** 解釋
第六至七節，使徒保羅再次提醒提摩太，在他身上有上帝賞賜的恩賜。

一是有火熱的心。火熱的心用在傳福音的事工上時，就是隨時隨地都在為傳福音著想，不會被環境的困難所挫敗，也不會氣餒。並不是大場面的佈道會才是在傳福音，只要有聖靈充滿的人，隨時隨地都會想要傳福音。

二是不膽怯。對早期教會的信徒來說，要面對羅馬政府逮捕的危險，也要面對自己猶太同胞的威脅。有聖靈恩賜的人，不應該是害怕、膽怯的態度。很可能提摩太有這樣的問題，否則使徒保羅不會在寫給哥林多教會的書信中，特別這樣叮嚀該教會，不要因為他年輕就瞧不起他（參考哥林多前書十六：—）。

三是充滿力量。生命充滿聖靈力量的人，可以忍受困難，承擔苦難，勇敢地見證福音。


四是充滿愛心。傳道者必須忍受各式各樣的信徒在信仰上不同態度，忍受各種莫名其妙的毀謗。

五是充滿自制。也就是知道滿足，知道怎樣過嚴謹的生活。

*** 第八至十節：
**** 經文
因此，你不要把為我們的主作證當作一件羞恥的事，也不要因我為了主的緣故成為囚犯而覺得羞恥。你要按照上帝所賜的力量，為福音分擔苦難。上帝拯救我們，呼召我們作他的子民，並不是因為我們有甚麼好行為，而是出於他的旨意和恩典。他在萬世以前就藉著基督耶穌把這恩典賜給了我們，現在由於我們的救主基督耶穌的來臨而實現了。基督已經毀滅了死亡的權勢，更藉著福音把不朽的生命彰顯出來。

不以福音為羞恥，這是使徒保羅寫給羅馬教會的書信中就已經很清楚告白過的（參考羅馬書一：）。他現在告訴提摩太，就是要讓提摩太清楚知道，傳福音一定會遇到許多挫折的事，特別是在使徒保羅的時代，傳福音甚至有性命的危險，若僅僅是一般謾罵言詞的羞辱，那還是最輕省的擔子。比較嚴重的，乃是會被逮捕送入監牢去餵野獸，或是送到競技場去跟人搏鬥。

**** 解釋
此時的使徒保羅，已經被逮捕入監牢了，對攻擊使徒保羅的人來說，是他們羞辱使徒保羅最好的機會，可以說他以前傳講的都是虛假的，若是真的，上帝怎麼會讓他遇到苦難呢？類似這樣的問題其實也經常出現在今天的教會中，若是有一位比較活躍在教會事工的人遇到重病，或是家裏發生意外事故，會友或是親人就會這樣問：上帝怎麼會讓這樣熱心福音事工的人遇到這樣的災難？

不要因為傳福音遇到迫害或苦難，就覺得羞恥，以為上帝沒有祝福和帶領，而是要將因為福音的緣故而受到的苦難，當作是在分擔耶穌基督的苦難一樣。

第九節，使徒保羅很清楚地指出一個人受呼召，並不是因為有甚麼好條件，這點對提摩太來說有特別的意義，因為他是當時以哥念、路司得這兩個地方的人人都稱讚的對象。也許他會認為自己就是有這樣的條件，才會被上帝透過使徒保羅所揀選。但使徒保羅提醒他不是這樣，任何人被上帝揀選，都是因為上帝的恩典。

摩西曾說上帝揀選以色列人，並不是因為以色列民族最強盛，而是因為上帝的愛的緣故（參考申命記七：）。先知以西結則說以色列人就像一個棄嬰一樣，上帝將他撿起來照顧，養育長大，然後又和以色列民族訂立婚約（參考以西結書十六：—）。

第十節，這救贖最根本的奧祕是上帝的心意，一種自由卻又負責任的心意。

當然耶穌並沒有廢除肉體的死亡。在耶穌來到世上之前和之後，所有人的生命都只有走向死亡一途。但耶穌戰勝了死亡。祂死了並且在第三天復活。耶穌告訴門徒，說祂離去是要爲他們預備地方，祂必再回來接他們到祂那裡去。耶穌消除了門徒對死亡的恐懼，並且提供一個確定的盼望，就是他們都將進入天國的家。

*** 第十一至十四節：
**** 經文
為了這福音，上帝指派我作傳道者、使徒，和教師。因此，我才受這些苦難。但是，我仍然滿懷確信；因為我知道我所信靠的是誰，也深信他能夠保守他所付託給我的，直到主再來的日子。你要堅守我所給你的那健全的信息，作為你的規範，也要守住我們跟基督耶穌連結所得到的信心和愛心。要藉著住在我們內心的聖靈持守那付託給你的美善。

**** 解釋
傳道者，這是要傳揚耶穌基督救贖的恩典，因為福音的中心就是耶穌基督。

使徒，這是指特殊的角色，在早期教會指的是那些跟隨耶穌基督的十二門徒。使徒保羅說他雖然沒有跟隨耶穌基督，但他成為使徒是上帝和耶穌基督親自揀選任命的。

教師，指幫助信徒明白真確的信仰認知。

使徒保羅在第十二節提到為了上述這些角色和任務，他受到許多苦難，在哥林多後書第十一章廿三至廿八節有很詳細描述。這些苦難其實對他不但沒有傷害，反而是增添了他的信心和勇氣（參考羅馬書五：—）。

「付託」這個字的意思是指將最貴重的東西交給一個可以信任的對象代為管理。因此，福音並不是某個人所擁有的專利品，也不是我們可以決定給誰就給誰。

「付託」的另一面，就是要忠實、不欺騙，不能隨便更改被「付託」的內容。

在當時的環境，已經不是倚靠個人的力量可以抵擋那些邪說異論，因為這些會誘惑人心的。在第十四節，使徒保羅提醒提摩太，必須倚靠聖靈的力量才有辦法。而使徒保羅強調聖靈是住在每個人的內心，並不是某某人有、誰沒有。

*** 第十五至十八節：
**** 經文
你知道，在亞細亞省的人都離棄了我，包括腓吉路和黑摩其尼在內。願主憐憫阿尼色弗一家；因為他屢次鼓勵我，使我精神愉快。他不因我作囚犯而覺得羞恥，一到羅馬就四處尋找我，終於找到了。願主使他在那日子得到主的憐憫！至於他在以弗所為我做的許多事，你是清楚知道的。

**** 解釋
亞細亞省，就是在今天的土耳其。以弗所就是亞細亞省的省都，而使徒保羅特別提起亞細亞省，其實就是在告訴提摩太必須小心注意自己過去的失敗。

在這兩段保羅個人的回想，第一段是一個很不愉快的回憶，第二段則是他對另一個陌生人深深地致敬。保羅提到兩個背棄他的人的名字，保羅在以弗所認識他們：腓吉路和黑摩其尼。

面對許多人的失敗與叛離，阿尼色弗所表現的忠誠顯得令人激賞。他和他的家人都住在以弗所。提摩太也熟知他在教會中服事的擺上。不知什麼原因，阿尼色弗也來到了羅馬，在那裡他遍尋所有監獄中的囚犯，直到他找到了保羅。他的探訪對保羅的幫助非常大，他爲這位孤寂的階下囚提振精神，同時也爲這位偉大使徒的心靈帶來力量。在這封信的最後，保羅還向阿尼色弗一家人問安(四章19節) 。有些聖經註釋者認爲，他的這些話暗示著阿尼色弗已然過世。或者阿尼色弗不在以弗所的家中而遠離在外。

** 經文信息：
*** 一、上帝以祂奇妙的愛揀選了我們，而不是因為有甚麼特別可愛的條件才使上帝揀選我們。
　　如果要說揀選條件，使徒保羅應該是最沒有資格的，因為他是曾大力迫害基督徒（參考腓立比書三：），逮捕基督徒送入牢獄。但上帝揀選了他，讓他親眼看見復活的耶穌基督，使他因此而被揀選成為原先他在迫害的福音的見證者。上帝揀選一個人來見證福音，並「不是因為我們有甚麼好行為，而是出於他的旨意和恩典」。使徒保羅在寫給提多的信中也再次提起這樣的看法，說上帝「拯救了我們；這並不是因為我們自己有甚麼好行為，而是因為他憐憫我們。」（提多書三：）

　　因此，被上帝揀選成為傳福音者，是上帝一項特別的恩典，不是讓我們用來驕傲的，而是用來分享、活出來並見證福音的。耶穌基督揀選十二個門徒之後，差派他們出去傳福音時給他們的交代，他說：「隨走隨傳，說『天國近了！』醫治病人，叫死人復活，叫長大痲瘋的潔淨，把鬼趕出去。你們白白地得來，也要白白地捨去。」（馬太福音十：7-8）

　　基督教會就是上帝揀選的福音僕人，應該學習毫無保留地與所有的人分享福音的信息，並活出見證福音的榮耀來。這就是所有的信徒都是「祭司」這個宗教改革運動重要的理念。

*** 二、因為傳福音而受苦難，這是很正常的經驗，也是教會歷史必然遇到的經歷。
　　如果我們翻開台灣教會歷史，就會發現早期宣教師來到台灣時，也是經常活在被羞辱中，甚至是被打死的狀況，像甘為霖牧師在台南白水溪地方差點被當地的民眾用火燒死，而台南神學院院長巴克禮牧師在西螺傳福音時，被當地人用糞便潑灑在身上的際遇，同樣的情況也發生在馬偕牧師的身上等等。今天我們就是「踏」在這些為福音而受難者的身上或血跡上，我們才能安然地分享福音所帶來的喜樂和福氣。

　　如果我們想要讓福音能繼續傳揚出去，就必須心存感恩和準備受難的心；感恩，是因為上帝的愛，透過許多信仰前輩的奉獻，讓我們得到福音的信息。準備受難的心，是我們知道，教會並不是在安逸的環境中生存下去的，而是在苦難中成長起來的。這苦難也可說是面對著社會環境變遷所帶來的各式各樣的挑戰，我們要有勇氣面對，而不是逃避。


* 第二講：當問心無愧的工人
作者: 盧俊義牧師  日期: 2011-03-03 17:11
經文：提摩太後書二：—

如果我們認真看使徒保羅的書信，就會發現有兩種材料是他很喜歡引用作為材料的，其一就是將傳福音當作像是在打仗的狀態，因此，他經常會引用如同打仗的軍人一樣，要有好的裝備、勇氣，以及軍人那種不懼怕，而且還要有權威的氣質。例如他寫給以弗所教會的書信中這樣說：

「所以，你們要準備好。要以真理作腰帶，以正義作護胸甲，以隨時宣揚和平的福音作鞋子穿上。要常常拿著信心的盾牌，好使你們能夠抵禦那邪惡者所射出的一切火箭。你們要以救恩作頭盔，以上帝的話作聖靈所賜的寶劍。」（以弗所書六：—）

這段話讀起來幾乎就是像一個穿戴齊全的武裝軍人要出征一般。他之所以會有這樣的描述，主要原因就是在於他的看法是：傳福音就是像在打仗，是跟邪惡的力量在打仗，必須要有齊全的裝備，這樣的軍人才不會打敗仗，以免尚未出去開打，就已經失敗了，那就不是一個好的傳道者。他寫給腓立比教會的書信中，特別提起信耶穌基督的人，應該就像一個「天上公民」那樣（參考腓立比書三：）。為甚麼他會這樣說？原因就是腓立比城乃是羅馬政府為退伍軍人建造的城市，羅馬軍人即使退伍了，還是喜歡穿著軍服上街，因為他們覺得當羅馬軍人是件很光榮的事。使徒保羅把羅馬軍人這種對自己角色的榮譽感，將之引用在基督徒的身上，也期盼所有的信徒會因為信耶穌基督，將自己看成是「天上公民」而有無上的光榮一樣。
像軍人這樣的裝備樣式，也在他寫給帖撒羅尼迦教會的書信中出現，他說：
「既然我們屬於白晝，就應該戒備。我們要以信和愛作護胸甲穿上，以得救的盼望作頭盔戴上。」（帖撒羅尼迦前書五：）

在寫給歌羅西教會的書信中，使徒保羅提到耶穌基督就是打勝了「靈界執政者和掌權者的權勢，把他們當作凱旋行列中的俘虜，公開示眾」（參考歌羅西書二：），這讓我們看到信耶穌基督者，就像跟隨耶穌基督去對「靈界執政者和掌權者」打一場屬靈的戰爭，一定要打贏，也確定會打贏，因為有耶穌基督作為後盾。

另外使徒保羅喜歡用的一個素材，就是用競技場上賽跑的情景來形容傳福音的人應該有的精神和態度。在他寫給腓立比教會的書信中有這樣的一段精彩的話說：

「這不是說我已經成功，或已經完全了。我繼續奔跑，只求贏得那獎賞；其實，為要使我達到這目標，基督耶穌已經先贏得了我。弟兄姊妹們，我並不認為我已經贏得了這獎賞；我只專心一件事：就是忘記背後，全力追求前面的事。我向著目標直奔，為要得到獎賞；這獎賞就是屬天的新生命，是上帝藉著基督耶穌呼召我去領受的。」（腓立比書三：—）

這段經文讓我們看到使徒保羅就是將當時羅馬人最熱愛的競技場上賽跑方式，引用到信仰的層面上來。他認為一個信耶穌基督的人，就像一個在競技場上賽跑的選手一樣，要抓住明確目標，然後奮勇地向前努力奔跑。要把那些會纏絆自己得到天上獎賞的障礙都排除掉，因為只有這樣才能完成信仰的終極目標。

使徒保羅告訴哥林多教會的信徒，在信仰上要有奪取冠冕的信心，因為那才是生命最高的榮譽。他說：
「你們一定知道，在運動場上賽跑的人很多，但是只有一個得獎。所以，你們要抱著奪標的心來跑。每一個運動員接受嚴格的訓練，為要爭取那會朽壞的華冠；但是我們所求的卻是那不朽的冠冕。所以，我只向著目標直奔；我又像鬥拳的人每一拳都不落空。我嚴格地對付自己的身體，為要完全控制它，免得我召喚別人參加競賽，自己反而被淘汰了。」（哥林多前書九：—）

沒錯，如果信仰的事就像在競技場上賽跑一樣，則所有的信徒就必須接受嚴格的訓練才有可能得獎。這是使徒保羅寫給哥林多教會的書信中所強調的。信仰的事，不要馬虎，這樣的認識是非常重要的，可惜，使徒保羅兩千年前對哥林多教會信徒所提醒的事，今天的信徒似乎更冷淡漠視了。

牧會三十年來，很多人都說我很凶悍、嚴格，其實，說穿了，我只有一個心願，就是在我牧養的教會沒有軟弱的信徒。這樣的要求不僅是在對信徒，更是對自己獻身傳道的一種自我期許。如果我們沒有這樣的心境，我們又怎能說要與邪惡的撒但、魔鬼對抗呢？很難啊！

因此，使徒保羅在寫給提摩太的書信中，就有多次引用競技場上的競爭場面來勉勵他，希望提摩太能盡一切心力奮勇向前，好使自己在傳福音的事工上有美好的見證，因為信仰關係到永恆生命的問題。在提摩太前書第六章十二節，他就這樣說：「在信仰的競賽上要盡力奔跑，為自己贏得永恆的生命。」在我們所讀的提摩太後書，他也將自己形容在競技場上盡力跑完全程的人，他說：
「那值得競爭的賽跑，我已經跑過；該跑的全程，我已經跑完；該守的信仰，我已經守住。」（提摩太後書四：）

一個傳道者要說出這樣的話，可不是一句隨便可說得出來的話語。但用在使徒保羅身上，他真的是當之無愧，因為他確實用全部生命的力量在傳福音事工上，這一點我相信是沒有人會否認的事。

** 現在讓我們來看看所讀這段經文的內容：
*** 第一至七節：
我兒啊，你要藉著基督耶穌所賜的恩典剛強起來。你在許多證人面前從我領受了的教導，你也應該交付給你所信任而能夠教導別人的人。

作為基督耶穌的忠勇戰士，你要分擔苦難。一個入伍的兵士要爭取長官的嘉許就不能讓營外的事務纏擾他。一個賽跑的人在競賽的時候不遵守規則就不能得獎。辛勤耕作的農夫應該首先享受所收成的穀物。你要思想我所說的話，因為主必定使你能領悟一切的事。

在一個受難的時代，特別是當使徒保羅再次被抓入監牢時，對許多信徒來說是很大的衝擊。因此，就像在後書第一章十五節使徒保羅所說的：「在亞細亞省的人都離棄了我，包括腓吉路和黑摩其尼在內。」這看起來好像很失望的樣子，使徒保羅因此勸勉提摩太，必須要剛強起來，就像在第一章十六節所提到的好的同工阿尼色弗，他就是忠心耿耿的好同工，因此帶給使徒保羅許多鼓勵。而從第二節我們還看到另外有一群信徒，他們都是很忠心地跟隨著提摩太所傳達的信息，而提摩太就是從使徒保羅領受福音信息的。

在這裏使徒保羅也讓我們看到，當時的人在信仰上受到迫害時，並不是以人的力量可以克服，因為這種迫害，並不是來自家庭或是個人，而是來自羅馬帝國的執政當局，力量之大可以想像得到。因此，使徒保羅提醒提摩太，不要以為可以倚靠自己的力量勝過這種來自羅馬帝國的迫害，而是要倚靠耶穌基督所賜的恩典。

第三至四節就像我在前面已經提過的，使徒保羅最喜歡使用的材料之一，就是將羅馬軍隊那種雄壯威武的樣式帶入信仰上來看。在他的觀念中，一個人若是信耶穌基督，就要跟隨耶穌基督的腳步，這樣的人一定要像一個勇敢善戰的軍人，很專心。因為信仰上的敵對者是無孔不入的，這是屬靈的戰爭，不是一般的戰爭，如若稍有疏忽，很快就會瓦解信仰的基礎。

請注意第三節特別提到作為基督的精兵，要「分擔苦難」，將這句話比較希伯來書第十三章廿三節，就會看到提摩太後來確實也曾因為傳福音的緣故入獄了。

第五節再次提到競技場上的賽跑者，在這裏尤其強調守規矩，這幾乎就是競技場上一種最重要的榮譽，因為遵守競賽的規定而得勝者，這樣的得勝者才會有榮譽可言。若是有人作假，就會使這樣的競賽失去公平的基礎。也因為當時這項傳統，今天的奧林匹克運動會對參賽者要求甚為嚴格，只要發現有人作弊或是服用禁藥，都會將他所得到的榮譽取消，並且還會禁止參賽一段時間，以示懲罰。

另一方面，所謂守規則，不僅是在競技場上，而是從運動員的訓練開始就必須嚴格遵守規則，否則很容易在訓練過程中發生意外，要不，就是在正式比賽時，會投機取巧。

第六節則是提到農夫最先享受自己辛苦撒種、耕種所得到的果實。請注意在這裏使徒保羅是說「辛勤耕作」，這句話已經說出一個最基本的認識：天下沒有白吃的午餐。用在農事上更清楚，因為想要有好的收成，就必須有辛勞的耕種。即使在今天科技這樣發達的時代，這句話也是定律。

使徒保羅從軍人談到競賽者，最後以農夫的耕種作為比喻，來形容作為一個傳道者應該有的工作態度，他在最後還告訴提摩太，必須好好認真思想他所說的話。這樣的交代通常也是父母對子女所說的，在這一章一開始，使徒保羅就是以「我兒啊」這樣的稱呼來開始這封後書的內容，可以想像得到，他就像提摩太信仰上的父親，在期待自己的子女真的會用心、認真在傳福音的事工上。

*** 第八至十三節：
你要記得耶穌基督，他是大衛的後代，上帝使他從死裏復活；這就是我所傳的福音。我因為傳這福音而遭受苦難，甚至被捆綁，像囚犯一樣。但是，上帝的話是不受捆綁的。因此，我為了上帝所揀選的子民忍受這一切，好使他們也能得到那從基督耶穌來的拯救和永恆的榮耀。以下這話是可靠的：
如果我們已經跟他同死，
我們也會跟他同活。
如果我們忍耐到底，
我們也會跟他一同掌權。
如果我們不認他，
他也會不認我們。
如果我們失信，
他依然信實可靠，
因為他不違背自己。

這段經文也是一首簡短的詩歌，卻是使徒保羅寫給提摩太書信中最重要的一段經文，因為這首詩歌可說就是使徒保羅的信仰告白一樣。使徒保羅在這裏提到幾個重要的信仰內涵：
第一，耶穌基督復活，這就是福音。當我們看使徒行傳時，就會明白使徒保羅就是一面纏訟官司，一面在宣揚「耶穌基督復活」這個信息；他只說了一句「因為我盼望死人復活」，就讓那些嚷著要把他打死的群眾分成兩派（參考使徒行傳廿三：—），也因為他說「相信死人復活的道理」，使審判他的總督腓力斯拒絕了猶太人的控告，進而寬待使徒保羅（參考使徒行傳廿四：、）。也因為他一再強調「基督必須受害，並且首先從死裏復活，向猶太人和外邦人宣佈拯救的亮光已經來到」，讓總督非斯都大受不了（參考使徒行傳廿六：—）。雖然表面上，他傳這樣的信息被關進囚房中，可是卻也因為他拼命傳揚這個信息，使許多人因此而信耶穌基督。

第二，為讓更多人得到耶穌基督拯救的信息，以及永恆生命的榮耀，甘願忍受苦難。這一直是使徒保羅最令人感動的地方，在他寫給羅馬教會的書信中，他甚至這樣說：「為了我的同胞，我骨肉之親，縱使我自己被上帝詛咒，跟基督隔絕，我也願意。」（羅馬書九：）這是指猶太人說的。但使徒保羅和提摩太都是在外邦人當中傳福音，且一再強調在耶穌基督裏，已經不再有猶太人與外邦人之分，大家在耶穌基督裏，都是「上帝子民的同胞，是上帝一家的人」（參考以弗所書二：）。換句話，只要能使人藉著耶穌基督而獲得拯救，他即使因此而受苦，也願意忍受。這樣的偉大情操，實在是非常值得今天所有傳道者應該要好好省思的功課。

第三，所有耶穌基督的信徒，都將因與耶穌基督連結在一起，與他同死也同復活。這一點可說是使徒保羅最重要的思想，在他寫給羅馬教會的書信中就有這樣的話說：「如果我們跟基督合而為一，經歷了他的死，我們同樣也要經歷他的復活。」（羅馬書六：）他又說：「如果我們跟基督同死，我們信，我們也要跟基督同活。」（羅馬書六：）使徒保羅一再強調：一個人若是信了耶穌基督，他就是與耶穌基督合而為一的人。

第四，堅忍的信心，必定得到上帝的獎賞。我們知道使徒保羅後來就是在羅馬皇帝尼祿掌權的時代殉教的。他那時代，基督徒開始面臨著極大的危機，只要被發現，就有可能被處死。因此，每當使徒保羅聽到有信徒離棄了信仰時，都會很難過。他就會在書信中一再勸勉信徒要有堅定的信心，上帝絕不會拋棄任何信靠祂的人。他引用了耶穌基督所講的話：「那在人面前認我的，我在我天父面前也要認他；那在人面前不認我的，我在天父面前也不認他。」（馬太福音十：—）同時他再次提醒提摩太，整本聖經的一個主軸信息：上帝乃是個信實的上帝（參考申命記七：９，以賽亞書四十九：，馬太福音廿三：，哥林多前書一：、哥林多後書一：，帖撒羅尼迦前書五：、）。

請注意，當聖經說上帝是「信實」的上帝時，這句話有三種意義：

其一指的是上帝永遠遵守祂與人所訂立的約。不論人是否繼續遵守這約，上帝永不改變這約（參考哥林多前書十：，帖撒羅尼迦後書三：，希伯來書十：）。

其二指的是上帝的愛永不改變。這種觀念在詩篇中一再出現（參考詩篇三十六：、八十九：、、、、九十二：２、九十八：、一○○：）。

其三指上帝的審判是公義的，而這公義是含有憐憫的意義在裏面（參考詩篇九十六：、一四三：１，以賽亞書十一：，約翰一書一：）。

*** 第十四至十九節：
你要提醒大家，在上帝面前鄭重地勸誡他們：不要在言詞上爭辯；那是毫無益處的，只會腐化聽的人。要努力在上帝面前作一個經得起考驗、問心無愧的工人，正確地講解真理的信息。要遠避荒唐無稽的空談，因為這一類的談話使人遠離上帝；他們所談的是像那腐蝕肌肉的毒瘡。這些人當中有舒米乃和腓理徒；他們離開了真理，竟說復活的事已成為過去，因而動搖了某些人的信心。可是，上帝所建立那鞏固的根基是不動搖的；在這基石上面刻著：「主認得屬他的人」，又刻著：「那自稱為屬主的人必須離棄邪惡。」

從第十四節開始，使徒保羅又開始告訴提摩太怎樣教導信徒，特別提醒他注意在教會中有些人傳達錯誤的信仰觀念，應該要禁止這種錯誤的信仰認知在教會內散佈出來，這是他寫信給提摩太時，開始就說明了寫此書信的主要目的，也是他要求提摩太繼續留在以弗所教會的主要原因（參考提摩太前書一：—）。

在這段經文當中，使徒保羅特別提起有兩個人就是在以弗所教會內傳播錯誤信仰認知的，這兩人的名字就是舒米乃和腓理徒。在前書第一章二十節，使徒保羅也曾提起兩個人，他們不但背離了信仰，而且更嚴重的，就是在信徒中傳不正確的信仰內涵，導致「毀謗上帝」，其中的一位就是舒米乃，另一位名叫亞歷山大。現在這裏又再提了一次舒米乃，原因很可能是他雖然已經被教會開除了，可是仍舊繼續在教會或是在信徒當中活動，這也就是使徒保羅要提摩太去禁止的原因。教會內若發現有人不聽從勸導傳播錯誤的信仰認知，就應該表明和這樣的人切斷關係，以免信徒繼續陷入信仰的錯誤中。另有一位名叫腓理徒的，他到底是誰？甚麼身份？很可惜並沒有更多的資料可供參考。

不過，我們從第十八節這句「竟說復活的事已成為過去」的話，可以明白他們受到當時「重智派」（Gnosticism）的影響甚深，認為耶穌基督並不是真正的人存活在世界上。因此，他在世上的時候，只是個「幻影」而已。人復活，並不包括肉體，而是只有靈魂復活，因為肉體是不好的、骯髒的、腐朽的，而靈魂是潔淨的。這樣的信仰認知並不正確，因為上帝創造人，並不是把人和靈魂分開的，上帝創造的人，是一個完整的生命，把肉體與靈魂分開，會使人成為一個不完整的人。何況福音書告訴我們，耶穌基督復活顯現給門徒們看到的時候，並不是只有靈魂出現，而是實質的肉體顯現在門徒面前，他與門徒一起吃喝，並且要存著懷疑之心的多馬用手去觸摸他被釘十字架的傷痕（參考約翰福音二十：—），這些都說明了一件基本的認識：復活，乃是生命的復活，而生命是包括了肉體與靈魂。

第十四節使徒保羅告訴提摩太，不要想在信仰上用辯論取勝，因為想要用辯論使人來信耶穌基督，那是很荒謬的想法。真正可以使人相信耶穌基督的，乃是因著基督徒付出的愛感動人的心才能得到（參考哥林多前書第十三章）。

第十五節可說是使徒保羅寫給提摩太書信中，最值得所有傳道者引用和記住在心的一節經文。在這節經文中，使徒保羅特別勸勉三件事：

一是：要經得起考驗。意思是指不要受到誘惑，這不僅是在福音信息的內容上，必須很清楚，不要被許多神蹟奇事的現象給迷惑，導致離開了聖經的教導。另一方面，也是在指生活上的誘惑甚多，這些都會造成對一個身為傳道者的誘惑，必須要有堅定的信心、有堅強的毅力，才能經得起考驗。其實，使徒保羅就是要提摩太在信仰和生活上都能嚴守紀律、知道節制，這是非常重要牧會生活的要求。

二是：要當個無愧的福音工人。這裏的「無愧」，意思就是沒有將自己的工作看成是一件羞恥的事。使徒保羅寫給羅馬教會的書信中，就曾說「我不以福音為恥」（參考羅馬書一：）。這句話在迫害的時代是非常有特殊意義的，因為會關係到生命的安危。即使在那樣危險的環境中，使徒保羅也是要求提摩太要堅持公開表明自己就是一個福音的工作者。如果傳福音的人，因為懼怕生命的危險，就把自己所擁有的傳道者身份隱藏起來，甚至認為是很羞恥的身份，這就已經失去了當傳道者的意義了。

三是：要正確地講解真理的信息。請注意這裏「正確地講解」之詞所用的希臘文，是由「直的」（horthos）和「切割」（temno）這兩個希臘字合併起來的。意思是開拓一條道路，要將阻礙的地方給予切開，例如穿越山嶺、山洞等，使之成為一條直的道路。另一方面，古時候的石匠，為了要取石材作桌面，就必須正確地切開石頭的面，使之成為筆直且平滑的切割面。這在羅馬帝國時代，用這兩個字在一起，大家就會知道指的就是要有很好的技術，將一條道路開拓得很順暢，或將一塊石頭切割得很好，且因為切割正確，而使切割後的石頭看起來非常美麗。使徒保羅告訴提摩太在解釋聖經上也要如此恰到好處，主要目的就是讓信徒能明白聖經的教訓，並進而喜歡閱讀聖經。

第十六至十八節，從這三節經文可以看到以弗所教會內部的真正問題所在，就是那些專門在傳講錯誤信息的人，對當時以弗所教會所造成的影響有多大。使徒保羅不僅說出舒米乃和腓理徒是在當時的信徒中傳播錯誤信息的人，且說出他們所傳講的，就是當時影響早期教會長達三個世紀之久的「重智派」觀念：耶穌基督沒有死，也沒有復活。就像我在前面已經說過的，此教派所傳講的內容，就是指著肉體是不好的，因此，人的復活只有靈魂，沒有肉體。這也就是為甚麼後來會有「使徒信經」這份影響後來基督教會發展甚大的信仰告白出現的主要原因，就是和這個「重智派」對信徒的影響有密切關係。

我們現今的教會所在使用的「使徒信經」，形成的時間很早，在第二世紀的初期就已經出現在教父手稿中，流行在當時的教會，且是當時任何一個信徒要進入教會信仰團契中，必定要會背誦的信仰內容之一。當時會出現這份信經，主要也是針對要接受洗禮者所提出的，在主後三四○年就通行於羅馬大公教會中所有的教會。在這份信仰告白中，最後一句話是我信「肉體的復活，永遠的生命」。請注意，這裏指的是「肉體復活」，而不是說「靈魂復活」。

但是，因為當時「重智派」的人影響力很大，導致許多信徒離開了原有的信仰，去接受「重智派」者的信仰觀念。如果我們翻開使徒保羅寫給哥林多教會的書信，就會發現他用很長的篇幅在介紹有關肉體復活的事（參考哥林多前書第十五章），也是為了「重智派」造成的影響的緣故。他就很清楚地提到：「死人復活也是這樣。身體埋葬後會朽壞；復活後是不朽壞的。被埋葬的是醜陋衰弱的；復活的是完美健壯的。被埋葬的是血肉的身體；復活的是屬靈的身體。」（哥林多前書十五：—）他強調一個重要的觀念：當天上的號角一響，所有的一切都會改變，那時候，原本朽壞的，都將因此變成不會朽壞的（參考哥林多前書十五：—）。

第十九節，這一節對基督教會來說很有意義。使徒保羅在這裏強調真正屬於基督的教會，其根基是來自上帝建造的，是不可能會動搖的。使徒保羅曾說耶穌基督就是教會「惟一的根基」，所有的基督徒就像是在這根基上建造房子一樣（參考哥林多前書三：ｂ—）。他也說耶穌基督就是信仰大家庭的「基石」，所有的信徒就是連結在這個大「基石」之上（參考以弗所書二：—），有這樣穩固的「基石」，就不會有動搖之慮。

其實，我們也可以了解，基督教會在經過了「重智派」的干擾之後，雖然對教會造成很大的影響，但這些以「重智派」建造起來的教會，卻在經過三百年之後消失了，主要原因就是沒有聖經的基礎。這幫助我們明白一件事：若是沒有堅強的聖經基礎，即使看起來很風光的成長之教會，也會在經過一段時日之後，就消失了。

*** 第二十至廿一節：
每一個大屋子裏都有許多器皿，不僅有金器、銀器，也有木器、瓦器；有的用在特別的場合，有的用在普通的場合。人如果自潔，脫離一切邪惡的事，就能夠被主所器重；因為他已獻給主，為主所重用，來做各樣善事。

第二十節再次讓我們看到使徒保羅言論的特色，就是將教會形容成為一間房子、大家庭、身體等，然後他說明房子的基礎，就是耶穌基督，信徒就是將房子建造在耶穌基督的基礎上（參考以弗所書二：）；耶穌基督就是這個信仰大家庭的主，大家都是上帝家裏的人（參考以弗所書二：）；也因為耶穌基督的緣故，所有的信徒都成為他肢體的一部份（參考哥林多前書十二：、，以弗所書四：—）。使徒保羅努力要提供一個信仰概念：在耶穌基督裏，不再分彼此，所有的信徒都是為了耶穌基督而來到教會之中。

第廿一節說到在教會服事的工作中，不是在分「特別」或「普通」，而是在於潔淨的心為主所用。使徒保羅這種觀念取自以色列人傳承下來的一個重要觀念：上帝是聖潔的，所以上帝的子民也必須是聖潔的（參考利未記十九：—）。以色列人用甚麼方式來表明「聖潔」這個意義呢？就是用獻祭。而使徒保羅則強調必須把自己當作像聖潔的祭品一般獻給上帝。他說：「所以，弟兄姊妹們，既然上帝這樣憐恤我們，我勸你們把自己當作活活的祭物獻給上帝，專心事奉他，蒙他喜悅。這就是你們應該獻上的真實敬拜。」（羅馬書十二：）這觀念在使徒保羅的書信中一直持續著，因此，他認為基督徒要獻給上帝最好的禮物，就是「更新」的生命（參考羅馬書十二：，哥林多後書五：—，以弗所書四：—）。

** 現在讓我們來想想看這段經文所帶來的信息：
*** 一、作個無愧於福音事工的僕人，乃是今天的教會和傳道者應該時刻注意的一件要事。

使徒保羅提醒提摩太，要他在上帝面前作個無愧於福音事工的僕人。他同時告訴提摩太要成為一個無愧的工人，其最基本的要件，就是從「正確地講解真理的信息」開始。看，這是多麼重要的提醒啊！

想想看，使徒保羅為甚麼要強調「正確地講解聖經」呢？原因就是在以弗所教會已經有人在傳那些不正確的信仰知識，說耶穌基督復活已是過去的事了。換句話說，有人在傳講沒有所謂復活這樣的信息，若是有，也只是靈魂復活，身體並不會復活。但這並不是聖經給我們的信息，聖經告訴我們的，是生命的復活。上帝既然以祂的形像創造人類，並且賜給人類有生命之氣，這就是無法消失的存在。因此，在基督教信仰中，我們說復活乃是整體的生命，並沒有分開靈魂與肉體。

對聖經有正確的了解，就不會受到誘惑，這一點是非常重要的認識。否則很容易因為不正確的講解聖經方式，使信仰偏離了聖經的基礎。我們應該有基本的認識：基督教會就是建造在聖經的基礎上。因此，在談基督教信仰時，就必須以聖經為本。如果沒有聖經的依據，所講的，也只是人的想法罷了。

這也就是為甚麼我來到咱教會後，一再鼓勵大家一起讀聖經，並且要按照進度來讀，也發給大家一份三年份的讀經表。來這裏已經有六年時間，我們將在明年六月完成新舊約聖經讀完兩遍。另一方面，我也帶大家研讀聖經、開查經班，也已經讀完了創世記、約伯記、馬可福音、路加福音、羅馬書等。現在帶大家查考啟示錄這本經書。在查經班時，我經常就是在提醒大家：在咱台灣經常有人在傳講不正確的信息，且有的人濫用聖經到了胡亂吹噓的現象。我一再提醒大家注意這些現象的原因，其實只有一個目的，就是希望大家正確地明白聖經，這樣才不至於被人利用，或被欺騙了而還不知道。

我最近接獲一份傳單，說是有一個人很偉大，且是偉大到自從耶穌基督當年在耶利哥曠野禁食四十晝夜之後，現在只有「某某恩」的這個牧師才有這樣寶貴經歷，說他也有經歷了禁食四十天的能力。這個人要在台灣各地開一所「超神學最高學府」。類似這樣的廣告，看起來很震撼人心，也很吸引人的耳目，如果沒有注意，還以為這個人多麼偉大，好像比舊約聖經的先知還要偉大的樣子。但想想看，一個人能禁食這麼久有甚麼意義？禁食的目的是為了甚麼？再者，如果我們有研讀聖經，就會知道耶穌基督曾告訴過我們的話。他說：

「你們禁食的時候，不可像偽善的人；他們裝出一副苦相，故意蓬頭垢面，好讓別人看出他們正在禁食。我告訴你們，他們這樣做已經得了所能得到的報償。你禁食的時候，要梳頭洗臉，不要讓別人看出你是在禁食，只讓那位在隱密中的天父知道；看得見你在隱密中做事的天父一定會獎賞你。」（馬太福音六：—）

這個「某某恩」的牧師既然讓人知道他禁食四十天，這樣的禁食就已經不需要上帝注意他的禁食了。因為禁食並不是要公開讓人知道的，且為甚麼要禁食？這一點也應該回到聖經中來，明白聖經中提供禁食的主要目的和用意。除非有相當特別，且是在聖靈的引導之下才進行禁食，而不是想到要禁食，就去禁食。如果我們有注意讀聖經，就會知道類似這種傳單所說的，根本就不足以讓我們去學習。

教會就是福音的僕人，因為教會的存在之目的，就是要傳福音，見證福音的。因此，一間教會的信仰內涵好與否，主要就是看該教會是否有在帶領信徒研讀聖經，帶領人來認識聖經上帝的話語。

一個傳道者，他獻身的使命就是要傳揚聖經的話語。因此，最基本要做的事，就是帶領信徒正確地認識聖經的信息。而傳道者若要正確地認識聖經信息，就必須對聖經下功夫研究，這一點是非常重要的事。因為信徒對聖經的認識，幾乎都是透過傳道者的協助得來的，傳道者若不用功，就很難幫助信徒在聖經的認識上進步。使徒保羅提醒提摩太牧養的工作必須從聖經著手，他的話也是在對今天之傳道者說的。

*** 二、我們都懷有各種不同的才能，但這些都是為了要讓我們成為福音的器皿，因此，必須從我們自己潔淨心靈開始做起。

每個人身上都有上帝所賞賜的不同恩典，這是我們經常聽到的一句話，也是使徒保羅告訴提摩太的話。他提醒提摩太在以弗所教會，要知道在教會中的信徒，都是來自各種不同階層的人，大家都是身懷上帝所賞賜的不同恩典。但我們必須注意一件事：這些恩典並不是用來炫耀自己的才華，或是只用來利益自己的需要，這不是賞賜給我們這些恩典的主要用意。使徒保羅告訴提摩太，說每個人恩典不一樣，就像許多器皿，雖然每個器皿都有它特殊的用途。

使徒保羅提到不同的材質；有的比較「特別」，有的比較「普通」。請注意，他是用「特別」和「普通」這樣對比的詞，這就很有趣了。通常會讓人使用次數最多的，應該是最普通的器皿，也因為這樣，這樣的器皿通常都不是最昂貴的材質做的。只有很少用到的東西，因為比較「特別」，所以，一般來說都是材質比較好的。但越「普通」，與人的關係就越密切；相對的，越「特別」，和人之間互動也就越少。

但不論是什麼材質，是「特別」或是「普通」，我們都因為耶穌基督的緣故才會聚集在同一間教會中，這是有一個共同的目的，就是為了要傳揚福音的緣故，這樣的認識是非常重要的。如果我們沒有這樣的認識，要在同一間教會中共同推動福音事工，那是很困難的。

我感到比較可惜的是，在咱台灣長老教會裏，有許多很好的人才，都擁有上帝所賞賜的美好恩典，但擁有這樣美好恩典的人，卻經常在教會事工中採取觀望的態度多，甚至有些人不但沒有參與服事，且還要讓其他的人來服事他。但我看到許多新興起的教會，教勢成長得很快，這樣的教會都有一個共同點：參與服事的信徒很多。他們都很願意放下自己原本被這個社會看為尊貴的身段，來參與教會事工，也因為這樣，反而帶領更多的人看到了受感動而加入了教會服事福音事工的行列，讓人感覺該教會很有活力，也因為這樣，加入的人越來越多，教會的成長相當快，這真的是我們應該要學習和反省的地方。

我曾一再告訴過大家，且告訴過長老們很多次，我只會帶領大家研讀聖經，其它有關怎樣組織信徒的事，這方面我確實甚麼都不會，你們要出來幫助我。我不是一個全能的牧師，更不是一個很有才華的傳道者，除了帶大家查經之外，我真的其它方面都很弱，需要大家一起來協助推動。我期盼大家不是告訴我說：啊，牧師，我們教會可以做甚麼，不是停留在這裏。因為停留在這裏，就是要我去做一樣。你可以告訴我說，我們教會可以改善那些、做哪些。然後我們一起來討論怎樣將這些美好的意見或願景給改善過來，或鋪陳出來，這樣才對。否則，你告訴我說，可以做甚麼。然後就等著我去做，結果必定是甚麼都沒有發生，因為我不會啊！除非你來參與才行。

教會若要成為一間真正在傳福音的教會，就必須所有的會友都動起來，大家把得自上帝的恩典提供出來。更重要的，就是懷著心甘情願的心一起來參與這些服事的工作，這一點是非常重要的。使徒保羅說，這樣的人所奉獻的，才會被上帝所器重。

（講於二○○三年十二月廿八日）



* 第三講：聖經是上帝所默示
作者: 盧俊義牧師  日期: 2011-03-03 17:10
經文：提摩太後書二：—三：

在第二章十四節至廿一節這段經文，使徒保羅提醒提摩太要教導以弗所教會信徒怎樣過教會生活，特別是對那些會導致信徒離棄信仰的異端邪說，要特別注意。不需要跟那些專門傳講這種謬論的人辯論，他甚至特別指名道姓的說出兩個導致信徒離棄信仰之道的人，就是舒米乃和腓理徒。這讓我們看到自從有教會這樣的信仰團契以來，內部就一再出現不同的聲音，而這些不同之聲音所造成的困擾，往往也是分裂教會的因素之一。

早期教會之所以會有這樣的困擾，主要原因是當時沒有像今天的教會有一本大家公認為權威的經典可作為依據。那時候唯一有的，就是猶太人的經典，也就是我們今天所謂的舊約聖經。因此，對耶穌基督所帶來新的信息，早期教會則是「傳說」甚多，作品也不少，但卻都是眾說紛紜，就像醫生路加所說的：「已經有好些人從事寫作，報導在我們當中所發生的事。他們的報導是根據那些從開始就親眼看見這些事，並且曾經傳佈這信息的人所敘述的。」（路加福音一：—）

這讓我們看到早期教會內有許多文書、信件都會談到有關耶穌基督的事，但誰說的比較正確？一般來說都會依據使徒們所寫的為準。可是，並不是每個使徒都會寫書信，這也是一件很遺憾的事。還好，後來有使徒保羅將基督教信仰做了個總整理，特別是他寫出了羅馬書這本被認為最重要的一本整理基督教信仰的經書，才使得基督教信仰有了個底子，這本「羅馬書」的經書也是影響基督教會相當深遠的一本經書。然後，我們看到每當使徒保羅用心在處理教會發生的問題時，因為無法親身去處理教會遇到的問題，包括信徒之間的紛爭，也有信仰上遇到的困擾等等，他大多是以書信回答當時教會所遇到的問題。誰也沒有想到，這些接近兩千年前回答問題所寫的書信，卻成為我們今天建構教會秩序時的基礎，這一點也是使徒保羅怎麼想也想不到的事。

因為使徒保羅在當時教會備受尊重，因此，他所提出的看法、意見、處理方式等，都成為教會處理問題的依據，因此，他的書信不僅流傳在一間教會，也會傳給鄰近的教會閱讀（參考歌羅西書四：），所以，當後來教父們在編輯新約聖經時，就會考慮到將使徒保羅的書信給編入聖經正典當中，成為信徒們閱讀的必要經書之一，主要目的就是要讓大家明白怎樣過教會這信仰團契的生活，以及應該有的信仰態度。

但我們都知道，使徒保羅雖然自己寫了對信仰的認知，甚至有很多次他就是在書信中作信仰告白，例如在前一講已經提過的提摩太後書第二章十一至十三節，可說就是使徒保羅的信仰告白一樣。這些信仰告白的內容都有相當清楚的聖經依據。而使徒保羅時代的聖經，就是舊約聖經。因為他的時代，新約聖經尚未成形，也還沒有進行編輯的工作。換句話說，舊約聖經還是成為當時基督徒最重要的信仰根據。因此，我們應該要有這樣的認識：基督教信仰的基礎，並不是只有新約聖經，舊約聖經和新約聖經的地位是同等重要，缺一不可。這也就是當使徒保羅寫信給提摩太時，一再提醒他要在聖經上下功夫，這樣才能夠「正確地講解真理的信息」（參考提摩太後書二：），以免教會內部因為對信仰的認識不夠，或是失去基礎而發生偏離的現象。

我們現在所讀的經文中，使徒保羅再次提到聖經的重要性，可以想像得到當時的教會內部，確實是信仰偏離正道的信徒不少。其實，我們今天經常聽到許多奇異的謬論，有的傳道者甚至自己扮演著「基督」的角色，迷惑信徒甚厲，就像目前發生在中國的「東方閃電」這個新興宗教一樣，雖然也是說聖經，但傳道者卻說自己就是「基督」，且說新約聖經時代的耶穌基督已經過去了，現在來的是「女基督」時代，這樣的荒腔走調、偏離聖經的基礎，這是值得我們注意的一件事。我們應該有這樣的認識：任何與聖經教訓相抵觸的信仰論調，就不是屬於基督教信仰的範圍。

** 現在讓我們來看看所讀經文的內容：
*** 第二章廿二至廿六節：
你不要像少年人意氣用事；要跟那些心地純潔、祈求主幫助的人一同追求正義、信心、愛心，與和平。要棄絕那種愚拙無知的辯論；你知道，這種辯論往往會引起爭吵。主的僕人不可爭吵；他應該和氣待人，殷勤善導，處處忍耐，用溫柔規勸敵對的人。也許上帝會給他們悔改的機會，使他們認識真理。這樣，雖然他們被魔鬼抓去，被迫順服了他，他們也會醒悟，從他的羅網中掙脫出來。

這裏使徒保羅再次提到提摩太是個「少年人」，在前書第四章十二節，使徒保羅就曾提醒提摩太：「別讓人小看你年輕。無論在言語、行為、愛心、信心，和純潔各方面，都要作信徒的榜樣。」現在則是要他不要「意氣用事」，這是指那些年輕人所比較容易呈現出來的「輕浮、虛榮、易怒、好辯論」等毛病，這些都是使一個人最容易失去理智判斷事務的現象。作為一個傳道者，必須在這方面盡可能避免。而相對於這些輕浮等事，則是要追求正義、信心、愛心、和平。這裏使徒保羅用的「追求」這個詞很特別，這原本是指如同一個人出去狩獵，看準了獵物，就盡所有力量一定要將獵物追到，唯恐稍微有疏忽而失去了獵物一樣。換句話說，使徒保羅希望提摩太要認真、用功到就像一個狩獵者在追捕獵物一般，認真在追求正義等這些信仰功課上。因為正義、信心、愛心、和平等這些都是在信仰團契中不可缺少的要素。

第廿三至廿四節可以參考第十四節，也是在強化第廿二節所提起的「少年人意氣用事」。我在前一講已經有說過，信仰並不是用辯論可以服人，信仰是透過真實愛的分享感化人的心而得到的，就像第廿五節所提到的，用「溫柔規勸敵對的人」。所謂「溫柔」，是指不傷害對方的尊嚴。這也是一種為對方著想，而不是只有為了自己的益處爭奪。

請注意，這裏提到「不可爭吵」，並不表示為了息事寧人而採取妥協的態度，不是這樣，而是不退讓，但有所堅持。就像「母親乳養兒女一般」（參考帖撒羅尼迦前書二：），是用生命的愛給予開導，希望對方明白真正的要理是甚麼。主要的目的，就是放在第廿六節，為的是期盼有一天，即使這些離開了教會的信徒因為走錯了路，也會迴轉過來，而不會覺得羞愧不敢回頭。這讓我們看到使徒保羅用心的，就是信仰的事，他並不希望因為有人誤入「歧途」，導致大家如同仇敵一般，他總是留給對方有個回頭的空間。這並不是用「沒關係」或是以「和稀泥」的態度隨便了事。信仰的事應該要有所堅持，對的，就是對；錯的，一定要指明出來。

*** 第三章一至九節：
你要知道，世界的末期會有種種苦難。那時候，人只顧自己，貪財，自誇，狂傲，毀謗，忤逆父母，忘恩負義，不聖潔，沒有親情，殘忍，散播謠言，蠻橫，凶暴，恨惡良善。他們出賣師友，任意妄為，狂妄自大，愛享樂過於愛上帝。他們披著宗教的外衣，卻拒絕宗教的實質。這一類的人，你們要躲避他們。他們當中有些人穿門入戶，到別人家裏去，迷惑意志薄弱、被罪過所壓制、被各種慾望所支配的婦女們。這些婦女雖然常常想要學習，卻無法認識真理。就像從前雅尼和洋布雷怎樣反對摩西，現在這些人照樣在反對真理。他們心思敗壞，在信仰上經不起考驗，再也發生不了甚麼作用；因為他們的愚昧會在眾人面前暴露無遺，正向雅尼和洋布雷一樣。

第一節又讓我們看到「世界的末期」這樣的詞句。聖經給我們一個觀念，就是每談到世界末了時，隨即跟著來臨的，就是上帝的審判。在使徒保羅的書信中，談到世界末了，就會與耶穌基督再臨的事連結在一起談論（參考羅馬書二：，哥林多前書四：、五：、十：，帖撒羅尼迦前書五：）。這讓我們看到，早期教會相信世界末日很快就會來到，而那時候，耶穌基督就會再臨，他再臨，就是要審判世界。在早期教會相信耶穌基督很快會再臨，可說是最重要的信仰告白之一，也因為這樣的信仰告白，他們忍受了來自猶太人和羅馬政府的嚴厲迫害，他們相信這個日子過不久會來到，當然這與使徒行傳第一章十至十一節記載耶穌基督升天時，有兩位穿著白衣的天使所傳出的「你們看見他怎樣升天，他也要怎樣回來」的信息有密切關係。而在約翰福音第十四章一至四節，耶穌基督也曾親口說出他去，但還要再來接信靠他的人到天上去，這對正受到迫害中的信徒來說，期盼耶穌基督再臨，可說是信仰中最大的支撐力，也是苦難生命中的一劑強心劑。

再者，使徒保羅在寫給提摩太的書信中，已經有提過一件事：「聖靈明明說了，在末後的時期，有些人會放棄信仰，去順從欺騙的靈和邪魔的道理。」（提摩太前書四：）這節經文已經說出一個事實：有人因為支撐不住，無法等到耶穌基督再臨，就已經放棄信仰了。而更嚴重的，就是在末世的日子裏，假先知甚多，這些人專門傳講一些不正確的信息，但卻很容易迷惑人的心，許多在那苦難的日子中失去了明辨真理的能力，跟隨了這些傳講假信息的人走。這種情形並不是只發生在新約聖經的時代，即使在今天的世代也是一再出現這樣的情景。就像今天在中國已經有一種自稱是「基督教」，傳講者卻自稱是「女基督」，這位自稱是「女基督」者就是說：過去的基督是男的，現在是個嶄新的時代，不再是男的，而是「女」的。這個信仰團體被稱之為「東方閃電」，在中國發展得很快，逼到中國基督教教會不得不公開宣告給信徒明白，「東方閃電」是個異端信仰團體，要信徒們不要跟隨這位自稱「女基督」者走。

再者，這裏也看到使徒保羅告訴提摩太，說在「世界的末期會有種種苦難」，這裏所提到的「苦難」，是指被魔鬼附身所帶來的折磨慘狀。像馬可福音第五章一至二十節所提到的、那位在格拉森出現被「大群」鬼附身的那個人一樣，那人已經不知道自己在幹甚麼，連睡在墓穴中、用石頭砸自己也不知道。因此，從這裏可以了解「苦難」的另一個意義，就是無法控制自己，就像「自我節制」一樣。明明知道不可以，卻一直陷下去。這樣，我們就可以明白使徒保羅所說的，這就是人的罪最典型表現的方式，也是人生命最大的軟弱與痛苦，因此他說：「我真苦啊！誰能救我脫離這使我死亡的身體呢？」（羅馬書七：）

另一方面，這裏的「苦難」還有另一個意思，就是指來自外在的攻擊、威脅，這也是初代教會一再會遇到的經歷，我們在使徒行傳中經常讀到每當使徒保羅和他的門徒在各地傳福音時，就會遇到猶太人設法製造動亂，想要造成羅馬政府有個錯誤的認識：基督徒就是社會的動亂者。這使我們想到主後六十五年左右，羅馬皇帝尼祿將羅馬城大火的事件，將之歸咎於基督徒，就可以想像得到那種罪狀會帶來的迫害有多嚴厲。

第二至六節，在這段經文中，使徒保羅一連串提到在世界末期的日子中，所出現各種令人難過的現象，在這裏他總共列舉了十九項不好的行為，我們可以將之歸類幾點：

一是自私，只顧自己。這是基督教信仰上最不能容許的一件事。使徒保羅寫信給腓立比教會時，特別提到我們要學習「以基督耶穌的心為心」，他說：「不要自私自利，不要貪圖虛名，要彼此謙讓，看別人比自己高明。不要只顧自己，也要關心別人的利益。」（腓立比書二：—）基督徒若是自私、只顧自己，就無法跟別人分享耶穌基督救贖的愛，這是非常清楚的。因為自私的人最容易表現在貪財的行為上。使徒保羅曾說「貪財是萬惡的根源」（參考提摩太前書六：）。因為這樣的人，不會去憐憫苦難者的需要。

二是自誇、狂傲，這兩個詞句經常是連結在一起使用的。所謂「自誇」，原來的意思是指沒有真才實力，卻誇口說很有能力。當時羅馬的社會有一種人，就是專門在江湖上四處賣藥的人，其實那是很普通的藥品，但賣藥的人卻會說得天花亂墜的，讓人以為他賣的藥可以治百病一樣的有效。這種就是「自誇」的意思。這在台灣社會也經常出現，我們稱之為「跑江湖、賣膏藥」的人。

「狂傲」，這是比「自誇」還要嚴重的毛病。這個詞的原來意思，是指一個人站在很高的地方，誇口自己的才能有多少。換句話說，在他的眼中根本就沒有任何其他的人可以跟他共比高，因為他就站在最高點在講話。因此，詩篇的作者說這種人的心中不會有上帝（參考詩篇十四：）。而更嚴重的是，這種人往往會把自己當作是上帝一樣，以自己為中心。

三是「忤逆父母，忘恩負義」、「沒有親情」，這三個詞句都有共通的意思。父母可說是子女最大的恩人，而會忤逆父母的人，基本上就是忘恩負義的人。忘恩負義，也是指對上帝恩典的藐視，因為父母乃是上帝給人最好的禮物。摩西法律中甚至明白規定，侮辱父母的人，可以處以死刑（參考申命記廿一：—、廿七：）。而「沒有親情」，指的就是對家族同胞的愛喪失了的人。

四是不聖潔、恨惡良善，這是指懷有壞的念頭，對人存心不良，這樣的人很容易產生不好的計謀去陷害別人。這種人其實就像狂傲的人一樣，他們的心中不會有上帝，因為不相信有上帝，才會有不良的計謀想要陷害別人。而「恨惡良善」則是與嫉妒有關。看到別人有好的行為或表現時，會充滿嫉妒的心，進而會設計陷害對方。

五是殘忍、凶暴，這是對苦難的生命沒有憐憫之心的意思。特別是在那迫害的時代，對那些被抓去關在監獄中的人，還存著幸災樂禍的態度，這種人就是殘忍、凶暴。

六是散播謠言、蠻橫，這是指一個人亂說話，故意編造虛假的故事，為的是要羞辱別人，這樣的行為很容易引起爭端。散播謠言就像違背十誡的第九誡一樣，都是存心不良的行為。而「蠻橫」則是對自己的約束不夠，沒有自制的能力，容易與別人起衝突。也就是不願意尋求與別人和好，只想要欺負別人。

七是出賣師友，這是指昧著良心說不誠實的話，或是做傷害朋友、師長的事。這已經是沒有道義可言，就像猶大出賣耶穌基督一樣。在早期教會也發生有些信徒為了自保，將其他信徒的名單提供給正在設法要逮捕的迫害者羅馬政府，使他們受到殘酷的迫害。

八是愛享樂過於愛上帝，這就像路加福音第十六章十九至三十一節耶穌基督比喻中的那位財主一樣，他可以天天奢華宴樂，卻沒有時間敬拜上帝。其實，這樣的人在心中根本就是藐視上帝的神聖和偉大。

九是假冒有信仰的人，但並不是真的如此，這種人也是使徒保羅經常指出的「假使徒」，不僅發生在哥林多教會（參考哥林多後書十一：），也發生在加拉太教會中（參考加拉太書一：），在以弗所教會中也出現這樣的人（參考提摩太前書一：—、四：—）。

我將這共計十九種發生在一個動亂不安的世代中，經常會出現在一般人、甚至信徒當中的現象，歸類成為八種，今天的時代我們隨時都會發現這些也是一直發生在生活的四周，這就是為甚麼有人會說，今天的時代好像是世界末日來到一樣。

第七節，使徒保羅特別提到這些假教師最喜歡使用的伎倆就是到處串門子，去誘惑婦女離棄真道。使徒保羅寫給提摩太的第一封書信中，也特別提醒提摩太注意那些年輕且守寡的婦女，要教導她們不要到處串門子，講些有的沒有的話，害教會紛爭更多（參考提摩太前書五：—）。現在他再次提起有些婦女比較容易受到那些能言善道的假教師誘惑，因此，要提摩太特別注意婦女行動。有時看起來她們是想要學習更多，但往往尚未學成認識真道，卻已經受到迷惑。

在第八至九節這裏使徒保羅特別提起兩個專門在欺騙婦女信徒的名字——雅尼和洋布雷。這兩人到底是誰？除了這裏出現之外，聖經中都沒有他們兩人的資料。但在猶太人的傳說中，說這兩人就是埃及法老王身邊的「術士」，曾被指派來抵擋摩西能力的人（參考出埃及記七：—、九：）。早期教會的信徒對摩西所行的神蹟，以及他帶領以色列人出埃及的故事相當熟悉，因此，使徒保羅將雅尼和洋布雷的行為，比喻在法老王身邊用來抵擋摩西的術士，為的是讓當時的信徒知道，反對聖經的教訓，就等於那些術士一樣，到最後受到傷害的，就是他們自己而已。

*** 第十至十三節：
但是，你已經跟隨了我的教導和人生觀，仿效了我的行為、信心、寬容、愛心、忍耐，並分擔了我所受的迫害和痛苦。我在安提阿、以哥念、路司得這些地方所遭遇、所忍受的迫害，你都知道；但是，主救我脫離了這一切。凡是立志跟從基督耶穌、過敬虔生活的人，都會遭受迫害。邪惡的人和騙子們也會一天比一天壞；他們欺騙別人，自己也被欺騙了。

這段經文剛好和前一段經文所提起的完全相反；在前一段提到末世的時代，人心墮落和惡劣的景況，這一段則是提醒提摩太要謹守從自己信仰的父親——使徒保羅——所領受的教導謹記在心。使徒保羅對提摩太有著相當的期待，也因此，他期盼提摩太確實會和一般人不同，他對提摩太要求會比較嚴格。

在第十節，使徒保羅特別指出他教導給提摩太的，是有正確的人生觀，以及很好的生活態度，不但有好的行為，也有信心、寬容、愛心、忍耐。這五項其實都可以在使徒保羅傳福音的過程中看的出來。

請注意這裏提到的「跟隨」這個詞，是表示「很詳細」的意思。這是指提摩太跟隨使徒保羅四處去傳福音，對使徒保羅的所行所為都很清楚。這也是在第十一節提起在安提阿（這是指彼西底的安提阿，參考使徒行傳十三：）、以哥念（參考使徒行傳十四：）、路司得（參考使徒行傳十四：）等地遇到迫害的經驗，使徒保羅都用極大的容忍之心給承受了下來。這些受到迫害的經歷，都是提摩太相當清楚的事。而這些迫害的事實也說明了使徒保羅是一個有好行為和信心、愛心的傳道者，否則跟隨他身邊的人一定會趁隙離他而去。沒有人會跟隨一個行為不檢點、缺乏愛心的傳道者，自古以來就是這樣。

第十二節，這是一節很有意思的經文，對早期的基督徒來說，這句話確實具有相當的震撼力，因為說出了基督教信仰真實的意義，並不是在尋求物質生活上的大富大貴，也不是在尋求生命的安全，剛好相反，因為信耶穌基督是與永恆的生命有密切關係，而這永恆的生命必須與敬虔的生活有關，這對當時在羅馬帝國統治之下，特別是在以弗所城來說，因為敬拜女神亞底米而造成淫亂行為甚厲的生活，成為極大的對比，因此，使徒保羅這句話確實很令當時以弗所的信徒很大的震撼。我們看到使徒保羅並不是只在講究信徒數多就好，他更是要求信仰必須和生活相連結在一起，但對一個淫亂成性的都會生活的人來說，過敬虔生活的人反而會被人認為是「異端」、「有問題」，可能因此就遭遇到親朋好友孤立，甚至拒絕來往，嚴重的還會被排斥、受到壓迫。

第十三節，「他們欺騙別人，自己也被欺騙」這句話，可說是針對那些假使徒說的，也就是那些將福音當作商品用來欺騙別人的人，到最後一定會露出他們欺騙的伎倆而遭到眾人的唾棄。事實上也是這樣，在台灣這種宗教騙子都不會生存太久，因為大家很快就會看到他們的真面目。

*** 第十四至十七節：
至於你，你要持守你所接受和確信的真理。你曉得誰是你的導師；你也記得你從小就明白聖經，就是能給你智慧、指引你藉著信基督耶穌而獲得拯救的那本書。全部聖經是受上帝靈感而寫的，對於教導真理，指責謬誤，糾正過錯，指示人生正路，都有益處，要使事奉上帝的人得到充分的準備，能做各種善事。

這段經文再次讓我們看到使徒保羅對聖經的重視。在後書第二章十五節，使徒保羅曾勸提摩太要「正確地講解真理的信息」，現在則是再次提起聖經的重要性。耶穌基督在講到財主與乞丐拉撒路的比喻中，就特別提起亞伯拉罕拒絕了那位死後被下到陰間受苦的財主的懇求，說：「你的兄弟有摩西和先知們去警告他們，讓你的兄弟去聽他們吧！」然後又說：「如果他們不聽摩西和先們的話，即使有人從死裏復活，他們也不會相信的！」（路加福音十六：、）請注意耶穌基督在這裏所提到的「摩西和先知的話」，指的就是舊約聖經。摩西代表著律法書，先知代表著聖經中所有先知的作品。一般來說舊約就是用這兩大部分構成的。

第一世紀的時代之聖經，就是舊約聖經。使徒保羅在這裏提醒提摩太，一定要重視聖經。因為提摩太的母親是猶太人，父親是希臘人。猶太人的家庭教育就是母親在擔當的主要使命，每個小孩子在六歲之前就會背誦十誡，在八歲以前會背誦出埃及記、默寫十誡，然後在十歲之前，必須會背誦出埃及記和申命記、默寫出埃及記，在十二歲以前，也就是國民小學畢業要進入初中之前，必須會背誦摩西五經，並且會默寫出埃及記和申命記。因此，對提摩太來說，他就是在母親教導之下，從小就開始學習認識聖經，這和咱台灣基督長老教會在一九六○年代以前，幾乎所有的教會都在禮拜天和暑假期間教導所有主日學小朋友學習認識聖經，有相同之處。可惜這樣的情景已經不復存在了。

使徒保羅說聖經能給人有「智慧」，以及指引「信耶穌而獲得拯救」。聖經告訴我們所謂「智慧」，是指認識上帝（參考箴言九：）。而整本聖經就是在告訴我們，上帝怎樣藉著耶穌基督來拯救人類。

第十六節是很重要的一節，也是經常有人提起討論的一節經文。要特別注意的是，在使徒保羅寫這本書信之時，那時候的聖經只有舊約。因此，當這裏說「全部聖經」，其實就是指舊約聖經說的。但我們今天的認識是包含了新約，而且我們也寧願這樣接受。

再者，使徒保羅在這裏說全部聖經都是「受上帝靈感而寫的」，這句話是指聖經並不是人想到要寫一本經典，就寫得出來。其實沒有一位作者想到自己在感動之下寫出來的書，後來會成為教會使用的聖經正典，這就像使徒保羅或是路加，他們一定沒有想到所寫的書信，或是福音書、教會歷史記錄，會成為今天的聖經正典。他們主要目的只有一點：就是將聖靈感動他們的話寫出來，將他們所知道的事告訴當時的信徒。我們可以這樣了解：全部新舊約聖經六十六卷的作者，都有一個共同目的，就是要讓讀者知道上帝的愛和拯救。他們將自己的信仰告白和對上帝的認識寫出來，當作教導或是反省的教材之用。

因為有上帝聖靈感動人的心，因此，這本聖經就成為基督教會共同的準則，可以讓有紛爭的教會明白甚麼是正確的？甚麼是錯誤的？若是沒有聖經，教會就會很容易陷入人為標準的危險。第十四至十五世紀的基督教會就是有這樣的危險，才會引起馬丁路德進行宗教改革，並且喊出「聖經乃是教會最高權威」。而約翰‧加爾文則強調「教會乃是建立在聖經的基礎上」。

第十七節，這裏使徒保羅說明白聖經的人，就會成為上帝所喜悅的僕人。換句話說，要成為一個傳福音的僕人，必須在聖經的教導上有明確認識，否則就無法成就上帝拯救的工作。這樣看來，沒有好好準備聖經的教導，就不會是上帝福音的好同工。

** 現在讓我們來想想所讀經文帶來的信息：
*** 一、用聖經的教導建造我們教會信仰的根基，才是我們永遠存在的力量。
使徒保羅一再告訴提摩太一定要正確明白聖經，並且「正確地講解真理的信息」，這樣才能幫助信徒們知道甚麼是謬誤、過錯，才會清楚明白真正的信仰內涵。使徒保羅對提摩太所說的這些話，其實也是在對今天的教會和傳道者所講的。身為一個傳道者，最重要的功課，就是要把聖經弄清楚，這樣才能「正確地講解真理的信息」。他告訴提摩太說「全部聖經都是受上帝靈感而寫的」，這一點也是基督教信仰所告白的，相信聖經就是上帝的話。而上帝的話就是真理；這真理是永恆的，在述說上帝奇妙的救恩與愛。

我相當感佩的一件事，就是在台灣的「聚會所」，他們解釋聖經的方式我並不是很同意，但是他們要求所有的信徒都必須認真讀聖經，這一點就讓我佩服到無話可說，他們幾乎將讀聖經成為該教會一個特別的記號。該信仰團契的另一個特色，就是祈禱。而這兩點剛好是這最近四十年來，咱台灣基督長老最大的弱點，很值得我們反省。

我最近也看到一份研究報告，這份報告指出這十年來，咱台灣基督長老教會流失的信徒已經超過一萬多名，流失到哪裏去？我想就是到其它教派去，要不，就是失去了信仰、改信其它宗教去了。為甚麼會這樣？我可以想像得到的，就是今天的教會已經失去了聖經上帝的話語之基礎導致的結果，這只要看一看今天的教會就知道，因為真正在推動信徒讀聖經的教會實在是太少。

但最令我感到相當興奮的一件事，就是最近有一位姊妹，每個禮拜三上午特地從員林搭車到咱教會來參加查經班，風雨無阻。這位姊妹在去年（二○○三）十二月十五日下午，特地從員林將家裏的佛像、佛經、匾額等親自帶來教會請我替她處理掉。那是製造非常精緻的佛像，以及印刷品質相當高級的佛經。她是來參加查經班學習認識到基督教信仰的真諦。如果你問我：為甚麼要跑這麼遠來參加查經班？這個問題我也不知道要怎樣回答？只能問她，和問上帝。因為她的生命已經遇到了上帝，上帝讓她從聖經中聽到祂在叫她的聲音。這就像使徒保羅所說的：「全部聖經是受上帝靈感而寫的。」我們深信聖靈在每個人的生命中呼喊著，一直在對人的心靈講話。也因為這位姊妹這麼殷勤參加查經班，我想起了聖經學者巴克萊（William Barclay）所說的一句話：「一個沒有查經班的教會，就是失去了不可替代的基本工作的教會。」這句話已經清楚說明了一點：查經班，才是幫助信徒真確明白聖經話語的途徑。

怎樣明白上帝的話語，且會將研讀聖經上帝的話語當作生活中最重要的一部份？這是一門很重要的功課，也是所有基督教會與傳道者要認真省思的一件事。因為一間教會若是沒有聖經上帝的話作為基礎，不論該教會的規模多大，只要我們的環境一變遷，該教會很快就會受到衝擊和影響而改變。設若教會想要屹立不搖，就必須有上帝的話作為基礎，這一點是我們要切記的信仰認知。

*** 二、生命中會有許多苦難，但我們因為信靠耶穌基督的救恩而勝過苦難。
就在監獄中，使徒保羅寫這封信給他最信任的得意門生提摩太時，很清楚地告訴他說：「你要知道，世界的末期會有種種苦難。」然後描述在那苦難的環境中，會有許多讓人聽到、想到、看到就會感到相當難過的事頻頻而來，這些難過的事，包括了對父母的忤逆、忘恩負義，以及出賣師友等等共計多達十九項。如果我們將使徒保羅所描述的這些發生在人身上問題剖開來看，就會發現不僅發生在他的時代，也是發生在我們這個時代。也因為這樣，我們經常會聽到有人說這個時代，很像是個世界末日的時代一樣。

生命中會有許多苦難，這也是耶穌基督在最後晚餐中對門徒們所說的話，他說：「在世上，你們有苦難；但是你們要勇敢，我已經勝過了世界！」（約翰福音十六：ｂ）這也是我一再提醒過大家的，基督教信仰並不是保平安、大賺錢的，基督教信仰反而是讓我們更清楚：生命中會有苦難。但我們因為信耶穌基督而獲得生命真實的力量，會勝過生命中的苦難。甚至會讓我們有足夠的勇氣面對生命苦難來臨。

我的好友陳南州牧師，當他兒子在幼小的時候因為得小兒麻痺症，他夫婦兩人四處尋找所有可能醫治的醫師、處方，但都遍尋不著時，非常痛苦。有一天我讀到牧師娘杜靜枝姊寫在「新使者」的一篇文中這樣說：「上帝知道我有能力可以接受這樣的重擔。」我讀到這句話受到很大的鼓勵，也感受到一股極大的生命力在靜枝姊的身上。她確實將這樣的重擔承受了下來，一直到她過世的時候，她沒有為這件生命中最痛苦的事多說甚麼，她深知上帝已經給她足夠的力量，使她能夠承受這種生命的苦難。

沒有人能夠說信耶穌基督，生命中不會有任何不安或苦難的事發生，沒有！因為這不是聖經的教訓，連耶穌基督也告訴他的門徒，說「在這世上，你們有苦難」。但我們要知道，苦難並不是生命的終點，也不是生命的羅網，因為耶穌基督告訴我們，他要我們「勇敢」，因為他已經「勝過了世界」，沒錯，耶穌基督已經勝過了這個苦難的世界，他復活了！他就是要讓信靠他的人也跟著他一起復活。

就是因為耶穌基督的復活，使我們的生命從苦難中產生希望，也從希望中看到生命的亮光。因此，基督教信仰並不是要告訴我們要怎樣逃避生命的苦難，而是要告訴我們怎樣勇敢去面對生命的苦難，並且彼此鼓勵，好讓我們能學習耶穌基督勝過這世界的苦難，這樣才對。

也是從這裏，我們要明白重要的一點：每當我們聽到國家有危險來臨時，我們並不是要想辦法逃避離開它去，而是要學習更堅定的信心，仰望上帝的帶領，學習耶穌基督的精神，讓我們因此得到更多的力量，承受所要面臨的生命苦難。只有這樣，我們才能向那些無法逃避苦難而必須接受苦難臨身的人說：我們與你們一起承受苦難，但我們已經勝過苦難，你們也可以像我們一樣，因著耶穌基督勝過苦難！這才是我們要見證的福音。

（講於二○○四年元月四日）




* 第四講：盡忠職守
作者: 盧俊義牧師  日期: 2011-03-03 17:10
經文：提摩太後書四：—

讀提摩太後書第四章，就好像看到使徒保羅在寫告別書一樣，根據教會的傳統說法，認為使徒保羅寫完提摩太後書之後不久，就被處以死刑。他因為具有羅馬公民的身份（參考使徒行傳廿二：—），因此，沒有釘死在十字架上，也沒有被丟進野獸競技場，而是被斬首示眾，在羅馬政府看來，這樣對待殖民區的人民已經是相當「人道」的了。

由於這是使徒保羅最後所說的話，因此也可以從這裏看出使徒保羅對提摩太的愛和鼓勵，就真的如同他在前書與後書的第一章開場白所說的，將提摩太看成是自己信仰上的「真兒子」。就是因為把提摩太當成是「真兒子」看待，因此，每當談到有關教會牧養工作時，使徒保羅幾乎就是說盡了一個傳道者應該有的傳道使命之態度。他沒有任何隱瞞或是存留甚麼秘方，可說是傾囊而出地將所有他想要說的話告訴提摩太，並且深深地對提摩太有一份很大的期盼，也因此，他幾乎就是毫無任何保留地將他自己獻身傳道的使命和對傳福音的看法讓提摩太知道，這對提摩太來說，是非常有幫助，也是學習的重要功課。

作為一個傳道者，應該就要像使徒保羅這樣，傾盡所有的力量，為福音打最美好的仗，也只有這樣，才能使福音成為生命的中心。如果一個傳道者，第一個想到的是自己利益的話，這樣就談不上所謂獻身的使命感，也說不上盡忠職守，獻身當傳道者，或是成為基督的教會，都應該有這樣的認識才對。

我很清楚記得，有一次有一間教會準備聘請一位傳道者去協助牧會的工作，這位傳道者知道我和該教會信徒、長執都很熟悉，於是來問我如果他去該教會協助牧會的事工，應該用甚麼態度？我告訴他：「盡你所有的能力就對了。」這位傳道者跟我說：「可是有某一位牧師告訴他，要他保留幾分。」我聽了之後覺得很好笑。就告訴這位年輕的傳道者：「上帝這樣愛我們，連祂的獨生子耶穌基督都毫無保留地賞賜給我們了，我們還有甚麼好保留幾分的？」我問這位來問我的年輕傳道者：「傳福音可以保留嗎？真正的福音有秘方可隱藏嗎？」我告訴他說：「若是真正的福音，就沒有秘密可言，上帝的話就是要公開宣揚出來的，沒有傳出去，就有災禍！」這也是使徒保羅所說的一句話（參考哥林多前書九：）。

於是這位年輕的傳道者接受了我的意見，他那時原本在學生中心工作，利用禮拜六和禮拜日學生沒有聚會活動的時間，到那間教會很用心地協助牧養的工作，經過一年之後，該教會在他學生工作告一段落之後，決定聘請他當該教會的專任牧者，並且給予許多工作上的支持，也因為這樣，他在該教會除了牧會之外，也帶領該教會關心學生工作。

我曾提過使徒保羅書信中最喜歡用的資料，就是用羅馬軍隊出征去打仗時，那種雄赳赳、氣昂昂的精神，因為信仰所面對的敵人乃是屬於靈界的邪惡者。另一方面，他也喜歡用羅馬競技場上那種賽跑者認真的樣式，當作他勸勉信徒的教材，希望所有的信徒都會像正在競技場上的競賽者一樣，想要贏得那最終點的冠冕，因為那是極大的榮耀。

另一方面，我們也看到使徒保羅每當談到信仰的問題時，就會提到辨別真實信仰的重要性，信徒若是沒有注意信仰的內涵，就容易被那些經常借用耶穌基督的名進行欺騙行為的人所得逞，不但導致信徒誤入信仰的歧途，也會造成教會的紛亂，嚴重的話還會造成教會分裂。例如他寫給加拉太教會的書信中，就特別提到有人在「傳另一種福音」，他說根本就沒有「另一種福音」可言，那是錯誤的信息，和福音根本沒有關係（參考加拉太書一：—）。

不僅在加拉太教會有這樣的問題，在哥林多教會也出現有專門在欺騙教會的人，這些人能言善道，且很會標榜自己的能力，使徒保羅知道後非常生氣，諷刺地說這種人是「超等使徒」（參考哥林多後書十二：），並不是真正的福音工作者，因為真正的使徒會揚傳耶穌基督受難於十字架，以及他復活的信息（參考哥林多前書二：），而不是在述說自己的能力有多大，因為所有的能力，即使有醫病趕鬼的能力，也是為了要見證福音的緣故（參考羅馬書十五：—）。除了哥林多、加拉太等教會，其它的教會也都發生類似有人滲透到教會裏面，為的就是要欺騙信徒跟隨他們，而不是遵行聖經的教訓，也因為這樣，使徒保羅一再呼籲提摩太，在以弗所教會牧會工作中，就是要教導信徒認識聖經的教訓，並且要「正確地講解真理的信息」來幫助信徒辨明真正的信仰內容，他強調這是作為一個「問心無愧」的福音工人最基本該有的態度（參考提摩太後書二：）。

也因此，使徒保羅很不喜歡那些在傳道事工上脫隊的同工，尤其是在教會中造成困擾與糾紛的人，他最不高興。可是他都有保留機會給這些人，希望能讓這些信徒再次回到教會團契，就像我們現在所讀的經文中提到約翰‧馬可，他原本脫離使徒保羅同工行列，後來再次回來，且成為使徒保羅的好同工。可是，對那些行徑很惡劣的同工，就不是這樣了，他會指名道姓，說出這些離經叛道的人的名字。使徒保羅寫給提摩太的書信中，我們已經看到他提到幾個離開教會信仰團契者的名字，他特別提到「舒米乃和亞歷山大」（提摩太前書一：）、「腓吉路和黑摩其尼」（參考提摩太後書一：）、「腓理徒」（參考提摩太後書二：）、「雅尼和洋布雷」（參考提摩太後書三：、）、「底馬」（提摩太後書四：）、「銅匠亞歷山大」（提摩太後書四：）等，這通常不是使徒保羅的習慣做法，因為他喜歡將那些對福音有貢獻的人提出來，為的是希望大家能學習那些人，現在之所以會將這些成為信仰絆腳石的人寫出來，實在是讓他看不下去了，且是若不清楚將這些人的名字寫出來，可能會讓更多信徒離開了真確的信仰，因為在整個亞細亞省的人離棄信仰的人必定不少，才逼得使徒保羅必須採取這樣強烈的手段來防範（參考提摩太後書一：）。

因此，辨別真確的信仰內涵，對一個信徒來說是很重要的信仰功課，而對一個傳道者來說，則是他在傳福音事工時，特別是在牧養工作上，需要經常注意的一件事。

** 現在讓我們來看所讀這段經文的內容：
*** 第一至五節：
在上帝和那位要審判所有活人死人的基督耶穌面前，憑著他的顯現和他的主權，我迫切地勸告你：要傳福音，不管時機理想不理想都要傳，用最大的耐心勸勉，督責，鼓勵，教導。時候將到，那時人要拒絕健全的教義，隨從自己的慾望，到處拜人為師，好來滿足他們發癢的耳朵。他們掩耳不聽真理的話，卻傾向荒唐的傳說。至於你，無論在任何情況下都要謹慎；要忍受苦難，做傳道人應做的工作，忠心履行你事奉的職務。

在第一節一開始，使徒保羅就談到對人的生命有審判主權的，就是上帝和耶穌基督，我們不要小看這句話的重要性，因為這句話也是在否定羅馬政府對人生命的主宰權。使徒保羅當時是被關在監獄中，當他這樣寫的時候，等於在告訴羅馬政府，他不承認羅馬政府對他有生命的判決權，這種權柄只有創造生命的上帝，和為了救贖人的生命而犧牲在十字架上的耶穌基督才擁有而已，不是世上任何一個人所擁有的政治權柄和勢力。其實，我們如果從耶穌基督所說的話來認識，也會清楚使徒保羅所說的這句話是有原因的，耶穌基督說：
「朋友們，我告訴你們，那只能殺害肉體，卻不能進一步傷害你們的，不用害怕。我要指示你們該怕的是誰：你們要怕那位奪走人的生命以後，又有權把他投入地獄的上帝。是的，我告訴你們，應該懼怕的就是他！」（路加福音十二：—）

耶穌基督這句話已經清楚在說明生命的主權是在上帝，人並沒有這樣的權柄。人所能做的，只能對人的身體進行迫害；但真正主宰著人的得救與否之權，那才是最重要的，而這權柄卻是在上帝和復活的耶穌基督身上。

再者，這句「審判所有活人死人的基督耶穌」，可說是早期教會最重要的信仰告白內容。這句話也就是在回應當時羅馬政府對基督徒的迫害，基督徒要表明並不害怕這樣的迫害，因為真正的審判者就是復活的耶穌基督，他的審判是連活人、死人都包含在內。我相信這句話對我們是一點也不陌生，因為在使徒信經中就有提到復活的耶穌基督要來「審判活人與死人」這句話。

第二節對傳道者來說，或是對今天的基督教會都是具有非常大的意義，因為傳福音乃是教會存在的最重要使命，也是基督徒應該有的責任。而我們知道這裏所說的福音，指的就是耶穌基督拯救的信息。使徒保羅告訴提摩太不論在甚麼情況下，都要傳福音，因為福音是和生命的得救與否有密切關係。不是喜歡的時候才要傳福音，也不是遇到挫折或是困境時，就對福音事工採取懈怠或是放棄的態度。

使徒保羅在這裏提到幾個牧養工作的重點：
一是要耐心勸勉。這讓我們看出，牧養工作並不是一件易事，有些信徒並不是很甘願或是容易接受真理的教導，這就必須多用些時間，特別是在這裏提到要「耐心」，所謂的「耐心」，是指不妥協，但原則很清楚之意。並不是為了討好信徒，怕信徒離棄信仰就採取睜一隻眼、閉一隻眼的態度，不是這樣。而是要一而再、再而三的給予鼓勵之意。

二是督責，意思是指知道錯誤時，沒有將之當作沒有發生，而是會清楚地讓信徒知道，錯誤在甚麼地方。

三是教導。使徒保羅所使用的詞是積極式的，意思就是不放棄任何可以掌握的機會，要在信仰的事上用心，讓信徒明白甚麼才是正確的信仰。

第三至四節讓我們看到人性在信仰上的共同點，就是指想要滿足慾望的需要，並不是真在追求對真理的認識。這兩節也同時指出真假使徒的差異，就像舊約先知耶利米時代的假先知一樣，經常說出當時的人喜歡聽的話，但那些卻不是上帝要他們去說的，而是那些假先知自己所想的，不是來自上帝的啟示，要不然就是假冒上帝的名說虛假的信息（參考耶利米書十四：—）。真正的先知就像先知米該雅所下的定義說的：「我指著永生的上主發誓，上主對我說甚麼，我就說甚麼。」（參考列王紀上廿二：）同樣的，身為一個福音的傳播者，他主要的使命就是見證上帝在耶穌基督身上的救恩，不是要彰顯自己的能力；他的主要責任就是在為福音作見證，而不是為了要討好信徒而講好聽的話。

第五節，這裏使徒保羅提到身為傳道者應該有的三點基本態度：

一是要謹慎。這是指要保持頭腦清醒之意。為甚麼傳道者需要頭腦清醒呢？很簡單，只有這樣才能避免受到誘惑。還有，當一個傳道者頭腦清醒的時候，他就會知道教會或是信徒的問題在哪裏。

二是忍受苦難。傳福音的工作一定不會很輕鬆，特別是在一個迫害的時代，傳福音甚至是會有生命的危險。因此，使徒保羅要提摩太有這樣的心理準備。雖然這個時代在咱台灣已經沒有類似使徒保羅時代這種政治迫害的問題，但這並不表示就沒有苦難，因為苦難不僅僅限在政治性的層面，比這更嚴酷的，恐怕就是來自教會內部信徒之間的爭鬥、分裂，以及不應該有的誤解。

三是忠心履行事奉的職務。這句話可以對照第二節所提到的「不管時機理想不理想都要傳」。但請注意，這並不是說非要在哪一間教會牧會多久才是在履行事奉的職務，我經常告訴那些因為與教會之間有發生糾紛的傳道者說，傳福音並不是被限制在教會，在教會是在牧會，真正可以讓一個傳道者放手去傳福音的地方，是在教會以外的地方，那是一個廣大的社會空間。傳道者就應該像耶穌基督告訴他的門徒所說的：「無論到甚麼地方，如果當地的人不接待你們，也不聽你們的話，你們就離開那地方，把腳上的塵土也跺掉，表示對他們的警告。」（馬可福音六：）使徒保羅就曾用這種態度回應彼西底的安提阿人，以及哥林多城人對福音的冷漠（參考使徒行傳十三：—、十八：）。沒錯，傳道者要盡責任在傳福音的事工，不論所遇到的境況是甚麼，都不要放棄傳福音的使命和責任。

*** 第六至八節：
至於我，我犧牲自己的時候到了；現在就是我離開人世的時刻。那值得競爭的賽跑，我已經跑過；該跑的全程，我已經跑完；該守的信仰，我已經守住。從今以後，有公義的華冠等著我，就是那以公義施行審判的主在基督再來的日子要賜給我的，不但賜給我，也要賜給所有愛慕他顯現的人。

如果我們要說使徒保羅寫給提摩太的書信中，最精華的經文在哪裏？應該可以說是這一段才對。在這段經文中，使徒保羅提到幾點很值得我們注意的事：

一是他知道自己所剩下的日子不多（第六節）。所以他說他「離開人世的時刻」到了。在第六節他說自己「犧牲」的時候到了，為甚麼他是用「犧牲」這樣的句子呢？這是採用民數記第廿八章七節所提到以色列人用羔羊獻祭在祭壇上的方式，要把獻在祭壇上的羔羊澆滿一公升的酒，然後才點上火燒化獻給上帝。使徒保羅用這樣的詞句來形容自己就像要獻給上帝的時刻到了，意思就是他已經知道羅馬皇帝還是會將他判處死刑，但他看這樣的死刑乃是使他可以當作獻給上帝的牲祭一樣。

二是他做了自我評估，看到自己確實跑完「那值得競爭的賽跑」（第七節）。我曾在前面說過，使徒保羅將傳福音當作是在羅馬競技場上競爭一樣，是在賽跑，看誰能得到最後的勝利而獲得那榮耀的冠冕。請注意，他特別在這裏強調競爭的內容是「值得」的。甚麼是值得的競爭？且是值得用所有生命的力量去競爭呢？當然就是耶穌基督的福音。使徒保羅窮盡一生的時間為了傳福音而奮鬥，並沒有因為遇到挫折、失敗就放棄。如果我們看他寫給哥林多教會的書信，特別在後書第十一章廿三至廿七節這段經文中，他在描述自己傳福音的旅途中所經歷到的際遇，那簡直不是今天的傳道者所能想像得到的；他曾遇到牢獄之災，也曾被鞭打三十九下，又曾遇到多次生命的危險等等。因此，他說自己確實是跑盡全程，實在是一點也不為過。

三是他深信自己可以得到來自天上所賞賜的冠冕（第八節）。他曾寫信給腓立比教會，說自己是努力朝向所訂的目標前進，目的就是要贏得從天上來的獎賞（參考腓立比書三：—）。現在他說這項獎賞已經在等著他去領取，因為他確實跑盡了全程，且沒有改變信仰，因為他守住了該守的信仰。

再者，使徒保羅在第六節這裏用「離開人世」這個詞的希臘文是「analuseos」，這個詞後來演變成為英文的「analysis」（分析）。所謂「分析」，意思就是把原本糾纏在一起的東西，逐一的解開來，使之更清楚、明白。因此，這個字也有「鬆開」、「解放」的意思。這樣，我們可以從這裏了解使徒保羅在說他「離開人世」的時刻到了，意思就是指糾纏生命的一切枷鎖都將解開，不再負著重擔。這就像耶穌基督所說的：「來吧，所有勞苦、背負重擔的人都到我這裏來！我要使你們得安息。」（馬太福音十一：）這也是為甚麼基督教信仰將生命的死亡看成是一種卸下重擔一樣，不是難過、痛苦，而是一種生命的解放（或是一般人所說的「解脫」之意）。因為辛勞一生，終於可以安然休息了，這是很值得安慰的事，特別是有耶穌基督成為復活生命的保證時，這樣的生命更是令人欣慰的事。

*** 第九至十五節：
你要盡快到我這裏來。底馬貪愛現世，離開我到帖撒羅尼迦去了。革勒士到加拉太去，提多到撻馬太去，只有路加跟我在一起。你要去找馬可，帶他一起來，因為他會幫助我的工作。我已經派推基古到以弗所去。你來的時候，要把我在特羅亞時留在加布家裏那一件外衣帶來；同時要把那些書，尤其是那幾本羊皮書卷也一起帶來。

銅匠亞歷山大害我不淺；主會照他所做的報應他。你自己也得提防他，因為他極力反對我們所傳的信息。

這段經文讓我們看到許多珍貴的歷史資料：

一是我們看到醫生路加乃是使徒保羅最好的搭當，當許多其他同工因為各種原因必須離開使徒保羅時，他一直在使徒保羅身邊協助他、照顧他。這也是為甚麼路加這位作者所寫使徒行傳這本教會史書很有價值，就是因為他和使徒保羅在一起的時間很長。使徒保羅甚至稱呼路加是「親愛的路加醫生」（參考歌羅西書四：），可見他和使徒保羅之間的關係甚為密切。

二是約翰‧馬可再次回到使徒保羅身邊，是好的同工。原本約翰‧馬可在使徒保羅第一次和巴拿巴去傳福音時，是同一個團隊（參考使徒行傳十三：），但不知道為甚麼約翰‧馬可突然臨時脫隊，逕自回到耶路撒冷去（參考使徒行傳十三：）。後來使徒保羅想要再第二次出去旅行傳道時，巴拿巴又要帶約翰‧馬可一起同行，被使徒保羅嚴詞拒絕，也為這件事兩個人從此分開各走各的路線（參考使徒行傳十五：—）。我們不知道是甚麼原因使他們再次和好成為同工，且在使徒保羅的語氣中，肯定約翰‧馬可是一位好的福音同伴，在這裏讓我們知道約翰‧馬可對使徒保羅在福音的事工上幫助非常大。

三是底馬貪愛現世。依照歌羅西書第四章十四節的記載，底馬曾和路加第一次陪同使徒保羅在羅馬監獄中。除了路加以外，也曾和約翰‧馬可、亞里達古等人與使徒保羅同為一個團隊在服事福音事工（腓利門書節）。使徒保羅不會隨便批評這些曾與他同工過的人，但現在卻將底馬寫成「貪愛現世」，可見底馬確實有很嚴重信仰上態度的轉變，才會逼得使徒保羅必須說出這樣嚴重的話。

四是使徒保羅對提摩太有很深的感情，在他即將去世之前，希望能見到提摩太一面，或許就像這兩封書信所寫的一樣，他對提摩太有相當的期待，準備要將他的後事告訴他。但同時，使徒保羅並沒有要放棄以弗所教會的福音事工，因為以弗所是當時亞細亞省的省會，在福音事工上的位置佔有很重要的角色，因此，使徒保羅特地差派推基古去接替提摩太。這封書信很可能就是由推基古帶去給提摩太的。

五是銅匠亞歷山大對使徒保羅的傷害很大。這一位亞歷山大到底是誰？我們並不清楚，很可能就是和提摩太前書第一章二十節所提起的那位「亞歷山大」同一個人。到底是怎麼傷害使徒保羅的？也沒有明確資料可循，但使徒保羅在這裏所用的「害」這個字，在希臘文是用「endeiknumi」，這個字是「顯露」、「陳列」的意思，也含有「舉證」的意義。換句話說，很可能亞歷山大就是一個告密者，向羅馬政府告密有關基督徒聚會的事，這對早期教會來說，是很嚴重的一件傷害事件。因此，使徒保羅不僅在這裏提起，還特別要提摩太提防這個人。

*** 第十六至十八節：
我第一次為自己辯護的時候，沒有人在我身邊，大家都離棄了我。願上帝不加罪於他們！主在旁支持我，給我力量，使我能夠把信息完整地傳給所有的外邦人；我也從獅子口裏被救了出來。主一定會救我脫離一切邪惡，接我安全地到他的天國去。願榮耀永永遠遠歸於他！阿們。

第十六節一直被聖經學界討論甚多，到底這裏所提起的「第一次為自己辯護」，這是指甚麼時候的第一次？是使徒行傳第廿八章記載的第一次抵達羅馬之時嗎？不太可能，因為那次並不是沒有人在他身邊，而是有些人一直在關心他、陪伴著他，甚至他還可以自由行動，且去拜訪他的人甚多。因此，有不少學者認為應該是在第二次他被關在監獄之時，那時因為看來情況並不樂觀，且迫害的情形越來越嚴重，頗有風聲鶴唳的氣氛，因而敢公開去探監的人沒有了，大家都有自身難保的危機意識。

第十七節，使徒保羅說上帝給他力量，使他能夠將耶穌基督復活的信息傳出來。其實，這也是使徒保羅堅持要上訴羅馬皇帝法庭的主要因素之一，他一直要讓羅馬統治當局知道，製造亂象的，並不是基督徒，而是一些想要迫害基督徒的猶太人，或是那些排斥基督教信仰的人。他一直努力要讓羅馬統治當局知道，基督徒是很守本份的，絕對不會與政府對抗（參考羅馬書十三：--）。除了這個因素之外，使徒保羅最希望做的一件事，就是將耶穌基督復活的信息傳揚出去，特別是希望能將復活的信息傳給羅馬統治階層的人。當他被羅馬總督、巡撫等人詢問時，他都會利用機會宣揚耶穌基督復活的信息（參考使徒行傳廿四：、、廿六：），也因此使得羅馬總督制止他，認為使徒保羅是「瘋了」，是「神經失常了」（參考使徒行傳廿六：）。這讓我們看出，使徒保羅就是要想盡辦法將耶穌基督復活的信息傳揚出去，那怕是被關、被殺，對他來說，那都是為了傳揚耶穌基督復活的信息的緣故。

第十八節，在這裏，使徒保羅並不是認為自己會從監獄中獲得釋放，因為他已經知道獲救的希望渺茫，才會要提摩太替他拿需要的衣服和書籍，並且要提摩太趕緊到羅馬去跟他相會，因此，這裏他說「主一定會救我脫離一切邪惡」，指的乃是讓他有堅定的信心，不受到任何外力的誘惑，甚至為了保存生命的安全而妥協傳福音的態度，或是對自己過去所傳揚的信息做任何傷害真理的承諾。他深信因為傳福音的緣故而受到迫害或喪失生命的，終必獲得上帝的賞賜，這就是在上帝國裏面得到永恆的生命。

*** 第十九至廿二節：

請替我向百基拉、亞居拉，和阿尼色弗一家問安。以拉都在哥林多住下了。特羅非摩害病，我讓他留在米利都。你要盡可能在冬季以前趕來。

友布羅、布田、利努、喀勞底雅，和其他所有的弟兄姊妹們都向你問安。
願主與你同在！願上帝賜恩典給你們！
在這裏提到一份很齊全的名單，這也是後書與前書之間最大的差異。

亞居拉和百基拉，這是一對夫妻，他們夫妻兩人原本就是織帳棚的人，在哥林多城相遇，因為與使徒保羅同業（參考使徒行傳十八：—），且又有共同的信仰，因此，一直是使徒保羅在福音事工上最好的伙伴。他們也為了福音的緣故，特地將自己的家開放成為聚會的地方（參考哥林多前書十六：）。

而阿尼色弗則是一位很疼惜使徒保羅的同工，為了尋找使徒保羅，他找遍了羅馬城，才知道使徒保羅被囚禁的地方（參考提摩太後書一：—）。

以拉都和提摩太兩人都是使徒保羅很深愛的門徒或是同工，曾被使徒保羅差派去馬其頓（參考使徒行傳十九：）。這裏則說以拉都留在哥林多，在該城的教會見證福音的信息。後來可能就是一直居住在羅馬城，協助該城教會的事工（參考羅馬書十六：）。

特羅非摩，他是使徒保羅的同工，卻也因為他的緣故，被猶太人逮到機會，認為使徒保羅就是故意帶領非猶太人的特羅非摩進入聖殿，等於藐視上帝聖殿的神聖一樣的尊嚴，因此將使徒保羅逮捕送官去審判（參考使徒行傳廿一：—）。

第廿一節提到要提摩太趕在冬天之前到羅馬來，主要原因就是：那是停止水陸交通時期。因為當地的冬天來襲的東北季風特強，不良於航行，若是再延誤一些時日，即使想要成行恐怕也有困難，而且使徒保羅自己也知道可能就會再過幾天日子就會被處死，他真希望看到提摩太最後一面。

友布羅、布田、利努、喀勞底雅等這四位是誰？我們也找不到更多的資料。不過這也是使徒保羅寫書信的一個特色，就是都會將和他同工且在身邊的人，在寄信時順便帶去請安的口信。

第廿二節很特別，前一句是用來對提摩太說的，因此，所用的是單數代名詞「你」，而下半句則是用複數代名詞的「你們」，指的就是對眾人所祝福的話，這裏的眾人很可能就是以弗所教會的兄弟姊妹們。

** 現在讓我們來想想看這章經文所帶來的信息：
*** 一、讓我們在見證福音事工上成為盡忠職守的教會，以榮耀上帝的名。
當我們看到使徒保羅對自己在傳福音的事工上做最後一次反省時，他很清楚當時的局勢對他很不利，因此，他說「犧牲自己的時候到了」，這種「犧牲自己」所表明的意義，乃是要將自己獻給上帝，為的就是要讓福音的信息能夠見證出來，而不是說自己年老體衰，也不是說自己即將老而病死，都不是，而是要準備面對被判死刑的死亡。更重要的，他將自己的死看成是「獻祭」一樣，是神聖且有榮耀，這一點就很值得我們一起來學習的了。

我知道有不少傳道者喜歡在自己退休，或是有信徒過世時，在告別禮拜時用這段經文，我不願意說是否妥當，但我要強調必須清楚使徒保羅說這段話的意義和背景，他是為了見證耶穌基督復活面臨死亡時，才說的這段話。如果一個傳道者只是退休，或是一個信徒去世，就用這段經文，那是需要再次好好評估的。

當使徒保羅回頭一看自己所走過的這段傳福音的道路時，他看到自己就像寫給腓立比教會的書信中所說的，他確實是沒有改變所訂的目標，他是勇往直前朝向這個目標直奔，為的就是希望能贏取來自天上的獎賞（參考腓立比書三：—）。因為他一直懷著執著不變的傳福音態度。從他寫給哥林多教會的書信中，我們看到他為了完成達到傳福音的使命，他甚至是歷經了許多的苦難（參考哥林多後書十一：—），我深信這些苦難都不是今天的傳道者或是在台灣的基督教會曾有過的經歷。我們應該感謝上帝的，乃是沒有讓我們經歷到這些苦難，也因此，我們應該有這樣的認識：至少要學習使徒保羅對傳福音事工的熱情和執著不變的態度，想盡一切辦法要將耶穌基督復活與拯救的福音傳揚出去，使我們的教會成為一間真正可以成為有見證的教會，成為一間可以榮耀上帝聖名的教會，這樣，我們才能仰望耶穌基督再臨的時候，要賜給我們的榮耀冠冕。

*** 二、不論在甚麼情況之下，都不要使傳福音的心冷淡下來，每間教會都要堅持這項使命感，持續到世界的末了。
使徒保羅寫這封書信給他最喜歡的門生提摩太，勸勉他不論在甚麼情況下，都要傳福音，並且在教導信徒的事工上，要用「耐心」、「督責」、「鼓勵」等態度，這在一個迫害的環境和時空下，確實是一個重大的功課。

「不管時機理想不理想都要傳」，這確實是一句很重要的話，對今天的傳道者和基督教會來說，都是一句很重要儆醒的話語。

想想看，甚麼時候叫做「時機不理想」？使徒保羅的時代，是面臨著羅馬帝國迫害的時代，隨時有可能被丟入野獸競技場餵食野獸；他的時代也是個容易就會被人誣告陷害而抓入監牢的時代，隨時都有可能因此被判死刑而釘死在十字架上。即使是這樣，使徒保羅還是勸勉提摩太不要停止傳福音，而且要用「最大的耐心」，努力傳福音，成為福音的見證者。不僅如此，他也要提摩太認真督責信徒，鼓勵他們，教導他們，讓他們在信仰生活和工作上有美好的見證。

如果時機不理想都需要這樣，那麼在時機理想的時候，豈不是更要加倍用心、認真傳福音？當然是這樣，因為那是最容易的時刻，且是最容易看到成果出現，在這樣的時機之下，傳福音最輕鬆，不會有重擔。我們應該說，今天的時代可說是時機最好的時代，也是最有空間的世代，因為今天也不再像使徒保羅的時代，傳福音會受到迫害，也不會有群眾鼓譟公然反對。再加上今天是一個多媒體的時代，可運用的傳播器材很多，這些都可以幫助教會和傳道者好好利用來作為傳福音的器具。我最近就一再接到好幾位兄姊跟我提到怎樣利用多媒體器材，將咱教會查經班、主日禮拜、快樂兒童營等等活動傳播出去。我也接到「好消息頻道」再次來邀請，希望我再去多開一個晚上八點檔的聖經故事節目，這些其實都在說明這個時代，確實是一個傳福音最佳契機的時代，實在不容許我們找藉口來推託沒有辦法。

另一方面，這個時代也是一個心靈很空虛的時代，科技過度發展的結果，不但沒有為我們帶來心靈的滿足，相對的，卻為我們帶來更多的不安和動亂。單單從社會現象的紛擾，以及越來越殘酷的犯罪手段，就可以看出這個時代實在是一個人心相當空虛的時代。我們看到年輕一代吸毒的情況，以及性氾濫的行為日趨嚴重，這些都會令我們擔心不已，深怕感染愛滋病的問題會擴散到成為全球性的世紀大病。

如果我們稍微注意一下，就會發現在元月十七日，台北市中山分局在一家公寓中查獲的所謂「轟趴事件」（Home Party），發現在那些「男性同志性愛派對，九十二人中，竟有高達廿八人是愛滋感染者」，更嚴重的，就是在「這九十二人中，患有梅毒、愛滋或是兩者兼具者共有四十六人，換言之，高達一半患有性病」，想想看，這些現象的背後所述說的意義是甚麼呢？對這些社會現象，我們不是要懼怕，也不是只有一味地譴責這些人的不正當行為，而是要去思考一件事：如果這些人有聽到福音的信息，我深信應該會有很大改變的機會。因為真實的福音就是上帝的話，而上帝的話才是會改變人的心思意念最大的力量。我們不要對這些人放棄，就像更生團契對大家曾經甚為恐懼的殺人犯陳進興，即使知道他已經被判死刑了，也不放棄傳福音給他一樣。

要保持高超的傳福音使命感，這是今天的傳道者和教會最重要的態度，但怎樣讓傳道者和教會保持這樣的使命感，則是所有的信徒需要學習的功課。

（講於二○○四年元月廿五日）
