* 提摩太前後書導論
** 給牧者的信
提摩太前後書和提多書素來被稱作「教牧書信」。帖撒羅尼迦前後書是寫給教會的；而提摩太前後書與提多書則是寫給個人的。然而，它們也並非純屬私人書信，而是保羅寫給提摩太和提多，教導他們如何做牧者的工作。同時，這些書信時常涉及神學，並且包括一些對教義的重要陳述。大致上來說，這些書信的觀點是極爲實際的，討論到在教會任職者的資格，辨別正確或錯誤教導的能力，以及保存福音信息的純正。其中還談到牧者工作在管理方面的細節，例如對待寡婦的方式、視群眾年齡層及階級的不同調整福音信息，以及帶領會眾禮拜。因此這些書信對於任何一個積極從事教會工作的人來說，都是有助益的。

** 寫作時間
在新約中，帖撒羅尼迦後書之後爲提摩太前書，但這並不意味著提摩太前書緊接著帖撒羅尼迦後書之後即被完成。帖撒羅尼迦前後書可能是保羅書信的第一部，並且我們可合理而準確地推算其於主後五十或五十一年完成。那些認爲提摩太前後書與提多書係由保羅寫成的人，都同意這三卷書是保羅書信的最後部份。承認保羅是上述書信的作者，並不能因此保證可以準確地推算出寫作的時間；要做到這一點需要對保羅的一生做整個的重新組織。但大致上仍有一共識，認爲寫作的時間約在主後六十五至六十七年間。那些認爲保羅不是這些書信之作者的人，寫作時間的認定上有更大的出入，但其中大多數的人認爲應介於第一世紀至第二世紀中葉間。無論哪一種看法，我們都在帖撒羅尼迦前後書及提摩太前後書與提多書中，發現保羅的第一部及最後一部書信之間的對比。

** 對作者的認定會影響解釋
爲什麼帖撒羅尼迦前後書被公認爲保羅所寫，而提摩太前後書與提多書卻都引起爭論？雖然在此不可能對這問題提出答案，但處理一些所涉及的議題仍是必要的，因爲我們對於這些議題的態度，必會對我們現今如何理解這些書信的信息有所影響。任何一個讀新約的人必定會觀察到，提摩太前後書於一開頭的經文中清楚地標明爲「作基督耶穌使徒」的保羅，寫給他信仰上的兒子提摩太。提多書也以類似的方式註明。在此，關於經文的正確性是毫無疑問的。這些書信若非出自保羅之手，便是由保羅的跟隨者之一所寫，再以保羅的名義發表。當研究新約的學者逐字讀完這些書信，他將發現這些書信中包含了爲數可觀的自傳材料，而以保羅之名發表。舉例而言，提摩太前書第一章中有一處提到提摩太是保羅在信仰上的兒子(提摩太前書一章2節)；有一段令人動容的自述，描寫保羅回想他迫害基督徒團體時的日子，並想到他自己乃是罪人中最壞的一個(提摩太前書1章12-17節)；另一處則提到他對於舒米乃和亞歷山大的懲戒之舉。其他諸如此類的經節出現在二章7節、三章14 S 15節及四章13節。研究者應該連同這些經節，考查幾處提到提摩太個人的經文，如五章21、23節及六章14、20節。提摩太後書特別具有豐富的傳記內容。例如，在第一章談到了提摩太的母親和外祖母，以及提摩太被按手受任聖職(提摩太後書一章5-6節)，還有保羅個人的信仰見證(提摩太後書1章11-12節)，及他對阿尼色弗的極力讚許(提摩太後書1章15-18節)。同樣地，在提摩太後書四章6-18節，提到保羅的重要言論：他到了生命的盡頭並仰望公義的華冠、對於底馬離棄他而作的批評，一些個人的要求，還有提及他在接受審訊時，眾人都棄他而去，以及他相信上帝將拯救他脫離一切邪惡並保守他直到永生的國度。我們還應注意，保羅在此附帶提到因病留在米利都的特羅非摩。保羅在提多書中，則是對於提多在克里特教會的管理上，給予具體的指示，並且還提到一些個人的事，如打算在尼哥波拉過冬的計劃(提摩太後書一章5節；三章12-15節)。一般唸新約的讀者，將會由於在書信一開頭的身分介紹，以及許多自傳式的內容，而相信教牧書信是由保羅所寫的。但特別鑽研提摩太前後書及提多書的學者，知道這當中仍有一些問題尚未獲得解答。教牧書信與其他保羅書信所使用的語言，有顯而易見的差異。的確，在希臘原文中更容易看出這項差異，但是在英文翻譯版本中也同樣看得出。一個代表性的例子，是在教牧書信中有這樣的句子：「這話是可靠，值得完全接受的」(提摩太前書一章15節；三章1節；四章9節；提摩太後書二章11節；提多書三章9節)；但這種特別的表達方式在保羅的其他書信中並未出現。除此之外，我們若仔細地研究還可以發現，在教牧書信中大概有三分之一的用語，是在保羅早期的書信中找不到的。而且，即使是在這兩類書信中都能發現的用語，在教牧書信中也有著不同的意義。舉例而言，「正義」(righteousness)這個字在教牧書信中用以形容一種道德品質(提摩太前書六章11節；提摩太後書二章22節)；但在羅馬書中，則是用以形容一種信仰的關係。在教牧書信與保羅其他書信中諸如此類的差異，使得細心的學者懷疑，這兩類書信是否真有可能出自同一人之手。


** 風格與內容
敏銳的讀者在研讀教牧書信時，也會察覺在寫作的風格上有不同之處。這種風格上的不同點較難以具體地把握；不過大致說來，與保羅早期的書信比較之下，教牧書信的筆調顯然較爲平和有序。即使是對假教師譴責的段落，也都相當冗長而且有點沉悶(如提摩太前書一章3-7節；提摩太後二章14-26節；三章1-9-1節；提多書一章10-14節)。在教牧書信中有些重要的段落，值得保羅以他最佳的文筆寫出，但整體看來，它們似乎缺少早期作品中那樣的衝擊與熱情。

比風格上差異更爲重要的，是內容上的差異。仔細研究帖撒羅尼迦前後書的學者，會立即察覺到，對基督再來盼望之強調，在比重上有了改變。這種期盼在提摩太前後書及提多書中，仍是信仰上很重要的信條(提摩太前書六章14節；提摩太後書四章8節，提多書二章13節)；不過在帖撒羅尼迦前後書裏，幾乎每一章都可看到這種期盼，並且在許多地方都是保羅進行論證時的主要思想。教牧書信的主要關懷似乎轉變到別的主題。作者非常留意教會組織與架構。在提摩太前中，他詳列長老與執事之資格；他教導提多在每個城市設立長老，並再一次列出長老的資格(提多書一章5-9節)。我們可清楚地看到，這些人被公認爲在主名下的教會中的督導者。雖然在帖撒羅尼迦教會中，確實也施行著一種教會紀律(帖撒羅尼迦前書五章12-13節；帖撒羅尼迦後書三章14-15節)，但對這個教會附帶一提的紀律，已成爲教牧書信的核心。並且顯而易見地，這些晚期書信中關於任命聖職的教義，在保羅早期的著作中並未如此清楚地表述出來。

教牧書信的作者對於保存純正的信仰極爲關心，無論是對於假教師的抨擊、強調健全的教訓、或甚至發展「信仰的託付」的想法，都表現出這樣的關心。在那些確定是由保羅所寫的書信中，「信仰」被認爲是確實地委身給耶穌基督，以祂作爲生命中的救主。這個觀念在教牧書信中並未被忽略，但重點卻是放在信仰的保存上。作者相信基督信仰的精神中，有一種「傳承」；此傳承被界定爲所接受的託付。它必須被善加守護，並且傳遞給那些努力忠心教導別人的人(提摩太前書四章6節，提摩太後書二章2節)。

** 在保羅生命中的時期
任何研究教牧書信的人，幾乎立即會問這樣一個問題：要將它們放在保羅生命中哪一個時期？在提摩太前書中，保羅待在馬其頓，是自由之身。他要提摩太留在以弗所(提摩太前書1章3節)，且希望能快點去看提摩太(提摩太前書三章14節)。在提多書裏，保羅曾待在克里特，並希望在尼哥波立過冬(提多書一章5節；三章12節)。在提摩太後書中，保羅身在羅馬的監牢裏(提摩太後書一章17節)。顯而易見地，他並未在獄中待上一段很長的時間，因爲他提及已留下以拉都住在哥林多，以及特羅非摩害病而停留在米利都。他在特羅亞時留了件外衣在加布家裏。他在羅馬時，底馬、革勒士、提多以及推基古都曾在他身旁；但由於種種因素，他們都離開了，只剩路加仍和他在一起。保羅剛接受了一次審訊；他在亞細亞的朋友都離棄了他，但他依然能夠向外邦人作見證。他催促提摩太儘快趕去看他(提摩太後書四章9-18節)。

這些相關資料與使徒行傳中對保羅生平的敘述相互吻合嗎？在路加的記載中，確認帖撒羅尼迦前後書的內容並不困難，但學者們一般的共識是，在教牧書信中與保羅生平有關的資料，並無法符合使徒行傳的敘述。

由於這個緣故，那些認爲教牧書信爲保羅所作的人，通常會重新建構保羅的生命經歷，以支持他們的立場，例如，他們會假定保羅如使徒行傳中記載的，由羅馬監獄中獲釋，然後他展開了另一個傳道之旅。途中他經過了克里特、馬其頓，以及以弗所等地。提摩太前書及提多書都記錄了這段旅程，而提摩太後書則記錄了保羅再次入獄。另一方面，那些不同意教牧書信爲保羅所作的人，通常會認爲保羅正如路加所述，在羅馬遭囚禁，接著就殉道了。

本注釋的讀者可能想問：這場爭辯的重要性何在？舉例來說，希伯來書曾被列爲保羅書信之一；而在今日，很少人會認爲希伯來書爲保羅所寫。然而，希伯來書的信息並未受作者爲何人的爭議所影響。討論教牧書信作者爲何人，與這些書信是否應被接受爲聖經，這兩個問題是有差別的。即使這些書信是在第一世紀初期產生，它們仍出自保羅一位忠心的門徒之手，這位門徒試圖以他自己的語言表達他認爲保羅會對那個世代的人所說的話--倘若保羅那時還在世的話。這些書信對基督信仰的理解，經過教會判斷後，認爲和教會所持守的信仰一致，也和其他列入聖經正典的書信一致。它們帶著聖經的權威向我們說話，無論它們是否爲保羅親自所寫作。

那麼，爲何作者的問題這麼重要？在提摩太前書第二章5-6節中有一段著名的文字，闡述「基督是上帝和人之間的中間人」這項教義。它是這麼寫的：「只有一位上帝，在上帝和人之間有一位中間人，就是成爲人的基督耶穌；他犧牲自己爲要使人類得自由，證明了在時機成熟的時候，上帝要人人得救。」這段文字不論是保羅大約在主後六十八年所寫，或是他的門徒在後數十年所寫，均是真確的。然而我們在第7節讀到：「爲了這個目的，我奉差遣作外邦人的傳道者和使徒，作教師來使他們相信並認識真理。我沒有撒謊：我所說的都是真的！」在此作者是誰的問題就關係重大。我們或是看待這一節爲保羅真實無僞的見證，或是認爲它是由保羅門徒在保羅去世後幾年，以他的名義所寫的一段話，雖然這段話被認爲適用於保羅身上。這兩種看法的確會使我們對這一經節做出不同的解釋。並且，就某個意義而言，教義的表述所具有的權威，也受到我們對於第7節之作 者的認定所影響。在提摩太前書第一章12-17節中，有一段傳記，裡頭包含著一項重要的宣告：「『基督耶穌降世的目的是要拯救罪人』這話是可靠、值得完全接受的。」不管我們認爲作者是誰，我們均贊同這段話。但作者繼續說道：「我是罪人中最壞的一個。」(他在此想起他曾迫害教會，這在13節有提到。)他接著又說，因著他受到的憐憫，基督耶穌顯示了「他充分的忍耐，使我得以作那些以後要信他、接受永恆生命的人的榜樣。」在這種自傳式的段落中，作者是誰就成爲我們詮釋經文的關鍵。

因此，假使要爲教牧書信寫注釋書的作者，有必要說明他是以何種觀點在詮釋經文。本注釋的立場是假定提摩太前後書與提多書皆爲保羅所作。當然，先前提到有關字彙以及教義著重處有所改變的問題，需要加以說明，不過這些問題無法得到完整的答案。對於那些接受教牧書信爲保羅所作的人而言，仍有些疑點是懸而未決的，不過他們對這些疑點有一些建議和提示。保羅早期的書信與教牧書信之間，相隔約有十五年；在這段時期中，保羅可能在用字上有些改變。用字上的差異有可能是因爲不同的人在記錄這些書信時所造成的。通常是由保羅口述信件的大意，請人代筆記錄，並在信末簽名以示身分。在寫作教牧書信時，他可能將他的想法列個大綱，並允許他的書記在實際撰寫時有相當的自由。也有可能保羅的確有寫這些書信，但在他去世幾年後由他的門徒加以增補、擴充而成。這樣一來，我們無從辨識哪些部分是真正出自保羅之手，哪些是後來增加的。在此情況下，我們仍舊必須將這些書信視爲保羅所作。

雖然主張教牧書信爲保羅所作會面臨一些不容輕忽的問題，但要以其他方式來解釋這些書信的來源，會面臨更大的問題。再者，尙有其他充分的理由可以肯定保羅是作者，其中之一就是書信開頭的自稱以及書信當中的傳記材料；而如此顯而易見的明證不應被輕易地一筆抹煞。此外，在教會剛成立之初，只有馬吉安 (Marcion)沒有將教牧書信列入保羅書信，但他這麼做是出於教義的理由。除此之外，初代教會的作者均一致地接受這些書信爲保羅所作，並且加以引用。當我們想到起初保羅在寫信時是相當用心和審慎的，我們必能了解，在保羅去世後隔一段時間所寫成的書信，要被毫無疑問地公認爲保羅所作，這並不容易。各個時代偉大的注釋家，雖然也同意以批判的方式研究聖經，但基於對各種證據的詳加考察，仍認定保羅是教牧書信的作者，這一點我們也應給予高度的重視。相對於他們考證的結論，我們還必須了解，今日大多數的新約學者並不認爲教牧書信爲保羅所作。但仍有一些學者相信這些書信爲保羅所作；同時，有更多學者認爲這些書信中保存了保羅書信的精髓。

許多人讀了教牧書信之後，會發現他們傾向接受保羅是作者的看法，因爲他們覺得這些書信的傳記部分是真實的。如果作者不是保羅，有誰會給阿尼色弗這樣特別的稱讚(提摩太後書一章15-18節)，或是因爲提摩太消化不良及經常生病而建議他喝少許的酒(提摩太前書五章23節)？在研讀提摩太後書時，其中的傳記部分更令人感到所言不虛。書信中描繪這位偉大使徒最後一次坐牢的景況，確實是真實可靠的，保羅的一些朋友離棄了他，另有一些朋友趕赴危險的任務，只有路加陪伴他。保羅接受審訊，而這使他得以有機會爲基督作見證。他知道自己即將離世，因而渴望在臨終前見提摩太一面。在此脈絡下，讀者可讀提摩太後書四章6-8節。有誰不會被這股肺腑之言感動呢？讀到有關這個審訊的敘述(提摩太後書四章16-17節)，並看到保羅接著說：「主一定會救我脫離一切邪惡，接我安全地到他的天國去」(提摩太後書四章18節)，任何人都可感覺到，這是保羅對提摩太最後的遺言，也是透過提摩太向教會的最後的遺言。

要認定作者是保羅，會碰上一些相關的問題；這些問題雖都是真實的，但不一定具關鍵性。例如，即使用字遣詞上有所改變，但人在不同的處境、生命的不同階段所使用的語彙的確可能有所不同。教義上的著重處有所轉移，但這可被設想爲因保羅的年紀漸長，且基督的再來似乎延遲了。對於一個即將卸下世上工作的人來說，關心教會的組織是極爲自然的。同樣地，鑑於保羅在寫這些書信時所面臨的處境，則他對福音的純正性以及信仰的託付有日益加深的關切，也是合情合理的。此外，保羅在歌羅西與腓利門書中對自己身繫囹圄的態度，和在提摩太後書中表達的有所不同，因此，可說是有必要假定保羅在羅馬曾兩度入獄。


** p153
上帝的福音 提摩太後書一章15 18節 問安( 一章152節) 對於提摩太後書的背景資料，除了這封信所提供之外，其他任何地方無從得 知。這是一封非常私人性卻又具啓示性的信。當保羅寫提摩太前書時，他還是自 由之身，他差派提摩太往以弗所去，且希望能和他在那裡儘快會合。而寫給提多 的信也是保羅能夠自由、積極從事宣教工作之時所完成的。但提摩太後書卻是保 羅身處羅馬監獄時才著作的書信。此外，比較這封信與保羅所寫作第一封監獄書 信(如歌羅西書) ，反映出截然不同的態度。當保羅第一次下監時，他正等候審 判，如同一位尚未判刑的人，仍有機會期待被釋放。但是當他第二次下監時，整 個羅馬地區對基督教的態度已經全然改變。寫這封信時，保羅已是一位被判有罪 的人， 一位被迫害教派的領袖。經過初審，他已無法倖免於死刑的結局，所以對 


標！ 的是 他的朋友而言，接近保羅是一件很危險的事。除了路加之外，不知什麼原因，保 羅所有的朋友都離棄了他。阿尼色弗則找他找得很辛苦。在這種處境下，保羅這 封信就成爲他留給提摩太最後的遺音；不僅如此，它更像是一個偉大的使徒留給 他所服事過的教會一段最後的話語。在這封書信裡，保羅試著激勵提摩太面對迫 害，因此，他不停地描繪著一個有信心的基督徒牧者的形象。在這封寫給他主內 親愛兒子的親密信件中，保羅表達了他深切的關懷，如同他正站在人生道路的盡 頭，回頭看他作使徒的生命，以及往前看那在墳墓背後與基督同在的生命 問安的部分仍是依循著提摩太前書的格式。保羅再一次確認自己使徒的身分 而且他是基督耶穌所差派來的人。他成爲使徒並不是因爲自己的選擇，乃是憑著 上帝的旨意。至於他宣教的中心目標乃是爲了宣揚「藉著基督耶穌應許的新生 命」。他寫信給提摩太就好像寫給一位他所愛的孩子。在前書裡，保羅強調提摩 太是他在信仰中真正屬靈的兒子；在後書中，重心則轉移到他對提摩太深切的疼 愛。第2節的後半段在這兩封書信中則是相同的


* 提摩太後書這本書信
　　這也是一封使徒保羅在監獄寫的書信，雖然不是像以弗所書、腓立比書、歌羅西書、腓利門書等四本同列為「獄中書信」，我們從第二章九節他提到說：「我因為傳福音而遭受苦難，甚至被捆綁，像囚犯一樣。」就可看出他已經人在監獄中服刑了。但長久以來，提摩太前、後書，以及提多書等這三本都被歸類為所謂「教牧書信」，顧名思義是談到有關在教會牧養工作的問題，主要的目的是在告訴提摩太要怎樣固守著以弗所教會，別讓那些專門在破壞正確信仰的人，在教會中得勢。

** 為甚麼要寫這封書信
　　當他第一次在羅馬等待受審之時，那時他是備受禮遇，可以在外面租屋居住，隨時有人去請問有關信仰的問題（參考使徒行傳廿八：23）。但現在則不是這樣，他是「被捆綁，像囚犯一樣」（參考提摩太後書二：9）。他這次在監獄中，雖然還沒有被審判該受怎樣的刑期，但卻可看出使徒保羅內心似乎已經有了個譜——死刑（參考四：7）可能為了這個緣故，他急切地希望能見到提摩太，要他「盡快」到羅馬監獄去看他，且最好是趕在冬季之前（參考提摩太後書四：21），可見他與提摩太之間的關係多麼地密切，他曾說提摩太是「惟一」跟他同心的福音伙伴（參考腓立比書二：22）。

** 一、使徒保羅寫提摩太後書，心中是相當寂寞的。
　　在第一章十五節，他特別提到說：「在亞細亞省的人都離棄了我，包括腓吉路和黑摩其尼在內。」在第四章十六節說：「我第一次為自己辯護的時候，沒有人在我身邊，大家都離棄了我。願上帝不加罪於他們！」腓吉路和黑摩其尼必定是在亞細亞省教會很有名望的教會領袖，意思是大多數信徒都背棄了使徒保羅。另外一個重要的同工也離開了使徒保羅，那個人就是底馬。他原本與路加都是使徒保羅的同工（參考歌羅西書四：14），為甚麼會離開？使徒保羅說他是因為「貪愛現世」（參考提摩太後書四：10）。但我們知道此時的使徒保羅心中是孤獨的，需要有人在他身邊。

** 二、在羅馬皇帝尼祿殘酷手段逼害下，已經有不少信徒離棄了信仰。
　　希望提摩太看待因信仰受逼害的事件，要與其他的信徒有不同的態度。他說：「你不要把為我們的主作證當作一件羞恥的事，也不要因我為了主的緣故成為囚犯而覺得羞恥。你要按照上帝所賜的力量，為福音分擔苦難。」（提摩太後書一：8）可見當時在迫害之下，離棄信仰的人中有人開始對福音所帶來的生命際遇感到難以理解，更嚴重的是將為福音受苦的事當作是一件有羞恥感的事。這種「不以福音為恥」的信仰告白，一再出現在使徒保羅傳福音的態度中。

　　因此，寫這封書信也有一個主要用意，是多給一些鼓勵，即使人已經陷入囹圄中，還是盡他當福音僕人的使命。他從提摩太身上著手鼓勵做起，要他「堅守」從使徒保羅所領受得到的信息，以及和主耶穌之間連結所得到的「信心和愛心」（參考提摩太後書一：13）；要提摩太「持守」所接受的和確信的「真理」（提摩太後書三：14），並鼓勵他無論「時機理不理想都要傳，用最大的耐心勸勉，督責，鼓勵，教導」（提摩太後書四：2）。這讓我們看出，即使是像提摩太這樣值得他信任的同工，甚至可看成是「信仰上的真兒子」，也是要在迫害的時空下，多給一些鼓勵。

** 三、很人性化的一本書信
　　聖經中很少有一本經書是這麼清楚將自己的人性需要表露出來的，而提摩太後書卻在這方面充分地讓我們看到：作為一個傳道者在人性上的軟弱。我們看到的使徒保羅也有「孤獨感」的一面，因此，需要有人陪伴他，或是說需要「信仰上的真兒子——提摩太」專程去看他。不但這樣，他還特別交代提摩太去看他的時候，記得將他放在特羅亞的加布家裏之一件外衣帶去。我們不清楚這件外衣為甚麼對他在監獄中有那麼重要，或是說這件外衣在他生命中所代表的特別意義是甚麼，不過擁有一項自己看為最珍貴的物品在身邊，一般人陷入牢獄中也常會有這種想要將珍貴的物品留在身邊，這是很自然的，因為這樣或許對正在孤獨感甚深的受刑人來說，有很大慰藉。他同時要提摩太也為他帶去存放在那兒的一些「羊皮書卷」。所謂「羊皮書卷」，應該指的是舊約聖經。在監獄中閱讀聖經，這情形就像許多在監獄中的囚犯不忘記繼續研讀聖經一樣，我們看到人心靈裏共同的需要，這就是上帝的話語。

　　我們也從這本書信中看到他也在心中還記得一位名叫亞歷山大的銅匠，他說這位銅匠曾害過他很深，並且語帶詛咒的內涵說「主會照他所做的報應他」（提摩太後書四：14）。在這封書信中，他也提到了舒米乃、腓理徒、腓吉路、黑摩其尼，特別是舒米乃，不僅在前書提起，後書又再提起一次，可見這個人在當時的亞細亞省教會造成的影響有多大。使徒保羅將這些人對教會造成傷害的人的名字都一一寫下來，這樣的態度與他寫給羅馬教會書信指導的信仰態度顯然有差別（參考羅馬書十二：14、19-21）。但這種處理教會失序的方式，也成為後來教會引用作為借鏡的一種模式。



