提摩太後書第三章：聖經是上帝所默示

* 1_背景

　　在第二章十四節至廿一節這段經文，使徒保羅提醒提摩太要教導以弗所教會信徒怎樣過教會生活，特別是對那些會導致信徒離棄信仰的異端邪說，要特別注意。不需要跟那些專門傳講這種謬論的人辯論，他甚至特別指名道姓的說出兩個導致信徒離棄信仰之道的人，就是舒米乃和腓理徒。這讓我們看到自從有教會這樣的信仰團契以來，內部就一再出現不同的聲音，而這些不同之聲音所造成的困擾，往往也是分裂教會的因素之一。

　　早期教會之所以會有這樣的困擾，主要原因是當時沒有像今天的教會有一本大家公認為權威的經典可作為依據。那時候唯一有的，就是猶太人的經典，也就是我們今天所謂的舊約聖經。因此，對耶穌基督所帶來新的信息，早期教會則是「傳說」甚多，作品也不少，但卻都是眾說紛紜，就像醫生路加所說的：「已經有好些人從事寫作，報導在我們當中所發生的事。他們的報導是根據那些從開始就親眼看見這些事，並且曾經傳佈這信息的人所敘述的。」（路加福音一：1-2）

　　這讓我們看到早期教會內有許多文書、信件都會談到有關耶穌基督的事，但誰說的比較正確？一般來說都會依據使徒們所寫的為準。可是，並不是每個使徒都會寫書信，這也是一件很遺憾的事。還好，後來有使徒保羅將基督教信仰做了個總整理，特別是他寫出了羅馬書這本被認為最重要的一本整理基督教信仰的經書，才使得基督教信仰有了個底子，這本「羅馬書」的經書也是影響基督教會相當深遠的一本經書。然後，我們看到每當使徒保羅用心在處理教會發生的問題時，因為無法親身去處理教會遇到的問題，包括信徒之間的紛爭，也有信仰上遇到的困擾等等，他大多是以書信回答當時教會所遇到的問題。誰也沒有想到，這些接近兩千年前回答問題所寫的書信，卻成為我們今天建構教會秩序時的基礎，這一點也是使徒保羅怎麼想也想不到的事。

　　因為使徒保羅在當時教會備受尊重，因此，他所提出的看法、意見、處理方式等，都成為教會處理問題的依據，因此，他的書信不僅流傳在一間教會，也會傳給鄰近的教會閱讀，所以，當後來教父們在編輯新約聖經時，就會考慮到將使徒保羅的書信給編入聖經正典當中，成為信徒們閱讀的必要經書之一，主要目的就是要讓大家明白怎樣過教會這信仰團契的生活，以及應該有的信仰態度。

　　但我們都知道，使徒保羅雖然自己寫了對信仰的認知，甚至有很多次他就是在書信中作信仰告白，例如在前一講已經提過的提摩太後書第二章十一至十三節，可說就是使徒保羅的信仰告白一樣。這些信仰告白的內容都有相當清楚的舊約聖經依據。我們應該要有這樣的認識：基督教信仰的基礎，並不是只有新約聖經，舊約聖經和新約聖經的地位是同等重要，缺一不可。這也就是當使徒保羅寫信給提摩太時，一再提醒他要在聖經上下功夫，這樣才能夠「正確地講解真理的信息」（參考提摩太後書二：15），以免教會內部因為對信仰的認識不夠，或是失去基礎而發生偏離的現象。

* 2_經文內容
** 第二章廿二至廿六節：
　　這裏使徒保羅再次提到提摩太是個「少年人」，在前書第四章十二節，使徒保羅就曾提醒提摩太：「別讓人小看你年輕。無論在言語、行為、愛心、信心，和純潔各方面，都要作信徒的榜樣。」現在則是要他不要「意氣用事」，這是指那些年輕人所比較容易呈現出來的「輕浮、虛榮、易怒、好辯論」等毛病，這些都是使一個人最容易失去理智判斷事務的現象。作為一個傳道者，必須在這方面盡可能避免。而相對於這些輕浮等事，則是要追求正義、信心、愛心、和平。這裏使徒保羅用的「追求」這個詞很特別，這原本是指如同一個人出去狩獵，看準了獵物，就盡所有力量一定要將獵物追到，唯恐稍微有疏忽而失去了獵物一樣。換句話說，使徒保羅希望提摩太要認真、用功到就像一個狩獵者在追捕獵物一般，認真在追求正義等這些信仰功課上。因為正義、信心、愛心、和平等這些都是在信仰團契中不可缺少的要素。

　　第廿三至廿四節可以參考第十四節，也是在強化第廿二節所提起的「少年人意氣用事」。信仰並不是用辯論可以服人，信仰是透過真實愛的分享感化人的心而得到的，就像第廿五節所提到的，用「溫柔規勸敵對的人」。所謂「溫柔」，是指不傷害對方的尊嚴。這也是一種為對方著想，而不是只有為了自己的益處爭奪。

　　請注意，這裏提到「不可爭吵」，並不表示為了息事寧人而採取妥協的態度，不是這樣，而是不退讓，但有所堅持。就像「母親乳養兒女一般」（參考帖撒羅尼迦前書二：7），是用生命的愛給予開導，希望對方明白真正的要理是甚麼。主要的目的，就是放在第廿六節，為的是期盼有一天，即使這些離開了教會的信徒因為走錯了路，也會迴轉過來，而不會覺得羞愧不敢回頭。這讓我們看到使徒保羅用心的，就是信仰的事，他並不希望因為有人誤入「歧途」，導致大家如同仇敵一般，他總是留給對方有個回頭的空間。這並不是用「沒關係」或是以「和稀泥」的態度隨便了事。信仰的事應該要有所堅持，對的，就是對；錯的，一定要指明出來。

** 第三章一至九節：
　　第一節又讓我們看到「世界的末期」這樣的詞句。聖經每談到世界末了時，隨即跟著來臨的，就是上帝的審判。在使徒保羅的書信中，談到世界末了，就會與耶穌基督再臨的事連結在一起談論（參考羅馬書二：16，哥林多前書四：5、五：5，帖撒羅尼迦前書五：2）。這讓我們看到，早期教會相信世界末日很快就會來到，而那時候，耶穌基督就會再臨，他再臨，就是要審判世界。在早期教會相信耶穌基督很快會再臨，可說是最重要的信仰告白之一，也因為這樣的信仰告白，他們忍受了來自猶太人和羅馬政府的嚴厲迫害，他們相信這個日子過不久會來到，當然這與使徒行傳第一章十至十一節記載耶穌基督升天時，有兩位穿著白衣的天使所傳出的「你們看見他怎樣升天，他也要怎樣回來」的信息有密切關係。而在約翰福音第十四章一至四節，耶穌基督也曾親口說出他去，但還要再來接信靠他的人到天上去，這對正受到迫害中的信徒來說，期盼耶穌基督再臨，可說是信仰中最大的支撐力，也是苦難生命中的一劑強心劑。

　　再者，使徒保羅在寫給提摩太的書信中，已經有提過一件事：「聖靈明明說了，在末後的時期，有些人會放棄信仰，去順從欺騙的靈和邪魔的道理。」（提摩太前書四：1）在末世的日子裏，假先知甚多，許多在那苦難的日子中失去了明辨真理的能力，跟隨了這些傳講假信息的人走。這種情形並不是只發生在新約聖經的時代，即使在今天的世代也是一再出現這樣的情景。

　　這裏也看到使徒保羅告訴提摩太，說在「世界的末期會有種種苦難」，這裏所提到的「苦難」，是指被魔鬼附身所帶來的折磨慘狀。像馬可福音第五章一至二十節所提到的、那位在格拉森出現被「大群」鬼附身的那個人一樣，那人已經不知道自己在幹甚麼，連睡在墓穴中、用石頭砸自己也不知道。因此，從這裏可以了解「苦難」的另一個意義，就是無法控制自己，就像「自我節制」一樣。明明知道不可以，卻一直陷下去。這樣，我們就可以明白使徒保羅所說的，這就是人的罪最典型表現的方式，也是人生命最大的軟弱與痛苦，因此他說：「我真苦啊！誰能救我脫離這使我死亡的身體呢？」（羅馬書七：24）

　　另一方面，這裏的「苦難」還有另一個意思，就是指來自外在的攻擊、威脅，這也是初代教會一再會遇到的經歷，我們在使徒行傳中經常讀到每當使徒保羅和他的門徒在各地傳福音時，就會遇到猶太人設法製造動亂，想要造成羅馬政府有個錯誤的認識：基督徒就是社會的動亂者。這使我們想到主後六十五年左右，羅馬皇帝尼祿將羅馬城大火的事件，將之歸咎於基督徒，就可以想像得到那種罪狀會帶來的迫害有多嚴厲。

　　第二至六節，在這段經文中，使徒保羅一連串提到在世界末期的日子中，所出現各種令人難過的現象，在這裏他總共列舉了十九項不好的行為，我們可以將之歸類九點：

一是自私，只顧自己。使徒保羅寫信給腓立比教會時，特別提到我們要學習「以基督耶穌的心為心」，他說：「不要自私自利，不要貪圖虛名，要彼此謙讓，看別人比自己高明。不要只顧自己，也要關心別人的利益。」（腓立比書二：3-4）基督徒若是自私、只顧自己，就無法跟別人分享耶穌基督救贖的愛。因為自私的人最容易表現在貪財的行為上。使徒保羅曾說「貪財是萬惡的根源」（參考提摩太前書六：10）。因為這樣的人，不會去憐憫苦難者的需要。

二是自誇、狂傲。所謂「自誇」，原來的意思是指沒有真才實力，卻誇口說很有能力。「狂傲」是比「自誇」還要嚴重的毛病。這個詞的原來意思，是指一個人站在很高的地方，誇口自己的才能有多少。換句話說，在他的眼中根本就沒有任何其他的人可以跟他比高，因為他就站在最高點在講話。因此，詩篇的作者說這種人的心中不會有上帝（參考詩篇十四：1）。而更嚴重的是，這種人往往會把自己當作是上帝一樣，以自己為中心。

三是「忤逆父母，忘恩負義」、「沒有親情」，這三個詞句都有共通的意思。父母可說是子女最大的恩人，而會忤逆父母的人，基本上就是忘恩負義的人。忘恩負義，也是指對上帝恩典的藐視，因為父母乃是上帝給人最好的禮物。摩西法律中甚至明白規定，侮辱父母的人，可以處以死刑（參考申命記廿一：18-21、廿七：16）。而「沒有親情」，指的就是對家族同胞的愛喪失了的人。

四是不聖潔、恨惡良善，這是指懷有壞的念頭，對人存心不良，這樣的人很容易產生不好的計謀去陷害別人。「恨惡良善」則是與嫉妒有關。看到別人有好的行為或表現時，會充滿嫉妒的心，進而會設計陷害對方。

五是殘忍、凶暴，這是對苦難的生命沒有憐憫之心的意思。特別是在那迫害的時代，對那些被抓去關在監獄中的人，還存著幸災樂禍的態度，這種人就是殘忍、凶暴。

六是散播謠言、蠻橫，這是指一個人亂說話，故意編造虛假的故事，為的是要羞辱別人，這樣的行為很容易引起爭端。散播謠言就像違背十誡的第九誡一樣，都是存心不良的行為。而「蠻橫」則是對自己的約束不夠，沒有自制的能力，容易與別人起衝突。也就是不願意尋求與別人和好，只想要欺負別人。

七是出賣師友，這是指昧著良心說不誠實的話，或是做傷害朋友、師長的事。這已經是沒有道義可言，就像猶大出賣耶穌基督一樣。在早期教會也發生有些信徒為了自保，將其他信徒的名單提供給正在設法要逮捕的迫害者羅馬政府，使他們受到殘酷的迫害。

八是愛享樂過於愛上帝，這就像路加福音第十六章十九至三十一節耶穌基督比喻中的那位財主一樣，他可以天天奢華宴樂，卻沒有時間敬拜上帝。其實，這樣的人在心中根本就是藐視上帝的神聖和偉大。

九是假冒有信仰的人，但並不是真的如此，這種人也是使徒保羅經常指出的「假使徒」，不僅發生在哥林多教會（參考哥林多後書十一：13），也發生在加拉太教會中（參考加拉太書一：8），在以弗所教會中也出現這樣的人（參考提摩太前書一：3-4、四：1-3）。

　　第七節，使徒保羅特別提到這些假教師最喜歡使用的伎倆就是到處串門子，去誘惑婦女離棄真道。使徒保羅寫給提摩太的第一封書信中，也特別提醒提摩太注意那些年輕且守寡的婦女，要教導她們不要到處串門子，講些有的沒有的話，害教會紛爭更多（參考提摩太前書五：13-14）。現在他再次提起有些婦女比較容易受到那些能言善道的假教師誘惑，因此，要提摩太特別注意婦女行動。有時看起來她們是想要學習更多，但往往尚未學成認識真道，卻已經受到迷惑。在第6節中提到的婦女，她們並不是代表所有的女性，而是其中保羅知道有些姐妹，容易被錯誤的教導引導，偏離了正路。

　　在第八至九節這裏使徒保羅特別提起兩個專門在欺騙婦女信徒的名字——雅尼和洋布雷。這兩人到底是誰？除了這裏出現之外，聖經中都沒有他們兩人的資料。但在猶太人的傳說中，說這兩人就是埃及法老王身邊的「術士」，曾被指派來抵擋摩西能力的人（參考出埃及記七：11-12、九：11）。早期教會的信徒對摩西所行的神蹟，以及他帶領以色列人出埃及的故事相當熟悉，因此，使徒保羅將雅尼和洋布雷的行為，比喻在法老王身邊用來抵擋摩西的術士，為的是讓當時的信徒知道，反對聖經的教訓，就等於那些術士一樣，到最後受到傷害的，就是他們自己而已。

** 第十至十三節：
　　這段經文剛好和前一段經文所提起的完全相反；在前一段提到末世的時代，人心墮落和惡劣的景況，這一段則是提醒提摩太要謹守從自己信仰的父親——使徒保羅——所領受的教導謹記在心。使徒保羅對提摩太有著相當的期待，也因此，他期盼提摩太確實會和一般人不同，他對提摩太要求會比較嚴格。

　　在第十節，使徒保羅特別指出他教導給提摩太的，是有正確的人生觀，以及很好的生活態度，不但有好的行為，也有信心、寬容、愛心、忍耐。這五項其實都可以在使徒保羅傳福音的過程中看的出來。

　　請注意這裏提到的「跟隨」這個詞，是表示「很詳細」的意思。這是指提摩太跟隨使徒保羅四處去傳福音，對使徒保羅的所行所為都很清楚。這也是在第十一節提起在安提阿（這是指彼西底的安提阿，參考使徒行傳十三：14）、以哥念（參考使徒行傳十四：5）、路司得（參考使徒行傳十四：19）等地遇到迫害的經驗，使徒保羅都用極大的容忍之心給承受了下來。這些受到迫害的經歷，都是提摩太相當清楚的事。而這些迫害的事實也說明了使徒保羅是一個有好行為和信心、愛心的傳道者，否則跟隨他身邊的人一定會趁隙離他而去。沒有人會跟隨一個行為不檢點、缺乏愛心的傳道者，自古以來就是這樣。

　　第十二節，這是一節很有意思的經文，對早期的基督徒來說，這句話確實具有相當的震撼力，因為說出了基督教信仰真實的意義，並不是在尋求物質生活上的大富大貴，也不是在尋求生命的安全，剛好相反，因為信耶穌基督是與永恆的生命有密切關係，而這永恆的生命必須與敬虔的生活有關，這對當時在羅馬帝國統治之下，特別是在以弗所城來說，因為敬拜女神亞底米而造成淫亂行為甚厲的生活，成為極大的對比，因此，使徒保羅這句話確實很令當時以弗所的信徒很大的震撼。我們看到使徒保羅並不是只在講究信徒數多就好，他更是要求信仰必須和生活相連結在一起，但對一個淫亂成性的都會生活的人來說，過敬虔生活的人反而會被人認為是「異端」、「有問題」，可能因此就遭遇到親朋好友孤立，甚至拒絕來往，嚴重的還會被排斥、受到壓迫。

　　第十三節，「他們欺騙別人，自己也被欺騙」這句話，可說是針對那些假使徒說的，也就是那些將福音當作商品用來欺騙別人的人，到最後一定會露出他們欺騙的伎倆而遭到眾人的唾棄。

** 第十四至十七節：
　　這段經文再次讓我們看到使徒保羅對聖經的重視。在後書第二章十五節，使徒保羅曾勸提摩太要「正確地講解真理的信息」，現在則是再次提起聖經的重要性。耶穌基督在講到財主與乞丐拉撒路的比喻中，就特別提起亞伯拉罕拒絕了那位死後被下到陰間受苦的財主的懇求，說：「你的兄弟有摩西和先知們去警告他們，讓你的兄弟去聽他們吧！」然後又說：「如果他們不聽摩西和先們的話，即使有人從死裏復活，他們也不會相信的！」（路加福音十六：29、31）請注意耶穌基督在這裏所提到的「摩西和先知的話」，指的就是舊約聖經。摩西代表著律法書，先知代表著聖經中所有先知的作品。一般來說舊約就是用這兩大部分構成的。

　　第一世紀的時代之聖經，就是舊約聖經。使徒保羅在這裏提醒提摩太，一定要重視聖經。因為提摩太的母親是猶太人，父親是希臘人。猶太人的家庭教育就是母親在擔當的主要使命，每個小孩子在六歲之前就會背誦十誡，在八歲以前會背誦出埃及記、默寫十誡，然後在十歲之前，必須會背誦出埃及記和申命記、默寫出埃及記，在十二歲以前，也就是國民小學畢業要進入初中之前，必須會背誦摩西五經，並且會默寫出埃及記和申命記。因此，對提摩太來說，他就是在母親教導之下，從小就開始學習認識聖經。

　　使徒保羅說聖經能給人有「智慧」，以及指引「信耶穌而獲得拯救」。聖經告訴我們所謂「智慧」，是指認識上帝（參考箴言九：10）。而整本聖經就是在告訴我們，上帝怎樣藉著耶穌基督來拯救人類。

　　第十六節是很重要的一節，也是經常有人提起討論的一節經文。要特別注意的是，在使徒保羅寫這本書信之時，那時候的聖經只有舊約。因此，當這裏說「全部聖經」，其實就是指舊約聖經說的。但我們今天的認識是包含了新約，而且我們也寧願這樣接受。

　　再者，使徒保羅在這裏說全部聖經都是「受上帝靈感而寫的」，這句話是指聖經並不是人想到要寫一本經典，就寫得出來。其實沒有一位作者想到自己在感動之下寫出來的書，後來會成為教會使用的聖經正典，這就像使徒保羅或是路加，他們一定沒有想到所寫的書信，或是福音書、教會歷史記錄，會成為今天的聖經正典。他們主要目的只有一點：就是將聖靈感動他們的話寫出來，將他們所知道的事告訴當時的信徒。我們可以這樣了解：全部新舊約聖經六十六卷的作者，都有一個共同目的，就是要讓讀者知道上帝的愛和拯救。他們將自己的信仰告白和對上帝的認識寫出來，當作教導或是反省的教材之用。

　　因為有上帝聖靈感動人的心，因此，這本聖經就成為基督教會共同的準則，可以讓有紛爭的教會明白甚麼是正確的？甚麼是錯誤的？若是沒有聖經，教會就會很容易陷入人為標準的危險。第十四至十五世紀的基督教會就是有這樣的危險，才會引起馬丁路德進行宗教改革，並且喊出「聖經乃是教會最高權威」。而約翰‧加爾文則強調「教會乃是建立在聖經的基礎上」。

　　第十七節，這裏使徒保羅說明白聖經的人，就會成為上帝所喜悅的僕人。換句話說，要成為一個傳福音的僕人，必須在聖經的教導上有明確認識，否則就無法成就上帝拯救的工作。

* 3_經文信息
** 3_1_用聖經的教導建造教會信仰的根基，才是永遠存在的力量。
　　使徒保羅一再告訴提摩太一定要正確明白聖經，並且「正確地講解真理的信息」，這樣才能幫助信徒們知道甚麼是謬誤、過錯，才會清楚明白真正的信仰內涵。使徒保羅對提摩太所說的這些話，其實也是在對今天的教會和傳道者所講的。他告訴提摩太說「全部聖經都是受上帝靈感而寫的」，這一點也是基督教信仰所告白的，相信聖經就是上帝的話。而上帝的話就是真理；這真理是永恆的，在述說上帝奇妙的救恩與愛。

　　怎樣明白上帝的話語，且會將研讀聖經上帝的話語當作生活中最重要的一部份？這是一門很重要的功課，也是所有基督教會與傳道者要認真省思的一件事。因為一間教會若是沒有聖經上帝的話作為基礎，不論該教會的規模多大，只要我們的環境一變遷，該教會很快就會受到衝擊和影響而改變。設若教會想要屹立不搖，就必須有上帝的話作為基礎，這一點是我們要切記的信仰認知。

** 3_2_生命中會有許多苦難，但我們因為信靠耶穌基督的救恩而勝過苦難。
　　就在監獄中，使徒保羅寫這封信給他最信任的得意門生提摩太時，很清楚地告訴他說：「你要知道，世界的末期會有種種苦難。」然後描述在那苦難的環境中，會有許多讓人聽到、想到、看到就會感到相當難過的事頻頻而來，這些難過的事，包括了對父母的忤逆、忘恩負義，以及出賣師友等等共計多達十九項。如果我們將使徒保羅所描述的這些發生在人身上問題剖開來看，就會發現不僅發生在他的時代，也是發生在我們這個時代。也因為這樣，我們經常會聽到有人說這個時代，很像是個世界末日的時代一樣。

　　生命中會有許多苦難，這也是耶穌基督在最後晚餐中對門徒們所說的話，他說：「在世上，你們有苦難；但是你們要勇敢，我已經勝過了世界！」（約翰福音十六：33）基督教信仰並不是保平安、大賺錢的，基督教信仰反而是讓我們更清楚：生命中會有苦難。但我們因為信耶穌基督而獲得生命真實的力量，會勝過生命中的苦難。甚至會讓我們有足夠的勇氣面對生命苦難來臨。

　　陳南州牧師，當他兒子在幼小的時候因為得小兒麻痺症，他夫婦兩人四處尋找所有可能醫治的醫師、處方，但都遍尋不著時，非常痛苦。牧師娘杜靜枝姊寫在「新使者」的一篇文中這樣說：「上帝知道我有能力可以接受這樣的重擔。」讀到這句話受到很大的鼓勵，也感受到一股極大的生命力在靜枝姊的身上。她確實將這樣的重擔承受了下來，一直到她過世的時候，她沒有為這件生命中最痛苦的事多說甚麼，她深知上帝已經給她足夠的力量，使她能夠承受這種生命的苦難。

　　沒有人能夠說信耶穌基督，生命中不會有任何不安或苦難的事發生，沒有！因為這不是聖經的教訓，連耶穌基督也告訴他的門徒，說「在這世上，你們有苦難」。但我們要知道，苦難並不是生命的終點，也不是生命的羅網，因為耶穌基督告訴我們，他要我們「勇敢」，因為他已經「勝過了世界」，沒錯，就是因為耶穌基督的復活，使我們的生命從苦難中產生希望，也從希望中看到生命的亮光。因此，基督教信仰並不是要告訴我們要怎樣逃避生命的苦難，而是要告訴我們怎樣勇敢去面對生命的苦難，並且彼此鼓勵，好讓我們能學習耶穌基督勝過這世界的苦難，這樣才對。

　　也是從這裏，我們要明白重要的一點：每當我們聽到國家有危險來臨時，我們並不是要想辦法逃避離開它去，而是要學習更堅定的信心，仰望上帝的帶領，學習耶穌基督的精神，讓我們因此得到更多的力量，承受所要面臨的生命苦難。只有這樣，我們才能向那些無法逃避苦難而必須接受苦難臨身的人說：我們與你們一起承受苦難，但我們已經勝過苦難，你們也可以像我們一樣，因著耶穌基督勝過苦難！這才是我們要見證的福音。
