* 傳揚
** 學習禱告的生活 黃銀成 2016年5月15日
http://weproclaimhim.com/?p=3245
*** abstract
禱告，要用心靈和誠實向神說話；因為神是靈。禱告就是把我們內心的一切，放在神面前，不論傷痛、憂慮、喜樂、愛慕、讚美、抱怨、軟弱、疑惑毫無保留地、自然地呈現在主前、與祂分享、求祂分擔。
禱告絕對不是一個形式，而是使人能從新得力的關鍵！受苦的時候，我們就來禱告；喜樂的時候，我們就向神歌頌，除非你向主坦誠，否則你很難去了解主的旨意，讓我們藉著禱告學習禱告。

*** context

禱告，不在乎話語的多少、辭句的巧拙，要用心靈和誠實向神說話；因為神是靈，我們必須用心靈和誠實與他聯合，在我們和神的中間不可有虛偽存在。人在人的面前常有虛偽，心口不一，心中滿懷著詭詐。口裡卻說得動聽；但向神禱告的時候，必須以至誠的心，我們的靈才能和神的靈相聯，神才能聽我們的禱告。

禱告沒有固定的模式，禱告是對神說話，如同我們與朋友說話一樣，我們與人說話，不會有固定的模式，即是要先講什麼、再說什麼；向神禱告，也不用如此。所以，一般在禱告之前，我們會先對上主稱呼，可稱「親愛的主」、「慈愛的天父」等等。而在禱告的結束要說「奉耶穌的名禱告，阿們！」，全世界有各樣宗教不同的禱告，但神只垂聽「奉耶穌的名」禱告文，意思即是祈求神看在耶穌的份上而垂聽禱告；「阿們」的意思就是「誠心所願」，代表以上的禱告正是來自我內心深處最誠的祈禱。

禱告絕對不是一個形式，而是使人能從新得力的關鍵！受苦的時候，我們就來禱告；喜樂的時候，我們就向神歌頌，無論何時何地，都能享受與神連結的平靜安穩！

只要我們願意開口，無論是有聲或無聲，神都聽得見。不管是感情、工作、課業、家庭、服事……都可以用不灰心的禱告來經歷神蹟。因為我們的神，是垂聽禱告的神！

向神禱告的內容並沒有順序，禱告內容會包括：敬拜、讚美、信靠、祈求、認罪、順服和感恩等等，當我們看見神所創造之物，心中充滿驚嘆與感動，可以對神創造的讚美。而聖經中有許多用詞可以拓展我們對讚美的了解。參照新舊約，查考讚美的含義包括：讚揚、祝福、榮耀、歌頌、尊崇、頌揚、誇耀、歡愛、歌唱，並以神為榮。這些新舊約中的字彙展現了讚美的風貌。在讚美時逐一地默想並用，可以使個人的讚美更豐富、更喜樂。

當我們犯罪而得罪神，或是心中有罪疚感，此時需要認罪，求主赦免。在聖經中的「罪」， 簡單的定義就是「沒有達到上帝的標準」。所以聖經所講的罪，不一定指犯法，被法官審判後，才稱為罪。上帝的標準，比法律上所認定的罪還要高。

耶穌在馬太福音第五章有提到：當你恨一個人，等於是殺了他；當你對婦人有淫念，等於是犯姦淫。「思想」在法律上不算為有罪，因為沒有行為事實，但是對上帝來說，這就是犯罪。人本來就有罪，從始祖亞當就犯了罪、得罪了神，所以，當動機產生了罪的思想，就要來到神的面前求赦免。

而在生活中，我們需要神的帶領，因此我們也需要祈求，禱告就是把我們內心的一切，放在神面前，不論傷痛、憂慮、喜樂、愛慕、讚美、抱怨、軟弱、疑惑毫無保留地、自然地呈現在主前、與祂分享、求祂分擔。除非你向主坦誠，否則你很難去了解主的旨意，讓我們藉著禱告學習禱告。

我們要如何跟神禱告？是用站著、坐著、跪著、或屈身禱告，哪種方式最好？我們的手應該向神張開、合攏還是高舉？我們禱告時眼睛需要閉著嗎？在教堂還是戶外哪裡禱告更好？我們應該在清晨起床後禱告還是夜晚上床前禱告？在我們的禱告中有什麼特定的話要說嗎？我們如何開始禱告？什麼是結束禱告的正確方式？這些問題和其它一些問題都是有關禱告的常見問題。

什麼是禱告的正確方式？上面提到的這些有那麼重要嗎？事實上，禱告的正確方式就是向神表達我們的內心。坐著、站著或跪著；手張開或合攏；眼睛睜著或閉著；在教堂、家中或室外；在清晨或夜晚——這些都是次要問題，取決於個人的喜好、信念和適應情況。神要的禱告是他與我們之間一種真實和個人的關係。所以，神應允我們的禱告並不是基於我們禱告時人在哪裡，身體是什麼姿勢，或禱告時說的順序是什麼。

禱告無關在什麼時間或地點，而是要進入內室之中。內室就是禱告的地方，在那裡只有「主和我」，不受任何人的打擾，我們可以盡情的向神傾心吐意。 我們都明白親近神的美好，也曾感受過那樣的甜蜜，只是在生活中，總會面臨突然湧來的波浪，攪動內心，嚴重的甚至會打亂步調，沮喪的浪潮更會令人快要窒息、快被淹沒，想要放棄…這時更應該要立即禱告，把眼睛閉上，專心思想主，開口向神呼求，藉著禱告，隨時跟神連上線。

** 別讓禱告摧毀你的人生 劉曉亭 2016年10月25日
http://weproclaimhim.com/?p=5147

這是史上最聳動的標題嗎？千萬別這麼想，如果大家知道有多少異端是從「禱告」出來的，有多少人在偏差的禱告中延誤就醫，我們就不敢這麼笑傲江湖了。

確實曾經有人因為迷信禱告不去就醫因而致死，家屬還因此告上法院，怪罪教會。新約教會創辦人江端儀就是禁食禱告後，宣稱得到啟示，因而走向異端。我們當然不能因噎廢食讓信徒對於禱告充滿疑慮，但是也不能忽略關於禱告的教導任憑信徒走向歧途。

說起禱告，其實還蠻極端的，許多基督徒除了簡單的謝飯禱告之外，禱告詞往往撐不過一分鐘，除非別人提供一大堆代禱事項，那就照表操課，禱告等於報告班長，把事情陳述一遍給上帝聽，同時心底暗自懷疑「這些事情上帝不是應該知道嗎？怎麼還要我報告？」

但是另外一些信徒不是禱告到別人一直偷看手錶就是禱告到出神入化。筆者就遇過謝飯禱告長達半小時的神人，真是禱告到地老天荒，大家看著飯菜仰天長嘯，還要拼命說「阿們」，希望對方心滿意足，提早結束，最後卻還是事與願違。

當然也有某些禱告給人神明附身的錯覺，不知情的人會以為對方胡言亂語。於是，信徒只好走進基督教書房去尋找教導禱告的書，只不過，有的書完全是神學教科書，有的書則是教戰手冊，前者不是太理論就是太抽象，不是不知所云就是讀了等於沒讀，後者太操作，幾近施法，把禱告「步驟化」「方法化」，同樣令人不安。

其實耶穌在登山寶訓已經把話說得很清楚，也用主禱文做了範本，無奈我們在濃厚民間信仰以及傳統文化背景下，還是把主禱文當護身符唸咒，並且把禱告當成方法，如此一來，我們的禱告反而可能摧毀我們的人生。

為什麼把禱告講得這麼嚴重？

基督徒都知道，禱告是靈命的呼吸，呼吸跟健康非常直接相關，不熟悉禱告的人就好像呼吸道過敏，連睡覺都困難，這樣的信仰比較像精神寄託，很難經歷信仰的大能。但另一種禱告卻又類似練武功，想要運氣發功，力拔山河，透過禱告進入靈異世界，這也是危險的。

禱告既然是呼吸，我們就要小心吸入廢氣，否則有礙健康。請問大家，您會把生活的焦點放在「呼吸」嗎？「呼吸」到底是手段或是目的呢？您活著就為了呼吸，或是呼吸是為了活著？這是可以輕易地分辨出來的。呼吸新鮮空氣誠然是美好的，但是不會成為您活著的意義。

一個基督徒在禱告中經歷神就好像呼吸到芬多精，尤其靈恩的經驗實在是難以言喻的真實美好，我們因此經常爬山，每週花好幾個小時去吸收芬多精，這絕對是好事，但是別忘了，爬山完還是要做正事。一個人絕對不能把「享受呼吸」當作人生的目標。

你可以把代禱當成一種人生使命，這是可以的，因為聖經也有這種例子，神託付你花大量時間為別人代求，這是一種彼此相愛，但是，若我們活著就是為了在禱告中自己享受神同在，那就很奇怪了。有點兒像一個孩子享受到父母的愛，於是決定不上學，不上班，天天膩在父母身邊享受父母的愛，這絕對是不健康的。

禱告是為了幫助基督徒更認識神，更經歷神的真實，最後的目的是與神同工，承擔責任，完成神的託付，這就是所謂「小事忠心，神要派你管理更大的事」，也是「先求神的國與神的義」。禱告的目的不是為了滿足我們個人的美好感受而是在禱告的成長中成全神的心意。

若是禱告只是讓我們追求神秘經驗，我們就只是吃奶的嬰孩，錯誤的認知會讓我們永遠長不大，耽誤了神美好的旨意，這絕非小事。忽略禱告的重要，只是做禮拜同樣會發育不良，都是照自己的意思做事，出了麻煩才來禱告請上帝收拾善後，也還是屬靈的小孩。成長是需要時間的，禱告也是長時間的操練。

一個基督徒有神的同在就必須開始操練禱告，禱告不是一種方法啟動宇宙神秘力量，禱告是跟天上的父對話，追求的是「願人都尊主為聖，願神的國降臨人間，願神的旨意行在地上如同在天上」，所以禱告是一件非常重要的事，是完成神心意的過程。

但是觀諸身邊的基督徒就會發現禱告的主流似乎早就偏離了聖經教導，禱告主軸還是脫不去個人榮辱與子孫幸福，身體健康與工作財富，最後滿足的還是自己，就算不是摧毀人生也是某種浪費人生。我們不是一個基督教背景的國家，所以用靈驗的角度體驗禱告也是很合理的事，這是一個過程。

明年是改教500週年，或許是不錯的機會讓我們省思整個信仰，我們禱告的方式與邏輯是否受了某些派別或是書籍與路線影響（例如「宣告」被濫用的現象），不自覺偏離了聖經，基督教我們禱告了若干年，究竟有沒有因此更認識上帝，性格更成熟，思想更開闊，人際更親近……這都是值得自我檢視的層面。

基督教也500年了，我們對世界的影響力愈來愈大還是愈來愈小，跟我們對禱告的理解直接相關，值得基督徒深思！

** 禱告怎能被禁止？ 呂紹昌 2016年7月15日
http://weproclaimhim.com/?p=3993

禱告，有很強的內聚性。在教會中，能一起禱告的團隊，才能有效持久；不禱告，卻有很強的排他性。吵架的夫妻，就是無法一起禱告。公立學校該有禱告與否，就讓美國社會有些壁壘分明。然而，無論贊成或反對禱告的人，都認定禱告有不可忽略的重要性。

頗令人意外的，英國最近為了禱告與教會的事，產生了不大不小的風波。為了迎接聖誕節，英國聖公會製作了一支僅56秒的廣告片「只要禱告」（Just Pray），語音內容是馬太福音第六章的主禱文。最先出場的是英國聖公會最高領袖坎特伯利主教韋爾比牧師（Rev. Justin Welby），抬頭望天，旁白配「我們在天上的父」。接著有各行各業不同膚色族群的人物：一位難民，一位練舉重者，一位農夫，一對新婚夫婦、一受洗者與會眾、一福音詩班小孩等等，各人說出部分經文，串成完整的主禱文，沒有其他多餘的字句。最後，所有人物連續以「阿們」結束。

https://youtu.be/vlUXh4mx4gI

此主禱文廣告短片，是為英國聖公會的新網站justpray.uk作宣傳，鼓勵民眾多禱告，原本預定在2015年聖誕節前一週的12月18日開始，作為《星際大戰七部曲：原力覺醒》播映前的廣告。一切審核許可就緒。廣告供應商DCM（Digital Cinema Media）卻於11月22日決定禁播該廣告片，理由是廣告內容涉及基督教信仰，恐怕對其他信仰的觀眾造成冒犯。英國一片譁然。

我所關心的是，若鼓勵禱告的付費廣告片被禁播了，或者鼓勵禱告的信息被當成了耳邊風，之後呢？
表達信仰的自由

聖公會是英國國教，但在無神論文化與氛圍不斷抬頭的當今大環境中，DCM公司竟敢禁播一個花大筆金錢在電影院中播放鼓勵禱告的廣告。當然，DCM公司是有說詞的，而且相當政治正確：因為擔心「對其他信仰、政治派別或無信仰的觀眾造成不敬」。真不知道DCM的反對到底是伊於胡底。英國DCM當然不是省油的燈，是個頂尖的廣告公司，市值超過170億英鎊，控制了全英國80％的連鎖戲院廣告業務，有不少名流士紳與自命自由開放之士為之擔任馬前卒與喉舌後盾。

當主禱文廣告片被禁播後，立時招來不少批評撻伐，各方不斷給壓力，期待DCM收回成命。首相卡梅倫評論對主禱文廣告禁播事件是「荒謬的」。倫敦市長強生認為禁播不合情理，甚至譴責此做法「不像話」。他認為主禱文已經融入英國人民生活2000年了。半官方的「平等人權委員會」甚至認為表達信仰的自由是「英國的必要價值」，沒任何法律禁止基督教機構藉著廣告來傳播信仰。

然而，最有意思的評論卻是來自一位無神論者，牛津大學終身榮譽教授，名氣響亮的理查‧道金（Richard Dawkins）。他也認為禁播理由很荒謬，而竭力支持主禱文影片放映。但他的理由其實是很有趣的。道金說：「若任何人會因為諸如禱告這麼繁瑣的事而被『冒犯』，那他們是配得被冒犯。」因為他根本不認為禱告有任何作用。他當然是錯得離譜而不自知，但他既然堅持言論自由，我自然由他胡言無妨。

英國聖公會在表達震驚、失望、困惑之餘，也考慮訴諸英國「平等法」以討回公道。我們當然要爭取表達信仰的自由，但重點並不在於人權自由與平等，那無非只是人本，關鍵在於如何運用神所賜給我們內在外在的自由，傳揚屬神的信息。
反轉文化的使命

在眾多回應中，英國聖公會薛菲爾教區主教克勞夫特（Rev. Steven Croft）的文章〈禁播主禱文的七個理由〉，最能振聾發聵。他就主禱文的信息與神學作深入的反思，認為主禱文與世俗世界的價值觀點並不相容，因此斷言這「主禱文」影片必然會被戲院拒絕。此文極有洞見，值得深思，略述如下：

1.「我們在天上的父，願人都尊你的名為聖」：首先，主禱文賜給禱告者一個身分認同，知道自己在這世界上的位分，並構成反轉主流文化的社群，破除我們生命毫無目的、無人關心，支離破碎的迷思。

2.「願你的國降臨；願你的旨意行在地上，如同行在天上」：給我們勇氣，得以在不完美的世界中生活。世界無常無望，但神作工，將這世界贖回與更新，建立神的國，邀請我們不因恐懼痛苦而後退，麻痺自己或沉迷，反而要逆流向上，為見公平與和平終將得勝。

3.「我們日用的飲食，今日賜給我們」：此句最強而有力，教導我們，一切夠用就好，不再要更多，要知足。這是顛覆性的美德，這也正是戲院禁播影片最厲害的原因。主禱文攔阻我們貪婪，而戲院中其他的廣告，多是鼓勵我們多多消費，購買快樂。

4.「免我們的債」：教導我們與自己和別人的不完美共存。我們生命中有罪惡，但神有解決之道。消費文化對快樂有許多虛謊的承諾。每日，主禱文承認人的不完美與罪孽，但賞賜非金錢能買的赦免。那是恩賜與恩典，顛覆一切廣告文化。

5.「如同我們免了人的債」：提供我們和解之道。我們受造並非要爭鬥、仇視或爭競，而是要饒恕與被饒恕，彼此和解。最寶貴的人際關係來自於和解與饒恕。

6.「不叫我們遇見試探；救我們脫離兇惡」：主禱文建立我們靈裡的活力。主禱文提醒我們並非活在童話世界，其實是在預備晦暗的日子，面對真實的暴力、疾病與艱難，但確信神的愛與美善將帶領我們經死蔭幽谷與青青草地。

7.「因為國度、權柄、榮耀，全是你的，直到永遠。阿們！」：主禱文告訴我們，信徒的生命將如何結局。禱告文回到開始的敬畏尊崇神，那應當是人的起點，也是人之終點。

主禱文蘊含了對神的敬畏，鋪陳了基督徒的身分本色，同時溫和篤定地向世人宣告。主禱文是信徒每一天當思想的功課，是每一天的禱告操練。基督教導的禱告文，怎會不蘊藏能力與祝福？如何能被禁止？
不能被禁的禱告

民間商業機構可以禁止播放主禱文的片子，但不能禁止基督徒的禱告。世上的公司可以禁止播放教會的影片，但無法禁止神的工作。

禱告，是神的工作。對能體會神同在的人而言，工作就是禱告；對能揣摩神心意的人，禱告就是工作。經歷過神的人，必然常常喜樂而禱告。「你們要靠主常常喜樂。我再說，你們要喜樂。當叫眾人知道你們謙讓的心。主已經近了。應當一無掛慮，只要凡事藉著禱告、祈求，和感謝，將你們所要的告訴神。神所賜出人意外的平安，必在基督耶穌裡保守你們的心懷意念。」（腓立比書4章4～7節）

問題是，基督徒喜愛禱告嗎？真正令人擔憂的，並非世界禁止基督徒在某些公開場合的禱告權利，而是基督徒是否喜歡禱告嗎？面對艱難黑夜，期待主臨的榮耀，信徒其實更應當儆醒禱告。「耶路撒冷阿！我在你城上設立守望的，他們晝夜必不靜默。呼籲耶和華的，你們不要歇息，也不要使他歇息，直等他建立耶路撒冷，使耶路撒冷在地上成為可讚美的。」（以賽亞書62章6～7節）

禱告既全然是屬於神與信徒之間的盟約，有什麼人事物與環境可以禁止我們向神傾心吐意？

主禱文影片可被禁播，但禱告必得釋放。

** 因著信，啟動關鍵禱告 黃銀成 2016年8月28日
http://weproclaimhim.com/?p=4427

記得我剛到教會服事的時候，當時沒有週間的禱告會，只有主日聚會前的短暫禱告，那時，只利用聚會前半小時間空檔來禱告，非但禱告品質不好，又易流於形式。於是我們開始了禱告會，就在每個週三晚上，直到如今，從沒有間斷過；通常，禱告會是教會最穩定聚會之一，每週固定獻上最深、最美的禱告。

我們要去思考：「為什麼我們會在這個地方禱告？」是因為教會的規定？是因為有許多的需要？是因為教會的事工之一？我們何以在每週晚上禱告會中，一同聚集並向神禱告？因為相信神！這是一個重要的核心價值，藉著對神的信心，而啟動上帝的作為。

信心在基督信仰中，是佔極重要的地位，然而信心也是今天人類最大的問題，從聖經創世記一直到啟示錄，都是在討論這個問題：信心！人都在信心中作選擇，以色列人何以在曠野路上抱怨神？北國何以遠離神，而去敬拜假神？挪亞時代的人們，何以嘲笑挪亞？因為「信心」出了問題！

在今日這個時代為何有人會敵對神？為何有人來了教會之後又離開？為何有人在教會不冷不熱？因為信心的問題。

我們相信：「上帝垂聽每個禱告」，但可惜的是，今天也有些基督徒把禱告視為抽獎般，如果上帝應允了，如同中了大獎般；若不是自己所期待的，就以「銘謝惠顧」代之。我們知道中獎的機會，常是非常渺小，但是，禱告不像是抽獎，什麼禱告是上帝必然垂聽？就是信心的禱告。

在整個希伯來書11章中，不斷提到一個關鍵詞：「因著信」，作者例舉舊約許多人物，像是亞伯、以諾、挪亞、亞伯拉罕、撒拉、以撒、雅各、約瑟、摩西……等人的見證，都是因著信，希伯來書的作者更說：「人非有信，就不能得神的喜悅；因為到神面前來的人必須信有神，且信他賞賜那尋求他的人。」（希伯來書11章6節）原來，來到主面前的前題，就是需要「信」。

在香港有首詩歌就叫做〈因著信〉，歌詞就取自希伯來書11章，裡面歌詞提到：

「憑信，他離別吾珥；因信，全然奉上愛子；憑信，還有人全力抓住天使，贏到祝福、換了名字；憑信，他行近紅海；因信，連潮浪也分開；憑信，曾有人被困於獅子坑內，仍敬拜上帝，發誓至死不改！在某天他下決心圍繞在城外，憑信放聲呼喊，城牆便倒塌下來；又有先知被擄他方常在心裡靜待，仍確信上帝榮耀會回來！憑信，我們懷著憑據；因信，同尋著了應許；憑信，能夠發現在世間只是寄居，朝更美家鄉走回去！」

如果說，耶穌基督的救贖是使我們恢復我們與上主的關係；那麼，信心就是我們回應這個救贖計畫的表現。

南北韓戰爭的時候，北韓軍隊大規模南下，兩個月之間南韓只只剩下釜山一帶的土地，那時是8月雨季，天氣不定，常常下雨，當時南韓總統李承晚在釜山聚集所有難民中的傳道人，邀請他們到他的家中，口氣很沉重的請求：「你們禱告吧！現在南韓軍力已經無法抵抗北韓共軍，連這塊最後基地，隨時都有可能被共軍攻下，我已撥電話請求正在日本的麥克阿瑟將軍領軍前來援助我們。他答應派B29轟炸機到敵區作地毯式轟炸。但雨若是不停，天上厚雲未散去，轟炸機就無法順利進行任務。目前是韓國存亡的時刻，我想唯只有上帝能幫助我們。各位，禱告吧！懇求上帝止住這雨水，並施行拯救。」

聽見這個話的傳道人，就聚集在一處，同心迫切禁食禱告10天。奇妙的事發生了，從那日以後，一滴雨水都不再落下，竟然在雨季出現好天氣，天空全是B29轟炸機，幾天之內共軍被炸得落花流水，接著麥克阿瑟將軍登陸仁川，南韓最終反敗為勝。

禱告很重要，但是還要加上信心，否則，禱告就變得很空洞。就好像煮菜對味，因為調味得好，而信心就是讓禱告對味。

耶穌曾教導我們那些錯誤的禱告，在馬太福音6章中，有些禱告是作白工：「你們禱告的時候，不可像那假冒為善的人，愛站在會堂裡和十字路口上禱告，故意叫人看見。我實在告訴你們，他們已經得了他們的賞賜。你禱告的時候，要進你的內屋，關上門，禱告你在暗中的父；你父在暗中察看，必然報答你。你們禱告，不可像外邦人，用許多重複話，他們以為話多了必蒙垂聽。你們不可效法他們；因為你們沒有祈求以先，你們所需用的，你們的父早已知道了。」（馬太福音6章5～8節）

在此，耶穌指出幾種錯誤的禱告：過度使用重復的形式化、儀文化、規定化、沉長化、表面化等等，這些是我們要避免的，反倒是要用「心靈」和「誠實」來敬拜祂。

為此，我們的禱告就要是信心的禱告！因著信，神使你的難處解決；因著信，讓你更多被主的愛摸著！
