* 提摩太前後書
** p156
給我們的靈不使我們膽怯；相反地，他的靈會使我們充滿力量，愛心和自制。」當保羅和提摩太領受聖職的時候，他們便接受了從天而來屬靈的供養，使他們的靈魂得著力量、愛和自制。
** 提摩太爲耶穌基督所做的見證(一章8-10節)
因爲提摩太已經接受了上帝所賜的力量，他便放膽宣揚福音。他不以爲耶穌基督做見證爲恥，也不會因保羅是個囚犯而以他爲恥。這是第一次我們得知保羅的處境。他正在爲他的信仰受苦，而提摩太也必隨時預備與他一起爲福音分擔苦。

此處所提及的福音及上帝的能力是基督福音一個簡要的概覽。上帝已經「拯救我們，呼召我們作他的子民，並不是因爲我們有什麼好行爲，而是出於他的旨意和恩典。他在萬世以前就藉著基督耶穌把這恩典賜給了我們。」保羅強烈地主張救恩最根本的基礎在於上帝的心意，祂要透過基督的救贖工作，爲祂自己拯救祂的百姓。因爲保羅在教牧書信強調好行爲的重要性，第9節的經文就更值得留意。上述保羅的話，與提多書三章5節相同，都指出單靠好行爲來做我們渴望救恩的基礎是行不通的。正如保羅所說，救贖是單單藉著信心、單單靠著恩典，單單榮耀上帝。這救贖最根本的奧祕是上帝的心意，一種自由卻又負責任的心意。

福音的根本在於上帝決定透過耶穌基督拯救世人。直到救主耶穌基督的出現，上帝永恆的救贖旨意，才完全地向我們顯明出來。耶穌的工作在下列經文中有如此的簡要說明：「基督已經毀滅了死亡的權勢，更藉著福音把不朽的生命彰顯出來。」當然耶穌並沒有廢除肉體的死亡。在耶穌來到世上之前和之後，所有人的生命都只有走向死亡一途。但耶穌戰勝了死亡。祂死了並且在第三天復活。祂爲上帝所應許的死後復活的生命做見證。耶穌告訴門徒，說祂離去是要爲他們預備地方，祂必再回來接他們到祂那裡去，他們必定與祂同在一個地方(約翰福音十四章3節)。耶穌消除了門徒對死亡的恐懼，並且提供一個確定的盼望，就是他們都將進入天國的家。如此，祂藉著福音，將「不朽的生命」顯明出來。藉著耶穌的工作，在上帝神聖的啓示裡，顯明了生命不朽的盼望。所以，在福音的信息中指出，人被呼召，一同來分享上帝永恆的救恩。

** p160
守聖靈所託付給他的真理的想法相符。提摩太之所以能夠傳揚福音的真理給當時的人們，是因爲聖靈內住所賜予他能力的緣故。
** 稱讚阿尼色弗(一章15-18節)
在這封勉勵提摩太的書信中，插入了兩段保羅個人的回想。第一段是一個很不愉快的回憶，第二段則是他對另一個陌生人深深地致敬。提摩太此時已經聽說，在亞細亞已經有一些基督徒背棄了保羅。這件事可能起因於那些當時在保羅接受審判時支持他的人，最後卻都失敗了。這封信在此提及當時羅馬緊張的情勢之一，對當時的人們而言，認同保羅及他所做的工作都是一件危險的事。保羅提到兩個背棄他的人的名字，保羅在以弗所認識他們，所以特別提起他們的名字：腓吉路和黑摩其尼。

面對許多人的失敗與叛離，阿尼色弗所表現的忠誠顯得令人激賞。他和他的家人都住在以弗所。提摩太也熟知他在教會中服事的擺上。不知什麼原因，阿尼色弗也來到了羅馬，在那裡他遍尋所有監獄中的囚犯，直到他找到了保羅。在當時這是相當不容易，因爲保羅可能被嚴密地看管著。但阿尼色弗找到了他，並且多次前往探望。阿尼色弗並不畏於認可這位已被判刑、且被法律禁止之宗教的領袖所帶來的危機。他的探訪對保羅的幫助非常大，他爲這位孤寂的階下囚提振精神，同時也爲這位偉大使徒的心靈帶來力量。保羅祈求主能夠憐憫阿尼色弗一家人，也祈求主在審判的那日憐憫他這個朋友。在這封信的最後，保羅還向阿尼色弗一家人問安(四章19節)。有些聖經註釋者認爲，保羅寫這封信時，他的這些話暗示著阿尼色弗已然過世。所以，保羅才會爲了一個已經過世的人祈求上帝。另外還有一個更有可能的假設就是，阿尼色弗不在以弗所的家中而遠離在外。



* 信實的基督徒牧者_提後二章
** 一個有紀律的福音牧師(11章1-7節)
面對亞細亞基督徒的背棄，以及阿尼色弗的忠心耿耿，保羅更加鼓勵提摩太必須在德行上及屬靈的能力上剛強起來。第2節保羅又回到他對信仰傳承純正性的關懷。在此保羅所指的，當然是福音信息的內容。提摩太已經從保羅及其他見證人領受了這信息，現在輪到提摩太去傳遞他所領受的基督信仰。當然，這必定是「相同的」信仰，絕不是一個更改過的版本。他要把這信仰傳遞給那些在信心上完全，且有能力能夠教導別人的人。保羅如此寫道，因他完全信賴提摩太，及那些被提摩太所教導的人，這些人要傳遞信仰給下一代，使他們對基督信仰有一個更全備的認識。此外，保羅所寫那些偉大的書信，以及在福音書中所保留，初代教會爲主所做的見證，當時都已經被蒐集和記錄下來。因此，那時才會有一本現成的文字資料，成爲基督徒在傳道及教導時的標準規範和材料。

在此保羅表達一個比較急迫的主題，就是他對屬靈的兒子提摩太的關心，期勉他能勝任基督教牧師的工作，並且憑著信心面對迫害的日子。因著這一份關心保羅鼓勵提摩太與他一同分擔苦難，如同一個「基督耶穌忠勇的戰士」。保羅並不是禁慾的苦行者，也不是要求自我折磨、懲罰等精神上的苦行者。但他真心期盼一個基督教牧師應該如同一個基督耶穌訓練有素的戰士，隨時準備忍受困難保羅以三個例子來說明他的想法。首先他舉士兵的例子。一個好的士兵不能被營外的私慾纏擾，他必須完全服從那召他入伍的人命令。一個基督的士兵更是不能被今世的俗務所纏擾，如此他便無法完全順服耶穌做他的主。第二個例證提到了一個運動員的訓練與紀律。沒有一個人可以不經過紀律和訓練而獲得運動競賽的冠軍。一個想要勝任自己所有責任和工作的基督教牧師，就必須學著去約束自己第三個例子是，一個了解勞力是豐收的必要因素，而辛勤工作的農夫。因此，一個牧師的紀律同樣地表達在他宣揚福音時，隨時準備忍受肉體勞苦的態度。這也反應出一個牧師在心理上及精神上的訓練，而且這是牧師生活中，最重要的一部分。有時牧師必須預備心面對不受歡迎的情形，甚至也必須面對因對上主的忠心而帶來的迫害。

** 至死信實(二章8-13節)
保羅在羅馬書開始的幾節經文中(羅馬書一章354節)，是他整篇信息的濃縮，這也可幫助我們來了解提摩太後書11章9節。經歷了死而復活，耶穌宣稱祂帶著能力，是上帝的兒子。從大衛以來，耶穌的祖先都有肉體，然而耶穌全然的神性與人性卻是一個新的象徵。保羅所宣講的福音就是爲了見證耶穌爲神人(God-man)。事實上，他之所以會陷入牢獄，也就是因爲他爲這位神人、及這關乎全人類生命的真理做見證。這封信裡保羅提到他在監獄裡的遭遇，指出在獄中時，他被看待如同一個危險的罪犯。他寫道他就像一個囚犯遭受捆綁，但他並不是一個被擊退的人。他知道上帝的話不會被捆綁。一個信仰也不會因爲它的領袖被下在監牢中便會毀滅。偉大的理想是不會被腳鐐給銬住的。保羅如此信實地傳揚基督的福音，現在也有人繼續在傳揚，且透過這封從羅馬監獄所寄出的信，保羅自己仍繼續爲耶穌基督做見證。

保羅接受了這個困境,因將它視爲自己被耶穌基督差派之後,傳道經歷的!部分,而且他也深深覺得,在最後的試驗來臨之時,他也不會膽怯、猶豫。他現在所忍受的,是「爲了上帝所揀選的子民忍受這一切,好使他們也能得到那從基督耶穌來的拯救和永恆的榮耀。」「被選出的子民」(theelect),較好的翻譯是「被揀選的子民」(thechosen)。所以,如果保羅一直持守他的信心直到生命的末了那些跟隨他的人,就能因他的模範而得到支持與認可。試想,假如這位向外邦人宣揚福音的偉大使徒,在他遭受迫害的時候否認了他的主,誰能臆測他在所有基督徒當中所造成的傷害呢?保羅對於自己忍受苦難的了解及其重要意義,爲後來的人預備了一個方向當早期基督徒在面臨殉道的時候,都會引用保羅所說的話,成爲他們讚美詩的!部分,來激勵自己。這是一段值得我們擺上信心的一段話

如果我們已經跟祂同死，
我們就會跟祂同活。
如果我們忍耐到底，
我們就會跟祂一同掌權。
如果我們不承認祂，
祂也不會承認我們。
如果我們失信，
祂依然信實可靠，
因為祂不違背自己。

第一句表達了那些爲基督而死，也將與祂同活的人的信心。因著這般信心早期基督徒面對死亡時，並不恐懼。第二句則是對忍耐到底這項功課的呼召。在此，這些動詞的時態相當地耐人尋味。接在「如果我們已經跟他同死」之後的句子，在希臘文的時態中是一個單一的動作。而在「如果我們忍耐到底」這幾個字之後，所用的時態卻是一個連續性的動作。事實上，有時爲基督而死，比活著卻不斷地面對迫害還來得容易呢!早期的基督徒都相信那與基督一同忍耐到底的，將來也必與祂一同掌權。而第三句的動詞用的卻是未來式。本句應當翻譯成:「假如我們要否認他。」它似乎暗示著基督不太可能被祂的信徒所棄絕。第三句是一個嚴正的警告，但它並不會比耶穌在馬太福音十章13節的警告來得更嚴厲。假如我們在人面前不承認耶穌的話，將來在天國，祂也會在父前不承認我們。所以當我們鼓勵人要有信心，且對那些忍耐到底的人承諾有永生，我們就免不了想知道，那些無法忍耐的人最後的遭遇將會如何?第三句提供我們一個嚴正且必要的警告，第四句卻是一個充滿希望的信息。當然，如果要把第四句翻譯成比第三句更嚴厲的警惕也是可以的。它說明了基督必忠實遵守賞罰的標準及要求。整本聖經最偉大的主題就是上帝的信實，雖然人背棄了祂。然而可以確信的是，並不是我們每一顆搖擺不定的信心，都會被我們的上主以嚴厲的審判加以否認和拒絕。記得保羅寫給帖撒羅尼迦教會的話「但是，主是信實的；也會使你們堅強，使你們不受那邪惡者的侵害。」(帖撒羅尼迦後書三章3節)假如我們對基督充滿信心的話，我們就能坦然無懼地面對那聿官11試驗的日子。當我們想起保羅，就想到他時常回想耶穌道成肉身時所表達出來的關懷與愛心，我們就能明瞭上帝的信實其實就是一個希望的表達。





