* 提摩太前後書
** p156
給我們的靈不使我們膽怯；相反地，他的靈會使我們充滿力量，愛心和自制。」當保羅和提摩太領受聖職的時候，他們便接受了從天而來屬靈的供養，使他們的靈魂得著力量、愛和自制。
** 提摩太爲耶穌基督所做的見證(一章8-10節)
因爲提摩太已經接受了上帝所賜的力量，他便放膽宣揚福音。他不以爲耶穌基督做見證爲恥，也不會因保羅是個囚犯而以他爲恥。這是第一次我們得知保羅的處境。他正在爲他的信仰受苦，而提摩太也必隨時預備與他一起爲福音分擔苦。

此處所提及的福音及上帝的能力是基督福音一個簡要的概覽。上帝已經「拯救我們，呼召我們作他的子民，並不是因爲我們有什麼好行爲，而是出於他的旨意和恩典。他在萬世以前就藉著基督耶穌把這恩典賜給了我們。」保羅強烈地主張救恩最根本的基礎在於上帝的心意，祂要透過基督的救贖工作，爲祂自己拯救祂的百姓。因爲保羅在教牧書信強調好行爲的重要性，第9節的經文就更值得留意。上述保羅的話，與提多書三章5節相同，都指出單靠好行爲來做我們渴望救恩的基礎是行不通的。正如保羅所說，救贖是單單藉著信心、單單靠著恩典，單單榮耀上帝。這救贖最根本的奧祕是上帝的心意，一種自由卻又負責任的心意。

福音的根本在於上帝決定透過耶穌基督拯救世人。直到救主耶穌基督的出現，上帝永恆的救贖旨意，才完全地向我們顯明出來。耶穌的工作在下列經文中有如此的簡要說明：「基督已經毀滅了死亡的權勢，更藉著福音把不朽的生命彰顯出來。」當然耶穌並沒有廢除肉體的死亡。在耶穌來到世上之前和之後，所有人的生命都只有走向死亡一途。但耶穌戰勝了死亡。祂死了並且在第三天復活。祂爲上帝所應許的死後復活的生命做見證。耶穌告訴門徒，說祂離去是要爲他們預備地方，祂必再回來接他們到祂那裡去，他們必定與祂同在一個地方(約翰福音十四章3節) 。耶穌消除了門徒對死亡的恐懼，並且提供一個確定的盼望，就是他們都將進入天國的家。如此，祂藉著福音，將「不朽的生命」顯明出來。藉著耶穌的工作，在上帝神聖的啓示裡，顯明了生命不朽的盼望。所以，在福音的信息中指出，人被呼召，一同來分享上帝永恆的救恩。

** p160
守聖靈所託付給他的真理的想法相符。提摩太之所以能夠傳揚福音的真理給當時的人們，是因爲聖靈內住所賜予他能力的緣故。
** 稱讚阿尼色弗(一章15-18節)
在這封勉勵提摩太的書信中，插入了兩段保羅個人的回想。第一段是一個很不愉快的回憶，第二段則是他對另一個陌生人深深地致敬。提摩太此時已經聽說，在亞細亞已經有一些基督徒背棄了保羅。這件事可能起因於那些當時在保羅接受審判時支持他的人，最後卻都失敗了。這封信在此提及當時羅馬緊張的情勢之一，對當時的人們而言，認同保羅及他所做的工作都是一件危險的事。保羅提到兩個背棄他的人的名字，保羅在以弗所認識他們，所以特別提起他們的名字：腓吉路和黑摩其尼。

面對許多人的失敗與叛離，阿尼色弗所表現的忠誠顯得令人激賞。他和他的家人都住在以弗所。提摩太也熟知他在教會中服事的擺上。不知什麼原因，阿尼色弗也來到了羅馬，在那裡他遍尋所有監獄中的囚犯，直到他找到了保羅。在當時這是相當不容易，因爲保羅可能被嚴密地看管著。但阿尼色弗找到了他，並且多次前往探望。阿尼色弗並不畏於認可這位已被判刑、且被法律禁止之宗教的領袖所帶來的危機。他的探訪對保羅的幫助非常大，他爲這位孤寂的階下囚提振精神，同時也爲這位偉大使徒的心靈帶來力量。保羅祈求主能夠憐憫阿尼色弗一家人，也祈求主在審判的那日憐憫他這個朋友。在這封信的最後，保羅還向阿尼色弗一家人問安(四章19節) 。有些聖經註釋者認爲，保羅寫這封信時，他的這些話暗示著阿尼色弗已然過世。所以，保羅才會爲了一個已經過世的人祈求上帝。另外還有一個更有可能的假設就是，阿尼色弗不在以弗所的家中而遠離在外。

