* 提摩太前後書
的結論。學習聖經的目的切不可自私；不要單爲自己靈魂的好處着想。人的悔改若只叫他思念自己的得救，而不理其它，這種悔改就不眞確！人必須學習聖經，使他自己對上帝和別人有益處。人若沒有火熱的心去拯救別人的話，這人還未算得救。 
** 保羅囑咐的原因p242
*** 提摩太後書四章一至五節
　　我在上帝面前，並在將來審判活人死人的基督耶穌面前，憑着祂的顯現和祂的國度囑咐你，務要傳道，無論得時不得時，總要專心，並用百般的忍耐，各樣的教訓，責備人，警戒人，勸勉人。因爲時候要到，人必厭煩純正的道理，耳朶發癢，就隨從自己的情慾，增添好些師傅；並且掩耳不聽眞道，偏向荒渺的言語。你卻要凡事謹愼，忍受苦難，作傳道的工夫，盡你的職分。
*** 解釋
　　當保羅結束這封信的時候，他希望鼓勵提摩太並要他注意他的傳道工作。爲要達到這個目的，保羅提示他有關耶穌的三件事。
(一)耶穌審判活人和死人。到了那一天，提摩太的工作將會被考驗；考驗的人就是耶穌自己而不是別人。基督徒的工作必須盡力而爲，照他所能獻給基督的去做，毋需理睬人的批評和看法。他渴望得到的一件事就是耶穌基督將來的一句話：『好，你這又良善又忠心的僕人！」倘若我們都以這種態度去工作，其差別必然難以估計。因爲它可以使我們不至因別人批評而容易生氣；不至自視過高只顧個人的權益和名望地位；使我們不至養成以自我爲中心的意念，凡事要求別人向自己致謝稱讚；甚至可以使我們不會因別人忘恩負義而傷亡。
(二)耶穌是一位再來的得勝者。保羅說：『我憑着祂的顯現囑咐你。』這個希臘字是epiphaneia。Eiphaneia有兩種特別的用法。它可以指神祇的顯聖干預；它也特別用在與羅馬皇帝有關方面。他的登基可以稱爲他的epiphaneia；另外特別的一點---保羅在這裏構思的背景---用作皇帝駕臨一城或一省。很顯明的，當皇帝準備駕臨一地之前，每一件事都必須安排妥當。街道打掃淸潔，佈置美麗，一切皆要準備就緒，務求配合皇帝的Epiphaneia。所以保羅對提摩太說：『你知道當一個城市恭候皇帝的epiphaneia的時候，會發生甚麼事；你同樣期待耶穌基督的epiphaneia，你也要照那樣做好你的工作，當他顯現的時候，好使一切的事皆已備妥。」基督徒必須那樣準備好自己的生活，能隨時迎見基督的再來。
(三)耶穌是王。保羅勸提摩太藉着記念耶穌基督的國度而行事爲人。到了那日，地上的國將變成主的國度，因此，保羅對提摩太說：『所以你要生活和工作，到天國降臨的時候，你會在天國公民的行列中，列在高位。』
　　我們的工作，必須叫我們能受得住基督的嚴格考驗。我們的生活也要如此，好迎接王的顯現。我們事奉要能表現出我們是上帝國度的公民的實質。
** 基督徒的責任p244
*** 提摩太後書四章一至五節(續)
　　在新約中，描述基督徒教師的責任的經文，很少像這段那麼淸晰。
　　基督徒教師要，心裏迫切。他所傳授的信息，實際上是關乎人的生死問題。眞正能使學生接受他信息的敎師，必須有熱忱的語調。司布眞(Spurgeon)對馬田里奧(Martineau)非常欽佩。然而馬田里奧是個信仰神體一位論者(unitarian)，不相信耶穌基督的神性；而司布眞則熱烈維護那信仰。有人問司氏：『你既不相信他所講的道，你怎可以欽佩他?』司布眞說：『是的，但我相信他的行事爲人。」人若能用聲音表達迫切的要求，別人必然會恭聽的。
　　基督徒敎師要堅持不變。『無論得時不得時』，總要竭力勸人聽基督的話。有人說：『要把握機會，製造機會。』正如木士庇底亞的狄奧多尼(Theodore of Mospeuestia)所說：『基督徒必須把每一次都當作爲基督發言的機會。』有人談到格拉斯哥威靈頓敎會(Wellington Church of Glasgow)的牧師喬治·摩禮遜(George Morrison)說：『無論他與人開頭談甚麼，他總是言歸正傳的談到基督。』這是叫我們不擇時間去談道的意思。因爲傳福音和人類的其他接觸一樣，必須有禮貌；它的意思乃是指我們可能過於害怕，以致不敢向別人講述耶穌基督。 
　　保羅繼續說出基督徒的見證必須産生的效果。
　　他必須責備人。他必須使罪人覺察自己的罪。華特.巴其亥(Walter Bagehot)曾說：『在達到完全的路上有一連串的討厭之事。』我們必須想盡方法使罪人覺得自己的罪是可厭惡的。伊比克德(Epictetus)將僞哲學家和眞哲學家作一個對比；前者只顧沽名釣譽，後者的目的是爲聽衆的好處而設想。僞哲學家只會阿諛奉承，爭取自我的尊敬；但眞哲學家則說：『你們來，我會指出你們的方法是不妥當的。』他說：『哲學家的講課如同一個外科醫生；當你離開的時候，你不會感覺快樂，只會覺得痛苦。』雅典有一位寵壞了的才子亞基表德(Alcibiades)，他經常對蘇格拉底說：『我憎惡你，因爲每逢看見你時，你使我認識自己。』基督徒敎師的第一個要素就是要迫使人看清他自己的眞相。
　　他必須責備人。在教會的偉大時代，他宣講之中有毫不畏懼的聲音，因這個緣故有大事發生。勃朗(E. F. Brown)把發生在印度的一件事告訴我們。在加爾各答(Calcutta)的總督府內有一個貴族少年，他因淫佚行爲而聲名狠藉。威爾遜會督(Bishop Wilson)有一天穿着主敎袍前往總督府，對總督說：『總督大人，我奉主名說，倘若那靑年到下主日還不離開加爾各答，我會在主教堂的講台上當衆斥責他。』結果，還未到下主日，那個惡少年便離開了。
　　米蘭(Milan)的安波羅修(Ambrose)是早期教會的一位顯赫人物。他是當時的皇帝狄奥多西二世(Theodosius)非常要好的一位朋友。狄奧多西雖是基督徒，但脾氣非常暴躁。安波羅斯在向皇帝講眞理的事上從不猶疑。他說：『倘若神父不敢道出眞理，還有誰敢說出眞理呢？』狄奧多西委任他的一位密友波大烈(Botherich)出任帖撒羅尼迦總督。波大烈是個好總督；但有一次，把一個行爲不檢的著名戰車駕駛好手囚禁。當時人們對這好手愛戴到難以置信的地步，因而起了暴動，並且謀害了波大烈。狄奧多西怒不可遏。安波羅修勸皇帝必須按情節分別懲罰；但國務卿魯芬羅(Rufinus)故意挑撥皇帝的怒火。結果狄奥多西爲了代友報仇，下令揮軍大屠殺。稍後他便想收回成命，但可惜遲一步抵達帖撒羅尼迦。當時劇場擠滿羣衆，而且門都關閉。軍隊衝進場內，不論男女老少，肆意殺戮。經過三小時的大屠殺，超過七千人遇難。這大屠殺的消息傳回米蘭，到了下主日當狄奧多西前往守禮拜的時候，安波羅修站在門外不准他進去。雖然皇帝懇求寬恕也無濟於事。過了八個月，狄奧多西再圖前往守禮拜，又遭安波羅修攔阻。最後，皇帝必須俯伏在地而懺悔，然後才獲准與會衆一同守禮拜。當教會在極盛的時候，對斥責人就英勇無懼。
　　在我們人際關係中，一句警告和責備的話常會救一位弟兄不致犯罪而沉淪。但是，正如有人說，說這話的時候，務要以『弟兄矯正弟兄的友愛之心』。說話時必須覺得我們同有罪孽感覺，我們的地位不是作別人的道德法官；但是在必須說的時候，我們向別人提出警告，乃是我們的責任。
　　他必須勸勉人。這是事情的另一面。責備絕不應該使人陷於沮喪之中，使他灰心失望。人不單只須受責備，也須受鼓勵。
　　還有，基督徒的責備，警戒和勸勉的職責，必須用百般的忍耐實行出來。這個希臘字是Makrothumia，它形容一種絕不會被激怒，不會失望，不會認爲任何人是不能得救的人之精神。基督徒因爲對基督有改變人心的大能，有不屈不撓的信仰，所以能耐性的相信人。 
** 愚笨的聽道者
*** 提摩太後書四章一至五節(續)
　　保羅繼續描述愚笨的聽道者。他警告提摩太，當日子來到，人會不聽純正的道理；但對那些能說出隨和與悅耳的話之人，會增添好些師傅。
　　在提摩太的時代，這些教師比比皆是，太誤人了。他們被稱爲智士(sophits)；他們周遊各城，聲稱能教授各種學問而收取酬金。雅典演說家艾素克拉底(Isocrates)說『他們以收費低和應許大吸引學生。』他們願意只收十五至廿英磅便把所謂人生的整套美德敎授學生。他們會教導人作精巧的辯論，並且措詞新穎，直到把理虧的强解成合理的事實。柏拉圖(Plato)痛詆他們說：『他們以虛假的敎育作餌，獵取有錢和有地位的青年，目的就是收費；他們利用科學的修詞方法敎人改善私人的談吐而賺錢，但是他們知道他們的教導是錯的。」
　　屈梭多模(Dio Chrysostom)寫出他們的情形：『你會聽聞許多可憐的智士彼此呼喝詆毀，他們的門徒聽他們召喚，也參加口角；許多著書的作家朗誦他們的低劣散文，詩人則唱出他們所寫的詞章；玩雜技的人則盡展自己的本事；占卜者則講出天下無奇不有的怪事；上萬的修辭學家曲解法律訴訟；還有不少商人推銷他們的商品。』
　　在提摩太時代的人常會被售賣假學問的假教師困擾。他們所定的政策就是替人找出理由去支持他心中想做的事。直到今天，任何敎師若敎人輕看罪，必危害基督教和全人類。
　　爲了和那些錯誤的教訓作對比，保羅把一些責任交代提摩太。他必須凡事謹慎，希臘文是nephein；它的意思是淸醒，不易衝動；好像一個運動員，必須善於控制他們的情慾、食慾和心情。浩德(Hort)說，這個字形容『一種精神狀態，不受任何事物煩擾或變爲錯亂......一切機能都完全受控制，大膽審愼地看一切實情和斟酌一切。』基督徒不會變成狂痴思想的犧牲品；在一個不穩定和常常被視爲瘋狂的世界中，平靜穩定是他的表號。
　　他必須忍受臨到他的一切痛苦。基督教覺得甚麼事情有價値，基督徒應當無怨無尤地爲之付代價。
　　他必須作傳道的工夫。基督徒雖然要做責備人和警戒人的工夫，但主要的工作仍然是傳好信息。倘若他堅持謹守紀律和捨己的生活，他會得到比低價享受更大的人生喜樂。
　　他必須盡他的職分。基督徒應當有唯一的野心，就是做一個對他所屬的教會和生活的社會有用的人。他不願失去的機會不是便宜得到的利益，而是事奉他的上帝，他的教會，和他的鄰舍。 

** 保羅跑盡人生的路程p249
*** 提摩太後書四章六至八節
　　我現在被澆奠，我離世的時候到了。那美好的仗我已經打過了，當跑的路我已經跑盡了，所信的道我已經守住了。從此以後，有公義的冠冕爲我存留，就是按着公義審判的主到了那日要賜給我的，不但賜給我，也賜給凡愛慕祂顯現的人。
*** 解釋
　　對保羅來說，人生的終點已非常接近，而且他自己也知道這件事。當伊拉斯莫斯(Erasmus)年老的時候，他說：『我是一個身經百戰的軍人，我賺得我的退役，餘下的爭戰必須留待年靑的人。」保羅這位老戰士，他要放下他的武器給提摩太接班。
　　在新約中，我們找不到比這裏所描寫更生動的一段經文。
　　保羅說：『我的生命已經抵達必須澆奠的時候。」被澆奠這個希臘字動詞是spendesthai，意即向諸神倒出來當作澆奠。羅馬人每餐皆以一種獻祭作結束；這是指拿起一杯酒將它倒出來(spendesthai)獻給諸神。保羅似乎這樣說：『生命的日子已盡，這是我離開的時候了：我必須把我的生命倒出來，獻給上帝作祭物。」他不是想自己受刑；他所想的是把他自己的生命獻給上帝。自從他悔改以後，他已把一切獻給上帝，他的金錢、學問、時間、精力、敏銳心思，和敬虔的心。現在餘下來的只有自己的生命，這時，他亦樂意捨去。
　　他繼續說：『我離世的時候到了。』希臘文(analusis)用作『離開」是非常生動的詞。因爲它包括多方面，而每一個景像都告訴我們關於離開這個世界的一些情形。
(甲)它用來形容除開套在動物頸上的軛或犂具。死亡對保羅來說就是息勞，放下勞苦工作而安息。正如斯賓塞(Spencer)說：勞動後獲得休息，暴風雨後抵達海港，生命之後死亡，都是可愛的事。 (乙)它可以解作鬆開手銬或腳鐐。死亡對保羅來說就是一種釋放。經過死亡，他住的不再是羅馬的牢獄，而是充滿光榮自由的天庭。
(丙)它可以解作鬆開營帳的繩索。對保羅來說，這是一個拔營起程的時候。他曾橫過小亞西亞和歐洲的許多道路。現在，他要走的是最後最偉大的旅程；他走這條引到上帝那裏去的路。
(丁)它可以用來作鬆開停泊船隻的纜繩。保羅有許多這樣的人生經歷。他的船離開港口，駛進深海。他現在正要啓航，進入最深的大海，渡過死亡的波濤，最後便會抵達那永恆的安全港。
　　因此對基督徒來說，死亡猶如放下重擔而獲得安息；它除去覊絆的事物，使人獲得自由；它叫人拔營起程，前往天上的住處；它除掉把我們捆綁在這個世界的繩索，叫我們啓航駛到上帝的面前。那 麼，誰還會懼怕死亡呢? 

** 打那美好的仗之喜樂p251
*** 提摩太後書四章六至八節(續)
　　保羅以他最擅長運用的生動圖畫再說下去：「那美好的仗我已經打過了；當跑的路我已經跑盡了；所信的道我已經守住了。」看起來他不是用人生三種範疇的不同圖畫，而是從不同比賽中看見一幅圖畫。
(一)『那美好的仗我已經打過了。」譯作『打仗」的希臘字是agon，這是指在比武場中的比賽。當運動員盡了他的最大努力去競賽以後，不論勝負，他心裏都獲得最大的滿足。保羅現在到了生命的盡頭，他知道畢生已經盡了最大的努力爲主作工。當巴栗(Barrie)的母親臨終的時候，他作一個偉大的聲明：『我可以回溯以往，甚至在最小的事情上我都做妥了。』世界上最使人心滿意足的就是知道自己已經盡力而爲。
(二)『當跑的路我已經跑盡了。」開步容易，達到終點卻難。所以生命必須有一種支持力；許多人都缺乏這種力量！有人向一位著名人物提議在他生前應該有人替他寫傳記。但他堅決拒絕，他的理由是：『我親眼看見許多人跑到最後一圈便倒下來。」眞的，人到最後衝刺之前，很容易幹一些愚不可及的事，把光榮的一生的美好記錄盡毀。但保羅聲稱他已跑盡當跑的路。當他抵達目標的時候，心中有一種深深地滿足。
　　全世界最偉大的賽跑可能是馬拉松長途賽，而且昔日馬拉松一役亦可以稱爲世界上最具有決定性的戰事之一。這是希臘人和波斯人的爭戰，倘若波斯人戰勝的話，希臘人的光輝永不會照耀全世界！結果希臘人以寡敵衆，贏得勝利。當戰爭告終，有一個希臘士兵用一日一夜的時間，從戰場奔回雅典，希望報告勝利的消息。他朝向衆官長之處直跑。最後他到了目的地，喘氣說：『各位要歡欣！我們已經打勝了。」正當他說完這句話便倒地而死。但是他已跑盡當跑的路；這樣離開世界是最好不過。
(三)『所信的道我已經守住了。』這句話的解釋可能不止一個意思。倘若我們仍然以運動比賽的背景去看它，我們會得到這樣的解釋。在希臘的偉大運動會中，最著名的就是奧林匹克了。全世界最偉大的運動員都齊集這裏。在比賽前一日，所有參賽者都必須向諸神作嚴謹的宣誓，表示他們已經受超過十個月時間的訓練，並且不會用任何狡詐的手段去取勝。保羅可能這樣說：『我已經守住這些規則，我已依照章則完成了競賽。』人若知道畢生沒有破壞生命競賽所定的榮譽規則，便會死得安樂。
　　但這句話可能還有別的意思。它也是生意上的術語。希臘人常常會說：『我已遵守了合約，我已忠誠履行我的承擔。』倘若保羅按這種方式說的話，他的意思就是說他已經獻身事奉基督，守住對基 督的承諾，而且他從來沒有令他的主失望。此外，它可能有一個意思解作：『我已經守住了我的信仰，我從來沒有失去我的信心和盼望。』照這句話的解釋，保羅就是說他不論甘苦，不論是自由或受囚，不論在海上或陸地遇到任何危險，甚至現在正面對死亡，他從沒有失去對耶穌基督的信靠。
　　保羅繼續說，那冠冕將會爲他存留。在競賽中，最大的獎品就是一個用月桂花編織成的花冠，得勝者獲得這個花冠作加冕。運動員都渴望獲得最大的榮譽。但這個花冠只能存留數天便凋謝了，保羅 知道爲他存留的冠冕是永遠不會枯萎的。
　　這時，保羅從人的看法轉到上帝的判斷。他知道在很短暫的時間內，他便會站在羅馬皇帝的審判台前，而他的受審只會有一個結果。他明白尼祿王的判詞是甚麼；但他亦同時明白上帝的判詞是甚麼。一個虔誠奉獻給基督的生命，對人的判詞會置之不理的。他們即使將他定罪，他也不必理會，他只要能聽他的主說：『好，你這忠心良善的僕人。』他便會心滿意足了。
　　保羅仍有一句要說的話，這個冠冕不單爲他存留，也爲凡期盼這位君王來臨之人。他好似對年靑的提摩太說：『提摩太阿！我的生命已將結束，但我知道我必會獲得我的報酬。倘若你跟從我的腳蹤，到你的終了，你也會得着同樣的信心和同樣的喜樂。』保羅所得的喜樂也是爲那些能打那美好的仗，跑當跑的路，並守住信仰的人存留的。 
